-- The Quillback Scavenger O.C.C., Palladium Fantasy RPG Book 9: The Baalgor Wastelands p.52-53.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-quillback-scavenger-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'quillback-scavenger', 'Quillback Scavenger', 'palladium-fantasy', '---
id: quillback-scavenger
men_of_arms: false
occ_group: optional
xp_table: [0, 1901, 3601, 7201, 14401, 24501, 35001, 45001, 65001, 85001, 115001, 145001, 185001, 250001, 310001]
name: Quillback Scavenger
system: palladium-fantasy
source_book: Palladium Fantasy RPG Book 9: The Baalgor Wastelands p.52-53
category: occ
tags: [beginner]
race_restrictions:
  only: ["quillback"]
  note: "A Quillback occupation: the book prints it inside the Quillback entry as the Quillback Scavenger R.C.C."
skills:
  hand_to_hand: { costs: { expert: 2, martial_arts: 3 } }
  occ_skills:
    - { name: "Detect Ambush", base: 30, per_level: 5, note: "Added by the Scavenger, at the catalog base; the book prints no bonus." }
    - { name: "Detect Concealment", base: 25, per_level: 5, note: "The book''s detect concealment and traps. Added by the Scavenger, at the catalog base; the book prints no bonus." }
    - { name: "Cook", base: 40, per_level: 5, note: "+5% O.C.C. bonus" }
    - { name: "Athletics (general)", base: 0, per_level: 0 }
    - { name: "Language: Native Tongue", base: 98, per_level: 0 }
    - { choose: 2, from: ["Language: Other", "Language: Dragonese"], bonus: 10, note: "Two languages of choice (+10% each). Language: Other is the repeatable row - take it twice for two different languages." }
    - { name: "Wilderness Survival", base: 35, per_level: 5, note: "+5% O.C.C. bonus" }
    - { choose: 2, categories: ["Weapon Proficiencies"], note: "Two of choice." }
    - { name: "Hand to Hand: Basic", base: 0, per_level: 0, note: "May be changed to Hand to Hand: Expert for the cost of two other skills, or Martial Arts for the cost of three." }
  occ_related_skills:
    count: 8
    categories:
      - { name: "Domestic", bonus: 10, note: "+10%" }
      - { name: "Horsemanship", only: ["Horsemanship: General", "Horsemanship: Exotic Animals"] }
      - { name: "Medical", only: ["Brewing", "First Aid", "Holistic Medicine"] }
      - { name: "Physical", except: ["Acrobatics", "Gymnastics", "Wrestling"] }
      - { name: "Rogue", bonus: 2, note: "+2%" }
      - { name: "Science", only: ["Mathematics: Basic", "Mathematics: Advanced"], note: "Mathematics skills only." }
      - { name: "Technical", bonus: 5, note: "+5%" }
      - "Weapon Proficiencies"
      - "Wilderness"
    schedule: [{ level: 3, count: 1 }, { level: 6, count: 1 }, { level: 9, count: 1 }, { level: 12, count: 1 }]
  secondary_skills:
    count: 4
    schedule: [{ level: 2, count: 2 }, { level: 5, count: 2 }, { level: 10, count: 2 }]
restrictions:
  - "No Communications, Espionage or Military related skills: the Vagabond''s restrictions still apply."
  - "Alignment: almost never good. Selfish alignments are the most common."
extraction_notes: |
  - Printed 52-53 (renders p053-p054), inside the Quillback entry: the paragraph opens at the foot of printed 52 and the skill rule is on printed 53.
  - The whole definition is one sentence on printed 53: in skills the Scavenger is identical to the Vagabond Optional O.C.C., except that it has detect ambush and detect concealment and traps as O.C.C. skills, does not have animal husbandry as an O.C.C. skill, and selects eight O.C.C. related skills to start with, Vagabond restrictions still applying. The skills block is therefore the stored vagabond-peasant block (Palladium Fantasy RPG Main Book p.99) with those three changes: two skills added, Animal Husbandry removed, related count 8 where the Vagabond has 6. The Hand to Hand price, the related categories and their bonuses, the later related picks and the secondary skills are the Vagabond''s, unchanged.
  - Detect Ambush and "detect concealment and traps" are printed with no percentage, so each is stored at the catalog base (30 and 25). The catalog row for the second is Detect Concealment.
  - EXPERIENCE: the book contradicts itself. Printed 53 says the Scavenger has "the same experience point requirements as a Thief or a Merchant O.C.C."; printed 215 prints a "Quillback Scavenger R.C.C." column of its own. Stored: the printed-215 column, lower bounds 0, 1901, 3601, 7201, 14401, 24501, 35001, 45001, 65001, 85001, 115001, 145001, 185001, 250001, 310001 (level 15 ends at 375,000). The Thief and Merchant ladder in the Main Book is a different one (1851, 3701, 7401, 13001 ...), so the two statements cannot both hold.
  - occ_group is optional: the class is defined by the Vagabond, which the Main Book files under Optional O.C.C.s. For the same reason men_of_arms is false; the entry prints no S.D.C. of its own, and the Quillback''s racial 15 comes from the race.
  - The entry prints no attribute requirements, no O.C.C. bonuses, no starting money and no equipment line, and says the Scavenger matches the Vagabond "in skills" only. None is stated here: no starting_money and no equipment_starting. The Vagabond''s kit includes clothing and hard leather armor, which a Quillback cannot wear (printed 53).
  - Alignment is a note in the book ("almost never be of a good alignment. Selfish alignments are most common"), which is a tendency rather than a limit; it is a restrictions line and the evil tag is not used.
  - race_restrictions names quillback, the race this R.C.C. is printed under. Printed 215 says 20-25% of Quillbacks are Scavengers.
---

# Quillback Scavenger

## Lore

A Scavenger is a Quillback who makes a living from whatever the Wastelands leave lying about: picking over ruins, camps and battlefields for odds and ends, and talking or running a way out of the trouble that follows. Many attach themselves to passing adventurers or to nomad bands, goblins and orcs included, and the tales that come back make folk heroes of them among their own kind.

Curiosity runs the Scavenger''s life. They act on impulse and are apt to help themselves to whatever interests them without permission.

**Alignment:** Almost never good; selfish alignments are the most common.

**Race:** Quillback only.

## GM Notes

Mechanically this is the Vagabond with a sharper eye: Detect Ambush and Detect Concealment in place of Animal Husbandry, and eight related skills at level one where the Vagabond has six. Everything else about the skill program, including the closed Communications, Espionage and Military categories, is the Vagabond''s.

The book gives two answers on experience. The class paragraph points at the Thief and Merchant table, and the experience page at the back prints a separate Scavenger column; the column is what is stored. The entry gives no money or gear, so starting possessions are the GM''s call, bearing in mind that a Quillback wears no clothing or armor.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'quillback-scavenger');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'quillback-scavenger';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-quillback-scavenger-class.sql');
