-- The Salvage Expert O.C.C., Rifts World Book 7: Underseas p.133-134.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-salvage-expert-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- Stub rows for anything the class references that the catalog lacks.
-- The "STUB" marker is load-bearing: it is how the gear importer later
-- recognises a row as still needing stats.
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('tool-kit-portable', 'Tool Kit Portable', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('tool-kit-large', 'Tool Kit Large', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('acetylene-torch', 'Acetylene Torch', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('duct-tape', 'Duct Tape', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('flashlight-pen', 'Flashlight Pen', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('soldering-goggles', 'Soldering Goggles', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('snorkel-gear', 'Snorkel Gear', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 7: Underseas p.133-134');


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'salvage-expert', 'Salvage Expert', 'rifts', '---
id: salvage-expert
name: Salvage Expert
system: rifts
source_book: Rifts World Book 7: Underseas p.133-134
category: occ
bonuses:
  attribute_minimums: { IQ: 9 }
skills:
  occ_skills:
    - { name: "Mathematics: Basic", base: 65, per_level: 5, note: "Printed as Basic Math (+20%)." }
    - { name: "Swimming", base: 65, per_level: 5, note: "Printed as Swim (+15%)." }
    - { name: "SCUBA", base: 60, per_level: 5, note: "Printed as S.C.U.B.A. (+10%)." }
    - { name: "Ocean Geographic Surveying", base: 20, per_level: 5, note: "+5%" }
    - { name: "Advanced Deep Sea Diving", base: 0, per_level: 0, note: "The book grants this at +10%, and the skill itself has no base percentage - printed 212 defines it and states none - so the bonus has nothing to modify and the row stays at 0. Same as the Tritonian Sea Wolf." }
    - { name: "Boat: Submersibles", base: 50, per_level: 4, note: "Printed as Pilot: Submersibles (+10%)." }
    - { name: "Navigation: Underwater", base: 45, per_level: 4, note: "Printed as Underwater Navigation (+15%)." }
    - { name: "Demolitions: Underwater", base: 72, per_level: 4, note: "Printed as Underwater Demolitions (+16%). SIXTEEN, not fifteen or ten - an odd figure and the only +16% in this book, transcribed as printed rather than rounded." }
    - { name: "Undersea Salvage", base: 50, per_level: 5, note: "Printed as Underwater Salvage (+20%)." }
    - { name: "Undersea & Sea Survival", base: 35, per_level: 5, note: "Printed as Underwater Survival (+10%)." }
    - { choose: 2, from: ["Language: Other"], bonus: 20, note: "Two languages of choice (+20%). Taken once per language - the picker asks which." }
    - { choose: 1, from: ["Literacy: Other"], bonus: 20, note: "Literacy in one language of choice (+20%)." }
    - { name: "W.P. Torpedo", base: 0, per_level: 0 }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "One further W.P. of choice." }
    - { name: "Hand to Hand: Basic", base: 0, per_level: 0, note: "Can be raised to expert for one other skill selection, or to martial arts (assassin if evil) for two." }
  occ_related_skills:
    count: 7
    schedule: [{ level: 3, count: 1 }, { level: 7, count: 1 }, { level: 11, count: 1 }, { level: 15, count: 1 }]
    categories:
      - "Communications"
      - "Domestic"
      - { name: "Electrical", bonus: 5 }
      - { name: "Mechanical", bonus: 10 }
      - { name: "Medical", only: ["First Aid"] }
      - "Military"
      - { name: "Physical", except: ["Acrobatics", "Wrestling"] }
      - { name: "Pilot", except: ["Military: Tanks & APCs", "Space: Small Spacecraft", "Space: Space Fighter", "Space: Starship"] }
      - { name: "Pilot Related", bonus: 10 }
      - "Rogue"
      - { name: "Science", bonus: 5 }
      - { name: "Technical", bonus: 10 }
      - "Weapon Proficiencies"
      - "Wilderness"
    note: "Espionage is barred entirely. Pilot bars tanks and spacecraft; the spacecraft bar is three catalog rows, and Space: Antigrav Suit and Space: Contragravity Pak stay takeable as worn suits rather than craft."
  secondary_skills:
    count: 5
    note: "Chosen from the same categories and under the same any/only/none limits as the related skills."
restrictions:
  - "Attribute requirements: I.Q. 9 or higher. A high P.P. and P.S. are handy but not mandatory."
  - "Alignment: any."
  - "Racial restrictions: none, but salvage experts are typically humanoid and predominantly surface dwellers."
  - "THE CHARACTER ALSO STARTS WITH ONE MAJOR ASSET: a two- to six-man submersible, a large sailboat, a modest cabin cruiser, or a suit of power armour. None of the four is in the starting equipment, because the catalog has no vessel rows for the first three - see BOOK-INGEST-AUDIT.md F3 on gear having no shape for a vessel. Otherwise the character books passage or rents what is needed, and an employer is likely to provide large boats, submersibles, special equipment and explosives."
  - "Money: 2D4x1000 in credits and 2D4x1000 in salvaged metals and artifacts. A lot of this character''s money goes into equipment and personal luxuries."
  - "Cybernetics: none to start."
  - "A salvage expert typically gets 10-20% of a recovered item''s original value selling it as is, and 1D6% for scrap metal. Restoration is reserved for what the character means to keep, or for what will be worth much more repaired."
equipment_starting:
  - { choose: 1, label: "weapon of choice", qty: 1, from: ["survival-knife", "hunting-knife", "short-sword", "trident", "short-spear"], note: "The catalog set, widened as more books are imported." }
  - { item_id: "survival-knife", qty: 1 }
  - { item_id: "tool-kit-portable", qty: 1 }
  - { item_id: "tool-kit-large", qty: 1 }
  - { item_id: "laser-torch", qty: 1 }
  - { item_id: "acetylene-torch", qty: 1 }
  - { item_id: "rope", qty: 1 }
  - { item_id: "duct-tape", qty: 1 }
  - { item_id: "flashlight-pen", qty: 1 }
  - { item_id: "flashlight-large", qty: 1 }
  - { item_id: "language-translator-portable", qty: 1 }
  - { item_id: "hand-computer", qty: 1 }
  - { item_id: "sack", qty: 2 }
  - { item_id: "backpack", qty: 1 }
  - { item_id: "canteen", qty: 1 }
  - { item_id: "sunglasses", qty: 1 }
  - { item_id: "soldering-goggles", qty: 1 }
  - { item_id: "snorkel-gear", qty: 1 }
  - { item_id: "wet-suit", qty: 1 }
  - { item_id: "scuba-gear", qty: 1 }
  - { item_id: "clothing", qty: 3 }
starting_money: "2d4x1000"
extraction_notes: |
  - Underseas, printed 133-134. The ocean''s answer to the operator - and the
    book says so itself, adding that operators are often key members of a
    salvage crew.
  - IT IS THE SECOND CLASS TO GRANT A +10% ON A SKILL WITH NO BASE. Pilot:
    Advanced Deep Sea Diving stays at 0 for the same reason it does on the
    Tritonian Sea Wolf: the skill states no percentage, so there is nothing for
    a bonus to modify. Two classes now do this, which is worth knowing if the
    skill ever gets a base from another book.
  - UNDERWATER DEMOLITIONS IS PRINTED AT +16%, which is the only +16% in this
    book and an odd figure among bonuses that are otherwise multiples of five.
    Transcribed as printed rather than rounded to +15%. The stored base is 72,
    from the catalog''s 56.
  - ITS 200 FEET OF SUPER LIGHTWEIGHT ROPE IS STORED AS ORDINARY ROPE. The book
    specifies 10 lbs with a 500 lb test weight, which is a distinct item; the
    catalog has one rope row and the gear pass can add the specific one later.
  - THE STARTING VESSEL IS NOT STORED. Printed 134 gives the character one of a
    two- to six-man submersible, a large sailboat, a modest cabin cruiser or a
    suit of power armour. Three of those four are vessels, and the catalog has
    no shape for a vessel in `gear` - BOOK-INGEST-AUDIT.md F3. It is a
    restriction line so the choice is at least visible.
  - NO `sdc_base` AND NO `mdc_base`, so it needs a `CORE_SDC_BY_CLASS` entry.
    1D6: a salvage professional with Hand to Hand: Basic and two W.P.s, whose
    skill list is tools, torches and survey work.
---

# Salvage Expert

## Lore

Salvage experts are trained to identify, locate and retrieve artifacts, treasure, parts and scrap metal from the sea. If a sunken vessel is not too badly damaged, the character may be able to raise it and even get it sailing again - though that takes the right equipment, a crew and weeks of work, with repairs and restoration taking weeks more.

In most cases the expert sells the ship, metal and articles as they are, as soon as possible, and gets ten to twenty percent of the original value. Scrap metal fetches a few percent. Restoration is reserved for what the character means to keep, or for what will be worth considerably more once cleaned up.

They are also hired for underwater excavation, mining, demolitions, rescue, recovery of bodies from wrecks, exploration and mechanical repairs. In many ways they are the ocean''s version of the operator.

## GM Notes

A salvage expert can be a likeable rogue pulling treasure out of the sea, a privateer or mercenary for hire, an adventurer, a pirate, or a foul-hearted villain who takes what he wants and crushes whoever is in the way - opposition and innocent aquatic life alike.

The seas are vast and effectively lawless, and that freedom attracts explorers, colonists and treasure hunters as readily as it attracts the ruthless. The worst of the salvage teams plunder natural treasures and people''s alike, sabotage or kill their competitors, and will cripple a vessel or bombard an underwater community and then salvage the wreckage. Survivors are abandoned, killed, or sold into slavery - the Splugorth, Naut''Yll, Horune and many pirates are always buying. These brigands measure the worth of a human life by its salvage value.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'salvage-expert');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'salvage-expert';
SELECT count(*) AS stub_gear FROM gear WHERE slug IN ('tool-kit-portable', 'tool-kit-large', 'acetylene-torch', 'duct-tape', 'flashlight-pen', 'soldering-goggles', 'snorkel-gear');

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-salvage-expert-class.sql');
