-- Rifts World Book 29: Madhaven - its gear. Forty new rows: the Haven Mutants'
-- bone weapons and armor (printed 81-83), the Order of the White Rose's TW
-- weapons, shield, body armors and barding (printed 83-88), its Techno-Wizard
-- devices (printed 88-91), and the White Rose healing items (printed 36-37).
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-madhaven-gear.sql
--
-- ALL 40 ARE NEW - catalog-diff --table gear --remote, 2026-09-24: matched 0,
-- missing 40 against 2830 rows; every nearest candidate is unrelated.
--
-- THE BONE WEAPONS ARE PREFIXED "Mutant". The book heads them bare - Bone Axe,
-- Bone Knife - and the catalog already holds an unrelated S.D.C. "Bone Knife"
-- estimate row. All ten take the prefix so the set reads together; the book's
-- own heading is in each description. See docs/surveys/madhaven.md.
--
-- EVERY NUMBER WAS READ OFF A 200 DPI RENDER, not the text layer, which carries
-- this book's digit cipher (`I D4xl O` for 1D4x10, `13 0` for 130). RECONCILED
-- row by row against the renders by book-reconcile: 40 of 40 agree.
--
-- CONVENTIONS, following add-new-west-gear-d-techno-wizard.sql:
--   * A TW weapon is 'weapon'; the Barrier Shield is 'armor', like the
--     catalog's other shields; a device that does no damage is 'gear'.
--   * The White Rose items are 'magic', as the catalog files healing potions.
--     The book names only a petal, leaf, thorn, blossom, sprig and bush; the
--     elixir, salve and potions are named here from what each one is made of.
--   * Where the book prices a range, cost holds the low end and cost_note the
--     range. The Thorn is priced by the book as double a petal, so its figure
--     is derived and cost_note says so. The Super-Healing Potion's figure is
--     the book's "resurrection potion" value, identified with it by the effect
--     it describes - an inference, and cost_note says so.
--   * The body armors and barding are priced only as exclusive to the Order;
--     cost is NULL. A weapon's own M.D.C. is in mdc, as 12 catalog weapons do.
--   * Mutant Bone Armor is one row for both suits; its M.D.C. is rolled, so
--     mdc is NULL and both suits' figures are in the description.
--   * Creation requirements (P.P.E., spells, hours) are in the description.
--   * Descriptions are short paraphrases; no sentence is the book's.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('mutant-bone-axe', 'Mutant Bone Axe', 'rifts', 'weapon', 10, 7500, 'Market cost 7,500 credits.', '1D8+3 M.D. +P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, 50, 'Book heading: Bone Axe. A shoulder-blade bone ground to an edge on a long bone haft, usually single-headed; doubles as a chopping tool. Weight 10-15 lbs. Bonuses: none. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.81'),
('mutant-bone-claw-gauntlet', 'Mutant Bone Claw Gauntlet', 'rifts', 'weapon', 10, 7200, 'Market cost 7,200 credits.', '2D4+2 M.D. +P.S. punch damage', 1, NULL, NULL, NULL, NULL, NULL, 45, 'Book heading: Bone Claw Gauntlet. Three sharpened arm or leg bones strapped along the forearm so they jut past the gloved fist, Dog Boy style, with bone knuckle guards sewn into the glove. Rakes, stabs and parries. Bonuses: +2 to parry and disarm. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.81'),
('mutant-bone-club', 'Mutant Bone Club', 'rifts', 'weapon', 10, 7500, 'Market cost 7,500 credits.', '1D6+1 M.D. +P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, 40, 'Book heading: Bone Club. A big leg bone with one end whittled and wrapped as a grip; the simplest bone weapon. Weight 10-15 lbs. Bonuses: +1 to parry. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.81'),
('mutant-bone-shiv', 'Mutant Bone Shiv', 'rifts', 'weapon', 3, 2500, 'Market cost 2,500 credits.', '1D4+1 M.D. +P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, 40, 'Book heading: Bone Shiv. The smallest and easiest bone weapon: a stubby dagger honed on one side to a needle point. Poor when thrown (half range, -4 to strike). Bonuses: +10% to conceal and palm. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.81'),
('mutant-bone-knife', 'Mutant Bone Knife', 'rifts', 'weapon', 8, 5400, 'Market cost 5,400 credits.', '1D6+2 M.D. +P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, 50, 'Book heading: Bone Knife. A carved mutant-bone knife 6-14 inches (15-35 cm) long. Bonuses: none. Not the S.D.C. catalog row ''Bone Knife''. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.81'),
('mutant-bone-sickle', 'Mutant Bone Sickle', 'rifts', 'weapon', 10, 7500, 'Market cost 7,500 credits.', '1D8+2 or 1D10 M.D. +P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, 35, 'Book heading: Bone Sickle Weapon. A rib honed along its inner curve and fixed to a short bone grip, giving a crescent blade. Favored by Leopard Men and Mantis Men. Bonuses: +1 to parry and disarm. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.82'),
('mutant-bone-spear', 'Mutant Bone Spear', 'rifts', 'weapon', 20, 14600, 'Market cost 14,600 credits.', 'Blunt end 1D4 M.D. +P.S.; blade end 2D6+3 M.D. +P.S.; 2D6+3 M.D. when thrown', 1, NULL, NULL, NULL, NULL, NULL, 100, 'Book heading: Bone Spear. Two or three long bones lashed end to end with rope or sinew, tipped with a bone blade; usable blunt, bladed or thrown, with long reach. Favored by Leopard Men and Savage Lumox. Weight 20-25 lbs. Bonuses: +1 to strike, +2 to parry, +1 to disarm. Thrown only half the usual range by anyone with P.S. 24 or less. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.82'),
('mutant-bone-sword', 'Mutant Bone Sword', 'rifts', 'weapon', 15, 8000, 'Market cost 8,000 (short sword), 11,500 (broadsword) and 15,400 (bastard sword) credits.', 'Short sword 1D8+2 M.D.; broadsword 2D6+2 M.D.; bastard sword 3D6+3 M.D. (each +P.S.; no P.S. bonus for a bastard sword used one-handed)', 1, NULL, NULL, NULL, NULL, NULL, 100, 'Book heading: Bone Sword. Made from one or two long bones, single- or (more often) double-edged, in three sizes. Weight 15-22 lbs on average. Bonuses: +1 to strike and parry. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.82'),
('mutant-giant-bone-sword', 'Mutant Giant Bone Sword', 'rifts', 'weapon', 35, 19200, 'Market cost 19,200-21,400 credits.', '4D6+5 M.D. +P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, 100, 'Book heading: Giant Bone Sword. A flamberge or executioner blade 5-7 ft (1.5-2.1 m) long, needing 2-4 long bones, for the biggest mutants. Weight 35-40 lbs. Bonuses: +1 to strike and disarm; anyone under 8 ft (2.4 m) tall with P.S. 24 or less gets no bonuses and is -3 to strike, parry and disarm. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.82'),
('mutant-bone-flail', 'Mutant Bone Flail', 'rifts', 'weapon', 15, 11500, 'Market cost 11,500 credits.', '2D6+4 M.D. +P.S. punch damage', 1, NULL, NULL, NULL, NULL, NULL, 75, 'Book heading: Bone Flail. A packed, sealed mutant skull with bone blades jutting from its eye, nose and mouth holes, swung from a grip of small bones joined to the tail of a spine by sinew. Unnerving to look at; favored by Leopard, Mantis and Pseudo Men. Bonuses: +1 to disarm and entangle. Haven Mutant bone is itself M.D.C., so these cut S.D.C. and M.D.C. material like a Vibro-Blade, can strike ghosts, Entities, Astral Beings and other intangible beings, and do half damage to creatures vulnerable to silver (vampires, most demons, some Entities). Crude and heavy: a wielder with P.S. under 18 is -1 to strike and parry and -2 thrown. Black Market value is about that of Xiticix weapons.', 'Rifts World Book 29: Madhaven p.82'),
('mutant-bone-armor', 'Mutant Bone Armor', 'rifts', 'armor', 80, 30000, 'Half suit 30,000-35,000 credits, full suit 64,000-75,000 credits (market cost); cost holds the half-suit low end.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Book heading: Bone Armor. Bones from roughly two mutant skeletons stitched and fitted together, sometimes with M.D.C. metal and ceramic scrap; heavy, and worn only by the strongest. HALF SUIT (arms, upper torso and a helmet): 80 lbs, A.R. 15, 1D6x10+25 M.D.C.; Speed -10% and -10% on agility skills (Acrobatics, Climb, Gymnastics, Prowl, Swim). FULL SUIT (not environmental): 150-200 lbs, A.R. 19, 2D4x10+50 M.D.C.; -20% to the same skills, Speed -25%. M.D.C. IS ROLLED, so the mdc column is empty. FLAW: Necromantic animation (Animate and Control Dead and the like) can make the armor itself try to obey the caster; the wearer overpowers it but is -5 on combat rolls, -2 attacks per melee, -20% on hand skills and Speed -20%.', 'Rifts World Book 29: Madhaven p.82-83'),
('tw-conduit-sword', 'TW Conduit Sword', 'rifts', 'weapon', 6, NULL, 'White Rose only; not sold on the Black Market. No price given.', 'Mystic Knight''s energy bolt damage +2D6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, 50, 'A bladeless iron hilt wound or inlaid with silver wire, akin to the TW Flaming Sword; a Mystic Knight pours raw energy in and it sets as a crystalline blade (50 M.D.C.). Twice the energy of one energy bolt forms a short sword, four times a long or bastard sword; the blade lasts 5 minutes before it needs another bolt, cuts M.D.C. material and harms beings vulnerable to magic. Light and easy to hide, it is the Order''s most widely issued weapon. Bonuses: +1 to strike and parry. CREATION: Featherlight (10), Power Weapon (35); physically the silver-wired iron hilt and a blue sapphire worth 500+ credits where the blade emerges.', 'Rifts World Book 29: Madhaven p.83'),
('tw-inferno-blade', 'TW Inferno Blade', 'rifts', 'weapon', 6, 12000000, 'White Rose only, never on the Black Market; its value is put at 12 million credits. Takes 2-3 months and needs a Techno-Wizard and a Fire Warlock working together.', '1D4x10+6 M.D. (x2 vs fire-vulnerable beings)', 1, NULL, NULL, NULL, NULL, NULL, 200, 'A large two-handed sword (or axe, pole arm or war hammer) in black, blood red or gold, warm to the touch and etched with fire imagery; magically light, so the superhumanly strong can wield it one-handed. M.D.C. 200, regenerating 20 per day. POWERS: 40 P.P.E. turns it to red-hot molten metal for 3 minutes (12 melees), wrapping weapon and wielder in a flame halo of 100 M.D.C. that burns anyone who touches or strikes the wielder for 2D6 M.D. (x2 vs fire-vulnerable). 30 P.P.E. casts Screaming Wall of Flame at 5th level Warlock strength. Scarce; rarely given to young Knights. Bonuses: +1 to strike and parry. CREATION: Enchant Weapon (1000), Ensorcel (400), Featherlight (10), Invincible Armor (30), Melt Metal (50), Power Weapon (35), Screaming Wall of Flame (35); physically a well forged weapon and rubies worth 10,000+ credits in total, one of them worth 1,000+.', 'Rifts World Book 29: Madhaven p.83-84'),
('tw-light-shapers', 'TW Light Shapers', 'rifts', 'weapon', 3, 600000, 'White Rose only, never on the Black Market; its value is put at 600,000 credits. Takes 3 weeks to make.', 'Energy blast 3D6 M.D. (double vs Shadow beings, vampires and others vulnerable to light); Lightblade 4D6 M.D.', 1, 'Energy blast 300 feet (91.5 m)', NULL, 'Up to three energy blasts per melee, each one melee attack', NULL, NULL, 140, 'Combat vambraces over upper arm and forearm with a plate guarding the hand; a favorite of the Reconcilers and often built into a Knight''s armor. No damage until 40 P.P.E. is channeled, after which they shine white for 5 minutes and the wearer mentally shapes the light into energy blasts, a forearm Lightblade (as the spell), or a small round Laser Shield. The shield parries laser and light attacks harmlessly and can block other energy (fire, plasma, particle beam, ion, electricity) while taking damage from them (140 M.D.C.); it is useless against physical attacks. Switching sword and shield costs one melee action; blasts can be fired in either form. Bonuses: +1 to strike with blasts, +1 to strike and parry with the Lightblade, +2 to parry energy attacks with the shield. CREATION: Energy Field (10), Globe of Daylight (2), Lightblade (20), Magic Shield (6), Power Bolt (20), Power Weapon (35); physically the vambraces and a diamond worth 5,000+ credits.', 'Rifts World Book 29: Madhaven p.84'),
('tw-storm-lance', 'TW Storm Lance', 'rifts', 'weapon', 15, 700000, 'White Rose only, never on the Black Market; its value is put at 700,000 credits.', '1D4x10 M.D., +1 M.D. per 10 mph (16 km) of charge speed to a maximum of +20 M.D.', 1, NULL, NULL, NULL, NULL, NULL, 300, 'A mounted-combat lance at least 10 ft (3 m) long, up to 15-20 ft (4.6-6.1 m) for big exotic mounts, silver or steel-blue and crackling with electricity; even lightened by magic it needs a saddle harness. Proven on War Birds, Ruin Lizards, Phantom Wolves, Dragon Cats and Fury Beetles. M.D.C. 300, regenerating 20 per day. POWERS: any wielder with the P.P.E. can cast Call Lightning (15), Lightning Arc (30) and Wind Rush (20) at 5th level; War Bird riders dive and use Wind Rush to scatter troops. Bonuses: +3 to strike and +2 to disarm when charging. CREATION: Ensorcel (400), Featherlight (10), Power Weapon (35), Wind Rush (20), Lightning Arc (30), Call Lightning (15); physically the lance, a diamond worth 1,000+ credits and two sapphires worth 1,000+ each set in the grip.', 'Rifts World Book 29: Madhaven p.84-85'),
('tw-barrier-shield', 'TW Barrier Shield', 'rifts', 'armor', 8, 370000, 'White Rose only, never on the Black Market; its value is put at about 370,000 credits.', 'Shield bash 1D6 M.D. plus Supernatural Strength damage if applicable', 1, NULL, NULL, NULL, NULL, NULL, 300, 'A kite or large heater shield enhanced to guard its bearer and, when needed, a whole group; issued to those facing heavy fire or fighting mounted, and painted with the Knight''s guild, family or a White Rose. M.D.C. 300, regenerating 10 per day. POWERS: the user can spend P.P.E. to cast Deflect (10), Targeted Deflection (15) and Wall of Defense (55) at 5th level. Bonuses: +2 to parry, and may try to parry every attack, even from several attackers and from energy and projectile weapons. CREATION: Speed Weapon (100), Power Weapon (35), Wall of Defense (55), Targeted Deflection (15), Deflect (10); physically a large metal shield with a diamond worth 700+ credits and an onyx worth 1,000+.', 'Rifts World Book 29: Madhaven p.85'),
('traditional-mystic-knight-armor', 'Traditional Mystic Knight Armor', 'rifts', 'armor', 20, NULL, 'Exclusive to Mystic Knights; no price given.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 70, 'Medium non-environmental Mystic Knight armor of M.D.C. ceramics and enchanted fabrics, the same suit the evil Mystic Knights wear; every Knight gets one on induction and keeps it as a sign of having renounced evil. White Rose Knights restyle it with angelic motifs in white, gold and crimson, though spikes and chains remain. Human-sized, can be made smaller or slightly larger. Mobility rated good to fair (-5% Climb/Prowl-type skills, -10% Acrobatics/Gymnastics). M.D.C. by location: main body 70, head/helmet 40, arms 30 each, legs 45 each.', 'Rifts World Book 29: Madhaven p.85'),
('light-white-rose-body-armor', 'Light White Rose Body Armor', 'rifts', 'armor', 9, NULL, 'Issued only within the White Rose Order; no price given.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 35, 'Light non-environmental armor like the traditional suit minus the skull helm and horns, in modern plastic and light ceramic; for Squires, Seekers, Garden Keepers and other rarely-fighting members. Mobility rated good to fair (-5% Climb/Prowl-type skills, -10% Acrobatics/Gymnastics). M.D.C. by location: main body 35, head/helmet 30, arms 20 each, legs 30 each.', 'Rifts World Book 29: Madhaven p.86'),
('tw-infiltration-body-armor', 'TW Infiltration Body Armor', 'rifts', 'armor', 10, NULL, 'Issued only within the White Rose Order; no price given.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'Heavy non-environmental infiltration armor in black, crimson or red with a blank faceplate behind a thick collar, heavy with spikes and chains - the suit that started the Order''s chain fad. Mobility excellent, no penalties. WEAPONS: a silver-plated spiked ball and chain or bladed chain doing 2D6 M.D. that can hurt supernatural foes; the spikes add 1D8 (S.D.C. or M.D. by the Knight''s strength) to a body block or tackle. SPECIAL: constant TW lightness and silence at no cost, Shadow Meld (10), Armor of Ithan (10). Activation costs are P.P.E.; I.S.P. may be spent instead at double. Spells work at 5th level. M.D.C. by location: main body 100, head/helmet 60, arms 42 each, legs 66 each.', 'Rifts World Book 29: Madhaven p.86'),
('gateway-tw-body-armor', 'Gateway TW Body Armor', 'rifts', 'armor', 12, NULL, 'Issued only within the White Rose Order; no price given.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 56, 'Medium non-environmental half suit of plate, padding and chain mail for Gateway Knights; it resembles evil Mystic Knight armor, and with its chains and shoulder spikes removed it passes for it on infiltration work. Mobility rated good to fair (-2% Climb/Prowl-type skills, -8% Acrobatics/Gymnastics). SPECIAL: Armor of Ithan (10), Invisibility: Superior (20). Activation costs are P.P.E.; I.S.P. may be spent instead at double. Spells work at 5th level. M.D.C. by location: main body 56, head/helmet 40, arms 30 each, legs 40 each.', 'Rifts World Book 29: Madhaven p.86'),
('cherubim-tw-body-armor', 'Cherubim TW Body Armor', 'rifts', 'armor', 30, NULL, 'Issued only within the White Rose Order; no price given.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 130, 'Heavy non-environmental flying armor designed by Gabriel with the Techno-Wizards for his personal guard, and under consideration for the Rose Thorn special forces; white and gold with purple, spiked and chained. Human-sized, can be made slightly larger but not smaller. Mobility rated poor (-30% on Prowl, Swim, Acrobatics and most physical skills). SPECIAL: Superhuman Speed (10), Invincible Armor (30), Call Lightning (15), Winged Flight (35). Activation costs are P.P.E.; I.S.P. may be spent instead at double. Spells work at 5th level. Each belt also carries a Splugorth Armor of Ithan Talisman (100 M.D.C., three uses a day) taken in battle - not part of the armor. M.D.C. by location: main body 130, head/helmet 60, arms 50 each, legs 75 each.', 'Rifts World Book 29: Madhaven p.87'),
('maximilian-tw-body-armor', 'Maximilian TW Body Armor', 'rifts', 'armor', 38, NULL, 'Issued only within the White Rose Order; no price given. Issued only to Knights of 5th level or higher while supply is limited.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 150, 'Heavy non-environmental armor first field-tested by the Knight called the Revenant (Siege on Tolkeen 3: Sorcerers'' Revenge p.44); huge, broad-shouldered, spiked and chained, carrying six TW enhancements where that was thought impossible. Can be made slightly larger, not smaller. Mobility poor: -30% to Prowl, -20% to Swim, Climb, Acrobatics and most physical skills. SPECIAL: Superhuman Strength (10), Superhuman Endurance (12), Armor of Ithan (10), Invincible Armor (30), Power Bolt (20), plus Spinning Blades (20) from a cloak-clasp talisman on the left breast rather than the suit. Activation costs are P.P.E.; I.S.P. may be spent instead at double. Spells work at 5th level. Commanders and Knights of repute may also carry a Splugorth Armor of Ithan Talisman (100 M.D.C., three uses a day). M.D.C. by location: main body 150, head/helmet 60, arms 50 each, legs 72 each.', 'Rifts World Book 29: Madhaven p.87-88'),
('tw-animal-barding', 'TW Animal Barding', 'rifts', 'armor', 50, NULL, 'Exclusive to Mystic Knights; no price given.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 120, 'Medium non-environmental M.D.C. barding for the Knights'' horses and exotic mounts, sized to the animal; weight 50-200 lbs depending on the animal. Reduces the mount''s speed and leaping distance and height by 20%. No special features. M.D.C. by location: main body 120, head 50, each wing or foreleg 40, each hindleg 60.', 'Rifts World Book 29: Madhaven p.88'),
('tw-illusion-and-protection-matrix', 'TW Illusion and Protection Matrix', 'rifts', 'gear', NULL, NULL, 'Not for sale - a fixed installation around the Garden. Recreating one elsewhere would take a small army of mages 2D6+6 years.', NULL, 0, 'The whole Garden (old Central Park), roughly 2.5 x 0.5 miles (4 x 0.8 km)', NULL, NULL, NULL, NULL, NULL, 'Book heading: "The Curtain". Hundreds of Central Park lampposts rewired with copper covered in Superior Protection Circle runes and tied to a TW generator fed by the Harlem ley line and nexus. It runs forever at no P.P.E. cost, acting as a giant protection circle and an artificial ley line extension, and hides the Garden as the ''Crater of the Damned'', a blasted crater circled by clouds of ghosts. SPECIAL: lampposts burn Lantern Light (1) by day and Globe of Daylight (2) by night; Illusory Terrain (120) and Protection Circle: Superior (300) run constantly. Entities, vampires, Undead Horrors and lesser and greater demons cannot enter; only demon lords, demigods, godlings and the like get through. SAVE: 16 vs illusion, rolled only on stepping into the crater; a failure brings 1D6x100 harmless illusory ghosts (Horror Factor 15) swooping in, a success reveals the forest. BONUSES to Garden residents: +3 to save vs magic and psionics, immune to possession, +8 vs Horror Factor; mages and creatures of magic get 10 extra P.P.E. and psychics 10 I.S.P. per melee round. CREATION: a nearby pair of ley lines and a nexus, over 50 miles (80 km) of copper wire, a huge P.P.E. generator, crystals and lampposts by the hundred as the focus.', 'Rifts World Book 29: Madhaven p.88-89'),
('tw-candle-music-box', 'TW Candle-Music Box', 'rifts', 'gear', 2, 200000, 'Market price 200,000 or more; rare.', NULL, 0, '10 foot (3 m) radius', 'Activation 22 P.P.E. per the stat block (the prose says 23); a new candle and fresh P.P.E. if the flame is snuffed.', NULL, NULL, NULL, NULL, 'A music box with a mournful tune; open it, light a candle and spend the P.P.E. and the flame turns purple and works as Protection Circle: Simple, radius 10 ft (3 m), for 1D4x10+90 minutes while the music plays. Wind and rain cannot put the flame out, but a Burster or similar can. BOOK DISCREPANCY: the description says 23 P.P.E., the stat line says 22. CREATION: Fuel Flame (5), Protection Circle: Simple (45); physically a pure oak music box with a silver music fork and good sound, and an emerald worth 1,000+ credits mounted on the lid.', 'Rifts World Book 29: Madhaven p.89-90'),
('tw-ghost-band', 'TW Ghost Band', 'rifts', 'gear', NULL, 300000, 'Market price 300,000-500,000 credits.', NULL, 0, NULL, '20 P.P.E. per activation; lasts 10 minutes', NULL, NULL, NULL, NULL, 'An oversized bracelet or headband with three silver wires strung above it, set humming by a tiny battery - picture a small round violin. It hides the wearer from simpler spirits (Poltergeists, Haunting Entities, Beautiful, Gluttonous and Harmful Ghosts): they must save vs magic at 15+ or cannot see the wearer and attack blind (-10 to strike). Attacking the Entity ends the invisibility. CREATION: Astral Projection (10), Invisibility: Superior (20) and an initial 110 P.P.E.; physically the band with suspended silver wires wired to a tiny battery, and a small emerald touching and propping all three wires.', 'Rifts World Book 29: Madhaven p.90'),
('tw-ghost-speaker-and-microphone', 'TW Ghost Speaker and Microphone', 'rifts', 'gear', 1, 50000, 'Market price 50,000-70,000 credits; not in high demand.', NULL, 0, '20 feet (6.1 m)', '20 P.P.E. per activation; 1D4+4 minutes per spirit', NULL, NULL, NULL, NULL, 'A microphone and speaker for two-way talk with spirits: typically 10 questions of up to 20 words each, and up to 10 replies of up to 10 words, though the spirit need not answer. Spirit voices echo, swell and fade. Anyone but a Necromancer, Techno-Wizard, or psionic having See the Invisible, Commune with Spirits or Astral Projection must save vs Horror Factor 12 on first use. CREATION: Energy Bolt (5), Astral Projection (10), Distant Voice (10, printed ''Distance Voice''), Tongues (12); physically a mahogany speaker set with a large clear quartz worth 400+ credits and a microphone set with a large rose quartz worth 500+.', 'Rifts World Book 29: Madhaven p.90'),
('tw-ghost-goo-gun', 'TW Ghost Goo Gun', 'rifts', 'weapon', 3, 70000, 'Market price 70,000-80,000 credits.', 'None - coats the target in visible ecto-goo', 0, '100 feet (30.5 m)', 'Effectively unlimited while the shooter can pay 10 P.P.E. per blast', NULL, NULL, NULL, 50, 'A revolver or pistol that shoots a sticky ectoplasmic blanket, enough to cover half a human-sized target, making an invisible or intangible Entity visible for two minutes (8 melee rounds). It does no harm but exposes the target to magic and psionic attack, and Entities hate being seen, so they often leave. Works on any invisible foe, though a shooter who cannot see the invisible fires blind (-10). Bonuses: +1 to strike. CREATION: Energy Bolt (5), See the Invisible (4), Apparition (20); physically the pistol housing and an amber stone worth 700+ credits.', 'Rifts World Book 29: Madhaven p.90-91'),
('tw-dark-light', 'TW Dark Light', 'rifts', 'gear', NULL, 50000, 'Market price 50,000-60,000 credits.', NULL, 0, '30 foot (9.1 m) diameter', '10 P.P.E. for 10 minutes of light', NULL, NULL, NULL, NULL, 'A light bulb on an extension cord tethered to a topaz, floating about 7 ft (2.1 m) up and casting deep purple light over a 30 ft area; ghosts and Entities passing through show as wispy silhouettes. No effect on beings made invisible by magic or psionics. CREATION: See the Invisible (4), Globe of Daylight (2), Manipulate Objects (5), initial cost 300 P.P.E.; physically a 60 watt bulb, a roughly 10 ft (3 m) extension cord and a large topaz.', 'Rifts World Book 29: Madhaven p.91'),
('tw-phantom-gloves', 'TW Phantom Gloves', 'rifts', 'gear', 1, 1000000, 'Market price 1 to 1.5 million credits, sometimes more; rare. About 200 hours to make a pair.', NULL, 0, 'Self; hands only', '30 P.P.E. per activation; lasts 15 minutes', NULL, NULL, NULL, NULL, 'Black and silver gloves that shift the wearer''s hands into the Astral Plane so they can touch and fight Astral Beings, Entities and other ethereal beings; held weapons are not affected, and while active the hands cannot touch the physical world and feel cold. Weight 1 lb each. AFTEREFFECT: numb hands, for 30 minutes, -10% to hand skills and -1 to strike, parry, disarm and entangle. CREATION: Energy Bolt (5), Astral Projection (10); physically the gloves with a black sapphire worth 5,000+ credits in each, about 200 hours per pair.', 'Rifts World Book 29: Madhaven p.91'),
('white-rose-leaf', 'White Rose Leaf', 'rifts', 'magic', NULL, 1000, 'A single leaf commands 1,000-6,000 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. Chewed, or steeped as a tea, a leaf clears fever, nausea, diarrhea and headache within 15 minutes, and one cup gives 24 hours of +2 to save vs disease, poison (lethal or not), harmful drugs and possession. Extra cups add nothing but flavor.', 'Rifts World Book 29: Madhaven p.36-37'),
('white-rose-thorn', 'White Rose Thorn', 'rifts', 'magic', NULL, 20000, 'Priced by the book as double a petal; a petal commands 10,000-30,000 credits, so 20,000-60,000 (derived, not printed).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. Set into a deep wound - gash, stab, gunshot, even a laser burn - a thorn sprouts root-like tendrils that fill it and turn to flesh, healing it in 1D4 hours and restoring 5D6 S.D.C. and 3D6 Hit Points; the thorn is absorbed. (Sap from a snapped stem does a lesser version on cuts, burns and rashes: 3D6 S.D.C. plus 2D6 Hit Points, or 1D6 M.D.C. to a Mega-Damage creature, healing in 1D4+4 hours.)', 'Rifts World Book 29: Madhaven p.36-37'),
('white-rose-petal', 'White Rose Petal', 'rifts', 'magic', NULL, 10000, 'A single petal commands 10,000-30,000 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. Petals keep indefinitely (100 years is the usual belief, 1,000 by legend) and always look freshly picked. One dissolved on the tongue or in hot water acts as a White Rose Healing Potion.', 'Rifts World Book 29: Madhaven p.36-37'),
('white-rose-healing-potion', 'White Rose Healing Potion', 'rifts', 'magic', NULL, 10000, 'The simple potions, salves, ointments and brews command 10,000-30,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. One petal dissolved in hot water (or on the tongue); stays potent 100+ years. It halts internal bleeding and restores all lost S.D.C. and a third of lost Hit Points; given to someone in a coma it has a 01-75% chance to bring them fully awake, though atrophy and injuries may need more treatment.', 'Rifts World Book 29: Madhaven p.36-37'),
('white-rose-elixir', 'White Rose Elixir', 'rifts', 'magic', NULL, 10000, 'The simple potions, salves, ointments and brews command 10,000-30,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. Unnamed in the book: a brew or elixir of one petal, one leaf and one thorn. It instantly cancels every poison and toxin, supernatural ones included, and restores 2D6+6 S.D.C. and 1D6+3 Hit Points; taken beforehand it gives 1D4+3 days of +6 to save vs drugs, disease and every poison.', 'Rifts World Book 29: Madhaven p.37'),
('white-rose-vampire-salve', 'White Rose Vampire Salve', 'rifts', 'magic', NULL, 10000, 'The simple potions, salves, ointments and brews command 10,000-30,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. Unnamed in the book: a salve of two petals and a pinch of pollen. On a vampire bite it breaks any control the vampire had and heals the wound fully, and the next bite counts as a first bite again.', 'Rifts World Book 29: Madhaven p.37'),
('white-rose-super-healing-potion', 'White Rose Super-Healing Potion', 'rifts', 'magic', NULL, 1000000, 'Called the resurrection potion in the price note: 1-10 million credits or more, by buyer.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. Made from a whole flower. Cures any disease or parasitic illness, cold to cancer, and fully restores Hit Points and S.D.C. (half of lost M.D.C. for a Mega-Damage creature); one of the few ways to remove a Bio-Wizard parasite safely. Also: 01-25% to cure a phobia or obsession, 01-55% to expel a possessing Entity, 01-90% to expel a Madness Entity, 01-95% to restore all damage from a Rotting Entity; Contagion Entity sickness is relieved only until it recurs. Revives the dead 01-75% within two hours (+10% under 30 minutes, 01-40% at 1-7 days, never after), healing all wounds and restoring a quarter of S.D.C. and Hit Points. Grants immunity to disease and poison for 1D6 weeks.', 'Rifts World Book 29: Madhaven p.37'),
('white-rose-blossom', 'White Rose Blossom', 'rifts', 'magic', NULL, 600000, 'A full blossom commands 600,000 to 2 million credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. A clipped stem and flower, which does the bush no harm. It stays fresh 1D6 years out of water or 1D6x10+40 years in a vase. Its scent clears foul odors from a room and keeps away sad or angry ghosts and Entities, Poltergeists and household pests; outdoors it draws bees, butterflies and songbirds and suppresses insect pests and plant disease within 500 ft (152 m) of a bush. A whole flower is also what a super-healing potion is made from.', 'Rifts World Book 29: Madhaven p.37'),
('white-rose-sprig', 'White Rose Sprig', 'rifts', 'magic', NULL, 1200000, 'A sprig commands 1.2 to 3.7 million credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. A stem carrying 3D4 thorns and a single blossom.', 'Rifts World Book 29: Madhaven p.37'),
('white-rose-bush', 'White Rose Bush', 'rifts', 'magic', NULL, 50000000, 'A whole bush (6+ blooms, 12 buds) commands 50 to 200 million credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'From the White Rose, an alien magical rose bush grown in secret in the Garden by the Keepers of the Garden; knowledge of it can get the holder hunted. A living bush, priceless but hard to keep alive once uprooted or moved from where it grew: 01-06% chance of survival, or 01-60% in the hands of the Garden''s gardeners and Keepers. Wild patches rarely exceed 1D4+2 bushes of up to 1D6+6 blooms each; each bloom takes at least 5 years to mature.', 'Rifts World Book 29: Madhaven p.37');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 40 Madhaven gear rows are in' AS assertion, count(*) AS got, 40 AS want
  FROM gear WHERE slug IN ('mutant-bone-axe', 'mutant-bone-claw-gauntlet', 'mutant-bone-club', 'mutant-bone-shiv', 'mutant-bone-knife', 'mutant-bone-sickle', 'mutant-bone-spear', 'mutant-bone-sword', 'mutant-giant-bone-sword', 'mutant-bone-flail', 'mutant-bone-armor', 'tw-conduit-sword', 'tw-inferno-blade', 'tw-light-shapers', 'tw-storm-lance', 'tw-barrier-shield', 'traditional-mystic-knight-armor', 'light-white-rose-body-armor', 'tw-infiltration-body-armor', 'gateway-tw-body-armor', 'cherubim-tw-body-armor', 'maximilian-tw-body-armor', 'tw-animal-barding', 'tw-illusion-and-protection-matrix', 'tw-candle-music-box', 'tw-ghost-band', 'tw-ghost-speaker-and-microphone', 'tw-ghost-goo-gun', 'tw-dark-light', 'tw-phantom-gloves', 'white-rose-leaf', 'white-rose-thorn', 'white-rose-petal', 'white-rose-healing-potion', 'white-rose-elixir', 'white-rose-vampire-salve', 'white-rose-super-healing-potion', 'white-rose-blossom', 'white-rose-sprig', 'white-rose-bush');
SELECT 'and every one cites Madhaven' AS assertion, count(*) AS got, 40 AS want
  FROM gear WHERE slug IN ('mutant-bone-axe', 'mutant-bone-claw-gauntlet', 'mutant-bone-club', 'mutant-bone-shiv', 'mutant-bone-knife', 'mutant-bone-sickle', 'mutant-bone-spear', 'mutant-bone-sword', 'mutant-giant-bone-sword', 'mutant-bone-flail', 'mutant-bone-armor', 'tw-conduit-sword', 'tw-inferno-blade', 'tw-light-shapers', 'tw-storm-lance', 'tw-barrier-shield', 'traditional-mystic-knight-armor', 'light-white-rose-body-armor', 'tw-infiltration-body-armor', 'gateway-tw-body-armor', 'cherubim-tw-body-armor', 'maximilian-tw-body-armor', 'tw-animal-barding', 'tw-illusion-and-protection-matrix', 'tw-candle-music-box', 'tw-ghost-band', 'tw-ghost-speaker-and-microphone', 'tw-ghost-goo-gun', 'tw-dark-light', 'tw-phantom-gloves', 'white-rose-leaf', 'white-rose-thorn', 'white-rose-petal', 'white-rose-healing-potion', 'white-rose-elixir', 'white-rose-vampire-salve', 'white-rose-super-healing-potion', 'white-rose-blossom', 'white-rose-sprig', 'white-rose-bush') AND source_book LIKE 'Rifts World Book 29: Madhaven p.%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-madhaven-gear.sql');
