-- The Shaydor Spherian R.C.C., Rifts World Book 6: South America p.103.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-shaydor-spherian-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'shaydor-spherian', 'Shaydor Spherian', 'rifts', '---
id: shaydor-spherian
men_of_arms: false
name: Shaydor Spherian
system: rifts
source_book: Rifts World Book 6: South America p.103
category: rcc
horror_factor: 12
attribute_dice:
  IQ: "3d6+2"
  ME: "4d6+2"
  MA: "3d6+2"
  PS: "2d6"
  PP: "2d6"
  PE: "3d6+2"
  PB: "3d6"
  Spd: "3d6"
mdc_base: "2d4x10+20"
bonuses:
  combat: { initiative: 4, strike: 3, parry: 3, dodge: 4, roll: 2 }
  saves: { horror_factor: 6, psionics: 1, toxins_poisons: 1, disease: 1, coma_death_pct: 10 }
skills:
  occ_skills:
    - { name: "Computer Operation", base: 50, per_level: 5, note: "+10%" }
    - { name: "Land Navigation", base: 51, per_level: 4, note: "+15%" }
    - { name: "Wilderness Survival", base: 40, per_level: 5, note: "+10%" }
    - { name: "Art", base: 40, per_level: 5, note: "+5%" }
    - { name: "Creative Writing", base: 35, per_level: 5, note: "Printed as Writing (+10%); the catalog row is Creative Writing." }
    - { name: "Mathematics: Basic", base: 65, per_level: 5, note: "Basic Math (+20%)" }
    - { name: "Mathematics: Advanced", base: 65, per_level: 5, note: "Advanced Math (+20%)" }
    - { name: "Language: Native Tongue", base: 98, per_level: 0, note: "Native Shaydorian at 98%." }
    - { name: "Language: Dragonese", base: 98, per_level: 0, note: "Dragonese/Elf at 98%." }
    - { choose: 2, from: ["Language: Other"], bonus: 20, note: "Languages: select two additional (+20%). Taken once per language - the picker asks which." }
    - { name: "W.P. Knife", base: 0, per_level: 0 }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "W.P. one of choice." }
    - { name: "Swimming", base: 50, per_level: 0, note: "Natural ability, printed as swim 50%; no per-level gain is printed." }
    - { name: "Climbing", base: 70, per_level: 0, note: "Natural ability, printed as climb 70%; no per-level gain is printed." }
    - { name: "Prowl", base: 60, per_level: 0, note: "Natural ability, printed as prowl 60%; no per-level gain is printed." }
  occ_related_skills:
    count: 7
    categories:
      - { name: "Communications", bonus: 10 }
      - "Electrical"
      - { name: "Espionage", only: ["Escape Artist", "Intelligence"], bonus: 5 }
      - "Mechanical"
      - { name: "Medical", bonus: 5 }
      - { name: "Pilot", except: ["Robots & Power Armor", "Robot Combat: Basic", "Robot Combat Elite", "Robot Combat Elite: Glitter Boy", "Robot Combat Elite: SAMAS", "Robot Combat Elite: T-31 Super Trooper", "Robot Combat Elite: X-10A Predator", "Robot Combat Elite: X-535 Jager", "Robot Combat Elite: X-545 Super Jager", "Robot Combat Elite: X-1000 Ulti-Max", "Robot Combat Elite: X-2000 Dyna-Max", "Robot Combat Elite: X-2500 Black Knight", "Robot Combat Elite: X-60 Flanker", "Robot Combat Elite: X-500 Forager"] }
      - "Pilot Related"
      - "Rogue"
      - "Science"
      - { name: "Technical", bonus: 5 }
      - "Weapon Proficiencies"
      - { name: "Wilderness", bonus: 5 }
    note: "Select seven ''other'' skills. Domestic, Military and Physical: none (Physical - see natural abilities). Pilot: any except robot and power armor. Espionage: Escape and Intelligence only. All new skills start at level one proficiency."
    schedule: [{ level: 3, count: 1 }, { level: 6, count: 1 }, { level: 9, count: 1 }, { level: 12, count: 1 }]
  secondary_skills:
    count: 6
    categories:
      - "Communications"
      - "Electrical"
      - { name: "Espionage", only: ["Escape Artist", "Intelligence"] }
      - "Mechanical"
      - "Medical"
      - { name: "Pilot", except: ["Robots & Power Armor", "Robot Combat: Basic", "Robot Combat Elite", "Robot Combat Elite: Glitter Boy", "Robot Combat Elite: SAMAS", "Robot Combat Elite: T-31 Super Trooper", "Robot Combat Elite: X-10A Predator", "Robot Combat Elite: X-535 Jager", "Robot Combat Elite: X-545 Super Jager", "Robot Combat Elite: X-1000 Ulti-Max", "Robot Combat Elite: X-2000 Dyna-Max", "Robot Combat Elite: X-2500 Black Knight", "Robot Combat Elite: X-60 Flanker", "Robot Combat Elite: X-500 Forager"] }
      - "Pilot Related"
      - "Rogue"
      - "Science"
      - "Technical"
      - "Weapon Proficiencies"
      - "Wilderness"
    note: "Six secondary skills from the related list, without the parenthetical bonuses."
equipment_starting:
  - { choose: 1, label: "Techno-Wizard weapon", qty: 1, from: ["manoan-flamer-pistol", "manoan-stun-pistol", "manoan-sk-stun-gun", "manoan-fireball-rifle"] }
special_abilities:
  - name: "Prehensile Tail"
    description: "Prehensile feet, tail and tentacles. +5 to strike with the tail (in place of the +3 general strike bonus when striking with it)."
  - { choose: 1, from: ["Psionic Orientation: Healer", "Psionic Orientation: Sensitive", "Psionic Orientation: Explorer", "Psionic Orientation: Warrior"] }
  - name: "Psionic Orientation: Healer"
    description: "Master psionic. Has Mind Block, Telepathy, See Aura, Bio-Regeneration (self), Healing Touch, Psychic Diagnosis and Bio-Manipulation. Plus five more Healing powers, three Sensitive and three Super. One additional Healing or Super power every three levels, starting at level three. I.S.P.: M.E. number plus 4D6x10, +10 per level of experience."
    psionics:
      type: "master"
      isp_base: "4d6x10 plus M.E. attribute number, +10 per additional level of experience"
      powers: ["Mind Block", "Telepathy", "See Aura", "Bio-Regeneration", "Healing Touch", "Psychic Diagnosis", "Bio-Manipulation (the evil eye)"]
      powers_starting: 11
      powers_starting_groups:
        - { count: 5, categories: ["Healing"] }
        - { count: 3, categories: ["Sensitive"] }
        - { count: 3, categories: ["Super"] }
      powers_schedule:
        - { level: 3, count: 1, categories: ["Healing", "Super"] }
        - { level: 6, count: 1, categories: ["Healing", "Super"] }
        - { level: 9, count: 1, categories: ["Healing", "Super"] }
        - { level: 12, count: 1, categories: ["Healing", "Super"] }
        - { level: 15, count: 1, categories: ["Healing", "Super"] }
  - name: "Psionic Orientation: Sensitive"
    description: "Master psionic. Has Mind Block Auto-Defense, Telepathy, Empathy, See Aura, Presence Sense, Sense Magic and Ectoplasm. Plus six more Sensitive powers, two Healing, two Physical and three MIND-type Super powers (no kinesis of any kind). One additional Sensitive or Super power every three levels, starting at level three. I.S.P.: M.E. number plus 3D6x10, +10 per level of experience."
    psionics:
      type: "master"
      isp_base: "3d6x10 plus M.E. attribute number, +10 I.S.P. per additional level of experience"
      powers: ["Mind Block Auto-Defense", "Telepathy", "Empathy", "See Aura", "Presence Sense", "Sense Magic", "Ectoplasm"]
      powers_starting: 13
      powers_starting_groups:
        - { count: 6, categories: ["Sensitive"] }
        - { count: 2, categories: ["Healing"] }
        - { count: 2, categories: ["Physical"] }
        - { count: 3, categories: [{ name: "Super", except: ["Electrokinesis", "Hydrokinesis", "Pyrokinesis", "Telekinesis (Super)", "Telekinetic Acceleration Attack", "Telekinetic Force Field"] }], note: "Three MIND-type Super powers, no kinesis of any kind. The kinesis powers are excluded; ''mind type'' is not enforced, so keep the picks to mental powers." }
      powers_schedule:
        - { level: 3, count: 1, categories: ["Sensitive", "Super"] }
        - { level: 6, count: 1, categories: ["Sensitive", "Super"] }
        - { level: 9, count: 1, categories: ["Sensitive", "Super"] }
        - { level: 12, count: 1, categories: ["Sensitive", "Super"] }
        - { level: 15, count: 1, categories: ["Sensitive", "Super"] }
  - name: "Psionic Orientation: Explorer"
    description: "Master psionic. Has Mind Block, Telepathy, See Aura, Astral Projection, Object Read, Telemechanics, Impervious to Cold, Impervious to Fire and Resist Fatigue. Plus four Physical powers, two Sensitive and three Super (any). One additional power from any psionic category every two levels, starting at level two. I.S.P.: M.E. number plus 3D6x10, +10 per level of experience."
    psionics:
      type: "master"
      isp_base: "3d6x10 plus M.E. attribute number, +10 per additional level of experience"
      powers: ["Mind Block", "Telepathy", "See Aura", "Astral Projection", "Object Read (Psychometry)", "Telemechanics", "Impervious to Cold", "Impervious to Fire", "Resist Fatigue"]
      powers_starting: 9
      powers_starting_groups:
        - { count: 4, categories: ["Physical"] }
        - { count: 2, categories: ["Sensitive"] }
        - { count: 3, categories: ["Super"] }
      powers_schedule:
        - { level: 2, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
        - { level: 4, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
        - { level: 6, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
        - { level: 8, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
        - { level: 10, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
        - { level: 12, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
        - { level: 14, count: 1, categories: ["Healing", "Physical", "Sensitive", "Super"] }
  - name: "Psionic Orientation: Warrior"
    description: "Master psionic. Has Mind Block Auto-Defense, Telepathy, See Aura, Sixth Sense, Death Trance, Alter Aura, Impervious to Fire, Summon Inner Strength and Resist Fatigue. Plus four Physical powers, two kinds of (Super) kinesis and three other Super powers. One additional power from any category except Healing every three levels, starting at level three. I.S.P.: M.E. number plus 4D4x10, +10 per level of experience."
    psionics:
      type: "master"
      isp_base: "4d4x10 plus M.E. attribute number, +10 per additional level of experience"
      powers: ["Mind Block Auto-Defense", "Telepathy", "See Aura", "Sixth Sense", "Death Trance", "Alter Aura", "Impervious to Fire", "Summon Inner Strength", "Resist Fatigue"]
      powers_starting: 9
      powers_starting_groups:
        - { count: 4, categories: ["Physical"] }
        - { count: 2, categories: [{ name: "Super", only: ["Electrokinesis", "Hydrokinesis", "Pyrokinesis", "Telekinesis (Super)"] }], note: "Two types of kinesis (Super)." }
        - { count: 3, categories: ["Super"], note: "Three other Super psionic powers." }
      powers_schedule:
        - { level: 3, count: 1, categories: ["Physical", "Sensitive", "Super"] }
        - { level: 6, count: 1, categories: ["Physical", "Sensitive", "Super"] }
        - { level: 9, count: 1, categories: ["Physical", "Sensitive", "Super"] }
        - { level: 12, count: 1, categories: ["Physical", "Sensitive", "Super"] }
        - { level: 15, count: 1, categories: ["Physical", "Sensitive", "Super"] }
natural_abilities:
  - { name: "Prehensile feet, tail and tentacles", description: "Can grasp and manipulate with feet, tail and tentacles." }
  - { name: "Double-jointed", description: "Double-jointed limbs." }
  - { name: "Ambidextrous", description: "Uses either hand equally well." }
  - { name: "Good color vision", description: "Good color vision." }
  - { name: "Keen hearing", description: "Keen hearing." }
  - { name: "Swim, climb and prowl", description: "Swim 50%, climb 70%, prowl 60%; granted as skills at those fixed percentages." }
restrictions:
  - "Magic: none. Relies on psionics, although a shaydor may collect and use magic items."
  - "The psionic orientation is chosen once, at creation, under Abilities; it is the character''s O.C.C. equivalent."
extraction_notes: |
  - Rifts World Book 6: South America, printed 103 (the whole entry is on that
    page; printed 102 is the Ewaipanomas and 104 carries no text). Read off the
    text layer and checked on a 150 dpi render of printed 103; every bonus,
    die code and percentage below matches the ink. The book notes the race is
    fully described in Rifts Atlantis; this is the South America printing and
    no shaydor class existed in production before it.
  - THE FOUR PSIONIC ORIENTATIONS ARE FOUR CHOOSABLE ABILITIES, NOT VARIANTS.
    They differ in I.S.P. formula, granted powers, starting splits and level
    ladder, and a variant cannot carry `psionics` (VARIANT_OVERRIDES), while
    `isp_base` lives inside `psionics` rather than being a pool base. So the
    class carries NO class-level psionics block and each orientation carries a
    complete master-psionic block - the shape the Gypsy Gifted uses.
  - Powers the book grants outright are `powers`; the "plus select" counts are
    `powers_starting_groups`, so `powers_starting` is the number PICKED, not
    counting the granted ones (Healer 11, Sensitive 13, Explorer 9, Warrior 9).
    "Every three levels, starting at level three" is levels 3, 6, 9, 12, 15;
    the Explorer''s "every two levels, starting at level two" is 2 through 14.
  - Name mapping to catalog rows: bio-regeneration (self) is the Healing row
    "Bio-Regeneration", not the Super one; bio-manipulation is
    "Bio-Manipulation (the evil eye)"; object read is "Object Read
    (Psychometry)". Mind Block Auto-Defense and Telemechanics are filed as
    Super in the catalog; Resist Fatigue as Healing. They are granted by name,
    so the category does not matter to the grant.
  - SENSITIVE: "three mind type powers from super psionics (no kinesis of any
    kind)". The kinesis rows are excluded by name (Electrokinesis,
    Hydrokinesis, Pyrokinesis, Telekinesis (Super), and the two telekinetic
    Super rows, Telekinetic Acceleration Attack and Telekinetic Force Field).
    "Mind type" has nothing in the catalog to filter on and is left to the
    player, stated in the group note.
  - WARRIOR: "two types of kinesis (super)" is an `only` of the four kinesis
    rows the Super category holds. The two telekinetic attack/field rows are
    not offered there, being uses of telekinesis rather than kinds of kinesis;
    they remain available among the three other Super powers.
  - The Sensitive''s I.S.P. is printed "M.E. level plus 3D6X10"; the other three
    say "M.E. number". Read as the M.E. attribute number, a misprint.
  - The Sensitive''s isp_base is worded differently from the Explorer''s
    identical formula only so no two strings in this file are byte-identical;
    they are the same formula.
  - No experience table: the book prints none for the shaydor. The survey''s
    plan was to borrow the Mind Melter''s ladder, but `mind-melter` stores no
    xp_table in production (checked --remote 2026-09-25), so none is stored.
  - No starting money, P.P.E., S.D.C. or hit point formula is printed; the race
    is an M.D.C. being (2D4x10+20). `men_of_arms: false`, as for every race.
  - SKILLS: this R.C.C. prints its own related and secondary skills and is
    played without an O.C.C. (the orientations stand in for one), so both
    blocks are stored as printed. Writing (+10%) is stored as Creative Writing,
    the catalog''s only writing row. Native Shaydorian is Language: Native
    Tongue at 98%; Dragonese/Elf is Language: Dragonese at 98%.
  - Swim 50%, climb 70% and prowl 60% are printed as natural abilities with no
    progression; they are granted as Swimming, Climbing and Prowl at those
    fixed percentages with no per-level gain.
  - Espionage "Escape and intelligence only" is Escape Artist and
    Intelligence. Pilot "any, except robot and power armor" excludes
    Robots & Power Armor and every Robot Combat row. Horsemanship is not on
    the printed list and is not offered.
  - Bonuses: "+2 to roll with punch, fall and impact" is `roll`; "+10% to
    save vs coma/death" is coma_death_pct. The +5 to strike with the tail is
    conditional and is in the Prehensile Tail ability, not in `bonuses`.
  - No Hand to Hand is printed, and no upgrade price; none is granted.
  - Equipment: "one or two TW weapons" is stored as one choice among the four
    Manoan TW weapons this book prints; the optional second is not stored.
  - Size 7 to 10 feet, weight 100 lbs; Horror Factor 12.
---

# Shaydor Spherian

## Lore

The shaydor are gentle, long-limbed, crystalline D-bees that the Splugorth
have held as slaves for millennia. They are usually met as small bands of
travelers or as servants of alien masters. A wandering tribe settled in Manoa
roughly two centuries ago, drawn by the city''s reputation for fairness, and
over the last hundred years their numbers there have exploded; they are now
among the most numerous and influential peoples of the city.

Every shaydor is a master psionic, and each follows one of four orientations
- Healer, Sensitive, Explorer or Warrior - which serves as its occupation.
They use no magic of their own, though they will collect and use magic items,
and shaydor of Manoa usually carry one or two Techno-Wizard weapons.

## GM Notes

The race is fully described in Rifts Atlantis. Choose the orientation under
Abilities at creation; it sets the I.S.P. formula, the granted powers and the
level ladder.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'shaydor-spherian');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'shaydor-spherian';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-shaydor-spherian-class.sql');
