-- The Kankoran R.C.C., Rifts Conversion Book One p.80-82.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-rifts-kankoran-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'rifts-kankoran', 'Kankoran', 'rifts', '---
id: rifts-kankoran
name: Kankoran
system: rifts
source_book: Rifts Conversion Book One p.80-82
category: rcc
men_of_arms: false
occ_restrictions:
  except: ["operator", "coalition-samas-pilot", "cs-rpa-fly-boy-ace", "ngr-power-armor-commando", "fq-side-kick-rpa", "glitter-boy", "fq-descended-glitter-boy-pilot", "fq-glitter-girl-pilot", "combat-cyborg", "cs-cyborg-strike-trooper", "destroyer-borg", "fq-cyborg-soldier", "fq-cyborg-dervish", "fq-cyborg-imprimer", "fq-cyborg-leviathan", "fq-cyborg-slasher", "mining-borg", "ngr-cyborg-soldier", "ojahee-borg", "plains-borg", "crazy", "ultra-crazy", "juicer", "coalition-juicer", "delphi-juicer", "dragon-juicer", "euro-juicer", "hyperion-juicer", "juicer-assassin", "juicer-gladiator", "juicer-scout", "maxi-killer", "mega-juicer", "phaeton-juicer", "titan-juicer"]
  note: "Technically any O.C.C., the Coalition Dog Pack included, but there is likely never to be a Kankoran Operator or power armor pilot, and no Kankoran will willingly submit to cybernetic, bionic or any other unnatural augmentation. The ids are the Operator, the power armor and Glitter Boy pilots, and every full conversion ''Borg, Crazy and Juicer O.C.C. in the catalog."
attribute_dice:
  IQ: "3d6"
  ME: "2d6"
  MA: "2d6"
  PS: "3d6"
  PP: "4d6"
  PE: "4d6"
  PB: "3d6"
  Spd: "4d6"
hit_points_base: "P.E. + 1D6 per level"
ppe_base: "4d6"
horror_factor: 12
bonuses:
  pools: { sdc: 20 }
  combat: { initiative: 3, pull_punch: 2, attacks: 1 }
  saves: { horror_factor: 1 }
  at_level:
    - { level: 2, saves: { horror_factor: 1 } }
    - { level: 3, saves: { horror_factor: 1 } }
    - { level: 5, saves: { horror_factor: 1 } }
    - { level: 7, saves: { horror_factor: 1 } }
    - { level: 9, saves: { horror_factor: 1 } }
    - { level: 11, saves: { horror_factor: 1 } }
    - { level: 13, saves: { horror_factor: 1 } }
    - { level: 15, saves: { horror_factor: 1 } }
skills:
  occ_skills:
    - { name: "Language: Other", base: 98, per_level: 0, note: "Wolfen, spoken at 98%; illiterate. The catalog has no Wolfen language row." }
    - { name: "Language: Gobblely", base: 98, per_level: 0, note: "Gobblely at 98%." }
    - { choose: 1, from: ["W.P. Archery", "W.P. Axe", "W.P. Blunt", "W.P. Chain", "W.P. Forked", "W.P. Knife", "W.P. Lance", "W.P. Pole Arm", "W.P. Shield", "W.P. Spear", "W.P. Staff", "W.P. Sword", "W.P. Whip"], note: "One extra Ancient W.P." }
natural_abilities:
  - name: "Natural Armor Rating"
    description: "6, and only in S.D.C. combat: an S.D.C. attack that rolls 6 or less to strike does no damage even if it hits. No M.D.C. - a Kankoran needs M.D.C. body armor like a human, and most prefer light and medium armor, often homespun."
  - name: "Nightvision"
    description: "40 feet (12.2 m), with keen color vision a bit better than human 20/20."
  - name: "Track Blood Scent"
    description: "Track blood scent up to 1000 feet (305 m) away. Base Skill: 30% +4% per level of experience."
  - name: "Recognize Common Smells"
    description: "Recognize common and known smells. Base Skill: 50% +3% per level of experience."
  - name: "Recognize Scent of Others"
    description: "Recognize the scent of others up to 50 feet (15.2 m) away. Base Skill: 20% +4% per level of experience."
  - name: "Keen Hearing"
    description: "Same as a Dog Boy. Unlike Dog Boys, Palladium canines cannot sense the supernatural or magic."
  - name: "Espionage and Wilderness Aptitude"
    description: "+5% to any Espionage or Wilderness skill. Apply by hand."
  - name: "Damage"
    description: "Bite 1D6 S.D.C.; claws 1D6 S.D.C. + P.S. bonus. Attacks per melee are as per Hand to Hand and other skills, plus the racial bonus attack."
  - name: "Horror/Awe Factor"
    description: "12, at least when seen in combat or when angry or threatening."
restrictions:
  - "Most Kankoran avoid mechanical, machine and robot or vehicle based skills; even those raised on Rifts Earth learn only the most basic modern skills - Computer Operation, Radio: Basic, Pilot Hovercycle and the like."
  - "Kankoran hate magic, though there is the occasional little mage."
extraction_notes: |
  - Rifts Conversion Book One printed 80-82 (file p081-p083). No Palladium Fantasy row exists for the Kankoran; the id carries the `rifts-` prefix batch 1 used, because a Palladium Fantasy conversion could later claim the plain id.
  - S.D.C. is "20 plus those gained from the O.C.C. and physical skills", so it is a POOL BONUS rather than sdc_base.
  - The Horror Factor save is "+1 at levels 1, 2, 3, 5, 7, 9, 11, 13 and 15", stored as a level-one bonus plus eight at_level steps. "+1 additional attack per melee round" is a flat combat bonus.
  - The natural A.R. of 6 and the +5% Espionage/Wilderness bonus are prose: the app has no natural armor field and no race-level per-skill modifier.
  - The "R.C.C. Skills" line is granted as occ_skills; Wolfen has no language row, so it is `Language: Other`. The extra Ancient W.P. is the same choice list as `rifts-wolfen`.
  - occ_restrictions is read from the "O.C.C.s Rifts" line. It says "technically any O.C.C." and then rules out the Operator, power armor pilots, and any cybernetic, bionic or other unnatural augmentation - so the except list names the Operator, the power armor and Glitter Boy pilots, and every full conversion ''Borg, Crazy and Juicer O.C.C. the catalog holds. "Most avoid" robot and vehicle skills is a tendency, not a bar, so robot pilots are not excepted. An O.C.C. of any named kind imported later is allowed until it is added.
  - Psionics: "Standard, basically same as humans", so no psionics block.
  - The section-wide rule on printed 74 - a new arrival from the Palladium World picks up the regional language and two Modern W.P.s within weeks, then three Rifts skills from Communications, Pilot (basic vehicles), Technical and W.P. Modern after 2D4+4 months or one level, and one more language or skill every two levels - applies to a character who came from Palladium rather than one raised on Rifts Earth. It is not stored; the survey carries it.
---

# Kankoran

## Lore

The Kankoran are humanoid foxes - four to five and a half feet of luscious red fur with a white-tipped tail - who live simple, Spartan lives as hunters and woodsmen in harmony with nature. Gentle and loving among their own kind, their society is still harsh: every youth passes a rite of passage, often six months to a year alone off the land, and takes a name from it (Leftside-Wound, Mountain Shadow, Knife Handle). They call scars "stripes" and respect anyone with a good collection. Legend says the Elves created them, so they honor Elves and get along with the gentler Faerie Folk and elemental spirits. Outsiders who undergo a Kankoran rite are accepted completely, and Kankoran often adopt stray children of any race.

They are not dimensional travelers, so any Kankoran on Rifts Earth is there by accident or for a compelling reason, and more than half a dozen in one place is unlikely. Courageous and kind, a Kankoran will come to the aid of anyone in need.

**Alignment:** Any, but tend toward good and Unprincipled.

**Size:** Four to five feet plus 1D6 inches (about 1.2 to 1.6 m). **Weight:** 80 to 140 pounds (36 to 63 kg).

**Average Life Span:** 45+ years.

**Habitat:** Theoretically anywhere, but prefers forests; on the Palladium World most live in the northern forests and mountains.

## GM Notes

Kankoran should find Native Americans and Wild Psi-Stalkers kindred spirits, and get along with Druids, Cyber-Knights, Sasquatch, the Lyn-Srial, mutant animals, Faerie Folk and forest peoples - more comfortable among animal-looking D-Bees than humans. Warriors inside robots, power armor and armored vehicles strike them as cowards; they take an instant dislike to cruel savages like the Simvan and Brodkil, and see Calgary''s Kingdom of Monsters, vampires, the Federation of Magic, the Splugorth and the Gargoyle and Brodkil Empires as evil. They have no formal enemies but hate tormentors, slavers and destroyers. The Wolfen employ them as scouts. On Palladium they carry obsidian daggers and spears; on Rifts Earth they use Vibro-Blades, energy and Techno-Wizard weapons and light body armor.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'rifts-kankoran');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'rifts-kankoran';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-rifts-kankoran-class.sql');
