-- Rifts World Book 20: Canada, batch 2a: gear. 45 new gear rows.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local  apps/character-creator/db/add-canada-gear.sql
--   node scripts/d1-apply.mjs --remote apps/character-creator/db/add-canada-gear.sql
--
-- ALL 45 ARE NEW - catalog-diff --table gear --remote and a slug query,
-- 2026-10-02. The survey is apps/character-creator/docs/surveys/canada.md.
-- Pages are printed folios; the cache page is the folio plus one
-- (scripts/books.json).
--
--   3   weapons unique to the Cyber-Horsemen of Ixion          printed 107
--   7   Momano anti-supernatural supplies and the bionic
--       Hydraulic Stake Driver                                 printed 125-126
--   8   Techno-Wizard bionic weapons                           printed 126-129
--   6   Inuit amulets, 11 talismans, 3 special items           printed 185-187
--   6   Tundra Ranger armor, the turret, the Sky Pack and
--       the two grades of Fury Beetle armor                    printed 187-192
--   1   the dog sled                                           printed 31
--
-- A RANGE STORES ITS LOW END, with the full range in cost_note or the
-- description (gear.cost in db/schema.sql). Fury Beetle armor is two rows
-- because the two grades print their own M.D.C., weight and price.
--
-- A TW BIONIC WEAPON'S COST is the Techno-Wizard conversion figure. The book
-- prices each as the standard cost of the bionic weapon plus the conversion,
-- and the base weapon varies. The Flaming Retractable Sword prints two
-- conversion figures, 55,000 in its creation stats and 70,000 under its
-- weapon stats; the first is stored and the note carries both.
--
-- THE INUIT ITEMS ARE NOT SOLD. cost is NULL and the creation cost (P.P.E.
-- and hours) is the cost_note. mdc 60 is the figure the book gives for most
-- amulets and talismans; the three special items print none and store none.
-- The book's Demon Mask is named Inuit Demon Mask here because the catalog
-- already holds a Demon-Mask from another book.
--
-- TWO PAGES ARE FLAGGED CORRUPT IN THE MANIFEST and their numbers were read
-- off renders: printed 129 (the Electro-Blaster's weapon stats and the
-- Flaming Retractable Sword) and printed 187 (both Ranger armors and the
-- TR-500 turret). The renders agree with the cache on every figure stored.
-- THE DIGIT CIPHER lands on the talismans' hours (1D4x10, 1D6x10, 2D4x10,
-- 4D4x10) and on the turret's 1D6x10 and 1D4x10; each is read as the dice it
-- can only be.
--
-- NOT HERE, and why:
--   Homemade M.D.C. Armor (printed 191-192)  held from Warlords of Russia
--       p.173, the same entry. This book prints 30-40 for the light grade
--       where that one prints 30-45; the held rows are left alone.
--   Skis and the communication helmet (192)  held: Skis: Downhill and Skis:
--       Cross-Country at the same prices, and Communications Helmet.
--   Tundra Ranger Energy Weapons (187)       a pointer to the core book's
--       early Coalition weapons, not new items.
--   The four vehicles                        add-canada-vehicles.sql.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('ixion-energy-weapon-rod', 'Ixion Energy Weapon Rod', 'rifts', 'weapon', NULL, 300000, 'Value 300,000+ credits. Very rarely in any hands but the Cyber-Horsemen, who neither sell nor trade it; nobody beyond Saskatchewan and Montana has seen one. A weapon maker would pay over a million credits for one to study.', '1D6 M.D. as a spear or staff, 2D6 M.D. as a pole arm; energy blast 3D6 M.D.', 1, '1600 feet (488 m)', '10 blasts; the rod recharges one blast every 10 minutes', 'Each blast counts as one melee action/attack', NULL, NULL, 15, 'The Cyber-Horsemen of Ixion''s energy weapon: a sleek modern spear, pole arm or iron staff with an energized blade end, which also fires an energy blast from one end of the rod.', 'Rifts World Book 20: Canada p.107'),
('ixion-mini-energy-weapon-rod', 'Ixion Mini-Energy Weapon Rod', 'rifts', 'weapon', NULL, 300000, 'Value 300,000+ credits. Very rarely in any hands but the Cyber-Horsemen, who neither sell nor trade it; nobody beyond Saskatchewan and Montana has seen one. A weapon maker would pay over a million credits for one to study.', '2D6 M.D.', 1, '600 feet (183 m)', '10 blasts; the rod recharges one blast every 10 minutes', 'Each blast counts as one melee action/attack', NULL, NULL, NULL, 'A pistol version of the Ixion Energy Weapon Rod: a rod with a curved grip and trigger. It has only the energy blaster mode.', 'Rifts World Book 20: Canada p.107'),
('ixion-sensory-deprivation-web', 'Sensory Deprivation Web', 'rifts', 'weapon', NULL, NULL, 'No price printed. A weapon unique to the Cyber-Horsemen of Ixion.', 'None; penalties only', 0, 'Thrown', NULL, NULL, NULL, NULL, 3, 'A crackling energy net with bola-like weights, carried along the Cyber-Horseman''s back and thrown over a victim. It short circuits the senses: blurred vision, deafness and vertigo. Penalties: -5 on strike, parry, dodge and initiative, skills at -50% and speed halved, while inside the web and for 1D4+1 melees after getting free. Pulling free takes two melee actions and needs no cutting. The book abbreviates it SDW.', 'Rifts World Book 20: Canada p.107'),
('holy-water-spray-dose', 'Holy Water (spray dose)', 'rifts', 'gear', NULL, 10, '10 credits per dose. Some priests supply it free to vampire hunters helping innocent people.', '4D6 to vampires per spray', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A dose for the bionic forearm or mouth chemical spray (or a squirt gun style weapon): 4D6 damage per spray to vampires, and it may affect certain demons. A hose can feed the sprayer from a one gallon (7 lbs) or two gallon (14 lbs) container worn on the back, shoulder or hip. Ordinary water does 2D6 to vampires per three ounces and costs nothing where water is not scarce.', 'Rifts World Book 20: Canada p.125'),
('garlic-or-wolfbay-spray-dose', 'Garlic or Wolfbay Spray (dose)', 'rifts', 'gear', NULL, 2, 'Two credits per dose.', '1D6 to vampires, plus penalties', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A dose for the bionic chemical spray. In the face of a vampire it does 1D6 damage and the vampire takes -9 on strike, parry and dodge and -3 initiative, and forfeits one melee attack a round for 1D4+1 rounds. Mortals take no damage but take -2 on strike, parry and dodge and -1 initiative for 1D4 rounds, or until they wash their eyes out. Environmental armor, or a helmet, visor or goggles, is complete protection.', 'Rifts World Book 20: Canada p.125'),
('salt-spray-10-doses', 'Salt Spray (10 doses)', 'rifts', 'gear', NULL, 1, 'One credit per 10 doses.', '1D4 to creatures that hate salt', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Doses for the bionic chemical spray. Does 1D4 damage to creatures that hate salt, such as faerie folk, and costs them two melee actions as they cough and back away.', 'Rifts World Book 20: Canada p.125'),
('silver-plating-bionic-blade', 'Silver Plating (bionic blade or spike)', 'rifts', 'gear', NULL, 200, '200 credits for a small spike, knife or blade; 500 for a short sword; 900-1200 for a large sword. Add 50% to plate a Vibro-Blade. The small-blade figure is stored.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Silver plating for knuckle spikes, finger blades, razor fingernails, forearm blades, wrist or palm needles, Vibro-Blades and similar concealed melee weapons, for use against supernatural beings vulnerable to silver. The silver must be at least 85% pure to work.', 'Rifts World Book 20: Canada p.125'),
('silver-bullet-medium-large-caliber', 'Silver Bullet (medium to large caliber)', 'rifts', 'weapon', NULL, 50, 'Approximately 50-75 credits per round; the low end is stored. About 20% less where silver is common, 20-40% more where it is rare.', '3D6 to 6D6 S.D.C./H.P., by caliber', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A round of at least 85% silver, fired from a finger gun, a forearm weapon or as a shooting knuckle spike.', 'Rifts World Book 20: Canada p.125'),
('silver-bullet-small-caliber', 'Silver Bullet (small caliber)', 'rifts', 'weapon', NULL, 15, '15-25 credits per round; the low end is stored. About 20% less where silver is common, 20-40% more where it is rare.', '1D6 or 2D6 S.D.C./H.P.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A light round of at least 85% silver, fired from a finger gun, a forearm weapon or as a shooting knuckle spike.', 'Rifts World Book 20: Canada p.125'),
('bionic-hydraulic-stake-driver', 'Hydraulic Stake Driver (bionic)', 'rifts', 'cybernetics', NULL, 30000, '30,000 credits for the driver. Wooden stakes are five credits per set of nine.', '3D6 H.P./S.D.C.', 0, '15 feet (4.6 m)', 'Nine narrow stakes, reloaded automatically until used up; refilling the feed takes one melee round', NULL, NULL, NULL, NULL, 'A bionic weapon fitted to the forearm, or in place of a hand and wrist. A hydraulic hammer punches a wooden stake into whatever it is pressed against and releases it, an automatic feed sets the next stake, and it can also fire stakes. A stake in the heart or temple is fatal, and a vampire staked in the heart falls into suspended animation. Millennium Tree stakes double the damage against vampires and count as 4D6 M.D. against most other supernatural beings. Metal stakes or spikes can be substituted and do 1D4 M.D.', 'Rifts World Book 20: Canada p.125-126'),
('tw-magical-silver-plated-blades', 'TW Magical Silver-Plated Blades', 'rifts', 'weapon', NULL, 10000, 'The standard cost of the bionic weapon plus 10,000 credits for the Techno-Wizard conversion; the conversion figure is stored. Creation: 25 P.P.E.; typically Lantern Light or Globe of Daylight, and Aura of Power; a pink quartz or diamond power crystal; about 8 hours.', 'The weapon''s normal damage as Mega-Damage against supernatural beings and creatures of magic only; vampires take the normal H.P./S.D.C. damage', 1, 'Hand to hand', '4 P.P.E. or 8 I.S.P. activates the magic for 15 minutes', NULL, NULL, NULL, NULL, 'Silver-plated knuckle spikes, finger blades, forearm blades, claws and similar bionic hand to hand weapons, enchanted so that once activated they count as magic weapons for 15 minutes. Against Mega-Damage armor they do nothing unless the blade was an M.D. weapon to begin with, such as a Vibro-Blade. TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.126'),
('tw-finger-blaster', 'TW Finger Blaster', 'rifts', 'weapon', NULL, 55000, 'The standard cost of the bionic weapon plus 55,000 credits for the Techno-Wizard conversion; the conversion figure is stored. Creation: 38 P.P.E.; Energy Bolt and Fire Ball; a firing mechanism with a diamond worth 2000 credits or more; about 45 hours.', '3D6 M.D.', 1, '200 feet (61 m)', '7 P.P.E. or 14 I.S.P. per blast', NULL, NULL, NULL, NULL, 'A bionic finger blaster that fires a magical bolt of energy in place of a light laser. TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.126-127'),
('tw-hydraulic-stake-driver', 'TW Hydraulic Stake Driver', 'rifts', 'weapon', NULL, 90000, 'The standard cost of the bionic weapon plus 90,000 credits for the Techno-Wizard conversion; the conversion figure is stored. The TW shotgun version is 85,000 credits. Creation: 75 P.P.E.; Energy Bolt, Fly and Create Wood; topaz or yellow quartz; about 65 hours.', '3D6 H.P./S.D.C.; no damage to most M.D. creatures', 0, '15 feet (4.6 m); the shotgun 50 feet (15.2 m)', '4 P.P.E. or 8 I.S.P. loads two stakes', NULL, NULL, NULL, NULL, 'The bionic Hydraulic Stake Driver, except that pumping P.P.E. or I.S.P. into it conjures its wooden stakes from nothing. A TW shotgun version holds two stakes and reaches 50 feet (15.2 m). TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.127'),
('tw-sunbeam-blaster', 'TW Sunbeam Blaster', 'rifts', 'weapon', NULL, 125000, 'The standard cost of the bionic weapon plus 125,000 credits for the Techno-Wizard conversion; the conversion figure is stored. The pistol or revolver version is 110,000 credits. Bionic eyes take four times the time and cost. Creation: 30 P.P.E.; Energy Bolt and Globe of Daylight; a rose quartz; about 45 hours.', '1D6+2 to supernatural beings injured by sunlight; no damage to most creatures', 0, '600 feet (183 m)', '2 P.P.E. or 4 I.S.P. per blast', NULL, NULL, NULL, NULL, 'A laser in a finger, forearm or eye whose beam is turned into a bolt of sunlight. Harmless to humans; it damages vampires, Shadow Beasts, Russian Demons and any other being of darkness that is vulnerable to sunlight. A pistol or revolver version holds six shots and costs 12 P.P.E. or 24 I.S.P. to reload. TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.127'),
('tw-flaming-shooting-knuckle-spikes', 'TW Flaming, Shooting Knuckle Spikes or Bullets', 'rifts', 'weapon', NULL, 55000, 'The standard cost of the bionic weapon plus 55,000 credits for the Techno-Wizard conversion; the conversion figure is stored. The weapon stats also print 18,000 credits for the bionic weapon, and every round is enchanted ammunition at 15-30 credits. Creation: 38 P.P.E.; Energy Bolt and Fire Ball; a firing mechanism with a diamond worth 2000 credits or more; about 45 hours.', '3D6 M.D. each (3D6 H.P. to vampires)', 1, '200 feet (61 m)', '3 P.P.E. or 6 I.S.P. per flaming spike or projectile, plus the enchanted round', NULL, NULL, NULL, NULL, 'A seemingly conventional knuckle spike or bullet that bursts into flame a moment after launch, like a miniature fire ball. The same enchantment is sold as a bionic forearm weapon (100 rounds, 400 feet/122 m, 35,000 credits), a 14-shot pistol or six-shot revolver (200 feet/61 m, 3D6 M.D., 25,000 credits) and a rifle (1800 feet/548.6 m, 3D6 M.D., 55,000 credits). TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.128'),
('tw-watergun', 'TW Watergun', 'rifts', 'weapon', NULL, 45000, 'The standard cost of the bionic weapon plus 45,000 credits for the Techno-Wizard conversion; the conversion figure is stored. The TW pistol version is 50,000 credits. Creation: 60 P.P.E.; Energy Bolt, Fly and Create Water; blue quartz or blue sapphire; about 65 hours.', '2D6 H.P./S.D.C. to vampires; no damage to most other creatures', 0, '50 feet (15.2 m)', '8 P.P.E. or 16 I.S.P. makes one gallon of water, or 30 shots', NULL, NULL, NULL, NULL, 'A bionic forearm weapon that squirts a stream of magically generated water, with no reservoir. A TW pistol version has the same range. TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.128'),
('tw-electro-blaster', 'TW Electro-Blaster', 'rifts', 'weapon', NULL, 100000, 'The standard cost of the bionic weapon plus 100,000 credits for the Techno-Wizard conversion; the conversion figure is stored. The pistol or revolver version is 50,000 credits. Creation: 30 P.P.E.; Energy Bolt, Electric Arc and Power Weapon; copper wire and plating; about 65 hours.', 'Electric Arc 2D6 (the entry''s text says 2D6 M.D.); Electro-Fist 2D6 M.D. plus the cyborg''s normal punch damage', 1, 'Forearm weapon or handgun 200 feet (61 m); the hand is melee only', '8 P.P.E. or 16 I.S.P. per arc, or to activate the Electro-Fist', NULL, NULL, NULL, NULL, 'A bionic forearm weapon or a bionic hand, never both. As a hand (which can have no other bionic feature) it is wrapped in electricity for one melee round, the Electro-Fist; even a gentle touch does 1D6 M.D. As a forearm weapon it fires a short electrical arc. A pistol or revolver version holds six shots and costs 12 P.P.E. or 24 I.S.P. to reload. TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.128-129'),
('tw-flaming-retractable-sword', 'TW Flaming Retractable Sword', 'rifts', 'weapon', NULL, 55000, 'The standard cost of the bionic weapon plus 55,000 credits for the Techno-Wizard conversion; the conversion figure is stored. THE BOOK PRINTS TWO FIGURES: 55,000 in the creation stats and, under the weapon stats, 30,000 for the bionic weapon plus 70,000 for the conversion. Creation: 85 P.P.E.; Fire Bolt and Power Weapon; two rubies worth 1000 credits each; about 60 hours.', '4D6 M.D.', 1, 'Hand to hand', '7 P.P.E. or 14 I.S.P. to activate', NULL, NULL, NULL, NULL, 'A seemingly ordinary retractable blade or Vibro-Blade, no smaller than a short sword, that becomes a magical flaming sword for two minutes (8 melee rounds). Activating it counts as one melee action. The book heads the entry Flaming Retractable Sword. TW bionics work only for a character with few bionics: a partial cyborg with 8-12 implants and two bionic limbs spends 30% more P.P.E. or I.S.P. at half range and duration, and anyone with more cannot use them.', 'Rifts World Book 20: Canada p.129'),
('inuit-amulet-bison', 'Inuit Amulet: Bison/Buffalo', 'rifts', 'magic', NULL, NULL, 'Not sold. Amulet creation cost: 275 P.P.E. and 1D6+6 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Bison fur and horn. +2 to save vs all types of magic. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-amulet-eagle', 'Inuit Amulet: Eagle', 'rifts', 'magic', NULL, NULL, 'Not sold. Amulet creation cost: 295 P.P.E. and 1D6+6 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Eagle skin and feathers. The wearer can see and speak to spirits, entities and the invisible. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-amulet-raven', 'Inuit Amulet: Raven', 'rifts', 'magic', NULL, NULL, 'Not sold. Amulet creation cost: 290 P.P.E. and 1D6+6 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Raven bones and feathers. Impervious to possession and +1 to save vs illusions. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-amulet-seal', 'Inuit Amulet: Seal', 'rifts', 'magic', NULL, NULL, 'Not sold. Amulet creation cost: 225 P.P.E. and 1D6+10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Seal skin. The wearer walks among seals without frightening them, and once every seven days can take one without resistance; trying for a second scatters them and drives the sea animals from the area for 2D6 days. Impervious to frostbite and hypothermia in the Arctic. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-amulet-snake', 'Inuit Amulet: Snake', 'rifts', 'magic', NULL, NULL, 'Not sold. Amulet creation cost: 250 P.P.E. and 1D6+4 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Snake skin or skull. Snake bites and snake venom do nothing; +4 on saves against any poison, +2 against drugs and disease. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-amulet-walrus', 'Inuit Amulet: Walrus', 'rifts', 'magic', NULL, NULL, 'Not sold. Amulet creation cost: 250 P.P.E. and 1D6+6 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Walrus skin. The wearer can swim in the icy sea or walk in snow without feeling the cold. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-bear-claw-talisman', 'Bear Claw Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 590 P.P.E. and 1D4x10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Run at 30 mph (48 km), a supernatural P.S. of 24 (punches and kicks 2D6 M.D.; a power punch doubles it and counts as two attacks) and Mega-Damage skin of 100 M.D.C. Wearing any armor cancels the M.D.C. If the M.D.C. is used up the talisman breaks; otherwise it regenerates at midnight each day. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185'),
('inuit-bear-tooth-talisman', 'Bear Tooth Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 500 P.P.E. and 1D6x10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Recognize and follow the tracks of the polar bear''s prey at 88%. The first strike on the prey hits without error and does triple damage, with any weapon. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.185-186'),
('inuit-caribou-antler-talisman', 'Caribou Antler Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 550 P.P.E. and 1D4x10 hours to make, and the antler must be carved with designs and symbols.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Sense where caribou can be found; the wearer is taken as a brother, can mount a wild caribou as a rider would a horse, and the herd follows. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-eagle-feather-talisman', 'Eagle Feather Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 580 P.P.E. and 1D4x10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'See and speak to spirits, entities and the invisible, constantly. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-eagle-claw-talisman', 'Eagle Claw Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 600 P.P.E. and 1D6x10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Arrows from the wearer''s bow fly double the usual distance at +2 to strike and do double damage, and do their normal damage (typically 2D6) as M.D. to supernatural beings, demons, entities and ghostly spirits. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-raven-claw-talisman', 'Raven Claw Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 700 P.P.E. and 2D4x10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Punches and kicks do their S.D.C. damage as M.D. to spirits, demons, entities, vampires and animated dead; a power punch does triple damage and counts as two melee actions. It also works as a holy symbol, holding at bay creatures such symbols affect, vampires included. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-turtle-shell-talisman', 'Turtle Shell Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 500 P.P.E. and 1D6x10 hours to make.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'A protective aura of 40 M.D.C., +6 for each of the Shaman''s levels (the item itself has 60, as stored). Armor above 50 M.D.C. cancels the aura. If the aura''s M.D.C. is used up the talisman breaks; otherwise it regenerates with each new tide. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-walrus-tusk-talisman', 'Walrus Bone or Tusk Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 595 P.P.E. and 1D4x10 hours to make, and the bone or tusk must be carved and engraved.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Swim like a walrus: dive 300 feet (91 m), survive to 600 feet (183 m), swim at 30 mph (48 km), see clearly in murky water, hold the breath six minutes, float effortlessly, and impervious to cold. Indefinite, at will. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-whale-bone-talisman', 'Whale Bone Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 660 P.P.E. and 1D6x10 hours to make, and the bone must be carved and engraved.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Swim like a whale: dive 1000 feet (305 m), survive to two miles (3.2 km), swim at 40 mph (64 km), see in murky and dark water, hold the breath ten minutes, float effortlessly, impervious to cold, and a supernatural P.S. of 40 while in the sea. Indefinite, at will. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-wolf-bone-talisman', 'Wolf Bone Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 650 P.P.E. and 1D6x10 hours to make, and the bone must be carved and engraved.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Transform into a Timber Wolf with all the animal''s abilities and a man''s mind, without speech; no time limit, back at will, once per 24 hours. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-wolf-teeth-talisman', 'Wolf Teeth or Skull Talisman', 'rifts', 'magic', NULL, NULL, 'Not sold. Talisman creation cost: 500 P.P.E. and 1D4x10 hours to make, and the bone must be carved and engraved.', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Track the wolf''s prey by sight and smell as well as the animal does. Works only for the Angakoq who made it or the person he gives it to, and the magic ends when either dies. One amulet and one talisman at most are worn at a time, and after one is taken off another of its kind does not work for 24 hours. It can be destroyed only by an attack aimed at the item itself (-6 to strike while worn).', 'Rifts World Book 20: Canada p.186'),
('inuit-bears-coat', 'The Bear''s Coat', 'rifts', 'magic', NULL, NULL, 'Not sold. Creation cost: 900 P.P.E. and 2D4x10 hours to make. Very rare; usually needs the P.P.E. of the Shaman, his Tornaq and a ley line nexus at a moment of power.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'The full skin of a Brown or Grizzly Bear. Put on, it turns the wearer into a huge bear with all the abilities of an M.D.C. mutant bear and a man''s mind, without speech; taking it off ends the magic. Twice per 24 hours. Only an Angakoq can make or use it.', 'Rifts World Book 20: Canada p.186'),
('inuit-demon-mask', 'Inuit Demon Mask', 'rifts', 'magic', NULL, NULL, 'Not sold. Creation cost: 660 P.P.E. and 2D4x10+60 hours to make.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A monstrous face of wood or a large animal''s skull, painted and set with bear or wolf teeth, walrus tusk and raven or eagle feathers. Demons see the wearer as a fellow demon. An antlered version, worn in a half hour ceremonial dance, drives every lesser demon and entity out of a 1D6 mile radius (+1 mile per level of the Shaman) for 1D6 days +1 per level; any that stay gone past nine days probably do not come back. The book heads the entry Demon Mask.', 'Rifts World Book 20: Canada p.186'),
('inuit-spirit-catcher', 'Spirit Catcher', 'rifts', 'magic', NULL, NULL, 'Not sold. Creation cost: 700 P.P.E. and 4D4x10 hours to make.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A carving with two eagle or raven heads on a cord, which the Shaman whirls overhead. Exorcism is at +30%, with no risk of the participants being possessed. Swung the same way it catches and holds poltergeists and other lesser haunting entities inside 100 feet (30.5 m), two per level of the Angakoq, until he swings it the other way to release them; those it cannot hold are revealed to him.', 'Rifts World Book 20: Canada p.186-187'),
('legion-tundra-body-armor', 'Legion Tundra Body Armor', 'rifts', 'armor', 10, 35000, 'Only the Tundra Rangers have it and they are not selling; open-market value 35,000 credits or more.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 60, 'The light, high-tech padded armor of the Tundra Rangers, worn over the Thermal-Armor Body Suit, as a full environmental system (heat resistance about 30% below normal) or a non-environmental one. 60 M.D.C. in all: 40 from the Legion armor and 20 from the Thermal-Armor. Many Rangers swap the full combat helmet (50 M.D.C.) for a thermal cap or hood (8 M.D.C.), goggles and an air filter. Excellent mobility: -5% to prowl, swim, acrobatics and gymnastics.', 'Rifts World Book 20: Canada p.187'),
('thermal-armor-body-suit', 'Thermal-Armor Body Suit', 'rifts', 'armor', 8, NULL, 'Only the Tundra Rangers have it and they are not selling.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 20, 'An insulated flight suit of a pre-Rifts M.D.C. fabric, thinly padded in places, worn under Legion Tundra Body Armor, under power armor, or alone. A light helmet (30 M.D.C.) makes it a super-lightweight environmental armor. Superior mobility, no penalties. Weight 8-10 pounds.', 'Rifts World Book 20: Canada p.187'),
('tr-500-heavy-laser-turret', 'TR-500 Tundra Ranger Heavy Laser Turret', 'rifts', 'weapon', NULL, NULL, 'No price printed; a fixed emplacement of the Tundra Rangers.', 'Laser 1D6x10 M.D. per blast. Mini-missiles 5D6 M.D. (fragmentation) or 1D4x10 M.D. (armor piercing), or smoke.', 1, 'Laser 4000 feet (1200 m); mini-missiles one mile (1.6 km)', 'Laser effectively unlimited on the base generators, with an auxiliary battery good for 80 blasts; 48 mini-missiles', 'Eight via the ADR system, or the gunner''s hand to hand attacks (usually 4-6)', NULL, NULL, 180, 'A pre-Rifts base-defense laser built into a low M.D.C. bunker manned by 2-4 soldiers, with a domed mini-missile launcher behind the gun and a second, smaller bunker for radar and sensors. It runs on Automated Defense Response, auto-fire or manual; 360 degree rotation and a 90 degree arc of fire. M.D.C. by location: main cannon 180 (stored), bunker housing 350, reinforced inner cockpit 100, mini-missile launcher 100, sensor array and radar unit 100, hatches (2) 100 each, the glass in the viewing slits 8. Two dozen at the Rangers'' headquarters near Fort Smith, ten at Regina and four at each smaller outpost.', 'Rifts World Book 20: Canada p.187'),
('legion-90-sky-pack', 'Legion-90 Sky Pack', 'rifts', 'gear', 30, 30000, 'Priced by engine: 30,000 credits gasoline, 50,000 electric, or 400,000 nuclear with a 10 year life. The gasoline figure is stored.', NULL, 0, 'Maximum speed 90 mph (144 km). Range 700 miles (1120 km) for gas or electric units; indefinite with nuclear power', NULL, NULL, NULL, NULL, 22, 'The Tundra Rangers'' all-purpose jet pack, held to the back of any Legion body armor by electromagnetic anchors and straps. No weapons; cannot be used underwater. 2.5 feet tall, 1.5 wide and one thick. A nuclear pack may overheat and burn out (01-40%) after more than six hours of continuous use and should cool for an hour after 4-6. The Rangers do not sell theirs, but equivalent packs are on the market.', 'Rifts World Book 20: Canada p.188'),
('fury-beetle-armor-partial', 'Fury Beetle Armor (Partial)', 'rifts', 'armor', 25, 10000, '10,000-14,000 credits; the low end is stored. Good availability even in wilderness regions.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 40, 'Homespun armor of the outer body plates and bone of the Fury Beetle, popular in central and eastern Canada; never environmental, and worn with a modern helmet (50 M.D.C.) with a built-in radio. The partial suit covers the chest, shoulders and other key areas. M.D.C. 40-50 (the low end is stored); weight 25-35 pounds. Fair to good mobility: -10% to prowl, climb, trick riding, swim, acrobatics and gymnastics.', 'Rifts World Book 20: Canada p.192'),
('fury-beetle-armor-full', 'Fury Beetle Armor (Full Plate)', 'rifts', 'armor', 50, 16000, '16,000-20,000 credits; the low end is stored. Good availability even in wilderness regions.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 75, 'Homespun full plate armor of the outer body plates and bone of the Fury Beetle; never environmental, and worn with a modern helmet (50 M.D.C.) with a built-in radio. M.D.C. 75-80 (the low end is stored); weight double the partial suit''s 25-35 pounds. -30% to prowl, climb, trick riding, swim, acrobatics and gymnastics.', 'Rifts World Book 20: Canada p.192'),
('dog-sled', 'Dog Sled', 'rifts', 'vehicle', NULL, 400, 'About 400-1000 credits for the sled; the low end is stored. An Inuit-built sled runs about 60 credits in materials, plus the work.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A narrow one or two-man sled pulled by six to nine dogs, driven standing at the rear, with a bed for packages, food and gear. It handles forest, tundra and glacier. Average speed 5-8 mph (8-13 km), sprinting at up to 30 mph (48 km) for a quarter hour; more than four speed runs in 24 hours risks lame, dead or balking dogs, and hard-pushed dogs need at least two hours of rest. Maximum load 600 lbs (270 kg) plus the driver and the sled. The dogs are priced separately.', 'Rifts World Book 20: Canada p.31');

-- Readbacks: each must return got = want. This script asserts its OWN rows.
SELECT 'all 45 Canada gear rows are in' AS assertion, count(*) AS got, 45 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 20: Canada p.%' AND slug IN ('ixion-energy-weapon-rod', 'ixion-mini-energy-weapon-rod', 'ixion-sensory-deprivation-web', 'holy-water-spray-dose', 'garlic-or-wolfbay-spray-dose', 'salt-spray-10-doses', 'silver-plating-bionic-blade', 'silver-bullet-medium-large-caliber', 'silver-bullet-small-caliber', 'bionic-hydraulic-stake-driver', 'tw-magical-silver-plated-blades', 'tw-finger-blaster', 'tw-hydraulic-stake-driver', 'tw-sunbeam-blaster', 'tw-flaming-shooting-knuckle-spikes', 'tw-watergun', 'tw-electro-blaster', 'tw-flaming-retractable-sword', 'inuit-amulet-bison', 'inuit-amulet-eagle', 'inuit-amulet-raven', 'inuit-amulet-seal', 'inuit-amulet-snake', 'inuit-amulet-walrus', 'inuit-bear-claw-talisman', 'inuit-bear-tooth-talisman', 'inuit-caribou-antler-talisman', 'inuit-eagle-feather-talisman', 'inuit-eagle-claw-talisman', 'inuit-raven-claw-talisman', 'inuit-turtle-shell-talisman', 'inuit-walrus-tusk-talisman', 'inuit-whale-bone-talisman', 'inuit-wolf-bone-talisman', 'inuit-wolf-teeth-talisman', 'inuit-bears-coat', 'inuit-demon-mask', 'inuit-spirit-catcher', 'legion-tundra-body-armor', 'thermal-armor-body-suit', 'tr-500-heavy-laser-turret', 'legion-90-sky-pack', 'fury-beetle-armor-partial', 'fury-beetle-armor-full', 'dog-sled');

SELECT 'the 20 Inuit items are magic and unsold' AS assertion, count(*) AS got, 20 AS want
  FROM gear WHERE slug LIKE 'inuit-%' AND category = 'magic' AND cost IS NULL
   AND source_book LIKE 'Rifts World Book 20: Canada p.18%';

SELECT 'the eight TW bionic weapons store their conversion figure' AS assertion, sum(cost) AS got, 535000 AS want
  FROM gear WHERE slug LIKE 'tw-%' AND source_book LIKE 'Rifts World Book 20: Canada p.12%';

SELECT 'both Fury Beetle grades store their low ends' AS assertion, count(*) AS got, 2 AS want
  FROM gear WHERE (slug = 'fury-beetle-armor-partial' AND mdc = 40 AND cost = 10000)
     OR (slug = 'fury-beetle-armor-full' AND mdc = 75 AND cost = 16000);

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-canada-gear.sql');
