-- The Tech-Ninja O.C.C., Rifts World Book 8: Japan p.82-84.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-tech-ninja-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'tech-ninja', 'Tech-Ninja', 'rifts', '---
id: tech-ninja
occ_group: men-of-arms
men_of_arms: true
name: Tech-Ninja
system: rifts
source_book: Rifts World Book 8: Japan p.82-84
category: occ
xp_table: [0, 2401, 4601, 9201, 18401, 28301, 48001, 78001, 110001, 150001, 200001, 250001, 310001, 380001, 470001]
attribute_requirements: { PP: 10, MA: 12 }
starting_money: "3d6x1000"
skills:
  hand_to_hand: { costs: { ninjitsu: 3, aikido: 1, jujitsu: 1, karate: 1 }, conditions: { ninjitsu: "only the tiny handful of tech-ninja who have learned the secret art of the true ninja" } }
  occ_skills:
    - { name: "Mathematics: Basic", base: 55, per_level: 5, note: "+10%" }
    - { name: "Language: Native Tongue", base: 98, per_level: 0, note: "The book prints Language: Japanese (+20%); the catalog''s native tongue already stands at 98%." }
    - { name: "Literacy: Native Language", base: 55, per_level: 5, note: "+15%; the book prints Literacy: Japanese." }
    - { name: "Computer Operation", base: 45, per_level: 5, note: "+5%" }
    - { name: "Computer Programming", base: 35, per_level: 5, note: "+5%" }
    - { name: "Computer Hacking", base: 25, per_level: 5, note: "+10%" }
    - { name: "Disguise", base: 35, per_level: 5, note: "+10%; the book lists Disguise (+10%) twice." }
    - { name: "Escape Artist", base: 40, per_level: 5, note: "+10%" }
    - { name: "Imitate Voices & Sounds", base: 52, per_level: 4, note: "+10%. The book prints Imitate Voice and Impersonation, which the catalog holds as two skills; this is the voice half." }
    - { name: "Impersonation", base: 40, per_level: 4, note: "+10%. The impersonation half of the book''s Imitate Voice and Impersonation." }
    - { name: "Climbing", base: 48, per_level: 5, note: "+8%" }
    - { name: "Prowl", base: 35, per_level: 5, note: "+10%" }
    - { choose: 3, categories: ["Weapon Proficiencies"], note: "W.P.: three of choice." }
    - { name: "Hand to Hand: Assassin", base: 0, per_level: 0, note: "Most tech-ninja do not know the ancient combat styles of the true ninja. A tiny handful have learned the secret art and can change Assassin to Ninjitsu at the cost of three other (related) skills. Alternatively Assassin can be replaced with Aikido, Jujitsu or Karate at the cost of one other skill." }
  occ_related_skills:
    count: 8
    minimums:
      - { count: 2, category: "Rogue" }
    schedule:
      - { level: 3, count: 1 }
      - { level: 7, count: 1 }
      - { level: 10, count: 1 }
      - { level: 12, count: 1 }
    categories:
      - { name: "Communications", bonus: 5 }
      - "Domestic"
      - { name: "Electrical", only: ["Basic Electronics"] }
      - { name: "Espionage", bonus: 10 }
      - { name: "Mechanical", only: ["Basic Mechanics", "Automotive Mechanics"] }
      - { name: "Medical", only: ["First Aid", "Forensics"] }
      - { name: "Military", bonus: 10 }
      - "Physical"
      - "Pilot"
      - { name: "Pilot Related", bonus: 5 }
      - { name: "Rogue", bonus: 10 }
      - "Science"
      - "Technical"
      - "Weapon Proficiencies"
      - { name: "Wilderness", bonus: 5 }
    note: "Eight skills, at least two of them from Rogue, plus one at levels 3, 7, 10 and 12. Medical: first aid and criminal sciences and forensics only; forensics needs its prerequisites under Science."
  secondary_skills:
    count: 5
    categories:
      - "Communications"
      - "Domestic"
      - { name: "Electrical", only: ["Basic Electronics"] }
      - "Espionage"
      - { name: "Mechanical", only: ["Basic Mechanics", "Automotive Mechanics"] }
      - { name: "Medical", only: ["First Aid", "Forensics"] }
      - "Military"
      - "Physical"
      - "Pilot"
      - "Pilot Related"
      - "Rogue"
      - "Science"
      - "Technical"
      - "Weapon Proficiencies"
      - "Wilderness"
equipment_starting:
  - { item_id: "ia-100-infiltrator-body-armor", qty: 1, note: "A suit of personalized mega-damage body armor; most use IA-100 Infiltrator Armor (60 M.D.C., concealed vibro-blades inflict 2D4 M.D.)." }
  - { item_id: "clothing", qty: 1, note: "Several nondescript sets of clothing and disguises." }
  - { item_id: "ninja-clothing-and-boots", qty: 1, note: "A black or camouflage ninja suit and rubber-soled tabi boots." }
  - { item_id: "hand-held-computer", qty: 1 }
  - { item_id: "pdd-pocket-audio-digital-disc-recorder-player", qty: 1, note: "Portable compact disc recorder/player and headphones." }
  - { item_id: "pdd-v-pocket-digital-disc-audio-and-video-player", qty: 1, note: "Video disc player." }
  - { item_id: "micro-film-camera", qty: 1, note: "Fits in the palm of the hand." }
  - { item_id: "pen-flashlight", qty: 1 }
  - { item_id: "large-flashlight", qty: 1 }
  - { item_id: "laser-scalpel", qty: 1 }
  - { item_id: "lock-picking-tools", qty: 1 }
  - { item_id: "small-crowbar", qty: 1 }
  - { item_id: "tool-kit", qty: 1, note: "Basic tool kit." }
  - { item_id: "utility-belt", qty: 1 }
  - { item_id: "backpack", qty: 1 }
  - { item_id: "air-filter", qty: 1 }
  - { item_id: "gas-mask", qty: 1 }
  - { item_id: "tinted-goggles", qty: 1 }
  - { item_id: "canteen", qty: 1 }
  - { item_id: "climbing-rope-per-foot", qty: 50, note: "50 feet (15.2 m) of knotted rope." }
  - { item_id: "grappling-hook", qty: 1 }
  - { item_id: "ninja-emergency-kit-rifts", qty: 1 }
  - { choose: 1, label: "energy weapon", qty: 1, from: ["at-6-mini-laser-pistol-escape-artist", "at-8-laser-pistol", "h-8-laser-pistol-h-brand", "super-h-8-laser-pistol-h-brand", "at-20-sharpshot-police-special-laser-pistol", "h-20-sniper-pistol-h-brand", "at-30-combat-laser-pistol", "h-30-siege-pistol-h-brand", "h-10-combat-laser-pistol", "h-13-ion-pulse-pistol", "at-130-particle-beam-pistol", "at-23-police-stun-rifle", "at-84-sharpshot-laser-rifle", "h-84-sniper-rifle-h-brand", "at-88-combat-laser-rifle", "at-230-particle-beam-rifle", "h-12-defender-ion-pulse-rifle", "h-25-super-rifle-h-brand"], note: "One energy weapon of choice, typically a small pistol or small concealed weapon; this is the catalog set of this book''s ArmaTech and H-Brand energy weapons, pistols first." }
  - { choose: 1, label: "E-clips", qty: 4, from: ["armatech-h-brand-pistol-e-clip", "armatech-h-brand-rifle-e-clip", "armatech-energy-canister"], note: "Four extra E-clips for the energy weapon chosen." }
  - { choose: 1, label: "grenades", qty: 2, from: ["at-d40-smoke-grenade", "at-d31-tear-gas-grenade"], note: "Two smoke or riot grenades; the tear gas grenade is this book''s riot grenade." }
  - { choose: 1, label: "vibro-blade", qty: 1, from: ["vibro-knife-tanto-jitte-sai", "vibro-saber-short-sword-ninja-short-sword", "vibro-katana", "vibro-wakizashi", "vibro-knife", "vibro-saber", "vibro-sword"], note: "One vibro-blade of choice; this book''s own vibro-blades (printed 117) come first." }
  - { choose: 1, label: "ancient weapon", qty: 1, from: ["katana-rifts", "wakizashi-rifts", "ninja-to-ninja-short-sword", "aikuchi-tanto-rifts", "kusari-gama-rifts", "manriki-gusari-rifts", "kusari-fundo", "kyoketsu-shoge", "nunchaku-rifts", "jitte-or-sai-rifts", "tonfa-rifts", "shikomi-zue-rifts", "shinobi-zue", "naginata-yari-rifts", "short-bow-rifts", "kawanga-rifts"], note: "One ancient weapon; the book names none, so this is the catalog set of this book''s traditional weapons." }
  - { item_id: "cyber-armor", qty: 1, note: "Implanted cyber-armor, one of the cybernetics the character starts with." }
  - { item_id: "tracer-chip", qty: 1, note: "Implanted by the clan to keep track of the character." }
special_abilities:
  - name: "Starting Cybernetics"
    description: "Starts with cyber-armor, a clan tracer chip and 1D4 cybernetic implants of choice. Additional implants must be purchased by the character. The cyber-armor and tracer chip are in the starting equipment; roll the 1D4 and pick the implants by hand."
  - name: "Freelance Rates"
    description: "As a freelance spy or assassin, a character of good reputation and experience (4th level or higher) can charge, and get, 4000 to 10,000 credits per single-day operation."
restrictions:
  - "Hand to Hand: Ninjitsu only for the tiny handful who have learned the true ninja''s secret art, at the cost of three related skills."
extraction_notes: "Rifts World Book 8: Japan printed 82-84 (cache p083-p085, text layer, page_offset +1). The Tech-Ninja O.C.C. heading is mid-column on printed 82 after the Cyber-Samurai''s closing lines; the entry ends with the Money and Cybernetics lines at the top of printed 84, where the Ninja Juicer begins. Printed 82 and 83 were rendered and match the text layer. || GROUP: the contents (printed 4) files the class under Character Classes of the Republic chapter, which names no group. Stored as men-of-arms with men_of_arms true because it is a trained assassin built on Hand to Hand combat, like the Mystic Ninja. A judgment call. || XP: the Tech-Ninja, Mystic Ninja column of the Experience Point Tables (cache p217), read off a render. || SKILLS: Japanese is stored as Language: Native Tongue (catalog 98%; the +20% cannot raise it) and Literacy: Native Language at 40 +15. Disguise (+10%) is printed twice in the O.C.C. skills and is stored once; the duplicate grants nothing. Imitate Voice and Impersonation (+10%) is stored as the catalog''s two skills, Imitate Voices & Sounds (42+10) and Impersonation (30+10), following the Rifts Changeling precedent. Medical''s criminal sciences and forensics is the catalog''s Forensics. Secondary skills: five, from the related list without its bonuses. || HAND TO HAND: Assassin; changing to Ninjitsu costs three other skills (the related picks) and to Aikido, Jujitsu or Karate one. The Ninjitsu condition is shown, not enforced. || EQUIPMENT: the energy weapon, E-clip type, grenades, vibro-blade and ancient weapon are choices over catalog rows because the book names none. The book gives 4D4x1000 credits worth of black market salable items besides the 3D6x1000 credits; the items are not coin and are prose. The 1D4 implants of choice cannot be a dice-count choice and are prose. The micro-film camera and small crowbar are this book''s micro-film-camera and small-crowbar rows (printed 83)."
---

## Lore

The ninja clans did not die with the old world. They survived the centuries by growing ever more secretive, and even the chaos after the coming of the Rifts could not wipe them out. The post-apocalyptic age produced two kinds of ninja: the traditional mystic shadow warrior, and a modern counterpart, the tech-ninja (also called cyber-ninja or ninja-techie).

Tech-ninja serve Japan''s corporations, whose rivalries can turn brutal and even deadly. They carry out espionage, sabotage and the occasional assassination or kidnapping against a patron''s business rivals. Every major corporation, Ichto and H-Brand among them, keeps a stable or clan of tech-ninja. H-Brand even hires its clan out to other nations, gaining a larger force and a steady trickle of secrets, and has enhanced a third of its ninja with full bionic conversion and juicer and crazy augmentation.

Unlike the traditional clans, which trace their families back for centuries, tech-ninja are recruited: mostly orphans and unwanted children, adopted or taken very young, raised to be loyal to the clan and to trust no outsider. Deceit is encouraged from childhood, and secrecy is kept at all costs.

Tech-ninja specialize in espionage, silent and covert operations and other illicit work. Most live seemingly normal lives, masquerading as businessmen, police officers (some joined the force already in the clan''s service) or soldiers, and some join mercenary or adventurer groups, never forgetting that their first loyalty is to the clan. They are trained in stealth, hand to hand combat and evasion, mostly for the city rather than the wilderness, with emphasis on defeating security systems and computer hacking. The wet work is usually left to specialists: the ninja ''borgs, juicers and crazies. The typical tech-ninja is expected to pass as an executive, break into a corporate president''s office, hack his computer and leave by the top floor of the skyscraper.

The traditional clans hold the tech-ninja in contempt as imitators who sully the ninja name; the tech-ninja think the traditionalists are dinosaurs, and claim their cybernetics, juicers and ''borgs outmatch any mystic art. In the New Republic a few corporations keep small teams and keep their activities low, and some benevolent corporations have lent their ninja to the government for covert operations, including raids on H-Brand and on the oni regions. In return the government overlooks occasional industrial espionage, as long as no innocents are harmed.

## Player Notes

Working among non-ninja, a tech-ninja player character usually poses as a high-tech thief or city rat, a spy, or a warrior or adventurer. If the other characters serve the same corporation as his clan, he might reveal his true profession, but only once he is convinced he can trust them.

## Equipment and Money

Beyond the listed gear, the equipment section describes other specialized ninja equipment, and the game master decides whether a ninja starts with any of it. The modern ninja favors technology in weapons and equipment. Money: 3D6x1000 credits, plus 4D4x1000 credits worth of black market salable items.

## Cybernetics

The character starts with cyber-armor and 1D4 implants of choice, plus a tracer chip the clan uses to keep track of him. Further implants must be purchased. See also the Ninja ''Borg.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'tech-ninja');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'tech-ninja';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-tech-ninja-class.sql');
