-- Fetishes - the 46 Native American magic items Rifts World Book 15: Spirit
-- West defines, printed 84-94: 18 minor, 18 major (three of them tattoos) and
-- 10 legendary.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-spirit-west-fetishes.sql
--
-- The book has a TEXT LAYER. Offset comes from scripts/books.json: page_offset
-- 1, no exceptions, so printed N is cache p(N+1). Printed 84 - the general
-- rules - is on this book's glyph-corrupt list with ONE hit; it carries no row,
-- and nothing below was read from it.
--
--   tier        printed   rows
--   minor        85-87     18
--   major        87-91     18   incl. three tattoo fetishes, printed 90-91
--   legendary    92-94     10
--
-- WHY THESE ARE ROWS AT ALL. Nine of the book's eleven O.C.C.s start with one
-- or more fetishes of choice - the Totem Warrior's "one minor fetish of choice"
-- on printed 43 is the typical line - and an equipment line needs a catalog row
-- to point at. So the fetishes land before the classes.
--
-- NONE IS PRICED, AND NONE IS GIVEN A PRICE. Printed 84 describes fetishes as
-- heirlooms, sacred gifts and rewards, made by Shamans and passed on rather
-- than sold. cost is NULL - the finished state for an item no book prices, per
-- db/schema.sql - and every row says why in cost_note. This matches the 61
-- unpriced rows of the 235 already in category 'magic', all of which carry a
-- cost_note (production, 2026-09-10).
--
-- THE TIER IS THE FIRST WORDS OF EACH DESCRIPTION, not a column: the gear table
-- has none, and the classes grant by tier ("one minor fetish"). The readbacks
-- below count on it.
--
-- NUMBERS THE TEXT LAYER SETS WRONG, read as the only dice they can be
-- (book-survey 0a, BOOK-INGEST-AUDIT F53 - the fault is in the ink, and a
-- render does not cure it): "!D6xlO" is 1D6x10, "!D4xlO" 1D4x10, "3D4xlO +140"
-- 3D4x10+140, "2D4xlO" 2D4x10, and the Spirit Weapon Fetish's small axe prints
-- "104x10 M.D." between a 1D4x10 and a 1D6x10, which is 1D4x10.
--
-- mdc IS SET ONLY WHERE THE BOOK GIVES A FIXED FIGURE: the Armor Fetish (45;
-- 25 from the substitute materials, in the description) and the Great Armor
-- Fetish (125). The Dragon Bone Armor Fetish's 3D4x10+140 is dice, so mdc is
-- NULL and the figure is in the description.
--
-- DESCRIPTIONS ARE PARAPHRASES, never the book's prose. Mechanical numbers
-- inside them were carried across from the entries.
--
-- NOT IMPORTED from these pages: the Mask Shaman's fetish masks (printed 57-59),
-- which are that class's own ability and ship with it, and the general fetish
-- rules of printed 84-85 - one fetish per tier for anyone but a Shaman, usable
-- only by believers, three uses a day for a fetish with a duration. Those are
-- rules, not items.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('armor-fetish', 'Armor Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 45, 'Minor fetish. Turtle shell or armadillo hide - or bear, ox or buffalo hide and tendon - that surrounds the wearer with the equivalent of light mega-damage body armor: 45 M.D.C. from shell or armadillo, 25 from the substitutes, with no prowl or movement penalty. It regenerates 5 M.D.C. a day; if the protection is ever fully depleted the fetish is destroyed, so it can be switched off when badly damaged.', 'Rifts World Book 15: Spirit West p.85'),
('body-fetish', 'Body Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Elk, buffalo or bear tendon or hide. When active it adds 50 S.D.C. to a mortal, or 15 M.D.C. to a supernatural or other mega-damage being. It works on ''Borgs.', 'Rifts World Book 15: Spirit West p.85'),
('climbing-fetish', 'Climbing Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Mountain goat, squirrel or wildcat teeth, horn or hide. Adds +10% to a skilled climber; an unskilled user climbs at a base 45%.', 'Rifts World Book 15: Spirit West p.85'),
('damage-fetish', 'Damage Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', 'Doubles the S.D.C. weapon''s damage', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish, for S.D.C. weapons. A deep tree root bound around a stone from a mountaintop, tied to one weapon at a time. Doubles that weapon''s S.D.C. damage, conventional firearms included, but covers only one part of a combined weapon (the rifle or its bayonet, not both). No effect on magic or mega-damage weapons. Always active.', 'Rifts World Book 15: Spirit West p.85'),
('ear-fetish', 'Ear Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. The ears of a keen-eared animal. Sharper, not amplified, hearing: +1 on initiative, +1 to roll with impact, punch or fall, and attackers are -2 to catch the wearer by surprise or from behind.', 'Rifts World Book 15: Spirit West p.86'),
('healing-fetish', 'Healing Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Bear, snake or buffalo bone. Heals 2D6 hit points or S.D.C. per use, twice a day, and constantly gives +1 to save vs disease.', 'Rifts World Book 15: Spirit West p.86'),
('heritage-and-self-fetish', 'Heritage & Self Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Beads, turquoise, a feather, bone and small keepsakes. A reminder of family, clan, heritage and personal values: in moments of temptation or moral doubt the G.M. uses it to remind the character what he holds important. It confers no special willpower and gives the G.M. no control over the character.', 'Rifts World Book 15: Spirit West p.86'),
('luck-fetish', 'Luck Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Made from trickster animals - rabbit, raven, fox. When the character most needs it, never more than twice a day, it gives +1 to initiative, dodge and roll with impact, +2 to save vs poison and disease, and +2% to most skill rolls (+5% to cardsharp, seduction, demolitions, trap/mine detection and prospecting), for two minutes per level of the user. One made from a fox is constant. Some tribes use them as medicine bundles.', 'Rifts World Book 15: Spirit West p.86'),
('porcupine-quill-fetish', 'Porcupine Quill Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. A single quill holding a porcupine''s spirit energy. A ritual tool: it applies the tattoo fetishes, ordinary tattoos and piercings, and sews other fetishes.', 'Rifts World Book 15: Spirit West p.86'),
('prowl-fetish', 'Prowl Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Rodent or feline feet, tail or hide. Adds +10% to prowl and to sense of balance; an unskilled user prowls at a base 40%. Lasts two minutes per level of the user, three times a day. It silences only the user''s own movement - his machines still make noise.', 'Rifts World Book 15: Spirit West p.86'),
('song-fetish', 'Song Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. The voice box and feathers or hide of a songbird or other singing animal. +20% to singing, and the user can imitate the calls of the animal it came from - sounds only, no words.', 'Rifts World Book 15: Spirit West p.86'),
('speed-fetish', 'Speed Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Wolf or coyote pads and nails, slivers of horse hoof, or bird feathers. While the user runs on foot his Speed becomes 50 (35 mph) or rises by 20, whichever is greater, with about a third of the usual fatigue, for up to two hours. No extra attacks or reaction speed.', 'Rifts World Book 15: Spirit West p.86'),
('strength-fetish', 'Strength Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Elk, moose, buffalo or bear teeth, horn, hoof or bone. Raises P.S. by six - two for a supernatural being - for two minutes per level, three times a day, and constantly lets the user carry 20% more.', 'Rifts World Book 15: Spirit West p.86'),
('sure-footedness-fetish', 'Sure-Footedness Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Deer, mountain goat, mule or squirrel horn, hoof or bone. Excellent balance (+20%), seldom a stumble or fall, and leaps 10% farther, for as long as the task needs.', 'Rifts World Book 15: Spirit West p.86'),
('swimming-fetish', 'Swimming Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Seal or otter teeth and bones, or frog or turtle bones. Gives a 55% swimming skill or +20% to an existing one, and lets the user hold his breath for one minute plus 15 seconds per P.E. point.', 'Rifts World Book 15: Spirit West p.86'),
('tooth-and-claw-fetish-minor', 'Tooth & Claw Fetish (minor)', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', '+1D6 to punches, claw strikes and kicks; +1D4 to bites', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. The teeth and claws of a predator. Spirit claws and teeth add a damage die to unarmed combat - S.D.C. for an ordinary being, M.D. for a mega-damage one with supernatural strength. Lasts one minute per level of the user, or for as long as a serious fight or the user''s anger lasts.', 'Rifts World Book 15: Spirit West p.86'),
('tracking-fetish', 'Tracking Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. Nose or beak, teeth, nails, hair or feathers of a keen-scented hunter. Follows both physical tracks and scent trails: +10% to a tracking skill, or a base 40% for the untrained.', 'Rifts World Book 15: Spirit West p.86-87'),
('wind-wing-fetish', 'Wind-Wing Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Minor fetish. A bird''s intact wing. A keen sense of wind direction and speed, and warning of an approaching storm - which way it comes from and whether it will be light or severe.', 'Rifts World Book 15: Spirit West p.87'),
('great-armor-fetish', 'Great Armor Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 125, 'Major fetish. A hide shirt or cloak with a skull or hide headpiece and armor pieces of shell, bone or hide - turtle, armadillo, buffalo, rhino-buffalo or dinosaur. Protects the whole body like extra heavy mega-damage body armor, 125 M.D.C., with no prowl or movement penalty. Always active.', 'Rifts World Book 15: Spirit West p.87'),
('great-body-fetish', 'Great Body Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. Elk, buffalo, bear or dinosaur hide. In mortal danger or combat it gives the user a supernatural P.E., turning his S.D.C. and hit points into M.D.C., for three minutes per level, up to once per level a day. No effect on a being that already has M.D.C.', 'Rifts World Book 15: Spirit West p.87'),
('great-ear-fetish', 'Great Ear Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. Skulls or hides of keen-eared animals. The equivalent of amplified hearing: a light sleeper who identifies familiar sounds and voices (70% +1% per level). +2 on initiative, +1 to dodge, +2 to roll with impact, punch or fall, blindness penalties halved, and attackers are -6 to strike by surprise or from behind.', 'Rifts World Book 15: Spirit West p.87-88'),
('great-healing-fetish', 'Great Healing Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. Bear, buffalo, snake or dinosaur bone or hide, laid on or passed over the patient, once per day per level of the owner. Negates poison, toxins and disease and heals 3D6 hit points and/or S.D.C. per use, or 1D6 M.D.C. on a being that cannot bio-regenerate. An owner with healing psionics, or a Healing Shaman, uses those powers at double strength. In exorcism it gives +10% and makes the user immune to possession, and it holds vampires at bay like a holy symbol.', 'Rifts World Book 15: Spirit West p.88'),
('great-luck-fetish', 'Great Luck Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. Heads, skulls and bones of trickster animals. When most needed, at most twice a day, for five minutes per level (constant if made from a fox): +1 initiative, +2 to dodge, disarm and roll with impact, +2 vs poisons and magic potions, +4 vs disease, and +2% to most skills (+5% to cardsharp, seduction, demolitions, trap/mine detection and prospecting). Always halves death-blow damage, gives +30% vs coma and death, and halves stun. It works only for good deeds: misuse stops it for 1D4 days, and a second offense drives its spirit out.', 'Rifts World Book 15: Spirit West p.88'),
('great-song-fetish', 'Great Song Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. A mask, headdress or necklace of bird skulls, bones and feathers, including raven or mynah. +20% to singing; the wearer imitates any animal or person heard while it is worn (70% +1% per level), recognizes any voice he has ever heard (90%), and remembers any song he has ever heard.', 'Rifts World Book 15: Spirit West p.88'),
('great-speed-fetish', 'Great Speed Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. Wolf or coyote feet, or horse or deer hooves and tail, with two raptor feathers. While the user runs on foot his Speed becomes 88 (60 mph) or doubles, whichever is greater, with a tenth of the usual fatigue, and he leaps 20 feet up and 40 across at a run; up to five hours. No extra attacks or reaction speed.', 'Rifts World Book 15: Spirit West p.88'),
('great-tracking-fetish', 'Great Tracking Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. The skull and hide or feathers of a predator known for its nose. +20% to tracking, or a base 60% for the untrained; smells poison in food and drink, recognizes a known person''s scent (80% +1% per level), and senses and traces a supernatural creature within 50 feet (70%).', 'Rifts World Book 15: Spirit West p.88'),
('medicine-bundle', 'Medicine Bundle', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. A wrapped collection - typically a healing, a heritage and a song fetish, 1D4+2 other minor fetishes and one greater or legendary fetish - kept by the eldest Shaman or the chief. While bundled it protects the whole tribe within 50 miles: innocents get +1 on saves and defensive actions and +2 vs demonic possession, warriors +1 on all combat rolls. Unbundled for a ceremony, its fetishes work at double range, duration and effect. Broken up, it loses its power and its fetishes work at half strength.', 'Rifts World Book 15: Spirit West p.88-89'),
('shapechange-fetish', 'Shapechange Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. An animal-hide cloak with the head worn as a hood. Transforms the owner, or one person he ritually designates, into a typical member of that one species - never a mega-damage or supernatural animal - keeping mind and skills but taking the animal''s physical attributes. A willing supernatural being can be changed, becoming S.D.C. Lasts one hour per level of the owner on himself, one hour in total on anyone else.', 'Rifts World Book 15: Spirit West p.89'),
('supernatural-damage-fetish', 'Supernatural Damage Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', 'The S.D.C. weapon''s damage as M.D.; +1D6 on a magic M.D. weapon', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. The root and stone of the minor Damage Fetish, set in a web of tendon. Tied to one weapon at a time, it turns that weapon''s S.D.C. damage into M.D. - a 4D6 revolver fires 4D6 M.D. rounds, a 2D6 arrow does 2D6 M.D. No effect on tech M.D. weapons or on spells; a magic M.D. weapon (holy sword, rune weapon, Techno-Wizard weapon) gains +1D6.', 'Rifts World Book 15: Spirit West p.89-90'),
('superhuman-strength-fetish', 'Superhuman Strength Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. Elk, moose, buffalo, bear or dinosaur skull, horn, paws or bone. When great strength is needed, or in combat, a mortal''s P.S. becomes supernatural (minimum 18), or an already supernatural P.S. rises by 4, until the need has passed.', 'Rifts World Book 15: Spirit West p.90'),
('tattoo-spirit-sight-fetish', 'Tattoo "Spirit-Sight" Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish - a tattoo of triangles under and beside the eyes, applied in ritual with a Porcupine Quill Fetish; for Native Americans only. Always on: sees astral beings and travellers, the energy forms of entities and supernatural beings, and Native American spirits, ancestors and elementals - but not things made invisible by other means. Cannot be turned off, and always counts as an active fetish.', 'Rifts World Book 15: Spirit West p.90'),
('tattoo-steady-hand-fetish', 'Tattoo "Steady-Hand" Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish - a tattoo of dots from the fingernails to a band around the wrist of the dominant hand, applied with a Porcupine Quill Fetish; for Native Americans only. Always on: +5% to steady-hand skills (sewing, skinning, carpentry, sculpting, climbing, surgery - not palming or other Rogue skills) and +1 to strike with a bow, an aimed weapon or a thrown weapon. Cannot be turned off.', 'Rifts World Book 15: Spirit West p.90'),
('tattoo-war-fetish', 'Tattoo "War" Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish - a permanent tattoo form of the Spirit Paint spell''s war paint, in the tribe''s own pattern, applied with a Porcupine Quill Fetish; for Native Americans only, usually warriors and chiefs. Always on: +2 to initiative, strike, pull punch, roll with impact, and save vs horror factor.', 'Rifts World Book 15: Spirit West p.90-91'),
('great-tooth-and-claw-fetish', 'Great Tooth and Claw Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', 'Kicks and punches 5D6 S.D.C. or 3D6 M.D.; power punch 1D6x10 S.D.C. or 6D6 M.D.; headbutt or throw 2D6 S.D.C. or 2D4 M.D.; bite 2D6 S.D.C. or 1D6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. The claws and jaw or teeth of a predator, or a raptor''s skull and talons. For the length of a battle the warrior, weapons put aside, is overlaid by a ghostly predator, doing S.D.C. against mortals and M.D. against supernatural and M.D.C. foes; a power punch counts as two attacks. Useless against greater Native American spirits, elementals and gods. Reserved for the greatest warriors and chiefs.', 'Rifts World Book 15: Spirit West p.91'),
('weapon-fetish', 'Weapon Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', 'Bow 4D6 S.D.C. or 4D6 M.D.; knife 2D6 S.D.C. or 1D6 M.D.; small axe or tomahawk 3D6 or 2D6 M.D.; large axe 4D6 or 3D6 M.D.; war club or staff 3D6 or 2D6 M.D.; spear 4D6 or 3D6 M.D.', 1, 'Bow: double normal bow range', NULL, NULL, NULL, NULL, NULL, 'Major fetish - the Native American equivalent of a minor rune weapon: a bow, a flint or obsidian knife or axe, a war club, staff or spear built with teeth, claws and feathers. Indestructible, bonded at its making to one owner and alignment, and handed down the generations. With it: +1 on all saves, +2 vs horror factor, +1 to strike when thrown, +1 on initiative and +1 attack per melee. It does S.D.C. or M.D. as suits the opponent, half damage for an incompatible user and double against alien intelligences; the bow fires spirit arrows.', 'Rifts World Book 15: Spirit West p.91'),
('wing-flight-fetish', 'Wing Flight Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Major fetish. A pair of wings from a medium to large bird. Flight at 40 mph for 10 minutes per level with the arms held out, once per day per level of the user.', 'Rifts World Book 15: Spirit West p.91'),
('cosmic-awareness-fetish', 'Cosmic Awareness Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish, worn on the head - a helm, skull, mask or antler headdress. Track 96%, fish 96%, recognize plants and poison 94%, climb 90/80%; cannot be surprised, senses anyone prowling within 100 feet, sees all invisible things, and senses evil and magic at double the psionic range and ley line disturbances. +2 initiative, +1 dodge, +2 roll with impact, +2 vs poison and potions, +4 vs disease, +4 vs illusions, +6 vs possession, +4 vs horror factor, and +5% to trap/mine detection, locate secret compartments, locate contraband, streetwise and wilderness survival. Halves death-blow damage, +30% vs coma and death, halves stun.', 'Rifts World Book 15: Spirit West p.92'),
('dragon-bone-armor-fetish', 'Dragon Bone Armor Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. A bone breastplate, leather leggings and a hide shield, perhaps of dragon bone. Protection like power armor: 3D4x10+140 M.D.C. with no prowl or movement penalty, restoring 4D6 M.D.C. per minute. The wearer is immune to fumes, gas, disease, cold, heat and normal fire (magic fire and M.D. plasma do half) and tires at a tenth the normal rate.', 'Rifts World Book 15: Spirit West p.92'),
('life-fetish', 'Life Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', '2D4x10 S.D.C. or M.D. against the undead and death-demons; 2D4 S.D.C. otherwise', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. A buffalo or dinosaur leg bone with a bear claw, a rattlesnake rattle and eagle feathers, carried like a scepter. Turns 2D4x10 animated dead like a holy symbol and strikes vampires, zombies, mummies, necromantic creations and death-demons for 2D4x10. Its user is immune to disease, a vampire''s bite and gaze, and necromancy. In a one-minute healing ritual, twice per day per level of the owner: negates poison and disease, mends bones, and heals 6D6 hit points/S.D.C. or 3D6 M.D.C.; coma victims are +40% to save. Exorcism +30%, and immunity to possession.', 'Rifts World Book 15: Spirit West p.92'),
('magic-spirit-fetish', 'Magic Spirit Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. Turquoise, a clear gem or crystal, a white feather and a dragon''s tooth; it can be lent. The wearer is immune to ley line storms, possession, magical mind control, magic illusions and magic sickness, invisible to magical detection including crystal balls, +2 to save vs all magic, and his P.P.E. cannot be seen or drawn on without his permission.', 'Rifts World Book 15: Spirit West p.92'),
('metamorphosis-fetish', 'Metamorphosis Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. Bear or great-cat paw gloves, a feathered and antlered headdress, and a necklace of teeth and hooves holding butterfly and moth cocoons. The owner can become any ordinary S.D.C. animal native to Earth - another human included - except insects, fish and crustaceans, keeping mind and skills. Indefinite, at most twice a day, and cancellable at will.', 'Rifts World Book 15: Spirit West p.92'),
('serpent-fetish', 'Serpent Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. A necklace of snake bones, rattlesnake skulls and rattles, and three feathers said to be the Kukulcan dragon''s, worn openly. Snakes never harm the wearer and give him their venom, and dragons treat him as a spirit brother. Immune to all poison, to every kind of dragon breath, and to a dragon''s gaze and horror factor; +6 vs drugs and magic potions.', 'Rifts World Book 15: Spirit West p.93'),
('spirit-weapon-fetish', 'Spirit Weapon Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', 'Bow 6D6 S.D.C. or 1D4x10 M.D.; knife 4D6 S.D.C. or 2D6 M.D.; small axe or tomahawk 5D6 or 1D4x10 M.D.; large axe 6D6 or 1D6x10 M.D.; war club 5D6 or 1D4x10 M.D.; staff 6D6 or 1D4x10 M.D.; spear 1D4x10 S.D.C. or 1D6x10 M.D.', 1, 'Thrown 500 feet (152 m), returning; bow 2000 feet (610 m)', NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. As the Weapon Fetish, with the same bonuses and the same bond to its owner, but far deadlier; it can be thrown 500 feet and returns after striking or on command. Half damage for an incompatible user; double against demons, triple against alien intelligences. The bow fires energy arrows.', 'Rifts World Book 15: Spirit West p.93'),
('spirit-wing-fetish', 'Spirit Wing Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. The intact wings of a large bird. Flight at up to 300 mph for 10 minutes per level, once per day per level of the user.', 'Rifts World Book 15: Spirit West p.93'),
('sweat-lodge', 'Sweat Lodge', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish - a lodge of wood and hides with a fire inside, for two people or two dozen. For Native Americans it serves as a ley line during rituals: it doubles spell effects, provides 10 P.P.E. per level every 12 hours, and restores 20 P.P.E. per half hour. In healing rituals it lets I.S.P. be shared as P.P.E. is in ritual magic, and a Healing Shaman of 10th level or higher with healing psionics may attempt a resurrection for 750 I.S.P., at 80% less 5% per day dead.', 'Rifts World Book 15: Spirit West p.93'),
('wind-rider-fetish', 'Wind-Rider Fetish', 'rifts', 'magic', NULL, NULL, 'No price - a fetish is made by a Shaman and given as a gift or reward, not sold (printed 84).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Legendary fetish. Feathers of six birds, one a raptor, around a flat turquoise with wind-borne seeds, worn in the hair. Exact wind speed and direction, and full warning of any storm, natural or magical. The wearer is untouched by wind and what it carries, tornadoes and hurricanes included, and can let the wind carry him like a leaf, landing gently when he chooses.', 'Rifts World Book 15: Spirit West p.93-94');

-- Read the result back rather than trusting the exit code. Every want is
-- counted from the book's pages, not from the database. INSERT OR IGNORE is
-- silent on a slug collision, so the count is the check that none happened.
SELECT 'the 46 fetishes are present' AS assertion, count(*) AS got, 46 AS want
  FROM gear WHERE category = 'magic' AND source_book LIKE 'Rifts World Book 15: Spirit West%';

SELECT 'eighteen minor' AS assertion, count(*) AS got, 18 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 15: Spirit West%' AND description LIKE 'Minor fetish%';

SELECT 'eighteen major, tattoos included' AS assertion, count(*) AS got, 18 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 15: Spirit West%' AND description LIKE 'Major fetish%';

SELECT 'ten legendary' AS assertion, count(*) AS got, 10 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 15: Spirit West%' AND description LIKE 'Legendary fetish%';

SELECT 'none carries an invented price' AS assertion, count(*) AS got, 0 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 15: Spirit West%' AND (cost IS NOT NULL OR cost_note IS NULL);

-- Armor Fetish 45 + Great Armor Fetish 125, the only two fixed figures.
SELECT 'the fixed M.D.C. figures sum to 170' AS assertion, sum(mdc) AS got, 170 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 15: Spirit West%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-spirit-west-fetishes.sql');
