-- The 24 spells of Biomancy, the Biomancer's tradition.
-- Rifts World Book 6: South America, printed 64-68.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-south-america-biomancy-spells.sql
--
-- LEVEL AND COST COME FROM THE BOOK'S OWN INDEX (printed 64, "Biomancer Spell
-- Descriptions"), which states both for all 24. Every row's level also agrees
-- with the level heading its description sits under - checked by the parser,
-- 24 of 24. Levels run L1:3 L2:5 L3:3 L4:3 L5:2 L6:2 L7:2 L8:2 L9:1 L10:1.
--
-- Read from the book's TEXT LAYER (.cache/books/south-america, page_offset 1).
-- Two repairs, both checked on a render:
--   * printed 67: the text layer sets the "Tree Teleport" heading at the foot
--     of Strengthen Plants instead of above its own entry. Moved back.
--   * printed 66: Strengthen Plants' P.P.E. line runs into its description.
--     The index prices it "20 or 400"; the entry prints a size schedule whose
--     first figure reads "100;" in the ink, where the order of the list says
--     10. ppe holds the index's 20 and ppe_note carries the schedule.
--
-- NAMES FOLLOW THE INDEX where the heading differs: the index says "Animate
-- Plants: Minor" and "Strengthen Plants", the headings "Animate Plant: Minor"
-- and "Strengthen Plant".
--
-- `Biomancy: ` prefix and `tradition = 'biomancy'`, following the Nature: /
-- nature convention (Mystic Russia) - a tradition's spells are namespaced so
-- they cannot collide with a general invocation of the same name. Only
-- Biomancers and some Jungle Elves learn them (printed 64).
--
-- THREE COSTS VARY (Accelerate Plant Growth, Shrink Plant, Strengthen Plants).
-- ppe holds the minimum, which is what the sheet's use button spends
-- (migration 021); ppe_note carries the schedule.
--
-- ONE ROW CARRIES same_spell_as. catalog-diff --table spells --remote,
-- 2026-09-25, matched none of the 24 names prefixed or bare, and put two at
-- a warlock row of the same name. Both went to scripts/same-spell-lib.mjs:
--
--   * Suspended Animation -> Earth: Suspended Animation: no problems. Linked.
--     Same level (8) and cost (80); this book ages the sleeper two years in
--     ten where the warlock row says one - a difference in the prose, not in
--     the numbers the link compares.
--   * Shrink Plant -> Earth: Shrink Plant: every number agrees (level 3, 10 or
--     200 P.P.E., 90% in 10% steps), but the descriptions share only 0.33 of
--     their vocabulary against a floor of 0.35, because the catalog's warlock
--     row is a paraphrase. NOT linked; the lib is the rule.

INSERT OR IGNORE INTO spells
  (name, level, ppe, ppe_note, variant_note, source, source_book, system, range, duration, damage, saving_throw, area_of_effect, casting_time, description, same_spell_as, tradition)
VALUES
  ('Biomancy: Commune with Nature', 1, 2, NULL, NULL, 'import', 'Rifts World Book 6: South America p.64', 'rifts', 'One mile (1.6 km) radius per level of experience.', 'Instant', NULL, 'None', NULL, NULL, 'The biomancer meditates and gets a general feeling for the surrounding ecosystem. The spell will tell the character if the ecosystem is unbalanced or damaged and why - a general sense of the source of the disturbance, such as drought, extensive pollution, deforestation, fire, war, plague, etc.', NULL, 'biomancy'),
  ('Biomancy: Shape Plants', 1, 4, NULL, NULL, 'import', 'Rifts World Book 6: South America p.64', 'rifts', 'Touch', 'Permanent', NULL, 'None', NULL, NULL, 'The spell caster can reshape a tree limb or small plant at will. He can alter its position and even twist the trunk and branches of a small tree or plant. Large trees and intricate designs, such as sculpting a normal tree into a humanoid or animal shape, will take multiple castings (each casting causes one minor effect). Affecting a large tree would take 8-12 castings. This power only works on living or freshly cut trees and plants.', NULL, 'biomancy'),
  ('Biomancy: Weather Sense', 1, 1, NULL, NULL, 'import', 'Rifts World Book 6: South America p.64', 'rifts', 'One mile (1.6 km) radius per level.', '24 hours', NULL, 'None', NULL, NULL, 'The character''s connection to nature gives him or her an idea of what the weather will be like for the next 24 hours. The spell delivers an extensive weather report; i.e. cloud cover, wind direction and speed, temperature highs and lows, humidity, the likelihood of precipitation or foul weather and approximately when it will arrive and how long it will last. Note that the spell cannot forecast weather changes caused by magic or ley lines during that period - but if the weather doesn''t come out as reported the character will know an outside force is responsible.', NULL, 'biomancy'),
  ('Biomancy: Animate Plants: Minor', 2, 4, NULL, NULL, 'import', 'Rifts World Book 6: South America p.64-65', 'rifts', '60 feet (18.3 m) per level of experience.', 'One melee round (15 seconds) per level of experience.', NULL, 'None', NULL, NULL, 'The spell caster can cause one plant of average tree size or less to move. The plant will remain rooted to the spot but will move its limbs or stems around. Trees will make a lot of noise if they flail their limbs, rustling their leaves as if a strong wind was running through them. The character can also make a tree or branch bend to better reach a branch or to climb. The animated plants cannot attack or hinder people, but can distract or even  terrify foes (at the G.M.''s discretion, seeing a large tree suddenly move its branches or bend as if to bow might call for a save vs a Horror Factor of 9 to 11).', NULL, 'biomancy'),
  ('Biomancy: Animal Weaponry: Simple', 2, 6, NULL, NULL, 'import', 'Rifts World Book 6: South America p.65', 'rifts', 'Self', 'One minute per level of experience.', NULL, 'None', NULL, NULL, 'The spell caster alters his own body by making his fingers magically elongate into bony animal-like claws, or his teeth into fangs. The claws inflict 3D6 S.D.C. in hand to hand combat and are +1 to strike and parry. Fangs inflict 2D6 S.D.C. per bite and can be used to chew through S.D.C. rope, wood or material.', NULL, 'biomancy'),
  ('Biomancy: Insect Leap', 2, 5, NULL, NULL, 'import', 'Rifts World Book 6: South America p.65', 'rifts', 'Self', 'Instant', NULL, 'None', NULL, NULL, 'This spell enables the character to make an enormous grasshopper-like leap. This can be either a broad, lengthwise leap or high jump. Broad jumps (for distance) will carry the character 50 feet (15.2 m) plus 10 feet (3.0 m) per level of experience. High jumps (leaping up rather than for distance) are 10 feet (3.0 m) plus 6 feet (1.8 m) per level of experience.', NULL, 'biomancy'),
  ('Biomancy: Plant Virtual Sight', 2, 6, NULL, NULL, 'import', 'Rifts World Book 6: South America p.65', 'rifts', '100 feet (30.5 m) per level of experience.', '1 melee round (15 seconds)', NULL, 'None', NULL, NULL, 'The spell caster can mystically "see" from the vantage point of any plant from a blade of grass low to the ground to the tallest treetop. For instance, a character needing to see past a jungle''s heavy canopy could use this spell to magically move his eyesight to the top of a tree. The caster has to specify the angle and direction he will be looking at.', NULL, 'biomancy'),
  ('Biomancy: Weave Plants', 2, 15, NULL, NULL, 'import', 'Rifts World Book 6: South America p.65', 'rifts', 'Touch', 'Permanent', NULL, 'None', NULL, NULL, 'The character can take portions of a plant (never a whole plant, but small pieces from bushes and trees like leaves, vines, and so on) and reshape them into a vegetable fiber that is lightweight, resilient and waterproof; reminiscent of plastic with a cotton-like texture. Color is manipulated by the selection of the base material. Fabric made of bark, branches and roots will be shades of brown, leaves provide shades of green, grains give yellow and orange, while flower petals and fruits offer an array of colors. As the caster creates the fiber, he or she can reshape it into clothing, belts, bags, baskets, rope or any article that can be made out of fabrics or weaves. The sewing/tailor skill is necessary to make a functional set of clothing (any style). Characters without a sewing or tailoring skill can only make simple cloaks, robes, blankets, sheets of material, sacks, rope and similar simple articles. Each casting creates three square feet (0.3 square meters) of material per level of experience. S.D.C. armor can be made by using bark or roots and layering and interlacing several layers of heavy cloth. The maximum protection such armor will provide is 45 S.D.C. with an A.R. of 13. This spell can also be used to mend M.D.C. wood armor, restoring up to 5 M.D.C. per level of experience with every casting. Biomancy wood armor is described later.', NULL, 'biomancy'),
  ('Biomancy: Accelerate Plant Growth', 3, 5, '5 for a small plant, 10 for a tree, 20 for a large tree', NULL, 'import', 'Rifts World Book 6: South America p.65', 'rifts', 'Touch', 'Permanent', NULL, 'None', NULL, NULL, 'The biomancer can speed up the normal growth of a plant. Full-grown plants will sprout a full year''s worth in a melee round and a sapling will grow up into a full sized adult plant. Adult trees will grow another 4D6% of their current size. A seed needs two castings, one after planting to create a sapling and another spell to make the plant reach full size.', NULL, 'biomancy'),
  ('Biomancy: Chitin', 3, 15, NULL, NULL, 'import', 'Rifts World Book 6: South America p.65-66', 'rifts', 'Self', 'Ten minutes per level of experience.', NULL, 'None', NULL, NULL, 'The character''s skin is covered by a dark, vaguely organic substance that looks like melted wax with spiny protuberances at the joints and shoulders. This mystical chitin protects the caster with 40 M.D.C. plus 5 M.D.C. per level of experience. The chitin armor is considered to be the equivalent of light body armor (-5% prowl penalty). No other armor can be worn over it, but it can be concealed under a cape, cloak or robe. The chitin clad character can be easily mistaken for a monster or D-Bee. The spines in the chitin inflict an extra 1D6 S.D.C. in hand to hand  combat - M.D. if this spell is combined with the spell animal weaponry: major.', NULL, 'biomancy'),
  ('Biomancy: Shrink Plant', 3, 10, '10 temporary; 200 for a permanent shrinking', NULL, 'import', 'Rifts World Book 6: South America p.66', 'rifts', 'Touch', 'One minute per level of experience or permanent.', NULL, 'Standard; supernatural plants get a +6 to save.', NULL, NULL, 'This spell will shrink any plant by as much as 90%, reducing a 30 foot (9.1 m) tree to a mere 3 feet (0.9 m). The caster can determine the degree of shrinking in gradations of 10% up to 90%. Once shrunk, the spell cannot be used on that plant again to make it any smaller. Expending 200 P.P.E. points will cause a permanent reduction of the plant.', NULL, 'biomancy'),
  ('Biomancy: Animal Weaponry: Major', 4, 20, NULL, NULL, 'import', 'Rifts World Book 6: South America p.66', 'rifts', 'Self', 'One minute per level of experience.', NULL, 'None', NULL, NULL, 'The spell caster alters his own body by making his fingers magically elongate into bony animal-like claws and/or his teeth into large fangs. The character can even make a pair of horns or antlers grow out of his head. The major spell makes these megadamage weapons. Claws inflict 2D6 M.D. in hand to hand combat and are +1 to strike and parry. Fangs inflict 1D6 M.D. per bite and can be used to chew through rope, wood, plastic, and even light chains and thin metal. Horns or antlers do 2D6 M.D. and are +1 to strike.', NULL, 'biomancy'),
  ('Biomancy: Forest Camouflage', 4, 15, NULL, NULL, 'import', 'Rifts World Book 6: South America p.66', 'rifts', 'Self', 'Two minutes (8 melees) per level of experience.', NULL, 'None', NULL, NULL, 'The mage can blend into any plant-covered landscape, becoming totally invisible! Unlike the chameleon spell, the mage can move around without disturbing the spell. Not even the see invisible spell, or creatures with that ability, are able to see the camouflaged character as long as he stays among vegetation. Neither will any technological imagers or sensors detect the magically concealed spell caster. While the spell is in effect, the character has an effective prowl skill of 60% (or adds 10% to an existing prowl skill, whichever is greater). The only way to attack the character is to shoot or strike wildly, but all such attacks are -5 to strike and the magically camouflaged character has the initiative. Area effect magic and explosives are more likely to hit the concealed target. The character will only reveal his hiding place if he calls attention to himself by shouting, making noise, or attacking. Even then attackers are -2 to strike and he is vulnerable only during the melee(s) in which he performs the foolish action. He can also reveal himself by stepping out of vegetation, like moving onto rocks, a vehicle or a paved street. By retreating back into the woodlands and remaining silent, the character will once again become invisible and undetectable. Remember, the spell only works in places where trees and plants are numerous: forests, jungles, city parks, even grasslands (but then the character must crawl or remain crouched).', NULL, 'biomancy'),
  ('Biomancy: Strengthen Plants', 4, 20, 'Index: 20 temporary or 400 permanent. The entry prices temporary effects by size - blades of grass (printed "100;", read as 10), a shrub or bush 20, small tree 30, adult tree 40, giant redwood type tree 60 - and 400 to make any living plant a permanent M.D. structure', NULL, 'import', 'Rifts World Book 6: South America p.66', 'rifts', 'One tree or 10 foot (3.0 m) area per level of experience.', 'One minute per level of experience or permanent.', NULL, 'None', NULL, NULL, 'This spell transforms normal trees and plants into M.D.C. structures! A blade of grass has one M.D.C. point (and is like stepping on a nail, pointed end up), small shrubs and bushes acquire 4D6 M.D.C., larger bushes and small trees have 1D6X10 M.D.C., good sized trees have 4D6X10 M.D.C. and trees towering 200 feet (61 m) or higher have 1D6X100+100 M.D.C.! Some biomancers use rituals and ley line energy to permanently transform whole forests into living mega-damage structures. This is especially effective in foiling logging operations, preventing normal chainsaws and bulldozers from harming the mega-damage plants. The transformed plants are also immune to disease, insects and to normal fires, but not mega-damage fire and forces. Once a mega-damage plant or tree is cut down/killed, however, it reverts back to normal S.D.C. wood, so people trying to exploit the capabilities of the strengthened plants get nothing for their troubles. Approximately 70% of the trees on Maga Island have been permanently transformed into mega-damage structures.', NULL, 'biomancy'),
  ('Biomancy: Animal Ghost', 5, 20, NULL, NULL, 'import', 'Rifts World Book 6: South America p.67', 'rifts', '10 feet (3.0 m) per level of experience.', 'One minute per level of experience', NULL, 'Standard', NULL, NULL, 'This spell can be used along a game trail, a drinking spot, or any place frequented by animals. The spell creates a seemingly real image of any one animal that has frequented the area regularly. The illusion appears real, especially from a distance and can be manipulated to do anything the animal would normally do. A deer would run away, a bear could stand threateningly and roar, a predator might growl and take an aggressive stance, and so on. Many biomancers use this spell to trick and frighten hunters, entice them on foolish chases, or to lure them into an ambush. The spell is referred to as animal "ghost" because like a ghost or holographic projection, the animal has no substance. Arrows, spears and bullets fly right through the image without any reaction from the creature. Also like a ghost, the animal will suddenly disappear without a trace when the spell ends.', NULL, 'biomancy'),
  ('Biomancy: Metamorphosis: Plant', 5, 30, NULL, NULL, 'import', 'Rifts World Book 6: South America p.67', 'rifts', 'Touch', '5 minutes per level of experience.', NULL, 'None', NULL, NULL, 'The biomancer can transform himself into a plant. The size can range from a shrub to a tree. While in this state, the magician cannot move, attack or use magic (except to end the spell), but remains in control of all his senses other than speech. Turning into a shrub or tree temporarily gives the character 60 additional S.D.C.; a large tree will grant the character an additional 200 S.D.C.', NULL, 'biomancy'),
  ('Biomancy: Bio-Blast', 6, 15, NULL, NULL, 'import', 'Rifts World Book 6: South America p.67', 'rifts', '100 feet (30.5 m) plus 10 feet (3.0 m) per experience level.', 'Instant', NULL, 'None except dodge, but the victim must know the attack is coming and must roll an 18 or higher.', NULL, NULL, 'The spell caster fires a bolt of life energy at a target, disrupting living beings and destroying inanimate objects. The blast does 2D6 S.D.C./hit point damage and causes neural disruption to living creatures. Victims lose initiative and the number of melee round attacks and combat bonuses are reduced by half for one melee round. Against inanimate objects, such as weapons, bots, vehicles, machines, rock and buildings, the blast inflicts 1D6 M.D. per level of the spell caster. Mega-damage is doubled against vampires, other undead, and supernatural monsters. The bio-blast can be fired from the fingertips or eyes of the spell caster and is +1 to strike.', NULL, 'biomancy'),
  ('Biomancy: Tree Teleport', 6, 20, NULL, NULL, 'import', 'Rifts World Book 6: South America p.67', 'rifts', '200 feet (61 m) per level of experience.', 'Instant', NULL, 'None', NULL, NULL, 'The biomancer can temporarily transform himself and up to 150 Ibs (68 kg) of equipment into bio-energy and "jump" to a nearby tree. The tree acts as a lightning rod for the bio-energy and enables the caster to disappear, move and reform himself. The effect is just like a teleport spell, enabling the character to pop in, out and around an area without leaving tracks or to surprise an enemy. The spell needs a tree to "ground" itself and to give the spell caster a fixed target location; he appears right next to the target tree. If a foolish character attempts the spell when there are no trees in range, he cannot re-materialize! Instead, the character will temporarily turn into energy and drift randomly for 1D6 days, after which time he will finally reappear next to a tree 1D4X10 miles (1D4X16 km) from his jump point (or the next closest tree if none are within that range).', NULL, 'biomancy'),
  ('Biomancy: Tree Warrior', 7, 30, NULL, NULL, 'import', 'Rifts World Book 6: South America p.67', 'rifts', 'Immediate area', '30 minutes per level of the biomancer.', NULL, 'None', NULL, NULL, 'This spell enables the biomancer to animate a tree and imbue it with supernatural strength and endurance. The tree will pull itself up by the roots, follow the biomancer and fight his enemies. At the end of the spell, the tree will root itself in the nearest convenient spot (if possible, its original position) and return to normal. The tree can serve as a bodyguard, spy, or scout. Tree warriors are ideal for ambushes because they can remain immobile like an ordinary tree until an unsuspecting victim is within reach and then strike. Biomancers who carelessly cause the death of a tree with this spell, however, have a 10% chance of losing their biomancer powers until they can somehow redeem themselves! This 10% chance is cumulative. Tree Warrior; M.D.C.200; 8 to 15 feet (2.4 to 4.6 m) tall, P.S. 25, P.P. 17, I.Q. 7, Spd. 16, +3 to strike, +4 to parry and dodge, bio-regenerate 2D6 M.D.C. per melee round, and M.D. fire and plasma does half damage.; Can shoot bio-energy bolts inflicting 3D6 M.D., doubled against vampires and the undead; range: 100 feet (30.5 m).; Four physical attacks or bio-bolts per melee. Punch inflicts 2D6 M.D., power punch does 4D6 M.D. (counts as two attacks).; The Tree Warrior will obey only the person who summoned it.', NULL, 'biomancy'),
  ('Biomancy: Undo Undead', 7, 25, NULL, NULL, 'import', 'Rifts World Book 6: South America p.68', 'rifts', '300 feet (91.4m)', 'Instant', NULL, 'Standard', NULL, NULL, 'The magician causes an undead creature to be surrounded by bio-energy that reacts to its necromantic energies like matter does to anti-matter! Vampires, zombies, skeletons and other undead or animated dead will be burned horribly if they fail their saving throw. The spell inflicts 1D6X10 M.D. or hit point damage, +2 points per level of the spell caster''s experience. A successful save means the undead suffers only 1D6 points of damage and recognizes the dangerous life magic held by his opponent.', NULL, 'biomancy'),
  ('Biomancy: Suspended Animation', 8, 80, NULL, NULL, 'import', 'Rifts World Book 6: South America p.68', 'rifts', 'Self', 'One day to ten years per level of the character.', NULL, 'None', NULL, NULL, 'The biomancer can place himself in a total state of suspended animation, slowing all body functions to a crawl and simulating death. The biomancer ages two years for every ten that he sleeps. While in the suspended state, the biomancer cannot cast spells or think, only dream. His physical body is not protected in any way by this spell so he should find a safe, dry, warm place with some form of protection. The character can be roused only by a Tree of Wisdom, Memory Tree, or via telepathic communication, but only if he can be convinced to end his magic sleep.', 'Earth: Suspended Animation', 'biomancy'),
  ('Biomancy: Touch of Life', 8, 60, NULL, NULL, 'import', 'Rifts World Book 6: South America p.68', 'rifts', 'Touch', 'Permanent', NULL, 'None', NULL, NULL, 'The biomancer can revive a recently dead person by infusing him with bio-energy. The corpse can be no more than a day old (less is better). The chance of success is 70% plus 1% per level of experience. If successful, the corpse will be restored to 10 hit points above zero. The person will be weak and sick until the rest of his hit points are restored. The touch of life does not restore missing limbs, heal burns or disease, or cure insanity.', NULL, 'biomancy'),
  ('Biomancy: Heal the Earth', 9, 200, NULL, NULL, 'import', 'Rifts World Book 6: South America p.68', 'rifts', '100 feet (30.5 m) area per level of experience.', 'Permanent', NULL, 'None', NULL, NULL, 'This spell will heal the area from any poisons, pollution, and other damaging substances. The area thus treated will become perfectly suited for the development of life, as determined by the region''s ecosystem. If cast on farmland, yields for the area affected will be increased by 10% per level of the spell caster''s experience.', NULL, 'biomancy'),
  ('Biomancy: Woodland Entity', 10, 80, NULL, NULL, 'import', 'Rifts World Book 6: South America p.68', 'rifts', 'Self', 'One melee (15 seconds) per level of experience.', NULL, 'None', NULL, NULL, 'The spell caster transforms himself into a gigantic tree-like creature with superhuman strength and endurance. The woodland entity has a P.S. of 30 (supernatural), and 300 M.D.C.! It regenerates 3D6 M.D.C. every melee round, attacks with its spiked claws, and is +2 to strike and inflict 6D6 M.D.! Fire and energy attacks inflict half damage and its own attacks do full damage to vampires and were-creatures; double damage to alien intelligences.', NULL, 'biomancy');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'biomancy spells inserted' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE tradition = 'biomancy';
SELECT 'every one is prefixed' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE name LIKE 'Biomancy: %' AND tradition = 'biomancy';
SELECT 'every one cites this book by page' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE tradition = 'biomancy' AND source_book LIKE 'Rifts World Book 6: South America p.%';
SELECT 'every one carries a cost and a level' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE tradition = 'biomancy' AND ppe > 0 AND level BETWEEN 1 AND 10;
SELECT 'the schedules carry their note' AS assertion, count(*) AS got, 3 AS want
  FROM spells WHERE tradition = 'biomancy' AND ppe_note IS NOT NULL;
SELECT 'the one retelling is linked' AS assertion, count(*) AS got, 1 AS want
  FROM spells WHERE tradition = 'biomancy' AND same_spell_as = 'Earth: Suspended Animation';
SELECT 'Woodland Entity is the one tenth-level spell, at 80' AS assertion, count(*) AS got, 1 AS want
  FROM spells WHERE name = 'Biomancy: Woodland Entity' AND level = 10 AND ppe = 80;

INSERT INTO data_script_runs (filename) VALUES ('add-south-america-biomancy-spells.sql');
