-- Elemental Spell Magic: the complete Air, Earth, Fire and Water spell
-- lists (Rifts Book of Magic p.71-72), 231 rows.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-elemental-spells.sql
--
-- NAMES ARE ELEMENT-QUALIFIED ("Air: Cloud of Steam") and that is load
-- bearing, not decoration. spells.name is UNIQUE, and these lists collide
-- two different ways:
--
--   - with the Invocation spells already in the catalog - Blinding Flash,
--     Globe of Daylight, Cloud of Smoke, Fire Bolt, Chameleon and Darkness
--     are all both, and an elemental Fire Bolt is not the invocation one;
--   - with EACH OTHER - Cloud of Steam is an Air 1st level (4 P.P.E.), a
--     Fire 4th level (10) and a Water 1st level (10). Freeze Water, Resist
--     Cold, Snow Storm, Hurricane, Circle of Rain, Heal Burns, Wall of Ice,
--     Drought, River of Lava, Frostblade, Dowsing and Protection from
--     Lightning all repeat across spheres at different levels and costs.
--
-- The prefix also groups the four spheres in the wizard's spell picker,
-- which filters by name substring: typing "Fire:" narrows to the Fire
-- sphere, which is how a Warlock picks from his own element.
--
-- Variable costs follow the ppe_note convention (migration 021): ppe holds
-- the MINIMUM, the note carries what the book prints - Create Wood
-- "5 or 10", Clay or Stone to Iron "40/60", Ironwood "50+".
--
-- Water prints Calm Waters TWICE, at 3rd level (15) and 8th (100); the
-- second is stored as "Water: Calm Waters (greater)" so both survive.
--
-- system is 'rifts'. Pure ASCII on purpose - see PR #101's pre-flight.

INSERT INTO spells (name, level, ppe, ppe_note, system, source, source_book, description) VALUES
('Air: Breathe Without Air', 1, 3, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Cloud of Slumber', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Cloud of Steam', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Create Light', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Create Mild Wind', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Stop Wind', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Thunderclap', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 1.'),
('Air: Change Wind Direction', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Cloak of Darkness', 2, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Create Air', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Distant Voice', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Electric Arc', 2, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Heavy Breathing', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Howling Wind', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Levitate', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Mesmerism', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Miasma', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Northwind', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Orb of Cold', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Silence', 2, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 2.'),
('Air: Air Bubble', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Call Lightning', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Float in Air', 3, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Darkness', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Fingers of the Wind', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Frequency Jamming', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Frostblade', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Northern Lights', 3, 12, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Resist Cold', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Sheltering Force', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Walk the Wind', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Wave of Frost', 3, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Wind Rush', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 3.'),
('Air: Ball Lightning', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Calm Storms', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Dissipate Gases', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Freeze Water', 4, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Invisibility', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Leaf Rustler', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Lightblade', 4, 12, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Lightning Arc', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Phantom Footman', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Protection from Lightning', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 4.'),
('Air: Breath of Life', 5, 60, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Circle of Rain', 5, 25, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Darken the Sky', 5, 25, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Detect the Invisible', 5, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Invisible Wall', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Phantom', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Phantom Mount', 5, 25, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Sonic Blast', 5, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Whirlwind', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 5.'),
('Air: Electrical Field', 6, 35, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 6.'),
('Air: Electro-Magnetism', 6, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 6.'),
('Air: Mist of Death', 6, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 6.'),
('Air: Snow Storm', 6, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 6.'),
('Air: Vacuum', 6, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 6.'),
('Air: Whisper of the Wind', 6, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 6.'),
('Air: Atmospheric Manipulation', 7, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 7.'),
('Air: Hurricane', 7, 60, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 7.'),
('Air: Rainbow', 7, 60, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 7.'),
('Air: Tornado', 7, 60, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 7.'),
('Air: Creature of the Wind', 8, 70, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 8.'),
('Air: Wind Blast', 8, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 8.'),
('Air: Wind Cushion', 8, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Air Elemental Magic, level 8.'),
('Earth: Chameleon', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Create Wood', 1, 5, '5 or 10', 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Dowsing', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Dust Storm', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Fool''s Gold', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Identify Minerals', 1, 3, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Identify Plants', 1, 3, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Mystic Fulcrum', 1, 3, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Rock to Mud', 1, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Rot Wood', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Shatter', 1, 3, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 1.'),
('Earth: Create Dirt or Clay', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Dirt to Clay', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Dirt to Sand', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Grow Plants', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Hopping Stones', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Throwing Stones', 2, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Track', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Wall of Clay', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Wither Plants', 2, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 2.'),
('Earth: Animate Plants', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Create Mound', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Crumble Stone', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Dig', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Earth Rumble', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Encase Object in Stone', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Locate Minerals', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Shrink Plant', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Wall of Stone', 3, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 3.'),
('Earth: Animate Object', 4, 12, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Cocoon of Stone', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Mend Stone', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Quicksand', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Repel Animals', 4, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Rust', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Sand Storm', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Wall of Thorns', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 4.'),
('Earth: Chasm', 5, 25, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 5.'),
('Earth: Clay to Lead', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 5.'),
('Earth: Clay to Stone', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 5.'),
('Earth: Close Fissures', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 5.'),
('Earth: Little Mud Mound', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 5.'),
('Earth: Travel Through Walls', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 5.'),
('Earth: Clay or Stone to Iron', 6, 40, '40/60', 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 6.'),
('Earth: Create Steel', 6, 34, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 6.'),
('Earth: Mend Metal', 6, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 6.'),
('Earth: Stone to Flesh', 6, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 6.'),
('Earth: Travel Through Stone', 6, 35, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 6.'),
('Earth: Wood to Stone', 6, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 6.'),
('Earth: Earthquake', 7, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 7.'),
('Earth: Metal to Clay', 7, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 7.'),
('Earth: Petrification', 7, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 7.'),
('Earth: River of Lava', 7, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 7.'),
('Earth: Sculpt & Animate Clay', 7, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 7.'),
('Earth: Wall of Iron', 7, 45, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 7.'),
('Earth: Cap Volcano', 8, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Earth: Create Golem', 8, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Earth: Firequake', 8, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Earth: Ironwood', 8, 50, '50+', 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Earth: Magnetism', 8, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Earth: Suspended Animation', 8, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Earth: Transference of Essence', 8, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Earth Elemental Magic, level 8.'),
('Fire: Blinding Flash', 1, 1, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Cloud of Smoke', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Create Coal', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Fiery Touch', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Fire Bolt', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Globe of Daylight', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Impervious to Fire', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Nightvision', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Stench of Hades', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 1.'),
('Fire: Cloud of Ash', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Darkness', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Fireblast', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Flame Lick', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Freeze Water', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Heat Object/Boil Water', 2, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Resist Cold', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Spontaneous Combustion', 2, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Swirling Lights', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Tongue of Flame', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 2.'),
('Fire: Circle of Cold', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Circle of Flame', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Create Heat', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Extinguish Fire', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Fire Ball', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Fire Gout', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Lower Temperature', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Part Fire', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Wall of Flame', 3, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 3.'),
('Fire: Cloud of Steam', 4, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: Fire Blossom', 4, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: Flame Friend', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: Fuel Flame', 4, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: Heal Burns', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: Mini-Fireballs', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: See Through Smoke', 4, 12, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 4.'),
('Fire: Blue Flame', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 5.'),
('Fire: Breathe Fire', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 5.'),
('Fire: Eat Fire', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 5.'),
('Fire: Fire Globe', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 5.'),
('Fire: Screaming Wall of Flame', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 5.'),
('Fire: Wall of Ice', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 5.'),
('Fire: Dancing Fires', 6, 35, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 6.'),
('Fire: Eternal Flame', 6, 75, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 6.'),
('Fire: Fire Whip', 6, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 6.'),
('Fire: Flame of Life', 6, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 6.'),
('Fire: Fire Sponge', 7, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 7.'),
('Fire: Melt Metal', 7, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 7.'),
('Fire: River of Lava', 7, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 7.'),
('Fire: Ten Foot Wheel of Fire', 7, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 7.'),
('Fire: Burst into Flame', 8, 70, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 8.'),
('Fire: Drought', 8, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 8.'),
('Fire: Plasma Bolt', 8, 60, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Fire Elemental Magic, level 8.'),
('Water: Cloud of Steam', 1, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Color Water', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Create Fog', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Dowsing', 1, 2, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Float on Water', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Purple Mist', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Salt Water to Fresh', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Sense Direction Underwater', 1, 4, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Walk the Waves', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Water to Wine', 1, 5, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 1.'),
('Water: Breathe Underwater', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Change Current', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Fog of Fear', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Foul Water', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Frostblade', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Liquids to Water', 2, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Resist Fire', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Ride the Waves', 2, 7, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Swim as a Fish: Superior', 2, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Water Seal', 2, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 2.'),
('Water: Calm Waters', 3, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Circle of Rain', 3, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Command Fish', 3, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Freeze Water', 3, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Impervious to Ocean Depth', 3, 12, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Resist Cold', 3, 6, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Sheet of Ice', 3, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 3.'),
('Water: Communicate with Sea Creature', 4, 12, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Create Water', 4, 8, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Hail', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Shards of Ice', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Speak Underwater', 4, 10, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Swim Like the Dolphin', 4, 15, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Wall of Ice', 4, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Water Wisps', 4, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 4.'),
('Water: Earth to Mud', 5, 20, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 5.'),
('Water: Protection from Lightning', 5, 25, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 5.'),
('Water: Snow Storm', 5, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 5.'),
('Water: Ten Foot Ball of Ice', 5, 30, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 5.'),
('Water: Whirlpool', 5, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 5.'),
('Water: Encase in Ice', 6, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 6.'),
('Water: Heal Burns', 6, 25, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 6.'),
('Water: Hurricane', 6, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 6.'),
('Water: Little Ice Monster', 6, 40, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 6.'),
('Water: Part Waters', 6, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 6.'),
('Water: Summon Sharks or Whales', 6, 50, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 6.'),
('Water: Drought', 7, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 7.'),
('Water: Rain Dance', 7, 60, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 7.'),
('Water: Summon Storm', 7, 100, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 7.'),
('Water: Calm Waters (greater)', 8, 100, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 8. Printed as a second Calm Waters at 8th level, 100 P.P.E.'),
('Water: Creature of the Waves', 8, 70, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 8.'),
('Water: Tidal Wave', 8, 80, NULL, 'rifts', 'import', 'Rifts Book of Magic p.71-72', 'Water Elemental Magic, level 8.')
ON CONFLICT (name) DO NOTHING;

-- Read the result back rather than trusting the exit code.
SELECT COUNT(*) AS elemental_rows FROM spells WHERE source_book = 'Rifts Book of Magic p.71-72';
SELECT substr(name, 1, instr(name, ':') - 1) AS sphere, COUNT(*) AS n FROM spells
 WHERE source_book = 'Rifts Book of Magic p.71-72' GROUP BY sphere ORDER BY sphere;
SELECT name, level, ppe, ppe_note FROM spells WHERE name IN ('Air: Cloud of Steam', 'Fire: Cloud of Steam', 'Water: Cloud of Steam', 'Earth: Create Wood', 'Earth: Ironwood', 'Water: Calm Waters (greater)') ORDER BY name;
