-- Rifts World Book 17: Warlords of Russia, batch 3: Russian bionics.
-- 33 new gear rows, category cybernetics, from Russian Cybernetic Systems
-- (printed 100-106).
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-warlords-of-russia-bionics.sql
--
-- ALL 33 ARE NEW - catalog-diff --table gear --remote, a slug query and a
-- read of every cybernetics row in production, 2026-10-01.
--
-- WHAT IS LEFT OUT, AND WHY. Printed 99 says the chapter reprints Triax
-- cybernetics for convenience, and the catalog holds those from Rifts World
-- Book 5: Triax and the NGR p.153-154 at the same prices: Macro-Eye,
-- Macro-Eye Laser, Multi-System Eye Socket, Third Eye, the Medical Sensor
-- Hand and its twelve features, Bio-Comp, the Internal Comp-Calculator, the
-- Extendible Hydraulic Hand/Arm, the Laser Beam Eye, the LGL-31 Grapnel, the
-- RVB-31 Concealed Vibro-Blade and the Psionic Electro-Magnetic Dampers. The
-- catalog wins; none is touched.
--   W-41 Palm Laser Torch (printed 106): the catalog holds Triax's PL-31
--     Palm Laser Torch at the same 15,000 credits. Same device under another
--     model number, or a different one - the book does not say. Ambiguous,
--     so left alone and said so.
--   Cyber Shield (printed 104): the Heavy Cyber-Shield, already in from the
--     weapons section (two rows, small and large), at the same figures.
--
-- THE DIGIT CIPHER lands on the Tool Hand's laser cutter (1D6x10 S.D.C.) and
-- the magnification figures (10x to 50x). Read as what they can only be.
--
-- WHAT THE BOOK ITSELF GETS WRONG, recorded and not corrected:
--   Passive Nightvision Eye  no price printed. cost is NULL.
--   Mekanikal Vibro-Blade arm  the Vibro-Claw fingers do 3D4 M.D. in the
--     description and 4D4 M.D. on the damage line. Both are in the row.
--
-- The Shocktroopers' own exclusive systems (printed 117-141) ship with the
-- cyborg batch, not this one.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('cyberlink-vehicle-interfacing', 'Cyberlink Vehicle Interfacing', 'rifts', 'cybernetics', NULL, 250000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A finger or head jack link that lets a partial or full conversion cyborg read and control a computerized machine or vehicle by thought. Linked to a vehicle: +1 initiative, +1 to strike with the vehicle or its built-in weapons, +1 to dodge and +1 melee action that must use the vehicle. Gives a base 45% to pilot any small one- or two-man vehicle, or +10% to a piloting skill the character has. The cyborg can raise the vehicle''s top speed by 1% per I.Q. point for three minutes per M.E. point. While linked he can do nothing but pilot and use the vehicle. Full control only of small, simple vehicles (motorcycles, cars, hovercycles, flying wings and the like); on a tank, aircraft, ship or giant robot the link reaches one system only.', 'Rifts World Book 17: Warlords of Russia p.100'),
('weapon-to-cyborg-energy-link', 'Weapon to Cyborg Energy Link', 'rifts', 'cybernetics', NULL, 120000, NULL, NULL, 0, NULL, 'Effectively unlimited for the linked energy weapon', NULL, NULL, NULL, 5, 'A concealed plug-in cable that powers an energy rifle or pistol from the cyborg''s own supply; damage, range and rate of fire are unchanged. Only for heavy full conversion cyborgs and Shocktroopers. The cable has 5 M.D.C.: a Called Shot at -5 at range, or a declared melee attack that hits on 12 or higher. Severed, it takes three melee actions to fit an E-Clip instead. While linked: speed -10% and -1 initiative. After about 10 minutes of frequent fire: speed -20%, no initiative bonus, -1 to parry and dodge, and hand to hand damage halved, recovering 15 minutes after unplugging. It can also power a small vehicle built for an E-Pack, at those heavier penalties from the start.', 'Rifts World Book 17: Warlords of Russia p.100'),
('robot-strength-optional-feature', 'Robot Strength (Optional Feature)', 'rifts', 'cybernetics', NULL, 200000, '200,000 credits for robot P.S. 20. Each point above 20 is another 10,000 credits per arm.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Lightweight hydraulics that give a full conversion cyborg robot P.S. and Mega-Damage punches and kicks. For Heavy Machines (maximum robot P.S. 35) and Cyborg Shocktroopers (maximum 40, and automatic for them); not available to partial cyborgs or Light Machines. The frame must be big and bulky and the sense of touch drops to about 45%.', 'Rifts World Book 17: Warlords of Russia p.101'),
('interchangeable-parts', 'Interchangeable Parts', 'rifts', 'cybernetics', NULL, 50000, '50,000 credits per modular joint or section.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Special couplings that make a bionic part removable and swappable: hand and wrist, forearm and elbow, upper arm and shoulder, a forearm weapon mount, foot and ankle, even an artificial face exchanged for an armored face plate.', 'Rifts World Book 17: Warlords of Russia p.101'),
('light-filters-cyber-optic', 'Light Filters (Cyber-Optic)', 'rifts', 'cybernetics', NULL, 1500, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A bionic eye feature that reduces glare. As many as three eye features can be combined in most bionic eyes.', 'Rifts World Book 17: Warlords of Russia p.101'),
('panorama-cluster-lens', 'Panorama Cluster Lens', 'rifts', 'cybernetics', NULL, 470000, NULL, NULL, 0, '1,200 feet (366 m)', NULL, NULL, NULL, NULL, NULL, 'A cluster of lenses that lets the cyborg see 360 degrees around and above at once. Cannot be surprised when awake; +2 initiative, +3 to dodge, +1 to disarm; +5% to Detect Ambush, Detect Concealment, Detect Traps and Intelligence, +10% to Cardsharp; and one Trick Shooting trick of choice. The lenses protrude from an eye socket, the forehead and the top and back of the head: P.B. is reduced 25% (maximum 10). Roll a random phobia at levels 3, 7 and 12; the wearer is jumpy and sleeps badly. Adjusting takes 3D4 weeks with no initiative bonus, combat bonuses halved, speed -20% and skills -25%. Very rare: a third of Assassin cyborgs use it and under 5% of others.', 'Rifts World Book 17: Warlords of Russia p.101'),
('passive-nightvision-eye', 'Passive Nightvision Eye', 'rifts', 'cybernetics', NULL, NULL, 'The book prints no price.', NULL, 0, '2,000 feet (610 m); more with a telescopic lens feature', NULL, NULL, NULL, NULL, NULL, 'A bionic eye feature that amplifies ambient light, such as moonlight and starlight, to see clearly in the dark.', 'Rifts World Book 17: Warlords of Russia p.102'),
('wide-angle-vision', 'Wide-Angle Vision', 'rifts', 'cybernetics', NULL, 60000, NULL, NULL, 0, '1,000 feet (305 m)', NULL, NULL, NULL, NULL, NULL, 'A wide-angle lens giving 180 degrees of peripheral vision, so ambushes and sneak attacks from the sides cannot be sprung. +1 initiative and +1 to dodge. Can be combined with other optic features. The eye is obviously mechanical and protrudes: P.B. is reduced 10%.', 'Rifts World Book 17: Warlords of Russia p.102'),
('spectra-eye', 'Spectra-Eye', 'rifts', 'cybernetics', NULL, 350000, NULL, NULL, 0, '100 feet (30.5 m)', NULL, NULL, NULL, NULL, NULL, 'A full-spectrum eye, from below infrared to beyond ultraviolet, plus microwaves, x-rays, gamma rays, heat, radiation and the energy trails of weapon discharges. Scans machines and metal for flaws, damage and overheating; tracks at a base 40%, or +15% to the tracking skill; sees any invisible being that gives off heat or radiation, though not Astral beings, ethereal spirits or life essences. The eye is obviously mechanical and protrudes: P.B. is reduced 10%.', 'Rifts World Book 17: Warlords of Russia p.102'),
('super-telescopic-eye', 'Super-Telescopic Eye', 'rifts', 'cybernetics', NULL, 20000, '20,000 credits; 38,000 for a pair.', NULL, 0, '5,000 feet (1524 m)', NULL, NULL, NULL, NULL, NULL, 'A bionic eye with six magnifications from 10x to 50x and filters to reduce glare.', 'Rifts World Book 17: Warlords of Russia p.102'),
('low-frequency-audio-rig', 'Low-Frequency (Earthquake) Audio Rig', 'rifts', 'cybernetics', NULL, 5000, NULL, NULL, 0, 'Heavy vehicles and armored divisions about 4 miles; cavalry, herds and city traffic 3 miles; infantry 2 miles; heavy machines and factories 1 mile; volcanic activity 12 miles; earthquakes 100 miles', NULL, NULL, NULL, NULL, NULL, 'A sensor that slides from the ear to touch ground, rock or wall and listen to vibration carried through the earth; the cyborg must lean on the surface. It tells whether the sound is approaching or receding, gives its general direction at 80%, and tells surface disturbances, explosions, earthquakes (and their strength) and volcanic rumbling apart.', 'Rifts World Book 17: Warlords of Russia p.102'),
('audio-filter-and-enhancement', 'Audio Filter & Enhancement', 'rifts', 'cybernetics', NULL, 38000, NULL, NULL, 0, 'Best under 79 feet (24.1 m); 60% clarity from 80 to 300 feet (24.4 to 91 m)', NULL, NULL, NULL, NULL, NULL, 'A sound system that edits out background noise to focus on one to four chosen sounds or voices and enhances them digitally, for picking out a conversation or identifying a machine or weapon by its sound.', 'Rifts World Book 17: Warlords of Russia p.102'),
('synthetic-voice-enhancer', 'Synthetic Voice Enhancer', 'rifts', 'cybernetics', NULL, 6000, NULL, NULL, 0, 'The usual vocal range', NULL, NULL, NULL, NULL, NULL, 'Deepens the voice to a gravelly, menacing tone and amplifies growls and roars; switched on and off at will, for effect and intimidation. Not a full voice modulator.', 'Rifts World Book 17: Warlords of Russia p.102'),
('gromeko-friend-or-foe-identification-computer', 'Gromeko Friend or Foe Identification Computer', 'rifts', 'cybernetics', NULL, 200000, NULL, NULL, 0, 'Line of sight', NULL, NULL, NULL, NULL, NULL, 'An implant tied to the cyborg''s optics and communications that profiles what he sees: up to 200 cyborg designs, armors and insignia of Russia, Europe and Asia and 600 monsters and demons, each with schematics of known weaknesses, armor, weapons and powers. A small yellow symbol marks a minimal or potential threat and a large red one a known enemy; icons classify the subject and a 1-10 scale rates its power, flashing at 10 when it is off the scale. Full conversion cyborgs only.', 'Rifts World Book 17: Warlords of Russia p.102'),
('cyborg-jet-pack', 'Cyborg Jet Pack', 'rifts', 'cybernetics', NULL, 165000, NULL, NULL, 0, NULL, '48 hours from an E-Pack, or indefinite on a cable to the cyborg''s own power supply', NULL, NULL, NULL, 140, 'A heavy jet pack for Heavy Machines and Cyborg Shocktroopers that snaps into connectors built into the back. Maximum speed 250 mph (400 km), cruising 70-100 mph; maximum altitude 2,000 feet (610 m). After three hours of continuous use there is a 01-50% chance of overheating and shutting down, rolled every 30 minutes; it needs 40 minutes to cool. Limited production outside the Kolodenko, Romanov and Burgasov camps.', 'Rifts World Book 17: Warlords of Russia p.103'),
('cyberjet-nodes', 'Cyberjet Nodes', 'rifts', 'cybernetics', NULL, 150000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Small directional jets in the back and legs for jet-assisted leaps and limited hovering. Leaping doubles normal running speed; a heavy cyborg leaps 100 feet high or 200 feet across, 30% farther with a running start, and a Light Machine 50% farther again. Hovers up to 100 feet for 1D4 minutes before settling gently to the ground. Full conversion cyborgs only.', 'Rifts World Book 17: Warlords of Russia p.103'),
('head-collar-and-hood', 'Head Collar & Hood', 'rifts', 'cybernetics', NULL, 35000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A retractable metal collar that rises to protect the back of the head and the sides of the neck and head, leaving the face clear and peripheral vision unblocked. Adds 42 M.D.C. to the head.', 'Rifts World Book 17: Warlords of Russia p.103'),
('cyborg-helmet-and-face-plate', 'Helmet and/or Face Plate (Cyborg)', 'rifts', 'cybernetics', NULL, 36000, '36,000 credits. Add 1,500 for an independent oxygen supply, and 12,000 for a face plate linked to the cyborg''s real face so the mouth and brows move.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 80, 'A Samurai-style face mask worn in place of a visor, or as a full helmet with face plate and a covering for the back of the head. It connects to all standard cyborg body armor or is worn alone, non-environmental, or with an air filter and oxygen tank. The face can look high-tech, human or monstrous.', 'Rifts World Book 17: Warlords of Russia p.103'),
('hydraulic-leg-boosters', 'Hydraulic Leg Boosters', 'rifts', 'cybernetics', NULL, 90000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Hydraulics that give the legs more power: running speed +20%, +2 feet to high jumps and +5 feet to horizontal leaps, and +1 to dodge. Full conversion cyborgs only.', 'Rifts World Book 17: Warlords of Russia p.103'),
('shoulder-weapon-mounts-clamps', 'Shoulder Weapon Mounts/Clamps', 'rifts', 'cybernetics', NULL, 1500, '1,500 credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Mountings on the shoulders, legs or back that hold a rifle, Vibro-Blade or other weapon in place of a holster or sling; the weapon snaps on and off and holds through action in the field.', 'Rifts World Book 17: Warlords of Russia p.104'),
('schematic-sensor-hand', 'Schematic Sensor Hand', 'rifts', 'cybernetics', NULL, 40000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A mechanical-looking hand with a schematic diagnostic sensor, a circuit tracer, a circuit modeler and a remote repair feature for fixing a circuit or rerouting a signal from where the user stands. Sold widely to adventurers and Operators as well as to the War Camps.', 'Rifts World Book 17: Warlords of Russia p.104'),
('tool-hand', 'Tool Hand', 'rifts', 'cybernetics', NULL, 24000, NULL, '1D6x10 S.D.C., one M.D., 1D4 M.D. or 1D6 M.D. (laser cutter finger, adjustable)', 1, '6 foot beam', NULL, NULL, NULL, NULL, NULL, 'A mechanical hand with a fingerjack, fingertip screwdrivers with changeable heads, finger pliers, a light in each fingertip, a laser cutter finger and a small retractable drill in the middle knuckle.', 'Rifts World Book 17: Warlords of Russia p.104'),
('tool-mechanics-arm', 'Tool Mechanic''s Arm', 'rifts', 'cybernetics', NULL, 190000, NULL, '1D6x10 S.D.C., one M.D., 1D4 M.D. or 1D6 M.D. (the Tool Hand''s laser cutter finger)', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'The Tool Hand plus a pair of retractable, folding, multi-jointed, three-fingered mini-arms (P.S. 10, P.P. 10) that reach two feet beyond the hand and hold work during a repair. Each takes tool heads: light drill, sander and buffer, screwdriver, cutting blades, wire cutters, pliers and clamp, needle-nose pliers, flashlight and hammer. Several store in the arm.', 'Rifts World Book 17: Warlords of Russia p.104'),
('tread-leg-mode', 'Tread Leg Mode', 'rifts', 'cybernetics', NULL, 185000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'In place of legs, a vehicular lower body on two treads with a torso housing that turns the upper body 360 degrees; the cyborg stands 15-20% shorter. Speed 90 mph (144 km), cruising 40-50 mph. The lower body has 100 M.D.C. and each tread 60. Full conversion cyborgs only.', 'Rifts World Book 17: Warlords of Russia p.104'),
('electro-cannon-forearm-blaster', 'Electro-Cannon Forearm Blaster', 'rifts', 'cybernetics', NULL, 30000, NULL, '3D6 M.D.', 1, '300 feet (91.5 m)', 'Effectively unlimited; draws on the cyborg''s power supply', 'Equal to the user''s hand to hand attacks per round', NULL, NULL, NULL, 'Anti-personnel and anti-vehicle. A forearm weapon that fires a bolt of intense electricity; S.D.C. electronics are fried. The rules for salt water, machinery and underwater electrical discharge apply.', 'Rifts World Book 17: Warlords of Russia p.104'),
('forearm-weapon-guards', 'Forearm Weapon Guards', 'rifts', 'cybernetics', NULL, 18000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 25, 'A thick flaring arm guard that protects a ranged weapon built into the forearm; often spiked, ribbed or bladed for show.', 'Rifts World Book 17: Warlords of Russia p.104'),
('hydraulic-hammer-hand', 'Hydraulic Hammer Hand', 'rifts', 'cybernetics', NULL, 40000, NULL, '+1D6 M.D. on top of normal punch damage', 1, NULL, NULL, 'Each attack is one melee action', NULL, NULL, NULL, 'An extra strong, hard bionic hand (+15 M.D.C.) in a hydraulic forearm housing that vibrates like a jackhammer; with sustained attacks it does anything a jackhammer can. 01-50% to knock a human-sized opponent, a Light Machine or a small vehicle under 250 pounds off its feet, costing initiative and one melee action; a successful roll with impact halves the damage. The hand can hold no other cybernetics and its sense of touch is 10%.', 'Rifts World Book 17: Warlords of Russia p.104'),
('hydraulic-ram-arm', 'Hydraulic Ram Arm', 'rifts', 'cybernetics', NULL, 80000, NULL, '4D6 M.D.', 1, NULL, NULL, 'Each ram attack is one melee action', NULL, NULL, NULL, 'For Heavy Machines and Shocktroopers only. The forearm and hand are one solid battering ram, equal to a power punch from robot P.S. 40 but costing one action. 01-80% to knock a human-sized opponent, a Light Machine or a small vehicle under 500 pounds off its feet and 2D4 yards away, costing initiative and two melee actions, with a 01-45% chance the victim drops what he holds; a successful roll with impact halves the damage and keeps hold. It cannot be parried without a shield or a P.S. of 30 or higher, though it can be dodged. The limb can carry no other cybernetics, has no sense of touch and costs the use of one hand (-20% to most skills).', 'Rifts World Book 17: Warlords of Russia p.104-105'),
('laser-cannon-arm', 'Laser Cannon Arm', 'rifts', 'cybernetics', NULL, 63000, NULL, 'Heavy laser 4D6 M.D.; light laser 2D6 M.D.; simultaneous dual blast 6D6 M.D.', 1, 'Heavy laser 3,000 feet (914 m); light laser 2,000 feet (610 m)', '12 blasts, then one combat round of recharge per blast', 'Each blast is one melee action', NULL, NULL, NULL, 'Anti-personnel and anti-vehicle. A heavy large-bore laser in place of a hand or forearm, with a light laser for precision fire and a pop-up telescopic scope with passive nightsight (2,000 feet). Only the light laser can snipe. The limb can carry no other cybernetics, has no sense of touch and costs the use of one hand (-20% to most skills).', 'Rifts World Book 17: Warlords of Russia p.105'),
('mekanikal-rail-gun-weapon-arm', 'Mekanikal Rail Gun Weapon Arm', 'rifts', 'cybernetics', NULL, 90000, '90,000 credits per arm.', '4D6 M.D. per burst of 20 rounds; 1D4 M.D. per single round', 1, '2,000 feet (610 m)', 'Seven bursts from the short clip (140 rounds), or 200 bursts from a 4,000 round ammo-drum on the back', 'Each burst is one melee attack', NULL, NULL, NULL, 'Anti-personnel and anti-vehicle. An Ammodyne AR-36 rail gun built into the forearm, its range cut by the shorter barrel; too large to retract and made in one size. One of the modular Mekanikal weapon arms built for Heavy Machines and Cyborg Shocktroopers; any of them can be swapped for another. It makes for a large, oversized forearm but keeps a fully articulated hand.', 'Rifts World Book 17: Warlords of Russia p.105'),
('mekanikal-barrage-weapon-arm', 'Mekanikal Barrage Weapon Arm', 'rifts', 'cybernetics', NULL, 90000, '90,000 credits per arm.', 'Laser 3D6 M.D.; ion 4D6 M.D.; both together 7D6 M.D.; mini-missiles by type', 1, 'Laser 2,000 feet (610 m); ion 1,200 feet (366 m); mini-missiles one mile (1.6 km)', 'Laser and ion effectively unlimited, drawing on the cyborg''s power supply; two mini-missiles per arm', 'Each blast is one melee attack; laser and ion fired together count as one, as does a pair of mini-missiles', NULL, NULL, NULL, 'Anti-personnel and anti-vehicle. A forearm with a high-powered laser, an ion blaster and a pair of mini-missiles. One of the modular Mekanikal weapon arms built for Heavy Machines and Cyborg Shocktroopers; any of them can be swapped for another. It makes for a large, oversized forearm but keeps a fully articulated hand.', 'Rifts World Book 17: Warlords of Russia p.105'),
('mekanikal-vibro-blade-multi-weapon-arm', 'Mekanikal Vibro-Blade Multi-Weapon Arm', 'rifts', 'cybernetics', NULL, 90000, '90,000 credits per weapon arm. An extra pair of arms is 130,000 credits each plus the weapon arm features, 440,000 in all; a third of that for a Warlord.', 'Laser 2D6 M.D.; pair of large top-mounted Vibro-Blades 3D6 M.D.; large underarm Vibro-Blade 3D6 M.D.; Vibro-Claw fingers 4D4 M.D. on the damage line (3D4 M.D. in the description)', 1, 'Laser 1,600 feet (488 m); the blades add 2-3 feet of reach', 'Laser effectively unlimited; every weapon draws on the cyborg''s power supply', 'Each laser blast is one melee attack', NULL, NULL, NULL, 'Anti-personnel and anti-vehicle. A forearm with a light precision laser suited to sniping, a pair of top-mounted Vibro-Swords, a long underarm blade for slashing and parrying, and long fingers ending in Vibro-Claws. +1 to strike with the laser on Aimed and Called Shots; +1 to strike and parry and +2 to disarm with the blades. A heavy cyborg can have one or two additional arms; a pair adds one melee attack. Shown on the Assassin Cyborg Shocktrooper. One of the modular Mekanikal weapon arms built for Heavy Machines and Cyborg Shocktroopers; any of them can be swapped for another. It makes for a large, oversized forearm but keeps a fully articulated hand.', 'Rifts World Book 17: Warlords of Russia p.105'),
('mekanikal-cutter-weapon-utility-arm', 'Mekanikal Cutter Weapon/Utility Arm', 'rifts', 'cybernetics', NULL, 250000, '250,000 credits per arm, three tentacles each.', 'Lasers (2) 1D6 or 2D6 M.D. each; Vibro-Knife 1D6 M.D.; whip attack 2D6 S.D.C.', 1, 'Lasers 1,200 feet (366 m); Vibro-Blade and physical blows three feet beyond normal reach', 'Lasers effectively unlimited, drawing on the cyborg''s power supply', 'Each tentacle attack is one melee action', NULL, NULL, 15, 'Anti-personnel and anti-vehicle. Three prehensile tentacles slide from a forearm compartment, one tipped with a Vibro-Knife and two with lasers, for construction, repair or combat. They hold or carry up to 120 pounds, strike and entangle; P.S. and P.P. 12. Each tentacle has 15 M.D.C. and is hit only by a called shot at -3, with no penalty in hand to hand. +1 attack per melee round and +1 to parry per set, two sets at most, one per arm. The forearm is oversized but keeps a fully articulated hand.', 'Rifts World Book 17: Warlords of Russia p.105-106');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 33 Warlords of Russia bionics rows are in' AS assertion, count(*) AS got, 33 AS want
  FROM gear WHERE slug IN ('cyberlink-vehicle-interfacing', 'weapon-to-cyborg-energy-link', 'robot-strength-optional-feature', 'interchangeable-parts', 'light-filters-cyber-optic', 'panorama-cluster-lens', 'passive-nightvision-eye', 'wide-angle-vision', 'spectra-eye', 'super-telescopic-eye', 'low-frequency-audio-rig', 'audio-filter-and-enhancement', 'synthetic-voice-enhancer', 'gromeko-friend-or-foe-identification-computer', 'cyborg-jet-pack', 'cyberjet-nodes', 'head-collar-and-hood', 'cyborg-helmet-and-face-plate', 'hydraulic-leg-boosters', 'shoulder-weapon-mounts-clamps', 'schematic-sensor-hand', 'tool-hand', 'tool-mechanics-arm', 'tread-leg-mode', 'electro-cannon-forearm-blaster', 'forearm-weapon-guards', 'hydraulic-hammer-hand', 'hydraulic-ram-arm', 'laser-cannon-arm', 'mekanikal-rail-gun-weapon-arm', 'mekanikal-barrage-weapon-arm', 'mekanikal-vibro-blade-multi-weapon-arm', 'mekanikal-cutter-weapon-utility-arm');
SELECT 'and every one cites Warlords of Russia' AS assertion, count(*) AS got, 33 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 17: Warlords of Russia p.%' AND slug IN ('cyberlink-vehicle-interfacing', 'weapon-to-cyborg-energy-link', 'robot-strength-optional-feature', 'interchangeable-parts', 'light-filters-cyber-optic', 'panorama-cluster-lens', 'passive-nightvision-eye', 'wide-angle-vision', 'spectra-eye', 'super-telescopic-eye', 'low-frequency-audio-rig', 'audio-filter-and-enhancement', 'synthetic-voice-enhancer', 'gromeko-friend-or-foe-identification-computer', 'cyborg-jet-pack', 'cyberjet-nodes', 'head-collar-and-hood', 'cyborg-helmet-and-face-plate', 'hydraulic-leg-boosters', 'shoulder-weapon-mounts-clamps', 'schematic-sensor-hand', 'tool-hand', 'tool-mechanics-arm', 'tread-leg-mode', 'electro-cannon-forearm-blaster', 'forearm-weapon-guards', 'hydraulic-hammer-hand', 'hydraulic-ram-arm', 'laser-cannon-arm', 'mekanikal-rail-gun-weapon-arm', 'mekanikal-barrage-weapon-arm', 'mekanikal-vibro-blade-multi-weapon-arm', 'mekanikal-cutter-weapon-utility-arm');
SELECT 'every row is a cybernetics row' AS assertion, count(*) AS got, 33 AS want
  FROM gear WHERE category = 'cybernetics' AND source_book LIKE 'Rifts World Book 17: Warlords of Russia p.10%';
SELECT 'the Passive Nightvision Eye carries no price' AS assertion, count(*) AS got, 1 AS want
  FROM gear WHERE slug = 'passive-nightvision-eye' AND cost IS NULL;
SELECT 'the four Mekanikal arms are in at their printed prices' AS assertion, count(*) AS got, 4 AS want
  FROM gear WHERE (slug IN ('mekanikal-rail-gun-weapon-arm', 'mekanikal-barrage-weapon-arm', 'mekanikal-vibro-blade-multi-weapon-arm') AND cost = 90000) OR (slug = 'mekanikal-cutter-weapon-utility-arm' AND cost = 250000);

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-warlords-of-russia-bionics.sql');
