-- The Inca Warrior O.C.C., Rifts World Book 9: South America 2 p.23-24.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-inca-warrior-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'inca-warrior', 'Inca Warrior', 'rifts', '---
id: inca-warrior
occ_group: men-of-arms
men_of_arms: true
name: Inca Warrior
system: rifts
source_book: Rifts World Book 9: South America 2 p.23-24
category: occ
xp_table: [0, 2151, 4301, 8601, 17201, 25501, 36001, 52001, 73001, 98001, 134001, 184001, 240001, 295001, 365001]
attribute_requirements: { ME: 12 }
starting_money: "1d4x1000"
bonuses:
  attributes: { PS: "1d6", PE: "1d6", PP: "1d4" }
  pools: { sdc: "1d4x10" }
  combat: { initiative: 1, strike: 1, parry: 1, dodge: 2, roll: 2, pull_punch: 2 }
  saves: { spell_magic: 2, psionics: 3 }
skills:
  hand_to_hand: { costs: { martial_arts: 1 } }
  occ_skills:
    - { name: "Language: Quechua", base: 98, per_level: 0, note: "98%." }
    - { choose: 2, from: ["Language: Other"], bonus: 25, note: "Two languages of choice (+25%). Taken once per language." }
    - { name: "Wilderness Survival", base: 45, per_level: 5, note: "+15%." }
    - { name: "Running", base: 0, per_level: 0 }
    - { name: "Climbing", base: 50, per_level: 5, note: "+10%." }
    - { name: "Lore: Demons & Monsters", base: 35, per_level: 5, note: "+10%; the book prints Demon and Monster Lore." }
    - { name: "Robot Combat Elite", base: 0, per_level: 0, note: "Printed as Power Armor Combat: Elite (Nazca PA or Sun Power Armor)." }
    - { name: "W.P. Axe", base: 0, per_level: 0, note: "The book says treat as W.P. Sword." }
    - { name: "W.P. Archery", base: 0, per_level: 0, note: "Printed as W.P. Sling (treat as Archery and Targeting)." }
    - { name: "W.P. Blunt", base: 0, per_level: 0 }
    - { name: "W.P. Energy Rifle", base: 0, per_level: 0 }
    - { name: "Hand to Hand: Expert", base: 0, per_level: 0, note: "Can be changed to Martial Arts at the cost of one other skill." }
  occ_related_skills:
    count: 8
    categories:
      - "Communications"
      - { name: "Domestic", bonus: 10 }
      - { name: "Espionage", bonus: 5 }
      - { name: "Medical", only: ["Holistic Medicine"] }
      - "Physical"
      - "Pilot"
      - { name: "Pilot Related", bonus: 5 }
      - "Rogue"
      - "Science"
      - { name: "Technical", bonus: 10 }
      - "Weapon Proficiencies"
      - { name: "Wilderness", bonus: 10 }
    note: "Electrical, Mechanical and Military: none. Medical: Holistic Medicine only."
    schedule:
      - { level: 3, count: 1 }
      - { level: 5, count: 1 }
      - { level: 7, count: 1 }
      - { level: 12, count: 1 }
  secondary_skills:
    count: 8
    categories:
      - "Communications"
      - "Domestic"
      - "Espionage"
      - { name: "Medical", only: ["Holistic Medicine"] }
      - "Physical"
      - "Pilot"
      - "Pilot Related"
      - "Rogue"
      - "Science"
      - "Technical"
      - "Weapon Proficiencies"
      - "Wilderness"
equipment_starting:
  - { item_id: "holy-axe", qty: 1 }
  - { item_id: "amulet-of-protection", qty: 1 }
  - { item_id: "holy-sun-sling", qty: 1 }
  - { choose: 1, label: "rifle", qty: 1, from: ["inti-20-variable-laser-rifle", "illapa-5-rocket-rifle"], note: "Either an Inti-20 laser rifle or an Illapa-5 rocket rifle." }
  - { choose: 1, label: "energy pistol of choice", qty: 1, from: ["inti-10-variable-laser-pistol", "illapa-1-rocket-pistol"], note: "The book says an energy pistol of choice; this is the Empire of the Sun''s own two pistols (printed 56-58)." }
  - { item_id: "fragmentation-grenade", qty: 6, note: "Six grenades, equivalent to Coalition grenades." }
  - { item_id: "gilded-body-armor", qty: 1 }
  - { item_id: "clothing", qty: 3, note: "Three sets of ordinary clothing." }
  - { item_id: "dress-clothing", qty: 2, note: "Two sets of ceremonial, traditional clothing." }
  - { item_id: "survival-kit", qty: 1 }
  - { item_id: "walkie-talkie", qty: 1, note: "The book says a radio." }
special_abilities:
  - name: "Holy Axe"
    description: "A minor holy weapon: 4D6+6 M.D., heals 1D8+1 S.D.C. or M.D.C. six times a day, and glows golden when wielded against supernatural beings."
  - name: "Amulet of Protection"
    description: "Projects the Armor of Ithan spell at 10th level strength (100 M.D.C.), activated at will six times a day; each activation lasts 10 minutes."
  - name: "Holy Sun Sling"
    description: "Fires small balls of magical fire: 4D6 M.D., range 2000 feet (610 m)."
  - name: "Additional Holy and Magical Weapons"
    description: "On dangerous missions the warrior is issued either Nazcan Mystical Armor or Sun Power Armor. At sixth level a warrior still serving the Empire is given a greater holy weapon (see Rifts Atlantis on rune and other magic weapons)."
level_progression:
  - { level: 6, grants: ["A greater holy weapon, if still serving the Empire"] }
restrictions:
  - "Physical attributes should all be at least 10 (advisory; only the M.E. 12 minimum is enforced)."
  - "Cybernetics: starts with none and rarely gets any."
side_effects: "Most training is mystical or archaic: the warriors know little about vehicles, power armor or other advanced systems and tend to underestimate technological threats."
extraction_notes: |
  - Rifts World Book 9: South America 2 printed 23-24 (cache p023-p024,
    page_offset 0); the stat block starts on printed 23 and the secondary
    skills, equipment, money and cybernetics lines run onto printed 24.
    Read off a 200 dpi render of printed 23 as well as the OCR; they agree.
  - xp_table: the Destroyer ''Borg and Inca Warrior ladder, printed 192,
    lower bounds, as briefed. The survey records that level 10 prints
    98.001 with a period; stored as 98001.
  - occ_group men-of-arms and men_of_arms true: the book files no O.C.C.
    under a group heading (it sits in O.C.C.s and R.C.C.s of the Empire of
    the Sun, printed 20); the Inca Warrior is the Empire''s elite fighting
    class, trained exhaustively in the arts of war, with no spell casting of
    its own. No sdc_base is printed; the +1D4x10 S.D.C. is a pool bonus.
  - Attribute requirements: M.E. 12 stored. "Physical attributes should
    all be at least a 10" is phrased as advice and is a restriction line,
    not an enforced minimum.
  - Bonuses: +1D6 P.S., +1D6 P.E., +1D4 P.P. (dice attribute bonuses),
    +1D4x10 S.D.C., +1 initiative, +1 strike and parry, +2 dodge, +2
    roll and pull punch, +2 save vs magic (spell_magic), +3 vs psionics.
    All unconditional, and the book says they add to attribute and skill
    bonuses.
  - SKILLS: Quechua 98; two languages of choice +25 as two Language: Other
    picks; Wilderness Survival 30+15 = 45; Running; Climbing 40+10 = 50;
    Demon and Monster Lore -> Lore: Demons & Monsters 25+10 = 35. Power
    Armor Combat: Elite (Nazca PA or Sun Power Armor) -> the catalog''s
    generic Robot Combat Elite with the note; there is no Nazca or Sun
    Power Armor elite row. W.P. Axe exists in the catalog and is used,
    though the book says treat it as W.P. Sword. W.P. Sling "treat as
    Archery and Targeting" -> W.P. Archery, the catalog''s convention for
    Archery and Targeting. W.P. Blunt, W.P. Energy Rifle, Hand to Hand:
    Expert (to Martial Arts for one other skill: costs martial_arts 1).
  - Related: 8, +1 at levels 3, 5, 7 and 12. Electrical, Mechanical and
    Military are None and omitted. Pilot is Any, robots and power armor
    included, so no exclusion. Horsemanship and Cowboy are not on the
    printed list and are not granted. Secondary: 8, same limits without
    the bonuses.
  - EQUIPMENT: Holy Axe, Amulet of Protection and Holy Sun Sling are this
    book''s catalog rows; their stats are repeated as special_abilities
    so the class detail shows them. Rifle: Inti-20 or Illapa-5. "An energy
    pistol of choice" is a choice of the Empire''s Inti-10 and Illapa-1.
    Six grenades "equivalent to Coalition grenades" -> fragmentation-
    grenade (the Coalition hand grenade) x6. Gilded Armor (70 M.D.C.) ->
    gilded-body-armor. Three ordinary outfits -> clothing x3; two
    ceremonial, traditional outfits -> dress-clothing x2 (nearest row,
    noted). Survival kit -> survival-kit. "A radio" -> walkie-talkie
    (judgement: a handheld set; field-radio would also fit).
  - NOT equipment: the Nazcan Mystical Armor or Sun Power Armor issued for
    dangerous missions (power armor, and mission-issue rather than
    starting gear) and the greater holy weapon at level 6 (a choice from
    Rifts Atlantis); both are ability and level_progression text.
  - Money: 1D4x1000 credits. Cybernetics: none; a restriction line.
  - NOT supersedes_race: an ordinary training O.C.C. that says nothing
    about replacing what the character was, so class-check''s warning that
    a race stating its own starting_money keeps the race''s value is the
    intended composition, not a defect.
---

## Lore

The Inca Warriors are the elite who guard the Incas and their Empire, set
apart from the ordinary militias that fill most of the Imperial Armies. Each
is armed with holy and magical weapons and drilled relentlessly in war, and
the combination of that training and their talismans lets one stand against
power armor or a squad of modern infantry.

Few of them understand technology; only those trained in the free city of
Arequipa learn to handle power armor, robots and similar machines. The rest
trust their enchanted weapons, skill and cunning, and their unfamiliarity
with machines has killed more than one of them. Traditionally the warriors
were men, but women have lately been given the same weapons and have served
with distinction.

They are sent alone or in small teams to scout, hunt guerrillas and
terrorists, sabotage the Arkhons and spy, and they often fight beside the
True Incas or lead units of regular soldiers. There are only about two
thousand of them, because there are no more holy weapons to arm others.

## GM Notes

Alignment: any, but usually good or unprincipled.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'inca-warrior');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'inca-warrior';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-inca-warrior-class.sql');
