-- The CS EOD Specialist O.C.C., Rifts World Book 11: Coalition War Campaign p.73-75.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-cs-eod-specialist-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'cs-eod-specialist', 'CS EOD Specialist', 'rifts', '---
id: cs-eod-specialist
men_of_arms: true
name: CS EOD Specialist
system: rifts
source_book: Rifts World Book 11: Coalition War Campaign p.73-75
category: occ
occ_group: men-of-arms
race_restrictions:
  only: ["none"]
  note: "This entry prints no racial line. The bar is the Coalition''s own, which RUE states for every other CS O.C.C. (p.230, 233, 237): human only. In Rifts a human character takes no R.C.C., so \"none\" is the human case."
attribute_requirements:
  IQ: 9
  ME: 14
  PP: 14
starting_money: "1800"
skills:
  hand_to_hand: { costs: { expert: 2, martial_arts: 3 } }
  occ_skills:
    - { name: "Literacy: Native Language", base: 60, per_level: 5, note: "+20%. Printed as Literacy: American." }
    - { name: "Mathematics: Basic", base: 70, per_level: 5, note: "+25%. Printed as Basic Math." }
    - { name: "Radio: Basic", base: 55, per_level: 5, note: "+10%; the book prints (10%) without the plus sign." }
    - { name: "Computer Operation", base: 50, per_level: 5, note: "+10%. Printed as Computer Operations." }
    - { name: "Basic Electronics", base: 45, per_level: 5, note: "+15%" }
    - { name: "Mechanical Engineer", base: 35, per_level: 5, note: "+10%; the book prints (10%) without the plus sign." }
    - { name: "Demolitions", base: 80, per_level: 3, note: "+20%" }
    - { name: "Demolitions Disposal", base: 80, per_level: 3, note: "+20%" }
    - { name: "Demolitions: Underwater", base: 66, per_level: 4, note: "+10%. Printed as Underwater Demolitions." }
    - { name: "NBC Warfare", base: 45, per_level: 5, note: "+10%. Printed as Nuclear, Biological, & Chemical Warfare." }
    - { name: "Trap Construction", base: 20, per_level: 4, note: "+15% ONLY when explosives are involved (35%), so the stored figure is the catalog base." }
    - { name: "Trap/Mine Detection", base: 34, per_level: 5, note: "+14%; the book prints (14%) without the plus sign." }
    - { name: "Hover Craft (ground)", base: 60, per_level: 5, note: "+10%. Printed as Pilot Hovercraft." }
    - { name: "W.P. Energy Rifle", base: 0, per_level: 0 }
    - { name: "Hand to Hand: Basic", base: 0, per_level: 0, note: "May be changed to Expert at the cost of two O.C.C. Related Skills, or to Martial Arts for three." }
  occ_related_skills:
    count: 6
    categories:
      - { name: "Communications", bonus: 5 }
      - "Domestic"
      - { name: "Electrical", bonus: 10 }
      - { name: "Espionage", except: ["Sniper", "Tracking (people)"], bonus: 10 }
      - { name: "Mechanical", bonus: 10 }
      - { name: "Medical", only: ["First Aid"] }
      - { name: "Military", bonus: 10 }
      - { name: "Physical", except: ["Acrobatics", "Wrestling"] }
      - { name: "Pilot", except: ["Robots & Power Armor", "Robot Combat: Basic", "Robot Combat Elite", "Robot Combat Elite: Glitter Boy", "Robot Combat Elite: SAMAS", "Robot Combat Elite: T-31 Super Trooper", "Robot Combat Elite: X-1000 Ulti-Max", "Robot Combat Elite: X-10A Predator", "Robot Combat Elite: X-2000 Dyna-Max", "Robot Combat Elite: X-2500 Black Knight", "Robot Combat Elite: X-500 Forager", "Robot Combat Elite: X-535 Jager", "Robot Combat Elite: X-545 Super Jager", "Robot Combat Elite: X-60 Flanker", "Air Assault Armor", "Military: Tanks & APCs", "Military: Jet Fighters", "Military: Combat Helicopter", "Fighter Combat: Basic", "Fighter Combat: Elite"], bonus: 5 }
      - { name: "Pilot Related", bonus: 5 }
      - "Rogue"
      - { name: "Science", bonus: 10 }
      - { name: "Technical", bonus: 5 }
      - "Weapon Proficiencies"
      - { name: "Wilderness", only: ["Land Navigation", "Hunting"] }
    note: "The Pilot exclusion is printed as robot, power armor, tank, APC and most combat aircraft skills; every combat aircraft skill the catalog holds is excluded, since the book names no survivor. Technical is printed +5%, and +10% for Literacy and Language skills; the category bonus stores the +5%."
    schedule:
      - { level: 3, count: 2 }
      - { level: 6, count: 1 }
      - { level: 9, count: 1 }
      - { level: 12, count: 1 }
  secondary_skills:
    count: 5
equipment_starting:
  - { choose: 1, label: "light or heavy Dead Boy body armor", qty: 1, from: ["ca-3-light-dead-boy-armor", "ca-4-standard-dead-boy-armor"] }
  - { item_id: "black-clothing-covert", qty: 1 }
  - { item_id: "winter-ski-mask", qty: 1 }
  - { item_id: "uniform", qty: 1 }
  - { item_id: "dress-uniform", qty: 1 }
  - { item_id: "gloves", qty: 1 }
  - { item_id: "disposable-surgical-gloves", qty: 100 }
  - { item_id: "tinted-goggles", qty: 1 }
  - { item_id: "stethoscope", qty: 1 }
  - { item_id: "pocket-computer", qty: 1 }
  - { item_id: "pdd-pocket-audio-digital-disc-recorder-player", qty: 1 }
  - { item_id: "pocket-laser-distancer", qty: 1 }
  - { item_id: "pocket-flashlight", qty: 1 }
  - { item_id: "portable-tool-kit", qty: 1 }
  - { item_id: "wilk-s-laser-scalpel", qty: 1 }
  - { item_id: "survival-knife", qty: 1 }
  - { choose: 1, label: "CP-40 or C-12 energy rifle", qty: 1, from: ["cp-40-pulse-laser-rifle", "c-12-laser-rifle"] }
  - { item_id: "e-clip", qty: 4 }
  - { item_id: "knapsack", qty: 1 }
  - { item_id: "backpack", qty: 1 }
  - { item_id: "utility-belt", qty: 1 }
  - { item_id: "battle-harness", qty: 1 }
  - { item_id: "air-filter", qty: 1 }
  - { item_id: "canteen", qty: 1 }
special_abilities:
  - name: "Homemade Explosives"
    description: "A skill exclusive to the EOD Specialist: 40% +4% per level of experience to make homemade explosives, boost the killing power of existing ones and set booby traps. Makes Molotov cocktails, exploding canisters, flash, tear gas and smoke bombs, S.D.C. and light M.D. grenades, explosive charges and mines, military grade grenades and mines from salvaged explosives, and can retool a military explosive for 25% more damage (at least an hour each, about a dozen before an operation). The book prints range, damage, radius and cost for each."
restrictions:
  - "Cybernetics: none to start, but augmented hearing, sight and sensor hands are common. Any of the Rifts RPG bionics may be available, and at the GM''s option those of Rifts Japan, Underseas and Triax and the NGR; unauthorized systems cannot be bought."
  - "On assignment: hovercycle or other vehicle, rocket launchers and mini-missiles, radiation suit (Dead Boy armor is not an environmental suit), and the explosives and EOD equipment the mission needs."
extraction_notes: "PAGE SPAN: the class heading is printed 73 and the Money and Cybernetics blocks end printed 75. HOMEMADE EXPLOSIVES has no catalog skill row, so the book''s 40% +4% per level is in special_abilities and does not progress on the sheet; a catalog row would be the fix. Trap Construction''s +15% applies only when explosives are involved and is left at the catalog base with the conditional figure in the note. Radio: Basic, Mechanical Engineer and Trap/Mine Detection are printed as (10%), (10%) and (14%) with no plus sign (confirmed on a render); read as bonuses like every other entry. No Language: Native Tongue is printed; Literacy: American is. Hand to Hand: Basic changes to Expert for two related skills and Martial Arts for three. Equipment: light or heavy Dead Boy is stored as the CWC CA-3 light or CA-4 standard; the PC-3000 hand-held computer is the pocket-computer row; the utility/combat harness is battle-harness; the laser scalpel is Wilk''s model as printed; the black clothing''s ski-mask is winter-ski-mask; fine leather gloves are the generic gloves row. The two satchels have no gear row (purse-satchel is a purse) and are left out. Money: base pay 1,800 credits a month plus hazard and combat pay; starts with one month''s basic salary."
---

## Lore

The Explosive Ordnance Disposal Specialist is trained to use, handle and dispose
of explosives and other dangerous substances - one of the few CS military
programs that teaches reading, writing and arithmetic. EOD soldiers learn
explosive compounds, fuses, primers, blasting caps, timers and triggers, basic
electronics, how best to deploy explosives in combat, and how to improvise
homemade explosives and simple, effective traps.

Many also learn basic espionage, because they often serve with Special Forces on
sabotage and strategic strikes. They tend to be daring tinkerers with steady
hands and steady nerves, resourceful and inventive.

## GM Notes

**On assignment:** 1D6+6 hand grenades of choice, 4 smoke grenades, 1D4 shape
charges, 2D4 flares, and access to nearly any explosive or EOD equipment the
mission calls for, up to fusion blocks, plus optics, cameras, mine detection
gear and rations. Most have mid-level security clearance; senior officers may
have the highest.

The Homemade Explosives list (printed 74-75) gives each device''s range, damage,
radius and cost to make, from a 5 credit Molotov cocktail to a 3,100 credit
anti-armor mine.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'cs-eod-specialist');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'cs-eod-specialist';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-cs-eod-specialist-class.sql');
