-- The Fallen Cosmo-Knight O.C.C., Rifts Dimension Book 2: Phase World p.102-104.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-fallen-cosmo-knight-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'fallen-cosmo-knight', 'Fallen Cosmo-Knight', 'rifts', '---
id: fallen-cosmo-knight
name: Fallen Cosmo-Knight
system: rifts
category: occ
occ_group: optional
source_book: Rifts Dimension Book 2: Phase World p.102-104
xp_table: [0, 3001, 5401, 10801, 21601, 31601, 50001, 80001, 120001, 170001, 230001, 300001, 380001, 470001, 600001]
attribute_dice:
  IQ: "3d6"
  ME: "4d6-2"
  MA: "3d6"
  PS: "3d6+10"
  PP: "3d6"
  PE: "3d6+4"
  PB: "3d6"
  Spd: "2d4x10-10"
mdc_base: "2d6x10+30, plus 2d6 M.D.C. per level of experience"
ppe_base: "1d6x50"
skills:
  occ_skills:
    - { choose: 3, from: ["Language: Other"], bonus: 0, per_level: 5, note: "Three languages of choice. The Cosmo-Knight prints +20% and the fallen knight''s blanket -20% cancels it exactly, so a fallen knight speaks his three languages at the catalog''s own 50% +5%/level. The zero is written OUT rather than omitted: an omitted bonus is a bonus nobody set, and this one was computed." }
    - { name: "Radio: Basic", bonus: -15, note: "Printed +5% on the Cosmo-Knight, less the fallen knight''s -20%." }
    - { name: "Navigation: Stellar", bonus: -5, note: "Printed as Navigation: Space (+15%) on the Cosmo-Knight, less -20%. A fallen knight does NOT get the Cosmo-Knight''s 89% figure: that came from Galactic Awareness, and all former cosmo-knight powers are lost. The catalog files the row as Navigation: Stellar." }
    - { name: "Lore: Demons & Monsters", bonus: -10, note: "Printed as Demon and Monster Lore (+10%) on the Cosmo-Knight, less -20%." }
    - { name: "Space: Zero Gravity Movement & Combat", bonus: -10, note: "Printed as Movement: Zero Gravity (+10%) on the Cosmo-Knight, less -20%. The catalog row has a base of 0 because the book states it as the P.P. attribute number x5%; see BOOK-INGEST-AUDIT.md F2." }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "W.P.: one of choice. A W.P. carries no percentage, so the -20% does not reach it." }
    - { name: "Hand to Hand: Martial Arts", base: 0, per_level: 0 }
  occ_related_skills:
    count: 10
    categories:
      - { name: "Communications", bonus: -20 }
      - { name: "Domestic", bonus: -15 }
      - { name: "Electrical", bonus: -20 }
      - { name: "Espionage", bonus: -15 }
      - { name: "Mechanical", bonus: -20 }
      - { name: "Medical", bonus: -20 }
      - { name: "Military", bonus: -20 }
      - { name: "Physical", bonus: -20 }
      - { name: "Pilot", bonus: -15 }
      - { name: "Pilot Related", bonus: -20 }
      - { name: "Rogue", bonus: -15 }
      - { name: "Science", bonus: -15 }
      - { name: "Technical", bonus: -10 }
      - { name: "Weapon Proficiencies", note: "NO -20% here. Every W.P. row in the catalog is base 0, per_level 0 - a weapon proficiency carries no percentage for a penalty to reduce - so a -20 would render a W.P. at minus twenty per cent. The blanket penalty reaches the fourteen categories that have a percentage and stops at this one." }
      - { name: "Wilderness", bonus: -20 }
    schedule: [{ level: 4, count: 2 }, { level: 7, count: 2 }, { level: 10, count: 1 }, { level: 12, count: 1 }]
    note: "The Cosmo-Knight''s list and schedule exactly, with every category''s printed bonus reduced by 20 points - so the six that carried a percentage keep part of it and the eight remaining percentage-bearing ones go to -20%. Weapon Proficiencies is the exception and takes none, because a W.P. row is base 0 with no percentage to reduce. All fifteen categories stay open; the fallen knight loses proficiency, not access."
  secondary_skills:
    count: 6
    note: "Six secondary skills, as the Cosmo-Knight. THE -20% IS NOT APPLIED HERE AND CANNOT BE: the parser rejects a bonus on a secondary category outright, on the reasoning that the parenthetical percentage a book prints applies to related selections only. This entry is the counter-example - its penalty is blanket rather than parenthetical - so apply -20% to secondary skills at the table."
bonuses:
  saves: { disease: 5, toxins_poisons: 5, mind_control: 5, harmful_drugs: 5 }
natural_abilities:
  - { name: "Supernatural Strength and Endurance", description: "P.S. and P.E. are still considered SUPERNATURAL, reduced though they are. It is the one piece of the cosmic body that survives the fall intact." }
  - { name: "Very Long Life Span", description: "Fallen knights live a very long time, which is part of the problem: most give up trying to regain their status after a few decades and have to decide what to do with the rest of a very long life." }
special_abilities:
  - name: "Resistant to Energy"
    description: "Non-magical energy attacks do HALF damage. This is what is left of the cosmo-knight''s near-immunity, which divided energy damage by 100 and ignored fire entirely."
  - name: "Bio-Regeneration"
    description: "1D6 M.D.C. per hour - against the cosmo-knight''s 1D4x10 per minute."
  - name: "The Cosmic Weapon, If He Had One"
    description: "A knight who forged a cosmic weapon keeps it. It still inflicts 1D4x10 M.D. and still flies back when thrown, but its throwing range is HALVED and whatever additional power was bought for it is gone. The cosmic armor is not kept: its 500 M.D.C. is lost with the fall. Nothing here is granted automatically - a fallen knight has a weapon only if the character had one before the fall, which is a fact about his history rather than a feature of the class."
  - name: "Magic OR Psionics, Learned Afterwards"
    description: "A fallen knight may learn magic or psionics, not both. The book says to use the ley line walker O.C.C. for spells or the mind melter O.C.C. for psionic powers, taking ONLY what those classes gain in spells or powers and NONE of their special abilities; a fallen knight may also become a witch (Rifts Conversion Book One) or a servant of a god (the Warriors of Valhalla O.C.C., Rifts Conversion Book Two). All of it starts at FIRST level whatever the knight''s experience was as a cosmo-knight. Nothing is granted here, because the book grants nothing: it points at another class''s progression and takes half of it. The ley line walker and the mind melter are both in this catalog and can be read directly."
  - name: "Regaining the Power"
    description: "Near impossible. Of the fallen knights who try, about one in a thousand succeeds, and in all recorded history only a dozen or so have satisfied the Cosmic Forge and gone on to be legendary heroes. Only a life of unquestionable integrity and dedication to goodness gets a fallen knight reborn with cosmic power. Some regain their powers only in the moment of an impossible fight, long enough to spend their lives well."
restrictions:
  - "Alignment: any. Principled or scrupulous for one who has seen the error of his ways, unprincipled or anarchist for one looking out for himself but not thoroughly corrupted, diabolic or miscreant for one who turned against everything he stood for, aberrant for one keeping a twisted version of the code - common among vigilantes, fanatical freedom fighters, mercenaries and rulers."
  - "Gains no P.P.E. with level unless the character becomes a practitioner of magic."
  - "Must now breathe, eat and sleep like a normal man, or suffer the consequences."
side_effects: "MAGIC, PSIONICS AND KINETIC ATTACKS DO FULL DAMAGE; energy weapons do half. A fallen knight is far more killable than a cosmo-knight and knows exactly how much has been lost, which is most of what makes the class what it is."
extraction_notes: |
  - Read from the OCR cache of a scan and verified against 200 dpi renders of
    printed 102, 103 and 104. The heading "The Fallen Knights" is below the
    Cosmo-Knight''s Cybernetics line in the right column of printed 102, and the
    entry''s last line is the Skills line in the LEFT column of printed 104.
    Everything below it on that page belongs to the next section, and the
    boundary is in the SAME column rather than at the column break: the Skills
    line is followed by a full-width illustration and then by the heading
    "Creating More Alien Races", still in the left column, the nine-step
    generator that is not a class. The right column of 104 opens with unheaded
    prose continuing that section. A first draft of this note put the heading
    in the right column, which is the reading the OCR''s linear order suggests
    and the render refutes. The survey''s range of 102-104 is correct as printed
    and was re-derived rather than inherited.
  - THE BOOK CONTRADICTS ITS OWN EXPERIENCE TABLE AND THE TABLE WINS. Printed
    103 says level improvement continues using the Fallen Knight Experience
    Table. THERE IS NO SUCH TABLE. Printed 183 was rendered whole and carries
    FOURTEEN ladders; one is headed `Cosmo-Knight` and none is headed Fallen,
    and `Fallen` appears nowhere in the OCR of printed 183 - it is in the cache
    only on printed 5, 6, 96 and 99-104. The alphabetical index on printed 6
    files this entry as "Cosmo-Knight: Fallen O.C.C." at page 102, a sub-entry
    of the Cosmo-Knight rather than a class of its own. So the PROSE LOST and
    the table won, and the fallen knight shares the Cosmo-Knight ladder, which
    is what is stored here. This is the Royal Kreeghor situation with the signs
    reversed: there a section heading corrected a survey built from the
    Contents; here a table corrects a sentence.
  - IT IS PLAYABLE, AND ITS OWN SUBHEADING SAYS BOTH THINGS AT ONCE. The
    heading on printed 102 reads "Optional Player Character or NPC Villains" -
    a label neither the Royal Kreeghor rule (a heading carrying the NPC label
    the Contents does not) nor the Vacuum Wasp rule (playable entries
    interleaved with NPC ones) covers, because it is both labels in one line.
    Printed 103 settles it four paragraphs later with a bold line of its own:
    available as player characters. The index on printed 6 agrees, calling it
    an O.C.C. and attaching no NPC label, where it does label the Second Stage
    Promethean and three others NPC. Two authorities for playable, none
    against.
  - IT IS TWO CLASSES AND NOT A VARIANT, AND `VARIANT_OVERRIDES` IS WHY. The
    entry is printed entirely as deltas off the Cosmo-Knight - use its
    attributes but reduce them, halve the M.D.C., halve the P.P.E., same skills
    at -20% - which reads exactly like `variants`. It cannot be one.
    `VARIANT_OVERRIDES` in `js/parser.js` is a literal list, grepped rather
    than assumed: `attribute_dice`, `attribute_requirements`, the four pool
    bases, `starting_money`, `bonuses` and `skill_overrides`. `special_abilities`
    is NOT among them, so a variant INHERITS the base''s abilities wholesale -
    and the sentence this entry turns on is that ALL former cosmo-knight powers
    and O.C.C. bonuses are lost. A variant would have shipped a fallen knight
    still carrying resistance-to-energy-divided-by-100, superluminal flight,
    cosmic blasts, galactic awareness, the 500-point cosmic armor and the +2/+2
    bonus block: every power the entry exists to take away. `skill_overrides`
    could restate the seven O.C.C. skills at -20% and could not touch the ten
    related picks or the six secondary ones, so even the half that fits fits
    only partly. Two classes, on the draconid''s precedent from batch 7.
  - THE ATTRIBUTE DICE ARE THE COSMO-KNIGHT''S WITH THE PRINTED DELTAS ALREADY
    APPLIED - I.Q. -2, M.E. -6, M.A. -4, P.S. -22, P.P. -6, P.E. -6, Spd. -10,
    and no reduction printed for P.B., which therefore keeps 3D6. The
    take-the-higher rule the Cosmo-Knight states is inherited with the
    attributes and is equally unstorable; see BOOK-INGEST-AUDIT.md F11, whose
    measurements cover this class too.
  - THE HALVED POOLS ARE ARITHMETIC ON A PRINTED FIGURE, NOT A GUESS, AND THE
    HALVES ARE EXACT. Half of the Cosmo-Knight''s 4D6x10+60 is stored as
    2D6x10+30: identical range, 50 to 150 against half of 100 to 300, and
    identical mean, 100 against half of 200. Half of 1D6x100 is stored as
    1D6x50: identical range and mean again. The per-level 4D6 is halved to 2D6
    the same way. `mdc_base` and `ppe_base` accept only a dice grammar with no
    division in it, so the alternative was storing the cosmo-knight''s full
    figures and describing the halving in prose, which would have put a
    fallen knight on the sheet at twice the toughness the book gives him.
  - NO `Money:` LINE AND NO EQUIPMENT LIST. Grepped across printed 99 to 104:
    neither cosmo-knight entry prints one. The Cosmo-Knight''s Standard
    Equipment is prose naming no item, and this entry has no equipment line at
    all. So there is no `starting_money` and no `equipment_starting`, and
    `--field-sources` has nothing to check on this class rather than having
    missed something.
  - THE MAGIC-OR-PSIONICS OPTION IS DESCRIBED AND NOT GRANTED. The book points
    at the ley line walker and the mind melter for progression and withholds
    their special abilities, and adds two classes from books this catalog does
    not hold. A `magic` or `psionics` block would have to replicate one of two
    other classes'' whole ladders and then pick between them at creation, which
    nothing here can express; the Time Master''s temporal magic in batch 9 is
    the precedent for granting less rather than granting an ungated
    approximation. Both named classes are in this catalog and a player can read
    them.
  - THIS CLASS COST THE REGRESSION SUITE ONE PINNED INVARIANT, AND IT IS THE
    ONLY CODE THIS BATCH TOUCHED. `regression.mjs` required every language
    choice group to carry a bonus GREATER THAN ZERO. A fallen knight''s is
    exactly zero - the Cosmo-Knight''s +20% less this entry''s -20% - and the
    pick then resolves at the catalog''s own 50% +5%/level, which is the right
    answer. The check''s own comment says what it was written to catch: a bonus
    LOST in a rewrite, which arrives as `undefined` rather than as 0. So the
    comparison moved from `> 0` to `>= 0` and the check still catches every
    case it was built for, while no longer asserting something the books do not
    guarantee. The zero is written out explicitly here so an absent bonus and a
    computed one still read differently. Called out because the batch''s
    standing rule is that a book changes no code, and this is the exception -
    it is a TEST rather than the app, the schema, a validator or a generator,
    and it is one operator.
  - THE -20% DOES NOT REACH THE SECONDARY SKILLS, because `parser.js` rejects a
    bonus on a secondary category outright - the comment there reasons that a
    book''s parenthetical percentage applies to related selections only, which
    is true of every class before this one and is not true of a blanket
    penalty. Recorded in the secondary-skills note so a GM can apply it.
  - THIS CLASS NEEDS NO `CORE_SDC_BY_CLASS` ENTRY: `withCorePools` returns early
    for a class stating an `mdc_base`, and this one states 2D6x10+30.
---

# Fallen Cosmo-Knight

**Optional player character or NPC villain. Available as a player character.**

## Lore

A character who has forsaken the cosmo-knights'' code is both pitiable and
fearsome. He loses most of his cosmic power, much of his self-respect and
sometimes his sanity, and he remembers what he had the way a recently blinded
man remembers color. Many sink into bitterness and despair. Those who do not
kill themselves or vanish into hermitage have to decide what to do with the rest
of a very long life, and a great many turn into the exact opposite of what they
were.

Fallen knights are dangerous: supernaturally strong and durable still, often
endowed with magic or psionics afterwards, and knowing more about cosmo-knights
and their weaknesses than anyone alive. Some become psychotic and take pleasure
in inflicting pain and chaos, especially on knights who did not fall. Others
become savage vigilantes who kill criminals - or anyone they suspect of being
one - without much concern for law or bystanders. Others still are simply
self-serving, chasing wealth and new power. And some try to earn back what they
lost, or at least their self-respect, by going on serving the cause of light and
making amends; a few of those are more heroic and more noble than they ever were
as cosmo-knights.

## The road back

Regaining the power is near impossible. Most give up after a few decades. Of
those who keep trying, roughly one in a thousand succeeds, and in all of
recorded history only a dozen or so have redeemed themselves to the Cosmic
Forge''s satisfaction and gone on to become legends. Many die heroically in the
attempt without ever getting there. Some regain their powers only for as long as
it takes to spend them - confronted with impossible odds, restored just long
enough to sacrifice themselves for a good cause or to buy other lives with their
own.

## Playing one

A fallen knight player character starts at first, second or third level, which
means he was a beginner cosmo-knight who lost his powers early. The player
should say why - the GM can help - and what the character wants now, whether
that is good, selfish, vengeful or evil. He can be a tragic hero, a dedicated
champion of good, a self-serving miscreant, a bitter and angry vigilante, or
something else entirely, and the background makes a serviceable springboard for
adventures and whole campaigns.

## GM Notes

- **NPC fallen knights are typically 5th to 8th level.** A character who falls
  during play loses all experience points above what his current level needs
  and goes on from there. The book says level improvement then continues on a
  Fallen Knight Experience Table, and there is no such table in the book -
  printed 183 gives the pair a single ladder, headed Cosmo-Knight, which is the
  one stored here.
- **Apply -20% to secondary skills.** The sheet cannot carry it; the class''s
  O.C.C. and related skills already have it.
- **The cosmic weapon is not granted.** A fallen knight has one only if the
  character forged one before the fall. It keeps its 1D4x10 M.D. and its return
  flight, at half throwing range and with no bought power.
- **Magic or psionics is a choice made after the fall**, at first level, using
  the ley line walker''s or the mind melter''s progression for spells or powers
  only - none of those classes'' special abilities.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'fallen-cosmo-knight');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'fallen-cosmo-knight';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-fallen-cosmo-knight-class.sql');
