-- The NGR Cyborg Soldier O.C.C., Rifts World Book 5: Triax and the NGR p.161.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-ngr-cyborg-soldier-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'ngr-cyborg-soldier', 'NGR Cyborg Soldier', 'rifts', '---
id: ngr-cyborg-soldier
occ_group: men-of-arms
name: NGR Cyborg Soldier
system: rifts
source_book: Rifts World Book 5: Triax and the NGR p.161
category: occ
attribute_requirements: { ME: 15 }
starting_money: "1d6x1000"
skills:
  occ_skills:
    - { name: "Mathematics: Basic", base: 55, per_level: 5, note: "+10%" }
    - { name: "Literacy: Euro", base: 40, per_level: 5, note: "+10%" }
    - { name: "Language: Euro", base: 70, per_level: 5, note: "+20%" }
    - { name: "Radio: Basic", base: 55, per_level: 5, note: "+10%" }
    - { name: "Computer Operation", base: 50, per_level: 5, note: "+10%" }
    - { name: "Military: Tanks & APCs", base: 56, per_level: 4, note: "+20%" }
    - { name: "Wilderness Survival", base: 40, per_level: 5, note: "+10%" }
    - { name: "Climbing", base: 50, per_level: 5, note: "+10%" }
    - { name: "Swimming", base: 60, per_level: 5, note: "+10%" }
    - { name: "SCUBA", base: 60, per_level: 5, note: "+10%" }
    - { name: "W.P. Automatic and Semi-automatic Rifles", base: 0, per_level: 0, note: "The book prints W.P. Automatic Rifle." }
    - { name: "W.P. Energy Rifle", base: 0, per_level: 0 }
    - { name: "W.P. Heavy M.D. Weapons", base: 0, per_level: 0, note: "The book prints W.P. Heavy Energy Weapons; this is the catalog''s row for rail guns and energy cannons." }
    - { name: "Hand to Hand: Basic", base: 0, per_level: 0, note: "May be changed to Expert for one O.C.C. Related skill, or to Martial Arts (or Assassin if evil) for two." }
    - { choose: 1, categories: ["Pilot"], bonus: 20, note: "Pilot skill of choice (+20%)." }
  occ_related_skills:
    count: 5
    categories:
      - { name: "Communications", bonus: 10 }
      - "Domestic"
      - { name: "Medical", only: ["First Aid"], bonus: 10 }
      - { name: "Military", bonus: 10 }
      - { name: "Physical", note: "Any that are still appropriate to a cyborg body." }
      - { name: "Pilot", bonus: 10 }
      - { name: "Pilot Related", bonus: 10 }
      - { name: "Rogue", bonus: 5 }
      - { name: "Technical", bonus: 10 }
      - "Weapon Proficiencies"
      - { name: "Wilderness", bonus: 10 }
    schedule:
      - { level: 4, count: 1 }
      - { level: 8, count: 1 }
      - { level: 12, count: 1 }
  secondary_skills:
    count: 0
    schedule:
      - { level: 2, count: 2 }
      - { level: 5, count: 2 }
      - { level: 8, count: 2 }
      - { level: 13, count: 2 }
equipment_starting:
  - { item_id: "e-clip", qty: 4 }
  - { item_id: "binoculars", qty: 1 }
  - { item_id: "utility-belt", qty: 1 }
  - { item_id: "backpack", qty: 1 }
  - { item_id: "walkie-talkie", qty: 1 }
extraction_notes: |
  - THE CLASS''S OWN BODY IS A VESSEL THIS CATALOG CANNOT HOLD, which is a
    sharper occurrence of BOOK-INGEST-AUDIT.md F3 than the ones recorded so far.
    Printed 161 says a cyborg soldier must be a partial or full conversion
    cyborg and that any of the borg designs in the book''s own cybernetics and
    borg section, printed 99-116, is available as a player character. Those five
    designs are F3 vessels, so the class ships with NO mdc_base: its M.D.C.,
    its P.S. and its speed all live in a chassis the catalog has no row for. A
    character built from this class gets the core S.D.C. rule instead, which is
    a human''s. The GM supplies the chassis from the book.
  - Electrical, Espionage, Mechanical and Science are printed as None and are
    therefore absent from occ_related_skills rather than listed empty.
  - The Physical category carries the book''s own qualifier - any that are still
    appropriate - as a note. It is a judgement the book leaves to the table and
    not something the picker can enforce, since which skills survive depends on
    the chassis.
  - The equipment list stores only what is issued to the character rather than
    to the chassis. Printed 161 issues all the ammunition and equipment
    appropriate to the borg''s own body styling and weapon systems, an energy
    rifle of choice and four grenades of choice; none of those resolves to a
    single catalog row, and the rifle and grenades are choices the book does not
    enumerate. They are in the body.
  - starting_money is the first-level savings the book prints, 1D6x1000. The
    1800 credit monthly salary and the 3500 to 5000 a month for 9th level and
    higher are pay rather than starting coin and are in the body.
  - Skill bases are catalog base plus the printed bonus, already added.
---

## Lore

Triax and the New German Republic embrace cybernetic enhancement where the Coalition States hesitate. Eighteen percent of NGR troops are full conversion borgs, fifteen percent are partial reconstruction, and sixty percent of soldiers carry minor cybernetic implants.

A cyborg soldier must be a partial or full conversion cyborg. Candidates are thoroughly evaluated and prepared for life as a living machine.

Alignment: Any. Any human in good mental health with the spirit to fight can become one.

## The chassis

The class does not carry its own M.D.C. Printed 161 says any of the borg designs in the book''s cybernetics and borg section, printed 99-116, is available as a player character, and those are giant machine stat blocks this catalog does not store. The GM picks the design from the book and supplies its M.D.C., P.S., speed and weapon systems. The special operatives, variants and exceptions the entry mentions use the borg design rules in the Rifts RPG.

## Rank and pay

Standard military, private to general. Salary is 1800 credits a month, rising to 3500 to 5000 for ninth level and higher, with quarters, food, clothing, medical care, maintenance and repairs provided. Quarters are dormitory style, four soldiers to an area.

## GM Notes

Standard issue beyond the stored equipment: all ammunition and equipment appropriate to the borg''s body styling and weapon systems, an energy rifle of choice, and four grenades of choice.

Equipment available upon assignment includes the T-100 Eagle jet pack, a hover vehicle or other transport, additional weapons and equipment, and medium-security access to most military bases. Availability depends on the local commander, supply, location, casualties and combat conditions.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'ngr-cyborg-soldier');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'ngr-cyborg-soldier';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-ngr-cyborg-soldier-class.sql');
