-- The Psi-Goblin R.C.C., Rifts World Book 12: Psyscape p.128-130.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-psi-goblin-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'psi-goblin', 'Psi-Goblin', 'rifts', '---
id: psi-goblin
name: Psi-Goblin
system: rifts
source_book: Rifts World Book 12: Psyscape p.128-130
category: rcc
attribute_dice:
  IQ: "1d6+8"
  ME: "2d6+8"
  MA: "1d6"
  PS: "2d6+12"
  PP: "2d6+12"
  PE: "2d6+12"
  PB: "2d6"
  Spd: "6d6"
mdc_base: "P.E. attribute number + 6d6+10, +1d6 per level of experience"
ppe_base: "3d4x10 + P.E. attribute number x2; does not increase with experience"
horror_factor: 11
xp_table: [0, 1926, 3851, 7451, 14901, 21001, 31001, 41601, 53001, 73001, 103501, 139001, 189001, 239001, 289001]
bonuses:
  combat: { attacks: 1, initiative: 3, strike: 2, disarm: 3, pull_punch: 4, roll: 2 }
  saves:
    horror_factor: 6
    spell_magic: 2
    ritual_magic: 2
    toxins_poisons: 3
    other: [ { label: "vs radiation", bonus: 3 }, { label: "vs pollution", bonus: 3 } ]
skills:
  hand_to_hand: { costs: {} }
  occ_skills:
    - { name: "Language: Gobblely", base: 98, per_level: 0, note: "Speaks Gobblely at 98%." }
    - { name: "Language: Other", base: 98, per_level: 0, note: "Faerie Speak at 98%. The catalog has no Faerie Speak language row." }
    - { choose: 1, from: ["Language: Other"], bonus: 10, note: "One additional language of choice, typically American (+10%)." }
    - { name: "Escape Artist", base: 50, per_level: 5, note: "+20%" }
    - { name: "Interrogation", base: 50, per_level: 5, note: "+20%" }
    - { name: "Intelligence", base: 42, per_level: 4, note: "+10%" }
    - { name: "Streetwise", base: 30, per_level: 4, note: "+10%" }
    - { name: "Land Navigation", base: 46, per_level: 4, note: "Printed as (10%); read as +10%." }
    - { name: "Wilderness Survival", base: 45, per_level: 5, note: "+15%" }
    - { name: "W.P. Paired Weapons", base: 0, per_level: 0 }
    - { name: "W.P. Targeting", base: 0, per_level: 0 }
    - { choose: 1, from: ["W.P. Knife", "W.P. Sword"], note: "W.P. Knife or Sword." }
    - { choose: 1, from: ["W.P. Archery", "W.P. Axe", "W.P. Blunt", "W.P. Chain", "W.P. Forked", "W.P. Knife", "W.P. Lance", "W.P. Pole Arm", "W.P. Shield", "W.P. Spear", "W.P. Staff", "W.P. Sword", "W.P. Whip"], note: "W.P.: one Ancient of choice." }
    - { choose: 1, from: ["W.P. Energy Pistol", "W.P. Energy Rifle", "W.P. Heavy M.D. Weapons"], note: "W.P.: one Energy Weapon of choice." }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "W.P.: one of choice (any)." }
    - { name: "Hand to Hand: Expert", base: 0, per_level: 0, note: "Hand to Hand: Expert (cannot be changed)." }
    - { choose: 4, categories: ["Espionage"], note: "1D4 Espionage skills of choice. Roll 1D4 and take that many; four is the most the roll allows." }
    - { choose: 4, categories: ["Rogue"], note: "1D4 Rogue skills of choice. Roll 1D4 and take that many; four is the most the roll allows." }
    - { choose: 4, categories: ["Technical", "Wilderness"], note: "1D4 Technical or Wilderness skills of choice. Roll 1D4 and take that many; four is the most the roll allows." }
psionics:
  type: "major"
  isp_base: "1d6x10 + M.E. attribute number x2, +1d6 per level of experience"
  powers: ["Detect Psionics", "Death Trance", "See The Invisible", "Sense Magic", "Sense Evil", "Mind Block", "Ectoplasm"]
  powers_starting: 2
  categories_allowed: ["Physical"]
magic:
  type: "spell"
  spells: ["Shadow Meld", "Armor of Ithan", "Fool''s Gold", "Repel Animals", "Energy Bolt", "Forcebonds", "Frostblade"]
  spells_starting: 0
trackable_resources:
  - { key: shadow_meld, label: "Shadow Meld", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
  - { key: armor_of_ithan, label: "Armor of Ithan", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
  - { key: fools_gold, label: "Fool''s Gold", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
  - { key: repel_animals, label: "Repel Animals", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
  - { key: energy_bolt, label: "Energy Bolt", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
  - { key: forcebonds, label: "Force Bonds", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
  - { key: frostblade, label: "Frostblade", max: 3, reset_on: day, note: "Innate; three times per 24 hours." }
natural_abilities:
  - { name: "Supernatural P.S. and P.E.", description: "On Rifts Earth (and Wormwood). Typically 3D6 S.D.C. restrained punch, 1D6 M.D. full strength punch, 2D6 M.D. power punch." }
  - { name: "Claws and Bite", description: "Claws add 1D6 M.D. to punching attacks; a bite does 1D6 M.D. Where magic is low these become Hit Point/S.D.C. damage." }
  - { name: "Mega-Damage Creature", description: "A mega-damage being on Rifts Earth. On its native world and other low-magic places it is a Hit Point and S.D.C. being instead: Hit Points P.E. + 6D6 (+1D6 per level), S.D.C. 1D4x10." }
  - { name: "Double-Jointed", description: "Reflected in the Escape Artist bonus." }
  - { name: "Nightvision", description: "1000 feet (305 m)." }
  - { name: "Swim", description: "55%." }
  - { name: "Climb", description: "80%/70%." }
  - { name: "Bio-Regeneration", description: "Regenerates 2D6 points per hour. Regrows fingers, ears and similar within 72 hours; a hand, arm or leg in 1D4 weeks." }
  - { name: "Impervious to Disease", description: "" }
special_abilities:
  - name: "Innate Magic"
    description: "Can perform each of Shadow Meld, Armor of Ithan, Fool''s Gold, Repel Animals, Energy Bolt, Force Bonds and Frostblade three times per 24 hour period. The book names no P.P.E. cost for these uses."
equipment_starting: []
restrictions:
  - "G.M. PERMISSION: the book presents the Psi-Goblin as an NPC villain and optional player character. A player Psi-Goblin is likely unprincipled or anarchist; scrupulous, principled or aberrant ones are a rarity."
  - "Alignment: any, but most are anarchist (35%), miscreant (32%) or diabolic (30%)."
  - "Hand to Hand: Expert cannot be changed."
  - "No secondary skills. The book names no O.C.C. for the race."
  - "Not sophisticated enough to use power armor, pilot robots or most combat vehicles; likes hover cycles, motorcycles and jet packs."
  - "Size: 4 to 5 feet (1.2 to 1.5 m) tall; 90 to 120 lbs (40.8 to 54 kg). Life span 1000+ Earth years."
extraction_notes: |
  G.M. PERMISSION: the stat block is headed "Psi-Goblin NPC Villain & Optional
  Player Character" (printed 129) and carries a Player Note, so it is imported
  as playable with a G.M.-permission note in restrictions and ## GM Notes.
  Production''s `goblin` is the Palladium Fantasy goblin, a different race; this
  is a new id.

  Read from the cache (printed 128-130 = cache p129-p131) and checked against a
  150 dpi render of printed 129 (pymupdf d[129]). The render confirms I.S.P.
  1D6x10 (cache "!D6xlO"), P.P.E. 3D4x10, S.D.C. 1D4x10, M.D.C. P.E. + 6D6+10,
  and "Land Navigation (10%)" printed without a plus.

  1. XP_TABLE is the ladder the batch brief supplies.
  2. POOLS: mdc_base only, because on Rifts Earth it is a mega-damage creature.
     The low-magic Hit Points (P.E. + 6D6, +1D6/level) and S.D.C. (1D4x10) are
     prose in the Mega-Damage Creature natural ability. No men_of_arms line is
     needed since mdc_base is stated. P.P.E. is from numbered ability 4 (the
     stat block says "See above") and does not increase with level.
  3. PSIONICS from numbered ability 2: Major, seven named powers (See the
     Invisible is the catalog''s "See The Invisible") plus two Physical of
     choice. "Needs a 12 or higher to save vs psionic attack" is the standard
     major-psychic save, so no save modifier is stored.
  4. MAGIC from numbered ability 1: the seven spells are granted by name in the
     magic block with spells_starting 0, and the three-per-24-hours limit is a
     special ability plus one trackable resource per spell. The book says Force
     Bonds and Frostblade are from Federation of Magic; the catalog''s rows are
     "Forcebonds" (RUE p.214) and "Frostblade" (Book of Magic p.112), the
     general-invocation rows of those names. The element-prefixed Frostblade,
     Fool''s Gold and Repel Animals rows were not used.
  5. BONUSES: "save vs magic +2" is stored as both spell_magic and
     ritual_magic 2. "+3 to save vs poison, radiation and pollution" is
     toxins_poisons 3 plus two saves.other entries. Impervious to disease is a
     natural ability (no number to store). "+2 to roll with impact or fall" is
     combat.roll 2. "+1 hand to hand attacks" is combat.attacks 1 on top of
     Hand to Hand: Expert.
  6. SKILLS: bases are catalog base plus printed bonus. Faerie Speak has no
     catalog language row, so it is a fixed Language: Other at 98% with a
     note (godling / demon-hound-rider precedent). The extra language (typically
     American, +10%) is a Language: Other pick. "W.P. Energy Weapon of choice"
     is a pick of Energy Pistol, Energy Rifle or Heavy M.D. Weapons. The 1D4
     Espionage / Rogue / Technical-or-Wilderness selections are stored at count
     4 with a roll-1D4 note (leopard-men / lanotaur precedent). Hand to Hand:
     Expert "cannot be changed" is hand_to_hand costs {}.
  7. NO related or secondary skills (the book says no secondary skills), no
     O.C.C. named, no equipment list and no money printed: equipment_starting is
     empty and there is no starting_money.
  8. The Psionic Powers / I.S.P. / R.C.C. Bonuses lines at the top of printed
     128 belong to the preceding Power Leech entry, not to the Psi-Goblin.
  9. Not stored: average level of experience (NPCs 3-7, player characters
     start at level one or two), habitat, allies, enemies and the weapons
     preferences beyond the vehicle line in restrictions.
---

# Psi-Goblin

## Lore

Psi-Goblins are small, savage D-bees from a magic-rich world much like Earth,
where they prey on Faerie Folk; many are thought to have been brought to Rifts
Earth by Lord Alistair Dunscon, who fields an army of them. Others roam the
Magic Zone as mercenaries, bandits, spies and assassins, and most people assume
every Psi-Goblin serves evil. They are jealous, greedy and cruel, resent anyone
more attractive, wealthy or powerful than themselves, and are feared as
torturers and interrogators. As creatures of magic they have more innate magic
than other goblins, along with psionics, and on Rifts Earth they become
mega-damage beings.

## GM Notes

G.M. permission required: the book presents the Psi-Goblin as an NPC villain
and an optional player character. One allowed as a player character is likely
unprincipled or anarchist.

They usually gather in groups of 6-24 ruled by one strong leader or a few
elders, and sometimes ally with Black Faeries, demons, Necromancers, high-level
evil mages, Mind Bleeders and evil psychics. They are found mainly in the Magic
Zone, with a tribe of about sixty in the ruins of Old Chicago and around a
hundred in the Pecos Empire. They hold grudges for life against anyone who
defeats or humiliates them, and they covet magic items and heavy weapons.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'psi-goblin');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'psi-goblin';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-psi-goblin-class.sql');
