-- Phase 3 of the NPC / bestiary work, third book: every species the Palladium
-- Fantasy RPG Main Book stats - the demons and deevils at the back of the book,
-- and the beings its magic makes (the monster insect, the mummy, zombies and the
-- golem) - rows for creatures (migration 074) and their attacks in stat_attacks
-- (owner_kind 'creature').
--
-- One-off data script, run once per environment. NOT a migration.
--
-- NOT HERE: the Player Races (printed 288-312), which are R.C.C.s for the class
-- pipeline; the demon and deevil LORDS, which are notable_npcs and whose own
-- pages here only point to Dragons and Gods; and the True Giants (printed
-- 333-335), which this book describes but does not stat.
--
-- AN S.D.C. BOOK: a row's pools are hit points, S.D.C. and A.R.; any Rifts Earth
-- M.D.C. is in pools_note.
--
-- EXTRACTED by six book-extract-workers, each given the NAMES of its species
-- rather than a page slice - the two earlier books lost blocks at slice edges -
-- and every number read off a 200 dpi render rather than the OCR cache, which
-- carries the digit cipher. A census of every Alignment line in the section found
-- four species no list had named (Gallu, Deevils, Fenry, Horrors); the sixth
-- worker read those. RECONCILED by book-reconcile against the renders, row by
-- row; its corrections are applied. Every row passes creatureFormulaGaps, the
-- grammar the endpoint rolls with. description and natural_abilities are short
-- paraphrases - no sentence is the book's.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-creatures-palladium-fantasy.sql
--
-- BY CATEGORY:
--   animal (1): Monster Insect
--   undead (2): The Mummy, Zombies
--   construct (1): Golem
--   demon (20): Gargoylites, Gurgoyles, Gargoyles, Gargoyle Mage, Gargoyle Lords, Alu
--     Demon Hound, Aquatics, Banshee, Couril, Labassu, Lasae, Shedim, Mares, Baal-Rog,
--     Demon Locusts, Jinn, Magots, Night Owls, Raksasha, Gallu (The Demon Bull)
--   deevil (12): Devilkins, Dire Harpies, Fiends, Gorgons, Imps, Arch Fiends, Wraiths,
--     Serpents, Beasts, Deevils, Fenry (Demon Wolf), Horrors

INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'monster-insect', 'Monster Insect', 'animal', 'palladium-fantasy', 0, 'N/A', NULL, '3D4x10', NULL, NULL, NULL, NULL, 'Book gives a single combined Hit Points/S.D.C. figure (3D4x10), no separate pools.', 16, 13, '{"attacks":3,"initiative":2,"strike":3,"parry":1,"dodge":3}', 'A.R. 16 if ant or beetle, 12 for all others (main figure used above is the ant/beetle A.R.).', 'Climb 90/85%, swim 80%, land navigation 80%, track humanoids and animals 80%; runs or flies at speed 58 (40 mph/64 km; flying bugs run at half that speed).', 'A mage-summoned insect enlarged to dog or horse size; aggressive, obeys the simple commands of its creator, fights to the death, and moves quickly on the ground or in flight.', NULL, NULL, 'Dog- or horse-sized', NULL, NULL, NULL, NULL, NULL, NULL, 'An ordinary insect magically enlarged to the size of a dog or horse, ferocious and obedient only to the mage who created it.', 'Palladium Fantasy RPG Main Book p.207');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'mummy', 'The Mummy', 'undead', 'palladium-fantasy', 0, 'N/A', '{"IQ":"4","PS":"20","PP":"10","PE":"18","PB":"2","Spd":"7"}', '70', NULL, NULL, NULL, NULL, 'Book gives a single combined Hit Points/S.D.C. of the Corpse: 70; only fire, explosives and magic can harm it. Linen wrappings have their own S.D.C. 50 and A.R. 10; if wrappings are destroyed, normal fire does double and magic fire quadruple damage to the corpse.', NULL, 10, '{"attacks":3,"strike":1,"parry":1}', '+1 to strike and parry; no dodge or initiative bonus. Fearless: impervious to horror factor, phobias, fear magic and most psionics (including empathy, telepathy, bio-manipulation). Afraid only of fire: HF 7 for a small fire/torch, 13 for a man-sized fire, 16 for larger fires; a torch used as a flaming club does 2D4 damage, magic fire double.', 'None, other than magically understands all languages.', 'A reanimated, linen-wrapped corpse; mindless, cannot speak or read, follows only simple commands, and is nearly immune to physical attacks, mind-affecting magic, and psionics; vulnerable chiefly to fire, explosives, and magic weapons.', NULL, NULL, NULL, NULL, 'Exists until destroyed', NULL, NULL, NULL, NULL, 'An animated linen-wrapped corpse created by necromantic ritual; mindless, fearless, and resistant to nearly everything except fire, explosives, and magic weapons.', 'Palladium Fantasy RPG Main Book p.211');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'zombies', 'Zombies', 'undead', 'palladium-fantasy', 0, 'N/A', '{"IQ":"7","PS":"20","PP":"13","PE":"18","PB":"2","Spd":"10"}', '150', NULL, NULL, NULL, NULL, 'Book gives a single combined Hit Points/S.D.C. of 150; fully regrows within 48 hours - only an exorcism, or burying the head apart from the body, stops it.', NULL, 12, '{"attacks":3,"strike":2,"parry":2,"dodge":2}', '+2 to strike, parry and dodge; no initiative bonus. Fearless: impervious to horror factor, phobias, fear magic and most psionics (including empathy, telepathy, bio-manipulation). Afraid only of fire: HF 6 for a small fire/torch, 12 for a man-sized fire, 15 for larger fires; a torch used as a flaming club does 1D6 damage, magic fire double.', 'Magically understands and reads all languages 96%, knows basic math 80%, land navigation 70%, track humanoids 50%, climb 50/45%.', 'A reanimated, more intelligent corpse that can speak, read simple signs, and perform tasks; supernatural strength and endurance, nightvision, immune to normal weapons, poison and disease, and regenerates fully within 48 hours unless beheaded and buried apart.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A more capable undead corpse than the mummy: it can speak, follow orders, and labor for its creator, but regenerates completely unless beheaded and buried apart.', 'Palladium Fantasy RPG Main Book p.213');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'golem', 'Golem', 'construct', 'palladium-fantasy', 0, 'N/A', '{"IQ":"6","PS":"25","PP":"15","PE":"25","PB":"3","Spd":"8"}', '250', NULL, NULL, NULL, NULL, 'One shared block for both kinds: figures above are for a STONE golem. An IRON golem instead has P.S. 30, A.R. 17, Horror Factor 18, Hit Points/S.D.C. 400 (vs stone: A.R. 14, HF 16, 250). Both regenerate fully 24 hours after destruction unless the heart is removed; a stone golem otherwise regenerates 10 S.D.C. per hour, 16 if iron. Single combined Hit Points/S.D.C. figure, no separate pools. Cannot wear body armor.', 14, 16, '{"attacks":4,"strike":2,"parry":2}', '+2 to strike and parry; no initiative or dodge bonus. Fearless: only magic weapons and supernatural P.S. (gods, demons, etc.) inflict full damage; magic energy, fire and cold attacks do half damage, as do normal weapons and punches.', 'Magically understands all languages 96%, knows basic math 80%, land navigation 60%, track humanoids 30%, climb 40/35%.', 'A magically animated clay-and-stone or iron giant, nearly indestructible, mindless and obedient only to its creator; needs no food or sleep, resists poison and most psionics, and regenerates unless its heart is removed.', NULL, NULL, 'No smaller than 10 feet (3 m) and no taller than 20 feet (6 m)', NULL, 'Regenerates 24 hours after destruction unless its heart is removed', NULL, NULL, NULL, NULL, 'A humanoid giant of clay and stone or iron, animated by ritual magic to serve its creator as a nearly unstoppable guardian or laborer.', 'Palladium Fantasy RPG Main Book p.214');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gargoylites', 'Gargoylites', 'demon', 'palladium-fantasy', 0, 'Typically anarchist or evil; never good', '{"IQ":"1D6+8","ME":"3D6+1","MA":"3D6+2","PS":"16+1D6","PP":"16+1D6","PE":"16+2D6","PB":"2D6","Spd":"3D6"}', '5D6+PE', '6D6', NULL, '4D6', '6D6', 'Spd is running 3D6; flying speed is 1D4x10+10. ISP powers: meditation, mind block, presence sense, sense magic, see aura, object read, telepathy, resist hunger, resist fatigue, resist thirst; equal to a 4th level psychic, does not increase with experience.', 13, 10, '{"attacks":4,"initiative":2,"strike":1,"parry":1,"dodge":3}', '+10 to save vs horror factor, +3 on all saving throws (in addition to attribute bonuses); dodge: +3 (+4 while in flight); damage: Claws 1D4 (plus supernatural P.S. bonus); punches/kicks/bite per Supernatural P.S. chart', 'Equivalent O.C.C.: all O.C.C. skills of the Thief, but only select three O.C.C. related skills (usually rogue) and ignore hand to hand skill; uses the Thief experience table. Average Level of Experience: 1D4+1.', 'Nightvision 120 ft, keen hawk-like vision, exceptional hearing, leap 12 ft, fly, glide, bio-regenerate 2D6/round. Can turn to living stone 3x/day: +100 S.D.C., +1D4 melee damage, half-speed flight, lasts 6 hours.', 'None; only Gargoyle Mages can perform magic', 'I.S.P. 6D6: meditation, mind block, presence sense, sense magic, see aura, object read, telepathy, resist hunger, resist fatigue, resist thirst; equal to 4th level psychic, does not increase with experience', '3 feet (0.9 m) tall', '100 pounds (45 kg)', NULL, NULL, 'greater demons; demon lords; gods; Summoners', NULL, NULL, 'A stunted gargoyle offshoot, mischievous rather than violent, greedy for gems, and used as spies by more powerful demonic beings despite weak, short-range wings.', 'Palladium Fantasy RPG Main Book p.313-314');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gurgoyles', 'Gurgoyles', 'demon', 'palladium-fantasy', 0, 'Typically evil; anarchist and good aligned gurgoyles incredibly rare and tormented, banished or slain', '{"IQ":"2D6","ME":"3D6","MA":"2D6","PS":"24+2D6","PP":"18+1D6","PE":"18+1D6","PB":"2D6","Spd":"6D6+10"}', '1D6x10+PE', '1D6x10', NULL, '2D6', '1D4x10', 'Cannot fly. I.S.P. powers limited to meditation, mind block, presence sense, telepathy, resist hunger, resist fatigue, resist thirst; advances with experience level; considered minor psychic.', 13, 14, '{"attacks":4,"initiative":2,"strike":1,"parry":2,"dodge":2,"pull":3,"roll":3}', '+10 to save vs horror factor, +1 to save against magic and psionic attacks; pull: +3 pull punch; roll: +3 roll with impact; damage: Claws 1D6 each, bite 1D4; tail strike same as punch (plus supernatural P.S. bonus)', 'Equivalent O.C.C.: all O.C.C. skills of the Mercenary Warrior, but only select three O.C.C. related skills and ignore hand to hand skill; uses the Ranger experience table. Average Level of Experience: 1D4.', 'Nightvision 220 ft, see the invisible, keen hawk-like vision, exceptional hearing, leap 40 ft, bio-regenerate 2D6 S.D.C. or hit points once per melee round.', 'None; only Gargoyle Mages can perform magic', 'I.S.P. 1D4x10, limited to meditation, mind block, presence sense, telepathy, resist hunger, resist fatigue, resist thirst; advances with experience; minor psychic', '8 to 10 feet (2.4 to 3 m) tall', '900 pounds (408 kg)', NULL, NULL, 'gargoyles; gargoyle lords', NULL, NULL, 'Wingless gargoyle cousins, numerous and dangerous ground fighters armed with spears and blades, organized under gargoyle lords alongside true gargoyles.', 'Palladium Fantasy RPG Main Book p.314');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gargoyles', 'Gargoyles', 'demon', 'palladium-fantasy', 0, 'Typically evil or anarchist; good aligned gargoyles incredibly rare and are tormented, banished or slain', '{"IQ":"2D6","ME":"3D6","MA":"2D6","PS":"24+2D6","PP":"18+2D6","PE":"18+2D6","PB":"2D6","Spd":"10+6D6"}', '1D6x10+PE', '2D4x10', NULL, '3D6', '1D4x10', 'Flying speed is 2D4x10+10. Not immortal; live 600-1000 years, reptilian, hatched from eggs in guarded hatcheries in Hades. I.S.P. advances with experience level.', 14, 16, '{"attacks":5,"initiative":2,"strike":1,"parry":2,"dodge":2,"pull":2,"roll":2}', '+1 to save vs psionic attack, +10 to save vs horror factor; dodge: +2 (+4 while flying); pull: +2 pull punch; roll: +2 roll with impact/fall; damage: Claws 1D6 each, bite 1D4; tail strike same as punch (plus supernatural P.S. bonus)', 'Equivalent O.C.C.: all O.C.C. skills of the Soldier, but only select three O.C.C. related skills and ignore hand to hand skill; uses the Ranger experience table. Average Level of Experience: 1D4+1.', 'Fly, glide, nightvision 220 ft, see the invisible, leap 30 ft, bio-regenerate 2D6 S.D.C./hit points every melee round.', 'None; only the Gargoyle Mage can perform magic', 'I.S.P. 1D4x10, limited to meditation, mind block, presence sense, telepathy, resist hunger, resist fatigue, resist thirst; advances with experience level', '10-20 feet (3-6 m) tall; 17 feet (5.1 m) average', '1400 pounds (630 kg) average', '600 to 1000 years', 'Own continent in the dimension of Hades', 'demons; devils; gods; alien intelligences; kobolds; orcs; goblins; hob-goblins (worshippers)', 'humans; elves; dwarves; Wolfen', NULL, 'Winged reptilian demons that hatch from guarded eggs, prized for brute strength, feared in the Palladium World, and easily bought by power or treasure.', 'Palladium Fantasy RPG Main Book p.313-314');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gargoyle-mage', 'Gargoyle Mage', 'demon', 'palladium-fantasy', 0, 'Any evil; never good', '{"IQ":"2D6+6","ME":"3D6+3","MA":"3D6","PS":"18+2D6","PP":"18+2D6","PE":"18+2D6","PB":"2D6","Spd":"5D6"}', '1D4x10+40', '2D4x10', NULL, '3D6x10', '1D6x10', 'Flying speed is 2D4x10+10. Only about 1 in 15,000 gargoyles is a mage; looks like a typical gargoyle, either sex; often advisor and second-in-command of gargoyle clans. I.S.P. advances with experience level.', 14, 16, '{"attacks":4,"initiative":3,"strike":1,"parry":2,"dodge":2}', '+4 to save vs magic, +3 on all other saving throws, +12 to save vs horror factor; dodge: +2 (+4 while flying); damage: Claws 1D6 each, bite 1D4; tail strike same as punch; or by magic (plus supernatural P.S. bonus)', 'Equivalent O.C.C.: all O.C.C. skills of the Earth Warlock, but only select three O.C.C. related skills and ignore hand to hand skill; uses the Warlock O.C.C. experience table. Average Level of Experience: 1D4+2 Warlock, limited per magic abilities.', 'Fly, glide, nightvision 220 ft, see the invisible, turn invisible at will, teleport self 90%+1%/level (2400 ft, 3x daily), dimensional teleport 50%+2%/level, bio-regenerate 4D6/round.', '3D6x10 P.P.E. plus 1D6 per level; possesses all level 1-3 earth elemental spells at proficiency of a 4th level warlock (static); speaks to elemental beings; 80% chance of seeing invisible elementals; senses elementals within 1000 ft', 'I.S.P. 1D6x10: meditation, mind block, presence sense, sense evil, sense magic, detect psionics, healing touch, exorcism, telepathy, resist hunger, resist fatigue, resist thirst; advances with experience level', '15-20 feet (4.6 to 6 m) tall; 18 feet (5.4 m) average', '1500 pounds (457 kg) average', NULL, NULL, 'gargoyle lords', NULL, NULL, 'A rare gargoyle caste born with elemental magic, serving as advisors and seconds-in-command to gargoyle lords, otherwise identical in appearance to common gargoyles.', 'Palladium Fantasy RPG Main Book p.314-315');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gargoyle-lords', 'Gargoyle Lords', 'demon', 'palladium-fantasy', 0, 'Any evil, occasionally anarchist; never good', '{"IQ":"2D6+5","ME":"3D6+2","MA":"2D6+3","PS":"24+2D6","PP":"18+2D6","PE":"18+2D6","PB":"2D6+1","Spd":"5D6"}', '1D6x10+40', '3D4x10', NULL, '6D6', '1D6x10', 'Flying speed printed as 204x10+10 - likely a printing error for 2D4x10+10, matching the pattern used by the adjacent Gargoyle and Gargoyle Mage entries; not usable as printed. One in 3000 gargoyles is a lord; organizes and leads gargoyles and gurgoyles, either sex. I.S.P. advances with experience level.', 14, 16, '{"attacks":6,"initiative":3,"strike":2,"parry":2,"dodge":2,"pull":3,"roll":2}', '+3 on all saving throws, +10 to save vs horror factor; dodge: +2 (+6 while flying); pull: +3 pull punch; roll: +2 roll with impact/fall; damage: Claws 2D4 each, bite 1D6; tail strike same as punch (plus supernatural P.S. bonus)', 'Equivalent O.C.C.: all O.C.C. skills of the Soldier or Assassin, but only select five O.C.C. related skills and ignore hand to hand skill; uses the Assassin experience table in either case. Average Level of Experience: 1D4+4.', 'Fly, glide, nightvision 220 ft, see the invisible, bio-regenerate 4D6/round. Turn to living stone 3x/day: +200 S.D.C., +1D6 melee damage, half-speed flight, lasts 6 hours.; turns invisible at will; teleports self 92% +1% per level (2400 ft, twice a day); dimensional teleport 54% +2% per level', NULL, 'I.S.P. 1D6x10, limited to meditation, mind block, presence sense, telepathy, resist hunger, resist fatigue, resist thirst; advances with experience level', '15-20 feet (4.6 to 6 m) tall; 18 feet (5.4 m) average', '2000 pounds (900 kg) average', NULL, NULL, NULL, NULL, NULL, 'Royal-blooded gargoyle rulers, one in three thousand, who command gargoyle and gurgoyle forces with stone-shifting toughness and superior combat prowess.', 'Palladium Fantasy RPG Main Book p.315');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'alu-demon-hound', 'Alu Demon Hound', 'demon', 'palladium-fantasy', 0, 'Most (50%) aberrant, but can be any evil; never good', '{"IQ":"2D6+4","ME":"2D6+6","MA":"2D6","PS":"18+2D6","PP":"16+1D6","PE":"16+1D6","PB":"2D6","Spd":"6D6"}', '6D6+PE', '5D6x2', NULL, '3D4x10', NULL, 'Cannot fly.', 12, 12, '{"attacks":4,"initiative":2,"strike":2,"parry":1,"dodge":1,"pull":6,"roll":3}', '+10 to save vs horror factor, +1 on all saving throws; pull: +6 pull punch; roll: +3 roll with impact; damage: Claws 1D6 each, bite 1D6 (plus supernatural P.S. bonus)', 'Equivalent O.C.C.: all O.C.C. skills of the Assassin, but only select two O.C.C. related rogue or espionage skills; ignore hand to hand skill; uses the Assassin experience table. Average Level of Experience: 1D4+3.', 'Nightvision 300 ft, see the invisible, keen hawk-like vision, exceptional hearing, track by scent 60% (per 100 ft), recognize own kind/known people 20%+2%/level, turn invisible at will, dimensional teleport 20%+1%/level, fire resistant (half damage), knows all languages, bio-regenerate 2D6/round. May wear armor of any type.', NULL, NULL, '12 feet (3.6 m) tall', '1000 pounds (450 kg)', NULL, 'Desert of Taut and rocky, desolate regions in the dimension of Hades', NULL, NULL, NULL, 'Fur-covered, canine-featured demons resembling Wolfen but walking upright, preferring solitude, tracking, and ambush over open combat in Hades wastes.', 'Palladium Fantasy RPG Main Book p.315-316');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'aquatics', 'Aquatics', 'demon', 'palladium-fantasy', 0, '50% diabolic, 40% miscreant, 10% aberrant', '{"IQ":"1D6+4","ME":"3D6","MA":"1D6","PS":"14+2D6","PP":"14+1D6","PE":"14+1D6","PB":"1D6","Spd":"6D6"}', '6D6+PE', '5D6', NULL, '1D4x10', NULL, 'Spd is swimming 6D6; crawling on land is 1D6; cannot fly. S.D.C. is 5D6 for the body, but each of its four tentacles also has 14 S.D.C.; a tentacle reduced to zero is severed. Equivalent Level of Experience: Second.', 10, 12, '{"attacks":4,"initiative":2,"strike":2,"parry":8,"dodge":8,"pull":1}', '+10 to save vs horror factor, +2 on all saving throws; pull: +1 pull punch; damage: Bite 2D4 (plus supernatural P.S. bonus); strangulation does normal supernatural P.S. damage per squeeze', 'Equivalent O.C.C.: Not applicable; simple-minded minion.', 'Nightvision 200 ft, good normal vision, exceptional hearing underwater, track by blood scent underwater only 80% (smells blood up to a mile), travels to any depth, breathes air or water, dimensional teleport 12%+1%/level, knows all languages, regenerates severed limbs in 10 minutes, bio-regenerate 2D6 every 5 minutes.', NULL, 'I.S.P.: M.E. x2, limited to death trance, mind block, resist fatigue, impervious to cold, levitation; advances with experience level; minor psychic', '12 feet (3.6 m) long', NULL, NULL, 'Sea', 'Summoners; greater demons; demon lords; evil gods', NULL, NULL, 'Octopus-fish hybrid sea demons that drown victims and capsize boats, serving as simple-minded aquatic minions with regenerating tentacles and severe fire vulnerability.', 'Palladium Fantasy RPG Main Book p.316');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'banshee', 'Banshee', 'demon', 'palladium-fantasy', 0, 'Miscreant evil only', '{"IQ":"2D6","ME":"1D6","MA":"1D6","PS":"1D6","PP":"3D6","PE":"1D6","PB":"1D6","Spd":"4D6"}', '50', '1D4x10', NULL, '10', '100', 'S.D.C. is vulnerable only to psionics and magic. Natural A.R. is None, ethereal.', NULL, 14, '{"attacks":2}', '+10 to save vs horror factor; Vulnerable to telepathy, empathic transfer, bio-manipulation, astral travelers, exorcism and ectoplasm; magic of exorcism, banishment, constrain being, commune with spirits and summon lesser being affects it; cannot enter magic sanctums or protection circles; attacks per melee: 2 psionic actions per melee round; or 3 hand to hand attacks, but only vs astral travelers or air elementals', 'Equivalent O.C.C.: Not applicable; animal-like predator. Equivalent Level of Experience: Not applicable.', 'Hovers and floats up to 100 ft high, teleports self up to 2000 miles (only to a new feeding site), naturally invisible and cannot become visible, ethereal (passes through solid matter, immune to physical weapons).', NULL, 'I.S.P. 100: clairvoyance, sense magic, empathic transmission (only way it attacks flesh and blood, equal to 5th level strength); natural empathy senses emotion/sickness/death at no I.S.P. cost; natural empathic transmission of sorrow radiates 60 ft, no I.S.P. cost', '6 to 10 ft tall (1.8 to 3 m); weightless spirit being', NULL, NULL, NULL, NULL, NULL, NULL, 'An invisible, ethereal spirit that feeds on psychic energy released at death, warning of doom through mournful wailing and sorrowful empathic broadcasts.', 'Palladium Fantasy RPG Main Book p.316-317');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'couril', 'Couril', 'demon', 'palladium-fantasy', 0, '50% diabolic, 30% miscreant, 20% aberrant; never good', '{"IQ":"1D6+7","ME":"3D6","MA":"2D6","PS":"2D6+6","PP":"2D6+6","PE":"2D6+6","PB":"3D6","Spd":"1D6"}', '3D6+PE', '5D6', NULL, '2D4x10+PE', NULL, 'Flying Spd is 4D6x3 (running Spd used above).', 6, 8, '{"attacks":3,"initiative":2,"strike":2,"parry":1,"dodge":4,"pull":3,"roll":4}', '+8 to save vs horror factor (only after one realizes it is a demon), +1 on all other saving throws.', 'As thief or assassin O.C.C., but only 2 O.C.C. related rogue/espionage skills; no hand to hand skill; uses the Assassin experience table even if a demon thief.; average level of experience 1D4+3', 'Keen hawk-like sight and hearing, minor dimensional teleport, all languages, fast self-healing; casts cloud of slumber, blinding flash, fleet feet, chameleon and ventriloquism; its song forces nearby victims into an exhausting dance.', 'Cloud of slumber, blinding flash, fleet feet, speed of the snail, chameleon, ventriloquism, plus the special Song of the Couril dance effect.', NULL, '1.5 to 2 feet (0.45 to 6 m) tall', '10 lbs (4.5 kg)', NULL, 'Hades (demon dimension)', NULL, NULL, NULL, 'A tiny, dark-skinned faerie-like demon that loves music, flowers and silver, sending scouts in small packs and swarming in larger clans.', 'Palladium Fantasy RPG Main Book p.317');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'labassu', 'Labassu', 'demon', 'palladium-fantasy', 0, '70% diabolic, 20% miscreant, 10% anarchist', '{"IQ":"1D6+4","ME":"2D6+6","MA":"1D6","PS":"N/A","PP":"N/A","PE":"N/A","PB":"N/A","Spd":"N/A"}', '6D6', '6D6x2', NULL, '4D6+PE', 'MEx5', 'Physical attributes (P.S., P.P., P.E., P.B., Spd) are not applicable in its natural ghostly form; it flies at Spd 6D6+10 as a natural ability rather than a Spd score. Equivalent Level of Experience: Not applicable. P.P.E. formula names P.E. as printed even though P.E. itself is N/A.', NULL, 14, '{"attacks":3}', '+12 to save vs horror factor, +2 on all other saving throws. Attacks only if it feels threatened, and only via psionics/empathic transmission, or hand to hand vs astral travelers and air elementals.; Vulnerable to magic, magic weapons, circles and spells, telepathy, empathic transfer, bio-manipulation, astral travelers, exorcism and ectoplasm; banishment, constrain being, commune with spirits and summon lesser being affect it; cannot enter magic sanctums or protection circles', 'Not applicable; treated as an animal-like predator, no O.C.C. skill package.', 'Hovers up to 1000 ft and flies; passes through solid matter; teleports self 88% (2400 ft, four times a day); dimensional teleport 33%; bio-regenerates 3D6 S.D.C./hit points per melee round.', NULL, 'I.S.P.: M.E. x5. Empathy, telepathy, mind block, see the invisible, telekinesis, empathic transfer, electro-kinesis, mind bolt; equal to 4th level strength.', '6 to 10 feet tall; weightless spirit being', 'Weightless (spirit being)', NULL, 'Palladium World and other dimensions; originates from Hades', 'Demon lords; Summoners', NULL, NULL, 'A wandering ghostly demon-spirit with a hideous head trailing mist, that possesses soulless or astrally-absent people to enjoy a physical body again.', 'Palladium Fantasy RPG Main Book p.317-318');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'lasae', 'Lasae', 'demon', 'palladium-fantasy', 0, '65% diabolic, 30% miscreant, 5% aberrant; never good', '{"IQ":"1D6+6","ME":"3D6","MA":"2D6","PS":"2D6+6","PP":"2D6+8","PE":"2D6+6","PB":"1D6","Spd":"2D6+10"}', '3D6+PE', '6D6', NULL, '2D4x10+PE', NULL, 'Cannot fly (Spd is running only).', 10, 10, '{"attacks":4,"initiative":2,"strike":3,"parry":1,"dodge":4,"pull":5,"roll":4}', '+10 to save vs horror factor, +2 on all other saving throws. A natural 20 hits the eyes, genitals or tongue it aims for and does double damage.', 'As thief or assassin O.C.C., no additional skills; no hand to hand skill; uses the Assassin experience table even if a demon thief.; average level of experience 1D4+2', 'Keen hearing and sight, nightvision 60 ft, turns invisible at will, leaps 20 ft, natural prowl 71%, climb 90%/85%, impervious to fire, speaks all languages, dimensional teleport 21% +2% per level, bio-regenerates 2D6 S.D.C./hit points per melee round.', NULL, NULL, '1.5 to 2 feet (0.45 to 6 m) tall', '8 lbs (3.6 kg)', NULL, 'Hades (demon dimension)', 'Summoners; witches; alchemists; greater demons; demon lords; evil gods', NULL, NULL, 'A small insectoid demon covered in sharp barbs, prized by evil spellcasters as a vicious spy, thief or assassin that maims for sport.', 'Palladium Fantasy RPG Main Book p.318-319');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'shedim', 'Shedim', 'demon', 'palladium-fantasy', 0, '40% aberrant, 35% miscreant, 20% diabolic, 5% anarchist', '{"IQ":"1D6+5","ME":"2D6+6","MA":"2D6","PS":"16+2D6","PP":"16+1D6","PE":"16+1D6","PB":"2D6","Spd":"6D6+10"}', '6D6+PE', '2D4x10', NULL, '1D4x10', NULL, 'Cannot fly (Spd is running only).', 12, 14, '{"attacks":5,"initiative":2,"strike":2,"parry":1,"dodge":1,"pull":4,"roll":4}', '+10 to save vs horror factor, +1 on all other saving throws. Prefers its natural claws and agility over weapons.', 'As Soldier O.C.C., no additional skills; no hand to hand skill; uses the Soldier experience table.; average level of experience 1D4+3', 'Hawk-like sight and keen hearing, nightvision 100 ft, tracks by scent 40%, resists fire and cold, leaps 40 ft from a standstill or 80 ft running, gymnastic, teleport 10% +2% per level, dimensional teleport 14% +1% per level, bio-regenerates 3D6 S.D.C./hit points per melee round.', NULL, NULL, '12 feet (3.6 m) tall', '800 lbs (362 kg)', NULL, 'Hades (demon dimension)', 'Summoners; greater demons; demon lords; gods; Abrasax the Insatiable, Lord of the Shedim', NULL, NULL, 'A hawk-headed, clawed, flightless demon bred as relentless shock troops for demon lords, especially their patron Abrasax.', 'Palladium Fantasy RPG Main Book p.319');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'mares', 'Mares', 'demon', 'palladium-fantasy', 0, 'Diabolic or Miscreant only', '{"IQ":"2D6+6","ME":"3D6","MA":"3D6","PS":"20+2D6","PP":"18+1D6","PE":"18+1D6","PB":"1D6","Spd":"3D6"}', '1D6x10+PE', '5D6x2', NULL, '4D4x10', 'MEx8', 'Cannot fly (Spd is running only). Average Level of Experience: Not applicable.', 12, 16, '{"attacks":3,"initiative":1,"strike":1,"parry":1,"dodge":1}', '+2 on all other saving throws, +12 to save vs horror factor. Three hand to hand attacks, or three by psionics, or two by magic (alternatives, not combined).', 'Not applicable; relies on magic, psionics and natural abilities rather than an O.C.C.', 'Night vision, invisibility at will, strong self- and dimensional teleport, all languages, self-healing; extorts villages with fear and threats, using an evil eye and hypnotic suggestion to torment victims.', '4D4x10 P.P.E.; casts befuddle, fear, spoil, sickness, minor curse, love charm, summon and control rodents, escape, and fool''s gold, at a fixed 4th level.', 'I.S.P.: M.E. x8. Meditation, mind block, healing touch, psychic diagnosis, see aura, alter aura, death trance, impervious to cold/fire, telekinetic punch, teleport object, empathic transmission, catatonic strike, cause insanity, hypnotic suggestion, induce nightmares, insert memory; considered a 4th level master psionic.', '10-12 feet (3-3.6 m) tall, often hunchbacked and stooped', '1200 lbs (540 kg)', NULL, 'Palladium World villages; Hades (demon dimension)', 'Lasae or Nasu (sometimes accompany her in pairs)', NULL, NULL, 'A hunchbacked hag-demon that terrorizes villages with extortion, curses and nightmares, and holds grudges for generations against those who defy her.', 'Palladium Fantasy RPG Main Book p.320');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'baal-rog', 'Baal-Rog', 'demon', 'palladium-fantasy', 0, '55% aberrant, 25% miscreant, 15% diabolic, 10% anarchist', '{"IQ":"2D6+8","ME":"2D6+8","MA":"2D6+8","PS":"2D6+28","PP":"2D6+10","PE":"3D6+12","PB":"2D6","Spd":"1D6x10"}', '3D4x10+PE', '2D4x10', NULL, '1D4x100', NULL, 'Flying Spd is 1D6x10+60 (the running Spd is in the attributes).', 14, 14, '{"attacks":6,"initiative":3,"strike":3,"parry":3,"dodge":3,"pull":4,"roll":4}', '+3 on magic saving throws, +12 to save vs horror factor. Six physical attacks per melee or three by magic; favorite weapon is the magic fire whip.', 'From the shared Greater Demons header: Basic/advanced math 92%, literate in Elven 98% plus two other languages, forgery 45%, intelligence 88%, track humans 50%, wilderness survival 70%, land navigation 80%, swim 60%, climb 80%/70%, dance 80%, streetwise 80%, demon & monster lore 80%, faerie lore 60%, W.P. chain, W.P. whip, W.P. sword.', 'Flight, keen darkvision, invisibility (sees and turns invisible), tracks by scent, strong dimensional teleport, fast self-healing, fire immunity, powerful unaided leaping; commands lesser demons and prefers solo missions.', 'P.P.E. 1D4x100; all levels 1-4 fire elemental magic, plus fire whip (level 7), animate & control dead, turn dead, exorcism, remove curse, heal wounds; equal to a 5th level wizard.', NULL, '12 feet tall (from the shared Greater Demons header)', NULL, NULL, 'Hades; also other worlds/dimensions via reconnaissance patrols or renegade lairs', 'Summoners; demon hordes of Hades', NULL, NULL, 'A huge bronze-skinned, bat-winged demon warrior who commands legions or roams alone as a spy, occasionally carving out kingdoms on other worlds.', 'Palladium Fantasy RPG Main Book p.321');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'demon-locusts', 'Demon Locusts', 'demon', 'palladium-fantasy', 0, '30% miscreant, 70% diabolic', '{"IQ":"3D6+10","ME":"3D6+10","MA":"2D6+10","PS":"3D6+30","PP":"3D6+10","PE":"3D6+10","PB":"1D6","Spd":"1D6x10+10"}', '2D4x10', '2D6x10', NULL, '2D4x100+100', 'MEx2', 'Flying Spd is 3D6x10+50 (running Spd used above). Average Level of Experience: 1D4+5. Hit Points formula is printed with no P.E. addend, unlike most other demons here.', 17, 16, '{"attacks":7,"initiative":4,"strike":2,"parry":4,"dodge":4,"pull":1,"roll":4}', '+5 on all saving throws, impervious to horror factor. Seven physical attacks per melee or three by magic.', 'Basic/advanced math 98%, literate in Elven 98% plus four other languages, forgery 85%, intelligence 90%, land navigation 98%, swim 70%, climb 80%/70%, streetwise 90%, demon & monster lore 90%, faerie lore 90%, magic lore.', 'Flight, sharp night vision, sees invisible, turns invisible, tracks by scent, strong dimensional teleport, rapid self-healing, fire immunity, huge unaided leaps.', 'P.P.E. 2D4x100+100; all level-one spell magic plus call lightning, fireball, fire bolt, negate magic, dispel magic barriers, fly as the eagle, animate/control dead, turn dead, remove curse, exorcism, curse phobia, luck curse, spoil, sickness, earthquake, id barrier, sanctum; equal to an 8th level wizard.', 'All sensitive powers; I.S.P.: M.E. x2; 5th level proficiency.', '12 feet long (3.6 m)', '700 lbs (315 kg)', NULL, 'Hades (demon dimension); most hibernate there and are rarely encountered in the world', 'Old Ones (per legend, as their foot soldiers)', 'Humankind; Elves; Gods of Light', NULL, 'A giant human-headed locust with a scorpion tail, the most powerful demon short of a lord, mostly dormant while awaiting apocalypse.', 'Palladium Fantasy RPG Main Book p.322');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'jinn', 'Jinn', 'demon', 'palladium-fantasy', 0, '50% diabolic, 25% miscreant, 5% aberrant, 20% anarchist', '{"IQ":"1D6+8","ME":"2D6+10","MA":"2D6+10","PS":"2D6+30","PP":"1D6+14","PE":"2D6+10","PB":"2D6","Spd":"2D6x10"}', '2D4x10+PE', '1D6x10', NULL, '1D6x100', '1D4x10+30', 'Flying Spd is 2D6x10+100 (running Spd used above). Can grow up to 24 feet tall at will. Level of experience: Not applicable. All attacks, bonuses, abilities and physical S.D.C. are halved during the daytime.', 14, 15, '{"attacks":6,"initiative":2,"strike":4,"parry":3,"dodge":3,"pull":5,"roll":4}', '+4 on all other saving throws, +4 to dodge while in flight; all bonuses halved during the daytime. Six physical attacks per melee or two by magic; prefers magic and magic weapons.', 'Basic math 98%, literate in Elven 98% plus two other languages, streetwise 65%, intelligence 90%, track humans 50%, wilderness survival 70%, land navigation 85%, swim 80%, demon & monster lore 90%, faerie lore 90%, pick locks 90%, pick pockets 70%, palming 70%, concealment 70%, locate secret compartments 65%, gemology 70%, recognize weapon quality 70%, W.P. sword, plus three of choice (4th level).', 'Naturally invisible, shifts to mist or insect form, changes size, flies and floats, fire/cold resistance, strong dimensional teleport, all languages, self-healing; bound by an ancient curse to grant three wishes to its captor.', 'P.P.E. 1D6x100. Black Jinn: earth elemental magic levels 1-8. White Jinn: water elemental levels 1-7. Green Jinn: air elemental levels 1-7. Yellow Jinn: fire elemental levels 1-8. All at 8th level proficiency (4th during the day).', 'I.S.P.: 1D4x10+30. All sensitive and physical psionic powers at 5th level proficiency.', '8 to 24 feet tall; can change size at will', NULL, NULL, 'Palladium World, the elemental plane, and Hades', NULL, NULL, NULL, 'An elemental spirit demon bound by an ancient curse to obey and grant three wishes to whoever captures or aids it, then seeks freedom.', 'Palladium Fantasy RPG Main Book p.323');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'magots', 'Magots', 'demon', 'palladium-fantasy', 0, '80% diabolic, 20% miscreant', '{"IQ":"1D6+2","MA":"1D6+2","ME":"1D6+10","PS":"1D6+40","PP":"1D6+12","PE":"1D6+16","PB":"1D6","Spd":"1D6x10+60"}', '2D4x10', '6D6x2', NULL, '1D6x100', NULL, 'Spd is running only; cannot fly.', 14, 16, '{"attacks":6,"initiative":2,"strike":3,"parry":1,"dodge":4,"roll":2}', '+3 on all saving throws, impervious to horror factor.', 'Track animals 35%, track humans 45%, wilderness survival 90%, land navigation 80%, swim 80%, climb 60%/20%, demon & monster lore 50%, faerie lore 30%.', 'Nightvision 120 ft, sees the invisible, turns to mist at will, teleports 25%, regenerates 6D6/min, immune to fire, knows all languages, leaps 40 ft. Eyes fire beams that petrify (1D6 min) unless victim saves vs magic 13+. Never uses weapons/armor; fights to the death enraged.', NULL, NULL, '20 ft tall (6 m)', '2 tons', NULL, 'Hades', NULL, NULL, NULL, 'Three-legged demon with a huge tentacle-eyed maw; petrifies and devours intruders while roaming Hades in small herds under Mictla command.', 'Palladium Fantasy RPG Main Book p.323-324');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'night-owls', 'Night Owls', 'demon', 'palladium-fantasy', 0, 'Any evil', '{"IQ":"2D6+8","MA":"2D6+8","ME":"2D6+10","PS":"1D6+28","PP":"2D6+8","PE":"2D6+10","PB":"2D6+1","Spd":"6D6"}', '1D6x10+PE', '1D6x10', NULL, '3D6x10', '5D6x10', 'Flying Spd 1D6x10+100.', NULL, 15, '{"attacks":5,"initiative":2,"strike":4,"parry":4,"dodge":5,"roll":4,"pull":4}', '+4 on all saving throws, +10 to save vs horror factor; 5 attacks per melee or 2 by magic.; dodge: +5 while flying', 'Basic math 98%, literate in Dragonese/Elven 98%, intelligence 80%, track humans 80%, wilderness survival 70%, land navigation 80%, prowl 62%, swim 20%, demon & monster lore 90%, faerie lore 80%.', 'Flies, nightvision 300 ft in total darkness, sees/turns invisible, teleports 56%, regenerates 4D6 M.D./minute, resists fire (half dmg), knows all languages. Rarely uses weapons; quiet, observant, treacherous, and loves torture.', 'P.P.E. 3D6x10: chameleon, globe of daylight, ignite fire, fear, repel animals, animate & control dead, turn dead, exorcism, remove curse, luck curse, phobia curse, heal wounds (6th level proficiency).', 'All sensitive and physical psionic powers plus bio-manipulation, hypnotic suggestion, mind bolt, mind block auto-defense, and P.P.E. shield (6th level proficiency).', '4-5 ft tall, 14 ft wingspan', '300 lbs (122 kg)', NULL, 'Hades', 'Evil humanoid sorcerers (as advisor/partner)', NULL, NULL, 'Owl-bodied demon with a bald human head; a solitary Hades hunter who advises evil sorcerers and hoards gold, gems, and magic items.', 'Palladium Fantasy RPG Main Book p.324-325');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'raksasha', 'Raksasha', 'demon', 'palladium-fantasy', 0, '55% aberrant, 20% miscreant, 10% diabolic, 15% anarchist', '{"IQ":"2D6+9","MA":"2D6+9","ME":"2D6+9","PS":"2D6+20","PP":"2D6+9","PE":"3D6+9","PB":"3D6","Spd":"1D6x10"}', '1D6x10+PE', '3D4x10', NULL, '2D4x100', 'MEx10', 'Cannot fly. Average level of experience 1D6+4. I.S.P. is M.E.x10 plus 10 per level of experience (only the M.E.x10 base is captured in the formula).', 10, 14, '{"attacks":6,"initiative":4,"strike":4,"parry":4,"dodge":4,"pull":4,"roll":4}', '+10 to save vs horror factor, +4 on all other saving throws; favors psi-sword and shield or sword-type weapons; occasionally wears armor/uses high-tech weapons; craves raw humanoid flesh.', 'May select the O.C.C. skills of the Wizard (80%) or Scholar (15%); ignores hand to hand skills; uses the Wizard experience table.', 'Nightvision 120 ft, keen sight, sees invisible, turns to mist, teleports self and cargo, resists fire/cold, knows all languages; shape-shifts into any creature 1-10 ft and can perfectly disguise as a specific individual using psionics. Tracks by smell 45%; bio-regenerates 4D6 S.D.C. per minute.', 'P.P.E. 2D4x100: all metamorphosis, protection, and illusionary spells (fools gold, charismatic aura, multiple image, hallucination, anti-magic cloud, protection circles, banish, exorcism, sanctum, sanctuary, etc.) plus 6 more spells of level 1-4; or Diabolism/Summoning instead.', 'All sensitive, healing, and physical psionic powers plus psi-sword, psi-shield, P.P.E. shield, mind block auto-defense, mentally possess others, hypnotic suggestion, and 4 of choice; considered a master psionic.', '6-10 ft tall (can shape-change to as small as 1 ft)', '700 lbs (315 kg)', NULL, 'Hades; infiltrates mortal political arenas', NULL, NULL, NULL, 'Shape-shifting demon with a humanoid body and feline head; disguises itself as specific people to manipulate politics and human affairs.', 'Palladium Fantasy RPG Main Book p.325');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'devilkins', 'Devilkins', 'deevil', 'palladium-fantasy', 0, '50% miscreant, 25% aberrant, 20% diabolic, 5% anarchist', '{"IQ":"2D6+8","MA":"3D6+8","ME":"1D6+12","PS":"2D6+12","PP":"2D6+12","PE":"3D6+6","PB":"4D6+2","Spd":"2D6+10"}', '1D4x10+PE', '6D6', NULL, '3D6x10+40', NULL, 'Average level of experience 1D4+2 (uses the Assassin experience table).', 10, 12, '{"attacks":3,"initiative":1,"strike":2,"parry":2,"dodge":2,"pull":3,"roll":3}', '+2 on all magic saving throws, +6 to save vs horror factor; often uses weapons, armor, devices of man.; damage: as per supernatural P.S.', 'All rogue skills at +10%, sing (+20%), dance (+10%), escape artist (+10%), forgery (+10%), intelligence (+10%), interrogation techniques (+10%), surveillance (+5%), land navigation (+15%), gemology (+5%), brewing (+5%), swim (+5%), climb (+5%), demon & monster lore (+30%), basic math (+10%), W.P. knife, W.P. blunt, two W.P. of choice, literate in Elven and four others (+20%).', 'Nightvision 90 ft, sees invisible, turns to mist, shape-shifts into human or animal form, teleports dimensionally, resists fire/cold, regenerates 2D6/round, knows all languages, leaps 30 ft.', 'P.P.E. 3D6x10+40: all level 1-3 fire elemental magic plus trance, domination, calling, energy disruption, turn dead, luck curse, compulsion, remove curse, cure minor disorders, heal wounds.', NULL, '6 ft tall', '200 lbs (90 kg)', NULL, 'Dyval', NULL, NULL, NULL, 'Pan-like deevil with a goat lower body and small horns; provokes victims into betrayal and violence rather than fighting directly.', 'Palladium Fantasy RPG Main Book p.327');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'dire-harpies', 'Dire Harpies', 'deevil', 'palladium-fantasy', 0, '60% diabolic, 40% miscreant', '{"IQ":"2D6","MA":"1D6","ME":"3D6","PS":"2D6+20","PP":"2D6+10","PE":"2D6+10","PB":"1D6","Spd":"1D6"}', '6D6+PE', '1D4x10', NULL, '1D6x10', NULL, 'Spd shown is running only; flying Spd 2D4x10+15. Average level of experience 1D4 (uses the Assassin experience table).', 12, 13, '{"attacks":4,"initiative":2,"strike":1,"parry":2,"dodge":5,"pull":2,"roll":2}', '+1 on all saving throws, +8 to save vs horror factor.; dodge: +5 while flying', 'Intelligence (+10%), land navigation (+20%), wilderness survival (+20%), track humanoids (+15%), track animals (+15%), military etiquette (+10%), demon & monster lore (+20%), basic math (+15%), climb (+10%).', 'Flies and glides, nightvision 220 ft, sees invisible, regenerates 2D6 S.D.C./hit points every melee round.', NULL, NULL, '18 ft tall', '1400 lbs (630 kg)', NULL, 'Dyval', 'Greater deevils and deevil lords (as their minions)', NULL, NULL, 'Demonic harpy with clawed feet, glowing yellow eyes, and lava-drooling jaws; a cruel, flesh-eating minion of the deevil lords.', 'Palladium Fantasy RPG Main Book p.327-328');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'fiends', 'Fiends', 'deevil', 'palladium-fantasy', 0, '30% aberrant, 30% miscreant, 20% diabolic, 20% anarchist', '{"IQ":"2D6+8","MA":"3D6+8","ME":"1D6+12","PS":"2D6+12","PP":"2D6+12","PE":"3D6+6","PB":"2D6+2","Spd":"2D6+10"}', '6D6+PE', '4D6+10', NULL, '3D4x10', NULL, 'Average level of experience 1D4+1 (uses the Assassin experience table).', 12, 14, '{"attacks":4,"initiative":2,"strike":2,"parry":2,"dodge":2,"pull":3,"roll":3}', '+2 on all magic saving throws, +7 to save vs horror factor; often uses weapons, armor, devices of man.', 'Streetwise (+10%), intelligence (+10%), land navigation (+15%), track humans (+10%), escape artist (+10%), pick locks (+10%), palming (+10%), concealment (+5%), locate secret compartment (+5%), demon & monster lore (+20%), basic math (+20%), prowl (+5%), climb (+10%), two W.P. of choice.', 'Nightvision 90 ft, sees invisible, shape-shifts into human or animal at will, teleports dimensionally, resists fire/cold, regenerates 3D6/round, knows all languages.', 'P.P.E. 3D4x10: all level one spell magic plus chameleon, shadow meld, multiple image, fear, escape, circle of flame, turn dead, animate & control dead, exorcism, heal wounds.', NULL, '15 ft tall', '1000 lbs (450 kg)', NULL, 'Dyval', 'Fellow demons of Dyval; Evil humans (opportunistically)', NULL, NULL, 'Featureless, shadow-black deevil predator with glowing yellow eyes and mouth; feeds on the P.P.E. of murdered victims and delights in torment.', 'Palladium Fantasy RPG Main Book p.328-329');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gorgons', 'Gorgons', 'deevil', 'palladium-fantasy', 0, '80% diabolic, 20% miscreant', '{"IQ":"1D6+2","MA":"1D6+2","ME":"2D6+10","PS":"2D6+20","PP":"2D6+10","PE":"3D6+6","PB":"1D6","Spd":"4D6"}', '6D6+PE', '4D6+20', NULL, '1D6x10+40', NULL, 'Each of the 8+1D6 snakes has 8 hit points (no S.D.C.) and regenerates separately. Average level of experience 1D4 (uses the Assassin experience table).', 10, 16, '{"attacks":8,"initiative":4,"strike":2,"parry":5,"dodge":2,"pull":3,"roll":3}', '+2 on all magic saving throws, +8 to save vs horror factor; often uses weapons, armor, devices of man.', 'Streetwise (+6%), land navigation (+10%), track humans (+5%), palming (+10%), concealment (+10%), recognize and use poison, demon & monster lore (+15%), basic math, prowl, climb, two W.P. of choice.', 'Nightvision 90 ft, sees invisible, cannot be surprised (many-eyed snakes), teleports dimensionally, resists fire/cold, regenerates 3D6/round; snakes regrow in an hour, full body regrows in a day unless beheaded and burnt. Gaze petrifies (save vs magic 14+, range 200 ft).', 'P.P.E. 1D6x10+40: death trance, turn dead, animate & control dead, spoil, stone to flesh, exorcism.', NULL, '12 ft tall', '600 lbs (270 kg)', NULL, 'Dyval', 'Fellow demons of Dyval; Evil humans (opportunistically)', 'Humans; Beautiful people, places, and things', NULL, 'Medusa-like deevil with a snake-haired head; dull-witted and cruel, it petrifies and destroys anything beautiful across the planes.', 'Palladium Fantasy RPG Main Book p.329-330');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'imps', 'Imps', 'deevil', 'palladium-fantasy', 0, '50% anarchist, 30% miscreant, 10% diabolic, 10% aberrant', '{"IQ":"1D6+8","MA":"3D6+8","ME":"2D6+6","PS":"2D6+6","PP":"2D6+6","PE":"3D6+4","PB":"2D6+2","Spd":"2D6+6"}', '4D6+PE', '20', NULL, '2D4x10+PE', NULL, 'Average Level of Experience: 1D4 (use the Thief experience table).', 10, 10, '{"attacks":3,"strike":1,"parry":1,"dodge":3,"pull":2,"roll":4}', 'Supernatural P.S. adds to damage. +2 on all magic saving throws, +4 to save vs horror factor. Often uses weapons/armor/devices of man; covets magic items, gems, gold.; attacks per melee: Three physical per melee or one magic', 'Streetwise +10%, Intelligence +10%, Land Navigation +10%, Escape Artist +10%, Pick Locks +10%, Palming +10%, Concealment +5%, Locate Secret Compartment +5%, Demon and Monster Lore +10%, Basic Math +20%, Brewing +15%, Gemology +20%, Recognize/Use Poison +6%, Prowl +5%, Climb +10%, W.P. Knife and one of choice.', 'Imps see in the dark to 90 ft (27.4 m), spot invisible foes, take only half damage from fire and cold, heal 1D6 S.D.C./hit points each melee round, know every language, and can always fly at Spd 27 (18.5 mph/30 kmph).', 'P.P.E. 2D4x10+P.E. All level one spell magic.', NULL, 'Three feet tall (0.9 m)', '100 pounds (45 kg)', NULL, 'Dyval, the deevil home realm', 'Fellow demons of Dyval; Humans and humanoids of the Palladium World (as treacherous partners)', NULL, NULL, 'A small, pot-bellied Dyval demon that looks deceptively cute; thrives on mischief, theft, overindulgence, and dragging mortals into trouble.', 'Palladium Fantasy RPG Main Book p.330');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'arch-fiends', 'Arch Fiends', 'deevil', 'palladium-fantasy', 0, '35% aberrant, 25% miscreant, 15% diabolic, 25% anarchist', '{"IQ":"2D6+10","MA":"3D6+10","ME":"1D6+14","PS":"2D6+14","PP":"2D6+12","PE":"3D6+10","PB":"2D6+6","Spd":"2D6+20"}', '6D6+PE', '4D6+30', NULL, '3D4x10+40', NULL, 'Average Level of Experience: 1D4+3 (use the Assassin experience table).', 14, 15, '{"attacks":5,"initiative":3,"strike":4,"parry":2,"dodge":2,"pull":5,"roll":3}', 'Supernatural P.S. adds to damage. +2 on all magic saving throws, +10 to save vs horror factor. Often uses weapons, armor, devices of man.; attacks per melee: Five physical per melee or two magic', 'Streetwise +16%, Intelligence +15%, Land Navigation +15%, Track Humans +15%, Escape Artist +15%, Pick Locks +10%, Palming +10%, Concealment +10%, Locate Secret Compartment +5%, Demon and Monster Lore +20%, Basic Math +30%, Prowl +5%, Climb +10%, literate in Elven and two others +20%.', 'Arch Fiends see 90 ft (27.4 m) in the dark, spot invisible foes, shift into human or animal shape at will, and dimension-teleport at 70% base +2% per level. Fire/cold deal half damage; they heal 4D6 S.D.C./hit points per melee round and know every language.', 'P.P.E. 3D4x10+40. All level one spells plus chameleon, shadow meld, multiple image, fear, escape, mystic portal, magic net, circle of flame, fire ball, fiery touch, repel animals, turn dead, animate and control dead, exorcism, banishment, heal wounds.', NULL, '15 feet tall (4.6 m)', '1000 pounds (450 kg)', NULL, 'Dyval, the deevil home realm', 'Fellow demons of Dyval; Evil humans, dragons, demons of Hades, other supernatural beings', NULL, NULL, 'A stronger, craftier variant of the Fiend; a high-ranking Dyval officer who often schemes independently among mortals, dragons, and other demons.', 'Palladium Fantasy RPG Main Book p.331');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'wraiths', 'Wraiths', 'deevil', 'palladium-fantasy', 0, '50% miscreant, 30% diabolic, 20% aberrant', '{"IQ":"3D6+8","MA":"3D6+12","ME":"2D6+12","PS":"3D6+12","PP":"2D6+8","PE":"3D6+6","PB":"4D6+6","Spd":"2D6+10"}', '6D6+PE', '6D6x2', NULL, '1D4x100', 'MEx10', 'Natural A.R.: none, ethereal - no physical armor rating. I.S.P. gains +10 per level of experience beyond the base M.E.x10. Average Level of Experience: 1D4+3 (use the Wizard experience table). Magic: None.', NULL, 15, '{"attacks":3,"initiative":3}', '+2 on all magic saving throws, +12 to save vs horror factor. Ethereal: ordinary physical attacks (weapons, arrows, fire, energy) pass through and do no damage; only magic or magic weapons harm it. Can use weapons via telekinesis/ectoplasm.; attacks per melee: Three, psionic only; damage: Psionic only', 'Streetwise +10%, Intelligence +20%, Interrogation Techniques +20%, Surveillance +30%, Land Navigation +20%, Heraldry +10%, Locate Secret Compartments +20%, Recognize Weapon Quality +10%, Gemology +20%, Demon and Monster Lore +30%, two lore of choice, Basic/Advanced Math +20%, literate in Elven and six others +20%.', 'Wraiths see 100 ft (30.5.4 m) in darkness, spot invisible beings, dimension-teleport at a 70% chance improving 2% each level, and regenerate 2D6 S.D.C./hit points per melee round while knowing every language; being ethereal, physical attacks pass through them harmlessly.', NULL, 'I.S.P. M.E.x10 plus 10 per level of experience. Possesses all sensitive and physical powers, plus detect psionics, mind bolt, telekinesis (super), telekinetic force field, P.P.E. shield, and seven of choice.', '12 feet tall (3.6 m)', NULL, NULL, 'Dyval, the deevil home realm', NULL, NULL, NULL, 'An ethereal, psionics-only Dyval spirit that spies and interrogates for its masters; normal weapons cannot touch it at all.', 'Palladium Fantasy RPG Main Book p.332');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'serpents', 'Serpents', 'deevil', 'palladium-fantasy', 0, '50% miscreant, 25% aberrant, 20% diabolic, 5% anarchist', '{"IQ":"3D6+8","MA":"3D6+12","ME":"2D6+12","PS":"3D6+12","PP":"2D6+8","PE":"3D6+6","PB":"4D6+6","Spd":"2D6+10"}', '1D4x10+PE', '6D6x3', NULL, '1D4x100', NULL, 'Average Level of Experience: 1D4+3 (use the Wizard experience table). Printed as Horror Factor/Awe.', 14, 15, '{"attacks":3,"initiative":1,"strike":2,"parry":2,"dodge":2,"pull":4,"roll":4}', 'Supernatural P.S. adds to damage. +2 on all magic saving throws, +12 to save vs horror factor/awe. Uses people, not toys.; attacks per melee: Three hand to hand per melee or two by magic', 'All rogue skills +20%, Escape Artist +10%, Intelligence +10%, Interrogation Techniques +20%, Surveillance +10%, Land Navigation +20%, Gemology +20%, Swim +20%, Climb +5%, Demon and Monster Lore +30%, Basic/Advanced Math +30%, two lore of choice, literate in Elven and six others +20%.', 'Serpents see 90 ft (27.4 m) in the dark, spot invisible targets, turn to mist or human shape at will, dimension-teleport at 80% rising 2% per level, take half damage from non-magic fire/cold, heal 4D6 S.D.C./hit points each melee round, and know every tongue.', 'P.P.E. 1D4x100. All level 1-4 earth elemental magic plus trance, compulsion, calling, energy disruption, turn dead, minor curse, remove curse, cure minor disorders, heal wounds.', NULL, '20 feet long (6 m)', '1000 pounds (450 kg)', NULL, 'Dyval, the deevil home realm', NULL, NULL, NULL, 'A huge, golden, serpentine Dyval demon that manipulates through blackmail and terror behind the scenes, though it will fight if pressed.', 'Palladium Fantasy RPG Main Book p.332');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'beasts', 'Beasts', 'deevil', 'palladium-fantasy', 0, '50% aberrant, 25% miscreant, 5% diabolic, 20% anarchist', '{"IQ":"2D6+10","MA":"3D6+4","ME":"1D6+14","PS":"5D6+14","PP":"2D6+12","PE":"3D6+12","PB":"2D6+4","Spd":"2D6+20"}', '2D4x10+PE', '4D6+40', NULL, 'PEx9', NULL, 'Running Spd is 2D6+20; flying Spd is 3D4x10. Average Level of Experience: 1D4+3 (use the Knight experience table regardless of which O.C.C. skill set is chosen).', 15, 15, '{"attacks":5,"initiative":2,"strike":4,"parry":2,"dodge":2,"pull":6,"roll":4}', 'Supernatural P.S. adds to damage. +3 on all magic saving throws, +10 to save vs horror factor. Often uses weapons/devices of man; never wears armor except as a disguise when metamorphed as human.; attacks per melee: Five physical per melee or two magic', 'Equivalent to all O.C.C. skills of the Knight or Assassin, but only four O.C.C. related skills are selected and the hand to hand skill is ignored (see combat/bonuses); the Knight experience table is used regardless of which is chosen.', 'Beasts see 120 ft (36.6 m) in darkness, spot invisible foes, shift into humanoid or bull form at will, and dimension-teleport at 70% rising 2% per level. Fire and cold deal half damage; they heal 4D6 S.D.C./hit points each melee round and know every language.', 'P.P.E.: P.E. number x9 (135 minimum). All level 1-3 spells plus domination, multiple image, magic net, circle of flame, fire ball, energy disruption, call lightning, turn dead, animate and control dead, exorcism, banishment, heal wounds.', NULL, '16 feet tall (4.9 m)', '2000 pounds (900 kg)', NULL, 'Dyval, the deevil home realm', NULL, NULL, NULL, 'A towering, ram-horned, goat-legged Dyval demon; the Deevil Lords and Arch Fiends lieutenant, commanding squadrons of lesser deevils.', 'Palladium Fantasy RPG Main Book p.332-333');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'gallu', 'Gallu (The Demon Bull)', 'demon', 'palladium-fantasy', 0, '40% aberrant, 30% miscreant, 22% diabolic, 6% anarchist, 2% unprincipled', '{"IQ":"1D6+8","MA":"1D6+8","ME":"1D6+10","PS":"1D6+30","PP":"1D6+12","PE":"2D6+12","PB":"2D6","Spd":"2D6x10+40"}', '4D6x2', '1D4x10+40', NULL, '3D6x10', NULL, NULL, 15, 13, '{"attacks":6,"initiative":2,"strike":3,"parry":4,"dodge":4,"pull":4,"roll":3}', '+2 on all magic saving throws, in addition to attribute bonuses; sometimes wears armor and uses man-made weapons; favors magic items; attacks per melee: 6 physical per melee, or 2 by magic', 'Equivalent OCC skills (special): basic math 82%, literate in Dragonese/Elven 98% plus two other languages, intelligence 88%, track humans 50%, wilderness survival 70%, land navigation 85%, swim 80%, climb 70%/60%, dance 80%, demon and monster lore 80%, faerie lore 60%, W.P. chain, W.P. axe and two of choice, all W.P.s equal to 6th level proficiency', 'Nightvision 90ft, sees and turns invisible at will, teleports between dimensions (60%+1%/level), resists fire (magic fire half damage), knows all languages, leaps 40ft, and regenerates 2D6 SDC or HP per melee round.', 'PPE 3D6x10; limited spells: blinding flash, cloud of smoke, globe of daylight, thunderclap, fear, repel animals, animate and control dead, turn dead, exorcism, remove curse, luck curse, phobia curse, heal wounds; 5th level proficiency', NULL, '12 to 14 feet tall (3.6 to 4.2 m)', '1000 pounds (450 kg)', NULL, NULL, '1D4+1 gargoyles/gurgoyles, Alu, Shedim, or Ghouls (typical escort)', NULL, NULL, 'A minotaur-like demon with a bull head and legs, human torso, glowing eyes, and harmless smoke-and-fire breath; travels with lesser demon escorts.', 'Palladium Fantasy RPG Main Book p.322');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'deevils', 'Deevils', 'deevil', 'palladium-fantasy', 0, '65% miscreant, 20% aberrant, 10% diabolic, 5% anarchist', '{"IQ":"1D6+6","MA":"3D6","ME":"1D6+12","PS":"2D6+12","PP":"2D6+10","PE":"3D6+6","PB":"1D6+1","Spd":"6D6+12"}', '1D6x10+PE', '6D6+10', NULL, '2D6x10+10', NULL, NULL, 12, 14, '{"attacks":4,"initiative":2,"strike":3,"parry":3,"dodge":2,"pull":3,"roll":3}', '+2 on all magic saving throws, +6 to save vs horror factor, in addition to attribute bonuses; uses any weapons and armor; with the Fenry, the foot soldiers of Dyval; attacks per melee: 4 hand to hand per melee round, or 2 by magic', 'Equivalent to all O.C.C. skills of the Mercenary or Assassin, but selects only two O.C.C. related skills and ignores hand to hand skill; uses the Assassin experience table', 'Nightvision 60ft, sees the invisible, turns invisible at will, shapeshifts to human form, tracks by smell 55% (per 100 ft), teleports between dimensions (63%+2%/level), regenerates 3D6 SDC per round, knows all languages, and leaps 30ft.', 'PPE 2D6x10+10; all level one fire elemental magic plus turn dead, luck curse, phobia curse, compulsion, remove curse, heal wounds', NULL, '8 feet tall (2.4 m)', '500 pounds (225 kg)', NULL, NULL, NULL, NULL, NULL, 'A horned, goat-legged deevil with a rams horns and a pig-like nose, a lesser tempter and betrayer serving the hordes of Dyval.', 'Palladium Fantasy RPG Main Book p.326-327');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'fenry', 'Fenry (Demon Wolf)', 'deevil', 'palladium-fantasy', 0, '40% miscreant, 40% diabolic, 20% aberrant', '{"IQ":"2D6+2","MA":"3D6+2","ME":"3D6+2","PS":"2D6+20","PP":"2D6+10","PE":"3D6+10","PB":"1D6+4","Spd":"2D6x10+40"}', '1D4x10+PE', '6D6+10', NULL, '2D4x10', '2D4x10+10', NULL, 10, 14, '{"attacks":4,"initiative":3,"strike":4,"parry":2,"dodge":2,"pull":1,"roll":2}', '+2 on all magic saving throws, +10 to save vs horror factor, in addition to attribute bonuses; never uses weapons or armor; a symbol of lycanthropy, sometimes worshipped by werewolves; attacks per melee: 4 physical or psionic per melee', 'Equivalent OCC skills: streetwise +30%, intelligence +20%, land navigation +25%, wilderness survival +25%, track animals +10%, track humans +20%, identify plants and fruit +10%, demon and monster lore +20%, basic math +10%, plus prowl, swim, and climb; uses the Assassin experience table', 'Nightvision 90ft, excellent day vision, keen hearing, fireproof (magic flame half damage), knows all languages, leaps 30ft high or 50ft long, teleports between dimensions (31%), regenerates 3D6 SDC or HP per round, and tracks blood or familiar scents at range.', NULL, 'ISP 2D4x10+10; all healing, sensitive, and physical psionic powers', '4 feet tall at the shoulder, 8 feet long (1.2 m / 2.4 m)', '600 pounds (270 kg)', NULL, NULL, NULL, NULL, NULL, 'A giant four-legged black demon wolf with glowing red eyes, a solitary hunter often kept as a scout by other supernatural beings.', 'Palladium Fantasy RPG Main Book p.328');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'horrors', 'Horrors', 'deevil', 'palladium-fantasy', 0, '50% aberrant, 25% miscreant, 5% diabolic, 20% anarchist', '{"IQ":"2D6+8","MA":"1D6+3","ME":"2D6+12","PS":"6D6+14","PP":"2D6+12","PE":"3D6+12","PB":"1D4","Spd":"4D6+20"}', '1D6x10+PE', '4D6+10', NULL, 'PEx9', NULL, 'Cannot fly; Speed figure is for running only. PPE has a floor of 135 regardless of P.E. score.', 16, 17, '{"attacks":5,"initiative":5,"strike":3,"parry":3,"dodge":3,"pull":6,"roll":2}', '+3 on all magic saving throws, +12 to save vs horror factor, in addition to attribute bonuses; rarely uses weapons and never wears armor; attacks per melee: 5 physical per melee, or 2 by magic', 'O.C.C. equivalent skills: streetwise +6%, intelligence +15%, land navigation +20%, track humans +30%, recognize weapon quality +15%, military etiquette +10%, demon and monster lore +20%, basic math +30%, climb +20%, swim +10%, one W.P. of choice (typically claws and bite), literate in Elven and two others +20%; average level 1D4+2, uses the Wizard experience table', 'Nightvision 120ft, sees and turns invisible at will, many eyes prevent surprise or blinding attacks, leaps 100ft, teleports between dimensions (74%+2%/level), immune to poison, resists fire and cold (magic versions half damage), knows all languages, and regenerates 4D6 SDC or HP per round.', 'PPE = P.E. x9 (135 minimum); all level one air elemental spells plus call lightning, turn dead, exorcism, banishment, heal wounds', NULL, '16 to 20 feet tall (4.9 to 6 m)', '2000 pounds (900 kg)', NULL, NULL, NULL, NULL, NULL, 'A monstrous, many-eyed deevil enforcer with a dripping maw and vicious claws, used to keep lesser deevils in line through torture and war.', 'Palladium Fantasy RPG Main Book p.331-332');

INSERT INTO stat_attacks (owner_kind, owner_slug, name, damage, is_mega_damage, range, note, sort) VALUES
  ('creature', 'monster-insect', 'Claws', '1D6', 0, NULL, NULL, 0),
  ('creature', 'monster-insect', 'Bite or Stinger', '3D6', 0, NULL, NULL, 1),
  ('creature', 'mummy', 'Punch', '2D6', 0, NULL, 'by hand/punch or by weapon', 0),
  ('creature', 'zombies', 'Punch', '2D6', 0, NULL, 'by hand/punch or by weapon', 0),
  ('creature', 'golem', 'Punch/Kick/Stomp', '3D6 + P.S. bonus', 0, NULL, 'or by weapon', 0),
  ('creature', 'gargoylites', 'claws', '1D4 (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'gurgoyles', 'claws', '1D6 each (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'gurgoyles', 'bite', '1D4 (plus supernatural P.S. bonus)', 0, 'melee', '', 1),
  ('creature', 'gargoyles', 'claws', '1D6 each (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'gargoyles', 'bite', '1D4 (plus supernatural P.S. bonus)', 0, 'melee', '', 1),
  ('creature', 'gargoyles', 'fire breath', '4D6 S.D.C.', 0, '40 ft (12.2 m)', 'once per melee round', 2),
  ('creature', 'gargoyle-mage', 'claws', '1D6 each (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'gargoyle-mage', 'bite', '1D4 (plus supernatural P.S. bonus)', 0, 'melee', '', 1),
  ('creature', 'gargoyle-mage', 'fire breath', '4D6 S.D.C.', 0, '10 ft (3 m)', 'once per melee round', 2),
  ('creature', 'gargoyle-lords', 'claws', '2D4 each (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'gargoyle-lords', 'bite', '1D6 (plus supernatural P.S. bonus)', 0, 'melee', '', 1),
  ('creature', 'gargoyle-lords', 'fire breath', '4D6 S.D.C.', 0, '40 ft (12.2 m)', 'once per melee round', 2),
  ('creature', 'alu-demon-hound', 'claws', '1D6 each (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'alu-demon-hound', 'bite', '1D6 (plus supernatural P.S. bonus)', 0, 'melee', '', 1),
  ('creature', 'aquatics', 'bite', '2D4 (plus supernatural P.S. bonus)', 0, 'melee', '', 0),
  ('creature', 'aquatics', 'strangulation', 'normal supernatural P.S. damage per squeeze', 0, 'melee', 'average human/elf/surface dweller drowns after 2 minutes without air; giants 1D4+2 minutes', 1),
  ('creature', 'banshee', 'astral strike', '1D6 hit points per punch or kick', 0, 'melee', 'only against astral travelers, air elementals, or astral attackers', 0),
  ('creature', 'labassu', 'Astral Strike', '1D6', 0, 'melee (astral plane, or vs astral travelers)', 'Its only means of physical harm; otherwise it attacks only via empathic transmission.', 0),
  ('creature', 'shedim', 'Hand Claws', '2D6', 0, 'melee', 'plus supernatural P.S. bonus; punch, stab or raking strike', 0),
  ('creature', 'shedim', 'Foot Claws', '2D6', 0, 'melee', 'plus supernatural P.S. bonus', 1),
  ('creature', 'shedim', 'Leap Kick', '3D6', 0, 'melee', 'plus supernatural P.S. bonus; clawed feet', 2),
  ('creature', 'shedim', 'Bite', '1D6', 0, 'melee', 'plus supernatural P.S. bonus', 3),
  ('creature', 'mares', 'Claws', 'supernatural P.S.+1D6', 0, 'melee', 'extra 1D6 on top of supernatural P.S. damage', 0),
  ('creature', 'baal-rog', 'Clawed Hands', '2D6', 0, 'melee', 'plus supernatural P.S. bonus; punch, stab or raking strike', 0),
  ('creature', 'baal-rog', 'Leap Kick', '3D6', 0, 'melee', 'plus supernatural P.S. bonus; clawed feet', 1),
  ('creature', 'baal-rog', 'Bite', '1D6', 0, 'melee', 'plus supernatural P.S. bonus', 2),
  ('creature', 'demon-locusts', 'Front-Leg Strike', '4D6', 0, 'melee', 'supernatural P.S. considered', 0),
  ('creature', 'demon-locusts', 'Rear-Leg Kick', '5D6', 0, 'melee', 'supernatural P.S. considered', 1),
  ('creature', 'demon-locusts', 'Power Punch', '1D6x10', 0, 'melee', 'counts as two attacks', 2),
  ('creature', 'demon-locusts', 'Bite', '2D6', 0, 'melee', NULL, 3),
  ('creature', 'demon-locusts', 'Scorpion Tail Sting', '6D6', 0, 'melee', 'target saves vs poison (14+) or is paralyzed 2D6 melees and takes 6D6 more damage', 4),
  ('creature', 'magots', 'Body Block', '4D6', 0, NULL, '85% chance to knock opponent off feet 20 ft away; victim loses two attacks and initiative; counts as two attacks', 0),
  ('creature', 'night-owls', 'Claw Strike', '1D6', 0, NULL, NULL, 0),
  ('creature', 'night-owls', 'Flying Claw Strike', '2D6', 1, NULL, '40% chance to knock opponent off feet; counts as two attacks', 1),
  ('creature', 'raksasha', 'Claw Strike', '1D6', 0, NULL, NULL, 0),
  ('creature', 'raksasha', 'Bite', '1D6', 0, NULL, NULL, 1),
  ('creature', 'dire-harpies', 'Claws', '1D6', 0, NULL, 'each', 0),
  ('creature', 'dire-harpies', 'Bite', '1D4', 0, NULL, NULL, 1),
  ('creature', 'dire-harpies', 'Spit Lava', '4D6', 0, '40 ft', 'counts as one melee attack', 2),
  ('creature', 'gorgons', 'Snake Bite', '2D6', 0, '10 ft reach', 'snakes are +2 to strike/dodge, +5 to parry', 0),
  ('creature', 'gorgons', 'Snake Whip/Jab', '1D6', 0, '10 ft reach', 'snakes are +2 to strike/dodge, +5 to parry', 1),
  ('creature', 'gallu', 'Clawed hands', '1D6', 0, 'melee', 'per punch, in addition to supernatural P.S. damage', 0),
  ('creature', 'gallu', 'Leap kick', '+6', 0, 'melee', 'printed as leap kick +6; exact application uncertain', 1),
  ('creature', 'gallu', 'Bite', '1D4', 0, 'melee', 'in addition to supernatural P.S. damage', 2),
  ('creature', 'gallu', 'Head butt with horns', '2D6', 0, 'melee', 'in addition to supernatural P.S. damage', 3);

INSERT INTO stat_attacks (owner_kind, owner_slug, name, damage, is_mega_damage, range, note, sort) VALUES
  ('creature', 'gallu', 'Running ram with horn', '4D6', 0, 'melee', '60% chance of knocking opponent off his feet; counts as two attacks', 4),
  ('creature', 'deevils', 'Claws', '1D6', 0, 'melee', 'in addition to supernatural P.S. damage', 0),
  ('creature', 'deevils', 'Head butt', '1D6', 0, 'melee', 'in addition to supernatural P.S. damage', 1),
  ('creature', 'fenry', 'Bite', '+2D6', 0, 'melee', 'extra damage beyond supernatural P.S. punch damage', 0),
  ('creature', 'fenry', 'Clawed feet', 'normal punch damage', 0, 'melee', 'per supernatural P.S., no additional bonus printed', 1),
  ('creature', 'fenry', 'Head butt', 'normal punch damage', 0, 'melee', 'per supernatural P.S., no additional bonus printed', 2),
  ('creature', 'horrors', 'Bite', 'full punch damage+1D6', 0, 'melee', 'punch damage already includes supernatural P.S.', 0),
  ('creature', 'horrors', 'Clawed hands', '+2D6', 0, 'melee', 'extra, beyond normal punch damage', 1);

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 36 creatures are in' AS assertion, count(*) AS got, 36 AS want
  FROM creatures WHERE slug IN ('monster-insect', 'mummy', 'zombies', 'golem', 'gargoylites', 'gurgoyles', 'gargoyles', 'gargoyle-mage', 'gargoyle-lords', 'alu-demon-hound', 'aquatics', 'banshee', 'couril', 'labassu', 'lasae', 'shedim', 'mares', 'baal-rog', 'demon-locusts', 'jinn', 'magots', 'night-owls', 'raksasha', 'devilkins', 'dire-harpies', 'fiends', 'gorgons', 'imps', 'arch-fiends', 'wraiths', 'serpents', 'beasts', 'gallu', 'deevils', 'fenry', 'horrors');
SELECT 'and their 58 attacks' AS assertion, count(*) AS got, 58 AS want
  FROM stat_attacks WHERE owner_kind = 'creature' AND owner_slug IN ('monster-insect', 'mummy', 'zombies', 'golem', 'gargoylites', 'gurgoyles', 'gargoyles', 'gargoyle-mage', 'gargoyle-lords', 'alu-demon-hound', 'aquatics', 'banshee', 'couril', 'labassu', 'lasae', 'shedim', 'mares', 'baal-rog', 'demon-locusts', 'jinn', 'magots', 'night-owls', 'raksasha', 'devilkins', 'dire-harpies', 'fiends', 'gorgons', 'imps', 'arch-fiends', 'wraiths', 'serpents', 'beasts', 'gallu', 'deevils', 'fenry', 'horrors');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-creatures-palladium-fantasy.sql');
