-- The 87 gear rows Rifts World Book 7: Underseas prices or stats - weapons,
-- body armour, bionic implants, and the book's list of ordinary sea vessels.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-underseas-gear.sql
--
-- Offsets from scripts/books.json: page_offset -1 with an exception putting
-- printed 1-130 at +0. The Tritonia and New Navy sections sit below the split,
-- so printed N is cache pN; everything from printed 133 on is cache pN-1.
--
--   section                              printed      rows
--   Weapons & Equipment of Tritonia       100-101        5
--   Weapons & Equipment of the New Navy   116-118       11
--   Human Ocean Equipment                 137-139        3
--   Some Basic Boats                      135-137       33
--   Naut'Yll Weapons & Technology         153-156       12
--   Horune Weapons & Technology           166            3
--   Weapons of Atlantis and rune weapons  173-175       10
--   NGR/Triax underwater kit              191-193       10
--
-- THE 33 BOATS GO IN `gear` WITH category 'vehicle', NOT IN THE `vehicles`
-- TABLE, and the reason is precedent rather than convenience. 36 gear rows
-- already carry that category - hovercycles, ATVs, exoskeletons - and the
-- `vehicles` table was built by migration 048 for stat blocks with M.D.C. BY
-- LOCATION and numbered weapon systems, which is what BOOK-INGEST-AUDIT F3
-- was about. These boats have a price, an S.D.C., a length, a speed and a
-- crew, and NO location breakdown and no Model Type line at all. They are the
-- first vessels in this catalog to use gear.sdc, which is exactly what that
-- column is for: how much the OBJECT takes before it breaks.
--
-- It also unblocks something. The Salvage Expert's starting vessel - printed
-- 134 offers a submersible, a large sailboat, a cabin cruiser or power armour
-- - was left unstorable in #805 because nothing held a vessel. `sailboat-large`
-- and `cabin-cruiser` are real rows now.
--
-- TWO PRICES IN THIS FILE ARE THE BOOK'S OWN TYPOS, not OCR damage, and the
-- difference decides how they are handled. An extraction pass flagged
-- "600,000 to 750,00" (Sailing Schooner) and "950,00 to 1.4 million" (Sailing
-- Brigantine) as probably missing a trailing zero. Printed 135 was RENDERED at
-- 220 and 240 dpi and read directly: the page really does print both that way.
-- A misread gets re-read; a misprint gets recorded. The Brigantine's broken
-- figure is the one that lands in the integer column, and it is stored as
-- 950,000 - the only reading consistent with its own 1.4 million upper bound
-- and with the Schooner's range beneath it - with the printed string quoted in
-- cost_note.
--
-- ONE ENTRY PRINTS TWO DIFFERENT COSTS. The NGR Deep-Sea Environmental Body
-- Armor on printed 191 ends its description "Cost: 56,000 credits" and then,
-- eight lines later, carries "Market Cost: Not available. Should cost around
-- 75,000 credits." Both are really there. The explicit Cost line is stored and
-- the estimate is in cost_note. A following line reads "Colors: BOTH types of
-- suits", which would explain two figures if the entry covers two variants -
-- but the book never names a second one, so that is recorded as an
-- observation and not asserted.
--
-- NULL COST IS A FINISHED ROW HERE, and this book leans on it hard: the Sonic
-- Wand, both techno-wizard grenades, the Kittani energy net, all five rune
-- weapons and the TXT-10 torpedoes print no price at all. Rune weapons are
-- explicitly sent to Rifts Atlantis for stats. Per the gear.cost comment, an
-- invented number would be indistinguishable from a real one, so none is
-- written.
--
-- SEVEN ROWS ARE STUB UPGRADES rather than inserts. The class imports in #800
-- through #807 created placeholder gear rows with auto-generated names - "Bg
-- 15 Blue Green Laser Pistol", "M 2011 Pistol" - carrying the
-- STUB marker. The ON CONFLICT clause below fills them in and corrects the
-- names, and it is GUARDED on the row still being a stub, so re-running this
-- file can never overwrite a row somebody has since edited by hand.
--
-- FOUR THINGS THE BOOK GETS WRONG, transcribed as printed and flagged in the
-- row that carries them rather than corrected:
--   * the M-20's clip weight, "one lb. (2.7 kg)" - the two units disagree
--   * the Underwater Rail Gun's air range, "2500 feet (76.2 m)"
--   * the TXD-8's weight, "52 lbs (9.5 kg)", repeating the TXD-6 metric figure
--   * the Underwater Rail Gun's cost line saying "outside naut'yll
--     settlements" on a KITTANI weapon, which reads like a phrase carried over
--     from the naut'yll section a few pages earlier
--
-- AND ONE NAME THE BOOK DISAGREES WITH ITSELF ABOUT: the TXD-03 Deep-Sea Laser
-- Assault Rifle is called the TX-60 in the standard-features list for the
-- TXD-6 and TXD-8 frogman armours on the facing page. The heading spelling is
-- stored and the other is in the row's cost_note.
--
-- NOT IMPORTED, deliberately:
--   * Kittani Plasma Weapons (printed 173) is a RULE, not an item - it applies
--     an underwater modification to a weapon line statted in Rifts Atlantis.
--   * "Other Weapons" (printed 166-167) is a paragraph naming brands the
--     horune like to capture. No stat block, nothing to store.
--   * every entry carrying a `Model Type:` line - 26 of them across these
--     pages. Those are power armour, robots and vessels with M.D.C. by
--     location, and they belong in the `vehicles` table in their own pass.
--
-- Pure ASCII with LF endings on purpose - see PR #101.

INSERT INTO gear
  (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book)
VALUES
('bg-15-blue-green-laser-pistol', 'BG-15 Blue-Green Laser Pistol', 'rifts', 'weapon', 2, 13000, NULL, '2D4 M.D.', 1, '1000 feet (305 m), above or under water', '15 shots', 'Standard', NULL, NULL, NULL, 'A Tritonian laser pistol firing a blue-green frequency that passes through water unimpeded, so its range and damage are the same above and below the surface. The pre-Rifts design resembles the Wilk''s pistol closely enough that amateurs confuse the two.', 'Rifts World Book 7: Underseas p.100'),
('bg-20-blue-green-laser-rifle', 'BG-20 Blue-Green Laser Rifle', 'rifts', 'weapon', 6, 20000, NULL, '3D6 M.D.', 1, '2000 feet (610 m)', '20 shots', 'Standard', NULL, NULL, NULL, 'The rifle built on the BG-15''s blue-green laser, and standard issue for Tritonian security and the Sea Wolves. Popular with pirates and fishermen too, and sometimes mistaken for a Wilk''s 447.', 'Rifts World Book 7: Underseas p.100'),
('m-80-stormbringer-mwas', 'M-80 "Stormbringer" Multi-Weapon Assault System', 'rifts', 'weapon', 21, NULL, NULL, 'Ion-pulse gun 4D6 M.D.; LAWS launcher 1D6x10 M.D. with mini-missiles or torpedoes; vibro-bayonet 1D6 M.D. in hand to hand.', 1, 'Ion-pulse gun 2000 feet (610 m); LAWS 4000 feet (1220 m); bayonet is close combat only.', 'Pulse gun 12 shots on a standard E-clip or 25 on a long clip; LAWS drum magazine of 5 rounds.', 'Each mode is one melee action.', NULL, NULL, NULL, 'A man-portable version of the giant Merbot''s M-90: an ion-pulse rifle, a rocket launcher and a vibro-bayonet in one unit. A P.S. of 20 or better is suggested; below that the user is -2 to strike and fatigues twice as fast.', 'Rifts World Book 7: Underseas p.100'),
('scuba-body-armor', 'SCUBA Body Armor', 'rifts', 'armor', 21, 65000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 70, 'Tritonian body armour carrying ten hours of oxygen and a set of ballast compartments, so the wearer controls ascent and descent rather than fighting his own buoyancy the way ordinary armour makes him. Excellent mobility, -5% to prowl.', 'Rifts World Book 7: Underseas p.100'),
('amphib-body-armor', 'Amphib Body Armor', 'rifts', 'armor', NULL, 75000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'A heavier, amphib-strength version of the SCUBA armour. Helmets are often custom-fitted for non-human head shapes and are designed to flood for a gilled amphib. Excellent mobility for an amphib at -5% to prowl; a human wearing it is -25%.', 'Rifts World Book 7: Underseas p.101'),
('m-2011-pistol', 'M-2011 Energy Pistol', 'rifts', 'weapon', 5, 19000, NULL, '1D4x10 S.D.C. or 3D6 M.D. per single shot, by setting.', 1, '800 feet (244 m)', '20 shots on a short E-clip, 30 on a long one.', 'Standard', NULL, NULL, NULL, 'The New Navy''s heavy ion sidearm, issued to officers, pilots and vehicle crews. Closer to a machine-pistol than a sidearm in size.', 'Rifts World Book 7: Underseas p.116'),
('m-160-assault-rifle', 'M-160 Assault Rifle', 'rifts', 'weapon', 7, 38000, NULL, '3D6 M.D. single shot, or 1D6x10 M.D. on a three-shot ion burst.', 1, '2000 feet (610 m)', '30 shots on a short E-clip, 55 on a long one.', 'Standard', NULL, NULL, NULL, 'The pre-Rifts standard-issue ion pulse rifle of the US Marines, still the New Marine Corps weapon. It works underwater with no loss of range or performance.', 'Rifts World Book 7: Underseas p.116'),
('rapid-fire-laws-3', 'Rapid-Fire LAWS-3 Rocket Launcher', 'rifts', 'weapon', 18, 45000, '45,000 credits for the launcher. A loaded clip is 3,000 credits armour-piercing or 2,100 fragmentation.', 'Single shot 1D4x10 M.D. armour-piercing, 1D6x10 M.D. high explosive, or 4D6 M.D. to a 20 foot (6 m) blast fragmentation. A three-round burst does 3D4x10 M.D. A.P., 3D6x10 M.D. H.E., or double damage and a 40 foot (12 m) blast fragmentation.', 1, '2000 feet (610 m) laser-guided, or about 4000 feet (1220 m) unguided at -2 to strike.', 'A six-round disposable clip; a reload is about one melee action.', 'One at a time or a three-round burst, either counting as one melee attack.', NULL, NULL, NULL, 'A rapid-fire, laser-designated anti-tank rocket launcher with auto-ejecting disposable clips. Two are issued to a ten-man squad.', 'Rifts World Book 7: Underseas p.116'),
('m-20-assault-rifle', 'M-20 Assault Rifle', 'rifts', 'weapon', 10, 35000, '35,000 credits for the rifle. Bullets are about 90 credits a clip standard or 150 armour-piercing; grenades are 220 fragmentation, 350 armour-piercing or plasma, and 50 smoke.', 'Mostly S.D.C.: a single round does 4D6 S.D.C. and an A.P. round 1D4x10 S.D.C. An eight-round burst does 1 M.D., or 3 M.D. armour-piercing. Grenades: fragmentation 3D4 M.D. to a 10 foot blast, plasma or napalm 4D6 M.D. to a 6 foot blast plus fire, armour-piercing 3D6 M.D., and smoke, which does none and lays a 20 foot cloud for 2D4 minutes.', 0, '2000 feet (610 m) for the rifle; 1200 feet (366 m) for the grenade launcher.', 'A 64-round cartridge clip and four grenades, hand-loaded in about five seconds.', 'Single round or an eight-round automatic burst, each one melee attack; a grenade is one attack each.', NULL, NULL, NULL, 'A pre-Rifts assault rifle much like an M-16A1 with an under-barrel grenade launcher, and one of the items the New Navy commonly trades to outsiders. It is an S.D.C. weapon that only reaches mega-damage on a burst or with a grenade.', 'Rifts World Book 7: Underseas p.117'),
('deep-sea-depth-charge', 'Deep Sea Depth Charge', 'rifts', 'weapon', NULL, 4500, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Dropped ordnance rather than a carried weapon, priced per charge. Imported as gear because it is a priced item a character can buy; it is not a hand weapon and carries no stat block of the usual shape.', 'Rifts World Book 7: Underseas p.117'),
('torpedo-mini', 'Torpedo, Mini', 'rifts', 'weapon', NULL, 3500, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'The smallest of the New Navy''s four torpedo grades, priced per torpedo. Launched ordnance rather than a carried weapon.', 'Rifts World Book 7: Underseas p.117'),
('torpedo-light', 'Torpedo, Light', 'rifts', 'weapon', NULL, 8000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'The second of the New Navy''s four torpedo grades, priced per torpedo.', 'Rifts World Book 7: Underseas p.117'),
('torpedo-medium', 'Torpedo, Medium', 'rifts', 'weapon', NULL, 10000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'The third of the New Navy''s four torpedo grades, priced per torpedo.', 'Rifts World Book 7: Underseas p.117'),
('torpedo-heavy', 'Torpedo, Heavy', 'rifts', 'weapon', NULL, 20000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'The largest of the New Navy''s four torpedo grades, priced per torpedo.', 'Rifts World Book 7: Underseas p.117'),
('navy-body-armor', 'Navy Body Armor', 'rifts', 'armor', 11, 40000, '40,000 credits outside the Salvation and Refuge Bases.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 45, 'Light, comfortable armour for general New Navy personnel, with built-in flotation that doubles as a life jacket. Excellent mobility, -5% on prowl and physical skills. It ruptures below 1000 feet (305 m).', 'Rifts World Book 7: Underseas p.118'),
('marine-combat-armor', 'US Marine Combat Armor', 'rifts', 'armor', 21, 50000, '50,000 credits outside the Refuge and Salvation Bases.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 85, 'Heavier combat armour with an airtight face mask, limited life support and a built-in radio, rated to 2000 feet (610 m). Good mobility, -10% on prowl and physical skills. Olive green or camouflage; it is traded to outsiders often enough that Iron Heart Armaments has tried to copy it.', 'Rifts World Book 7: Underseas p.118'),
('green-laser-rifle', 'Green Laser Rifle', 'rifts', 'weapon', 6, 20000, NULL, '3D6 M.D.', 1, '2000 feet (610 m)', '20 shots', 'Standard', NULL, NULL, NULL, 'A laser rifle favoured by pirates, undersea explorers and fishermen. Built of black plastic and ceramic in a shape close enough to a Wilk''s 447 that the two are easily confused.', 'Rifts World Book 7: Underseas p.137'),
('lews-9-light-environmental-wet-suit', 'LEWS-9 Light Environmental Wet Suit', 'rifts', 'armor', 11, 15000, '15,000 credits without the jet boots; add 3,000 credits for the boots. A two-part price, not a range.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 25, 'A form-fitting sealed wet suit with a helmet head-up display giving depth, time, direction and an air gauge, a short-range radio, and shoulder plates that double as small storage compartments. Three hours of air, and it ruptures below 500 feet (152 m). Optional aqua-jet boots weigh 4 lbs (1.8 kg) and make 3 mph on a four-hour E-clip charge.', 'Rifts World Book 7: Underseas p.137'),
('mews-10-medium-environmental-wet-suit', 'MEWS-10 Medium Environmental Wet Suit', 'rifts', 'armor', 30, 50000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 55, 'A heavier deep-sea suit carrying everything the LEWS-9 has plus a full aqua-jet system in the boots, shoulders and back, and a built-in decompression and air-recirculation system on a twelve-hour power pack. Costs -5% on prowl and similar physical skills.', 'Rifts World Book 7: Underseas p.139'),
('nautyll-sonic-wand-tw', 'Sonic Wand (TW)', 'rifts', 'weapon', NULL, NULL, 'NO PRICE, NO WEIGHT AND NO PAYLOAD LINE are printed for this item, which is unusual - every other entry in the Naut Yll weapons section carries all three.', 'Three sonic blasts of 2D6 M.D. each, or one blast of 6D6 M.D., for 10 P.P.E. or 20 I.S.P. For 15 P.P.E. or 30 I.S.P. it fires two sonic stun blasts, as the dolphin magic spell, against which a victim must roll 14 or better to save. As a club it does 2D6 S.D.C.', 1, '600 feet (183 m)', NULL, NULL, NULL, NULL, 100, 'A techno-wizard nightstick with two nodules near the tip and a coil of wire by the handle. The user must be psionic or a sorcerer with P.P.E. to power it. The wand itself has 100 M.D.C.', 'Rifts World Book 7: Underseas p.153'),
('nautyll-sonic-rifle-tw', 'Sonic Rifle (TW)', 'rifts', 'weapon', 6, 80000, '80,000 credits outside a naut yll outpost. It costs 200 P.P.E. to make and 60 P.P.E. or 120 I.S.P. to recharge.', '5D6 M.D. on a sonic blast, or a sonic stun.', 1, '2000 feet (610 m)', '30 blasts and 20 stuns.', 'Single shot, one melee action.', NULL, NULL, 100, 'A techno-wizard rifle with 100 M.D.C. that never jams.', 'Rifts World Book 7: Underseas p.153'),
('nautyll-particle-wave-pistol', 'Particle Wave Pistol', 'rifts', 'weapon', 4, 20000, '20,000 credits outside a naut yll outpost.', '4D6 M.D. per shot.', 1, '1000 feet (305 m)', '20 shots. The coupling must be modified by an armorer for underwater use.', 'Standard', NULL, NULL, NULL, 'The naut yll sidearm.', 'Rifts World Book 7: Underseas p.153'),
('nautyll-particle-wave-rifle', 'Particle Wave Rifle', 'rifts', 'weapon', 7, 40000, '40,000 credits outside a naut yll outpost.', '6D6 M.D. per shot.', 1, '2000 feet (610 m)', '30 shots', 'Standard', NULL, NULL, NULL, 'The naut yll infantry rifle.', 'Rifts World Book 7: Underseas p.154'),
('nautyll-harpoon-rifle', 'Harpoon Rifle', 'rifts', 'weapon', 15, 50000, '50,000 credits outside a naut yll settlement.', 'A standard dart does 1D6 M.D., with a further 1D6 M.D. if the barb is torn out rather than cut. An explosive tip does 4D6+6 M.D. underwater or 4D6 M.D. on land. A lethal poison head does 5D6 M.D. and another 5D6 M.D. every 1D6 melee rounds; a neural poison head does 3D6 M.D. and halves the victim. A smoke or flare head does 1D6 M.D. and burns 2D4 minutes.', 1, '2000 feet (610 m), or 500 feet (152 m) on a cable.', '40 in a drum or 20 in a box magazine.', 'Single shot', NULL, NULL, NULL, 'The naut yll harpoon rifle, and the reason five different heads are worth carrying.', 'Rifts World Book 7: Underseas p.154'),
('nautyll-energy-trident', 'Energy Trident', 'rifts', 'weapon', 12, 70000, '70,000 credits outside a naut yll settlement.', '5D6 M.D., fired or in melee.', 1, '1000 feet (305 m) as an energy blast, or melee reach as a strike.', '30 charges', 'As the wielder hand to hand attacks.', NULL, NULL, NULL, 'The naut yll trident, which fires as readily as it stabs.', 'Rifts World Book 7: Underseas p.154'),
('nautyll-energy-net', 'Energy Net', 'rifts', 'weapon', 8, 6000, NULL, 'A strike does 2D4 S.D.C. The electrical burst is settable to 1D6x10 S.D.C. or 2D6 M.D., affecting whatever is in the net and a ten foot radius around it; a target 10 to 30 feet away takes 1D4 and has a 1-35% chance of being stunned for 1D4 melee rounds. On land the damage is halved and there is no radius.', 1, 'Thrown about 30 feet (9 m) underwater, dropped from up to 1000 feet (305 m), or thrown 40 feet (12 m) on land. The charge can be triggered from up to 1200 feet (366 m).', '8 bursts, regenerating in 30 minutes.', 'As the wielder hand to hand attacks.', NULL, NULL, 20, 'A thrown net that electrifies what it catches. The net itself has 20 M.D.C.', 'Rifts World Book 7: Underseas p.155'),
('nautyll-dpse', 'Dual-Purpose Self-Propelled Explosives (DPSE)', 'rifts', 'weapon', NULL, 2000, 'THE BOOK GIVES NO PRICE OF ITS OWN: it says the cost is the same as the equivalent mini-torpedo or mini-missile, roughly 2,000 credits. The stored figure is that reference, not a printed price for this item.', 'The book gives no damage of its own either, describing it as roughly the equivalent of a plasma or heat mini-missile or torpedo.', 1, 'The book refers the reader to the range and speed of the equivalent mini-torpedo or plasma missile rather than printing one.', 'A one or two shot launcher, or a four-shot backpack.', 'LAW style, one or two shots.', NULL, NULL, NULL, 'A naut yll munition that works as either a torpedo or a missile. Almost every field on this entry is a cross-reference rather than a number, which is why so many of them are null.', 'Rifts World Book 7: Underseas p.155'),
('nautyll-tw-grenade-black-water', 'Techno-Wizard Grenade: Black Water', 'rifts', 'weapon', NULL, NULL, 'No price printed for either techno-wizard grenade.', 'The book gives no damage figure: the effect is the Black Water ocean spell.', 0, NULL, NULL, 'Dropped or placed, with a six second delay.', NULL, NULL, NULL, 'A techno-wizard grenade that produces the Black Water spell effect. The book states the effect by reference and gives it no stat block of its own.', 'Rifts World Book 7: Underseas p.155'),
('nautyll-tw-grenade-sonic-blast', 'Techno-Wizard Grenade: Sonic Blast', 'rifts', 'weapon', NULL, NULL, 'No price printed for either techno-wizard grenade.', '4D6 M.D. to a 20 foot (6 m) blast diameter.', 1, NULL, NULL, 'Dropped or placed, with a six second delay.', NULL, NULL, NULL, 'The offensive half of the naut yll techno-wizard grenade pair.', 'Rifts World Book 7: Underseas p.155'),
('nautyll-shell-body-armor', 'Shell Body Armor', 'rifts', 'armor', NULL, 30000, '30,000 credits outside a naut yll settlement.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 90, 'Plate armour assembled from shells, worn by naut yll line troopers. It circulates water to stop the wearer dehydrating and lets him breathe by drawing air out of the water, controls temperature and resists pressure. It carries no built-in computer or communications - those are separate items. Good mobility, -10% on prowl and other physical skills, though not on swimming.', 'Rifts World Book 7: Underseas p.155'),
('nautyll-korallyte-armor', 'Korallyte Armor', 'rifts', 'armor', NULL, 80000, '80,000 to 150,000 credits, and scarce. Outside naut yll hands it turns up only through a renegade koral shaper in Tritonia, an Atlantean merchant, or pirates.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 150, 'Armour grown from the secretions of the Korallyte mollusc and moulded to its wearer, worn by naut yll officers and elite warbands. It can be repaired with the Shape Koral spell. Full mobility and no prowl penalty, which no other armour in this book manages.', 'Rifts World Book 7: Underseas p.155'),
('horune-harpoon-gun', 'Horune Harpoon Gun', 'rifts', 'weapon', 5, 2000, 'Manufactured in Atlantis.', 'A standard spear does 3D6 S.D.C. and an explosive tip 2D4 M.D. Magic and techno-wizard heads do 6D6 M.D. electrical or 4D6 M.D. heat and plasma, or cast a net on impact at fourth level strength.', 0, '500 feet (152 m)', '3 harpoons, one melee action to reload each, from a 12-harpoon quiver.', 'Single shot or a volley of two or three.', NULL, NULL, NULL, 'The horune pirate boarding weapon.', 'Rifts World Book 7: Underseas p.166'),
('horune-sonic-rifle', 'Horune Sonic Rifle', 'rifts', 'weapon', 6, 10000, 'The book prices it LOW, at 10,000 credits, and says why: almost nothing else can recharge it. Only a Dream Ship or a dolphin combat drone can.', '6D6 M.D. per blast, as the naut yll sonic blast.', 1, '2000 feet (610 m)', '40 blasts', 'Single shot, one melee action.', NULL, NULL, 100, 'A Ship Dreamer techno-wizard rifle with 100 M.D.C. and a reputation for durability. Its low price is a consequence of being nearly impossible for an outsider to recharge.', 'Rifts World Book 7: Underseas p.166'),
('horune-energy-trident', 'Horune Energy Trident', 'rifts', 'weapon', 12, 70000, NULL, '5D6 M.D., fired or in melee.', 1, '1000 feet (305 m) as an energy blast, or melee reach as a strike.', '30 charges', 'As the wielder hand to hand attacks.', NULL, NULL, NULL, 'Usually stolen from the naut yll, or bought as a two-pronged Splugorth copy.', 'Rifts World Book 7: Underseas p.166'),
('kittani-underwater-rail-gun', 'Underwater Rail Gun', 'rifts', 'weapon', 125, 70000, 'The cost line reads "outside naut yll settlements", which is odd on a KITTANI weapon and looks like the phrase was carried over from the naut yll section a few pages earlier. Transcribed as printed.', 'A 40-round burst does 1D4x10 M.D.; a single round does 1D4 M.D.', 1, 'The book prints 1000 feet (305 m) underwater and "2500 feet (76.2 m)" in air. The metric figure on the air range does not convert and is a misprint in the book; the imperial figure is the usable one.', '1120 rounds, or 28 short bursts, per drum.', 'Standard', NULL, NULL, NULL, 'A Kittani rail gun built to fire underwater. The gun is 125 lbs and its ammunition drum another 45.', 'Rifts World Book 7: Underseas p.173'),
('kittani-rocket-grenades', 'Kittani Rocket Grenades', 'rifts', 'weapon', 1, 150, 'PRICED BY TYPE, not by one figure: 150 credits fragmentation, 200 high explosive, 200 gill clog, 350 concussion. The stored cost is the lowest of the four.', 'High explosive 5D6 M.D. to a 4 foot diameter; fragmentation 3D6 M.D. to 40 feet; concussion 4D6 M.D. to 20 feet and 2D6 M.D. to 40, with a 1-35% chance of stunning for 1D4 melee rounds. The gill clog round lays a 20 foot cube of chemical cloud instead of doing damage: -6 on initiative, -6 to strike, parry and dodge, half speed and actions and -50% on skills, halved on a save of 16 or better, with a 1-79% chance per minute of choking. On land all damage and radii are halved and the gill clog does nothing at all.', 1, 'Jet-propelled 300 feet (91 m), or dropped from up to a mile.', NULL, 'One or two at once, counting as one action.', NULL, NULL, NULL, 'Four grenade types on one entry, of which the gill clog is the one built specifically for drowning a gilled enemy.', 'Rifts World Book 7: Underseas p.173'),
('kittani-energy-trident', 'Kittani Energy Trident', 'rifts', 'weapon', 12, 55000, '55,000 credits outside Atlantis.', 'A triple pulse laser does 6D6 M.D.; an energised strike 4D6 M.D.; a de-energised strike 2D4 M.D.', 1, 'Laser 2000 feet (610 m), thrown 100 feet (30.5 m), or melee reach.', '30 charges', 'As the wielder hand to hand attacks.', NULL, NULL, NULL, 'The Kittani answer to the naut yll trident, and the better weapon of the two.', 'Rifts World Book 7: Underseas p.174'),
('kittani-energy-net', 'Kittani Energy Net', 'rifts', 'weapon', NULL, NULL, 'No price printed. The book states the item is fundamentally the same as the naut yll energy net and does not restate its other fields.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 30, 'A Kittani copy of the naut yll energy net. Only its 30 M.D.C. is printed here; every other figure is left to the naut yll entry on printed 155, and is deliberately NOT copied across into this row.', 'Rifts World Book 7: Underseas p.174'),
('rune-spiked-sea-helm', 'Spiked Sea Helm', 'rifts', 'armor', NULL, NULL, 'No price printed. The book says rune weapons are rare and expensive and sends the reader to Rifts Atlantis for full stats, listing only their special abilities here.', 'A head butt does 2D6 M.D. and impaling on the spike 4D6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'An open-face rune helm that grants breathe underwater, swim like a fish, Armor of Neptune and speak underwater for three hours, three times a day. Taking it off leaves the abilities running for another 3D4 minutes.', 'Rifts World Book 7: Underseas p.174'),
('rune-sea-slayer-sword', 'Sea Slayer, Rune Sword', 'rifts', 'weapon', NULL, NULL, 'No price printed; see the Spiked Sea Helm note.', 'The blade does 2D4x10 M.D. and the shark-head pommel bites for 5D6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'A soul-drinking rune sword that can animate and fight on its own up to 200 feet from its owner, with three attacks per melee, +4 to strike and parry and +2 on initiative - though it cannot drink souls while animated.', 'Rifts World Book 7: Underseas p.174'),
('rune-claw', 'Rune Claw', 'rifts', 'weapon', NULL, NULL, 'No price printed; see the Spiked Sea Helm note.', 'A single blade does 3D6 M.D. and both together 6D6 M.D. It can also fire force bolts shaped like the blades for 2D4x10 M.D.', 1, '1000 feet (305 m) for the force bolts, underwater or in air.', NULL, NULL, NULL, NULL, NULL, 'A forearm-mounted retractable double blade. NOTE: this entry ends on a dangling comma in the cache immediately before the next heading, so a trailing clause may have been lost in the scan; everything above is what the page carries.', 'Rifts World Book 7: Underseas p.174'),
('rune-trident', 'Rune Trident', 'rifts', 'weapon', NULL, NULL, 'No price printed; see the Spiked Sea Helm note.', '3D4x10 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'A rune trident carrying every sensitive and physical psionic power plus hydrokinesis, pyrokinesis and bio-manipulation, with 3D6x10 I.S.P. at the strength of a sixth level mind melter. It is CURSED: an aquatic wielder must save against magic at 17 or better every twelve hours of ownership or be permanently turned to the opposite of his own nature.', 'Rifts World Book 7: Underseas p.175'),
('rune-harpoon', 'Rune Harpoon', 'rifts', 'weapon', NULL, NULL, 'No price printed; see the Spiked Sea Helm note.', 'A thrown stab does 1D6x10 M.D., with a further 4D6 M.D. if it is unhooked rather than cut out. A blunt strike does 4D6 M.D. Against a whale or a pneuma-biform all damage is DOUBLED.', 1, '500 feet (152 m) in air, 300 feet (91 m) underwater. It returns to the thrower by magic.', NULL, NULL, NULL, NULL, NULL, 'A rune harpoon that casts agony, life drain, wind rush, summon fog, mask of deceit and fly as the eagle, three times each per day at tenth level strength. Its doubled damage against whales and pneuma-biforms makes it a Whale Singer hunter weapon.', 'Rifts World Book 7: Underseas p.175'),
('ngr-deep-sea-environmental-body-armor', 'Deep-Sea Environmental Body Armor', 'rifts', 'armor', NULL, 56000, 'THE ENTRY PRINTS TWO DIFFERENT COSTS. Its description paragraph ends "Cost: 56,000 credits", and eight lines later a separate line reads "Market Cost: Not available. Should cost around 75,000 credits." Both were read off the cache directly. The stored figure is the 56,000 from the explicit Cost line; the 75,000 is an availability estimate rather than a market price. A following line reading "Colors: BOTH types of suits..." suggests the entry may cover two variants, which would explain two figures - but the book never names a second one, so that is not asserted here.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 175, 'Medium cyborg armour built for depth, often a fully contained environmental suit that plugs into existing cybernetic armour and systems. Good mobility, -10% on prowl and other physical skills. Rated to 1.7 miles (2.7 km).', 'Rifts World Book 7: Underseas p.191'),
('ngr-depth-gauge-alarm', 'Depth Gauge & Alarm', 'rifts', 'cybernetics', NULL, 3000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'An internal implant that calculates depth and reports it on an internal audio channel or head-up display, and warns the wearer when he comes within 100 feet of his own maximum depth tolerance.', 'Rifts World Book 7: Underseas p.191'),
('ngr-bionic-gills', 'Gills', 'rifts', 'cybernetics', NULL, 90000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'An implant in the neck or rib cage that extracts oxygen from water, letting the recipient breathe underwater indefinitely. Triax has so far failed to build a bio-system version that is not cybernetic.', 'Rifts World Book 7: Underseas p.191'),
('ngr-bionic-sonar', 'Sonar', 'rifts', 'cybernetics', NULL, 25000, NULL, NULL, 0, 'Two miles (3.2 km)', NULL, NULL, NULL, NULL, NULL, 'A bionic sonar system tracking up to 24 targets at once.', 'Rifts World Book 7: Underseas p.191'),
('ngr-sonic-echo-location-system', 'Sonic Echo-Location System', 'rifts', 'cybernetics', NULL, 60000, NULL, NULL, 0, '2000 feet (610 m)', NULL, NULL, NULL, NULL, NULL, 'A dolphin-like bionic echo-location system with a base 78% proficiency at judging distance, depth and shape. It cancels the penalties for blindness in total darkness.', 'Rifts World Book 7: Underseas p.191'),
('txt-10-ultra-mini-torpedoes', 'TXT-10 Ultra-mini Torpedoes', 'rifts', 'weapon', NULL, NULL, 'No price printed.', 'High explosive 4D6 M.D. to a 6 foot diameter, or concussion 3D6 M.D. to a 30 foot radius underwater. On land the radius is halved.', 1, 'About 1000 feet (305 m), halved in air.', NULL, 'One, or a volley of two or four.', NULL, NULL, NULL, 'The Triax ultra-mini torpedo, carried by NGR frogman armour and deep-sea power armour.', 'Rifts World Book 7: Underseas p.191'),
('txd-01-deep-sea-sonic-beam-rifle', 'TXD-01 Deep-Sea Sonic Beam Rifle', 'rifts', 'weapon', NULL, 60000, 'The book gives no market price, only a black-market estimate: it "should command a price of 60,000 to 75,000 credits". Stored as the low end of that estimate.', '5D6 M.D. underwater, or 2D6 M.D. on land - the same effect as the sonic blast ocean spell.', 1, '300 feet (91 m) underwater, 80 feet (24 m) on land.', '40 shots on a full-size energy clip.', 'As the gunner hand to hand attacks.', NULL, NULL, NULL, 'A Triax sonic rifle built for underwater use, and much weaker in air.', 'Rifts World Book 7: Underseas p.191'),
('txd-02-deep-sea-laser-harpoon-rifle', 'TXD-02 Deep-Sea Laser/Harpoon Rifle', 'rifts', 'weapon', NULL, 60000, 'A black-market estimate rather than a price: 60,000 to 75,000 credits. Stored as the low end.', 'The laser does 3D6 M.D. The harpoon does 1D6 M.D. conventional or 5D6 M.D. exploding.', 1, 'Laser 1200 feet (366 m) underwater or 2000 feet (610 m) on land; harpoon 300 feet (91 m) either way.', 'Laser 40 shots on a full-size energy clip; harpoon one, reloadable from an eight-spear quiver.', 'As the gunner hand to hand attacks.', NULL, NULL, NULL, 'A Triax combination weapon pairing a laser with a reloadable harpoon.', 'Rifts World Book 7: Underseas p.192'),
('txd-03-deep-sea-laser-assault-rifle', 'TXD-03 Deep-Sea Laser Assault Rifle', 'rifts', 'weapon', NULL, 50000, 'A black-market estimate rather than a price: 50,000 to 75,000 credits. Stored as the low end. NAMING: the standard-features list for the TXD-6 and TXD-8 frogman armours calls this same weapon the TX-60, referring back to "the beginning of this section". The book disagrees with itself; the heading spelling is stored.', 'The blue-green laser does 2D6 M.D. single shot or 1D4x10 M.D. on a triple pulse. The vibro-blade bayonet does 2D6 M.D. as a strike or 3D6 M.D. thrown.', 1, 'Laser 2000 feet (610 m) underwater or 3000 feet (914 m) on land; the bayonet can be thrown 200 feet (61 m).', 'Laser 60 shots on a full-size energy clip; one bayonet.', 'As the gunner hand to hand attacks.', NULL, NULL, 120, 'The Triax deep-sea assault rifle, with 120 M.D.C. of its own and rated to four miles depth.', 'Rifts World Book 7: Underseas p.192'),
('txd-6-frogman-armor', 'TXD-6 Frogman Armor', 'rifts', 'armor', 32, 75000, 'No market price, only an estimate: it "should cost around 75,000 credits".', NULL, 0, NULL, NULL, NULL, NULL, NULL, 70, 'The lighter of the two Triax frogman suits. Good mobility, -10% on prowl and other physical skills, rated to 1200 feet (366 m).', 'Rifts World Book 7: Underseas p.193'),
('txd-8-frogman-armor', 'TXD-8 Frogman Armor', 'rifts', 'armor', 52, 120000, 'No market price, only an estimate: it "should cost around 120,000 credits".', NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'The heavier Triax frogman suit, with an exoskeleton giving +6 to P.S., +10 to Spd and a 75% lower fatigue rate. Fair mobility, -15% on prowl and other physical skills, rated to 2000 feet (610 m). THE BOOK PRINTS ITS WEIGHT AS "52 lbs (9.5 kg)", repeating the TXD-6 metric figure; 9.5 kg is wrong for both and the imperial figures are the usable ones.', 'Rifts World Book 7: Underseas p.193'),
('canoe-standard', 'Canoe (standard)', 'rifts', 'vehicle', NULL, 500, '500 to 1000 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 50, NULL, 'Length 10 to 12 feet (3.0 to 3.65 m), 1-4 mph paddling, 2 to 4 passengers. S.D.C. 50 in wood or 85 in aluminium; the stored figure is the wooden hull.', 'Rifts World Book 7: Underseas p.135'),
('pacific-twin-canoe', 'Pacific Twin Canoe', 'rifts', 'vehicle', NULL, 30000, '30,000 to 45,000 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 150, NULL, 'Length 18 to 20 feet (5.4 to 6.1 m), 6 mph team rowing or 1 to 6 mph under sail, crew and passengers 6 to 10. S.D.C. 150 wood.', 'Rifts World Book 7: Underseas p.135'),
('pacific-war-canoe', 'Pacific War Canoe', 'rifts', 'vehicle', NULL, 50000, '50,000 to 70,000 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 340, NULL, 'Length 40 to 60 feet (12.2 to 18.3 m), 8 mph team rowing, crew and passengers 10 to 40. S.D.C. 340 wood.', 'Rifts World Book 7: Underseas p.135'),
('rowboat-standard', 'Rowboat (standard)', 'rifts', 'vehicle', NULL, 600, '600 to 1200 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 110, NULL, 'Length 8 to 12 feet (2.4 to 3.65 m), 1-2 mph paddling or 4 mph with an outboard motor, 2 to 6 aboard. S.D.C. 110 wood or 150 aluminium; the stored figure is the wooden hull.', 'Rifts World Book 7: Underseas p.135'),
('sailboat-small', 'Sailboat (small)', 'rifts', 'vehicle', NULL, 10000, '10,000 to 40,000 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 250, NULL, 'Length 16 to 30 feet (4.9 to 9.1 m), max speed 6 mph, two to six sailors and 4 to 8 passengers. S.D.C. 250 wood.', 'Rifts World Book 7: Underseas p.135'),
('sailboat-large', 'Sailboat (large)', 'rifts', 'vehicle', NULL, 90000, '90,000 to 150,000 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 600, NULL, 'Length 60 to 90 feet (18.3 to 27.4 m), max speed 12 mph, 10 to 20 crew with a minimum of four. S.D.C. 600 to 900 wood; the stored figure is the low end. This is one of the four vessels a Salvage Expert may start with.', 'Rifts World Book 7: Underseas p.135'),
('sailing-corsair', 'Sailing Corsair', 'rifts', 'vehicle', NULL, 350000, '350,000 to 450,000 credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 1800, NULL, 'Length 70 to 90 feet (21.3 to 27.4 m), max speed 16 mph, 6 to 8 officers, 20 to 26 sailors and 30 to 40 passengers or soldiers. S.D.C. 1800 to 2200 wood.', 'Rifts World Book 7: Underseas p.135'),
('sailing-schooner', 'Sailing Schooner', 'rifts', 'vehicle', NULL, 600000, 'The book prints "600,000 to 750,00 credits" - the upper figure is a MISPRINT IN THE BOOK, not an OCR fault; printed 135 was rendered at 220 dpi and read directly. It is almost certainly 750,000. Only the low end is stored.', NULL, 0, NULL, NULL, NULL, NULL, 2100, NULL, 'Length 100 to 120 feet (30.5 to 36.5 m), max speed 12 mph, 8 officers, 20 to 40 sailors and 30 to 40 passengers or soldiers. S.D.C. 2100 to 2600 wood.', 'Rifts World Book 7: Underseas p.135'),
('sailing-brigantine', 'Sailing Brigantine', 'rifts', 'vehicle', NULL, 950000, 'The book prints "950,00 to 1.4 million credits" - the LOW figure is a MISPRINT IN THE BOOK, not an OCR fault; printed 135 was rendered at 240 dpi and read directly. Stored as 950,000, which is the only reading consistent with the 1.4 million upper bound and with the Schooner below it.', NULL, 0, NULL, NULL, NULL, NULL, 3000, NULL, 'Length 100 to 140 feet (30.5 to 42.6 m), max speed 20 mph, 12 officers, 30 to 40 sailors and 50 to 70 passengers or soldiers. S.D.C. 3000 to 3400 wood.', 'Rifts World Book 7: Underseas p.135'),
('sailing-frigate', 'Sailing Frigate', 'rifts', 'vehicle', NULL, 2000000, '2 to 5 million credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, 3400, NULL, 'Length 150 to 200 feet (45.7 to 61 m), max speed 16 mph, 12 officers, 40 to 60 sailors and 100 to 144 passengers or soldiers. S.D.C. 3400 to 4000 wood.', 'Rifts World Book 7: Underseas p.135'),
('sail-and-oar-war-galley', 'Sail & Oar War Galley', 'rifts', 'vehicle', NULL, 2000000, '2 to 3 million credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Length 180 to 200 feet (54.8 to 61 m), 5 mph on half oars and 10 mph on all of them.', 'Rifts World Book 7: Underseas p.135'),
('sailing-cutter', 'Sailing Cutter', 'rifts', 'vehicle', NULL, 5000000, '5 to 7 million credits. Printed 135 prices these as an average ship of good to very good quality, and the figure excludes special weapon systems, sensors, special features and magic M.D.C. or construction, all of which cost extra.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'The largest of the sailing vessels the book prices.', 'Rifts World Book 7: Underseas p.136'),
('speedboat', 'Speedboat', 'rifts', 'vehicle', NULL, 45000, '45,000 to 90,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A small fast motor boat.', 'Rifts World Book 7: Underseas p.136'),
('racing-boat-hydrofoil', 'Racing Boat/Hydrofoil', 'rifts', 'vehicle', NULL, 300000, '300,000 to 500,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A racing hull or hydrofoil.', 'Rifts World Book 7: Underseas p.136'),
('commercial-hydrofoil', 'Commercial Hydrofoil', 'rifts', 'vehicle', NULL, 100000, '100,000 to 150,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A working hydrofoil rather than a racing one.', 'Rifts World Book 7: Underseas p.136'),
('cabin-cruiser', 'Cabin Cruiser/Inboard Motorboat', 'rifts', 'vehicle', NULL, 40000, '40,000 to 120,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'An inboard motorboat with a cabin. This is one of the four vessels a Salvage Expert may start with.', 'Rifts World Book 7: Underseas p.136'),
('yacht-large', 'Yacht (large)', 'rifts', 'vehicle', NULL, 100000, '100,000 to 200,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A large private motor yacht.', 'Rifts World Book 7: Underseas p.136'),
('fishing-boat-small', 'Fishing Boat (small)', 'rifts', 'vehicle', NULL, 25000, '25,000 to 50,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A small working fishing boat.', 'Rifts World Book 7: Underseas p.136'),
('fishing-trawler-large', 'Fishing Boat/Trawler (large)', 'rifts', 'vehicle', NULL, 100000, '100,000 to 200,000 credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A large commercial trawler.', 'Rifts World Book 7: Underseas p.136'),
('tugboat', 'Tugboat', 'rifts', 'vehicle', NULL, 1000000, 'Construction cost 1 to 2 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Priced as a CONSTRUCTION cost rather than a market price - the book uses that wording for the larger commercial hulls.', 'Rifts World Book 7: Underseas p.136'),
('freighter-small', 'Small Freighter', 'rifts', 'vehicle', NULL, 6000000, 'Construction cost 6 to 10 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A small cargo ship, priced as a construction cost.', 'Rifts World Book 7: Underseas p.136'),
('freighter-large-commercial', 'Large Commercial Freighter', 'rifts', 'vehicle', NULL, 15000000, 'Construction cost 15 to 20 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A large cargo ship, priced as a construction cost.', 'Rifts World Book 7: Underseas p.137'),
('oil-tanker-large', 'Large Oil Tanker', 'rifts', 'vehicle', NULL, 10000000, 'Construction cost 10 to 16 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A large tanker, priced as a construction cost.', 'Rifts World Book 7: Underseas p.137'),
('commercial-submarine', 'Commercial Submarine', 'rifts', 'vehicle', NULL, 10000000, 'Construction cost 10 to 15 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A civilian submarine, priced as a construction cost.', 'Rifts World Book 7: Underseas p.136'),
('navy-submarine-generic', 'Navy Submarine', 'rifts', 'vehicle', NULL, NULL, 'NO PRICE PRINTED. The book points the reader at the submarines described under the New Navy and Triax instead of giving a figure. NULL is the finished state here, not an unfinished one.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military submarine. The book gives no price and refers the reader to the New Navy and Triax vessel entries.', 'Rifts World Book 7: Underseas p.136'),
('coast-guard-cutter', 'Coast Guard Cutter', 'rifts', 'vehicle', NULL, 2000000, '2 to 8 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A coast guard patrol cutter.', 'Rifts World Book 7: Underseas p.136'),
('navy-patrol-boat', 'Navy Patrol Boat', 'rifts', 'vehicle', NULL, 8000000, '8 to 10 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military patrol boat.', 'Rifts World Book 7: Underseas p.136'),
('navy-hydrofoil-aero-jet-patrol-boat', 'Navy Hydrofoil Aero-Jet Patrol Boat', 'rifts', 'vehicle', NULL, 10000000, '10 to 14 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A fast military hydrofoil patrol craft.', 'Rifts World Book 7: Underseas p.136'),
('navy-frigate', 'Navy Frigate', 'rifts', 'vehicle', NULL, 40000000, '40 to 50 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military frigate. The book describes its weapons in prose rather than as a numbered system list.', 'Rifts World Book 7: Underseas p.136'),
('navy-missile-cruiser', 'Navy Multi-Purpose Missile Cruiser', 'rifts', 'vehicle', NULL, 50000000, '50 to 75 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military missile cruiser.', 'Rifts World Book 7: Underseas p.137'),
('navy-destroyer', 'Navy Multi-Purpose Destroyer', 'rifts', 'vehicle', NULL, 70000000, '70 to 90 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military destroyer.', 'Rifts World Book 7: Underseas p.137'),
('navy-battleship', 'Navy Battleship', 'rifts', 'vehicle', NULL, 80000000, '80 to 100 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military battleship.', 'Rifts World Book 7: Underseas p.137'),
('navy-aircraft-carrier', 'Navy Aircraft Carrier', 'rifts', 'vehicle', NULL, 110000000, '110 to 150 million credits. Printed 136 prices these including basic sensors and features and only the weapon systems listed. An M.D.C. version of the same vessel costs twice as much.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A military aircraft carrier - the most expensive vessel the book prices.', 'Rifts World Book 7: Underseas p.137')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  category = excluded.category,
  weight_lbs = excluded.weight_lbs,
  cost = excluded.cost,
  cost_note = excluded.cost_note,
  damage = excluded.damage,
  is_mega_damage = excluded.is_mega_damage,
  range = excluded.range,
  payload = excluded.payload,
  rate_of_fire = excluded.rate_of_fire,
  sdc = excluded.sdc,
  mdc = excluded.mdc,
  description = excluded.description,
  source_book = excluded.source_book
WHERE gear.description LIKE 'STUB%';

-- Read the result back rather than trusting the exit code. One statement each:
-- D1 rejects a compound SELECT past five terms and rolls the whole file back.
SELECT COUNT(*) AS underseas_gear FROM gear WHERE source_book LIKE '%Underseas%';
SELECT COUNT(*) AS underseas_stubs_left FROM gear
  WHERE source_book LIKE '%Underseas%' AND description LIKE 'STUB%';
SELECT COUNT(*) AS boats FROM gear
  WHERE source_book LIKE '%Underseas%' AND category = 'vehicle';
SELECT slug, name, cost, mdc FROM gear
  WHERE slug IN ('bg-15-blue-green-laser-pistol', 'm-2011-pistol', 'marine-combat-armor',
                 'navy-body-armor', 'scuba-body-armor')
  ORDER BY slug;
SELECT slug, name, cost, sdc FROM gear
  WHERE slug IN ('sailboat-large', 'cabin-cruiser', 'sailing-brigantine') ORDER BY slug;
SELECT COUNT(*) AS total_gear FROM gear;

INSERT INTO data_script_runs (filename) VALUES ('add-underseas-gear.sql');
