-- The Dragon Ray R.C.C., Rifts World Book 7: Underseas p.20-22.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-dragon-ray-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'dragon-ray', 'Dragon Ray', 'rifts', '---
id: dragon-ray
name: Dragon Ray
system: rifts
source_book: Rifts World Book 7: Underseas p.20-22
category: rcc
attribute_dice:
  IQ: "3d6"
  ME: "3d6+6"
  MA: "4d6+6"
  PS: "2d6+16"
  PP: "3d6+6"
  PE: "3d6+6"
  PB: "3d6"
  Spd: "2d6+12"
mdc_base: "PEx10"
bonuses:
  combat: { attacks_base: 3, strike: 3, parry: 4, dodge: 5, pull_punch: 1, roll: 4 }
  saves: { horror_factor: 3, spell_magic: 1, toxins_poisons: 1, disease: 2 }
  at_level:
    - { level: 3, combat: { attacks: 1 } }
    - { level: 6, combat: { attacks: 1 } }
    - { level: 9, combat: { attacks: 1 } }
    - { level: 12, combat: { attacks: 1 } }
    - { level: 15, combat: { attacks: 1 } }
psionics:
  type: "major"
  isp_base: "M.E. + 6d6, +1d6+2 per level"
  powers: ["Bio-Regeneration (Super)", "Ectoplasm", "Resist Fatigue", "Mind Block", "Total Recall", "Speed Reading"]
  powers_starting: 2
  categories_allowed: ["Sensitive", "Physical"]
skills:
  occ_skills:
    - { name: "Swimming", base: 98, per_level: 0, note: "At 98%, a fixed figure rather than the catalog base plus a bonus." }
    - { name: "Advanced Fishing", base: 40, per_level: 5, note: "+10%" }
    - { name: "Language: Dragonese", base: 94, per_level: 0, note: "At 94%, a fixed figure." }
    - { choose: 2, from: ["Language: Other"], bonus: 30, note: "Two other languages (+30%). Taken once per language - the picker asks which." }
    - { choose: 1, from: ["Literacy: Other"], bonus: 20, note: "Literacy in one language of choice (+20%)." }
    - { name: "Ocean Geographic Surveying", base: 35, per_level: 5, note: "+20%" }
    - { name: "Navigation: Underwater", base: 45, per_level: 4, note: "Printed as Underwater Navigation (+15%)." }
    - { name: "Undersea & Sea Survival", base: 35, per_level: 5, note: "Printed as Undersea Survival (+10%)." }
    - { name: "Lore: Demons & Monsters", base: 35, per_level: 5, note: "Printed as Lore: Monsters and Demons (+10%)." }
  occ_related_skills:
    count: 8
    schedule: [{ level: 3, count: 1 }, { level: 7, count: 1 }, { level: 11, count: 1 }, { level: 15, count: 1 }]
    categories:
      - { name: "Communications", bonus: 10 }
      - { name: "Domestic", bonus: 10 }
      - { name: "Electrical", bonus: 5 }
      - { name: "Physical", except: ["Boxing", "Wrestling", "Gymnastics"] }
      - { name: "Pilot", only: ["Boat: Sail Type", "Boat: Paddle Types/Canoe/Kayak"] }
      - "Pilot Related"
      - { name: "Rogue", bonus: 5 }
      - { name: "Science", bonus: 5 }
      - { name: "Technical", bonus: 10 }
      - "Weapon Proficiencies"
      - "Wilderness"
    note: "Espionage, Mechanical, Medical and Military are barred entirely. The Domestic +10% applies to Sing only in the book, and the Rogue +5% to Computer Hacking only; both are stored as whole-category bonuses because a category entry carries one bonus for every skill in it - see extraction_notes. Pilot is only simple vessels like sailboats."
restrictions:
  - "Alignment: any, but most are scrupulous, unprincipled or anarchist."
  - "Size: 16 to 20 feet (4.9 to 6.1 m) from snout to tail tip, with a wingspan of 20 to 25 feet (6 to 7.6 m). Weight 600 to 900 lbs (270 to 405 kg)."
  - "Average life span: 900 years, though some have lived as long as 3000."
  - "Horror Factor: 9, but only when the dragon ray is attacking or angry."
  - "P.S. IS SUPERNATURAL."
  - "Depth tolerance: one mile (1.6 km). Can hold its breath for 2D4x10 minutes."
  - "Speed is the GROUND speed of 2D6+12. Underwater it is 2D6+30, roughly 22 to 30 mph; flying it is 2D6+76."
  - "About 7% of dragon rays learn some form of magic. Most find its study too demanding and time-consuming to be fun."
  - "A dragon ray who takes a magic O.C.C. uses that O.C.C.''s skills and abilities instead of this list, but HALVES its related skill selections and keeps the Dragon Ray experience table."
  - "Dragon rays are NOT true dragons."
natural_abilities:
  - name: "Mega-Damage Being"
    description: "Hit points and natural armour rating are the M.D.C.: P.E. number times ten, plus 2D6 per level of experience."
  - name: "Flight"
    description: "Flies at a speed of 2D6+76. On land it can snake along the ground with its wings folded and tucked behind it."
  - name: "Swim 98%"
    description: "Swims at 98% without training. Underwater the wings and tail glide on the currents and dive with a manta ray''s grace, at a speed of 2D6+30."
  - name: "Impervious to Cold"
    description: "Cold does NO damage."
  - name: "Prehensile Tail"
    description: "The tail can grip and manipulate."
  - name: "Articulated Wing-Arms"
    description: "The wing-arms are strong and articulated, each ending in a single pointed tip used like a finger. They can operate a computer - dragon rays love electronics - and are strong enough to climb with or perch on a branch."
  - name: "Bio-Regeneration"
    description: "Heals twice as fast as a human and regenerates lost fins, parts of the tail and limbs within 3D4 weeks."
  - name: "Sense Magnetic North"
    description: "Always knows precisely where magnetic north lies, as the dolphin does."
  - name: "Natural Combat"
    description: "Three physical or psionic attacks per melee round at level one, and one more at levels three, six, nine, twelve and fifteen. A jab with the wing-arm tips does 1D6 M.D.; a swat with arm and wings 2D6 M.D.; a head butt 1D6 M.D.; a bite 3D6 M.D.; a tail slap 1D6 M.D.; a tail strike 3D6 M.D.; a tail power strike 6D6 M.D. and counts as two attacks. A natural 19 or 20 is a critical strike."
  - name: "Tail Parry & Strike"
    description: "+3 to parry and +2 to strike with the tail. Included in the stored combat bonuses."
  - name: "Mid-Air Leap"
    description: "Leaps 20 feet (6.1 m) plus 2 feet (0.6 m) per level out of the water without actually flying. Counts as two melee actions."
  - name: "Mid-Air Precision Leaping"
    description: "The same leap, aimed - to startle or attack beings in a vehicle flying close to the surface, or to grab or knock an item out of a hand. As the dolphin''s."
  - name: "Quick Turns & Stops"
    description: "Rolled as an automatic dodge or parry; a 12 or higher succeeds. A failed roll means the dragon ray could not stop in time and shoots past or slams into something, taking 4D6 impact damage itself."
  - name: "Speed Burst"
    description: "Swims or flies at double speed for 1D4+1 minutes, six times an hour before tiring. Used for a quick dodge or a quick strike at +2, or to close or break away in a hurry. Conditional, so the bonus is prose rather than stored."
  - name: "Tight Circle & Turn"
    description: "Turns and circles within an area as small as 15 feet (4.6 m) across."
  - name: "Dive"
    description: "Dives up to 3000 feet (914 m) at triple normal speed."
  - name: "Psionics"
    description: "Every dragon ray is a MAJOR psionic with bio-regeneration (super), ectoplasm - which it uses to form hands to manipulate objects, use weapons and operate machines - resist fatigue, mind block, total recall and speed reading, plus two of choice from sensitive or physical. I.S.P. is the M.E. number plus 6D6, and 1D6+2 more per level."
extraction_notes: |
  - Underseas, printed 20-22. The dragon ray sits in the Creatures of the Deep
    chapter among about twenty sea-monster entries, and it is one of only TWO
    in that chapter the book makes playable: the Experience Tables on printed
    214 give it a ladder, shared with the Sperm Whale and the Naut''Yll
    Devastator. Printed 22 also states outright that it can be an NPC, a
    villain or an optional player character, at the G.M.''s decision. The other
    ~18 entries in those pages carry `R.C.C. Skills of Note:` and no ladder,
    and are deliberately not imported.
  - M.D.C. IS STORED AS THE BASE ONLY. The book gives it as P.E. number x10
    plus 2D6 per level of experience. `mdc_base` holds the P.E. multiple; the
    per-level 2D6 is in the natural-ability text, because there is no
    per-level M.D.C. key.
  - SPEED IS THE GROUND SPEED. The book prints three - ground 2D6+12,
    underwater 2D6+30, flying 2D6+76 - and `Spd` holds one number. Ground is
    stored because it is the one the sheet''s movement figures assume; the other
    two are in the restrictions and in the natural abilities.
  - TWO CATEGORY BONUSES ARE STORED WIDER THAN THE BOOK PRINTS THEM, and this
    is the opposite trade from the Rurlel Eelman''s Medical entry. Printed 22
    gives Domestic: Any (+10% to sing) and Rogue: Any (+5% on computer
    hacking) - a category granted in full with the percentage attached to ONE
    member. A category entry carries one bonus for every skill in it, so the
    choice is between granting the whole category with the bonus applying too
    widely, or narrowing the category to the named skill with `only` and losing
    the rest. Here the category is kept whole, because the book plainly grants
    all of it and the bonus is the smaller error. The Rurlel went the other way
    because its Medical grant was the narrower half of the sentence. Both
    readings are recorded on their own class.
  - PILOT IS TWO ROWS, AND THE FIRST DRAFT NAMED A ROW THAT DOES NOT EXIST.
    Printed 22 allows "only simple vessels like sailboats", a description
    rather than a list. The draft wrote `Sailing Ships/Boats`; `class-check`
    reported it matching nothing, and an unmatched `only` fails CLOSED - Pilot
    would have been granted and then offered nothing at all, silently. The
    catalog''s rows are `Boat: Sail Type` and `Boat: Paddle Types/Canoe/Kayak`,
    which are the two that answer "simple vessels", and both are stored.
    `Boat: Ships` and `Boat: Motor, Race & Hydrofoil` are deliberately left
    out as not simple.
  - THE ROLL-WITH-IMPACT BONUS IS STORED UNDER `roll`. `sheet.js` draws a
    literal COMBAT_FIELDS list and `roll` is the key in it; `roll_with_impact`
    would parse, validate, compose and render nowhere.
  - THE CRITICAL-ON-19-OR-20 IS PROSE. `critical` is a real COMBAT_FIELDS key
    but it holds a bonus number, not a threshold, so a natural 19-20 critical
    range has nowhere to go and is in the natural-ability text.
  - PSIONICS: the book grants six named powers plus two of choice from
    sensitive or physical, so `powers_starting` is 2 and
    `categories_allowed` is those two categories. Bio-Regeneration (Super) is
    the catalog''s Super row rather than the Healing one, which is what the
    book''s "(super)" means.
---

# Dragon Ray

## Lore

Dragon rays are winged, ray-like creatures that divide their lives between the sea and the land. Sixteen to twenty feet long from snout to tail tip, with a wingspan half again as wide, they glide on ocean currents with a manta ray''s grace and fly above the waves with equal ease. On land they snake along the ground, wings folded and tucked behind them.

They are natural storytellers. Many exaggerate outrageously, but spin such spellbinding yarns that nobody minds. Telling tall tales for laughs is one thing; those of selfish or evil alignment can turn into compulsive liars, and the most cunning and foul-hearted become confidence artists, thieves and assassins who use their storytelling to win trust and then abuse it.

They love electronics and computers, and the single pointed tip on each wing-arm works well enough as a finger to operate one.

Dragon rays are not true dragons. They are mega-damage creatures who may learn magic and who all possess psionic powers.

## GM Notes

An evil dragon ray may conquer and rule a community through lies, treachery or fear. Some work alone, hunting power or wealth; others work with brigands - pirates, unscrupulous salvage teams, mercenaries and monsters.

They can live indefinitely in the sea like dolphins, or indefinitely on land, but most divide their time about sixty-forty between the two. They are most often found along the coastlines of large deep lakes, deep rivers, seas and oceans, or living on islands, in sea cliffs, on beaches and in coastal villages. Dragon rays are found throughout the world.

They have no particular enemies and no particular allies, though they like humans, surface and aquatic humanoid D-bees, and most friendly intelligent beings. Alchemists value them, and they are occasionally captured and sold as slaves or pets.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'dragon-ray');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'dragon-ray';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-dragon-ray-class.sql');
