-- Rifts World Book 2: Atlantis - bio-wizardry (printed 111-125): 33 rows.
-- Microbes, parasites and symbiotes as gear, by Nate's decision on the survey
-- (2026-09-26), and the bio-wizard weapons and devices. See
-- apps/character-creator/docs/surveys/atlantis.md.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-atlantis-bio-wizardry.sql
--
-- READ FROM A SCAN. Extracted by book-extract-worker from printed 106-125.
-- Everything is 'magic' except the Overlord Power Armor ('armor'). Where a
-- range is printed, cost is its low end and cost_note the range; most devices
-- are "not generally available" and cost_note says so. Organisms and devices
-- have no mega-damage flag unless they attack.
--
-- THE BOOK DISAGREES WITH ITSELF ONCE: the Eylor Helm of Omnipotence prints
-- 1150 P.P.E. and, in the same entry, 400. payload records both.
--
-- NOT HERE, and why:
--   * Transmutation, augmentation and reconstruction (printed 107-110), the
--     bio-wizard eyes and sensor systems (110-112): body modifications with
--     no class that installs them, left per the survey.
--   * Eylor Floating Eyes and the Seeker-Hunter Eye (124): constructs with
--     combat stats and no price, so creatures (survey batch 9).
--   * The Eylor Slave Barge (124-125): a vessel with M.D.C. by location, so
--     vehicles (survey batch 8).

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('aerobes', 'Aerobes (Microbe)', 'rifts', 'magic', NULL, 15000, 'per dose', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Bio-wizard microbe, inhaled into the lungs and bloodstream of an animal, human or D-Bee (not supernatural beings). For 24 hours it enriches the blood with oxygen and filters airborne toxins: +10 to save vs gases, +2 vs poison, drugs, toxins and disease; destroys most lung diseases including the common cold; the host uses half the oxygen and can hold his breath for six minutes.', 'Rifts World Book 2: Atlantis p.112'),
('aquarobes', 'Aquarobes (Microbe)', 'rifts', 'magic', NULL, 20000, 'per dose', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Bio-wizard microbe: for eight hours the host can breathe underwater, waterborne pollutants are filtered, and he is +2 to save vs poison. Out of the water the host is at half speed and half combat bonuses while it lasts.', 'Rifts World Book 2: Atlantis p.112'),
('clotrobes', 'Clotrobes (Microbe)', 'rifts', 'magic', NULL, 3000, 'per dose', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Bio-wizard microbe that lives six hours: clots blood and closes wounds in 1D4 minutes, prevents infection, and restores 1D4 hit points (or M.D.C.) in the first four hours on top of normal healing. +1 to save vs poison, toxins and disease.', 'Rifts World Book 2: Atlantis p.112'),
('dehibicila', 'Dehibicila (Microbe)', 'rifts', 'magic', NULL, 50000, 'per dose, typically sold with a blowgun, dart and syringe', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A disease microbe used as a weapon against humans and most D-Bees (not supernatural or magic creatures). For 48 hours the victim has fever, nausea and fatigue: skills -30%, and speed, attacks, combat bonuses and saving throws are halved.', 'Rifts World Book 2: Atlantis p.112'),
('dragoncila', 'Dragoncila (Microbe)', 'rifts', 'magic', NULL, 200000, 'per dose, typically sold with a blowgun', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A disease microbe that infects dragons only. For 72 hours the dragon is sick: skills -25%, speed, attacks and saving throws halved, and it cannot metamorphose or use its breath weapon.', 'Rifts World Book 2: Atlantis p.112'),
('plastirobes', 'Plastirobes (Microbe)', 'rifts', 'magic', NULL, 25000, 'per dose; the plastikil microbe that kills it costs the same', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A microbe that eats plastic, destroying 100 lbs (45 kg) of plastic an hour for four hours; plastic-man body armor loses half its M.D.C. in that time. It dies after four hours, or a dose of plastikil microbes kills it in 20 minutes.', 'Rifts World Book 2: Atlantis p.112'),
('purirobes', 'Purirobes (Microbe)', 'rifts', 'magic', NULL, 10000, 'per dose', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A microbe that lives four hours, killing disease and instantly neutralizing poison: the host is impervious to poison, including toxic gas, while it lasts.', 'Rifts World Book 2: Atlantis p.113'),
('stasirobes', 'Stasirobes (Microbe)', 'rifts', 'magic', NULL, 70000, 'per dose', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Puts the host into a six-hour healing stasis sleep from which he cannot be woken: body temperature drops, P.P.E. and I.S.P. recover at double the normal rate, and 2D4 hit points are restored per six hours. +4 to save vs poison, gases, magic and psionics and +15% vs coma/death while in stasis.', 'Rifts World Book 2: Atlantis p.113'),
('transfortifiers', 'Transfortifiers (Microbe)', 'rifts', 'magic', NULL, 1000000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A microbe that multiplies for 20+1D6 years and turns the host into an M.D.C. being: 110 M.D.C. plus 1D6x10 more per level (or ten years), impervious to cold, heat, magic cold, fire and plasma, grows six inches per level (or 20 years), and P.S. becomes supernatural +2 per level. +4 to save vs poison, toxins, drugs and gases, +10% vs coma/death, +1 vs magic, +2 vs horror factor. The host gains 100 lbs per level, loses a point of P.B. per level (to a minimum of 3), skills -10% and Spd -2 per level, eventually becomes immobile, and dies when the microbes do, about 22 years after exposure. Removable only in the first two months (purirobes 1-15%, restoration 1-30%).', 'Rifts World Book 2: Atlantis p.113'),
('watrobes', 'Watrobes (Microbe)', 'rifts', 'magic', NULL, 5000, 'per 4-gallon dose', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A water-purifying microbe: purifies a gallon every 30 minutes, four gallons over its two-hour life.', 'Rifts World Book 2: Atlantis p.114'),
('brain-feeder', 'Brain Feeder (Parasite)', 'rifts', 'magic', NULL, 150000, 'each', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A one-inch (25.4 mm) parasite that lives in the brain of a psionic mortal for three years. For the first 2D4 months it doubles the host''s I.S.P. and gives a constant high (+2 to save vs psionic attack, horror factor and magic illusions, +5% skills, +1 initiative). Then the bonus vanishes, I.S.P. drains 5 a week and I.Q. and M.E. drop a point; each later stage takes another point of I.Q. and M.E. and more skill (-15%, then -50%), until all I.S.P. and psionics are gone, the host is likely insane, becomes a vegetable in 4D4 weeks and dies 4D4 weeks later unless it is removed.', 'Rifts World Book 2: Atlantis p.114-115'),
('lobee-optos', 'Lobee-optos (Parasite)', 'rifts', 'magic', NULL, 500000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A 9-inch (228 mm) parasite that bores through the forehead into the brain and lives 60 years, its eye-bulb forming a third eye. The host gains +50 I.S.P., +10 P.P.E. and becomes the equivalent of a master psionic with seven powers from any non-super category plus bio-manipulation, and +1D6+1 I.S.P. per level; an existing psionic instead gains two minor and two super powers plus the I.S.P. and P.P.E. +1 to save vs illusions, +2 vs psionic attack, +4 vs mind control, +2% vs coma/death. Side effects: chronic headaches, needs two more hours of sleep (or -10% skills), and the host gets no save if the parasite is attacked psionically. Removal is brain surgery.', 'Rifts World Book 2: Atlantis p.115'),
('mystic-leech', 'Mystic Leech (Parasite)', 'rifts', 'magic', NULL, 250000, 'per leech; it must feed on at least 10 P.P.E. a day or starve in 24 hours', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A 5-inch (127 mm) leech living six years that gives its host nothing: it continuously drains 50 P.P.E. per leech until removed, leaves the victim -1 to strike, parry and dodge from vertigo, costs a psionic 5 I.S.P. per leech plus headaches, and fully debilitates a psi-stalker. The leech is +4 to save vs magic and +2 vs psionics. Removed by surgery; killing one releases a 3D6 M.D. energy eruption on everyone within 20 feet (6 m).', 'Rifts World Book 2: Atlantis p.115-116'),
('oplos', 'Oplos (Parasite, mated pair)', 'rifts', 'magic', NULL, 50000, 'for a mated pair; a male and female are needed', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Microscopic eye parasites (1/32 inch, 0.79 mm) that live a year and whose young multiply on. They give perfect hawk-like vision, nightvision 100 feet plus 100 feet per year, see the invisible, see aura and the full spectrum including infrared and ultraviolet; +1 initiative. The price: nightmares and hallucinations, a worsening crawling sensation in the eyes, a roll on the Random Insanity Table every two years after the second, and after ten years a maddening torment. Removal takes the eyes and optic nerves.', 'Rifts World Book 2: Atlantis p.116'),
('heart-worms', 'Heart Worms (Parasite)', 'rifts', 'magic', NULL, 250000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, '2D4 eggs injected into the heart of a mammal, human or D-Bee (not supernatural). The worms give +200 S.D.C. (30 M.D.C. to an M.D.C. being), +20 Spd, +6 P.S., +10 P.P.E., triple healing, rare fatigue, immunity to poison, drugs and disease, half damage and duration from gases, +3 to save vs magic and +10% vs coma/death - and devour the heart in 1D4+1 years, killing the host. Removal means replacing the heart with a cybernetic or bio-wizard one.', 'Rifts World Book 2: Atlantis p.116-117'),
('mind-slug', 'Mind Slug (Little Mindolar)', 'rifts', 'magic', NULL, 2000000, 'per slug', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A 4-inch (101 mm) parasite fixed to the temple that makes the host docile and obedient, charmed by the first person he sees: -6 to save vs psionics and mind control, -5 initiative, -10% skills, one fewer melee attack, and confusion when making decisions. It has 10 hit points, and every point of damage to it does 10 to the host. Removed by surgery or by killing it, with a 1-40% chance of a lasting slug phobia.', 'Rifts World Book 2: Atlantis p.116'),
('zombitron', 'Zombitron (Parasite, pair)', 'rifts', 'magic', NULL, 500000, 'for a pair; each must feed on an animal or die in 5 days', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A small crawling parasite (climb 82%, prowl 50%, 2 hit points, five-year life) that fastens to the head, neck or spine and puts its host into a zombie trance: he obeys commands, has one melee action and no combat bonuses, and a typical human starves in 1D4 months. The victim saves on 15 or higher each melee, -2 per zombitron beyond the first, with no save once entranced. Pulled off with gloves, tongs or a stick.', 'Rifts World Book 2: Atlantis p.116-117'),
('absurr-life-node', 'Absurr Life Node (Symbiote)', 'rifts', 'magic', NULL, 100000000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A grapefruit-sized symbiote with a two-foot tail that fuses to the base of the neck of an intelligent non-supernatural being and triples its life span. It has 1D6x100 M.D.C. of its own, makes its partner an M.D.C. being with 4D6x10+20 M.D.C., and can transfer its own M.D.C. to the partner. It warns of danger empathically, wakes the host, gives bursts of energy, and makes both impervious to mind control and empathic transmission; +2 to save vs psionic attack, +5 vs horror factor, +20% vs coma/death. Permanent: if either dies, both die.', 'Rifts World Book 2: Atlantis p.117-118'),
('chest-amalgamate', 'Chest Amalgamate (Chest Thing)', 'rifts', 'magic', NULL, 6000000, NULL, '4 attacks per melee: tentacle strike 2D6 S.D.C. restrained or 1D4 M.D.; bite 1D4 M.D. plus poison; chest-mouth bite 1D6 M.D. plus poison', 1, '5 feet (1.5 m) tentacle reach', NULL, NULL, NULL, NULL, NULL, 'A symbiote that attaches over the whole chest, sharing lungs, blood and nourishment, with 4D4x10+20 M.D.C. shared with the host and a 90-year life. It gives +1 initiative, +1 to strike and dodge, double speed, +1 melee attack, +4 ft leap, danger warning, no fatigue on four hours sleep, deadened pain, double healing, immunity to poison, drugs, gases and disease, +1 to save vs magic, +10% vs coma/death and 20 more years of life. Its poison bites add 6D6 S.D.C. (3D6 M.D.) or 2D6x10 S.D.C. (6D6 M.D.), save applies. Permanent deformity, +100 lbs, eats double and craves blood; removal kills the host.', 'Rifts World Book 2: Atlantis p.117-118'),
('elom', 'Elom (Symbiote)', 'rifts', 'magic', NULL, 25000000, NULL, 'Electromagnetic blast up to 6D6 M.D. in 1D6 increments (+3 to strike); area discharge up to 4D6 M.D. in a 20 ft (6.1 m) radius', 1, '2000 feet (610 m)', NULL, 'two attacks per melee, even if the host is unconscious', NULL, NULL, NULL, 'A baseball-sized symbiote attached to the spine, with 1D6x10 M.D.C. of its own (it does not make the host an M.D.C. being). It raises a 60 M.D.C. force field around the host for up to 20 minutes, up to 12 times a day, fires electromagnetic discharges, makes the host impervious to electrical attacks including ley line bolts, blocks P.P.E. drain by practitioners and vampires, and gives +1 to save vs magic. If it dies the host suffers as if it were removed surgically.', 'Rifts World Book 2: Atlantis p.118-119'),
('mindlink', 'Mindlink (Symbiote)', 'rifts', 'magic', NULL, 250000, 'plus 10,000 credits per communication program, up to eight; programs are permanent', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A silver-dollar-sized organism implanted in the brain that gives limited telepathy and mind block auto-defense; a psionic gains +30 I.S.P. and a non-psionic an I.S.P. base of M.E. x3. It is programmed for telepathic communication with up to eight races, groups or individuals. Ninety percent of those the Splugorth implant are secretly programmed to let the Splugorth and High Lords read the host''s mind, with no save. Removal loses every power and leaves minor scarring (-1 P.B.).', 'Rifts World Book 2: Atlantis p.119'),
('pathic-healer', 'Pathic Healer (Symbiote)', 'rifts', 'magic', NULL, 4000000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A hand-sized intelligent symbiote (living 200 years, with the healer psionic powers and 2D4x100 I.S.P.) worn on the head or chest of almost any being. It scans the body in 1D4 minutes and relays vital data telepathically, restores 1D6 hit points, gives +4 to save vs toxins and +20% vs coma/death, and gives attending healers +10% to their skills. It drains 1D4 P.P.E. from its partner every eight hours, and leaves if asked.', 'Rifts World Book 2: Atlantis p.119'),
('talo-mind-worms', 'Talo Mind Worms (Symbiote)', 'rifts', 'magic', NULL, 2000000, 'each; 5,500,000 for a mated pair', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Worms living under the scalp at the temples for 12 years; up to 20 can share a host. Each worm has 15 I.S.P. of its own and the powers bio-regenerate (self), psychic purification, resist fatigue, empathy, sixth sense, mind block auto-defense and summon inner strength, and gives the host an I.S.P. base of 12, plus 5 I.S.P. and 2 S.D.C. per worm The host is +1 to save vs psionic attack, +2 vs poison and +2% vs coma/death (not cumulative). Removed by surgery (-1 P.B.) or persuaded to leave.', 'Rifts World Book 2: Atlantis p.119-120'),
('psi-interrogator', 'Psi-Interrogator', 'rifts', 'magic', 6, 1000000, 'not generally available; 1 to 2 million credits when sold', 'Psionic only', 0, 'touch (telepathy at its normal range)', '140 I.S.P., regenerating 10 an hour; full recharge at a ley line nexus or pyramid; the organism lives 70 years', 'four psionic attacks per melee', NULL, NULL, NULL, 'A thorny pod that releases four tentacles, used for interrogation and torture, with the powers of a sixth level master psionic (victims save on 15 or higher): bio-manipulation, empathic transmission, mind bond (relayed to its operator), mind wipe, induce sleep, psychic diagnosis, psychic surgery and telepathy. An indestructible magic item.', 'Rifts World Book 2: Atlantis p.120'),
('psionic-rod', 'Psionic Rod (Scepter)', 'rifts', 'magic', 7, 2000000, 'not generally available; 2 to 12 million credits when sold', '1D4 M.D. blunt plus P.S. bonus; psi-sword; mind bolt', 1, 'varies by power', '92 I.S.P., regenerating 10 an hour; full recharge at a ley line nexus or pyramid; the Zembahk inside lives 100 years and can be replaced', 'four psionic attacks per melee', NULL, NULL, NULL, 'A 3-foot (0.9 m) scepter powered by a captive Zembahk, with sixth level psionic powers (save 15 or higher): psi-sword, telekinetic force field, mind bolt, telepathy at double range, the minor sensitive powers mind block, sense evil, sense magic and sixth sense, and the minor physical powers alter aura, ectoplasm and impervious to cold and fire. Indestructible.', 'Rifts World Book 2: Atlantis p.120-121'),
('staff-of-pacification', 'Staff of Pacification', 'rifts', 'magic', 12, 10000000, 'not generally available; 10 to 40 million credits when sold; a replacement containment unit costs 500,000 (in Atlantis only) and a Zembahk 600,000 to 1,000,000', '2D6 M.D. blunt plus P.S. bonus; energy bolt 4D6 S.D.C. (2 P.P.E.) or 2D6 M.D. (4 P.P.E.), +3 to strike', 1, 'energy bolt 2000 feet (610 m); other spells 10 to 60 feet (3 to 18.3 m)', '80 P.P.E., regenerating 10 an hour; full recharge at a ley line nexus or pyramid; the Zembahk lives 150 years', 'three spell attacks per melee; energy bolts separately, one per hand to hand attack', NULL, NULL, 50, 'A staff powered by a lobotomized Zembahk, casting as a fifth level wizard (save 13 or higher): energy bolt, agony, blind, mute, paralysis: lesser, domination, trance, befuddle and magic net. The housing has 50 M.D.C. and the Zembahk 70 (a called shot at -3); destroying the housing ends its powers.', 'Rifts World Book 2: Atlantis p.121'),
('staff-of-power', 'Staff of Power', 'rifts', 'magic', 25, 10000000, 'not generally available; 10 to 60 million credits when sold; a replacement containment unit costs 750,000 and a Zembahk 600,000 to 1,000,000', '5D6 M.D. blunt plus P.S. bonus', 1, '10 to 300 feet (3 to 91 m)', '160 P.P.E., regenerating 20 an hour; full recharge at a ley line nexus or pyramid; each Zembahk lives 150 years', 'two kinds of magic per melee', NULL, NULL, 100, 'A staff powered by two Zembahk, casting as a fifth level wizard (save 13 or higher): heal wounds, words of truth, sleep, shadow meld, call lightning, energy disruption, mystic portal, negate magic and anti-magic cloud. The housing has 100 M.D.C. and each Zembahk 70 (a called shot at -1).', 'Rifts World Book 2: Atlantis p.121'),
('staff-of-eylor', 'Staff of Eylor (Slaver''s Eye Staff)', 'rifts', 'magic', 20, 10000000, 'not generally available; 10 to 40 million credits when sold', '3D6 M.D. blunt plus P.S. bonus', 1, '10 to 300 feet (3 to 91 m)', '100 P.P.E., regenerating 20 an hour; full recharge at a ley line nexus or pyramid', 'two kinds of magic per melee', NULL, NULL, 150, 'A staff topped by a soccer-ball-sized Eye of Eylor that forms a permanent symbiotic bond with its owner within 72 hours of willing use; it is intelligent (I.Q. 3D4+2) and evil, and its owner loses 10 hit points for every M.D.C. it takes. Casts twice a day each at eighth level (save 14 or higher): extinguish fire, repel animals, fear, chameleon, befuddle, call lightning, energy disruption, dispel magic barriers, negate magic, tongues and oracle. It returns to its owner within 24 hours if lost or stolen and heals 1 M.D.C. a day. Not indestructible: 150 M.D.C., called shot at -2.', 'Rifts World Book 2: Atlantis p.122'),
('staff-of-all-seeing', 'Staff of All Seeing', 'rifts', 'magic', 12, 6000000, 'not generally available; 6 to 24 million credits when sold; a replacement containment unit costs 500,000 and a Zembahk 600,000 to 1,000,000', '2D6 M.D. blunt plus P.S. bonus', 1, 'the wielder only', '80 P.P.E., regenerating 10 an hour; full recharge at a ley line nexus or pyramid; the Zembahk lives 150 years', 'two kinds of magic per melee', NULL, NULL, 50, 'A Zembahk-powered staff casting as a fifth level wizard on its wielder: detect concealment, see aura, see the invisible, eyes of Thoth, eyes of the wolf, oracle, sense magic, sense evil and tongues. The housing has 50 M.D.C. and the Zembahk 70 (a called shot at -3).', 'Rifts World Book 2: Atlantis p.122'),
('telepathic-holographic-imager', 'Telepathic Holographic Imager', 'rifts', 'magic', 50, 2000000, 'not generally available; 2 to 8 million credits when sold', NULL, 0, '10 feet (3 m)', 'draws on its user''s P.P.E. or I.S.P., or ambient energy', NULL, NULL, NULL, NULL, 'A device with a simple plant-like intelligence (2D4 M.D.C.) that turns thoughts into three-dimensional holographic images: 65% accurate, 85% for something familiar, and 100% with total recall.', 'Rifts World Book 2: Atlantis p.122-123'),
('overlord-power-armor', 'Overlord Power Armor', 'rifts', 'armor', 30, 3000000, 'not generally available; 3 to 9 million credits when given or sold. Repairs by a Splugorthian alchemist cost 150,000 credits per 10 M.D.C.', NULL, 1, 'self', '180 P.P.E. (120 in the body, 60 in the helmet), regenerating 10 an hour; full recharge at a ley line nexus or pyramid', 'two kinds of magic per melee', NULL, NULL, 230, 'Magic environmental body armor made for the Kydians, the Splugorth Overlords and Powerlords: 230 M.D.C. plus magic, excellent mobility (-5% prowl). Three stones cast as a fifth level wizard on the wearer (save 13 or higher): fly as the eagle, swim as the fish, breathe without air, superhuman speed, escape; shadow meld, invisibility: superior, charismatic aura, impervious to energy, energy field; see the invisible, sense magic, tongues, heal wounds (self) and negate poison (self).', 'Rifts World Book 2: Atlantis p.123'),
('symbiotic-weapon-modification', 'Symbiotic Weapon Modification', 'rifts', 'magic', NULL, 100000000, '100 million credits or more, or a trade of services; seldom made available even to minions', '+1D6 M.D. to the weapon', 1, NULL, 'unlimited', NULL, NULL, NULL, NULL, 'A baseball-sized Eye of Eylor fused to any weapon, rune weapons included, linking it to one owner: the weapon gains a pseudo-intelligence, flies to its owner''s hand from up to 40 miles (64 km), casts teleport: lesser, levitate and shadow meld at will, and does +1D6 M.D. It cannot attack on its own, and no one but its linked owner can use it (it re-links if the owner dies).', 'Rifts World Book 2: Atlantis p.125'),
('eylor-helm-of-omnipotence', 'Eylor Helm of Omnipotence', 'rifts', 'magic', NULL, NULL, 'No price printed.', NULL, 0, NULL, '400 P.P.E. by the closing sentence; the introduction to the same entry says 1150', 'three spell attacks per melee in addition to the wearer''s own', NULL, NULL, 200, 'A helm set with a basketball-sized Eye of Eylor and three baseball-sized eyes on each side; evil (usually aberrant), Horror Factor 16. The sphere has 200 M.D.C. and the eye 120, and it adds 50 M.D.C. to its wearer, with the Eyes of Eylor optics, abilities and psionics. It casts 30 spells three times a day each at eighth level: eyes of the wolf, see the invisible, see aura, detect concealment, oracle, breathe without air, invulnerability, teleport: lesser, time slip, escape, shadow meld, fly as the eagle, negate magic, dispel magic barrier, metamorphosis: human, mask of deceit, heal wounds, cure illness, exorcism, constrain being, turn dead, animate and control dead, domination, life drain, fire ball, call lightning, wisps of confusion, minor curse, sickness and spoil. The book prints two P.P.E. figures for it (1150 and 400).', 'Rifts World Book 2: Atlantis p.125');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'the 33 bio-wizardry rows are in' AS assertion, count(*) AS got, 33 AS want
  FROM gear WHERE slug IN ('aerobes', 'aquarobes', 'clotrobes', 'dehibicila', 'dragoncila', 'plastirobes', 'purirobes', 'stasirobes', 'transfortifiers', 'watrobes', 'brain-feeder', 'lobee-optos', 'mystic-leech', 'oplos', 'heart-worms', 'mind-slug', 'zombitron', 'absurr-life-node', 'chest-amalgamate', 'elom', 'mindlink', 'pathic-healer', 'talo-mind-worms', 'psi-interrogator', 'psionic-rod', 'staff-of-pacification', 'staff-of-power', 'staff-of-eylor', 'staff-of-all-seeing', 'telepathic-holographic-imager', 'overlord-power-armor', 'symbiotic-weapon-modification', 'eylor-helm-of-omnipotence') AND source_book LIKE 'Rifts World Book 2: Atlantis p.%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-atlantis-bio-wizardry.sql');
