-- The Cyclops R.C.C., Palladium Fantasy RPG Book 9: The Baalgor Wastelands p.38-41.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-cyclops-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'cyclops', 'Cyclops', 'palladium-fantasy', '---
id: cyclops
men_of_arms: false
name: Cyclops
system: palladium-fantasy
source_book: Palladium Fantasy RPG Book 9: The Baalgor Wastelands p.38-41
category: rcc
tags: []
attribute_dice:
  IQ: "3d6"
  ME: "2d6"
  MA: "4d6"
  PS: "5d6+2"
  PP: "4d6"
  PE: "4d6"
  PB: "2d6"
  Spd: "2d6"
hit_points_base: "P.E. + 1D6 per level"
ppe_base: "P.E. attribute number +1d6x10"
yields_to_occupation: { ppe_base: [magic] }
horror_factor: 12
skills:
  occ_skills:
    - { name: "Language: Troll/Giant", base: 98, per_level: 0, note: "Every Cyclops speaks the Troll/Giant tongue. The book prints no percentage; stored as a fluent 98%." }
    - { choose: 1, from: ["Language: Other"], bonus: 48, note: "Western Human, which every Cyclops speaks. Taken as Language: Other - the picker asks which. The book prints no percentage; stored as a fluent 98%." }
    - { choose: 1, from: ["Literacy: Dragonese/Elven", "Literacy: Other"], bonus: 10, note: "About 40% of Cyclops are literate in Elven and/or Western Human or another language (+10%). Skip this pick for a Cyclops who is not." }
bonuses:
  pools: { sdc: 50 }
  combat: { attacks_base: 2, pull_punch: 4, roll: 2 }
  saves: { horror_factor: 3 }
natural_abilities:
  - name: "Giant Damage"
    description: "Section rule for true giants, printed 40. Unless the giant''s own entry says otherwise: a restrained open-handed slap does 1D6 damage, a restrained punch 2D4, a full-strength punch 2D6 plus P.S. damage bonus, and a power punch 4D6 plus P.S. damage bonus (counts as two attacks); or by weapon or magic."
  - name: "Giant Bonuses (section rule)"
    description: "Printed 40 says that, in addition to attribute and skill bonuses, most giants are also +1 on initiative, +2 to pull punch, +1 to roll with impact or fall, +3 to save vs Horror Factor, and +1 to save vs poison, drugs and disease. This giant''s own Bonuses line is what the sheet adds; the section line is given here for the G.M. to rule on."
  - name: "Natural Armor Rating"
    description: "Natural A.R. 5."
  - name: "Superior Strength and Endurance"
    description: "Superior physical strength and endurance. Two attacks per melee at the least, or those of the O.C.C. and combat skills."
  - name: "Nightvision"
    description: "60 feet (18.3 m); can see in total darkness. Good overall vision and hearing."
  - name: "Energy Resistance"
    description: "Impervious to lightning and electricity, magic electricity included. Every other form of energy does half damage, except kinetic energy, which does full damage."
  - name: "Lightning Shafts (magic)"
    description: "About one Cyclops in three (33%) can make magic lightning javelins and arrows. Javelins, jagged rods pointed at both ends and 6 to 10 feet (1.8 to 3 m) long: light 4D6 damage (650-1,000 gold), medium 7D6 (1,000-1,500 gold), heavy 1D6x10 (1,600-2,400 gold; rare), super 2D4x10 (2,000-5,000 gold; super-rare). Thrown range 1,000 feet (305 m), or 2,000 feet (610 m) from the hand of a Cyclops. Arrows, made to fit short bows, long bows or crossbows: light 3D6 damage (300-500 gold), heavy 6D6 (800-1,200 gold); range 200 feet (61 m) beyond the bow''s own, 600 feet (183 m) beyond it for a Cyclops. A shaft is used once: it becomes a real lightning bolt in flight and is gone after it strikes. Roll to strike as usual with +1."
restrictions:
  - "Magic by O.C.C. Psionics are standard, the same as humans."
extraction_notes: |
  - Printed 38-41. The Giants section opens on printed 38, its shared combat paragraph is at the top of printed 40, the Cyclops entry starts on printed 40 and its block, headed "Giant Humanoid", runs to Favorite Weapons on printed 41. Printed 39 is a full-page illustration. Folios read off the renders.
  - Attributes as printed on 40: I.Q. 3D6, M.E. 2D6, M.A. 4D6, P.S. 5D6+2, P.P. 4D6, P.E. 4D6, P.B. 2D6, Spd 2D6. Hit Points "P.E. +1D6 per level of experience".
  - S.D.C. reads "50 plus those gained from O.C.C. and physical skills", so the 50 is a pool bonus and no sdc_base is stated.
  - Average P.P.E. reads "1D6x10 plus P.E. attribute number or by magic O.C.C.": stored as ppe_base, yielding to a magic occupation''s own figure. The page names magic O.C.C.s only, so clergy is not in the yield.
  - Horror Factor 12 is stored as horror_factor. Natural A.R. 5 is a natural ability.
  - Attacks per Melee reads "Two minimum or by O.C.C. and combat skills": stored as attacks_base 2.
  - Bonuses as printed on 41: +3 to save vs Horror Factor, +4 to pull punch, +2 to roll with impact. Stored.
  - SECTION RULE, printed 40 ("Special Combat Considerations and Bonuses"): the damage figures are the natural ability Giant Damage. The same paragraph says "most giants are also" +1 initiative, +2 pull punch, +1 roll with impact or fall, +3 save vs Horror Factor and +1 save vs poison, drugs and disease. It says "most", and every giant''s own Bonuses line restates part of that list with its own numbers, so the section list is NOT added to bonuses on any of the four giants; it is the natural ability Giant Bonuses (section rule), in the same words on each.
  - O.C.C.s Available: "Any, without restriction, although most lean toward Men of Arms", so no occ_restrictions. Printed 215: giants use the experience table of their chosen O.C.C., so no xp_table.
  - Skill Notes and Bonuses: "All Cyclops speak Troll/ and Western Human" - the word after the slash is missing in print and is read as Troll/Giant. No percentage is printed for either tongue; both are stored at 98 as this import''s reading of a spoken native tongue. The catalog holds no Western Human language row, so it is a one-pick Language: Other group. The 40% literacy is a one-pick literacy group at the printed +10%.
  - The lightning shafts are prose: making them belongs to a third of the race, and the +1 to strike applies only with a shaft.
  - No money or equipment line is printed for the race; none is stated.
  - Size 14 feet plus 1D4 additional feet, 600 to 1,000 pounds; life span 600 years, some to 1,000. In the Lore.
---

# Cyclops

## Lore

The Cyclops are one-eyed giants whose line is said to reach back to the Age of Chaos. No other people knows how to make lightning javelins and arrows, and the trade in those weapons has made them rich enough to keep a kingdom of their own on the Isle of the Cyclops, west of the Western Empire. Anyone else who learns the art is said to be visited by greater demons and made an example of.

In the Baalgor Wastelands they are the rarest of the giants: exiles from the Isle, or ambitious ones who came looking for a bigger share. Most serve the Nimro as military advisors and makers of magic arms; a few lead mixed bands of bandits, pirates and mercenaries, or dig through old ruins after lost magic.

**Alignment:** Any, but leans toward anarchist and evil.

**Physical Appearance:** Olive-skinned giants with a single large eye in the middle of the head and, usually, long dark hair. They favor togas and fine silk, and gold and gem jewelry.

**Size:** 14 feet plus 1D4 additional feet (4.6 to 5.5 m). **Weight:** 600 to 1,000 pounds (270 to 450 kg).

**Average Life Span:** 600 years; some have reached 1,000.

**Habitat:** Anywhere, but mostly the Wastelands, the Old Kingdom and the Great Northern Wilderness, with a few living as free citizens of the Western Empire and thousands on the Isle of the Cyclops.

**Enemies:** Changelings, Titans and Trolls by tradition. Cyclops and Gigantes detest one another and feud constantly.

**Allies:** Kobolds (who often worship them), Nimro, Ogres and dragons. Indifferent to most others.

**Favorite Weapons:** Their own lightning weapons and magic arms and armor of every kind; also plain javelins, spears, bows and large swords.

## GM Notes

Cyclops are more civilized than their reputation, but they bully anything smaller, and most are greedy for wealth, standing and power. They prefer their own lightning weapons and also love rune weapons, magic armor and magic items. Only about a third of them can actually make lightning shafts, so a player Cyclops with that secret is a decision for the table.

The Isle supplies lightning weapons to the Empire of Sin and is on friendly terms with the Western Empire, and its dealings with the Nimro Kingdom are kept secret from the Western Empire; the story for outsiders is that any such weapon in a Baalgor giant''s hands came from a rogue. That lie is a ready-made plot.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'cyclops');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'cyclops';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-cyclops-class.sql');
