-- New West bionics: the Mining 'Borg attachments and the other bionic items.
-- Printed 187-189. Twenty-five new rows, all category 'cybernetics'.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-new-west-gear-b-bionics.sql
--
-- READ OFF RENDERS OF PRINTED 187-189, per the rule this book's gear pages
-- established in add-new-west-gear-a-bandito.sql. These three pages are the
-- shape book-survey 0e warns about: priced entries buried in prose, with the
-- Cost: label sitting mid-paragraph rather than on a line of its own.
--
-- ALL 25 ARE NEW. catalog-diff --table gear --remote on 2026-09-10 returned
-- 25 missing and 0 matched against 1264 rows, and the generic-sounding ones
-- were checked a second time by hand against the 29 existing cybernetics rows,
-- because a near-miss on a name like Combat Computer or Prehensile Tail is
-- exactly how a duplicate gets in: no cybernetics row in the catalog has
-- Computer, Tail, Anchor, Plating or Jet in its name at all.
--
-- CHEMICAL SPRAY CARRIES NO PRICE AND NONE IS INVENTED. It is the one entry in
-- the section the book gives no Cost: line for, so cost and cost_note are NULL.
-- It is imported anyway because it is a listed attachment with stats.
--
-- THE EXTRA APPENDAGES ARE TWO ROWS, NOT ONE. The book runs the prehensile
-- tail and the extra pair of arms together under a single heading and then
-- prices them separately - 200,000-220,000 against 250,000 - with different
-- M.D.C. So they are split, and each carries the shared heading in its
-- description.
--
-- EXTRA ARMOR PLATING HAS NO SINGLE PRICE. The book says "varies", then gives
-- a rate: about 1,500 credits per two points of M.D.C., and 75,000 for 100
-- M.D.C. The rate is stored in cost_note and cost holds the 75,000 the book
-- works out itself, rather than a figure nothing in the book states.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('chemical-spray', 'Chemical Spray', 'rifts', 'cybernetics', NULL, NULL, NULL, '4D6 S.D.C.', 0, NULL, 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, NULL, 'A Mining cyborg attachment. Typically an acid used for cleaning metal ores, but it can also carry other chemicals such as foam for putting out fires. Can be built into the hand, chest or mouth of a full conversion cyborg. THE BOOK PRINTS NO PRICE for this entry and none is invented. Like the rest of the mining attachments it is a TOOL: it can be used as a hand to hand weapon but is not intended for combat.', 'Rifts World Book 14: New West p.187'),
('forearm-attachment-high-powered-flashlight', 'Forearm Attachment: High-Powered Flashlight', 'rifts', 'cybernetics', NULL, 1000, '1,000 credits', NULL, 0, '600 feet (183 m) as a narrow beam, or 60 feet (18.3 m) as a wide beam', 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, NULL, 'A Mining cyborg attachment. The light beam adjusts between a narrow beam and a wide one covering a 20 foot (6 m) arc. It can also be mounted on the cyborg head, and can be conventional light or infrared.', 'Rifts World Book 14: New West p.187'),
('modular-hand-housing', 'Modular Hand Housing', 'rifts', 'cybernetics', NULL, 5000, '5,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A bionic housing that enables the cyborg to use a variety of interchangeable hands. It is the fitting the modular hands below plug into.', 'Rifts World Book 14: New West p.187'),
('modular-arm-housing', 'Modular Arm Housing', 'rifts', 'cybernetics', NULL, 8000, '8,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A bionic housing that enables the cyborg to use a variety of interchangeable forearms. It is the fitting the modular forearm attachments below plug into.', 'Rifts World Book 14: New West p.187'),
('modular-hand-laser-hand', 'Modular Hand: Laser Hand', 'rifts', 'cybernetics', NULL, 36000, '36,000 credits each', 'Four settings: 6D6 S.D.C., 1D4 M.D., 1D6 M.D. and 2D6 M.D.', 1, '8 feet (2.4 m)', 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 35, 'A Mining cyborg attachment. The first two fingers of the hand are precision cutting lasers similar to the laser scalpel, used for repairs, welding and cutting. M.D.C. 35 per hand.', 'Rifts World Book 14: New West p.187'),
('modular-hand-shovel-hand', 'Modular Hand: Shovel Hand', 'rifts', 'cybernetics', NULL, 35000, '35,000 credits each', '1D4 M.D. as a digging, stabbing or chopping weapon', 1, NULL, NULL, NULL, NULL, NULL, 50, 'A Mining cyborg attachment. Large hands with thick, strong fingers that taper at the fingertips; with the hand open and flat and the fingers pressed together it serves as both a shovel and a chisel. M.D.C. 50 per hand. PENALTY: skills requiring precision use of the hands and the use of small tools are -15%.', 'Rifts World Book 14: New West p.187'),
('modular-hand-vibro-monster-claw-hand', 'Modular Hand: Vibro-Monster Claw Hand', 'rifts', 'cybernetics', NULL, 45000, '45,000 credits per each hand', '3D6 M.D. as a weapon', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'A Mining cyborg attachment. An oversized hand with three thick fingers and a thumb, the last digit being a large hooked claw resembling a mechanical talon, used for crushing, clawing and digging through packed earth, clay and rock. PENALTY: this is not a good hand for precision work or even picking up objects; -20% on ALL skills.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-air-blaster', 'Modular Forearm Attachment: Air Blaster', 'rifts', 'cybernetics', NULL, 66000, '66,000 credits', 'From zero to 1D6 S.D.C., up to one M.D. as a sand blaster and rock splitter', 1, 'One foot (0.3 m)', 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 40, 'A Mining cyborg attachment. A high-powered air gun with several nibs and nozzles covering a range of work: a gentle puff to clean delicate electronics, machine mechanisms, bones or artifacts; stronger blasts to blow away rock and debris; and hammering blasts to break fractured rock and to sandblast. M.D.C. 40 per arm. The blast also has a 01-60% chance of knocking human-sized opponents off their feet, losing initiative and one melee action.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-jackhammer', 'Modular Forearm Attachment: Jackhammer', 'rifts', 'cybernetics', NULL, 60000, '60,000 credits', '2D6 M.D. as a hammering weapon', 1, NULL, 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 50, 'A Mining cyborg attachment. In place of a hand and forearm is a heavy-duty jackhammer designed to break rock into small pieces, typically used on rock that has already been drilled, or for the construction or demolition of buildings. M.D.C. 50 per jackhammer arm. It does NOT have the focused penetrating power of a drill.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-multi-tool', 'Modular Forearm Attachment: Multi-Tool', 'rifts', 'cybernetics', NULL, 88000, '88,000 credits each', 'Retractable chain saw 1D6x10 S.D.C. or 1D4 to 2D4 M.D.; circular saw 1D4x10 S.D.C. or one M.D.; retractable drill 1D6, 2D6 or 3D6 S.D.C.; welding torch 1D6 to 2D6 S.D.C.; laser rod 1D6 M.D.; power nailer 1D4 S.D.C.', 1, 'Laser rod 800 feet (224 m); utility laser 10 feet (3 m); flashlight finger 20 feet (6 m); power nailer 20 feet (6 m)', 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 25, 'A Mining cyborg attachment, and the most crowded of them. A light work and utility arm and hand. The hand (25 M.D.C.) has four fingers and a thumb: one finger is a flashlight, one is a utility laser doing 1D4, 1D6 or 3D6 S.D.C., and on top of the hand is a sensor unit equal to a sensor hand. Mounted on the forearm are a retractable chain saw, a circular saw, a small retractable drill and a retractable rod-style welding torch, plus an E-Clip arm port, a concealed retractable laser rod and a concealed retractable power nailer.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-heavy-mining-drill', 'Modular Forearm Attachment: Heavy Mining Drill', 'rifts', 'cybernetics', NULL, 66000, '66,000 credits', '3D6 M.D. as a drill weapon', 1, NULL, 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 50, 'A Mining cyborg attachment. In place of a hand and forearm is a huge, powerful looking drill for making large holes in rock and metal - a man can fit his arm through them and still have room - and for drilling away rock. A handful of detachable drill bits in a variety of large sizes are available. M.D.C. 50 per drill arm.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-precision-mining-drill', 'Modular Forearm Attachment: Precision Mining Drill', 'rifts', 'cybernetics', NULL, 60000, '60,000 credits', 'Three settings: 4D6 S.D.C., 1D4 M.D. and 2D4 M.D. as a drill weapon', 1, NULL, 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 30, 'A Mining cyborg attachment. In place of a hand and forearm is a thin, narrow, high-powered drill for making small holes and precision drilling, with detachable bits in a variety of sizes. Suits mining and building or construction work. M.D.C. 30 per drill arm.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-plasma-torch', 'Modular Forearm Attachment: Plasma Torch', 'rifts', 'cybernetics', NULL, 75000, '75,000 credits each', 'Four settings: 1D6x10 S.D.C., 1D6 M.D., 2D6 M.D. and 4D6 M.D.', 1, '3 feet (0.9 m)', 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 45, 'A Mining cyborg attachment. In place of an arm and hand is a versatile plasma torch used for repairs, welding and cutting. M.D.C. 45 per unit.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-and-hand-attachment-sonic', 'Modular Forearm & Hand Attachment: Sonic', 'rifts', 'cybernetics', NULL, 52000, '52,000 credits', 'None', 0, 'Sonic imaging 1000 feet (305 m); built-in metal detector 3 feet (0.9 m)', 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, NULL, 'A Mining cyborg attachment. A sonic pulse and scanner system for reading images of what lies underground, with a built-in metal detector. It does NO damage - it is purely a sensor.', 'Rifts World Book 14: New West p.188'),
('modular-forearm-attachment-vibro-pick', 'Modular Forearm Attachment: Vibro-Pick', 'rifts', 'cybernetics', NULL, 24000, '24,000 credits', '2D6 M.D. as a digging or chopping weapon', 1, NULL, 'Effectively unlimited; the tool draws on the power supply of the cyborg', NULL, NULL, NULL, 35, 'A Mining cyborg attachment. In place of a hand is a classic pickaxe. M.D.C. 35 per hand. The cheapest of the mining attachments.', 'Rifts World Book 14: New West p.188'),
('boosters-and-maneuvering-jets', 'Boosters and Maneuvering Jets', 'rifts', 'cybernetics', NULL, 18000, '18,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Small jets built into the feet, lower legs, back and shoulders of full conversion cyborgs, used to help the cyborg maintain balance as well as buoyancy in water. They can actually propel the character underwater at a sluggish speed of three knots per hour.', 'Rifts World Book 14: New West p.189'),
('combat-computer', 'Combat Computer', 'rifts', 'cybernetics', NULL, 150000, '150,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A marvel of computer miniaturization and human/machine integration. Using whatever sensors and sensory abilities the cyborg has, the combat computer gathers and analyzes data and sends it to the brain, where it is translated into enhanced reflexes and response time. BONUSES: +1 on initiative, +1 to dodge, +1 to disarm, +2 to pull punch, and +2 to roll with punch, fall or impact.', 'Rifts World Book 14: New West p.189'),
('customized-paint-job', 'Customized Paint Job', 'rifts', 'cybernetics', NULL, 800, '800 to 3000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Basically the same as customizing body armour: special colours, designs, insignias and so forth, applied to a cyborg or robot body.', 'Rifts World Book 14: New West p.189'),
('customized-face-or-armored-plate', 'Customized Face or Armored Plate', 'rifts', 'cybernetics', NULL, 2000, '2,000 to 20,000 credits, depending on the complexity', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A cyborg face or faceplate made handsome, beautiful, monstrous, robotic, ornate, or whatever else the purchaser may desire.', 'Rifts World Book 14: New West p.189'),
('prehensile-tail', 'Prehensile Tail', 'rifts', 'cybernetics', NULL, 200000, '200,000 to 220,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, 30, 'A bionic extra appendage. 30 to 50 M.D.C., and it adds ONE EXTRA ATTACK per melee round. The book files it with the extra pair of arms under one Extra Appendage/Arms heading and then prices the two separately; see Rifts RPG pages 239 and 240 for the details. The M.D.C. column holds the lower of the two figures.', 'Rifts World Book 14: New West p.189'),
('extra-pair-of-arms-and-hands', 'Extra Pair of Arms and Hands', 'rifts', 'cybernetics', NULL, 250000, '250,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, 40, 'A bionic extra appendage: a second pair of arms and hands, human-like or tentacles. 40 to 80 M.D.C. per arm, and they add ONE EXTRA ATTACK per melee round. The book files this with the prehensile tail under one Extra Appendage/Arms heading and then prices the two separately; see Rifts RPG pages 239 and 240 for the details. The M.D.C. column holds the lower of the two figures.', 'Rifts World Book 14: New West p.189'),
('extra-armor-plating', 'Extra Armor Plating', 'rifts', 'cybernetics', NULL, 75000, 'Varies; typically about 1,500 credits per two points of extra M.D.C., which the book works out as 75,000 credits for 100 M.D.C.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Extra plating that can be added to any full conversion cyborg and to most robots. How much depends on the frame: small robots about the size of a dog can take as much as 30 M.D.C., man-sized 80 M.D.C., horse-sized robots as much as 150 M.D.C., and anything larger than horse-sized generally 200 M.D.C., which includes most large vehicles. THE BOOK STATES NO SINGLE PRICE - it gives a rate, and the cost column holds the 100 M.D.C. figure the book itself works out rather than a number nothing in the book states.', 'Rifts World Book 14: New West p.189'),
('quick-draw-holsters', 'Quick Draw Holsters', 'rifts', 'cybernetics', NULL, 10000, '10,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Compartments built into the legs of a cyborg that serve as holsters and holders for handguns, knives or sawed-off shotguns. On a mental command they literally spring into the waiting hands of the cyborg. BONUS: +1 on initiative with those weapons.', 'Rifts World Book 14: New West p.189'),
('stabilizing-anchors', 'Stabilizing Anchors', 'rifts', 'cybernetics', NULL, 5000, '5,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Like the Glitter Boy has: small spikes about 8 inches (0.4 m) long shoot out of the lower legs and into the ground to anchor the cyborg in place. Also used in construction and climbing.', 'Rifts World Book 14: New West p.189'),
('western-wilderness-survival-kit', 'Western Wilderness Survival Kit', 'rifts', 'cybernetics', NULL, 75000, '75,000 credits', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A survival kit packed into the secret compartment or compartments of a cyborg or robot body, said to have everything one could possibly need to survive. Contents: a pocket tool kit, 20 feet (6 m) of wire, 12 rubber bands, 6 safety pins, 6 sewing needles and a spool of thread, fishing line and hooks, a pocket mirror, 6 hand flares, a pocket knife, a laser scalpel, a cigarette lighter, a small flashlight, a small silver cross, a bottle of aspirin (50 tablets), an IRMSS kit, an RMK kit, a compass, and one week of dried food rations.', 'Rifts World Book 14: New West p.189');

-- Read the result back rather than trusting the exit code.
SELECT count(*) AS new_west_cybernetics FROM gear WHERE source_book LIKE 'Rifts World Book 14: New West%' AND category = 'cybernetics';
SELECT count(*) AS priced FROM gear WHERE source_book LIKE 'Rifts World Book 14: New West%' AND category = 'cybernetics' AND cost IS NOT NULL;

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-new-west-gear-b-bionics.sql');
