-- Free Quebec's own weapons, armor and harpoon ammunition, printed 44-51.
-- Seventeen new rows: ten weapons, three suits of body armor, one optic, and
-- the four harpoon types the QN-06 fires.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-free-quebec-gear.sql
--
-- The book has a TEXT LAYER, so every number here was read with the page's own
-- block geometry rather than from prose order. Two pages of this book are
-- WELDED across the gutter - printed 42 and 58, BOOK-INGEST-AUDIT.md F30 -
-- and NEITHER is in this range. The gear pages read in order.
--
-- WHAT IS DELIBERATELY NOT HERE, and it is most of printed 43-44. The book
-- lists the old-style CS weapons the Quebec Military uses - C-18, C-10, C-12,
-- C-14, C-27, CR-1, C-40R, CS Vibro-Blades, CS Neural Mace - and gives PAGE
-- NUMBERS INTO THE RIFTS RPG instead of stats. Same for Triax's TX-5, TX-11
-- and TX-26, Northern Gun's NG-P7, and the Urban Warrior, Plastic Man,
-- Huntsman and Bushman armor of printed 51-52. There is nothing to extract:
-- the book prints no figures for any of them.
--
-- THE GRENADES AND FLARES OF PRINTED 43-44 ARE ALREADY IN THE CATALOG, at the
-- prices this book prints. Checked --remote before writing this file:
-- Stun/Flash Grenade 100, Tear Gas Grenade 200, Flare 1, Parachute Flare 10,
-- Smoke Grenade, Fragmentation Grenade, Plasma Grenade 350 all exist and all
-- agree. Five rows this file would otherwise have duplicated.
--
-- THE Q4-44 "DRUMMER" PRINTS A BLACK MARKET PRICE TEN TIMES ITS OWN, and it is
-- recorded rather than corrected. Free Quebec sells it for 4,500 credits and
-- the book says the black market "should sell for 45,000-50,000" - the exact
-- figure it gives for the Q4-40 Mule two paragraphs earlier, which costs
-- 15,000. It reads like a copied line. The stored cost is the 4,500 the book
-- states outright; the cost_note carries the black market figure AS PRINTED
-- and says it is suspect. A guess at what was meant would be indistinguishable
-- from a number the book gave.
--
-- A PRICE RANGE STORES ITS LOW END in cost with the range in cost_note.
--
-- INSERT OR IGNORE THROUGHOUT, and the readback COUNTS rather than trusting
-- the exit code - an IGNORE that collides is silent, which is exactly how a
-- row goes missing without an error.
--
-- Sorts between add-first-stage-promethean-class.sql and
-- add-freedom-fighter-class.sql - checked against the directory. It depends on
-- nothing and nothing in the directory depends on it; the Free Quebec class
-- scripts are written AFTER this is applied --remote, so class-check sees
-- these rows and emits no stubs for them.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('fq-mini-hud-system', 'Mini-HUD System', 'rifts', 'gear', 1, 15000, 'Free Quebec cost 15,000 credits. Military-exclusive and unknown to outsiders; the book states that if it is ever knocked off it will sell for at least 35,000 credits on the black market', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A mini Head Up Display co-developed with Triax that fits most rifles like a scope, used either as a multi-optics sight or linked directly to the wearer''s helmet. Provides telescopic, passive nightvision, infrared and thermo-imaging enhancement plus exact distance, angle and targeting hairs on the face plate. Bonuses: +1 on initiative and +2 to strike with long-range weapons, in addition to any W.P. bonuses. Experimental, and issued only on assignment to Special Forces, Commandos, Rangers and snipers.', 'Rifts World Book 22: Free Quebec p.44'),
('q1-01-laser-pistol', 'Q1-01 Laser Pistol', 'rifts', 'weapon', 3.5, 10000, 'Free Quebec cost 10,000 credits; the black market has obtained only a few and sells them for around 16,000', '3D4 M.D. per single shot, or 4D6 M.D. per short burst (counts as one attack but fires four blasts)', 1, '800 feet (244 m)', '20 shots per standard E-Clip or 30 shots per long E-Clip', 'Standard: aimed, short burst, or wild (3D4 M.D.)', NULL, NULL, NULL, 'The "Que-One-Oh-One", standard issue sidearm of the Free Quebec Military, issued to officers, guards and Special Operatives. Heavier damage than its weight and balance suggest, without sacrificing range.', 'Rifts World Book 22: Free Quebec p.44-45'),
('q1-02-stopper-ion-pistol', 'Q1-02 "Stopper" Ion Pistol', 'rifts', 'weapon', 4.5, 12000, 'Free Quebec cost 12,000 credits. Not available on the black market; the book estimates 18,000-20,000 when it is', '4D6+4 M.D. per single blast; cannot fire bursts', 1, '200 feet (61 m)', '12 shots per standard E-Clip or 24 shots per long E-Clip', 'Semi-automatic, equal to the hand to hand attacks of the shooter; each shot counts as one melee action', NULL, NULL, NULL, 'A heavy energy pistol representing a partial breakthrough in Quebec weapon technology. Two major drawbacks: terrible range and considerable weight. Commandos, Special Forces, Juicers and Cyborg troopers favour it for close combat.', 'Rifts World Book 22: Free Quebec p.45'),
('q2-10-laser-pulse-rifle', 'Q2-10 Laser Pulse Rifle', 'rifts', 'weapon', 6, 16000, 'Free Quebec cost 16,000 credits. Not yet available on the black market; the book estimates 22,000-24,000 when it is', '1D6, 2D6 or 3D6 M.D. per individual shot depending on the setting, or 6D6+6 M.D. per short burst (counts as one attack but fires five blasts)', 1, '2000 feet (610 m)', '20 shots per standard E-Clip or 30 shots per long E-Clip', 'Standard: aimed, short burst, or wild (3D6 M.D.)', NULL, NULL, NULL, 'A durable three-setting laser that fires single shots for precision work and sniping, or automatic bursts of five. Comes with a telescopic scope as standard and can take the Mini-HUD System.', 'Rifts World Book 22: Free Quebec p.45'),
('q2-20-llg-infantry-standard', 'Q2-20 LLG "Infantry Standard"', 'rifts', 'weapon', 7, 26000, 'Free Quebec total cost 26,000 credits with Vibro-Bayonet, one E-Clip and 36 grenades. Not yet on the black market; the book estimates around 40,000 there, with grenades at 550 apiece or 4,500 a dozen', 'Laser: 3D6 M.D. per single shot or 6D6 M.D. per short burst (one melee attack, five blasts). Mini-Grenade Launcher: high explosive 4D6 M.D. to a 6 foot (1.8 m) area, or a concussion charge doing 2D6 M.D. and knocking everything within 15 feet (4.6 m) off its feet. Vibro-Bayonet: 2D4 M.D. per strike', 1, 'Laser 2000 feet (610 m); grenade launcher 1100 feet (335.5 m); bayonet within reach', 'Laser 20 shots per short (standard) E-Clip or 30 per long E-Clip. Grenade launcher holds four rifle grenades; troops typically carry 32 more plus the four in the gun', 'Laser standard: aimed, short burst, or wild. Grenades one at a time or in volleys of two. Bayonet equal to the hand to hand attacks of the user', NULL, NULL, NULL, 'The Light Laser and Grenade Launcher, inspired by the CS "Fire Breather" and standard issue for all Free Quebec Infantry. A Vibro-Blade bayonet mounts to the lower barrel on a magnetic-lock housing and the Mini-HUD can be fitted. Weighs 7 lbs (3.2 kg) bare, 8 lbs (3.6 kg) with the Mini-HUD and 9 lbs (4 kg) with the bayonet. A variant with slightly different styling is used by the Quebec Navy. Reloading one grenade is one melee action and all four is four.', 'Rifts World Book 22: Free Quebec p.45-47'),
('q2-30-rapid-fire-heavy-laser', 'Q2-30 Rapid-Fire Heavy Laser', 'rifts', 'weapon', 24, 35000, 'Free Quebec cost 35,000 credits; fair to poor availability. Not yet on the black market; the book estimates 65,000-75,000 when it is', '3D6 M.D. per single shot; 6D6 M.D. per short burst of five; 1D6x10 M.D. per medium burst of 20 (two melee actions); 2D6x10 M.D. per long burst of 40 (two melee actions); 4D6x10 M.D. when the whole 80-shot payload is emptied into one target, or 3D6 M.D. to 4D4 targets when sprayed', 1, '3000 feet (914 m)', '80 shots total: 20 from the standard E-Clip and 30 each from two long E-Clips. A portable 50 lb (22.5 kg) power pack adds 120 more', 'Standard Modern Weapon Proficiency combat', NULL, NULL, NULL, 'A heavy long-range laser the size and weight of a rail gun, used like a light machinegun and also mounted on hover jeeps and trucks or fired from a tripod. Experimental, designed with Cyborg Shock Troopers, Juicers and power armor in mind. AN ORDINARY SOLDIER NEEDS P.S. 22 OR HIGHER: below that the shooter is -2 to strike and takes twice as long to reload. Strike bonuses come only with the W.P.: +3 on a single shot, +2 on a short burst, +1 on a medium or long burst, none on a full-payload discharge. Weighs 24 lbs (10.8 kg) loaded, 26 lbs (11.7 kg) with tripod and Mini-HUD. Designed with Triax engineers a year before Free Quebec seceded, a fact both governments keep quiet.', 'Rifts World Book 22: Free Quebec p.46-47'),
('q4-40-mule-assault-rifle', 'Q4-40 "Mule" Assault Rifle', 'rifts', 'weapon', 15, 15000, 'Free Quebec cost 15,000 credits; fair to good availability. Not yet on the black market; the book estimates 45,000-50,000 when it is, with explosive rounds at 700-800 credits each', 'One explosive round 2D6 M.D.; a rapid-fire burst of three rounds at the same target 6D6 M.D. and counts as one melee attack', 1, '800 feet (244 m) maximum effective', '12 rounds total - six hand held in the weapon and six in the standard clip. The clip can be replaced with a 24 round drum for a total of 30', 'Equal to the combined hand to hand attacks of the shooter; each shot or three-round burst is one melee attack', NULL, NULL, NULL, 'A projectile weapon firing the same explosive rounds as the QST-104 Glitter Girl Assault Cannon, scaled down for ordinary humans - much shorter ranged and with a kick that earns it two handles. Only cyborgs, power armor and characters of P.S. 26 or higher fire it one-handed without penalty; an ordinary human at P.S. 26 or less is -2 to strike on a single shot and -4 on a burst. It fires from either the front or the back handle grip. Weighs 15 lbs (6.75 kg) bare, 20 lbs (9 kg) with the ammo drum.', 'Rifts World Book 22: Free Quebec p.47-48'),
('q4-44-drummer-shotgun', 'Q4-44 "Drummer" Double-Barreled Shotgun', 'rifts', 'weapon', 16, 4500, 'Free Quebec cost 4,500 credits; good availability. The book then states a black market price of "45,000-50,000 credits with explosive shotgun rounds costing 200-300 credits each" - TEN TIMES the retail price, and the identical figure it gives for the Q4-40 Mule two entries earlier, which retails at 15,000. Recorded as printed; the 4,500 is the figure the book states outright', 'One explosive round 1D6 M.D., or 2D6 M.D. from a simultaneous double-barrel blast at the same target (one melee action). S.D.C. rounds do 4D6 S.D.C. from buckshot or 5D6 S.D.C. from solid slugs, doubled from a double-barrel blast', 1, '600 feet (183 m) maximum effective; 200 feet (61 m) underwater', '42 rounds - two hand loaded in each barrel plus a 40 round drum. Only two if no drum is available', 'Equal to the combined hand to hand attacks of the shooter; each shot or two-round double blast is one melee attack', NULL, NULL, NULL, 'Cheap, efficient and practical: a high-tech shotgun firing conventional S.D.C. rounds or light M.D. rounds. Super-durable - it takes a beating without jamming and fires underwater even after an hour submerged. A favourite of Reload Teams, Headhunters, Rangers, Juicers, Commandos and naval troops. Weighs 16 lbs (7.2 kg) with the ammo drum.', 'Rifts World Book 22: Free Quebec p.47-49'),
('q5-50-light-rail-gun', 'Q5-50 Light Rail Gun', 'rifts', 'weapon', 45, 32000, 'Free Quebec cost 32,000 credits; good availability. Not yet on the black market; the book estimates 60,000-70,000 when it is', '4D6 M.D. per full damage burst of 20 rounds; 1D4 M.D. per single round', 1, '4000 feet (1219 m) maximum effective', 'Short clip 200 rounds (10 bursts), light drum 600 rounds (30 bursts), or a heavy belt feed drum of 2000 rounds (100 bursts). Reloading a drum takes about two minutes untrained, or 20-30 seconds for a capable field mechanic or Reload Team', 'Equal to the character''s hand to hand attacks per melee round, usually three to six', NULL, NULL, NULL, 'A light anti-personnel rail gun for power armor troops, cyborgs and characters of P.S. 24 or greater; the same P.S. 24 is required to handle a drum. The 2000 round drum is typically reserved for cyborgs and carried as a backpack or by a partner in a two-man team. The gun weighs 45 lbs (20.25 kg); the short clip 10 lbs (4.5 kg), the light drum 30 lbs (13 kg) and the heavy drum 100 lbs (45 kg). Drums hook to the back of body armor or onto a Borg or power armor housing.', 'Rifts World Book 22: Free Quebec p.48'),
('qn-06-laser-harpoon-gun', 'QN-06 Laser Harpoon Gun', 'rifts', 'weapon', 6.5, 15000, 'Free Quebec cost 15,000 credits. Northern Gun and the black market offer knock-offs at 21,000', 'Laser 3D6 M.D. per blast. Harpoon damage varies with the spear type - see the four harpoon rows', 1, 'Laser 1200 feet (365.7 m); harpoons 350 feet (106.7 m) above water or 200 feet (61 m) underwater', 'Laser 20 shots per standard E-Clip or 30 per long E-Clip. Harpoons: three loaded, types may vary. A diver often carries a pouch of 12 more, each reloaded by hand at one melee action apiece', 'Each shot counts as one melee attack; only one harpoon can be fired at a time', NULL, NULL, NULL, 'A naval weapon used by Navy divers, Navy power armor troops and Army Special Forces. The top notch in the barrel fires a blue-green laser; the two side slots and one bottom slot hold any variety of spear.', 'Rifts World Book 22: Free Quebec p.48-50'),
('qn-06-harpoon-standard', 'QN-06 Harpoon: Standard', 'rifts', 'weapon', NULL, 6, '6 credits each', '2D6+3 S.D.C./Hit Points', 0, 'As fired by the QN-06: 350 feet (106.7 m) above water or 200 feet (61 m) underwater', 'One spear', 'One per melee attack', NULL, NULL, NULL, 'The plain spear for the QN-06 Laser Harpoon Gun.', 'Rifts World Book 22: Free Quebec p.49'),
('qn-06-harpoon-radio-transmitter', 'QN-06 Harpoon: Radio/Transmitter', 'rifts', 'weapon', NULL, 200, '200 credits each', '2D4 S.D.C./Hit Points as a weapon', 0, 'As fired by the QN-06. The transmitter itself carries up to 8 miles (12.8 km)', 'One spear', 'One per melee attack', NULL, NULL, NULL, 'A tracking harpoon and an excellent spy device. Transmits a tracking signal and can relay sounds from whatever it is impaled in or hooked onto; a magnetic clip lets it cling to M.D.C. metal structures. Battery life is 72 hours of constant transmission. The spear must stick into the target or fall on top of it without falling off, and there is a 01-32% chance per half hour that the bug works loose and drops off.', 'Rifts World Book 22: Free Quebec p.49'),
('qn-06-harpoon-flare', 'QN-06 Harpoon: Flare', 'rifts', 'weapon', NULL, 15, '15 credits each', 'None; it is a signalling device', 0, 'As fired by the QN-06: 350 feet (106.7 m) above water or 200 feet (61 m) underwater', 'One spear', 'One per melee attack', NULL, NULL, NULL, 'A flare harpoon that emits a bright, sparking light and burns for 120 seconds.', 'Rifts World Book 22: Free Quebec p.49'),
('qn-06-harpoon-high-explosive', 'QN-06 Harpoon: High Explosive', 'rifts', 'weapon', NULL, 600, '600 credits each', '4D6 M.D.', 1, 'As fired by the QN-06: 350 feet (106.7 m) above water or 200 feet (61 m) underwater', 'One spear', 'One per melee attack', NULL, NULL, NULL, 'The high explosive spear for the QN-06 Laser Harpoon Gun.', 'Rifts World Book 22: Free Quebec p.49'),
('qeba-10-battle-armor', 'QEBA-10 Environmental Battle Armor', 'rifts', 'armor', 18, 42000, 'Free Quebec cost 42,000 credits; 70,000 on the black market, where it is rare', NULL, 0, NULL, NULL, NULL, NULL, NULL, 80, 'The one standard suit of Quebec Military body armor, glossy black lightweight ceramic bonded at a molecular level, with spikes and light accents. Different headpieces distinguish divisions and rank; the face plate is smooth and featureless but for spikes, horns and fins. Full environmental protection to 300 degrees centigrade, radiation shielded, five hour oxygen supply. M.D.C. by location: Head/Helmet 50, Arms 35 each, Legs 50 each, Main Body 80 (heavy). Mobility good; -10% to climb and -20% to prowl, swim, acrobatics and similar physical skills. TWO FEATURES ARE UNIQUE TO FREE QUEBEC ARMOR: a built-in language translator covering English, Euro, Techno-can, the two most common Inuit tongues, old French and a dozen other regional languages (four of them user-programmable), and a back-mounted video camera and long-range transmitter that flips over the shoulder to film, recording nine hours on three self-loading video discs and transmitting ten miles (16 km) as standard, up to 25 miles (40 km) in clear wilderness, or hundreds of miles by relay. Built upon the old Coalition Dead Boy armor and issued only in the last year.', 'Rifts World Book 22: Free Quebec p.49-50'),
('jeba-13-juicer-battle-armor', 'JEBA-13 Juicer Environmental Battle Armor', 'rifts', 'armor', 18, 40000, 'Free Quebec cost 40,000 credits; 50,000 on the black market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 55, 'The composite suit worn by Quebec Military Juicers who do not wear the standard QEBA-10: the arms, legs and lower body of Bushman armor, the upper chest and shoulders of Juicer Assassin armor, and the head and helmet of the Infantry QEBA. A medium-light environmental suit with all standard EBA features and no special features. M.D.C. by location: Head/Helmet 50, Arms 25 each, Legs 38 each, Main Body 55 - light for a Juicer, medium for a normal human. Mobility very good for Juicers and merely good for anyone else, who takes double the penalties; -5% to climb, prowl, swim, acrobatics and similar physical skills.', 'Rifts World Book 22: Free Quebec p.50-51'),
('tx-j50-juicer-eba', 'TX-J50 Juicer EBA', 'rifts', 'armor', 20, 50000, 'Free Quebec cost 50,000 credits; 80,000 or more on the black market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 90, 'A Triax import, sold in limited quantities by Northern Gun and the black market and hugely popular with Juicers across Canada and the northeastern United States. Surprisingly flexible for its protection, thanks to advanced M.D.C. alloys and a simple exoskeleton augmentation that enhances balance and supports the joints. The face plate has simplistic robot and demonic features, and the helmet crown carries a modular clamp for a ponytail or Mohawk. M.D.C. by location: Head/Helmet 70, Arms 40 each, Legs 55 each, Main Body 90 - light for a Juicer, heavy for a normal human. Mobility very good to excellent for Juicers and only fair for anyone else, who takes triple the penalties; -5% to climb, prowl, swim, acrobatics and similar physical skills. Triax has agreed to suspend import after Coalition pressure, but not before perhaps 15,000 suits reached the country and Free Quebec bought enough to equip a third of its Juicers.', 'Rifts World Book 22: Free Quebec p.51');

-- Read the result back rather than trusting the exit code.
SELECT count(*) AS got_free_quebec_gear FROM gear
 WHERE source_book LIKE 'Rifts World Book 22: Free Quebec%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-free-quebec-gear.sql');
