-- Rifts World Book 19: Australia, batch 3: vehicles and power armor.
-- Nine rows with their M.D.C.-by-location tables and weapon lists: three
-- suits of power armor (the Mokoloi Prey-Stalker, printed 145-148; the Modular
-- Powered Armor "Rusty", 210-212; the X50 "Bushbasher", 212-214) and the six
-- Notable Vehicles (printed 214-223). 80 location rows, 35 weapon rows.
-- book-reconcile checked every figure; it found three main-body location rows
-- missing and one wrong remark, both corrected here.
-- See apps/character-creator/docs/surveys/australia.md.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-australia-vehicles.sql
--
-- READ IN COLUMN ORDER (scripts/read-columns.py) and off renders where a
-- block was scrambled, then checked again by book-reconcile: these pages set
-- each stat block beside line art and the plain text layer interleaves the
-- columns.
--
-- THE PREY-STALKER ROW IS INCOMPLETE, AND SAYS SO. The source PDF binds
-- printed page 145 twice and has no page 146. That page holds the first four
-- weapon entries, the head of the Sonic Blast entry, and the suit's speed,
-- size, weight and price. None of it is stored or guessed. The book prints
-- two headings for this suit (the narrative and the stat block); it is one
-- row.
--
-- CONVENTIONS:
--   cost is the lowest printed price; the others are in cost_note. The
--     Crawler's is the stripped Outback sale, the Viper's the fuel-powered
--     model, the Stinger's the model without the VR interface.
--   A printed range stores its low end: the Fliers' main body (200 to 300)
--     and weight (5-12 tons).
--   weight_tons is converted from pounds for the two City power armors and
--     the Stinger; the printed weight is in the description.
--   The Slicer's mini-torpedo launcher prints no M.D.C.: NULL.
--   A weapon the book lists with no damage figure of its own (optics, the
--     Rusty's forearm weapons by page reference) is in the description, not a
--     weapon row.
--
-- Pure ASCII, LF. Re-running it is a no-op.

INSERT OR IGNORE INTO vehicles
  (slug, name, system, vehicle_class, crew, passengers, speed_ground, speed_air, speed_water, dimensions, weight_tons, mdc_main_body, cost, cost_note, description, source_book)
VALUES
  ('mokoloi-prey-stalker-power-armor', 'Mokoloi "Prey-Stalker" Techno-Wizard Power Armor', 'rifts', 'power-armor', 'One Mokoloi', NULL, NULL, NULL, NULL, NULL, NULL, 280, NULL, 'Not read: Printed page 146 is missing from the source PDF (page 145 is bound in twice).', 'Techno-Wizard Prey-Stalker Power Armor; Purpose: Assault, Anti-Personnel. Mokoloi (Croc-men) Techno-Wizard armor; heavy M.D.C. protection and weapons, does not boost attributes. Supernatural P.S. 30. Withstands depth of one mile (1.6 km), double normal swimming speed, breathes underwater 2 hours at a time without visible air supply. Levitate, Float in Air, Repel Animals as 4th level spells, each 6 times per 24 hours. Regenerates 2D6+6 M.D.C. per 24 hours. Nightvision 600 ft, see invisible, sense magic (5th level). Creation: initial P.P.E. 325; spells Constrain Being (20), Energy Field (10), Armor of Ithan (10), Invisible Armor (30), Power Weapon (35), Swim as a Fish superior (12), Breathe Without Air (5), Float in Air (5), levitation (5), Superhuman Speed (10), Superhuman Strength (10), Mend the Broken (10+), Shockwave (35), Fire Ball (10), Electric Arc (8), Fireblast (8), Globe of Daylight (2), See the Invisible (4), Nightvision (6), Sense Magic (4) plus secret incantations. Materials: mechanical components, armor plating, silver plating for blades/claws/mechanics, two large rose quartz crystals for eyes, a Tectonic Entity or energy sphere locked inside as power source (content with its role), secret components. Build time 960 to 1100 hours (about 4-8 months). INCOMPLETE ROW. Printed page 146 is missing from the source PDF (page 145 is bound in twice). That page holds weapon items 1-4 (the laser eyes, back flame gun, lava spit and the arm and tail blades), the head of the Sonic Blast entry with its damage, and the speed, size, weight and price of the suit. Those are not stored; the weapons below are the ones the surviving pages print, the Sonic Blast without its damage. The suits sensors give +1 to strike and +1 to dodge with long-range weaponry only.', 'Rifts World Book 19: Australia p.145-148'),
  ('apaa-rusty-modular-power-armor', 'Modular Powered Armor "Rusty" (APAA)', 'rifts', 'power-armor', 'One', NULL, 'Running: 55 mph (88 km) maximum, 30% of usual fatigue rate; can be souped up to 70 mph (112 km) for an additional 30,000 dollars/credits. Leaping: 15 feet (4.6 m) high or 20 feet (6.1 m) across', 'Not possible without a jet pack; standard jet pack max altitude 2000 feet (610 m), speed 120 mph (192 km)', 'Swim 5 mph (4.3 knots/8 km) for an hour at a time; underwater jet pack 20 mph (17.2 knots/32 km) indefinitely; pressure to 1200 feet (366 m)', 'Height: 8 feet (2.4 m) tall. Width: From 3 feet (0.9 m). Length: 3 feet (0.9 m); varies slightly with the different backpacks and attachments', 0.26, 200, 1700000, 'Market Cost: 1.7 to 2 million in the Outback. Each Weapon System is an extra cost.', 'Official Designation: Assault Power Armor Alpha (APAA); Common Name: Rusty; Purpose: Multi-Purpose/General Purpose. Light modular environmental power armor, depth 1200 ft. P.S. equal to 28. Cargo: snap-on hard case backpack plus torso compartment (handgun, four extra clips, knife, hand-held radio) and holster belt with six pouches. Nuclear power, average life 20 years. Sensors: full optical systems, telescopic vision, passive nightvision, thermo-imaging, infrared. Extra armor: main body +50% (100 M.D.C.), other parts +20%, $800 per M.D.C. point; City Military suits 260-300 main body, Outback-sold basic suits start at 200. Attachments (jet pack, underwater pack, hook and winch, flame thrower with fuel tank, sensor packs, long-range radio/radar) typically $15,000-$30,000 each. Bugged: Cities can track the wearer and silent alarms trigger if used against a City or Military Outpost; -45% for Engineer or Cyber-Specter to find and deactivate (printed in intro text). Traded suits are usually stripped to one or two weapon systems. Weight as printed: 520 pounds (235 kg).', 'Rifts World Book 19: Australia p.210-212'),
  ('x50-bushbasher-power-armor', 'X50 "Bushbasher" Power Armor (APAB)', 'rifts', 'power-armor', 'One', NULL, 'Running: 35 mph (56 km) maximum, 20% of usual fatigue rate. Leaping: 5 feet (1.5 m) high or 10 feet (3 m) across', 'Not possible without a jet pack', 'Swim 5 mph (4.3 knots/8 km) for an hour at a time; underwater jet pack 20 mph (17.2 knots/32 km) indefinitely; pressure to 1200 feet (366 m)', 'Height: 7 feet (2.1 m); 8 feet (2.4 m) with part of the shoulder gun protruding when stored on the shoulder pointing up. Width: 3 feet (.9m). Length: 3 feet (.9 m); may vary with backpack attachments', 0.35, 240, 2800000, 'Black Market Cost: City cost is 2.8 million for a new suit of power armor fully loaded with weapon systems. Outback: rare stripped-down versions (no weapons other than Vibro-Blades, 20% less armor) sell for three times that; fully loaded versions (illegal) sell for 10 times the base price.', 'Official Designation: Assault Power Armor Beta (APAB); Common Name: Bushbasher; Primary Purpose: Infantry Assault and Espionage. Environmental power armor, depth 1200 ft; Melbourne/Perth Military standard for about 40 years. P.S. equal to 30. Nuclear power, average life 20 years. Sensors: full optical systems, telescopic vision, passive nightvision, thermo-imaging, infrared. Field troops typically carry four smoke and six fragmentation grenades. Jet pack and underwater pack attach to back. Outback-traded suits typically have one weapon system (usually Vibro-Blades) and 20% less M.D.C. Bugged for City tracking (printed in the Rusty intro text). No cargo line printed. Weight as printed: 700 pounds (315 kg).', 'Rifts World Book 19: Australia p.212-214'),
  ('nt-1200-devil-4x4', '"Devil" 4x4 NT-1200 Multi-Purpose Vehicle', 'rifts', 'vehicle', 'Three: a driver, gunner, and communications officer', 'Five more seated comfortably on bench seats, seven cramped; six others can ride on the exterior hand-holds in an emergency if speed is held under 35 mph (56 km)', 'Cruising: 45 mph (72 km); Maximum Speed: 140 mph (224 km); Maximum Off-Road Speed: 110 mph (176 km)', NULL, NULL, 'Height: 6 feet (1.8 m), sensor cluster adds 3 feet (0.9 m) for overall 9 feet (2.7 m). Width: 7 feet (2.1 m) body alone, 11 feet (3.3 m) overall. Length: 18 feet (5.5 m)', 8.5, 225, 180000, '$180,000 for a new, undamaged civilian vehicle (30% less armor, no weapons). Military units with standard weaponry and sensors $490,000. Price may vary 10-30% up or down; usually up. Component costs: grenade launcher $42,000, rail gun $130,000, comms suite $30,000, sensors $120,000, other onboard systems $60,000; two extra weapon systems for under $200,000.', 'NT-1200 Multi-Purpose Vehicle (stat block titled "Devil 4x4 Vehicle"). All-terrain jeep-style small squad transport and light combat vehicle; independent suspension, four wheel drive. Military version: pop-up grenade launcher, bonnet rail gun or laser, comms suite (200 mi/320 km), sensors (20 mile/32 km radar, targeting computer +1 to strike with onboard weapons), self-destruct feature. All models: air conditioning, 4 hour oxygen supply, small fridge, 3 gallons water, first-aid kit, A/V display, CD player, crash air bags (half damage to passengers). Range 300 miles (480 km) combustion, unlimited nuclear; about 36% have solar collector and battery adding 120 miles (192 km). Rear cargo compartment 6 ft wide x 3 ft long x 4 ft deep (6 ft long with rear seats folded); carries 5 tons, tows 12 tons, speed -30% when hauling over 6 tons. Civilian model has 30% less M.D.C. and no weapons. Military models can add two more weapon systems. Weight as printed: 8.5 tons.', 'Rifts World Book 19: Australia p.214-215'),
  ('nt-6000-crawler-apc', '"Crawler" APC NT-6000 All-Terrain Half-Track', 'rifts', 'vehicle', 'Four: a driver, communications engineer/navigator, gunner and soldier escort/defender', 'Up to four additional personnel in the four-door front cab; the rear holds a platoon of 40 troops in body armor, or 26 in power armor', 'Cruising: 35-50 mph (56 to 80 km); Maximum Speed: 100 mph (160 km); Maximum Off-Road Speed: 80 mph (128 km)', NULL, NULL, 'Height: 8 feet, 8 inches (2.65 m) main body; weapons and sensor/communications cluster add 4 feet (1.2 m) for overall 12 feet, 8 inches (roughly 3.9 m). Width: 9 feet, 4 inches (2.8 m). Length: 28 feet (8.5 m)', 18, 440, 514000, '$940,000 for a standard Military vehicle. Occasionally sold or traded to an Outback community minus all weaponry and sensors, less 40% of the M.D.C., with a fuel-solar system (never nuclear), at $514,000; may sell for twice that on the secondary market. Component costs: mini-missile launcher $140,000 plus $5000 per missile; main gun approx. $160,000; comms $30,000; sensors $120,000; other onboard systems $60,000; additional weapons average around $150,000 each.', 'NT-6000 All-Terrain Half-Track (stat block titled "Crawler Half-track"). Armored personnel carrier and cargo hauler. Front two wheels solid rubber, rear on tank tracks; ramp slides out of cargo bay. Roughly half nuclear (effectively unlimited range, 20 year life), half combustion (500 mile/804 km) with solar/electric battery adding 120 miles (192 km). Trailer section carries up to 100 tons and pulls 200 tons more, speed -30%. Military models have the same comms suite (200 mi/320 km), sensors (20 mile radar, targeting computer +1 to strike) and onboard systems as the Devil, and can take two additional weapon systems. Weight as printed: 18 tons.', 'Rifts World Book 19: Australia p.215-217'),
  ('slicer-patrol-boat', '"Slicer" Patrol Boat', 'rifts', 'ship', '9-13: captain/pilot, helmsman/co-pilot, navigator/communications officer, two gunners, 2-4 sailors/Marines/combat troops and 2-4 Power Armor troops', '6-10 additional personnel on the bridge; the belly holds up to 10 more fully armed Marines', NULL, NULL, 'Cruising: 40 mph (64 km/34 knots); Maximum Speed: 140 mph (224 km/123 knots)', 'Height: 6 feet (1.8 m) from water level to top of cabin, 12 feet (3.7 m) with sensor mast; draft of 4 feet 4 inches (1.3 m) below water. Width: 11 feet (3.4 m). Length: 44 feet (13.4 m)', 12.5, 500, 1600000, '1.6 million for a nuclear powered vessel with all weaponry and sensors. Not available on the open market except via the black market; very rare.', 'Slicer Patrol Boat; Purpose: Fast Response Patrol Boat (no NT designation printed). Bonus: +2 to dodge. About one third combustion (600 miles/960 km), two thirds nuclear with unlimited range (20 year life). Supplies for the skeleton crew of 4 for 3 months (1 month with soldier unit). Hold carries 6 tons and tows 40 tons; speed -60% when hauling over 10 tons. Comms 500 miles (800 km); long (30 mi/48 km) and short (2 mi/3.2 km) radar tracking up to 36 targets; passive sonar 1 mile (1.6 km). Air conditioning with 6 hour oxygen supply, basic medical equipment, A/V, four inflatable rafts (6 men each, 3 days supplies, A.R. 8, 50 S.D.C.). Sensor mast destroyed: other sensors at -40%. Flying bridge destroyed: use bow bridge with no penalty (below-decks -20% to detect ambushes). Main cabin destroyed: speed -20%. Standard crew includes Trencher Power Armor troops. Weight as printed: 12.5 tons.', 'Rifts World Book 19: Australia p.217-218'),
  ('nt-v40-viper-attack-chopper', '"Viper" NT-V40 Multi-Purpose Attack Chopper', 'rifts', 'vehicle', 'Two minimum, typically four: pilot, co-pilot/communications, and two door gunners', 'Four can ride comfortably in the rear compartment with the door gunners; six cramped', 'Not possible unless hauled by another vehicle', 'Can hover stationary or achieve a maximum of 480 mph (768 km); maximum altitude 5000 feet (1524 m)', NULL, 'Height: 8 feet (2.4 m) for body, 14 feet (4.3 m) including rotor blades. Width: 10 feet (3 m) wing tip to wing tip with rotors folded, or 35 feet (10.7 m) with rotors deployed. Length: 38 feet (11.6 m)', 6.5, 210, 1800000, '3.9 million for a nuclear powered Viper (70%), or 1.8 for a fuel powered chopper. Super-rare outside the Tech-Cities.', 'NT-V40 Multi-Purpose Attack Chopper (stat block titled "NT-V40 Attack Chopper"). Primary purpose Air Assault, Rescue and Troop Support; secondary Reconnaissance, Insertion and Extraction. Limited stealth, can rig for silent running at reduced speed. Range 500 miles (800 km) combustion, unlimited nuclear (20 year life). Cargo up to one ton. Folding telescoping rotors stored in a compartment holding a reserve pair that deploy within about one melee action if the main rotors are destroyed (200 ft/61 m altitude lost mid-air). Ejector seats for pilot and co-pilot only. Sensors: thermographic, low light nightvision, HUD, targeting scope, laser targeting, 20 mile (32 km) radar, loudspeaker, infrared, directional spy microphone, external camera, 300 mile (480 km) comms, onboard computer; sealed filtered cockpit. May carry 1-4 jet-pack power armor troopers. Bonuses: +1 to strike with all ranged weaponry, +1 to dodge, +2 on initiative. Weight as printed: 6.5 tons. The fuel-powered price is printed as "1.8" with no "million".', 'Rifts World Book 19: Australia p.218-220'),
  ('vr-500x-stinger', 'VR-500X "Stinger" Remote Mini-Helicopter', 'rifts', 'drone', 'Unmanned drone. If controlled by VR interface, one human operator who can be up to 50 miles (80 km) away (double in flat desert or grasslands without mountains or trees)', NULL, 'Not possible, must be hauled by another vehicle', 'May hover in place or achieve a maximum of 460 mph (736 km); maximum altitude 1800 feet (167.6 m)', NULL, 'Height: 3 feet (0.9 m). Width: 3 feet (0.9 m) wing tip to wing tip, 12 feet (3.7 m) total with rotors running. Length: 14 feet (4.3 m)', 0.5, 60, 550000, '760,000 for a new, undamaged Stinger with full arms and VR interface. Excluding the VR drops the price to 550,000.', 'VR-500X Remote Mini-Helicopter (stat block titled "VR-500X Stinger Robot"); Purpose: Defense and Patrol/Reconnaissance. Patrol drone, spotter/spy, defense. Range approx. 400 miles (640 km); power combustion or electric with approx. one hour flight/fuel time; cargo none. One VR operator can control 1-4 Stingers which then mimic the lead unit like a swarm. Three cameras; Perth model has swivelling (90 deg up/down, 360 deg) camera/sensor under the gun mount and a pair under the rotors, Melbourne model launches missiles from the underbelly and has VTOL jets in place of sensor wings. Without a VR operator it acts predictably (all bonuses halved, round down). Sensors: thermographic, low light, HUD, targeting scope, laser targeting, terrain following radar, loudspeaker, infrared, microphone, camera, 100 mile (160 km) comms. Weight as printed: 1000 pounds (450 kg). Printed oddities, stored as printed: the ceiling reads 1800 feet (167.6 m), which do not agree; the prose gives six mini-missiles per wing where the weapon entry gives 24 rockets.', 'Rifts World Book 19: Australia p.220-222'),
  ('one-and-two-man-fliers', 'One & Two Man Fliers', 'rifts', 'vehicle', '1-2; typically a pilot or pilot and co-pilot/gunner', NULL, 'Not possible unless hauled by another vehicle', 'Fliers can hover stationary or achieve a maximum of 480 mph (768 km); maximum altitude typically 5000 feet (1524 m)', NULL, 'Height: Varies from 8-12 feet (2.4 to 3.6 m). Width: Varies from 10-20 feet (3 to 6 m) depending on wingspan. Length: Varies from 12 to 22 feet (3.6 to 6.7 m)', 5, 200, 2800000, '2.8 to 6.2 million; reduce by half if not nuclear powered (approximately half are nuclear powered).', 'One & Two Man Fliers: small VTOL aircraft used exclusively by the Perth and Melbourne militaries. One combined entry; the book prints no separate one-man and two-man figures. Primary purpose Air Assault and Troop Support. Most share the same basic features, varying 10-30% in speed and in weapon combinations. VTOL, hover, low and slow flight (down to 5 feet/1.5 m above ground); not faster than the assault helicopter. Range 500 miles (800 km) combustion, unlimited nuclear (20 year life). Cargo none other than payload and crew. Ejector seats and sensors same as the Viper. Bonuses: +1 to strike with all ranged weaponry, +2 to dodge, +1 on initiative. Most two-man models can take two additional light weapons or one heavy, but only 40% have extras. Weight as printed: Varies from 5-12 tons. One combined entry: the book prints ranges, not separate one-man and two-man figures. Main body is 200 to 300 M.D.C. and weight 5-12 tons; the low ends are stored. The secondary gun range reads 1600 feet (183 m), which do not agree.', 'Rifts World Book 19: Australia p.222-223');

INSERT OR IGNORE INTO vehicle_locations (vehicle_slug, location, mdc, mdc_note, ordinal)
VALUES
  ('mokoloi-prey-stalker-power-armor', 'Laser Eyes (2)', 20, 'each', 1),
  ('mokoloi-prey-stalker-power-armor', 'Hands (2)', 80, 'each', 2),
  ('mokoloi-prey-stalker-power-armor', 'Arms (2)', 120, 'each', 3),
  ('mokoloi-prey-stalker-power-armor', 'Legs (2)', 160, 'each', 4),
  ('mokoloi-prey-stalker-power-armor', 'Flame Gun (1; detachable from the back)', 50, NULL, 5),
  ('mokoloi-prey-stalker-power-armor', 'M.D. Arm Blades (2)', 100, 'each', 6),
  ('mokoloi-prey-stalker-power-armor', 'M.D. Tail Blade (1)', 100, NULL, 7),
  ('mokoloi-prey-stalker-power-armor', 'Tail', 200, 'asterisk footnote not printed on available pages', 8),
  ('mokoloi-prey-stalker-power-armor', 'Head', 90, 'asterisk footnote not printed on available pages', 9),
  ('mokoloi-prey-stalker-power-armor', 'Main Body', 280, 'regenerates 2D6+6 M.D.C. per 24 hours', 10),
  ('apaa-rusty-modular-power-armor', 'Arms (2)', 65, 'each', 1),
  ('apaa-rusty-modular-power-armor', 'Hands (2)', 20, 'each', 2),
  ('apaa-rusty-modular-power-armor', 'Legs (2)', 95, 'each', 3),
  ('apaa-rusty-modular-power-armor', 'Head', 60, 'Destroying it eliminates optical enhancement and sensory systems; no power armor bonuses to parry, strike or dodge. Small and hard to hit; only by called shot at -3 to strike', 4),
  ('apaa-rusty-modular-power-armor', 'Main Body', 200, 'Depleting it shuts the armor down completely', 5),
  ('x50-bushbasher-power-armor', 'Arms (2)', 100, 'each', 1),
  ('x50-bushbasher-power-armor', 'Legs (2)', 140, 'each', 2),
  ('x50-bushbasher-power-armor', 'Shoulder Gun (1)', 50, 'small/difficult target; Called Shot at -3 to strike', 3),
  ('x50-bushbasher-power-armor', 'Shoulder Missile Launcher (1)', 60, 'called shot at -3', 4),
  ('x50-bushbasher-power-armor', 'Concealed Forearm Lasers (1 per arm)', 12, 'each; * called shot at -3', 5),
  ('x50-bushbasher-power-armor', 'Vibro-Blades (retractable; 2)', 15, 'each; printed with a dash and no asterisk', 6),
  ('x50-bushbasher-power-armor', 'Head', 80, 'Destroying the helmet eliminates optical and sensory systems; no power armor bonuses to parry, strike or dodge; human head exposed; only by called shot at -3', 7),
  ('x50-bushbasher-power-armor', 'Detachable Front Plate', 60, 'Attacks from directly in front that hit the main body subtract from this plate first; remains easily removed once depleted', 8),
  ('x50-bushbasher-power-armor', 'Main Body', 240, 'Depleting it shuts the armor down completely', 9),
  ('nt-1200-devil-4x4', 'Wheels (4)', 30, 'each', 1),
  ('nt-1200-devil-4x4', 'Windshield (front and rear)', 15, 'each', 2),
  ('nt-1200-devil-4x4', 'Side Windows (4)', 10, 'each', 3),
  ('nt-1200-devil-4x4', 'Doors (2; sides)', 90, 'each; single asterisk: small/difficult target; called shot at -4', 4),
  ('nt-1200-devil-4x4', 'Sensor Cluster/Communications Array (1; top, rear)', 50, NULL, 5),
  ('nt-1200-devil-4x4', 'Winch (1; rear)', 15, 'single asterisk: small/difficult target; called shot at -4', 6),
  ('nt-1200-devil-4x4', 'Headlights (6)', 5, 'each; single asterisk: small/difficult target; called shot at -4', 7),
  ('nt-1200-devil-4x4', 'Rail Gun (1)', 50, 'single asterisk: small/difficult target; called shot at -4', 8),
  ('nt-1200-devil-4x4', 'Pop-Up Grenade Launcher (retractable; 1)', 45, 'single asterisk: small/difficult target; called shot at -4 (value printed with a dash glyph, - 45)', 9),
  ('nt-1200-devil-4x4', 'Main Body', 225, 'Depleting it destroys the vehicle.', 10),
  ('nt-6000-crawler-apc', 'Front Tires (2)', 50, 'each; single asterisk: small/difficult target; called shot at -4', 1),
  ('nt-6000-crawler-apc', 'Side Tracks (2)', 110, 'each; single asterisk: small/difficult target; called shot at -4', 2),
  ('nt-6000-crawler-apc', 'Windshield (front)', 25, NULL, 3),
  ('nt-6000-crawler-apc', 'Side Windows (4)', 15, 'each', 4),
  ('nt-6000-crawler-apc', 'Cargo Bay Portals (8; sides)', 10, 'each', 5),
  ('nt-6000-crawler-apc', 'Main Gun (1; cab)', 50, 'single asterisk: small/difficult target; called shot at -4', 6),
  ('nt-6000-crawler-apc', 'Mini-Missile Launcher (1; cab)', 75, 'single asterisk: small/difficult target; called shot at -4', 7),
  ('nt-6000-crawler-apc', 'Sensor Cluster/Communications Array (1)', 60, NULL, 8),
  ('nt-6000-crawler-apc', 'Bay Door/Ramp (1; large)', 130, NULL, 9),
  ('nt-6000-crawler-apc', 'Headlights (4)', 8, 'each', 10),
  ('nt-6000-crawler-apc', 'Main Body', 440, 'Depleting it destroys the vehicle.', 11),
  ('slicer-patrol-boat', 'Weapon Turrets (2)', 90, 'each', 1),
  ('slicer-patrol-boat', 'Pop-Up Missile Launchers (2)', 80, 'each; single asterisk: small/difficult target; called shot at -3', 2),
  ('slicer-patrol-boat', 'Mini-Torpedo Launcher (1; rear)', NULL, 'no M.D.C. figure printed', 3),
  ('slicer-patrol-boat', 'Window Slits (6)', 15, 'each; single asterisk: small/difficult target; called shot at -3', 4),
  ('slicer-patrol-boat', 'Searchlight (1; top, large)', 15, 'single asterisk: small/difficult target; called shot at -3', 5),
  ('slicer-patrol-boat', 'Sensor Mast/Cluster', 70, 'single asterisk: small/difficult target; called shot at -3; the sensor-mast note separately says called shot at -4, thin target', 6),
  ('slicer-patrol-boat', 'Bridge Section', 150, 'double asterisk: depleting destroys top bridge controls and likely kills anyone there; bow bridge usable instead', 7),
  ('slicer-patrol-boat', 'Main Cabin', 220, 'triple asterisk: destroying it disables the flying bridge and exposes the sealed cabin; speed -20%', 8),
  ('slicer-patrol-boat', 'Main Hull', 500, 'Depleting it breaks the boat up and sinks it.', 9),
  ('nt-v40-viper-attack-chopper', 'Nose Gun', 20, 'single asterisk: small/difficult target; called shot at -3', 1),
  ('nt-v40-viper-attack-chopper', 'Medium-Missile Launchers (2)', 100, 'each; single asterisk', 2),
  ('nt-v40-viper-attack-chopper', 'Circular Mini-Missile Launchers (2)', 35, 'each; single asterisk', 3),
  ('nt-v40-viper-attack-chopper', 'Door Gunner Weapon Mount (1 or 2)', 25, 'each', 4),
  ('nt-v40-viper-attack-chopper', 'Gunner''s Side Doors (2; when closed)', 70, 'each', 5),
  ('nt-v40-viper-attack-chopper', 'Searchlight (1; underside of nose section)', 10, 'single asterisk', 6),
  ('nt-v40-viper-attack-chopper', 'Main Rotor Blades', 45, 'double asterisk: called shot at -4, all other attacks pass through; destroying them slides backup rotors into place in seconds with 200 ft (61 m) altitude loss; destroying backups crashes the chopper, 01-29% chance of salvageable parts including door gunner weapons', 7),
  ('nt-v40-viper-attack-chopper', 'Tail', 75, NULL, 8),
  ('nt-v40-viper-attack-chopper', 'Wings (2)', 50, 'each', 9),
  ('nt-v40-viper-attack-chopper', 'Cockpit', 150, NULL, 10),
  ('nt-v40-viper-attack-chopper', 'Main Body', 210, 'triple asterisk: depleting destroys the helicopter', 11),
  ('vr-500x-stinger', 'Rotors', 15, 'single asterisk: called shot at -5, all other attacks miss; destroying rotors crashes the drone', 1),
  ('vr-500x-stinger', 'Rail Gun', 25, NULL, 2),
  ('vr-500x-stinger', 'Tail', 25, NULL, 3),
  ('vr-500x-stinger', 'Sensor Wings (2 Perth; VTOL Jets Melbourne)', 20, 'each', 4),
  ('vr-500x-stinger', 'Landing Gear', 20, NULL, 5),
  ('vr-500x-stinger', 'Main Body', 60, 'double asterisk: depleting destroys the robot helicopter; 01-12% chance the gun is salvageable', 6),
  ('one-and-two-man-fliers', 'Nose Gun/Main Gun', 50, 'single asterisk: small/difficult target; called shot at -3', 1),
  ('one-and-two-man-fliers', 'Secondary Guns', 30, 'each; single asterisk: small/difficult target; called shot at -3', 2),
  ('one-and-two-man-fliers', 'Searchlight (1; underbelly)', 10, 'single asterisk: small/difficult target; called shot at -3', 3),
  ('one-and-two-man-fliers', 'Jet Thrusters (2-4; rear)', 70, 'each; single asterisk: small/difficult target; called shot at -3', 4),
  ('one-and-two-man-fliers', 'VTOL Thrusters (3-6; underbelly)', 30, 'each; single asterisk: small/difficult target; called shot at -3', 5),
  ('one-and-two-man-fliers', 'Tail Section', 135, NULL, 6),
  ('one-and-two-man-fliers', 'Wings (2-4)', 100, 'each', 7),
  ('one-and-two-man-fliers', 'Reinforced Pilot''s Compartment', 50, NULL, 8),
  ('one-and-two-man-fliers', 'Main Body', 200, '200 to 300 depending on size and body styling; double asterisk: depleting destroys the vehicle (value is a range, so mdc is a text string here)', 9);

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('mokoloi-prey-stalker-power-armor', 1, 'Hand to Hand Combat', 'Equal to Supernatural P.S. or the 30 supernatural P.S. of the armor, whichever is higher; Body Flip/Throw 1D4 M.D. plus victim loses initiative and one attack', 1, NULL, NULL, NULL, '+2 attacks per melee round, plus one at levels 5 and 10; +2 initiative, +1 at levels 6 and 12; +1 parry (+2 with blades extended); +2 dodge; +1 roll with punch, fall or impact', 'Bonuses apply to Mokoloi trained in the armor. Item 7 of the weapon list.'),
  ('mokoloi-prey-stalker-power-armor', 2, 'Left Arm: Electric Arc', '3D6 M.D.', 1, '200 feet (61 m)', 'Each blast counts as one melee attack/action', 'Effectively unlimited', '+2 to strike (point and shoot)', 'Item 6. Like the Electric Arc spell but slightly more damage and range.'),
  ('mokoloi-prey-stalker-power-armor', 3, 'Sonic Blast (right arm; item 5)', 'Not read: the damage line is on printed page 146, which is missing from the source PDF.', 1, '50 feet (15.2m)', 'Once per melee round; each blast counts as one melee attack/action', 'Effectively unlimited', NULL, 'Only the tail of this entry is on available pages (printed 147): knockdown table. Under 500 lbs: 01-88% knocked down and hurled 3D4 yards/meters, 89+ keeps balance but full damage. 500-1000 lbs: 01-50%, hurled 1D4 yards. Up to one ton: 01-20%, knocked back a few feet. Fliers hurled twice as far, not grounded; may be slammed into walls etc. for extra 1D4 M.D. Fallen: 01-40% drop held item, lose initiative and two attacks; caster and those touching him unaffected; acrobatics/balance skills +10% to save; successful fall/impact roll (14+) halves damage, full penalties. Entry header, damage and purpose lie on missing printed page 146.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'mokoloi-prey-stalker-power-armor');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('apaa-rusty-modular-power-armor', 1, 'Forearm Weapons', 'as Cyborg weapons, Rifts RPG page 241', 1, NULL, NULL, NULL, NULL, 'Forearm Blasters, Retractable Blades (page 241), Chemical Spray, Climb Cord, Arm Computer (page 240) can be built in or attached; no figures or cost given here. Item 3.'),
  ('apaa-rusty-modular-power-armor', 2, 'Concealed Vibro-Blades (2)', '2D6 M.D.', 1, NULL, NULL, NULL, NULL, 'Primary purpose Anti-Foliage; secondary Anti-Personnel; 3 foot long blades in slots under forearms; Cost $35,000. Item 4.'),
  ('apaa-rusty-modular-power-armor', 3, 'High-Powered Long-Range Laser (shoulder mounted)', '3D6 M.D.', 1, '3000 feet (915 m)', NULL, NULL, '+1 to strike on an aimed shot', 'Very accurate, suitable for sniping; Cost $28,000. Shoulder-mount options (item 5): one weapon over either shoulder, 30 degree arc of fire, voice command/touch pad; City price, two or three times more in Outback.'),
  ('apaa-rusty-modular-power-armor', 4, 'Dual Laser Blaster (shoulder mounted)', '6D6 M.D.', 1, '2000 feet (610m)', NULL, NULL, NULL, 'Twin barrel fires simultaneously; Cost $65,000.'),
  ('apaa-rusty-modular-power-armor', 5, 'Heavy Standard Ion Blaster (shoulder mounted)', '4D6 M.D.', 1, '1200 feet (366 m)', NULL, NULL, NULL, 'Cost $46,000.'),
  ('apaa-rusty-modular-power-armor', 6, 'Particle Beam Gun (shoulder mounted)', '6D6+6 M.D.', 1, '1200 feet (366 m)', NULL, NULL, NULL, 'Cost $100,000.'),
  ('apaa-rusty-modular-power-armor', 7, 'ATA Gun (shoulder mounted)', '6D6 M.D. per round', 1, '1000 feet (305 m)', 'each shot counts as one attack', '400 for a mini-drum, 1440 for a large drum', NULL, 'EIPP plasma propellant; Cost $38,000 for the weapon, $25 per ATA slug.'),
  ('apaa-rusty-modular-power-armor', 8, 'Medium Rail Gun (shoulder mounted)', '4D6 M.D. per burst of 12 rounds', 1, '2200 feet (670 m)', 'bursts only', '1440 drum (120 bursts)', NULL, 'Cost $62,000 for the weapon and one dollar per round.'),
  ('apaa-rusty-modular-power-armor', 9, 'S.D.C. Projectile Weapons (shoulder mounted)', '5D6 S.D.C. per round, or 1D6x10 S.D.C. per four-round burst', 0, '2000 feet (610 m)', 'each shot counts as one attack', '400 for a mini-drum (100 bursts), 1440 for a large drum (360 bursts)', NULL, 'Fires rifle rounds; Cost $8,000 for the weapon, $5 per 10 rounds (50 cents each). Text layer read 1D6x10 from a digit-cipher token.'),
  ('apaa-rusty-modular-power-armor', 10, 'Hand to Hand Combat', 'Restrained Punch 2D6 +10 S.D.C.; Full Strength Punch 1D4 M.D.; Kick 1D6 M.D.; Leap Kick 3D6 M.D. (counts as two attacks); Body Flip/Throw or Tackle 1D6 M.D.', 1, NULL, NULL, NULL, '+1 to dodge; +1 on initiative', 'Also Basic/Elite Power Armor Combat Training bonuses from Rifts RPG page 45 (must be selected as a skill). Damage standard for P.A.s. Item 6.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'apaa-rusty-modular-power-armor');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('x50-bushbasher-power-armor', 1, 'Shoulder Mounted Gun (1)', 'varies with rifle type', 1, 'Maximum Effective Range: varies per rifle type, typically 1200-4000 feet (366 to 1219 m)', NULL, 'Energy weapons are effectively unlimited', NULL, 'Any combat rifle or light rail gun, cabled to the nuclear power supply; City units mostly use laser rifle, or particle beam or rail gun for heavy damage. Can be removed and used as an ordinary rifle. Item 1.'),
  ('x50-bushbasher-power-armor', 2, 'Concealed Forearm Lasers (2)', '3D6 M.D. single blast; both together 6D6 M.D.', 1, 'Maximum Effective Range: 2000 feet (610 m)', 'Equal to the combined hand to hand attacks of the pilot (usually 4-6)', 'Effectively unlimited; feeds from the armor internal power', '+1 to strike', 'Primary Defense, secondary Anti-Personnel. Fire 30 degrees to either side, angle up/down 20 degrees. Simultaneous fire counts as one attack, needs motionless shooter and larger-than-man-sized target, still -2 to strike; firing both while running is -4 to strike. Item 2.'),
  ('x50-bushbasher-power-armor', 3, 'Concealed Vibro-Blades (2)', '2D6 M.D.', 1, NULL, NULL, NULL, NULL, 'Primary purpose Close Combat; 3 foot slender blades extruded from under the forearms. Item 3.'),
  ('x50-bushbasher-power-armor', 4, 'Belly Flame Thrower (1)', '1D6 M.D. per blast; burning targets take 1D4 M.D. more per melee round for 1D6 melee rounds', 1, 'Maximum Effective Range: 100 feet (30.5 m)', 'Each blast counts as one melee attack', '12 blasts, from canisters in the lower back', NULL, 'Primary Anti-Personnel; napalm or plasma flame; 01-65% chance surrounding combustibles catch fire (normal fire does S.D.C. damage). Used with extreme caution. Item 4.'),
  ('x50-bushbasher-power-armor', 5, 'Shoulder Mounted Mini-Missile Launcher (1)', 'Varies with missile type, usually Armor Piercing (1D4x10 M.D.)', 1, 'Effective Range: One mile (1.6 km)', 'One or two at a time', 'Five', NULL, 'Primary Anti-Armor and Assault. Item 5. Render shows 1D4x10 (text layer read as a digit-cipher token).'),
  ('x50-bushbasher-power-armor', 6, 'Hand to Hand Combat', 'Restrained Punch 2D6 +10 S.D.C.; Full Strength Punch 1D4 M.D.; Kick 1D6 M.D.; Leap Kick 3D6 M.D. (counts as two attacks); Body Flip/Throw or Tackle 1D6 M.D.', 1, NULL, NULL, NULL, '+1 to strike; +1 on initiative; +1 to dodge; +1 to roll with punch, fall or impact', 'Also Basic/Elite Power Armor Combat Training bonuses from Rifts RPG page 45 (must be selected as a skill). Item 6.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'x50-bushbasher-power-armor');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('nt-1200-devil-4x4', 1, 'Pop-Up Grenade Launcher (1)', 'Depends on grenade type; typically 2D6 (frag.) or 5D6 M.D. (plasma)', 1, '500 feet (152 m)', 'One at a time or in volleys of two or four', '42 grenades', NULL, 'Purpose: Assault. Military vehicles only; launches any grenade type.'),
  ('nt-1200-devil-4x4', 2, 'Mounted Rail Gun (1)', '4D6 M.D. per burst of 12 rounds', 1, '3,000 feet (914 m)', 'Only fires bursts of 12 rounds; each burst counts as one melee attack', '1440 drum (120 bursts)', NULL, 'Purpose: Anti-personnel and light assault. Prose says military versions have a light rail gun OR a laser gun (3D6 M.D.; 2000 ft/610 m range) on the bonnet passenger side; dashboard link, 90 degrees up/down, 25 degrees side to side; belt fed from hopper under bonnet.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'nt-1200-devil-4x4');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('nt-6000-crawler-apc', 1, 'Pop-Up Mini-Missile Launcher (1)', 'Depends on rocket type; usually fragmentation 5D6 to a 20 foot (6.1 m) radius or plasma 1D6x10 to a 15 foot (4.6 m) radius', 1, 'One mile (1.6 km)', 'Volleys of 2, 4 or 8', '24 rockets; reloaded by hand in two minutes', NULL, 'Purpose: Defense. Military vehicles only; folds open over the bonnet; small unguided rockets. Cost $140,000 plus $5000 per missile.'),
  ('nt-6000-crawler-apc', 2, 'Main Gun (1)', 'Varies by type: particle beam cannon (like NeraTech M-21) 1D6x10 M.D.; double-barrelled laser cannon 6D6 M.D.; rail gun 4D6 M.D. per burst', 1, 'Particle beam 2000 ft (610 m); laser cannon 3000 ft (914 m); rail gun 4000 ft (1228 m)', 'Not stated (turret rotates 180 degrees, 90 degree arc up and down)', 'Rail gun: 200 bursts; others not stated', NULL, 'Type varies. Particle beam for heavy firepower; laser or rail gun for range. Book refers to its weapon section for M-21 stats. Cost approx. $160,000.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'nt-6000-crawler-apc');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('slicer-patrol-boat', 1, 'Main Weapon Turrets (2)', 'Rail Gun: 1D4x10 M.D.; Laser: 6D6 M.D.', 1, 'Rail Gun: 4000 feet (1218 m); Laser: 3000 feet (914 m)', 'Standard', 'Rail gun burst is 15 rounds, belt-fed gun holds 6000 rounds (400 bursts each); no room for spare ammo drums unless no extra troops in hold. Laser unlimited if tied to nuclear power', NULL, 'Purpose: Assault & Defense. One turret each side of the mid-section; typically high-powered double-barreled laser or rail gun.'),
  ('slicer-patrol-boat', 2, 'Mini-Torpedo Launcher Rack (1)', '1D6x10 (High Explosive)', 1, '3 miles (4.8 km)', 'Single torpedo or a volley of two or four', '12 in launcher plus a dozen stored in hull; 3 minutes to reload launcher with six, 5 minutes for complete reload', '+5 to strike (guided smart-torpedoes, requires a gunner devoted to it; otherwise fired dry with no bonus)', 'Purpose: Anti-sub/ship. Mounted on the stern.'),
  ('slicer-patrol-boat', 3, 'Pop-Up Mini-Missile Launchers (2)', 'Varies by missile; typically Armor Piercing 1D4x10 M.D.', 1, 'Maximum Effective Range: One mile (1.6 km)', '1, 2 or 4 missiles in a volley', 'Eight per launcher, auto-reload for 32 per launcher (64 in all)', NULL, 'Purpose: Anti-Aircraft and Anti-Ship. Two bow hatches open and the launchers rise up.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'slicer-patrol-boat');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('nt-v40-viper-attack-chopper', 1, 'Nose Gun (1)', 'A single burst fires 20 rounds and inflicts 1D4x10 M.D.', 1, '4000 feet (1219 m)', 'Each burst counts as one melee attack', '4000 rounds (200 bursts)', NULL, 'Purpose: Anti-Personnel & Assault. Large belt-fed Gatling-style rail gun under the cockpit nose; primary weapon.'),
  ('nt-v40-viper-attack-chopper', 2, 'Mini-Missile Launchers (2)', 'Varies by missile; typically Armor Piercing 1D4x10 M.D.', 1, 'Maximum Effective Range: One mile (1.6 km)', '1, 2 or 4 missiles in a volley', '24 per launcher with automatic reloading, 48 in all', NULL, 'Purpose: Anti-Aircraft and Anti-Armor. Circular launchers on the weapon appendages.'),
  ('nt-v40-viper-attack-chopper', 3, 'Medium-Range Missile Launchers (2)', 'Varies by missile; typically Armor Piercing or High Explosive 3D6x10 M.D.', 1, 'Maximum Effective Range: approx. 50 miles (80 km)', '1, 2 or 3 missiles in a volley', 'Three per launcher, six in all', NULL, 'Purpose: Anti-Aircraft and Heavy Assault. Napalm/Plasma used only at sea.'),
  ('nt-v40-viper-attack-chopper', 4, 'Door Gunner''s Turrets (2)', 'Depends on weapon mounted (virtually any rifle or rail gun)', 0, 'Not stated', 'Not stated', 'Not stated', '-4 to strike when the helicopter is moving, -1 when hovering stationary', 'Folding mount and harness at each side door; suppressing fire and sniping. Gunners may wear flak vest up to heavy armor, rarely Bushbasher or Trencher power armor.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'nt-v40-viper-attack-chopper');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('vr-500x-stinger', 1, 'Nose Mounted Rail Gun (1)', 'A 40 round burst inflicts 1D4x10 Mega-Damage', 1, '4000 feet (1219 m)', 'Six bursts per melee round; total of seven melee actions in robot mode, otherwise attacks equal those of the VR controller +2', '2000 rounds (50 bursts)', NULL, 'Purpose: Assault. Small belt-fed Gatling-style rail gun; primary weapon.'),
  ('vr-500x-stinger', 2, 'Mini-Missiles (weapon wings)', 'Varies; usually high explosive 5D6 to a 5 ft (1.5 m) radius or armor piercing 1D4x10 to a 3 ft (.9 m) radius', 1, 'One mile (1.6 km)', 'Individually or in volleys of 2 or 4', '24 rockets altogether; each launcher has 6 forward tubes, each tube holds 2 rockets', NULL, 'Purpose: Assault. Intro text says six mini-missiles in each wing (12 total).')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'vr-500x-stinger');

INSERT INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note)
SELECT * FROM (VALUES
  ('one-and-two-man-fliers', 1, 'Nose Gun (1)', 'A single beam does 3D6+2 M.D.; a simultaneous dual blast does 1D4x10 M.D.', 1, '3000 feet (914 m)', 'Each single or dual blast counts as one melee attack; total attacks equal pilot attacks per melee round +1', 'Effectively unlimited', NULL, 'Purpose: Anti-Personnel & Assault. Turret under the nose, typically a double-barrelled laser.'),
  ('one-and-two-man-fliers', 2, 'Secondary Guns (2)', 'A single beam does 2D6 M.D.; a simultaneous dual blast does 4D6 M.D. Other energy weapons (particle beams, ion guns) may do more damage at shorter range', 1, '3000 feet (914 m); all others 1600 feet (183 m)', 'Each single or dual blast counts as one melee attack; total attacks equal gunner attacks per melee round +1', 'Effectively unlimited', NULL, 'Purpose: Anti-Personnel & Assault. Typically single-barrelled lasers on the fuselage or wing base, operated by the gunner; rail guns generally not used.'),
  ('one-and-two-man-fliers', 3, 'Missiles', 'Varies by missile; Medium-Range typically Armor Piercing or High Explosive 3D6x10 M.D.; Mini-Missiles typically Armor Piercing 1D4x10 M.D.', 1, 'Medium-Range: approx. 50 miles (80 km); Mini-Missiles: one mile (1.6 km)', '1, 2 or 4 missiles in a volley', 'Varies; minimum of two medium-range per wing or four minis', NULL, 'Purpose: Anti-Aircraft and Heavy Assault. Two medium-range or four mini-missiles on each wing (2-4 wings; most have two); launched by the gunner.')
) WHERE NOT EXISTS (SELECT 1 FROM vehicle_weapons WHERE vehicle_slug = 'one-and-two-man-fliers');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 9 Australia vehicle rows are in' AS assertion, count(*) AS got, 9 AS want
  FROM vehicles WHERE slug IN ('mokoloi-prey-stalker-power-armor', 'apaa-rusty-modular-power-armor', 'x50-bushbasher-power-armor', 'nt-1200-devil-4x4', 'nt-6000-crawler-apc', 'slicer-patrol-boat', 'nt-v40-viper-attack-chopper', 'vr-500x-stinger', 'one-and-two-man-fliers') AND source_book LIKE 'Rifts World Book 19: Australia p.%';
SELECT 'three are power armor, one a ship, one a drone' AS assertion, count(*) AS got, 5 AS want
  FROM vehicles WHERE slug IN ('mokoloi-prey-stalker-power-armor', 'apaa-rusty-modular-power-armor', 'x50-bushbasher-power-armor', 'nt-1200-devil-4x4', 'nt-6000-crawler-apc', 'slicer-patrol-boat', 'nt-v40-viper-attack-chopper', 'vr-500x-stinger', 'one-and-two-man-fliers') AND vehicle_class IN ('power-armor', 'ship', 'drone');
SELECT 'their location rows are in' AS assertion, count(*) AS got, 80 AS want
  FROM vehicle_locations WHERE vehicle_slug IN ('mokoloi-prey-stalker-power-armor', 'apaa-rusty-modular-power-armor', 'x50-bushbasher-power-armor', 'nt-1200-devil-4x4', 'nt-6000-crawler-apc', 'slicer-patrol-boat', 'nt-v40-viper-attack-chopper', 'vr-500x-stinger', 'one-and-two-man-fliers');
SELECT 'their weapon rows are in, once' AS assertion, count(*) AS got, 35 AS want
  FROM vehicle_weapons WHERE vehicle_slug IN ('mokoloi-prey-stalker-power-armor', 'apaa-rusty-modular-power-armor', 'x50-bushbasher-power-armor', 'nt-1200-devil-4x4', 'nt-6000-crawler-apc', 'slicer-patrol-boat', 'nt-v40-viper-attack-chopper', 'vr-500x-stinger', 'one-and-two-man-fliers');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-australia-vehicles.sql');
