-- Rifts World Book 8: Japan - traditional gear (printed 54-55 and 118-120):
-- 49 new rows. See apps/character-creator/docs/surveys/japan.md, step 3.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-a-japan-traditional-gear.sql
--
-- TEXT LAYER, page_offset +1. Extracted by two book-extract-workers and checked
-- row by row by book-reconcile.
--
-- WHAT IS HERE: the Mystic Ninja's traditional equipment and gimmick clothing
-- (printed 54-55); six bows, two gas arrowheads and magic arrows (118); and the
-- Traditional Japanese S.D.C. Weapons (118-120).
--
-- SLUGS ENDING -rifts. Heroes Unlimited and Palladium Fantasy already hold most
-- of these items under the plain slug (katana, nunchaku, ninja-emergency-kit),
-- each a copy for its own game, as Nightbane's are (-nb). None of them is a
-- Rifts row. This book prints its own credit prices and damage, so the Rifts
-- copy is its own row, suffixed -rifts where the plain slug is taken, and
-- keeps the item's name.
--
-- NOT HERE, because the catalog already holds this book's figures from an
-- earlier Rifts book: the Light, Medium, Heavy and High Explosive, Tear Gas
-- (arrowhead-gas), Smoke, Flare, Neural Disrupter and Tracer Bug arrowheads
-- (Triax printed 150, Spirit West printed 203), the crossbow pistol and the
-- modern crossbow (Spirit West printed 203). Conventional arrowheads print no
-- price; their damage is in the bow rows. The Exploding Shuriken closes the
-- vibro-blade section and ships with the high-tech weapons (step 4).

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('ninja-clothing-and-boots', 'Ninja Clothing & Boots', 'rifts', 'gear', NULL, 250, '250 credits for the outfit and boots.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A ninja outfit in black, white, red or camouflage: jacket, pants, gauntlets, tabi socks, double belt, leg ties, separate limb pieces, a quilted groin and body protector, many shuriken pockets and a two-part hood, with matching knee-high rubber-soled boots.', 'Rifts World Book 8: Japan p.54'),
('ninja-emergency-kit-rifts', 'Ninja Emergency Kit', 'rifts', 'gear', NULL, 300, '300 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A cloth bag of emergency supplies: 6 shuriken, 6 eggshell bombs, 12 caltrops, a knife, a towel, a small cooking pot, paper and pencil, matches or lighter, a first-aid kit, lock picks, spare clothing, and seven days of tight rations of rice, soybean curd and tea.', 'Rifts World Book 8: Japan p.54'),
('ninja-hang-glider-hito-washi', 'Ninja Hang Glider (Hito Washi)', 'rifts', 'gear', 25, 350, '350 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Carried disassembled as a small bundle of rods and cloth; assembled, it lets its user drop from a great height, even an airplane, and glide to the ground or a treetop.', 'Rifts World Book 8: Japan p.54'),
('climbing-claws-tekagi-or-shuko-rifts', 'Climbing Claws (Tekagi or Shuko)', 'rifts', 'gear', NULL, 65, '65 credits a pair.', '1D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A metal or leather palm band with two to six spikes on the inside, for climbing wood and stone: +10% to climbing. It can also be used to strike.', 'Rifts World Book 8: Japan p.54'),
('climbing-spikes-rifts', 'Climbing Spikes', 'rifts', 'gear', NULL, 45, '45 credits a pair.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Spiked claws strapped to the soles of the feet: +10% to climbing, but the wearer cannot walk or run normally while they are on.', 'Rifts World Book 8: Japan p.54'),
('eggshell-bomb-rifts', 'Eggshell Bomb', 'rifts', 'weapon', NULL, 35, '35 credits each.', 'None; blinds', 0, 'thrown about 60 ft (18.3 m); 10 ft (3 m) cloud', NULL, NULL, NULL, NULL, NULL, 'An eggshell filled with pepper, metal shavings and secret substances that shatters into a small cloud of blinding smoke. Those caught in it save vs non-lethal poison gas (16+) or are temporarily blinded, -6 to strike, parry and dodge.', 'Rifts World Book 8: Japan p.54'),
('ippon-sugi-nobori-rifts', 'Ippon-Sugi Nobori', 'rifts', 'gear', NULL, 50, '50 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A short spike-studded length of wood with a rope at each end, used only to climb trees and poles like a lineman''s belt: +25% to climbing.', 'Rifts World Book 8: Japan p.54'),
('kawanga-rifts', 'Kawanga', 'rifts', 'weapon', NULL, 75, '75 credits.', '2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A ninja rope-and-grapple combination for climbing and for fighting; as a weapon it needs the chain weapon proficiency.', 'Rifts World Book 8: Japan p.54'),
('chain-per-foot-rifts', 'Chain (per foot)', 'rifts', 'gear', NULL, 4, 'About 4 credits a foot (0.3 m), varying with thickness and tensile strength.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Common chain sold in farming villages and hardware stores; modern Japanese stock is usually well tested and reinforced.', 'Rifts World Book 8: Japan p.54'),
('climbing-rope-per-foot', 'Climbing Rope (per foot)', 'rifts', 'gear', NULL, 1, 'About 1 credit a foot (0.3 m), varying with thickness and strength.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Rope fit for climbing, sold in farming villages and hardware stores.', 'Rifts World Book 8: Japan p.54'),
('ninja-rope-ladder', 'Ninja Rope Ladder', 'rifts', 'gear', NULL, 20, '20 credits plus 1 credit a foot (0.3 m) of length.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A rope with loops knotted about every two feet and a 3 lb weight at the bottom; the top is often tied to a grappling hook. Easy to use and to hide.', 'Rifts World Book 8: Japan p.54'),
('tetsubishi-ninja-caltrops-rifts', 'Tetsubishi (Ninja Caltrops)', 'rifts', 'weapon', NULL, 2, '2 credits each.', 'Rarely more than 1 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Caltrops built so a barb always points up; a victim with one in the foot is unlikely to keep walking until it is removed. Useless against M.D.C. armor.', 'Rifts World Book 8: Japan p.54'),
('concealed-body-armor-sdc', 'Concealed Body Armor (S.D.C.)', 'rifts', 'armor', NULL, 3000, '3,000 to 6,000 credits for non-magical concealed armor.', NULL, 0, NULL, NULL, NULL, 14, 50, NULL, 'Ninja gimmick clothing: an outfit with a concealed inner mesh, A.R. 14 and 50 S.D.C.', 'Rifts World Book 8: Japan p.54'),
('concealed-body-armor-mdc', 'Concealed Body Armor (M.D.C.)', 'rifts', 'armor', NULL, 3000, '3,000 to 6,000 credits for non-magical concealed armor.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 9, 'Ninja gimmick clothing: an outfit of concealed lightweight mega-damage material, 9 M.D.C. Rare and powerful magic can raise that to 50 M.D.C.; that version is not priced.', 'Rifts World Book 8: Japan p.54'),
('concealed-pockets', 'Concealed Pockets', 'rifts', 'gear', NULL, 20, '20 credits a pocket.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja gimmick clothing: hidden pockets, loops, holders and hooks for small objects and concealed weapons. A jacket holds about six pockets and six loops; an overcoat or cloak 10 small and 4 large pockets and up to two dozen loops; a hat 3 to 5 small pockets.', 'Rifts World Book 8: Japan p.54-55'),
('concealed-tools', 'Concealed Tools', 'rifts', 'gear', NULL, 15, '15 credits an item.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja gimmick clothing: tiny items - wire, needles, razor blades, lock picks, microchips, bugs, recorders - sewn into seams and cuffs or built into a buckle; about four per shirt or trousers, eight per overcoat or robe.', 'Rifts World Book 8: Japan p.55'),
('expanding-straps-and-belts', 'Expanding Straps and Belts', 'rifts', 'gear', NULL, 15, '15 credits a strap.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja gimmick clothing: straps and belts hiding extra material that pulls out to four times their length, to bind a prisoner, garrote a foe or tie into a cord of about 10 ft.', 'Rifts World Book 8: Japan p.55'),
('fake-wounding', 'Fake Wounding', 'rifts', 'gear', NULL, 300, '300 credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja gimmick clothing: sacks of fake blood sewn into an outfit, each with a small charge that bursts the fabric to fake a battle wound.', 'Rifts World Book 8: Japan p.55'),
('reversible-clothing', 'Reversible Clothing', 'rifts', 'gear', NULL, NULL, 'Double the usual cost of the article of clothing.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja gimmick clothing: an article that changes color and look when turned inside out, such as leather one side and canvas or fur the other.', 'Rifts World Book 8: Japan p.55'),
('shoe-sandal-or-boot-compartment', 'Shoe, Sandal or Boot Compartment', 'rifts', 'gear', NULL, 80, '80 credits a pair.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja gimmick clothing: soles with a hidden compartment or a concealed tool or weapon.', 'Rifts World Book 8: Japan p.55'),
('short-bow-rifts', 'Short Bow', 'rifts', 'weapon', NULL, 200, '200 credits.', 'Conventional arrow 2D4 S.D.C.; by arrowhead', 0, '400 ft (122 m)', NULL, '2 to 8 shots a melee, by W.P.', NULL, NULL, NULL, 'A basic short bow. Bows weigh 2 to 5 lbs (modern ones 2 to 3); rate of fire 2 to 8 by W.P.; the same bow fires S.D.C., M.D. or magic arrows (printed 118).', 'Rifts World Book 8: Japan p.118'),
('ninja-bow-rifts', 'Ninja Bow', 'rifts', 'weapon', NULL, 500, '500 credits.', 'By arrowhead', 0, '400 ft (122 m)', NULL, '2 to 8 shots a melee, by W.P.', NULL, NULL, NULL, 'A bow that comes apart quickly and is easy to hide. Bows weigh 2 to 5 lbs (modern ones 2 to 3); rate of fire 2 to 8 by W.P.; the same bow fires S.D.C., M.D. or magic arrows (printed 118).', 'Rifts World Book 8: Japan p.118'),
('long-bow-rifts', 'Long Bow', 'rifts', 'weapon', NULL, 400, '400 to 600 credits.', 'Conventional arrow 2D6 S.D.C.; by arrowhead', 0, '700 ft (213 m)', NULL, '2 to 8 shots a melee, by W.P.', NULL, NULL, NULL, 'The long bow, traditionally a weapon of the samurai caste. Bows weigh 2 to 5 lbs (modern ones 2 to 3); rate of fire 2 to 8 by W.P.; the same bow fires S.D.C., M.D. or magic arrows (printed 118).', 'Rifts World Book 8: Japan p.118'),
('samurai-bow', 'Samurai Bow', 'rifts', 'weapon', NULL, 600, '600 to 900 credits.', '2D6 S.D.C. per arrow', 0, '800 ft (244 m)', NULL, '2 to 8 shots a melee, by W.P.', NULL, NULL, NULL, 'The samurai''s bow, longest-ranged of the traditional bows. Bows weigh 2 to 5 lbs (modern ones 2 to 3); rate of fire 2 to 8 by W.P.; the same bow fires S.D.C., M.D. or magic arrows (printed 118).', 'Rifts World Book 8: Japan p.118'),
('modern-composite-bow', 'Modern Composite Bow', 'rifts', 'weapon', NULL, 500, '500 to 1,200 credits.', 'Conventional arrow 2D6 S.D.C.; by arrowhead', 0, '500 to 700 ft (152 to 213 m)', NULL, '2 to 8 shots a melee, by W.P.', NULL, NULL, NULL, 'A light, accurate, durable bow of man-made materials. Bows weigh 2 to 5 lbs (modern ones 2 to 3); rate of fire 2 to 8 by W.P.; the same bow fires S.D.C., M.D. or magic arrows (printed 118).', 'Rifts World Book 8: Japan p.118'),
('traditional-crossbow', 'Traditional Crossbow', 'rifts', 'weapon', NULL, 400, '400 to 600 credits.', 'By bolt', 0, '600 ft (183 m)', NULL, '2 to 8 shots a melee, by W.P.', NULL, NULL, NULL, 'A traditional crossbow. Bows weigh 2 to 5 lbs (modern ones 2 to 3); rate of fire 2 to 8 by W.P.; the same bow fires S.D.C., M.D. or magic arrows (printed 118).', 'Rifts World Book 8: Japan p.118'),
('arrowhead-tranquilizer-gas', 'Arrowhead: Tranquilizer Gas', 'rifts', 'gear', NULL, 250, '250 credits.', 'None', 0, '10 ft (3 m) cloud', NULL, NULL, NULL, NULL, NULL, 'A high-tech arrowhead for bow or crossbow that shatters on impact into a 10 ft (3 m) cloud; everyone in it saves vs harmful drugs (15+) (printed 118). Sleep gas: those who fail are knocked out for 1D6 minutes.', 'Rifts World Book 8: Japan p.118'),
('arrowhead-paralysis-gas', 'Arrowhead: Paralysis Gas', 'rifts', 'gear', NULL, 400, '400 credits each.', 'None', 0, '10 ft (3 m) cloud', NULL, NULL, NULL, NULL, NULL, 'A high-tech arrowhead for bow or crossbow that shatters on impact into a 10 ft (3 m) cloud; everyone in it saves vs harmful drugs (15+) (printed 118). A nerve toxin: those who fail are paralysed for 1D6 minutes.', 'Rifts World Book 8: Japan p.118'),
('magic-arrows', 'Magic Arrows', 'rifts', 'gear', NULL, 800, '800 to 8,000 credits; availability and price vary dramatically, and they are most common in the New Empire.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Magic or techno-wizard arrows (and bows), sold in Japan; effects vary with the enchantment.', 'Rifts World Book 8: Japan p.118'),
('aikuchi-tanto-rifts', 'Aikuchi/Tanto', 'rifts', 'weapon', NULL, 100, '100 to 500 credits by quality and beauty.', '1D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Curved Japanese daggers that can be thrown; the tanto has a hilt, the aikuchi none. W.P. Knife.', 'Rifts World Book 8: Japan p.118'),
('bisento-rifts', 'Bisento', 'rifts', 'weapon', NULL, 500, '500 credits.', '3D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A large spear with a broad curved blade, a pole arm. W.P. Pole Arm.', 'Rifts World Book 8: Japan p.118'),
('blow-gun-rifts', 'Blow Gun', 'rifts', 'weapon', NULL, 30, '30 credits.', 'None; the dart is usually poisoned or drugged', 0, '50 ft (15.2 m)', NULL, NULL, NULL, NULL, NULL, 'A small pipe that fires darts by breath, a ninja favorite. W.P. Archery & Targeting (or the book''s own W.P. Mouth Weapons).', 'Rifts World Book 8: Japan p.118'),
('bokken', 'Bokken', 'rifts', 'weapon', NULL, 80, '80 credits.', '2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A wooden practice katana, still dangerous in skilled hands and popular against vampires. W.P. Sword.', 'Rifts World Book 8: Japan p.118'),
('daisho-rifts', 'Daisho', 'rifts', 'weapon', NULL, NULL, 'No price of its own: the entry gives manufactured katana at 900-1,200 credits and wakizashi at 400-600. An authentic samurai daisho is a priceless mega-damage rune weapon, typically 1D4 million credits when one is sold (see the True Samurai O.C.C.).', 'Katana 3D6 S.D.C.; wakizashi 2D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'The matched katana and wakizashi, symbol of the samurai caste; in the New Empire only a samurai may carry one. Ordinary copies are made by H-Brand and others.', 'Rifts World Book 8: Japan p.118-119'),
('jitte-or-sai-rifts', 'Jitte or Sai', 'rifts', 'weapon', NULL, 100, '100 credits a pair.', '1D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Pronged weapons used in pairs to parry and pin a blade; a skilled user entangles with one and strikes with the other (paired weapons). W.P. Knife.', 'Rifts World Book 8: Japan p.119'),
('katana-rifts', 'Katana', 'rifts', 'weapon', NULL, 450, '450 credits for H-Brand''s mass-market copy; the Daisho entry gives manufactured katana at 900-1,200.', '3D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A mass-market copy of the samurai long sword. W.P. Sword.', 'Rifts World Book 8: Japan p.119'),
('kusari-fundo', 'Kusari-Fundo', 'rifts', 'weapon', NULL, 120, '120 credits.', '2D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A heavier, deadlier manriki-gusari on a chain 2.5 to 4 ft long. W.P. Chain. Only those trained in hand to hand martial arts, assassin or Ninjitsu, or with W.P. Chain, use it well; anyone else is -2 to strike and parry and spends two melee actions an attack (printed 119).', 'Rifts World Book 8: Japan p.119'),
('kusari-gama-rifts', 'Kusari-Gama', 'rifts', 'weapon', NULL, 500, '500 credits.', '1D10 or 2D4+2 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A chain with a weight at one end and a sickle at the other, entangling with one end and striking with the other. W.P. Chain. Only those trained in hand to hand martial arts, assassin or Ninjitsu use it well; anyone else is -2 to strike and parry and spends two melee actions an attack (printed 119).', 'Rifts World Book 8: Japan p.119'),
('kyoketsu-shoge', 'Kyoketsu-Shoge', 'rifts', 'weapon', NULL, 200, '200 credits.', '1D8 or 2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A rope with an iron ring at one end and a double blade at the other, to entangle and strike (the book prints Kyoketsu-Shogi). W.P. Chain. Only those trained in hand to hand martial arts, assassin or Ninjitsu use it well; anyone else is -2 to strike and parry and spends two melee actions an attack (printed 119).', 'Rifts World Book 8: Japan p.119'),
('manriki-gusari-rifts', 'Manriki-Gusari', 'rifts', 'weapon', NULL, 30, '30 credits.', '1D8 or 2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A chain with blunt weights at both ends, easy to take apart and hide. W.P. Chain. Only those trained in hand to hand martial arts, assassin or Ninjitsu, or with W.P. Chain, use it well; anyone else is -2 to strike and parry and spends two melee actions an attack (printed 119).', 'Rifts World Book 8: Japan p.119'),
('naginata-yari-rifts', 'Naginata/Yari', 'rifts', 'weapon', NULL, 300, '300 credits.', '2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Long spears, hard to hide; the naginata''s blade is curved, the yari''s straight. W.P. Spear.', 'Rifts World Book 8: Japan p.119'),
('ninja-to-ninja-short-sword', 'Ninja-To (Ninja Short Sword)', 'rifts', 'weapon', NULL, 500, '500 credits.', '2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A short sword like the wakizashi but straighter, small and easy to hide. W.P. Sword.', 'Rifts World Book 8: Japan p.119'),
('no-dachi-rifts', 'No-Dachi', 'rifts', 'weapon', NULL, 600, '600 credits.', '3D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A huge curved two-handed sword 5 to 6 ft long, drawn from a scabbard on the back. W.P. Sword.', 'Rifts World Book 8: Japan p.119'),
('nunchaku-rifts', 'Nunchaku', 'rifts', 'weapon', NULL, 50, '50 credits.', '1D8 or 2D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Two lengths of wood or iron joined by a short chain; used in pairs to strike, or singly two-handed to entangle. W.P. Chain. Only those trained in hand to hand martial arts, assassin or Ninjitsu, or with W.P. Chain, use it well; anyone else is -2 to strike and parry and spends two melee actions an attack (printed 119).', 'Rifts World Book 8: Japan p.119'),
('shinobi-zue', 'Shinobi-Zue', 'rifts', 'weapon', NULL, 250, '250 credits.', '1D10 or 2D4+2 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A hollow wooden staff hiding a weighted chain. W.P. Staff.', 'Rifts World Book 8: Japan p.119'),
('shikomi-zue-rifts', 'Shikomi-Zue', 'rifts', 'weapon', NULL, 200, '200 credits.', '1D8 S.D.C.', 0, NULL, NULL, NULL, NULL, 50, NULL, 'A staff with a spring-loaded hidden blade, a ninja favorite in the disguise of a blind man; usable as a fragile bo staff or a spear. W.P. Staff or Spear.', 'Rifts World Book 8: Japan p.119-120'),
('shuriken-rifts', 'Shuriken', 'rifts', 'weapon', NULL, 10, '10 credits each.', '1D4 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Ninja throwing stars meant to distract and cover a retreat more than to kill; often poisoned or drugged. W.P. Archery & Targeting (or the book''s own W.P. Small Thrown Weapons).', 'Rifts World Book 8: Japan p.120'),
('tonfa-rifts', 'Tonfa', 'rifts', 'weapon', NULL, 50, '50 credits.', '1D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A short wooden weapon for parrying and close fighting, like a nightstick. W.P. Blunt.', 'Rifts World Book 8: Japan p.120'),
('wakizashi-rifts', 'Wakizashi', 'rifts', 'weapon', NULL, 300, '300 credits for H-Brand''s mass-market copy; the Daisho entry gives manufactured wakizashi at 400-600.', '2D4 S.D.C. (the Daisho entry gives 2D6)', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A mass-market copy of the samurai short sword. W.P. Sword.', 'Rifts World Book 8: Japan p.120');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'the 49 rows of add-a-japan-traditional-gear.sql are in' AS assertion, count(*) AS got, 49 AS want
  FROM gear WHERE slug IN ('ninja-clothing-and-boots', 'ninja-emergency-kit-rifts', 'ninja-hang-glider-hito-washi', 'climbing-claws-tekagi-or-shuko-rifts', 'climbing-spikes-rifts', 'eggshell-bomb-rifts', 'ippon-sugi-nobori-rifts', 'kawanga-rifts', 'chain-per-foot-rifts', 'climbing-rope-per-foot', 'ninja-rope-ladder', 'tetsubishi-ninja-caltrops-rifts', 'concealed-body-armor-sdc', 'concealed-body-armor-mdc', 'concealed-pockets', 'concealed-tools', 'expanding-straps-and-belts', 'fake-wounding', 'reversible-clothing', 'shoe-sandal-or-boot-compartment', 'short-bow-rifts', 'ninja-bow-rifts', 'long-bow-rifts', 'samurai-bow', 'modern-composite-bow', 'traditional-crossbow', 'arrowhead-tranquilizer-gas', 'arrowhead-paralysis-gas', 'magic-arrows', 'aikuchi-tanto-rifts', 'bisento-rifts', 'blow-gun-rifts', 'bokken', 'daisho-rifts', 'jitte-or-sai-rifts', 'katana-rifts', 'kusari-fundo', 'kusari-gama-rifts', 'kyoketsu-shoge', 'manriki-gusari-rifts', 'naginata-yari-rifts', 'ninja-to-ninja-short-sword', 'no-dachi-rifts', 'nunchaku-rifts', 'shinobi-zue', 'shikomi-zue-rifts', 'shuriken-rifts', 'tonfa-rifts', 'wakizashi-rifts') AND source_book LIKE 'Rifts World Book 8: Japan p.%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-a-japan-traditional-gear.sql');
