-- Rifts World Book 25: China 2 - the Geofront's guns, specialized ammunition,
-- Chi Demon Weapons and body armor (printed 142-150).
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-a-china-2-geofront-gear.sql
--
-- SCAN, page_offset +1. Every figure was read off a 200 dpi render by a
-- book-extract-worker. The survey is apps/character-creator/docs/surveys/china-2.md.
--
-- COST: the Geofront sells none of its technology; where the book prints a
-- Black Market price, that price (its low end) is the cost and the book's
-- words are in cost_note. The ammunition and the two Mo Fuqian skins print
-- no price and are NULL.
--
-- AMMUNITION is one row per round per gun, ten in all, because the Hound's
-- Fang prints larger damage for the same five rounds as the Hound's Tooth.
-- They are filed under the catalog's general gear category.
--
-- NOT HERE: the Chi Demon Weapons' charging and burial rules (printed 145-146)
-- are rules for the Chi Warrior and are in its class; the Geo-Borgs' built-in
-- weapons (128-132) are in their classes, as cyborg bodies are elsewhere.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('china-g-91-geo-blaster-phased-emitter', 'G-91 "Geo-Blaster" Phased Emitter', 'rifts', 'weapon', 2, 15000, 'Not sold: the Geofront does not sell their technology; use restricted to military and police. Black Market 15,000-20,000 credits minimum, double that in many markets (printed 142).', 'Four settings: Light Stun 1D6 S.D.C.; Normal Stun 3D6 S.D.C.; Heavy Stun 1D6 M.D.; Lethal 2D6 M.D. (also see stun effects)', 1, '400 feet (122 m)', '30 shots for Light or Normal stun, 15 shots for Heavy Stun or Lethal', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'Light police pistol with four settings from light stun to lethal; the heavy stun setting can incapacitate minor supernatural creatures. Bonuses: +1 to strike on an aimed shot. Stun: victim saves vs non-lethal poison (16 or higher) or loses a melee attack plus is short-circuited 2D4 melee rounds (half attacks/Spd, -8 initiative, -8 strike/parry/dodge, skills at half). Heavy Stun is for supernatural creatures, save 13+, only works on creatures with 100 M.D.C. or less. Heavy/Lethal on a human: 1D6x10+12 damage, 01-35% chance of stopping heart. Does not bypass full environmental armor/power armor.', 'Rifts World Book 25: China 2 p.142'),
('china-ght-85-hounds-tooth-auto-mag', 'GHT-85 "Hound''s Tooth" Auto-Mag', 'rifts', 'weapon', 5, 35000, 'Not sold: the Geofront does not sell their technology. Black Market 35,000 minimum (printed 143).', 'Standard round 1D6 M.D. single shot, 3D6 three round burst (specialized ammo listed separately)', 1, '500 feet (152.4 m)', 'Each clip holds 18 rounds', 'Single shot or three round bursts only, each counts as one melee attack', NULL, NULL, NULL, 'Workhorse Geofront handgun/SMG with two barrels that selects between standard and specialized ammo. Bonuses: -2 to strike if P.S. 13 or less unless fired two-handed (Gun Master O.C.C. exempt). Heading and intro on 142 (right column bottom), stats on 143. Double-barreled; side clip; three selector buttons (standard lower barrel / specialized ammo top barrel / both barrels).', 'Rifts World Book 25: China 2 p.143'),
('china-ghf-ak47-hounds-fang-assault-rifle', 'GHF-AK47 "Hound''s Fang" Assault Rifle', 'rifts', 'weapon', 10, 50000, 'Exclusive to the Geofront; Black Market 50,000-70,000 credits (printed 143).', 'Standard round 1D6+3 M.D. single shot, 4D6 three round burst, 7D6 six round burst', 1, '1600 feet (488 m)', 'Banana clip 50 rounds; mini-drum 150 rounds (adds 5 lbs/2.25 kg); drum takes 3 melee actions to change, banana clip 1', 'Single shot, three round burst, or six round burst. Single and 3-round count as one melee attack; six round burst takes two melee attacks', NULL, NULL, NULL, 'Standard-issue Geofront assault rifle with pseudo-rail-gun barrel for range; fires the same multipurpose ammo as the Hound''s Tooth. Stats begin 143 and continue on 144 (range, payload, cost). Can use the Hound''s Tooth specialized ammo.', 'Rifts World Book 25: China 2 p.143'),
('china-ght-88-brilliant-light-heavy-laser-pistol', 'GHT-88 "Brilliant Light" Heavy Laser Pistol', 'rifts', 'weapon', 6, 15000, 'Not sold: Geofront does not sell their technology. Black Market 15,000 credits; mini-nuke cell 200,000+ (printed 144).', '3D6 M.D. per shot', 1, '1000 feet (305 m)', '15 shots per standard E-Clip, 220 from one mini-nuke cell', 'Single shot, each counts as one melee attack', NULL, NULL, NULL, 'Heavy laser pistol with long range, powered by an experimental nuclear cell or standard E-Clip. Bonuses: -2 to strike if P.S. 13 or less unless two-handed (Gun Master exempt).', 'Rifts World Book 25: China 2 p.144'),
('china-ght-89-double-tap-dual-laser-pistol', 'GHT-89 "Double Tap" Dual Laser Pistol', 'rifts', 'weapon', 7, 22000, 'Not sold: Geofront does not sell their technology. Black Market 22,000 credits; mini-nuke cell 200,000+ (printed 145).', '3D6 S.D.C. from the S.D.C. setting, 2D6 M.D. per shot from the Mega-Damage setting, 4D6 M.D. for the M-mini-missile', 1, 'Lasers: 600 feet (183 m); M-mini-missile: One mile (1.6 km)', 'One M-mini-missile (6 additional in a small case, hand loaded, two melee actions to reload). S.D.C. laser: 200 S.D.C. blasts per standard E-Clip. M.D. laser: 20 shots per E-Clip (220 per mini-nuke cell).', 'Lasers: single shot, each counts as one melee attack', NULL, NULL, NULL, 'Dual-laser pistol (light S.D.C. barrel, medium M.D. barrel) with a micro-mini-missile on top. Bonuses: -2 to strike if untrained in this design and/or P.S. 13 or less, unless two-handed (Gun Master exempt). Weight: 7 lbs (3 kg) without the M-mini-missile, 8.5 lbs (3.8 kg) with the missile. Heading and intro on 144, stat lines on 145.', 'Rifts World Book 25: China 2 p.145'),
('china-ght-93-demon-knocker-ion-pulse-pistol', 'GHT-93 "Demon Knocker" Ion Pulse Pistol', 'rifts', 'weapon', 5, 12000, 'Not sold: Geofront does not sell their technology. Black Market 12,000 credits; mini-nuke cell 200,000+ (printed 145).', '1D8 M.D. per single shot or 3D8 M.D. per triple burst/pulse', 1, '500 feet (152 m)', '21 single shots or 7 pulse shots per standard E-Clip; 220 single shots or 73 triple pulse bursts from one mini-nuke cell', 'Single shot or three shot pulse, either counts as one melee attack', NULL, NULL, NULL, 'Heavy close-combat ion pistol firing single shots or three-shot pulses. Bonuses: -2 to strike if untrained and/or P.S. 13 or less, unless two-handed (Gun Master exempt).', 'Rifts World Book 25: China 2 p.145'),
('china-ght-95-vaporizer-particle-beam-pistol', 'GHT-95 "Vaporizer" Particle Beam Pistol', 'rifts', 'weapon', 9, 35000, 'Not sold: Geofront does not sell their technology. Black Market 35,000 credits; mini-nuke cell 200,000+ (printed 145).', '5D6 M.D. per single blast', 1, '500 feet (152 m)', '10 shots per standard E-Clip, 120 from one mini-nuke cell', 'Single shot', NULL, NULL, NULL, 'Heavy close-combat particle beam pistol in the Geofront arsenal for 300 years. Bonuses: -2 to strike if untrained and/or P.S. 13 or less, unless two-handed (Gun Master exempt).', 'Rifts World Book 25: China 2 p.145'),
('china-silver-nitrate-round-hounds-tooth', 'Silver Nitrate Round (Hound''s Tooth)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', '2D6 M.D. single round, 5D6 three round burst; supernatural beings vulnerable to silver suffer double damage', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #1 for the GHT-85 Hound''s Tooth (printed 143-144). Hollow-tip M.D. rounds filled with concentrated silver nitrate.', 'Rifts World Book 25: China 2 p.143'),
('china-claws-hounds-tooth', 'Claws (Hound''s Tooth)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', '3D6 M.D. single shot, 6D6+6 M.D. three round burst', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #2 for the GHT-85 Hound''s Tooth (printed 143-144). Malleable M.D. metal that flattens into jagged edges on impact.', 'Rifts World Book 25: China 2 p.143'),
('china-mercury-filled-rounds-hounds-tooth', 'Mercury-Filled Rounds (Hound''s Tooth)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', '3D6 M.D. single shot, 6D6+6 M.D. three round burst; supernatural creatures save vs lethal poison (14 or higher); failed save: extra 2D6 M.D., -2 strike/parry/dodge for 1D4 melee rounds, bio-regeneration takes triple time to heal; multiple shots only increase duration, not penalties', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #3 for the GHT-85 Hound''s Tooth (printed 143-144). Liquid mercury in tip absorbed into the bloodstream.', 'Rifts World Book 25: China 2 p.143'),
('china-du-rounds-hounds-tooth', 'DU Rounds (Hound''s Tooth)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', '4D6 M.D. single round, 1D4x10+4 M.D. three round burst', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #4 for the GHT-85 Hound''s Tooth (printed 143-144). Rare, only issued to special teams.', 'Rifts World Book 25: China 2 p.143'),
('china-u-rounds-hounds-tooth', 'U-Rounds (Hound''s Tooth)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', '5D6 M.D. single shot, 1D6x10 M.D. three round burst', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #5 for the GHT-85 Hound''s Tooth (printed 143-144). Far more rare than DU, only issued to experienced teams; book refers to Rifts World Book 5 (Triax and the NGR) for U/DU details.', 'Rifts World Book 25: China 2 p.143'),
('china-silver-nitrate-round-hounds-fang', 'Silver Nitrate Round (Hound''s Fang)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', 'Increased Mega-Damage: 3D6 M.D. single round, 1D4x10 M.D. three round burst, 1D6x10+6 M.D. six round burst; +1D6 M.D. per round to creatures vulnerable to silver', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #1 for the GHF-AK47 Hound''s Fang (printed 143-144). Same as the Hound''s Tooth silver nitrate round, increased damage.', 'Rifts World Book 25: China 2 p.143'),
('china-claws-hounds-fang', 'Claws (Hound''s Fang)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', 'Increased Mega-Damage: 4D6 M.D. single shot, 1D4x10+6 M.D. three round burst, 2D4x10 M.D. six round burst', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #2 for the GHF-AK47 Hound''s Fang (printed 143-144). Same as Hound''s Tooth claws, increased damage.', 'Rifts World Book 25: China 2 p.143'),
('china-mercury-filled-rounds-hounds-fang', 'Mercury-Filled Rounds (Hound''s Fang)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 143).', 'Increased Mega-Damage: 4D6 M.D. single shot, 1D4x10+6 M.D. three round burst, 2D4x10 M.D. six round burst; supernatural creatures failing save vs lethal poison (14 or higher) suffer extra 2D6 M.D., -2 strike/parry/dodge for 1D4 melee rounds, bio-regeneration triple time; multiple shots only increase duration of penalties', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #3 for the GHF-AK47 Hound''s Fang (printed 143-144). Same as above, increased damage.', 'Rifts World Book 25: China 2 p.143');

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('china-du-rounds-hounds-fang', 'DU Rounds (Hound''s Fang)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 144).', 'Increased Mega-Damage: 5D6 M.D. single round, 1D6x10+6 M.D. three round burst, 2D4x10+12 M.D. six round burst', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #4 for the GHF-AK47 Hound''s Fang (printed 143-144). Same as Hound''s Tooth DU, increased damage.', 'Rifts World Book 25: China 2 p.144'),
('china-u-rounds-hounds-fang', 'U-Rounds (Hound''s Fang)', 'rifts', 'gear', NULL, NULL, 'No price printed (printed 144).', 'Increased Mega-Damage: 6D6 M.D. single shot, 1D6x10+3 M.D. three round burst, 2D4x10+18 M.D. six round burst', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialized round #5 for the GHF-AK47 Hound''s Fang (printed 143-144). Rare, same as above, increased damage.', 'Rifts World Book 25: China 2 p.144'),
('china-chi-auto-mag-demon-claw', 'Chi Auto-Mag "Demon Claw"', 'rifts', 'weapon', 7, 35000, 'Most Chi Weapons are family heirlooms or belong to the military. If on the Black Market they would sell like TW weapons for at least 35,000-40,000 credits (printed 146).', '3D6 S.D.C. against mortal foes, 5D6 M.D. per blast against Mega-Damage opponents', 1, 'Normal: 800 feet (244 m), 1200 feet (366 m) when charged with Chi', '15 shots per clip', 'Each shot counts as one melee attack/action', NULL, NULL, NULL, 'A Geofront Chi Demon Weapon (printed 145-147): a Chi Warrior charges its clip with 10 I.S.P. a minute (or 20 P.P.E.); P.S. 17 or less is -3 to strike, the Gun Master excepted. Lightweight demon-claw pistol favored by Chi-Commandos; glows blue when charged. Bonuses: None normally; +1 to Aimed shots when the weapon is charged. Note: Not depicted. Cost line is at the top of the right column of 146.', 'Rifts World Book 25: China 2 p.146'),
('china-chi-energy-pistol-demons-fury', 'Chi-Energy Pistol "Demon''s Fury"', 'rifts', 'weapon', 9, 70000, 'Family heirloom/military. Black Market like TW weapons: at least 70,000-90,000 credits (printed 146).', '5D6 S.D.C. against mortal/S.D.C. targets, 6D6 M.D. against Mega-Damage targets that are not supernatural, 1D6x10 M.D. against the supernatural', 1, '800 feet (244 m), 1200 feet (366 m) when charged with Chi', '30 shots per banana clip', 'Each shot counts as one melee attack/action', NULL, NULL, NULL, 'A Geofront Chi Demon Weapon (printed 145-147): a Chi Warrior charges its clip with 10 I.S.P. a minute (or 20 P.P.E.); P.S. 17 or less is -3 to strike, the Gun Master excepted. Pistol that looks like it grows out of a horned demon face; fires explosive mini-fireballs when charged. Bonuses: +1 to strike on Aimed or Called Shots. Does not use specialized ammo; damage same regardless of ammo used.', 'Rifts World Book 25: China 2 p.146'),
('china-chi-sniper-rifle-demons-eye', 'Chi Sniper Rifle "Demon''s Eye"', 'rifts', 'weapon', 12, 150000, 'Most are in the hands of the Geofront military; rare (fewer than 5,000), reserved for Commandos, Military Specialists, Special Forces. Black Market like TW weapons: at least 150,000-200,000 credits (in places overrun by demons like Russia and the NGR) (printed 147).', '5D6 S.D.C. against mortal/S.D.C. targets, 1D6x10 M.D. against Mega-Damage targets that are not supernatural (including dragons), 2D6x10 M.D. against the supernatural', 1, '3000 feet (914 m)', '30 shots per standard ammo clip, 50 rounds per banana clip', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A Geofront Chi Demon Weapon (printed 145-147): a Chi Warrior charges its clip with 10 I.S.P. a minute (or 20 P.P.E.); P.S. 17 or less is -3 to strike, the Gun Master excepted. Sniper rifle growing from a horned demon face, with superior range and huge damage to infernals. Bonuses: +1 to strike on an Aimed or Called Shot; looking through the rifle eyes gives a telescopic scope and passive nightvision for an additional +1 to strike on an Aimed shot. Heading and intro on 146 bottom right, stats on 147.', 'Rifts World Book 25: China 2 p.147'),
('china-chi-mini-gun-vengeance', 'Chi Mini-Gun "Vengeance"', 'rifts', 'weapon', 40, 120000, 'Reserved exclusively for the military. Black Market like TW weapons: at least 120,000-180,000 credits (in places overrun by demons like Russia and the NGR) (printed 147).', '1D4x10 M.D. against mortal and Mega-Damage targets that are not supernatural; 3D4x10 (M.D.) per 10 round burst against supernatural foes', 1, '1600 feet (488 m)', '50 round banana clip (five bursts), 200 round drum (20 bursts) or backpack belt feed with 450 rounds (45 bursts). Adds 8 lbs (3.6 kg), 32 lbs (14.4 kg), or 80 lbs (36 kg) respectively.', 'Bursts only', NULL, NULL, NULL, 'A Geofront Chi Demon Weapon (printed 145-147): a Chi Warrior charges its clip with 10 I.S.P. a minute (or 20 P.P.E.); P.S. 17 or less is -3 to strike, the Gun Master excepted. Heavy mini-gun that only strong Chi Warriors can wield; mows down Yama King minions. Bonuses: None, even when charged with Chi. The 3D4x10 vs supernatural line is printed without M.D. after it.', 'Rifts World Book 25: China 2 p.147'),
('china-standard-brigandine-armor', 'Standard Brigandine Armor', 'rifts', 'armor', 20, 50000, 'Geofront can make a limited number annually; 500,000 available to the military. Black Market: upwards of 50,000 credits (printed 148).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 90, 'Medium PLA infantry environmental armor. Class: PLA-MA1; environmental armor, unisex design. M.D.C. by location: Head/Helmet 65, Arms 50, Legs 70, Main Body 90, +2D6 from M.D. ornamentation. Mobility: Good; -5% to Climb and -10% other Physical skills. Shared EBA systems list printed on 148: environmental, life support, 5 hours air, loudspeaker 80 dB, radio 5 miles, radiation shielded, heat resistant to 300 C, depth tolerance 1000 feet (305 m), magnetic clamps.', 'Rifts World Book 25: China 2 p.148'),
('china-heavy-brigandine-armor', 'Heavy Brigandine Armor', 'rifts', 'armor', 80, 90000, '100,000 available to the military. Black Market: upwards of 90,000 credits (printed 148).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 140, 'Bulkier brigandine with built-in exoskeleton for heavy weapon and armored units. Class: PLA-MA2; completely environmental, unisex design. M.D.C. by location: Head/Helmet 100, Arms 80, Legs 90, Main Body 140, +3D6 from M.D. ornamentation. Mobility: Good as augmented by the internal exoskeleton; -5% to Climb and -15% to other Physical skills. Exoskeleton: +10 to P.S. (equal to Robotic), +15 to Spd, increases jumps and leaps by 10 feet (3 m), user fatigue reduced by 50%; depth tolerance 1500 feet (457 m). Magnetic clamps to anchor heavy weapons/E-Clips.', 'Rifts World Book 25: China 2 p.148'),
('china-shadow-armor', 'Shadow Armor', 'rifts', 'armor', 6, 30000, 'Exclusive to the Geofront. If a suit ever made it to the Black Market it could easily sell for 30,000 credits (printed 149).', NULL, 0, NULL, NULL, NULL, 18, NULL, 48, 'Concealed M.D. fabric uniform worn by all Geofront military; with gloves and full-face helmet it becomes light environmental armor. Class: SA-23 Mega-Damage Uniform (body suit). M.D.C. by location: Main body 48 with jacket (58 for officers with extra plating; 18 without jacket); Arms & Legs 20 each (with jacket); Visor Style Helmet 38 or Hard-Face Helmet 50. Components: jumpsuit 18, jacket 30, boots 12. A.R. 18 without a helmet (rolls above hit the head/unprotected part; S.D.C. attacks below A.R. 18 do no damage; explosion and M.D. impact attacks over 15 points may do 1D6 S.D.C./Hit Points to the body underneath). Mobility: Excellent, no penalties. Heading and first paragraph at bottom of 148; description and stats on 149 (left column), rest of stats in top of right column. All soldiers who served keep a suit (Army Reserve).', 'Rifts World Book 25: China 2 p.149'),
('china-mo-fuqian-demon-skin', 'Mo Fuqian Demon Skin', 'rifts', 'armor', NULL, NULL, 'No price printed (printed 149).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Fast-healing M.D. artificial skin grafted onto every Geofront soldier. Class: Artificial skin graft (no class/model printed). M.D.C. by location: 4D6+18 M.D.C., heals at a rate of 2D6 M.D.C. per 12 hours. All Geofront soldiers undergo the augmentation on entering service (age 16 or 17); physical M.D.C. equal to light body armor.', 'Rifts World Book 25: China 2 p.149'),
('china-mo-fuqian-kai-demon-skin-armor', 'Mo Fuqian Kai Demon Skin Armor', 'rifts', 'armor', 60, NULL, 'No price printed (printed 149).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 60, 'Living demon-shaped armor worn like a jumpsuit for special ops; permanently grafts if worn too long. Class: DSA-003 Mega-Damage Skin. M.D.C. by location: Main body 60, Arms & Legs 30 each, Hands/Claws 18 each, Head/Face/Helmet 45. Mobility: Excellent, no penalties. Reduce Spd by 20% if P.S. is less than 13. Weight: 60 lbs (27 kg), though well dispersed; soldiers with P.S. and P.E. of 13 or more wear it without difficulty (sentence continues on 150). Problems & Conditions: absorbs and spends half of wearer I.S.P.; after 96 hours begins to graft permanently; if worn 96-144 hours peeling takes 4D6+20 minutes, 2D6 M.D. to the underlying Mo Fuqian, scarring (01-33% P.B. -1, 34-66% P.B. -2, 67-00% none); worn over 288 hours it is permanent; its M.D.C. merges, adding 2D6+6 to permanent M.D.C.; P.B. halved and M.A. -1D4. Heading and stats begin 149, remainder on 150.', 'Rifts World Book 25: China 2 p.149');

SELECT 'China 2 adds 26 Geofront gear rows' AS assertion, count(*) AS got, 26 AS want
  FROM gear WHERE slug IN ('china-g-91-geo-blaster-phased-emitter', 'china-ght-85-hounds-tooth-auto-mag', 'china-ghf-ak47-hounds-fang-assault-rifle', 'china-ght-88-brilliant-light-heavy-laser-pistol', 'china-ght-89-double-tap-dual-laser-pistol', 'china-ght-93-demon-knocker-ion-pulse-pistol', 'china-ght-95-vaporizer-particle-beam-pistol', 'china-silver-nitrate-round-hounds-tooth', 'china-claws-hounds-tooth', 'china-mercury-filled-rounds-hounds-tooth', 'china-du-rounds-hounds-tooth', 'china-u-rounds-hounds-tooth', 'china-silver-nitrate-round-hounds-fang', 'china-claws-hounds-fang', 'china-mercury-filled-rounds-hounds-fang', 'china-du-rounds-hounds-fang', 'china-u-rounds-hounds-fang', 'china-chi-auto-mag-demon-claw', 'china-chi-energy-pistol-demons-fury', 'china-chi-sniper-rifle-demons-eye', 'china-chi-mini-gun-vengeance', 'china-standard-brigandine-armor', 'china-heavy-brigandine-armor', 'china-shadow-armor', 'china-mo-fuqian-demon-skin', 'china-mo-fuqian-kai-demon-skin-armor');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-a-china-2-geofront-gear.sql');
