-- The Night Witch O.C.C., Rifts World Book 18: Mystic Russia p.73-78.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-night-witch-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- Two skill rows this book needs, written with REAL VALUES rather than left as
-- stubs. class-check emitted both at base 0 and filed the language under
-- Communications; both are wrong against the catalog's own convention, and a
-- stub percentage is the kind of number nothing ever flags again.
--
--   Language: Russian   Technical, 50/+5 - matching Language: Other and
--                       Language: Gypsy, and every other ordinary language.
--   Literacy: Russian   Communications, 30/+5 - matching Literacy: Other.
--
-- Eighteen classes in this book will reference them. The values come from the
-- convention, not from a page: this book states no skill percentages at all,
-- which is why its survey records zero new skills.
INSERT OR IGNORE INTO skills (name, category, base, per_level, source, source_book) VALUES ('Language: Russian', 'Technical', 50, 5, 'import', 'Rifts World Book 18: Mystic Russia p.73-78');
INSERT OR IGNORE INTO skills (name, category, base, per_level, source, source_book) VALUES ('Literacy: Russian', 'Communications', 30, 5, 'import', 'Rifts World Book 18: Mystic Russia p.73-78');


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'night-witch', 'Night Witch', 'rifts', '---
id: night-witch
name: Night Witch
system: rifts
source_book: Rifts World Book 18: Mystic Russia p.73-78
category: occ
occ_group: magic
xp_table: [0, 2081, 4161, 8801, 18001, 33001, 48001, 65001, 90001, 120001, 150001, 200001, 250001, 300001, 400001]
attribute_requirements: { IQ: 8 }
mdc_base: "P.E. x2 for physical M.D.C., plus 2d6 M.D. per level of experience"
ppe_base: "2d4x10 plus the P.E. attribute number, and 2d6 more per level of experience"
starting_money: "1d6x1000"
skills:
  occ_skills:
    - { name: "Mathematics: Basic", bonus: 20, note: "The book prints ''Basic Math (+20%)''. The catalog renamed that row to Mathematics: Basic and keeps a redirect, so the book''s spelling would still resolve as a GRANT - but only as a grant. The current name is stored so the string stays live if it is ever used in an only/except, where redirects are skipped and a stale name fails silently." }
    - { name: "Language: Russian", base: 98, per_level: 0, note: "Speaks Russian at 98%" }
    - { name: "Language: Euro", bonus: 20, note: "Speaks Euro (+20%)" }
    - { choose: 2, categories: ["Technical"], only: ["Language: Other"], bonus: 20, note: "Two other languages of choice (+20%)" }
    - { name: "Literacy: Russian", bonus: 10, note: "Literacy: Russian (+10%)" }
    - { name: "Lore: Demons & Monsters", bonus: 20, note: "Lore: Demons & Monsters (+20%)" }
    - { choose: 2, categories: ["Technical"], only: ["Lore: Demons & Monsters", "Lore: Faeries & Creatures of Magic", "Lore: Magic", "Lore: Religion"], bonus: 10, note: "Lore: two of choice (+10%)" }
    - { name: "Holistic Medicine", bonus: 20, note: "The book prints ''Herbology (+20%)''. Herbology is a Rifts World Book Three: England skill this catalog does not hold, and THIS BOOK draws the equivalence itself on printed 153: ''the Holistic Medicine skill can include the skills and powers of the Herbalist/Herbology skill as presented in Rifts World Book Three: England''." }
    - { name: "Land Navigation", bonus: 10, note: "Land Navigation (+10%)" }
    - { name: "Wilderness Survival", bonus: 5, note: "Wilderness Survival (+5%)" }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "W.P. Ancient, one of choice (any)." }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "W.P. Energy Weapon, one of choice (any)." }
    - { name: "Hand to Hand: Basic", note: "Can be changed to Expert for the cost of one O.C.C. Related Skill, or to Martial Arts or Assassin for two." }
  occ_related_skills:
    count: 8
    categories:
      - "Communications"
      - { name: "Domestic", note: "+5%" }
      - { name: "Medical", note: "+20%" }
      - { name: "Physical", except: ["Gymnastics", "Acrobatics"] }
      - { name: "Pilot", note: "Any except robots, power armor, military vehicles, ships and aircraft." }
      - "Pilot Related"
      - "Rogue"
      - { name: "Science", note: "+10%" }
      - { name: "Technical", note: "+10%; +15% to language and lore skills." }
      - "Weapon Proficiencies"
      - "Wilderness"
    schedule: [{ level: 3, count: 2 }, { level: 6, count: 2 }, { level: 9, count: 2 }, { level: 12, count: 2 }]
  secondary_skills:
    count: 3
    schedule: [{ level: 3, count: 1 }, { level: 5, count: 1 }, { level: 7, count: 1 }, { level: 9, count: 1 }, { level: 13, count: 1 }]
magic:
  type: "spell"
  spells:
    - "Spoiling: Sense Poison"
    - "Spoiling: Sense Bad Food & Drink"
    - "Spoiling: Spoil Water"
    - "Spoiling: Curdle Milk"
    - "Spoiling: Spoil Wine"
    - "Spoiling: Spoil Eggs"
    - "Spoiling: Spoil Sleep"
    - "Spoiling: Use Poison Flawlessly"
    - "Spoiling: Cursed Bread"
    - "Spoiling: Dry Mother''s Milk"
    - "Spoiling: Impervious to Disease"
    - "Spoiling: Spoil & Taint Food"
    - "Spoiling: Spoil Concentration"
    - "Spoiling: Track Thy Enemy"
    - "Spoiling: Spoil Memory"
    - "Spoiling: Spoil the Mind with Numbing Madness"
    - "Spoiling: Wither Thy Enemies"
    - "Spoiling: Demon Charms"
  spell_traditions_allowed: ["spoiling"]
bonuses:
  saves: { horror_factor: 5, possession: 8 }
special_abilities:
  - name: "Minor Mega-Damage creature"
    description: "The Night Witch has P.E. x2 for physical M.D.C., plus 2D6 M.D. per level of experience, and her P.S. is supernatural."
  - name: "Strongest at night"
    description: "Increase physical M.D.C., P.S. and Spd by 30% at night. A conditional bonus, so it is prose rather than a bonus line."
  - name: "Long Life"
    description: "Unless slain, a Night Witch lives 3D4x10 years past the age of 80."
  - name: "Bio-Regeneration"
    description: "Bio-regenerates 2D6 M.D. per hour, but ONLY at night - no healing occurs during daylight. She can regrow severed limbs, taking 1D6+6 months."
  - name: "Deceptively alluring"
    description: "In youth most Night Witches (90% are female) are attractive, even beautiful: +1D6+1 to the P.B. attribute. The beauty fades with age and the witch becomes increasingly haggish."
  - name: "Shapechanging"
    description: "The traditional shapechanging powers of the Witch, described in the book''s Night Witch section."
  - name: "Demon Helpers"
    description: "Lesser demons, typically The Unclean, bound to serve the witch indefinitely. They cannot be freed, dismissed, sold or locked away, never travel more than 200 miles (320 km) from their master, will not stay away more than three days, and always sense her exact location. They obey faithfully but pester constantly, and under minimal torture will name their master. The witch may keep extra demons by permanently sacrificing 6D6 of her own P.P.E. and 1D6 M.D.C."
  - name: "The power to Spoil"
    description: "All Night Witches know the whole of Spoiling Magic - every spell in that tradition, granted outright and listed above."
  - name: "Additional spell knowledge"
    description: "Beyond Spoiling Magic the witch starts with 2D4 wizard/Ley Line Walker spells selected from levels 1-4, OR 1D4 Necromancer Bone Magic spells of any level. The number is rolled, and a rolled count of starting spells is not something the wizard can express, so the allotment is recorded here rather than as a spells_starting number that would have to invent a figure. N.P.C. villains are likely to know two to four times more wizard spells."
  - name: "Spell strength"
    description: "+1 to spell strength at levels 3, 6, 9 and 13."
restrictions:
  - "EVIL OR SELFISH ONLY - any selfish or evil alignment, and most (50%) are miscreant. The attribute requirement the book states is I.Q. 8 ''and an evil heart''."
  - "The book presents this O.C.C. as an evil Non-Player Character villain, and heads its own stat block ''Night Witch Optional O.C.C. & N.P.C. Villain'' - playable at the Game Master''s discretion rather than by default."
  - "Racial restrictions: none, although the vast majority (75%) are human."
  - "Cybernetics: none. The Night Witch avoids them as unnatural and unnecessary."
  - "The character also starts with 1D6x100 credits'' worth of TRADEABLE GOODS, over and above the coin in starting_money. That field is coin only, and the goods are not a named item the gear catalog can hold, so they are recorded here. N.P.C. witches start with 2D6x10,000 instead, and many amass sizable fortunes - some rule towns, clans and gangs."
  - "Notable vulnerability: the light of day is unwelcome and unpleasant; the witch prefers night, shadow and cloudy days."
  - "Spoiling Magic is exclusive to the Witch O.C.C.s and no other class, which is why it is a tradition of its own in the catalog."
extraction_notes: "Rifts World Book 18: Mystic Russia pp.73-78. THE BOOK PRINTS ''Herbology'' AND THAT SKILL IS NOT IN THIS CATALOG: it belongs to Rifts World Book Three: England, which is not held here. The equivalence is the book''s own, from printed 153 - ''the Holistic Medicine skill can include the skills and powers of the Herbalist/Herbology skill as presented in Rifts World Book Three: England'' - so Holistic Medicine is granted rather than a Herbology row being invented with a percentage no page here states. Two skill rows ARE created, both following the catalog''s existing convention rather than a guess: Language: Russian at Technical 50/+5, matching Language: Other and Language: Gypsy, and Literacy: Russian at Communications 30/+5, matching Literacy: Other. They are created properly rather than as class-check stubs, which would have written both at base 0 and filed the language under Communications against the convention. Eighteen classes in this book will use them. All 18 Spoiling Magic spells are granted by name, matching the book''s ''All spells are known to the Witch''; they were imported as their own tradition in the same batch, and `spell_traditions_allowed` names it so a level-gated pick can reach them too. The book''s ADDITIONAL allotment - 2D4 wizard spells from levels 1-4, or 1D4 Bone Magic spells of any level - is recorded in special_abilities rather than as `spells_starting`, because that key takes an integer and the book states a rolled count; writing a fixed number there would invent a figure the page does not give. The ''Average Level of Experience (N.P.C.): 1D6+2'' line describes how a Game Master should stat an encounter, not the player character, so it is not stored. Attribute requirement is I.Q. 8; the book''s second requirement, ''an evil heart'', is carried as a restriction because alignment is not an attribute."
---

# Night Witch

## Lore

The Night Witch is the Russian witch of myth and superstition - a creature of
darkness who enjoys corrupting and spoiling the human spirit and tarnishing all
that is good, healthy and beautiful. She will gladly help the evil and the
falling, and will even help an old rival, provided the aid leaves them indebted
to her and ultimately worse off.

Anyone who willingly seeks a Night Witch''s help consorts with evil and opens
himself to danger, treachery and the corruption of his own soul. She is the
friend of the envious, the ambitious, the greedy, the hate-filled and the
vengeful, and she is good at making revenge and greed sound delicious and just
rather than bitter and cruel.

Those who commission her sometimes argue their own hands are clean, since it was
the witch who did the deed. They are deluded or lying: commissioning a Night
Witch is itself a deliberate act of evil. Characters of good alignment who turn
to a Night Witch, a Necromancer or a demon to extract revenge or to harm others
drop automatically to anarchist alignment, and willing participation in torture
or murder takes them further still.

## Alignment

Any selfish or evil alignment. Half are miscreant.

## GM Notes

The book presents this O.C.C. as an evil Non-Player Character villain and heads
its stat block "Night Witch Optional O.C.C. & N.P.C. Villain" - playable at the
Game Master''s discretion rather than by default.

Palladium''s own note at the head of the section is worth passing on: the Night
Witch keeps to the Russian view of the evil, haggish witch of myth, no slight is
intended to well-intentioned modern witches or to practitioners of wicca,
druidism or shamanism, and the character is a fictional presentation not meant
to portray any real-life people or religious belief.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'night-witch');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'night-witch';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-night-witch-class.sql');
