-- Rifts World Book 25: China 2 - the Green Scarf Taoist Sect's magic items
-- (printed 101-114), the Soothsayer's tools (65-66), the Book of Ten Thousand
-- Demons (80) and the five fans the White Jade Fan style prices (23).
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-a-china-2-magic-gear.sql
--
-- SCAN, page_offset +1. Every figure was read off a 200 dpi render by a
-- book-extract-worker. The survey is apps/character-creator/docs/surveys/china-2.md.
--
-- ONE ROW PER PRICED VARIANT: the Black Cloud Pearl and Pink Cloud Pearl each
-- price a limited and an unlimited enchantment; the Demon Armor prices a
-- partial suit in M.D.C. and S.D.C. forms, a full suit, and two add-ons; each
-- of the four Swords of Demon Hunting is its own row.
--
-- COST is the single printed figure, or the low end of a printed range with the
-- range in cost_note, as earlier imports do. A price printed as dice (most of
-- the fans) or not printed at all (the Soothsayer's tools) is NULL with the
-- book's words in cost_note.
--
-- WHERE THE BOOK DISAGREES WITH ITSELF the item's own entry wins and the
-- other reading is in the description: the Demon Catching Mirror is 500 M.D.C.
-- on printed 105 and 100 in the Demon Catching Hero's kit (80); the Binding
-- Demon Stamp renews at 40,000-120,000 a year on 103 and 40,000-80,000 on 84.
--
-- NOT HERE: the classes' starting packages (a Demon Catcher's mirror and sword,
-- a Slaver's chains and snares, a Wrangler's picks) are the item rows above,
-- named in the class files. Slugs carry a china- prefix so no Palladium or
-- Japan row is shadowed.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('china-binding-blinders', 'Binding Blinders', 'rifts', 'magic', NULL, 20000, '20,000 credits (printed 102).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Blinders on a demon; owner can command it blind (-10 strike/parry/dodge, no magic/psionics unless owner allows). Stops metamorphosis, invisibility, natural abilities. Duration: magic good 2 years from purchase. Used by: slave owner.', 'Rifts World Book 25: China 2 p.102'),
('china-binding-chains', 'Binding Chains', 'rifts', 'magic', NULL, 2000, '2,000 credits (printed 102).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Chain and manacles that hold a demon or monster regardless of Supernatural P.S.; do not stop magic, psionics, flight, shape change. Penalties: -30% Pick Locks/Escape Artist. Duration: 2 years.', 'Rifts World Book 25: China 2 p.102'),
('china-binding-demon-snare', 'Binding Demon Snare', 'rifts', 'magic', NULL, 9000, '9,000 credits (printed 102).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Special rope for capturing Goblins, Lesser Demons and Deevils; victim helpless within it. No effect on mortals, Greater Demons, creatures of magic. Saving throw: save vs magic 14 or higher; success only means 2 attacks/round, no bonuses, no magic. Duration: 2 years.', 'Rifts World Book 25: China 2 p.102'),
('china-binding-demon-choker-snare', 'Binding Demon Choker Snare', 'rifts', 'magic', NULL, 15000, '15,000 credits (printed 102-103).', 'sleep vapor knocks out in 1D4+2 melee actions; no damage', 0, NULL, NULL, NULL, NULL, NULL, 110, 'A Green Scarf Taoist Sect magic item (printed 101-114). Stick and pull cord lasso that chokes and releases sleep vapor; needs Supernatural P.S. 55 to snap; two hands to use; cannot parry. Works on humans. The captive loses initiative and two melee attacks a round, and its combat bonuses are halved. Saving throw: none for Goblins/Lesser Demons/humans; Greater Demons 12+ vs knockout each round. Duration: 2 years.', 'Rifts World Book 25: China 2 p.102-103'),
('china-binding-demon-stamp', 'Binding Demon Stamp', 'rifts', 'magic', NULL, 80000, '80,000 credits initial; renewal yearly, ranges 40,000 to 120,000 credits (printed 103-104).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Magic brand that makes a demon docile and obedient; front plus back stamping for full control. Slaver must renew yearly or lose it. Duration: must renew yearly. I.S.P.: 1 I.S.P. per use; creator invests 2D6+6 permanent I.S.P. Used by: Demon Slaver O.C.C. (and select Green Scarf members). The book disagrees with itself here: Printed 84 (Demon and Dead Slaver O.C.C.) says renewal varies 40,000 to 80,000 annually; printed 103 says 40,000 to 120,000. Book disagrees with itself.', 'Rifts World Book 25: China 2 p.103-104'),
('china-binding-hand-stock', 'Binding Hand Stock', 'rifts', 'magic', NULL, 6000, '6000 credits (printed 104).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Small wooden stock clamping the hands, usually chained; does not stop magic or psionics. Penalties: Spd and attacks halved, bonuses halved; -55% Pick Locks/Escape Artist; -30% hand skills. Duration: 2 years.', 'Rifts World Book 25: China 2 p.104'),
('china-binding-head-hand-stock', 'Binding Head & Hand Stock', 'rifts', 'magic', NULL, 10000, '10,000 credits (printed 104).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Wooden stock around head and hands; demon helpless, no spells, psionics or special abilities. Penalties: 2 attacks/round, Spd 20%, bonuses zero. Duration: 2 years.', 'Rifts World Book 25: China 2 p.104'),
('china-binding-leash-collar', 'Binding Leash & Collar', 'rifts', 'magic', NULL, 20000, '20,000 credits (only works on Stamped Lesser/Greater Demons) (printed 104).', NULL, 0, 'leash 7-12 feet', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Whoever holds the leash commands the demon; lets a Stamped demon be lent without transferring ownership. Saving throw: battle of wills, 1D20 x3, demon -5 to save. Duration: 1 year.', 'Rifts World Book 25: China 2 p.104'),
('china-binding-bell-of-bliss', 'Binding Bell of Bliss', 'rifts', 'magic', NULL, 100000, '100,000 credits (printed 105).', NULL, 0, '2000 foot (610 m) radius', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Handheld bell; sound pains demons: Lesser -40% skills, -1 attack, no initiative; Greater -20% skills, -2 initiative, -2 bonuses. Saving throw: None. Duration: 1 year; effect while rung.', 'Rifts World Book 25: China 2 p.105'),
('china-black-cloud-pearl-single-use', 'Black Cloud Pearl (Single Use)', 'rifts', 'magic', NULL, 3000, '3,000 credits for one use; rechargeable by Green Scarf Cultist for another 3,000 credits (printed 105).', NULL, 0, '3 ft (0.9 m) radius; close proximity', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Thrown pearl releases black cloud that traps one or two demons; afterward -1 attack, -2 bonuses, no initiative first round. Humans pass through blind. Saving throw: None for Lesser; Greater 12+ with usual bonuses; Demon Lords impervious. Duration: 1D4+1 melee rounds (30 to 75 seconds); trapped demons feel it as 4D6 minutes.', 'Rifts World Book 25: China 2 p.105'),
('china-black-cloud-pearl-six-uses-a-day', 'Black Cloud Pearl (Six Uses a Day)', 'rifts', 'magic', NULL, 1000000, 'One million credits (printed 105).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Same pearl enchanted for six uses per day. Duration: six times a day for 1D4+5 years in China, 3 years outside. Note: Also listed by cross-reference under Magic Pearls, printed 108.', 'Rifts World Book 25: China 2 p.105'),
('china-binding-demon-catching-mirror', 'Binding Demon Catching Mirror', 'rifts', 'magic', NULL, 1000000, 'One million credits (printed 105).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 500, 'A Green Scarf Taoist Sect magic item (printed 101-114). Eight-sided I Ching mirror that entraps any demon looking fully into it; holds up to four; wielder can release or converse. Impervious to magic and demons. Duration: no time limit. The book disagrees with itself here: Printed 80 (Demon Catching Hero) prints M.D.C. 100 and calls the one million a replacement cost; printed 105 prints M.D.C. 500.', 'Rifts World Book 25: China 2 p.105'),
('china-fake-demon-catching-mirror', 'Fake Demon Catching Mirror', 'rifts', 'magic', NULL, 200, '200-400 credits (printed 105).', NULL, 0, NULL, NULL, NULL, NULL, 34, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Non-magical imitation for bluffing demons. Not sold by Green Scarves; any craftsman can make one.', 'Rifts World Book 25: China 2 p.105'),
('china-binding-demonic-mirror-of-truth', 'Binding Demonic Mirror of Truth', 'rifts', 'magic', NULL, 30000, '30,000 credits (printed 105-106).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'A Green Scarf Taoist Sect magic item (printed 101-114). Brass eight-sided mirror; reveals auras, invisible things and the true face of Goblins/demons disguised by magic or shape changing. Duration: 1 year (ancient ones last until broken).', 'Rifts World Book 25: China 2 p.105-106'),
('china-binding-ivory-faerie-blossom', 'Binding Ivory Faerie Blossom', 'rifts', 'magic', NULL, 35000, '35,000 credits (printed 106).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). 13 carved ivory flowers that attract and distract Faerie Folk and Lesser Nature Spirits for capture or conversation. Penalties: creature no initiative, -1 attack. Duration: amuses creature 2D6x10 minutes; magic 1 year.', 'Rifts World Book 25: China 2 p.106'),
('china-binding-lotus-petal-circle', 'Binding Lotus Petal Circle', 'rifts', 'magic', NULL, 420000, '420,000 credits (printed 106).', NULL, 0, 'close proximity; circle 4-6 ft (1.2-1.8 m)', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). 42 enchanted petals sprinkled in a circle trap a Lesser Demon, Goblin or Lesser Nature Spirit; broken if a second person steps in. Not Ghosts, Vampires, Greater Demons. Saving throw: Lesser none; Greater 10+ with bonuses. Duration: usually 1D4 hours per use; magic lasts 1D4+2 years in China, 1D4 years outside.', 'Rifts World Book 25: China 2 p.106'),
('china-binding-pipe-of-ling-lun', 'Binding Pipe of Ling Lun', 'rifts', 'magic', NULL, 500000, '500,000 credits for a Green Scarf flute; 10 million credits for ancient Binding Flute with no time limit (printed 106-107). An ancient one with no time limit: 10,000,000 credits.', NULL, 0, '1000 foot (305 m) radius', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Flute whose music stops fighting among humans and demons and brings calm; afterward demons -2 initiative, -1 attack, -20% skills for 1D6+1 rounds if fighting resumes. Saving throw: None. Duration: while played; magic 1 year. Used by: anyone skilled in wind instruments.', 'Rifts World Book 25: China 2 p.106-107'),
('china-binding-seal-of-the-green-scarf-celestial-master', 'Binding Seal of the Green Scarf Celestial Master', 'rifts', 'magic', NULL, 200000, '200,000 credits (printed 107).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Thrown iron seal that brands a Chinese demon with the Yang character; it must obey one command from the Celestial Master. Brand fades in 4D6 days. Duration: 1D4+2 years in China, 2 years outside.', 'Rifts World Book 25: China 2 p.107'),
('china-phoenix-eye-or-peacock-tail-fan', 'Phoenix Eye or Peacock Tail Fan', 'rifts', 'magic', NULL, 700000, '700,000 credits; rare (printed 107).', '1D10 (S.D.C. or M.D.) to dead, undead, Ghosts, Goblins, demons', 1, NULL, NULL, NULL, NULL, NULL, 888, 'A Green Scarf Taoist Sect magic item (printed 101-114). Peacock-feather fan that turns away animated dead (up to 1D10x10), cools, blows ghosts away, and can dispel a curse. Bonuses: half damage from Ghosts/Entities, see invisible, +2 save vs possession and Demonic Curses. Duration: as long as the item has M.D.C. I.S.P.: 60 I.S.P. plus permanent loss of 1D10 I.S.P. to dispel a Demonic Curse.', 'Rifts World Book 25: China 2 p.107'),
('china-white-fans-winds-of-submission', 'White Fans'' Winds of Submission', 'rifts', 'magic', NULL, 50000, '50,000 credits per pair (printed 107-108).', '1D6+1 per level of wielder (S.D.C. or M.D.)', 1, '15 feet (4.6 m) to strike', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Pair of white fans used together; gusts strike, parry, and impede demons (Spd -75%, attacks halved, bonuses +1 only). Duration: 1 year.', 'Rifts World Book 25: China 2 p.107-108');

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('china-fire-pearl', 'Fire Pearl', 'rifts', 'magic', NULL, 2500, '2,500 credits (printed 108).', '4D6 S.D.C. or M.D.', 1, '200 feet (61 m)', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Pearl becomes a thrown fireball when 6 I.S.P. is pumped in. Duration: 4 melee rounds to throw; one use. I.S.P.: 6 I.S.P.', 'Rifts World Book 25: China 2 p.108'),
('china-pearl-of-recuperation', 'Pearl of Recuperation', 'rifts', 'magic', NULL, 5000, '5000 credits (printed 108).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Swallowed, restores 3D6+6 Hit Points or 1D6+6 M.D., or cures drunkenness; one use; magic lasts 100 years or until used.', 'Rifts World Book 25: China 2 p.108'),
('china-pearls-of-knowledge', 'Pearls of Knowledge', 'rifts', 'magic', NULL, 15000, '15,000 credits per each pearl (printed 108).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Held in mouth: one pearl understands all languages, two also speak, three also read. Duration: 1 year.', 'Rifts World Book 25: China 2 p.108'),
('china-pearl-of-demon-strength', 'Pearl of Demon Strength', 'rifts', 'magic', NULL, 30000, '30,000 credits per each (printed 108).', 'punch 4D6 S.D.C. or 2D6 M.D.; or +2D6 M.D. if already Supernatural P.S.; spit 1D6x10 S.D.C. or 4D6 M.D.', 1, 'spit 200 feet (61 m)', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Held in fist gives Supernatural Strength punches, or can be spat like a cannonball. Duration: 1 year. Used by: anyone.', 'Rifts World Book 25: China 2 p.108'),
('china-pink-cloud-pearl-four-flights', 'Pink Cloud Pearl (Four Flights)', 'rifts', 'magic', NULL, 6000, '6,000 credits (printed 108).', NULL, 0, 'max height 1000 ft (305 m), speed 20 mph (32 km)', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Pearl makes a pink cloud flying platform carrying about three human-sized characters. I.S.P.: 6 I.S.P. per five minutes.', 'Rifts World Book 25: China 2 p.108'),
('china-pink-cloud-pearl-unlimited', 'Pink Cloud Pearl (Unlimited)', 'rifts', 'magic', NULL, 180000, '180,000 credits (printed 108).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Same pearl with unlimited uses for a year. Duration: 1 year. I.S.P.: 6 I.S.P. per five minutes.', 'Rifts World Book 25: China 2 p.108'),
('china-black-scarf', 'Black Scarf', 'rifts', 'magic', NULL, 25000, '25,000 credits (printed 108).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Black silk scarf with green trim worn at the neck. Bonuses: impervious to poison, +1 save vs magical vapors and disease. Duration: 1 year.', 'Rifts World Book 25: China 2 p.108'),
('china-climbing-scarf', 'Climbing Scarf', 'rifts', 'magic', NULL, 20000, '20,000 credits (printed 108-109).', NULL, 0, '20-25 feet (6.1-7.6 m) long', NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Knotted and tossed, it hangs in the air for climbing; falls after one hour. Duration: 1 year. Note: Cost is at the top of 109; heading and description on 108.', 'Rifts World Book 25: China 2 p.108-109'),
('china-green-yellow-scarf', 'Green & Yellow Scarf', 'rifts', 'magic', NULL, 40000, '40,000 credits (printed 109).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Gives the speed and reflexes of a snake. Bonuses: +1 attack per melee, +1D6 damage, +5 automatic dodge. Duration: 1 year.', 'Rifts World Book 25: China 2 p.109'),
('china-scarf-of-demon-binding', 'Scarf of Demon Binding', 'rifts', 'magic', NULL, 60000, '60,000 credits (printed 109).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Whip-like scarf that entangles Goblins, Lesser Demons and nature spirits; undoing takes 1D4+1 actions. Bonuses: +2 strike, +4 entangle; entangled demon loses half attacks and bonuses. Duration: 1 year.', 'Rifts World Book 25: China 2 p.109'),
('china-scarf-of-entrancement', 'Scarf of Entrancement', 'rifts', 'magic', NULL, 40000, '40,000 credits (printed 109).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Used in dancing; fascinates the opposite sex and slows others (no initiative). Not Ghosts, Entities, dragons, Faeries. Duration: 1 year.', 'Rifts World Book 25: China 2 p.109'),
('china-scarf-of-the-python', 'Scarf of the Python', 'rifts', 'magic', NULL, 35000, '35,000 credits (printed 109).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Wrapped from neck to wrist, gives cobra-like speed and reflexes. Bonuses: +1 attack per melee, +1D6 damage (crush too), +3 entangle, +5 automatic dodge. Duration: 1 year. The book disagrees with itself here: Title says python, description says cobra.', 'Rifts World Book 25: China 2 p.109'),
('china-viper-scarf-or-silk-vipers', 'Viper Scarf or Silk Vipers', 'rifts', 'magic', NULL, 80000, '80,000 credits (printed 109).', '+1D6 (S.D.C. or M.D.)', 1, NULL, NULL, NULL, NULL, NULL, 32, 'A Green Scarf Taoist Sect magic item (printed 101-114). Scarf ends become living snakes that attack and parry. Bonuses: +2 strike, +3 parry, +2 automatic dodge; two attacks each, four extra attacks. Duration: 1 year. I.S.P.: 12 I.S.P. per five minutes. The book disagrees with itself here: Each viper 32 M.D.C., but text later says the remaining viper fights until it takes 30 M.D.; book inconsistent.', 'Rifts World Book 25: China 2 p.109'),
('china-bone-swords-and-weapons', 'Bone Swords and Weapons', 'rifts', 'weapon', NULL, 50, '50-300 credits depending on size and quality (double for stone, triple for jade/silver) (printed 110).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Bone weapons do normal S.D.C. to mortals but the same dice as M.D. to demons vulnerable to bone. Wood, silver, jade, stone work the same for creatures vulnerable to them. Typical damage: Axe, Small/Hatchet 1D6; Axe, Large/Battle 1D10 or 2D6 (metal may do 3D6); Club/Cudgel, Small 1D6; Club/Cudgel, Medium 2D4 or 1D8; Club/Cudgel, Large 2D6 or 1D10; Knife, Small 1D4; Knife, Typical 1D6; Knife, Large 1D6+1 or 2D4; Spear, Typical 1D10 or 2D6; Staff, Small/Walking Stick/Cane 1D6; Staff, Medium or Slender 2D4 or 1D10; Staff, Large or Heavy 2D6 to 3D6; Sword, Short 1D6; Sword, Medium 1D10 to 2D6; Sword, Large 3D6 to 2D10; Giant-Size Weapon add one additional die.', 'Rifts World Book 25: China 2 p.110'),
('china-cobras-tooth-dagger', 'Cobra''s Tooth Dagger', 'rifts', 'weapon', NULL, 90000, '90,000 credits to buy new; rare; re-enchant 50,000 credits (printed 110-111). Re-enchanting: 50,000 credits.', '2D6 S.D.C./Hit Points to mortals, 2D6 M.D. to creatures of magic, Goblins, demons', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Hooked bone knife; victim feels sick 3D6 minutes and cannot recover I.S.P. or draw ambient I.S.P./Chi. Duration: I.S.P. block magic 1 year.', 'Rifts World Book 25: China 2 p.110-111'),
('china-tigers-claw-club', 'Tiger''s Claw Club', 'rifts', 'weapon', NULL, 40000, '40,000 credits (printed 111).', '2D6 S.D.C. mortals, 2D6 M.D. Goblins/demons, 3D6 M.D. Nature Spirits/creatures of magic; double to beings vulnerable to bone or claws', 1, NULL, NULL, NULL, NULL, NULL, 300, 'Club ending in a real tiger claw. Bonuses: +1 save vs magic, Demonic Curses, mind control, possession from Nature Spirits/demons/creatures of magic. Duration: indefinite.', 'Rifts World Book 25: China 2 p.111'),
('china-sword-of-demon-hunting-the-hunter-blade', 'Sword of Demon Hunting: The Hunter Blade', 'rifts', 'weapon', NULL, 650000, '650,000 credits (printed 111).', '2D6 S.D.C. mortals, 3D6 M.D. demons and evil supernatural', 1, 'senses demons within 200 ft (61 m)', NULL, NULL, NULL, NULL, 500, 'Detection blade: senses demons, sees through disguises, sees invisible demons and evil Entities, +20% Tracking; stab with one M.D. dispels disguise. The 500 M.D.C. is the section line on printed 111 that most demon hunter weapons have 500. Bonuses: +1 strike. Used by: Demon Quellers.', 'Rifts World Book 25: China 2 p.111'),
('china-sword-of-demon-hunting-the-hunter-slayer-blade', 'Sword of Demon Hunting: The Hunter-Slayer Blade', 'rifts', 'weapon', NULL, 1500000, '1.5 to 2 million credits (printed 111).', '3D6 S.D.C. mortals, 3D6 M.D. creatures of magic, 5D6 M.D. Lesser/Greater Demons (double from behind or nat 18-20), 1D10x10 M.D. Demon Lords/Yama Kings/Alien Intelligences', 1, NULL, NULL, NULL, NULL, NULL, 300, 'Wide executioner-style sword, one-handed at P.S. 18+; returns to owner when thrown after bonding. Bonuses: +2 strike.', 'Rifts World Book 25: China 2 p.111'),
('china-sword-of-demon-hunting-the-demon-hunter-defender', 'Sword of Demon Hunting: The Demon Hunter Defender', 'rifts', 'weapon', NULL, 800000, '800,000 credits (printed 111).', '1D6 S.D.C. mortals, 3D6 M.D. demons and evil supernatural', 1, NULL, NULL, NULL, NULL, NULL, 500, 'Sickle-shaped blade; wielder cannot be bound, tied, entangled or held by demons while it is drawn. The 500 M.D.C. is the section line on printed 111 that most demon hunter weapons have 500. Bonuses: +1 disarm, +2 parry, +2 save vs Horror Factor, +3 vs Demonic Curses, +4 vs Demonic Disease/Illness, +5 vs poison/breath/vapor, +6 vs possession.', 'Rifts World Book 25: China 2 p.111'),
('china-sword-of-demon-hunting-the-demon-hunters-vengeance', 'Sword of Demon Hunting: The Demon Hunter''s Vengeance', 'rifts', 'weapon', NULL, 950000, '950,000 credits (printed 111-112).', '2D6 S.D.C. mortals, 4D6 M.D. demons and creatures of supernatural evil', 1, NULL, NULL, NULL, NULL, NULL, 500, 'Long silver blade; wounds cannot be bio-regenerated for 3 hours per level of user; also 4D6 M.D. on creatures of magic without stopping regeneration. The 500 M.D.C. is the section line on printed 111 that most demon hunter weapons have 500. Bonuses: +1 attack per melee, +3 strike, +1 disarm, triple damage on nat 19 or 20. Note: Damage line starts at foot of 111 and finishes top of 112.', 'Rifts World Book 25: China 2 p.111-112');

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('china-demon-fighter-sword', 'Demon Fighter Sword', 'rifts', 'weapon', NULL, 25000, '25,000 credits (printed 112).', '2D6+2 S.D.C. mortals, 3D6 M.D. demons and other M.D. opponents', 1, NULL, NULL, NULL, NULL, NULL, 300, 'Lion''s Head sword; never dulls, indestructible by fire; may also be small axe, battle axe or spear. Bonuses: +1 parry, +1 disarm.', 'Rifts World Book 25: China 2 p.112'),
('china-classic-demon-slayer-sword', 'Classic Demon Slayer Sword', 'rifts', 'weapon', NULL, 80000, '80,000 credits (printed 112).', '2D6 S.D.C. mortals, 2D6 M.D. creatures of magic, 5D6 M.D. Lesser/Greater Demons, 1D6x10 M.D. Demon Lords/Yama Kings/Alien Intelligences', 1, NULL, NULL, NULL, NULL, NULL, 900, 'Silver blade in ivory handle; eternally sharp; may also be axe or spear. Bonuses: +1 strike.', 'Rifts World Book 25: China 2 p.112'),
('china-monster-slayer-swords-of-the-three-virtuous-ways', 'Monster Slayer Swords of the Three Virtuous Ways', 'rifts', 'weapon', NULL, 50000, '50,000 credits for the pair (printed 112).', 'each blade 3D6 S.D.C. mortals, 3D6+12 M.D. demons, undead, Dead and Damned, evil supernatural', 1, NULL, NULL, NULL, NULL, NULL, 400, 'Pair of swords that activate only when two different warriors wield them together. Bonuses: paired wielders +2 initiative, +2 parry for partner. Used by: two warriors, female/Yin and male/Yang, side by side. Note: 400 M.D.C. each.', 'Rifts World Book 25: China 2 p.112'),
('china-demon-possessed-slayer-immortal-blade', 'Demon Possessed Slayer (Immortal Blade)', 'rifts', 'weapon', NULL, 4000000, '4-8 million credits (printed 112-113).', '4D6 S.D.C. mortals, 4D6 M.D. demons and evil supernatural, 6D6 M.D. Demon Quellers/Celestial Court heroes, 2D6x10 M.D. dragons, demigods, gods of good', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Sword possessed by an evil spirit that tempts its owner; indestructible; 13 secret powers granted only for evil acts. I.Q. 1D6+18, M.E. 1D6+16, M.A. 1D6+16; alignment Aberrant 15%, Miscreant 35%, Diabolic 30%, Anarchist 20%. Bonuses: +1 attack per melee, +1 strike and parry, +2 save vs Horror Factor, +2 vs possession.', 'Rifts World Book 25: China 2 p.112-113'),
('china-sword-of-heavenly-light', 'Sword of Heavenly Light', 'rifts', 'weapon', NULL, 500000, '500,000 to 600,000 credits for a pair; a single one does one die less damage (printed 113-114).', '3D6 S.D.C. or M.D. vs flesh and blood; 3D10 vs Ghosts, Entities, energy beings', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Pair of mercury-like rapiers; plunged into the Dead and Damned or Western Vampire it freezes them; reveals the invisible. Used by: heroes of good or Unprincipled alignment, and Demon Quellers; others -6 strike and only 1D6.', 'Rifts World Book 25: China 2 p.113-114'),
('china-green-scarf-light-armor', 'Green Scarf Light Armor', 'rifts', 'armor', NULL, 12000, '12,000 to 15,000 credits non-environmental, double for environmental (printed 114).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). No maneuverability penalty. M.D.C.: helmet 25, main body 30-40.', 'Rifts World Book 25: China 2 p.114'),
('china-green-scarf-medium-armor', 'Green Scarf Medium Armor', 'rifts', 'armor', NULL, 20000, '20,000 to 30,000 credits non-environmental, double for environmental (printed 114).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). -10% on Acrobatics, Climb, Prowl, Swim. M.D.C.: helmet 40, main body 45-65.', 'Rifts World Book 25: China 2 p.114'),
('china-green-scarf-heavy-armor', 'Green Scarf Heavy Armor', 'rifts', 'armor', NULL, 40000, '40,000 to 50,000 credits non-environmental, double for environmental (printed 114).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). -20% on Acrobatics, Climb, Prowl, Swim. M.D.C.: helmet 60, arms 30, legs 40, main body 80-100.', 'Rifts World Book 25: China 2 p.114'),
('china-demon-armor-partial-m-d-c', 'Demon Armor, Partial (M.D.C.)', 'rifts', 'armor', NULL, 23000, '23,000 credits (printed 114).', NULL, 0, NULL, NULL, NULL, 14, NULL, 60, 'A Green Scarf Taoist Sect magic item (printed 101-114). Upper body protected with horned helmet; Horror Factor 10; spiked shoulders +1D8 M.D. body block, spikes +1D6 M.D. punch/elbow/head/knee. M.D.C.: 60 (main body).', 'Rifts World Book 25: China 2 p.114'),
('china-demon-armor-partial-s-d-c', 'Demon Armor, Partial (S.D.C.)', 'rifts', 'armor', NULL, 4000, '4,000 credits (printed 114).', NULL, 0, NULL, NULL, NULL, 14, 140, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). S.D.C. variant of the partial suit.', 'Rifts World Book 25: China 2 p.114'),
('china-demon-armor-full-suit', 'Demon Armor, Full Suit', 'rifts', 'armor', NULL, 45000, '45,000 credits for basic non-environmental suit (printed 114).', NULL, 0, NULL, NULL, NULL, NULL, NULL, 113, 'A Green Scarf Taoist Sect magic item (printed 101-114). Full black or gray leather armor covered in spikes and horns; Horror Factor 13. M.D.C.: Hands 18, Arms 30, Legs 36, Helmet 60, Main Body 113.', 'Rifts World Book 25: China 2 p.114'),
('china-demon-armor-environmental-system', 'Demon Armor Environmental System', 'rifts', 'armor', NULL, 11000, 'Add 11,000 credits (printed 114).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Add-on to the full suit.', 'Rifts World Book 25: China 2 p.114'),
('china-demon-armor-self-healing-enchantment', 'Demon Armor Self-Healing Enchantment', 'rifts', 'armor', NULL, 250000, '250,000 credits; re-enchant 250,000 credits yearly (printed 114).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Green Scarf Taoist Sect magic item (printed 101-114). Bio-regenerates 2D6 M.D.C. per minute; destroyed if main body reaches zero. Duration: 1 year.', 'Rifts World Book 25: China 2 p.114'),
('china-stalks-of-fortune', 'Stalks of Fortune', 'rifts', 'magic', NULL, NULL, 'No price printed (printed 65).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Fifty milfoil stalks for I Ching readings; 60% +2% per level success; also dowsing +20%.', 'Rifts World Book 25: China 2 p.65'),
('china-soothsayer-stone-ax', 'Soothsayer Stone Ax', 'rifts', 'weapon', NULL, NULL, 'No price printed (printed 65).', '2D4 S.D.C. mortals/structures, 2D6 M.D. demons and Goblins; double to beings vulnerable to stone', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Hatchet-sized stone blade on willow handle; evil supernatural beings cannot touch it without dread.', 'Rifts World Book 25: China 2 p.65'),
('china-peach-wood-knife', 'Peach-Wood Knife', 'rifts', 'weapon', NULL, NULL, 'No price printed (printed 65).', '1D6 (S.D.C. or M.D.)', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Peach-wood knife.', 'Rifts World Book 25: China 2 p.65'),
('china-peach-wood-sword', 'Peach-Wood Sword', 'rifts', 'weapon', NULL, NULL, 'No price printed (printed 65).', '2D6 (S.D.C. or M.D.)', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Peach-wood sword, offered as alternative to the knife.', 'Rifts World Book 25: China 2 p.65'),
('china-peach-pits', 'Peach Pits', 'rifts', 'weapon', NULL, NULL, 'No price printed (printed 65).', '1D6+1 (S.D.C. or M.D.)', 1, '20 feet (6.1 m)', NULL, NULL, NULL, NULL, NULL, 'Spit peach pits that hit demons, Goblins, Ghosts. Bonuses: +1 save vs Demonic Curses, vapor/breath, disease when held in mouth.', 'Rifts World Book 25: China 2 p.65'),
('china-peach-tree-protection-charm', 'Peach Tree Protection Charm', 'rifts', 'magic', NULL, NULL, 'No price printed (printed 66).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Peach-wood figure plus 1D4 tiger paintings; blocks Goblins, Ghosts, Lesser Demons from a doorway.', 'Rifts World Book 25: China 2 p.66'),
('china-peach-tree-wood-branches', 'Peach Tree Wood Branches', 'rifts', 'magic', NULL, NULL, 'No price printed (printed 66).', '1 point (S.D.C. or M.D.)', 1, '15 feet (4.6 m) thrown', NULL, NULL, NULL, NULL, NULL, 'Staked around a site to keep out Lesser Demons, Goblins, Ghosts; soaked in water with 8 I.S.P. to cure stomach ills.', 'Rifts World Book 25: China 2 p.66');

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('china-peach-blossom-petals', 'Peach Blossom Petals', 'rifts', 'magic', NULL, NULL, 'No price printed (printed 66).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Good-fortune petals; tea halves effect of demonic illness; fresh petals repel Lesser Demons (save 12+). I.S.P.: 3 I.S.P. to rejuvenate a petal.', 'Rifts World Book 25: China 2 p.66'),
('china-sweeping-broom', 'Sweeping Broom', 'rifts', 'weapon', NULL, NULL, 'No price printed (printed 66).', '4D6 M.D. to demons, Ghosts, Goblins, evil nature spirits with either end; 1D10 S.D.C. to mortals with handle; 1 point with bristles; Sunlight Attack 6D6 M.D. to beings vulnerable to sunlight', 1, 'sweeping pushes spirits 10 ft (3 m)', NULL, NULL, NULL, NULL, NULL, 'Ordinary-looking 5-6 ft (1.5-1.8 m) broom, the Soothsayer''s best weapon. Bonuses: impervious to disease while held; +4 save vs disease-type Demonic Curses. I.S.P.: 10 I.S.P. for Sunlight Attack.', 'Rifts World Book 25: China 2 p.66'),
('china-book-of-ten-thousand-demons-wan-gui-yao', 'Book of Ten Thousand Demons (Wan Gui Yao)', 'rifts', 'magic', NULL, NULL, 'Replacement cost: priceless (only a 10th level or better Tao Shih Celestial Calligrapher can duplicate) (printed 80).', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Lists names and descriptions of 10,000 demons; name lookup chance 01-02% minions up to 01-90% Demon Lords. Used by: Great Demon Catching Hero.', 'Rifts World Book 25: China 2 p.80'),
('china-tourist-fan', 'Tourist Fan (Rifts China)', 'rifts', 'weapon', NULL, 1, 'usually 1 credit or less (printed 23).', 'With White Jade Fan: thrust 1D8, slash 1D6, thrown 1D4', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A fan as a weapon for the White Jade Fan style (printed 23): paper, plastic or cheap material; easily broken. The fan itself has 1D4 S.D.C.', 'Rifts World Book 25: China 2 p.23'),
('china-bamboo-fan', 'Bamboo Fan (Rifts China)', 'rifts', 'weapon', NULL, NULL, '1D4 credits (printed 23).', 'With White Jade Fan: thrust 1D8, slash 1D6, thrown 1D4', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A fan as a weapon for the White Jade Fan style (printed 23): seasoned bamboo slats, unornamented, good weapon. The fan itself has 3D6 S.D.C.', 'Rifts World Book 25: China 2 p.23'),
('china-silk-fan', 'Silk Fan (Rifts China)', 'rifts', 'weapon', NULL, NULL, '2D6 credits (no needles) to 3D10x100 credits (8-16 needles) (printed 23).', 'With White Jade Fan: thrust 1D8, slash 1D6, thrown 1D4; needles without poison do 1 S.D.C. each', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A fan as a weapon for the White Jade Fan style (printed 23): up to 16 needles, usually poisoned, flicked one or two at a time. The fan itself has 2D4+4 S.D.C.', 'Rifts World Book 25: China 2 p.23'),
('china-iron-fan', 'Iron Fan (Rifts China)', 'rifts', 'weapon', NULL, NULL, '3D6x10 credits (printed 23).', 'With White Jade Fan: thrust 1D8, slash 1D6, thrown 1D4; +3 to damage', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A fan as a weapon for the White Jade Fan style (printed 23): sharpened edges and points; ceremonial and military. The fan itself has 2D6+24 S.D.C.', 'Rifts World Book 25: China 2 p.23'),
('china-jade-fan', 'Jade Fan (Rifts China)', 'rifts', 'weapon', NULL, NULL, '4D10x100 Green Jade; 2D6x1,000 Red or Blue Jade; 3D6x2,000 White Jade (printed 23).', 'With White Jade Fan: thrust 1D8, slash 1D6, thrown 1D4', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A fan as a weapon for the White Jade Fan style (printed 23): precious jade, dozens of hours of work. The fan itself has 1D10 S.D.C.', 'Rifts World Book 25: China 2 p.23');

SELECT 'China 2 adds 68 magic gear rows' AS assertion, count(*) AS got, 68 AS want
  FROM gear WHERE slug IN ('china-binding-blinders', 'china-binding-chains', 'china-binding-demon-snare', 'china-binding-demon-choker-snare', 'china-binding-demon-stamp', 'china-binding-hand-stock', 'china-binding-head-hand-stock', 'china-binding-leash-collar', 'china-binding-bell-of-bliss', 'china-black-cloud-pearl-single-use', 'china-black-cloud-pearl-six-uses-a-day', 'china-binding-demon-catching-mirror', 'china-fake-demon-catching-mirror', 'china-binding-demonic-mirror-of-truth', 'china-binding-ivory-faerie-blossom', 'china-binding-lotus-petal-circle', 'china-binding-pipe-of-ling-lun', 'china-binding-seal-of-the-green-scarf-celestial-master', 'china-phoenix-eye-or-peacock-tail-fan', 'china-white-fans-winds-of-submission', 'china-fire-pearl', 'china-pearl-of-recuperation', 'china-pearls-of-knowledge', 'china-pearl-of-demon-strength', 'china-pink-cloud-pearl-four-flights', 'china-pink-cloud-pearl-unlimited', 'china-black-scarf', 'china-climbing-scarf', 'china-green-yellow-scarf', 'china-scarf-of-demon-binding', 'china-scarf-of-entrancement', 'china-scarf-of-the-python', 'china-viper-scarf-or-silk-vipers', 'china-bone-swords-and-weapons', 'china-cobras-tooth-dagger', 'china-tigers-claw-club', 'china-sword-of-demon-hunting-the-hunter-blade', 'china-sword-of-demon-hunting-the-hunter-slayer-blade', 'china-sword-of-demon-hunting-the-demon-hunter-defender', 'china-sword-of-demon-hunting-the-demon-hunters-vengeance', 'china-demon-fighter-sword', 'china-classic-demon-slayer-sword', 'china-monster-slayer-swords-of-the-three-virtuous-ways', 'china-demon-possessed-slayer-immortal-blade', 'china-sword-of-heavenly-light', 'china-green-scarf-light-armor', 'china-green-scarf-medium-armor', 'china-green-scarf-heavy-armor', 'china-demon-armor-partial-m-d-c', 'china-demon-armor-partial-s-d-c', 'china-demon-armor-full-suit', 'china-demon-armor-environmental-system', 'china-demon-armor-self-healing-enchantment', 'china-stalks-of-fortune', 'china-soothsayer-stone-ax', 'china-peach-wood-knife', 'china-peach-wood-sword', 'china-peach-pits', 'china-peach-tree-protection-charm', 'china-peach-tree-wood-branches', 'china-peach-blossom-petals', 'china-sweeping-broom', 'china-book-of-ten-thousand-demons-wan-gui-yao', 'china-tourist-fan', 'china-bamboo-fan', 'china-silk-fan', 'china-iron-fan', 'china-jade-fan');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-a-china-2-magic-gear.sql');
