-- The NGR Field Mechanic O.C.C., Rifts World Book 5: Triax and the NGR p.162.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-ngr-field-mechanic-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- Stub rows for anything the class references that the catalog lacks.
-- The "STUB" marker is load-bearing: it is how the gear importer later
-- recognises a row as still needing stats.
INSERT OR IGNORE INTO gear (slug, name, system, description, source_book) VALUES ('t-13-field-mechanic-body-armor', 'T-13 Field Mechanic Body Armor', 'rifts', 'STUB ' || char(8212) || ' created by class import, needs stats', 'Rifts World Book 5: Triax and the NGR p.162');


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'ngr-field-mechanic', 'NGR Field Mechanic', 'rifts', '---
id: ngr-field-mechanic
occ_group: men-of-arms
name: NGR Field Mechanic
system: rifts
source_book: Rifts World Book 5: Triax and the NGR p.162
category: occ
attribute_requirements: { IQ: 9 }
starting_money: "2d4x1000"
skills:
  occ_skills:
    - { name: "Mathematics: Basic", base: 65, per_level: 5, note: "+20%" }
    - { name: "Mathematics: Advanced", base: 55, per_level: 5, note: "+10%" }
    - { name: "Literacy: Euro", base: 60, per_level: 5, note: "+30%" }
    - { name: "Language: Euro", base: 80, per_level: 5, note: "+30%" }
    - { name: "Language: Other", base: 60, per_level: 5, note: "Select one additional language (+10%)." }
    - { name: "Radio: Basic", base: 65, per_level: 5, note: "+20%" }
    - { name: "Computer Operation", base: 50, per_level: 5, note: "+10%" }
    - { name: "Electrical Engineer", base: 50, per_level: 5, note: "+20%" }
    - { name: "Robot Electronics", base: 50, per_level: 5, note: "+20%" }
    - { name: "Mechanical Engineer", base: 45, per_level: 5, note: "+20%" }
    - { name: "Robot Mechanics", base: 40, per_level: 5, note: "+20%" }
    - { name: "Weapons Engineer", base: 45, per_level: 5, note: "+20%" }
    - { name: "Weapon Systems", base: 50, per_level: 5, note: "+10%" }
    - { name: "Hover Craft (ground)", base: 60, per_level: 5, note: "+10%; the book prints Pilot Hover Vehicles." }
    - { name: "Robots & Power Armor", base: 62, per_level: 3, note: "+6%" }
    - { name: "Robot Combat: Basic", base: 0, per_level: 0 }
    - { name: "Running", base: 0, per_level: 0 }
    - { name: "W.P. Energy Rifle", base: 0, per_level: 0 }
    - { name: "Hand to Hand: Basic", base: 0, per_level: 0, note: "May be changed to Expert (or Assassin if evil) for two O.C.C. Related skills." }
  occ_related_skills:
    count: 4
    categories:
      - { name: "Communications", bonus: 10 }
      - "Domestic"
      - { name: "Electrical", bonus: 20 }
      - { name: "Mechanical", bonus: 20 }
      - { name: "Medical", only: ["First Aid"], bonus: 10 }
      - { name: "Military", bonus: 10 }
      - { name: "Physical", except: ["Acrobatics", "Wrestling"] }
      - { name: "Pilot", bonus: 10 }
      - { name: "Pilot Related", bonus: 10 }
      - { name: "Rogue", bonus: 5 }
      - "Science"
      - { name: "Technical", bonus: 10 }
      - "Weapon Proficiencies"
    schedule:
      - { level: 4, count: 1 }
      - { level: 8, count: 1 }
      - { level: 12, count: 1 }
  secondary_skills:
    count: 0
    schedule:
      - { level: 2, count: 2 }
      - { level: 4, count: 2 }
      - { level: 7, count: 2 }
      - { level: 10, count: 2 }
      - { level: 13, count: 2 }
equipment_starting:
  - { item_id: "t-13-field-mechanic-body-armor", qty: 1 }
  - { item_id: "tx-42-laser-pulse-rifle", qty: 1 }
  - { item_id: "smoke-grenade", qty: 4 }
  - { item_id: "fragmentation-grenade", qty: 2 }
  - { item_id: "signal-flare", qty: 6 }
  - { item_id: "survival-knife", qty: 1 }
  - { item_id: "flashlight", qty: 1 }
  - { item_id: "binoculars", qty: 1 }
  - { item_id: "hand-held-computer", qty: 1 }
  - { item_id: "utility-belt", qty: 1 }
  - { item_id: "air-filter", qty: 1 }
  - { item_id: "gas-mask", qty: 1 }
  - { item_id: "portable-language-translator", qty: 1 }
  - { item_id: "walkie-talkie", qty: 1 }
  - { item_id: "uniform", qty: 2 }
  - { item_id: "dress-uniform", qty: 1 }
extraction_notes: |
  - Shares its experience ladder on printed 224 with the Communications Officer
    and the Medic/Medical Officer; the table heads all three together.
  - Mathematics: Advanced is printed "(10%)" with no plus sign, alone among the
    fourteen percentages in this entry. Read as +10% and stored as 55, the
    catalog''s 45 plus 10. The alternative reading - a FIXED 10% - would be a
    skill worse than the untrained base, which no Palladium class prints.
  - Espionage and Wilderness are printed as None and are therefore absent from
    occ_related_skills rather than listed empty.
  - The standard issue names a "T-42 or T-30 rifle". Both are TX- weapons in the
    book''s own weapons chapter: the TX-42 Laser Pulse Rifle on printed 145 and
    the TX-30 Ion Pulse Rifle on printed 145. The TX-42 is stored as the default
    and the choice is in the body; the same T-42/TX-42 slip is recorded on the
    NGR Infantry Soldier.
  - Six issued items are NOT stubbed, because the book names them only in this
    list and stats none of them: the laser distancer, the portable tool kit, the
    large tool box and tools, the four overalls, and the portable laser torch
    and laser wand - which the entry itself defers to Wilk''s rather than
    statting. They are in the body.
  - The universal hand or headjack and two cybernetic augmentations the
    character starts with are cybernetics rather than carried gear, and the two
    are an unrestricted pick from any category. In the body.
  - starting_money is the first-level savings the book prints, 2D4x1000. The
    3000 credit monthly salary and the 4200 a month for 9th level and higher
    are pay rather than starting coin and are in the body.
  - Skill bases are catalog base plus the printed bonus, already added.
---

## Lore

A highly regarded specialist in the repair, modification and maintenance of robots, power armour, vehicles and machines. The life line of the mechanised division, and key personnel in an army and a society that lean so heavily on robots, cybernetics and machines.

Field mechanics are regularly in the middle of combat making repairs or helping retrieve robots and vehicles, and they occasionally slip behind enemy lines with commandos or a reconnaissance team to assess enemy armour or to break into and sabotage enemy systems. The NGR issues them special armour, optics, cybernetics and equipment.

Alignment: Any.

## Rank and pay

Standard military, private to lieutenant colonel. Salary is 3000 credits a month, rising to 4200 for ninth level and higher, with quarters, food, clothing and medical access provided. Out of the field the mechanic shares a three bedroom apartment with two other mechanics.

## Cybernetics

A universal hand or headjack plus two cybernetic augmentations from any category, usually sensory - a gyro-compass, amplified hearing and the like. Not stored, because the choice is unrestricted and the catalog has no cybernetics picker.

## GM Notes

Issued alongside the stored equipment, and not given catalog rows because the book stats none of them: a laser distancer, a portable tool kit, a large tool box and tools, four overalls, and a portable laser torch and laser wand - the entry defers both to Wilk''s rather than stating figures. The issued rifle is a TX-42 or a TX-30.

Equipment available upon assignment includes T-11 Enhanced body armour, the X-60 Flanker, the T-100 Eagle jet pack, additional weapons, energy clips, vehicles and equipment, plus low to mid-level access to military bases, garages, hangars, storage bays and repair shops. The field mechanic usually gets priority for robot replacement parts, T-13 and T-11 body armour, tools and repair facilities.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'ngr-field-mechanic');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'ngr-field-mechanic';
SELECT count(*) AS stub_gear FROM gear WHERE slug IN ('t-13-field-mechanic-body-armor');

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-ngr-field-mechanic-class.sql');
