-- Rifts World Book 6: South America - its gear. 30 new rows: the Republic of
-- Colombia's C-series weapons (printed 22-24), the Biomancers' bio-weapons and
-- bio-armor (printed 69-70), the Weapons of Manoa (printed 91-92) and Cibola's
-- drugs and potions (printed 143-144).
--
-- NOT HERE: Cibola's three Naruni weapons (printed 139). The NE-4, NE-10 and
-- NE-200 are already in the catalog from Phase World p.117-118 with the same
-- weight, damage, range, payload and price; this book calls the pistol
-- "NE-4P". catalog-diff matched the rifle and machinegun by name and put the
-- pistol at distance 1.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-south-america-gear.sql
--
-- ALL 30 ARE NEW - catalog-diff --table gear --remote, 2026-09-25, run
-- immediately before this file was written.
--
-- EVERY NUMBER on printed 22-24 WAS READ OFF A RENDER: the text layer sets
-- those stat blocks away from their headings. The rest were read from the
-- text layer and checked against renders. The book's ink drops some minus
-- signs ("is 2 to save" for Dream); those are stored as the penalty they are.
--
-- CONVENTIONS:
--   * The bio-weapons are 'magic', like the catalog's other grown and enchanted
--     items. The book prices them only in P.P.E. to create; cost is NULL and
--     the P.P.E. is in cost_note. The Enchanted Spears, Swords & Clubs heading
--     gives three weapons with three damage lines, so it is three rows.
--   * Bone Blade is one row with its three sizes in damage, as the book prints
--     one entry for them.
--   * The Manoan enchanted armors are 'armor' with the book's "most weigh
--     around 25 pounds" as weight; the TW weapons are 'weapon'; the TW energy
--     cell is 'magic' and unpriced ("roughly the same as a normal E-clip").
--   * The drugs are 'gear' with a drug- slug, following Triax's drugs.
--   * Where the book prices a range, cost is the low end and cost_note the range.
--   * The Cat's Gauntlet and Simba's War Club are not here: they ride with their
--     gods' notable NPC rows (docs/surveys/south-america.md).

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('rc-10-laser-pistol', 'RC-10 Laser Pistol', 'rifts', 'weapon', 2, 9000, NULL, '1D6 M.D.', 1, '1000 feet (305 m)', '20 shots', 'Standard', NULL, NULL, NULL, 'Low-powered Colombian laser pistol, the best local technology can make. Popular with street gangs and standard issue for local police; serious soldiers scorn its low damage. Weight 2 lbs (0.9 kg).', 'Rifts World Book 6: South America p.22'),
('rc-15-laser-rifle', 'RC-15 Laser Rifle', 'rifts', 'weapon', 21, 14500, NULL, '3D6+6 M.D.', 1, '1000 feet (305 m)', '20 shots', 'Standard', NULL, NULL, NULL, 'Standard issue rifle of the Colombian army. Heavy, short-ranged for a rifle and lacking the features of North American or European designs, but rugged, reliable in hot, humid jungle, and hard-hitting - many call it an energy shotgun. Weight 21 lbs (9.5 kg).', 'Rifts World Book 6: South America p.23'),
('dragon-1-plasma-projector', 'Dragon-1 Plasma Projector', 'rifts', 'weapon', 21, 20000, NULL, '5D6 M.D.', 1, '1200 feet (366 m)', '12 shots', 'Standard', NULL, NULL, NULL, 'Colombian heavy plasma cannon resembling the Coalition C-27 (Rifts RPG p.203), without the targeting scope and with a lighter charge. Usually issued to Anti-Monsters or heavy weapon squads. Weight 21 lbs (9.5 kg).', 'Rifts World Book 6: South America p.23'),
('rp-c20-rocket-pistol', 'RP-C20 Rocket Pistol', 'rifts', 'weapon', 4, 14000, '14,000 credits for the pistol; 80 credits per standard explosive round, 50 per wooden warhead round.', '3D6 M.D. standard explosive round; wooden warhead 1 M.D. to normal targets, 4D6 to vampires', 1, '1200 feet (366 m)', '9 shots', 'Standard', NULL, NULL, NULL, 'Based on a pre-Rifts Argentine prototype: a gas propellant tank launches each round at bullet speed, then air vents ignite its jet fuel and it flies on as an explosive-tipped rocket, giving good range and penetration. "C" series weapons are made only at Camargo, in an Argentine-sponsored factory that survived the Coming of the Rifts. Wooden warheads are for anti-vampire work. Weight 4 lbs (1.8 kg).', 'Rifts World Book 6: South America p.23'),
('rr-c40-rocket-rifle', 'RR-C40 Rocket Rifle', 'rifts', 'weapon', 21, 35000, '35,000 credits for the rifle; 80 credits per standard round, 50 per wooden warhead round.', '3D6 M.D. single round; 1D4x10 M.D. burst of 10. Wooden warheads: 1 M.D. to normal targets (1D4 M.D. burst), 4D6 to vampires (1D6x10 burst)', 1, '1200 feet (366 m)', '60 or 100 shot ammo clip', 'Standard; semi-automatic or automatic by selector switch', NULL, NULL, NULL, 'Rifle version of the RP-C20, firing the same rocket cartridge, with a selector for semi-automatic or automatic fire and a larger magazine. Weight 21 lbs (9.5 kg).', 'Rifts World Book 6: South America p.24'),
('rar-c15-rocket-auto-cannon-rifle', 'RAR-C15 Rocket Auto-cannon Rifle', 'rifts', 'weapon', 50, 65000, NULL, '3D6+5 M.D. single round; 1D4x10 M.D. short burst (8 rounds); 2D4x10 M.D. long burst (20 rounds). Wooden warheads: 1 M.D. to normal targets (1D4 M.D. burst), 4D6 to vampires, 1D6x10 short burst, 2D6x10 long burst', 1, '2000 feet (610 m)', '200 round belt (ten long or 25 short bursts), or a 48 round magazine', 'Standard', NULL, NULL, NULL, 'A smaller, lighter rifle version of the RA-C15 tripod weapon, for robots, cyborgs, power armor troops and characters of P.S. 24 or more. Anyone weaker is -10 to strike and can barely lift and aim it, unless it is vehicle- or tripod-mounted and crewed by two operators with a combined P.S. of 24+. Loaded with solid wood warheads against vampires. Weight 50 lbs (22.68 kg).', 'Rifts World Book 6: South America p.24'),
('ra-c15-rocket-auto-cannon', 'RA-C15 Rocket Auto-cannon', 'rifts', 'weapon', 70, 85000, NULL, '4D6 M.D. per round; 1D6x10 M.D. short burst (8 rounds); 2D6x10 M.D. long burst (20 rounds). Wooden warheads: 2 M.D. to normal targets (2D6 M.D. long burst), 6D6 to vampires, 2D6x10 short burst, 3D6x10 long burst', 1, '2600 feet (792 m)', '400 round belt (20 long or 50 short bursts), or a 48 round magazine', 'Standard', NULL, NULL, NULL, 'Crew-served heavy rocket weapon, vehicle-mounted or used as a squad''s tripod support gun; a two or three man crew with a combined strength of 30. Fires a larger rocket than the rifles, from a long magazine or a belt-fed drum. Weight 70 lbs (31.7 kg).', 'Rifts World Book 6: South America p.24'),
('enchanted-wooden-club', 'Enchanted Wooden Club', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 80 P.P.E. (Maga Island / Bahia Kingdom markets).', '1D6 S.D.C., or 2D6 M.D. with the bio-energy aura active', 1, NULL, 'Aura activates six times, 5 minutes (20 melee rounds) each; recharge at a ley line or nexus, or a mage spends 30 P.P.E.', NULL, NULL, NULL, NULL, 'Lesser bio-weapon: fire-hardened wood charged with magic into a mega-damage structure (1D4x100 M.D.C., which matters only when someone tries to break it; it can parry M.D. weapons safely). On a mental command costing one melee action the owner wraps it in a bio-energy aura that lets it deal M.D. Anyone can use a charged weapon, but only if they know of and will the power.', 'Rifts World Book 6: South America p.69'),
('enchanted-wooden-sword', 'Enchanted Wooden Sword', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 80 P.P.E. (Maga Island / Bahia Kingdom markets).', '2D4 S.D.C., or 3D6 M.D. with the bio-energy aura active', 1, NULL, 'Aura activates six times, 5 minutes (20 melee rounds) each; recharge at a ley line or nexus, or a mage spends 30 P.P.E.', NULL, NULL, NULL, NULL, 'Lesser bio-weapon: a wooden club with sharpened edges, fire-hardened and charged with magic into a mega-damage structure (1D4x100 M.D.C., relevant only when attacked directly; it parries M.D. weapons safely). A mental command costing one melee action wraps it in a bio-energy aura that lets it deal M.D. Anyone can use a charged weapon who knows of and wills the power.', 'Rifts World Book 6: South America p.69'),
('enchanted-wooden-spear', 'Enchanted Wooden Spear', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 80 P.P.E. (Maga Island / Bahia Kingdom markets).', '2D6 S.D.C., or 4D6 M.D. with the bio-energy aura active', 1, NULL, 'Aura activates six times, 5 minutes (20 melee rounds) each; recharge at a ley line or nexus, or a mage spends 30 P.P.E.', NULL, NULL, NULL, NULL, 'Lesser bio-weapon: a fire-hardened wooden spear (no metal or stone tip may be fitted), charged with magic into a mega-damage structure (1D6x100 M.D.C., relevant only when attacked directly). A mental command costing one melee action wraps it in a bio-energy aura that lets it deal M.D., more than a sword or club. Anyone can use a charged weapon who knows of and wills the power.', 'Rifts World Book 6: South America p.69'),
('light-wood-armor', 'Light Wood Armor', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 150 P.P.E. in a ritual of about ten minutes.', 'Thorns 1D4 M.D. in hand to hand', 1, NULL, NULL, NULL, NULL, NULL, 45, 'Lesser bio-armor grown from one large tree or several medium ones that flow around the recipient during the ritual (who is blind and oblivious for 1D4 minutes); the wood then becomes form-fitting, polished M.D. armor of the caster''s design. Fully sealed with 10 minutes of air, and alive, purifying air: +3 to save vs toxic gases and airborne poisons. Extrudes defensive thorns at hands, elbows, shoulders and knees. No prowl penalty. Regenerates 2D6 M.D.C. per 24 hours (faster with a Biomancer''s Weave Plant). Bonded to its owner alone and withers 1D6 hours after the owner dies; destroyed, it dies. Doffed, it liquifies into a thorny mound and flows back on in about 10 seconds.', 'Rifts World Book 6: South America p.69'),
('light-chitin-armor', 'Light Chitin Armor', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 200 P.P.E. in a ritual of about 20 minutes.', 'Extending claws 1D6 M.D., +1 to strike', 1, NULL, NULL, NULL, NULL, NULL, 70, 'Lesser bio-armor: an enchanted insect swarm in a forest or swamp covers the recipient and secretes a goo that sets into insect plate armor with helmet and clear goggles. Non-Biomancers and non-Jungle Elves may have to save vs Horror Factor 10 or ruin the ritual. Excellent mobility, no prowl penalty. Alive: regenerates 4D6 M.D.C. per 24 hours and can be healed by Heal Wounds, Restoration or a Biomancer''s healing touch; at 0 M.D.C. it dies. Sealed with a 20 minute air supply; it filters gases, +6 to save vs toxic gases, airborne poisons and disease even unsealed. Custom-made for one owner and dies with them.', 'Rifts World Book 6: South America p.69-70'),
('bio-energy-bow', 'Bio-Energy Bow', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 200 P.P.E.', '4D6 M.D. per arrow, doubled against vampires, undead and alien intelligences', 1, '900 feet (274 m)', '40 arrows, then recharge at a ley line or by any wizard or psionic spending 25 P.P.E. or 40 I.S.P.', NULL, NULL, NULL, NULL, 'Greater bio-weapon grown from a living tree and magically shaped like a strung bow with no visible string. Drawing an imaginary string on a mental command and releasing it looses an arrow of bio-energy.', 'Rifts World Book 6: South America p.70'),
('bone-blade', 'Bone Blade', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 500 P.P.E.', 'Large sword 4D6 M.D., short sword 3D6 M.D., knife 2D6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Greater bio-weapon: a supernaturally sharp blade shaped like a giant serrated tooth, made as a large sword, short sword or knife. Permanently enchanted and usable by anyone. The blade has 1D6x100 M.D.C. (only if targeted directly) and regenerates 4D6 M.D.C. per melee round.', 'Rifts World Book 6: South America p.70'),
('insect-pincers', 'Insect Pincers', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates them for 500 P.P.E.', 'Stab or slash 4D6 M.D.; scissor cut 6D6 M.D. With one pincer destroyed, 2D6 M.D. and no scissor cut', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Greater bio-weapon worn like a glove, with two double-edged pincers protruding from the hand harness that snap open and shut on a mental command, to stab, cut, slash or scissor. Each pincer has 1D6x100 M.D.C. (only if targeted directly) and regenerates 4D6 M.D.C. per melee round.', 'Rifts World Book 6: South America p.70'),
('wood-armor-superior', 'Wood Armor: Superior', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 650 P.P.E.', 'Restrained punch 3D6 S.D.C., full punch 1D6+4 M.D. (with thorns), power punch 2D6+4 M.D. (counts as two attacks)', 1, NULL, NULL, NULL, NULL, NULL, 80, 'Greater bio-armor, created exactly like Light Wood Armor but far stronger. Regenerates 1D6 M.D.C. per hour, faster with the same spells. Alive and moving, it acts as an exo-skeleton giving the wearer the equivalent of Supernatural P.S. 18, +1 to strike and parry, +2 to dodge. Biomancer spells that add armor or weapons to the caster work on it too.', 'Rifts World Book 6: South America p.70'),
('chitin-armor-superior', 'Chitin Armor: Superior', 'rifts', 'magic', NULL, NULL, 'No credit price printed; a Biomancer creates it for 900 P.P.E.', 'Restrained punch 4D6+10 S.D.C., full punch 2D6+6 M.D. (with claws), power punch 4D6+6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, 110, 'Greater bio-armor, fundamentally Light Chitin Armor made stronger. Regenerates 2D6 M.D.C. per hour. A living exo-skeleton granting Supernatural P.S. 25, +20% speed, and +2 to strike, parry and dodge. Biomancer spells that add armor or weapons to the caster work on it too.', 'Rifts World Book 6: South America p.70'),
('manoan-tw-energy-cell', 'Manoan TW Energy Cell', 'rifts', 'magic', NULL, NULL, 'Costs roughly the same as a normal E-clip in Manoa; no figure printed.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Manoan techno-wizard energy cell that powers Manoan TW weapons so that ordinary soldiers without magic or psionics can use them. A spent cell recharges magically after half an hour in a stone pyramid (the Five Pyramids of Manoa have great recharging chambers) or when invested with 40 P.P.E. It will not power normal energy weapons or other TW devices.', 'Rifts World Book 6: South America p.91'),
('manoan-enchanted-chain-mail', 'Manoan Enchanted Chain Mail', 'rifts', 'armor', 25, 35000, '35,000 credits. Repairs need a techno-wizard or alchemist; in Manoa 300-400 credits per M.D.C. point restored.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 75, 'Enchanted mega-damage chain mail made by the armorers and alchemists of Manoa for sale and for the Armed Forces; uncharacteristically light (most such suits weigh around 25 lbs / 11 kg). -5% prowl penalty.', 'Rifts World Book 6: South America p.91'),
('manoan-enchanted-segmented-plate', 'Manoan Enchanted Segmented Plate', 'rifts', 'armor', 25, 45000, '45,000 credits. Repairs need a techno-wizard or alchemist; in Manoa 300-400 credits per M.D.C. point restored.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 85, 'Enchanted mega-damage segmented plate made by the armorers and alchemists of Manoa for sale and for the Armed Forces; uncharacteristically light (most such suits weigh around 25 lbs / 11 kg). -10% prowl penalty.', 'Rifts World Book 6: South America p.91'),
('manoan-enchanted-plate-armor', 'Manoan Enchanted Plate Armor', 'rifts', 'armor', 25, 60000, '60,000 credits. Repairs need a techno-wizard or alchemist; in Manoa 300-400 credits per M.D.C. point restored.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'Enchanted mega-damage full plate made by the armorers and alchemists of Manoa for sale and for the Armed Forces; uncharacteristically light and comfortable (most such suits weigh around 25 lbs / 11 kg). -15% prowl penalty.', 'Rifts World Book 6: South America p.91'),
('manoan-flamer-pistol', 'Manoan "Flamer" Pistol', 'rifts', 'weapon', 2, 10000, '10,000 credits in Manoa; rarely found elsewhere.', '3D6 M.D. per blast', 1, '600 feet (183 m)', '12 shots per TW-Cell', 'Equal to the number of hand to hand attacks per melee; not automatic', NULL, NULL, NULL, 'Techno-wizard pistol built in a baroque style like a 16th-century wheellock, firing mini-fireballs (as the warlock spell) at greater range. Standard sidearm of the Manoan Armed Forces and popular with local adventurers, scouts, guardsmen and Amazons. Usable by anyone; recharged at a pyramid or by a techno-wizard. Weight 2 lbs (0.9 kg).', 'Rifts World Book 6: South America p.91'),
('manoan-sk-stun-gun', 'Manoan SK Stun Gun', 'rifts', 'weapon', 3, 15000, NULL, 'Stun: the effects of the Agony spell, save vs magic 14+. Kill: lightning bolt 5D6 M.D., +3 to strike', 1, '600 feet (183 m) on kill, 100 feet (30.5 m) on stun', '8 shots of either setting per E-Cell', 'Equal to the number of hand to hand attacks per melee', NULL, NULL, NULL, 'Techno-wizard pistol with two settings: stun casts a long-range Agony (Rifts RPG p.177), kill fires a magic lightning bolt from the barrel. Standard issue for the Manoan Internal Security Forces, for subduing mortal criminals and fighting supernatural foes. Weight 3 lbs (1.4 kg).', 'Rifts World Book 6: South America p.91'),
('manoan-fireball-rifle', 'Manoan "Fireball" Rifle', 'rifts', 'weapon', 6, 20000, NULL, '4D6+6 M.D. per blast', 1, '1600 feet (488 m)', '24 shots with a TW-Cell', 'Equal to the number of hand to hand attacks per melee', NULL, NULL, NULL, 'Ornate, archaic-looking techno-wizard rifle, usually with a gold sheen, firing a stronger fireball than the Flamer pistol with more range and capacity. Most Amazon warriors are issued one. Weight 6 lbs (2.7 kg).', 'Rifts World Book 6: South America p.92'),
('manoan-stun-pistol', 'Manoan Stun Pistol', 'rifts', 'weapon', 2.5, 8000, NULL, 'The effects of the Agony spell, save vs magic 13+', 0, '50 feet (15.2 m)', '8 shots per E-Cell', 'Equal to the number of hand to hand attacks per melee', NULL, NULL, NULL, 'Non-lethal, stun-only civilian version of the SK Stun Gun, a bit smaller; popular with storekeepers and bouncers for self-defense. Using one without provocation in Manoa brings a large fine, confiscation and, for visitors, expulsion. Weight 2.5 lbs (1.2 kg).', 'Rifts World Book 6: South America p.92'),
('drug-dream', 'Dream', 'rifts', 'gear', NULL, 50, '50 to 200 credits per dose; the price rises when the addict looks desperate.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Magical potion in a golden bottle, Cibola''s most popular recreational drug. Drowsy 1D6 minutes after a dose (attacks and bonuses halved), asleep 2D6 minutes later, then 1D6 hours living a utterly realistic dream of the user''s dearest fantasy, resumable on the next dose. Addictiveness: high. More than once a week needs a save of 16+ (M.E. bonus applies) or reality palls and daily use follows (-2 to that save). More than twice a week: lethargy, -2 initiative, -20% skills. Six months of regular use brings nightmares on any day without a dose; daily users have no initiative, skills at 40%, and half actions and bonuses, and many die of neglect.', 'Rifts World Book 6: South America p.143'),
('drug-energizer', 'The Energizer', 'rifts', 'gear', NULL, 1000, '1,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Potion, usually sold as a pill, popular among mages: refills the user''s P.P.E. and adds 2D6x10 more, which must be used within an hour. Then the extra is gone and 1D6x10 more is temporarily lost; at 0 P.P.E. the user is badly fatigued (attacks, bonuses and skills halved) until two hours'' rest. A 3% chance, +2% per use, of permanently losing 1D6 P.P.E. and recovering P.P.E. at half speed. Addictiveness: medium.', 'Rifts World Book 6: South America p.143'),
('drug-transformer', 'The Transformer', 'rifts', 'gear', NULL, 2000, '2,000 credits per dose.', 'Claws: supernatural P.S. damage +2D6 M.D.; bite 4D6 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Alchemical potion that turns the drinker into a monster reflecting their dark side for 2D4+10 minutes: +1 ft height and about 300 lbs, an M.D. hide of 3D6x10 M.D.C., +10 P.S. with supernatural strength, endurance and triple speed, +2 to strike, parry and dodge, regenerating 1D6 M.D.C. per melee round; no weapons or complex strategy, skills -40%. Afterwards exhausted: one attack, no initiative or bonuses if pressed, collapsing within 1D6 melees to sleep 1D4 hours. Over three uses a week: short temper and -5% skills; after two months of frequent use, 2% per dose (cumulative) that the change becomes permanent, halving I.Q., M.E. and M.A. and stripping most skills. Addictiveness: medium.', 'Rifts World Book 6: South America p.143-144'),
('drug-enhancer', 'Enhancer', 'rifts', 'gear', NULL, 500, '500 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drug that works only for psionics: one dose a day adds 2D4x10 I.S.P. for two hours or until spent. Save vs poison 14+ or get the shakes for 1D4 hours (-3 to strike and parry, -20% to piloting, computer and other precise hand-eye skills). Addictiveness: high, more than once a week; addicts off the drug are -2 to save vs psionic attack, mind control and magic illusions, -10% on skills, and easily intimidated.', 'Rifts World Book 6: South America p.144'),
('drug-lightning-nectar', 'Lightning Nectar', 'rifts', 'gear', NULL, 2000, '2,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Liquid drug, drunk or injected: for 1D4+2 hours grants 2D6x10 I.S.P. and one super psionic power, by color - red Pyrokinesis, blue Electrokinesis, white Hydrokinesis, purple Bio-Manipulation, yellow Mind Bolt (colors are an additive, and street doses get mixed up). One dose a day works. A master psionic who already has the power uses it at half I.S.P. cost. Afterwards save vs poison 14+: success means -2 to strike, parry and dodge and -10% skills for 1D6 hours; failure means the same for 1D6 days plus a save of 12+ or half-rate I.S.P. recovery, headaches and -1D4 attacks for 2D6 days. Addictiveness: medium to high, more than twice a week; each month it is used more than four times costs one M.E. point permanently. Rumored to be made from the brains of psychic animals.', 'Rifts World Book 6: South America p.144');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 30 South America gear rows are in' AS assertion, count(*) AS got, 30 AS want
  FROM gear WHERE slug IN ('rc-10-laser-pistol', 'rc-15-laser-rifle', 'dragon-1-plasma-projector', 'rp-c20-rocket-pistol', 'rr-c40-rocket-rifle', 'rar-c15-rocket-auto-cannon-rifle', 'ra-c15-rocket-auto-cannon', 'enchanted-wooden-club', 'enchanted-wooden-sword', 'enchanted-wooden-spear', 'light-wood-armor', 'light-chitin-armor', 'bio-energy-bow', 'bone-blade', 'insect-pincers', 'wood-armor-superior', 'chitin-armor-superior', 'manoan-tw-energy-cell', 'manoan-enchanted-chain-mail', 'manoan-enchanted-segmented-plate', 'manoan-enchanted-plate-armor', 'manoan-flamer-pistol', 'manoan-sk-stun-gun', 'manoan-fireball-rifle', 'manoan-stun-pistol', 'drug-dream', 'drug-energizer', 'drug-transformer', 'drug-enhancer', 'drug-lightning-nectar');
SELECT 'and every one cites South America' AS assertion, count(*) AS got, 30 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 6: South America p.%';

INSERT INTO data_script_runs (filename) VALUES ('add-south-america-gear.sql');
