-- New West Techno-Wizard weapons. Printed 213-218. Twelve new rows.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-new-west-gear-d-techno-wizard.sql
--
-- PRINTED 217 IS ONE OF THIS BOOK''S THREE GLYPH-CORRUPT PAGES (cache p218,
-- `corrupt_pages` in the manifest) AND IT CARRIES THREE PRICES - the Old
-- Lightning Rifle''s 80,000, the Hellfire Shotgun''s 65,000 and the Snare
-- Gun''s 45,000. All three were read off a RENDER, which the survey flagged as
-- required before this batch started.
--
-- THE RENDER OF 217 IS PERFECTLY LEGIBLE, and that is worth recording: this is
-- an ENCODING fault, where the ink is right and the text layer is wrong, not
-- the other kind where the page itself is damaged (Free Quebec printed 118
-- shows `a\\` on the paper). A render cures the first and not the second, and
-- New West printed 217 is the first. `book-survey` 0a has the distinction.
--
-- ALL 12 ARE NEW - catalog-diff --table gear --remote, 2026-09-10: 12 missing,
-- 0 matched against 1324 rows. The catalog''s existing TW rows are the
-- Converted Energy Pistol and Rifle, the Wing Board and the Tree Trimmer; none
-- of this book''s twelve collides with them.
--
-- CATEGORY IS 'weapon', NOT 'magic', because that is what the catalog already
-- does with a Techno-Wizard gun: tw-converted-energy-pistol and
-- tw-converted-energy-rifle are both filed as weapons. The TW Silencer is
-- 'gear' - it does no damage and attaches to somebody else''s gun.
--
-- TWO OF THE TWELVE DO NO MEGA-DAMAGE and are is_mega_damage 0:
--   * the TW-38 Endless Revolver fires magical S.D.C./Hit Point bolts - 4D6
--     S.D.C. - which is the whole point of its 38-shot payload.
--   * the TW Sapper does NO physical damage at all. It drains P.P.E.
-- The Thundergun is the awkward one and is stored as 1: its silver bullets do
-- 3D6 S.D.C. to a mortal but 5D6 M.D. to a practitioner or creature of magic
-- and 1D6x10 to supernatural evil, so mega-damage is what it is FOR.
--
-- "COST: 45,000+ CREDITS" IS THE SECTION''S HOUSE STYLE and the plus is not
-- noise - it means the price starts there. cost holds the stated figure and
-- cost_note carries the plus, the availability, and the discount the book
-- offers famed champions of good and fellow mages of renown (10%, or 20% on
-- the Sapper). Two entries print NO plus - the TW-38 at 30,000 and the Snare
-- Gun and Silencer at 45,000 and 15,000 - and those are recorded as flat.
--
-- THE CREATION STATS ARE IN THE DESCRIPTION, not in columns. Every entry
-- states an initial P.P.E. cost, the spells needed with their own P.P.E. costs,
-- a physical requirement including a gem of a stated value, and the hours of
-- work - none of which the gear table has a column for, and all of which is
-- what a Techno-Wizard character actually needs. The recharge cost is in
-- payload, where a reader looking at ammunition will meet it.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('tw-45-six-gun', 'TW-45 Six-Gun', 'rifts', 'weapon', 2.5, 45000, '45,000+ credits; fairly common with fair to good availability. Famed champions of good or fellow mages of renown may be given a 10% discount.', '1D6 M.D. per shot', 1, '500 feet (152 m)', '6 energy shots. Reloading all six chambers costs 6 P.P.E. or 12 I.S.P. and counts as one melee action (2-3 seconds). Conventional bullets can be fired instead, but cannot be loaded until all magic energy is discharged, and with even one chamber conventionally loaded the weapon cannot be charged.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'Also printed as the TW-45. Six-Guns appear as any variety of pre-Rifts replica six-shooter, changed through Techno-Wizardry to store magical energy released as mega-damage blasts. THE SIX-GUN IS UNIQUE IN NOT REQUIRING A SORCERER: the user needs only the P.P.E. or I.S.P. to recharge it, with no spell knowledge at all, where most TW weapons demand that the user be able to cast the spells they were built from. That dramatically widens the pool of possible users and the value of the weapon. CREATION: initial P.P.E. cost 40; spells needed Telekinesis (8) and Energy Bolt (5); physically a large revolver and a rose quartz worth 600 credits or more; about 50 hours of work. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a revolver apply.', 'Rifts World Book 14: New West p.214'),
('tw-38-endless-revolver', 'TW-38 Endless Revolver', 'rifts', 'weapon', 2.5, 30000, '30,000 credits; fairly common with fair to good availability. Famed champions of good or fellow mages of renown may be given a 10% discount.', '4D6 S.D.C. per shot', 0, '500 feet (152 m)', '38 magical energy blasts. Reloading all 38 costs 6 P.P.E. or 12 I.S.P. and counts as one melee action. Six conventional bullets can be fired instead, but cannot be loaded until all magic energy is discharged.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A comparatively small .38 caliber revolver, which does NOT get its name from the caliber but from a magical payload of 38 shots. It has all the same basic features as the TW Six-Gun but shoots magical S.D.C./Hit Point bolts rather than mega-damage - the trade for the huge payload, with no stopping to reload after every six. CREATION: initial P.P.E. cost 30; spells needed Telekinesis (8) and Energy Bolt (5); physically an excellent quality .38 caliber revolver and a rose quartz worth 300 credits or more; about 45 hours of work. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a revolver apply.', 'Rifts World Book 14: New West p.214'),
('tw-spitfire-revolver', 'TW Spitfire Revolver', 'rifts', 'weapon', 3, 60000, '60,000+ credits; fair availability. Famed champions of good or fellow mages of renown may be given a 10% discount.', '3D6 M.D. per shot', 1, '200 feet (61 m)', '6 energy blasts. Reloading all six chambers costs 10 P.P.E. or 20 I.S.P. and counts as one melee action. Conventional bullets can be fired instead, but cannot be loaded until all magic energy is discharged.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A large, heavy revolver based on the old Wells Fargo .31 caliber single action revolver, with all the same basic features as the TW Six-Gun but shooting magical, mega-damage mini-fire balls. The shortest ranged gun in the TW line. CREATION: initial P.P.E. cost 60; spells needed Energy Bolt (7) and Fire Balls (10); physically a Wells Fargo .31 caliber revolver and a diamond worth 2000 credits or more; about 60 hours of work. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a revolver apply.', 'Rifts World Book 14: New West p.215'),
('tw-thundergun', 'TW Thundergun', 'rifts', 'weapon', 3, 60000, '60,000+ credits; fair availability. Famed champions of good or fellow mages of renown may be given a 10% discount.', 'Silver bullets: 3D6 S.D.C. to mortal beings, 5D6 M.D. to practitioners of magic and creatures of magic such as dragons and faerie folk, and 1D6x10 M.D. to supernatural evil', 1, '500 feet (152 m)', '6 shots, whether enchanted silver bullets or conventional rounds; conventional bullets have no special properties. Enchanting six more silver bullets costs 15 P.P.E. or 30 I.S.P., and works ONLY on bullets coated with or made of silver.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'An old style Schofield No. 3 single action revolver with all the same basic features as the TW Six-Gun, shooting enchanted projectiles that inflict mega-damage to supernatural beings and creatures of magic. Each round striking a supernatural or magic being CRACKS WITH THE SOUND OF THUNDER, and the gun is unusually loud in any case. IT HAS NO EFFECT AT ALL against robots, cyborgs or M.D.C. structures, which is the limit that decides whether it is the right gun to carry. A favourite of vampire hunters and monster slayers. CREATION: initial P.P.E. cost 60; spells needed Energy Bolt (7), Sense Evil (2), Sense Magic (4), Fly as the Eagle, Fire Bolt (7) and Thunderclap (4); physically a Schofield No. 3 revolver and a clear diamond worth 5000 credits or more with no more than a few flaws; about 60 hours of work. The magic affects only silver bullets; normal bullets do ordinary damage. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a revolver apply.', 'Rifts World Book 14: New West p.215'),
('tw-super-six-carbine', 'TW Super-Six Carbine', 'rifts', 'weapon', 5, 75000, '75,000+ credits; fairly common with fair to good availability. Famed champions of good or fellow mages of renown may be given a 10% to 20% discount.', '2D6 M.D. per shot', 1, '1500 feet (457.2 m)', '6 energy shots. Reloading six more blasts costs 15 P.P.E. or 30 I.S.P. and counts as one melee action. Six conventional bullets can be fired instead, but cannot be loaded until all magic energy is discharged.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'Basically a rifle version of the TW Six-Gun, only with substantially greater range - three times it. Weight typically 5 to 8 lbs, varying with the weapon it was built from. CREATION: initial P.P.E. cost 50; spells needed Telekinesis (8) and Energy Bolt (5); physically a rifle and a rose quartz worth 600 credits or more; about 60 hours of work. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a conventional rifle apply.', 'Rifts World Book 14: New West p.215'),
('tw-eagle-eye-marksman-rifle', 'TW Eagle Eye Marksman Rifle', 'rifts', 'weapon', 5, 75000, '75,000+ credits; fair availability. Famed champions of good or fellow mages of renown may be given a 10% to 20% discount.', '2D6 M.D. per shot; effectively a laser', 1, '1800 feet (548.6 m)', '6 laser-like energy blasts. Reloading six more costs 15 P.P.E. or 30 I.S.P. and counts as one melee action. CONVENTIONAL BULLETS CANNOT BE USED IN THIS GUN, unlike the rest of the line.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A magical weapon based on the design of the old Colt Sporting Rifle with a half stock, looking like a cross between a revolver and a rifle, with a long sight running the entire length of the barrel. THE SIGHT IS THE POINT: it is magically enchanted to let the viewer SEE THE INVISIBLE, gives NIGHTVISION and telescopic enhancement, and offers +1 to strike. The gun fires a sort of magic laser beam. Weight typically 5 to 6 lbs. CREATION: initial P.P.E. cost 85; spells needed See the Invisible (4), Eyes of the Wolf (25), Energy Field (10), Globe of Daylight (2) and Energy Bolt (5); physically a Colt Sporting rifle with half stock and a yellow crystal worth 500 credits or more; about 70 hours of work. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a conventional rifle apply, on top of the sight''s +1.', 'Rifts World Book 14: New West p.216'),
('tw-windblaster-rifle', 'TW Windblaster Rifle', 'rifts', 'weapon', 5, 90000, '90,000+ credits; poor availability, rare. Famed champions of good or fellow mages of renown may be given a 10% discount.', 'Equal to a 5th level Wind Rush spell per shot', 1, '300 feet (91.5 m)', 'Two magical wind blasts. Reloading two more costs 25 P.P.E. or 50 I.S.P. and counts as one melee action. Conventional bullets can also be fired, but not until all magic energy is unleashed from both barrels, and must be loaded by hand.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A TW heavy rifle firing a wind rush with each pull of the trigger, at 5th level spell strength. Based on the styling of an old West Winchester and sometimes called the "Wind-Chester". The MOST EXPENSIVE and RAREST of this book''s TW long guns short of the Sapper. Weight typically 5 to 8 lbs, varying with the weapon type. CREATION: initial P.P.E. cost 50; spells needed Energy Bolt (5) and Wind Rush (20); physically a heavy rifle - it CANNOT have a sawed-off barrel and cannot be a shotgun - and a blue quartz or blue sapphire worth 700 credits or more; about 60 hours of work. BONUS NOTE: NO bonuses are applicable, which is unusual in this line.', 'Rifts World Book 14: New West p.216'),
('tw-old-lightning-rifle', 'TW Old Lightning Rifle', 'rifts', 'weapon', 5, 80000, '80,000+ credits; poor availability. Famed champions of good or fellow mages of renown may be given a 10% discount.', '5D6 M.D. per shot', 1, '1200 feet (366 m)', 'Up to 6 shots total. Reloading ONE more lightning blast costs 15 P.P.E. or 30 I.S.P. and counts as one melee action. Conventional bullets can be shot from the weapon, but only when all magic energy has been fired, and must be loaded by hand.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A long-barrelled rifle - Volcanic carbines are preferred - firing powerful bolts of magic lightning with each pull of the trigger, and the hardest hitting TW gun in this book at 5D6 M.D. a shot. Note that it recharges ONE blast at a time where the rest of the line recharges six, which is what its damage costs. Weight typically 5 to 8 lbs, varying with the weapon type. CREATION: initial P.P.E. cost 95; spells needed Energy Bolt (5) and Call Lightning (15); physically a long-barrelled rifle and a yellow or blue crystal, diamond or other, worth 1000 credits or more; about 70 hours of work. THE PRICE AND AVAILABILITY WERE READ OFF A RENDER of printed 217, one of this book''s three glyph-corrupt pages. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a conventional rifle apply.', 'Rifts World Book 14: New West p.216-217'),
('tw-hellfire-shotgun', 'TW Hellfire Shotgun', 'rifts', 'weapon', 5, 65000, '65,000+ credits; fair availability. Famed champions of good or fellow mages of renown may be given a 10% discount.', '6D6 M.D. per shot', 1, '300 feet (91.5 m)', 'Two fire ball blasts. Reloading two more costs 16 P.P.E. or 32 I.S.P. and counts as one melee action. Conventional rounds can be shot from the weapon, but not until all magic energy is unleashed from both barrels, and must be loaded by hand.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A heavy, double-barrelled, sawed-off shotgun that shoots devastating magic fire balls with each pull of the trigger. Weight typically 5 to 6 lbs. CREATION: initial P.P.E. cost 55; spells needed Ignite Fire (6), Fire Bolt (7) and Fireball (10); physically a heavy, double barrelled, sawed-off shotgun and a rose quartz or red or orange sapphire worth 1000 credits or more; about 60 hours of work. THE PRICE WAS READ OFF A RENDER of printed 217, one of this book''s three glyph-corrupt pages. BONUS NOTE: no bonuses for shotguns, but the SPELL bonuses and effects all apply.', 'Rifts World Book 14: New West p.217'),
('tw-snare-gun', 'TW Snare Gun', 'rifts', 'weapon', 3, 45000, '45,000 credits; poor availability. A favourite of bounty hunters and lawmen.', 'Fires a magic net equal to a 5th level spell', 0, '200 feet (61 m)', 'Two magic net blasts. Reloading two more costs 10 P.P.E. or 20 I.S.P. and counts as one melee action. Conventional rounds or flares can be shot from the weapon, but not until all magic energy is unleashed from both barrels, and must be loaded by hand.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A double-barrelled, sawed-off shotgun or flare gun that fires a magic net with each pull of the trigger, at 5th level spell strength. It TAKES rather than kills, which is why it is a favourite of bounty hunters and lawmen. The cheapest of this book''s TW long arms, and one of only three in the section priced flat rather than as a "plus" figure. Weight typically 3 to 5 lbs. CREATION: initial P.P.E. cost 45; spells needed Energy Bolt (5) and Magic Net (7); physically a short, double barrelled, sawed-off shotgun and a clear crystal worth 300 credits or more; about 40 hours of work - the quickest build in the section. THE PRICE WAS READ OFF A RENDER of printed 217, one of this book''s three glyph-corrupt pages. BONUS NOTE: no bonuses apply.', 'Rifts World Book 14: New West p.217'),
('tw-sapper', 'TW Sapper', 'rifts', 'weapon', 4, 150000, '150,000+ credits; VERY RARE. Famed champions of good or fellow mages of renown may be given a 20% discount - twice what the rest of the section offers. Rarely sold to anyone who is not a practitioner of magic, though exceptions are sometimes made for reputable Cyber-Knights, Sky-Knights and lawmen.', 'No physical damage. Each blast DRAINS P.P.E.: 1D6 from an average person, 3D6 from a practitioner of magic, and 4D6 from a creature of magic such as a dragon or faerie folk or a supernatural being such as a demon, elemental, godling or god. Against a magic barrier - magical walls, force fields, and armour of Ithan - the blast does the equivalent of 4D6 M.D. or S.D.C. depending on the nature of the barrier.', 0, '600 feet (183 m)', 'The weapon can hold up to 24 shots. 40 P.P.E. gives it four P.P.E.-sapping or anti-magic blasts.', 'Each shot counts as one melee attack', NULL, NULL, NULL, 'A powerful and dangerous weapon to all practitioners of magic, firing a sort of negative or anti-magic energy bolt that dispels P.P.E., sapping sorcerers and creatures of magic with every blast that hits. It typically looks like an old style musket, SO THAT FELLOW TECHNO-WIZARDS AND MAGES KNOW WHEN THEY ARE FACING ONE, but it can be built into any kind of large gun such as a shotgun, rifle or even a rail gun. TIMING IS EVERYTHING against a spell caster: roll initiative to see whether the caster got the spell off first. If the caster LOSES initiative he is struck before the spell goes off, the spell is negated, and HALF the P.P.E. needed to cast it is dispelled - even when that is more than the usual 1D6 to 4D6 - and no further P.P.E. is sapped. If the caster WINS initiative the spell is cast and the sapper blast lands an instant later with the usual drain. Once a character is down to three P.P.E. the blasts have no further effect on him, and shooting at illusions has no effect at all. Popular among Cyber-Knights, lawmen and bounty hunters. Weight typically 4 to 7 lbs, varying with the weapon type. CREATION: initial P.P.E. cost 195, by far the largest in the section; spells needed Anti-Magic Cloud (140) and Energy Disruption (12); physically a large gun such as a shotgun, rifle or rail gun and a clear diamond with no more than two minor flaws, minimum value 10,000 credits; about 120 hours of work. BONUS NOTE: the character''s usual W.P. and O.C.C. bonuses to strike with a rifle apply.', 'Rifts World Book 14: New West p.217-218'),
('tw-silencer', 'TW Silencer', 'rifts', 'gear', 1, 15000, '15,000 credits; fair availability. A favourite of gamblers, highwaymen, bounty hunters and assassins.', 'None', 0, 'Reduces the weapon''s range by 10%, but COMPLETELY muffles all sound from it', 'A fully charged silencer obliterates the sound of 10 gun shots. Recharging it to muffle another 10 costs 10 P.P.E. or 20 I.S.P. and counts as one melee action.', 'Not applicable', NULL, NULL, NULL, 'A nifty little device using a variation of the Globe of Silence spell to totally negate all sound from the weapon being fired. It works on MAGIC FIREARMS OR CONVENTIONAL WEAPONS ALIKE, which is unusual in this section. TW Silencers look just like ordinary silencers except for a trio of magic symbols and a black or dark blue crystal. CREATION: initial P.P.E. cost 45; spells needed Energy Bolt (5) and Globe of Silence; physically a length of tubing that attaches to the muzzle of the weapon - NOT applicable to shotguns, machineguns or rail guns - plus three magic symbols and a black or dark blue crystal worth 200 credits or more; about 3D4 hours to build, the only build time in the section given as dice. BONUS NOTE: no bonuses apply.', 'Rifts World Book 14: New West p.218');

-- Read the result back rather than trusting the exit code.
SELECT count(*) AS tw_rows FROM gear WHERE slug LIKE 'tw-%' AND source_book LIKE 'Rifts World Book 14: New West%';
SELECT count(*) AS from_corrupt_page FROM gear WHERE source_book LIKE '%New West p.21%7%' AND slug LIKE 'tw-%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-new-west-gear-d-techno-wizard.sql');
