-- The 37 priestly prayers of Wormwood, Rifts Dimension Book 1 pp.83-90.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-wormwood-prayers.sql
--
-- Transcribed from the OCR cache (.cache/books/ww, 300dpi, no text layer) and
-- reconciled row by row against the book's own List of Priestly Prayers &
-- Spells on printed page 83 - which is the ONLY place the book states which
-- prayers exist. All 37 names agree; no row was dropped and none was invented.
--
-- LEVEL 0 IS DELIBERATE, and it is the first time this catalog has used it.
-- These are not invocations on a numbered ladder. The book gives them no
-- level at all: a priest of light starts with eight named prayers and picks
-- more on a per-level schedule, so there is nothing for a level column to
-- hold. Every class granting them names them through magic.spells_from, and
-- leveling.js states outright that a named list REPLACES the spell-level gate
-- - so a level of 0 gates nothing rather than gating them out.
--
-- Two rows carry ppe 0 on purpose and both say why in ppe_note. Impervious to
-- Symbiotes is a constant, automatic ability the book prices as "Not
-- applicable"; Open & Close Dimensional Rifts is a GRANT of two Rifts RPG
-- invocations (close rift p.189, dimensional portal p.190) rather than a
-- spell with a stat block of its own. Neither is a cost lost to a page break,
-- which is what a bare 0 usually means.
--
-- Three rows carry a variant_note. The book spells them one way in its p.83
-- list and another in its own description heading - "Summon and use Angel
-- Hair" against "Summon & Use Angel Hair", and likewise for the parasites and
-- the spirits. The list is the authority for membership, so the list wins and
-- the losing reading is recorded rather than discarded.
--
-- ON CONFLICT (name) DO UPDATE rather than INSERT OR IGNORE, so this file is
-- the authoritative bytes in every environment even where a row already
-- exists. Pure ASCII with LF endings on purpose - see PR #101.

INSERT INTO spells
  (name, level, ppe, ppe_note, variant_note, source, source_book, system, range, duration, damage, saving_throw, area_of_effect, casting_time, description)
VALUES
  ('Close an Opening', 0, 3, 'Three for a window-size portal large enough for a human to crawl through, six for a door, nine for an opening twice a normal door. Add 100 to close a door permanently.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.84', 'rifts', 'Five feet (1.5 m)', 'Two minutes (8 melee rounds) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One melee (15 seconds) of prayer or concentration.', 'The spell caster can close an existing opening (hole, window, doorway), making it a solid part of the wall/building. The portal is completely sealed as if no opening had ever existed. To accomplish this feat, the character simply prays or concentrates and asks Wormwood to temporarily restructure itself to close the portal. When the spell elapses, the opening reappears. A ten foot (3 m) diameter of wall has 50 M.D.C. points. Only another priest, monk, apok or wormspeaker can reopen the door or create a new temporary opening. Anybody caught in a closing opening will be stuck, but not hurt, until someone who can manipulate structures can free him.'),
  ('Control Temperature', 0, 4, 'Four; triple the cost for a duration of one day.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.83', 'rifts', '30 feet (9 m) per level of experience', 'One hour per level of experience or one day at triple the P.P.E. cost.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', '300 foot (90 m) radius per level of experience.', 'Five minutes of prayer or concentration.', 'The character can cause Wormwood to increase or decrease the temperature in a particular area by three degrees Fahrenheit per level of experience.'),
  ('Create a Burial Place', 0, 2, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.83', 'rifts', 'Five feet (1.5 m)', 'Permanent grave', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One minute of prayer or concentration.', 'The character can cause Wormwood to spread open to create a shallow hole where a dead body can be placed. When the priest is finished saying a prayer over the body, the planet folds over the hole, covering the body(s) inside. The living planet then recycles the corpse by reducing it down to its chemical components. Thus, there is no chance for stench, pestilence or defiling of the grave. If so desired, the priest can also raise a small, two or three foot (0.6 or 0.9 m) pillar to mark the grave.'),
  ('Create a Fountain of Water', 0, 6, 'Six for a small fountain or 24 to create a small, shallow pool of water (can hold three humans comfortably).', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.83', 'rifts', 'Five feet (1.5 m)', 'Two minutes (8 melee rounds) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One minute (4 melee rounds) of prayer or concentration for a fountain, five minutes to create a pool.', 'The individual attuned to Wormwood can make a three foot tall mound appear out of the ground from which cool, clear drinking water bubbles forth. Additional P.P.E. and concentration can create a shallow pool of water suitable for drinking or bathing in. Small fountains have a mega-damage structure of 10. Large ones have 2D4x10 M.D.C., pools 3D4x10 M.D.C.'),
  ('Create Life Force Cauldron', 0, 400, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.83', 'rifts', 'Touch', 'Permanent', NULL, 'The cauldron can only be created in domains completely controlled by the Forces of Evil. In evil places, the living planet is weak and the would-be creator needs only to roll a 9 or higher to make the cauldron.', NULL, 'Ten minutes of concentration.', 'Only characters of an anarchist or evil alignment will even consider the creation of a life force cauldron. Wormwood resists the creation of the cauldron in any area not dominated and corrupted by the Forces of Evil. Life force cauldrons are used to create worm zombies, magic slime and other nightmarish creations of magic. The main reason it is NEVER created or used by characters of a good or even unprincipled alignment is that human sacrifices are needed to power it.'),
  ('Create Magic Slime', 0, 50, '50 points per vial of slime for potions; varies for slime of different kinds.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.84', 'rifts', 'Ten feet (3 m) away from a life force cauldron.', 'The slime remains until used.', NULL, 'Not applicable.', NULL, 'Ten minutes of concentration.', 'Magic slime is created with a life force cauldron which is usually the source for all or most of the P.P.E. necessary for its creation. These cauldrons are found only in domains completely controlled by the Forces of Evil. The slime is used to create a variety of magic potions and ointments. Limitations: Must have a life force cauldron to make the magic slime and only characters of an anarchist or evil alignment will consider making and using slime.'),
  ('Create an Opening', 0, 3, 'Three for portals from a peephole up to a window big enough to crawl through, six for a door, nine for an opening twice the size of a normal human-size door.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.84', 'rifts', 'Five feet (1.5 m)', 'One minute (4 melee rounds) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One melee (15 seconds) of prayer or concentration.', 'The spell caster can create an opening (hole, window, doorway) in a solid wall of a building. He simply prays or concentrates and asks Wormwood to temporarily restructure itself in a small area to create an opening. When the spell elapses or is cancelled, the wall closes back into a solid, single surface.'),
  ('Create a Pillar', 0, 2, 'Two points per every five feet (1.5 m) up to a maximum of 50 feet (15.2 m) outdoors; double indoors.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.84', 'rifts', 'Five feet (1.5 m) per level of experience.', 'One minute (4 melee rounds) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One minute of prayer or concentration.', 'A pillar with small branches for climbing rises from the ground. It can be climbed to get a better view of the surrounding area, provide some shade, and/or to serve as a perch to rest in above the ground and away from predators. The pillar is a mega-damage structure with 25 M.D.C. points per five feet (1.5 m), and its diameter is roughly that of the average tree.'),
  ('Create Shelter', 0, 12, '12 points for a temporary hut (one hour per level), 24 for a durable one (one day per level). Add 100 to make it permanent.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.84', 'rifts', 'Five feet (1.5 m)', 'One hour per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'Ten minutes of prayer or concentration.', 'The shelter simply swells out of the ground in the shape of a small bubble structure that resembles an igloo. It is only large enough to accommodate two or three human-size occupants comfortably and is difficult to see from a distance (it blends in with its surroundings). Furthermore, the hut maker can always sense the location of his creation as long as it exists. The shelter is a mega-damage structure with 100 M.D.C. points.'),
  ('Create Stairs', 0, 4, 'Four points per every five foot (1.5 m) length of stairs. Add 100 to make them permanent.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.84', 'rifts', 'Five feet (1.5 m) per level of experience.', 'Two minutes (8 melees) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One melee (15 seconds) of prayer or concentration.', 'Through prayer or concentration the character asks Wormwood to temporarily restructure itself to form a stairway. At first a mound will appear in the floor and begin to go up or down to form a ramp. A moment later the ramp reshapes into stairs. When the spell elapses, the stairs slip back into the floor. Stairs are a mega-damage structure with 25 M.D.C. points per every five foot (1.5 m) length. Note: The stairs spell can also be used to create a narrow bridge.'),
  ('Create Tunnel', 0, 5, 'Five points per every five foot (1.5 m) length of tunnel; 10 more to widen it for walking, 100 to make it permanent.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.85', 'rifts', 'Five feet (1.5 m) per level of experience.', 'Two minutes (8 melees) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One melee (15 seconds) of prayer or concentration.', 'Through prayer or concentration the character asks Wormwood to temporarily restructure itself to form a tunnel or series of tunnels underneath the ground. At first an indentation appears in the ground and begins to sink, creating an ever deepening tunnel. The tunnel''s width is usually wide enough for a human to crawl through, but can be enlarged big enough for walking. The direction of the tunnel is completely controlled by the spell caster, but he must be inside to do so. When the spell elapses, the tunnel closes up and disappears as if it never existed.'),
  ('Create Wall', 0, 10, '10 points per 10 foot (3 m) section, 10 more per additional section, 100 per section to make it permanent.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.85', 'rifts', 'Five feet (1.5 m) per level of experience.', 'Two minutes (8 melees) per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'One melee (15 seconds) of prayer or concentration.', 'A solid wall grows from the ground of the living planet or floor of buildings. The wall is 10 feet (3 m) long by as high as 10 feet tall and about half a foot (0.15 m) thick, and is a mega-damage structure with 50 M.D.C. points per section. Like most structures created from/by Wormwood, the wall is attached to the ground and cannot be cut loose and physically carried to a different location. The creation of a wall is typically erected as a defensive barrier.'),
  ('Create Worm Zombies', 0, 250, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Ten feet (3 m) away from a life force cauldron.', 'The monster exists until it is physically destroyed.', NULL, 'Not applicable.', NULL, 'Ten minutes of concentration.', 'The zombie is created with a life force cauldron which is usually the source for all or most of the P.P.E. necessary for its creation. These cauldrons are found only in domains completely controlled by the Forces of Evil. Limitations: Must have a life force cauldron to make zombies and only characters of an anarchist or evil alignment will consider making these zombies.'),
  ('Destroy Life Force Cauldron', 0, 100, '100 points; 200 reduces the roll needed to a 7 and 300 reduces it to one point. The destroyer cannot use the cauldron''s own P.P.E. against it.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Touch', 'Permanent', NULL, 'The land fights against any magic leveled against it. The spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means the P.P.E. is expended without result. A successful roll means the cauldron is destroyed and its store of P.P.E. is harmlessly dispelled.', NULL, 'One minute (4 melee rounds) of prayer or concentration.', 'The priest or wormspeaker can safely release the mystic, life energy stored in the cauldron and destroy it. When destroyed, the dangerous pool is absorbed back into Wormwood as if it had never existed. This is a great ability because life force cauldrons are used by evil beings for human sacrifice and to create terrible monsters like the worm zombies.'),
  ('Heat Point', 0, 2, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Two feet (0.6 m) per level of experience.', 'One minute per level of experience.', '2D6 S.D.C. to anybody who touches the heated area.', 'Not applicable.', 'One foot (0.3 m) per level of experience.', 'About half a melee round (7 seconds) of prayer or concentration.', 'The spell caster can super heat an area one foot in diameter in a matter of seconds. The area will glow red with heat and will burn anybody who touches it, or who passes his hand over it less than three feet (0.9 m) away. Combustible materials such as paper, cloth, dry grass or leaves, wood, human hair, animal fur and similar has a 1-50% chance of catching on fire; add 10% for each additional minute up to 100%. The heat point spell can also be used to light torches, start campfires, boil water, give a hot foot, and cauterize wounds.'),
  ('Hell Fire', 0, 15, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Ten feet (3 m) per level of experience.', 'One melee round (15 seconds).', '4D6 M.D. to most things and 2D4x10 M.D. to supernatural monsters. An apok casting it inflicts 3D4x10.', 'Not applicable.', 'One foot (0.3 m) per level of experience. Height: five feet (1.5 m) plus one foot (0.3 m) per level of experience.', 'One melee round (15 seconds) of prayer or concentration.', 'This ability is roughly the same as the heat point only far more deadly and is used as a method of attack, defense and purification. Hell fire actually creates a pillar of intensely hot, magic flame. The size of the pillar depends on the experience level of its creator. There is also a 90% likelihood that combustible material will catch fire. The pillar is stationary and cannot be moved once it has been created, but is great for blocking entrances. It can also be used as a signal flare. Note: Hell fire does not burn buildings or harm the surface of the planet Wormwood.'),
  ('Invisible to Magic Seeing', 0, 25, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Self', '15 minutes per level of experience.', NULL, 'Not applicable.', NULL, 'Two melee rounds (30 seconds) of concentration.', 'This magic makes the character invisible to all means of magic observation/tracking, including see the invisible, calling, and locate. Nor can he be found or observed by astral travelers or through the use of any kind of crystal ball. Furthermore, the character can sense when he is being watched by invisible creatures, astral travelers, magic or through a crystal ball. The moment he activates this spell, he disappears from the crystal ball/magic sight.'),
  ('Life Fuel', 0, 5, 'Varies by purpose: 5 per hour for Life Shield, 15 to Cleanse the Body, 20 to Restore Life, 30 to Cleanse the Spirit, up to 50 to give Life Energy.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Self, or others by touch or prayer within 3 ft (0.9 m).', 'Instant and permanent', NULL, 'Not applicable.', NULL, 'Two melee rounds (30 seconds) of concentration.', 'The amount of potential psychic energy expended varies with the character''s purpose. Cleanse the Body: 15 P.P.E. instantly negates poison and drugs, or relieves the symptoms of disease, reducing all penalties and the duration of the sickness by half. Cleanse the Spirit: 30 P.P.E. frees victims of supernatural possession and mind control; possessing entities are instantly forced out and characters under psionic, vampiric or mystic mind control get another save at a special +6 bonus. Life Energy (self only): as much as 50 P.P.E. can be willingly given to another priest, apok, wormspeaker or practitioner of magic. Life Shield (self only): 5 P.P.E. per hour prevents the character''s P.P.E. reserve from being stolen or drained. Restore Life: 20 P.P.E. restores 10 hit points and all S.D.C. of non-mega-damage creatures and 2D6+10 M.D.C. to mega-damage creatures.'),
  ('Locate Places of Evil', 0, 3, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.86', 'rifts', 'Self', '20 minutes per level of experience.', NULL, 'Not applicable.', NULL, 'Two melee rounds (30 seconds) of prayer or concentration.', 'The character can sense the direction of places (cities, towns, lairs) in which a few very powerful supernatural monsters can be found or an entire city or armed camp of supernatural fiends can be located. He can also sense the direction and approximate distance of any crawling towers within a ten mile radius per level of experience. This power enables the spell caster to find or avoid places inhabited by thousands of monsters or an extremely powerful monster like the Host or an alien intelligence. This ability cannot detect a small number of supernatural marauders nor mortal humans or D-Bees of evil alignment.'),
  ('Locate Food & Resources', 0, 3, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.87', 'rifts', 'Self', '20 minutes per level of experience', NULL, 'Not applicable.', NULL, 'Two melee rounds (30 seconds) of prayer or concentration.', 'The character can sense the direction and approximate distance of the nearest food cave. He can also sense the direction and general area where food worms and grubs might be found and where food may be stored. Similarly, the character can sense the direction and approximate distance to the nearest available source of water (fountain or pool), as well as mountains made of resin/mucus, bubbling resin pools, and angel hair. However, his senses may lead to a town or city where food caves, grubs, water and resources are commonplace. This particular ability does not include locating blood stones, crystals or symbiotes.'),
  ('Locate Home Town', 0, 2, 'Two points to sense the correct direction home. Recognising home town on arrival is automatic and costs nothing.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.87', 'rifts', 'Self', 'Constant', NULL, 'Not applicable.', NULL, 'Not applicable.', 'Characters attuned to Wormwood will automatically sense when they have returned to their home town regardless of how much it may have changed or whether the character is suffering from memory loss or insanity. Furthermore, the character can expend P.P.E. to determine the correct direction toward home. Home is the place where the character was either born or has spent several years (ten or more) of his life.'),
  ('Impervious to Symbiotes', 0, 0, 'Not applicable; automatic and always on.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.87', 'rifts', 'Self', 'Constant', NULL, 'Not applicable.', NULL, 'Not applicable.', 'Exclusive to the priests of light and apok. The priest is impervious to the effects of ALL symbiotic organisms created from the Living Planet, including the foul designs manifested by the Forces of Darkness and the helpful Spirit of Wormwood. The priest is also impervious to magic slime, parasites and worm zombies (they will not attack him/her). The life force battery and life force cauldron cannot drain his/her energy. The only exceptions are food grubs, angel hair, blood stones and crystals, which are not true symbiotes and can be used by the priest. The character is still vulnerable to alien symbiotic organisms from other dimensions.'),
  ('Mold Structures', 0, 20, '20 points per five foot (1.5 m) radius transformed temporarily; add 100 to make the change permanent. 120 points accelerates organic growth fivefold.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.87', 'rifts', 'Five feet (1.5 m)', '20 minutes per level of the spell caster or permanent.', NULL, 'In domains completely controlled by the Forces of Evil, the land resists and the spell caster must roll a 14 or higher to have Wormwood respond appropriately. A failed roll means P.P.E. is expended without result. Evil characters have the same problem in lands where they do not dominate.', NULL, 'Five minutes of prayer or concentration per every five foot (1.5 m) radius.', 'The character attuned to Wormwood can rearrange existing structures created by the living planet or shaped by another character. This ability enables the spell caster to change the look or configuration of an existing building, room, cave, tunnel, pillar, sculpture, fountain, etc., which is part of Wormwood. This includes reshaping rooms, creating new doors or windows, creating fountains, molding statues or ornamentation, styling furniture, adding additions to existing rooms or buildings and so on. Permanent remolding can be changed again via this same spell by that character or another with the same power.'),
  ('Open & Close Dimensional Rifts', 0, 0, 'No cost of its own. Grants the Rifts RPG spells Close Rift and Dimensional Portal; use their costs.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.87', 'rifts', 'See Close Rift and Dimensional Portal.', 'See Close Rift and Dimensional Portal.', NULL, 'See Close Rift and Dimensional Portal.', NULL, NULL, 'Same as the spells found in the Rifts RPG - close rift, page 189 and dimensional portal, page 190. This prayer is a grant of those two invocations rather than a spell with a stat block of its own, which is why it carries no cost here.'),
  ('Remove Symbiotes', 0, 15, '15 points per symbiotic organism removed. 30 points to make a life force battery merge back into Wormwood.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.87', 'rifts', 'Touch or up to ten feet (3 m)', 'Varies; see description.', NULL, 'Even in domains completely controlled by the Forces of Evil, the symbiotes'' resistance against this power is weak. The spell caster must roll a 10 or higher to make it release. A failed roll means P.P.E. is expended without results.', NULL, 'One minute (4 melee rounds) of prayer or concentration.', 'The character can recognize symbiotes created by Wormwood (including those corrupted by the Forces of Darkness) and can remove them from others without harm to that person (no damage or side effects). The organism is harmless, disposed of by sending it back into Wormwood. The priest can also use this power to safely free prisoners from life force batteries; the creature waits until a new victim can be found, and if no new source of energy is found within a week it shrivels up and dies. To make the life force battery merge back into Wormwood, the priest must expend 30 P.P.E. and roll a 14 or higher.'),
  ('Repel Symbiotes', 0, 7, '7 points to repel parasites, 30 points to stop a crawling tower for a few days.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.88', 'rifts', 'Touch or up to ten feet (3 m) per level of experience.', 'Varies; see description.', NULL, 'Even in domains completely controlled by the Forces of Evil, the symbiotes'' resistance against this power is weak. The spell caster must roll a 7 or higher to make it flee the area. A failed roll means P.P.E. is expended without results.', NULL, 'Five seconds (counts as two melee actions) of prayer or concentration and a stern command.', 'The character can recognize symbiotes created by Wormwood, especially those created by the Forces of Darkness. Evoking this spell with a short chant and concentration repels aggressive symbiotes, including parasites, life force batteries and worm zombies. The creatures are forced to stop, turn and leave the area without harming the spell caster or anybody near him. Two symbiotes/parasites can be affected per level of experience. The parasites will not return for 1D4 hours, but zombies and life force batteries can return in 1D4 minutes. The character can even make a crawling tower stop for one day per experience level, on a roll of 14 or higher. Evil characters can repel the spirits of Wormwood, edible grubs and worms and make angel hair disappear before it falls. This spell does not affect battle saints, stones or crystals.'),
  ('Ride Giant Parasites', 0, 10, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.88', 'rifts', 'Touch or up to ten feet (3 m) per level of experience.', '15 minutes per level of experience (double for wormspeakers).', NULL, 'Even in domains completely controlled by the Forces of Evil, the symbiotes'' resistance against this power is weak. The spell caster must roll a 7 or higher to turn the monster into a tame and obedient riding animal. A failed roll means P.P.E. is expended without results.', NULL, 'Five seconds (counts as two melee actions) of prayer or concentration followed by a stern command.', 'The spell caster can instantly turn an aggressive, giant parasite into a tame and obedient riding animal. The creature will obey only the person who has enchanted it and will allow others to climb on top of it only after the spell caster has mounted it first. The parasite can be used like a horse, pack animal or to pull a cart or wagon, but cannot be made to fight for any reason. Part of this spell is to make the animal docile.'),
  ('Summon and use Angel Hair', 0, 20, NULL, 'The description heading on p.88 spells this Summon & Use Angel Hair; the p.83 list is followed here.', 'import', 'Rifts Dimension Book 1: Wormwood p.88', 'rifts', 'The material falls within 20 feet (6 m) of the summoner.', 'The hair falls from the sky for one minute per level of experience. Enough material falls in one minute to make a full suit of clothes.', NULL, 'In domains completely controlled by the Forces of Evil it is difficult to summon angel hair. The spell caster must roll a 15 or higher to succeed. A failed roll means no angel hair and the character only loses 5 P.P.E.; only a successful summoning uses all of it.', NULL, 'Five minutes of prayer or concentration before the spell is cast and angel hair begins to fall.', 'Just as the name of this spell suggests, the character is able to summon the material humans call angel hair. Fine strands of cotton-like fibers appear in thin air, about 50 feet (15.2 m) above the ground and gently fall to earth. The material can be used to make clothes of all kinds, as well as rope and thread.'),
  ('Summon Battle Saints & Orbs', 0, 190, '190 points to summon a battle saint orb and 390 points to summon a battle saint.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.88', 'rifts', '10 feet (3 m) per level of experience.', 'The battle saint will remain active for 24 hours or until it is destroyed.', NULL, 'None, not even in domains completely controlled by the Forces of Evil.', NULL, 'Ten minutes of prayer or concentration.', 'This spell is not so much a summoning as it is an awakening. When a battle saint or battle saint orb is dormant, they turn into a small hill or part of a mountain. One must know that the symbiotic giant is located in that area, go to its resting place and work the magic there. Limitations: the battle saint or orb will NOT respond to evil priests, evil summoners, dark priests or any of the Forces of Darkness. A priest of light can summon both but cannot pilot either. Apoks, monks, knights of the Temple, knights of the Hospital and master psionics can pilot both mechanisms; the wormspeaker can awaken and pilot them.'),
  ('Summon Edible Grubs', 0, 15, '15 points feeds two human beings, 20 feeds four, 25 feeds six, 30 feeds eight.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.89', 'rifts', 'Appear within 5 feet (1.5 m) of the summoner.', 'Instant.', NULL, 'In domains completely controlled by the Forces of Evil it is difficult to summon edible grubs. The spell caster must roll a 15 or higher to succeed. A failed roll means no grubs and the character only loses 5 P.P.E.', NULL, 'Five minutes of prayer or concentration.', 'In response to this spell, the ground of Wormwood puckers and creates a small, bowl-size indentation. Inside the bowl are worms and grubs. Although they are alive and may be considered too gross to eat by alien visitors, they are actually very tasty and extremely nutritious. The creatures can be cooked or eaten raw.'),
  ('Summon Entities', 0, 150, '150 points summons 1D6 poltergeists or 1D4 haunting entities, 250 summons one syphon or tectonic entity, 300 summons one possessing entity (always evil).', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.89', 'rifts', 'Appear within 5 feet (1.5 m) of the summoner.', 'The entities will stay 24 hours per level of experience.', NULL, 'In domains completely controlled by the Forces of Evil it is easier to summon entities; roll 10 or higher. Elsewhere the spell caster must roll a 15 or higher. Using a life force cauldron doubles the cost but the summoning never fails. A failed roll means no entities and only half the P.P.E. is used.', NULL, 'Ten minutes of prayer or concentration.', 'In response to this spell, the air in front of the spell caster, or above the life force cauldron, begins to shimmer and for a brief two seconds, opens a tiny dimensional rift that releases one or more entities (the specific type can be designated). The lesser entities are more mischievous and troublesome than dangerous, but the syphon, tectonic and possessing entities are potentially lethal. See Rifts Conversion Book One for complete descriptions about entities.'),
  ('Summon Flies', 0, 50, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.89', 'rifts', '100 miles (160 km) per level of experience.', '30 minutes per level of experience.', NULL, 'None', 'A 100 foot (30.5 m) radius per level of the summoner.', 'Ten minutes of prayer or concentration.', 'This magic will cause 1000 flying insects per level of experience to amass in a gigantic, blinding cloud. The swarm interferes with radar, creating false readings, and reduces visibility to about 10 feet (3 m). The bugs are also very distracting, noisy and annoying, and may clog engines, air intake valves, vents, and joints of bots, borgs and vehicles. Characters not protected inside body armor, a vehicle or completely covering their heads lose half of their melee actions, can barely see or hear, completely lose initiative, and have all combat bonuses and speed reduced by half.'),
  ('Summon and Command Parasites', 0, 100, '100 points summons 1D4 lesser parasites like ticks and beetles, 270 summons one of the larger types, 450 summons the giant Battler parasite.', 'The description heading on p.89 spells this Summon & Command Parasites; the p.83 list is followed here.', 'import', 'Rifts Dimension Book 1: Wormwood p.89', 'rifts', 'Appear within 20 feet (6 m) of the summoner.', 'Will stay 24 hours per level of experience (double for wormspeakers).', NULL, 'In domains completely controlled by the Forces of Evil it is easier to summon parasites; roll 10 or higher. Elsewhere the spell caster must roll a 14 or higher. Using a life force cauldron doubles the cost but the summoning never fails. A failed roll means no parasites and only half the P.P.E. is used.', NULL, '20 minutes of prayer or concentration.', 'In response to this spell, the ground in front of the spell caster begins to move and a mound of earth swells up from the ground. A moment later the parasites appear and the mound shrinks back into the ground. The parasite will only obey the commands of the character who summoned it and will even let that person ride on its back. Parasites are aggressive and combative by nature so they make ideal guards and attack animals.'),
  ('Summon and use Spirits of Wormwood', 0, 190, NULL, 'The description heading on p.90 spells this Summon & Use Spirits of Wormwood; the p.83 list is followed here.', 'import', 'Rifts Dimension Book 1: Wormwood p.90', 'rifts', '10 feet per level of experience.', 'The symbiotic spirit remains for 3D4 hours. The duration is always random.', NULL, 'None, not even in domains completely controlled by the Forces of Evil. If the spirit is available it will come. Frequently the spirit is not available from the Living Planet and cannot come (G.M.''s discretion), in which case no P.P.E. is expended.', NULL, 'Ten minutes of prayer or concentration.', 'The character can summon the wispy creatures known as the Spirits of Wormwood and sometimes referred to by common folk as angels. In reality, the symbiotic spirit is an ectoplasmic manifestation that temporarily bonds with the priest or fighter to give him superhuman powers and insight. Limitations: it will only link and offer its powers to characters of a good alignment (including unprincipled if nobody nicer is available). Once connected to a character it cannot be made to let go until its random duration has elapsed or its host body is slain.'),
  ('Summon & Use Stones & Crystals', 0, 150, 'A crystal ball requires 600 P.P.E. and permanently burns 2D6 of the caster''s base; a control crystal 450 and 1D6; stones with special powers 350 and 1D4; the average lesser stone or crystal 150 and one point.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.90', 'rifts', 'Appear within 20 feet (6 m) of the summoner.', 'Permanent until destroyed.', NULL, 'The character must roll an unmodified 15 or higher. Using a life force cauldron doubles the P.P.E. cost and reduces the roll to an 8 or higher. A failed roll means no item appears and the character still uses up all the P.P.E. except for that from his own personal reserve.', NULL, '20 minutes of prayer or concentration.', 'In response to this spell, the ground in front of the spell caster begins to move and a pillar swells up from the earth. A moment later a pod buds at the top to reveal one large (the most powerful) stone or crystal as desired. At the base of the small pillar the summoner can also summon 1D4 lesser stones or crystals. Alternatively, the spell caster can summon 1D4+1 lesser stones or crystals. Note that all these items are a part of the Living Planet and in each case, their summoning permanently destroys a small amount of the spell caster''s personal P.P.E. base.'),
  ('Summon & Use Symbiotes', 0, 100, '100 points summons any type of worm (3D4 blood worms or 1D4x10 worms of mending), 300 summons one star or claw, 400 summons one crawler.', NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.89', 'rifts', 'Appear within 20 feet (6 m) of the summoner.', 'Permanent/until destroyed.', NULL, 'In domains completely controlled by the Forces of Evil the land resists and the spell caster must roll a 14 or higher. Evil characters have the same problem in lands where they do not dominate. A failed roll means no symbiote and only half the P.P.E. is used. Sometimes Wormwood simply cannot respond (G.M.''s discretion).', NULL, '20 minutes of prayer or concentration.', 'In response to this spell, the ground in front of the spell caster begins to move and a moment later, the symbiote pops out. Note: This power is not available to the Priest of Light, who is impervious to symbiotes.'),
  ('Summon Wind', 0, 60, NULL, NULL, 'import', 'Rifts Dimension Book 1: Wormwood p.90', 'rifts', 'Not applicable.', '15 minutes per level of experience', NULL, 'Not applicable.', '1000 foot (305 m) radius per level of experience.', 'Five minutes of prayer or concentration followed by a stern command.', 'The spell caster can summon an unnatural wind to sweep the area. The speed and force of the wind is 7 mph (11 km) per level of experience and can be completely controlled by the wind maker, who can also change the direction it blows. Windstorms gusting at 50 mph (80 km) or higher force characters moving against the wind to travel at half speed, sound travels half as far, visibility is reduced by 25% and flying skills and stunts suffer -40%. Winds of 80 mph (128.7 km) or greater make travel and flying impossible; human-size to giant characters are knocked down and pushed 1D4x100 yards/meters every time they stand up, and visibility drops to about 20 feet (6 m).')
ON CONFLICT (name) DO UPDATE SET
       level = excluded.level,
       ppe = excluded.ppe,
       ppe_note = excluded.ppe_note,
       variant_note = excluded.variant_note,
       source = excluded.source,
       source_book = excluded.source_book,
       system = excluded.system,
       range = excluded.range,
       duration = excluded.duration,
       damage = excluded.damage,
       saving_throw = excluded.saving_throw,
       area_of_effect = excluded.area_of_effect,
       casting_time = excluded.casting_time,
       description = excluded.description;

-- Read the result back rather than trusting the exit code.
SELECT count(*) AS wormwood_prayers FROM spells WHERE name IN ('Close an Opening', 'Control Temperature', 'Create a Burial Place', 'Create a Fountain of Water', 'Create Life Force Cauldron', 'Create Magic Slime', 'Create an Opening', 'Create a Pillar', 'Create Shelter', 'Create Stairs', 'Create Tunnel', 'Create Wall', 'Create Worm Zombies', 'Destroy Life Force Cauldron', 'Heat Point', 'Hell Fire', 'Invisible to Magic Seeing', 'Life Fuel', 'Locate Places of Evil', 'Locate Food & Resources', 'Locate Home Town', 'Impervious to Symbiotes', 'Mold Structures', 'Open & Close Dimensional Rifts', 'Remove Symbiotes', 'Repel Symbiotes', 'Ride Giant Parasites', 'Summon and use Angel Hair', 'Summon Battle Saints & Orbs', 'Summon Edible Grubs', 'Summon Entities', 'Summon Flies', 'Summon and Command Parasites', 'Summon and use Spirits of Wormwood', 'Summon & Use Stones & Crystals', 'Summon & Use Symbiotes', 'Summon Wind');
SELECT count(*) AS total_spells FROM spells;

-- Records this run. One row per run rather than per file: every statement
-- above guards itself, so this script is safe to re-run.
-- See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-wormwood-prayers.sql');
