-- The 23 rites of African ceremonial magic: seven chants, the Drums of
-- Protection, eight dances and the rain maker's seven dances.
-- Rifts World Book 4: Africa, printed 86-93.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-africa-ceremony-spells.sql
--
-- Read from the book's TEXT LAYER (.cache/books/africa, page_offset 1) by the
-- parser that produced zzzzzzzzzzz-africa-necromancy-and-witch-spells.sql, extended
-- for three things this chapter does: a title that wraps onto a lowercase line
-- ("Rain Maker's Dance" / "of Bad Medicine"), the labels "Range of area
-- affected", "Area of Affect" and "Area affected", and the misprint
-- "Dnration" (printed 92). The extension regenerates the earlier script's
-- thirty rows byte-identically.
--
-- EVERY COST AGREES WITH AN INDEPENDENT READING: the survey's slice reader
-- transcribed all 23 costs from the same pages by hand, and the two readings
-- match figure for figure. The book prints NO LEVEL for any rite and no index
-- for them, so they are level 0, the precedent Wormwood's prayers and this
-- book's witch spells set. Who may lead each rite (priest, rain maker,
-- medicine man) is in its description, as the book states it.
--
-- `Ceremony: ` prefix (Nate's choice, 2026-09-25, from the section title
-- Ceremonial Magic) and tradition `african-ceremonial`. catalog-diff --remote
-- on 2026-09-25 matched none of the 23, prefixed or bare. The near names were
-- checked with scripts/same-spell-lib.mjs and none is the same spell:
-- Water: Rain Dance, Water: Part Waters and Air: Calm Storms differ in cost,
-- area and duration; Clouds of Survival: Calm Storms shares the cost and
-- duration but only 0.09 of its description - it slows a downpour to drizzle.
-- No row carries same_spell_as.
--
-- TEN COSTS ARE SCHEDULES OR QUALIFIED, so `ppe` holds the lowest figure and
-- `ppe_note` the printed wording (migration 021): by caster (Control Ley Line
-- Storms 70/110, Water Doubling 30/50), by weather (Rain Dance 300/950, Part
-- Waters 200/600, Ride the Lightning 100/200), Divining's further 90 to see the
-- evil's face, Remove Taboo's 40 for the initial ritual, and three that say
-- what the points buy (Warning, Drums of Protection, War).
--
-- Left out on purpose: the eleven drum messages (printed 86), coded signals
-- with no cost, and the Medicine Man's area protection ritual and Witch Lure
-- (printed 81-82), prose inside his charm list that ride with those items in
-- the gear import.

INSERT INTO spells
  (name, level, ppe, ppe_note, variant_note, source, source_book, system, range, duration, damage, saving_throw, area_of_effect, casting_time, description, same_spell_as, tradition)
VALUES
  ('Ceremony: Chant of Blessing', 0, 50, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.87', 'rifts', '20 foot (6 m) area.', '24 hours per experience level of the priest.', NULL, 'Not applicable to those who want the blessing.', NULL, NULL, 'One or more priests pray for about five minutes and then chant a blessing for another five minutes. At the end of the ceremony, the subject of the blessing is given minor magical protection and power. +1 to save vs witchcraft, +2 to save vs poisons and disease of all kinds, plus the gift of alertness if the character is a hunter or warrior: +1 on initiative. As many as six people per level of the priest can be blessed.', NULL, 'african-ceremonial'),
  ('Ceremony: Chant to Control Ley Line Storms', 0, 70, '70 for a rain maker or 110 for a medicine man.', NULL, 'import', 'Rifts World Book 4: Africa p.87', 'rifts', 'Half mile (0.8 km) length of ley line per level of the character.', 'Two minutes per level of experience. Can be canceled at any time.', NULL, 'Not applicable.', 'See range.', NULL, 'Note: This chant is exclusive to the rain maker and medicine man O.C.C.s, although priests and others may participate in the ritual and provide additional P.P.E. The chanter cannot create a ley line storm, but can grab hold of one and redirect it. He can hold the storm in one place, send it in the opposite direction, reduce its intensity by half, and is never struck by its energy bolts or other phenomena. He can also sense whether the storm is natural or created by magic, a stone pyramid or Millennium Tree. The character can reduce the intensity of a Millennium Storm and escape any damage from it, but he cannot hold it in place or redirect it. The character must continue his chanting the entire time he desires to control the storm.', NULL, 'african-ceremonial'),
  ('Ceremony: Chant/Ritual of Divining', 0, 90, '90; a further 90 (180 in all) to see the face of the evil in the waters.', NULL, 'import', 'Rifts World Book 4: Africa p.87', 'rifts', '3 feet (0.9 m).', 'One minute per level of experience.', NULL, 'Not applicable.', NULL, NULL, 'This ritual involves chanting and foot stomping. Unlike some of the more P.P.E. costing rituals that require scores or hundreds of people, this ceremony can have as few as two other priests or loyal followers. Those participating in the ritual chant, hum and stomp their feet at important intervals for about 15 minutes. At the end of ritual, the head priest drops two small stones into three pots of water and peers into them to glimpse the immediate future (72 hours) or to understand events that are occurring in the present. Three divination questions can be asked and the answers revealed per each minute of the priest''s experience. This divining magic will reveal the following: The presence of good medicine. The presence of bad medicine. The presence of a witch or evil spirits. The presence of the gods. The presence of revenge/hatred. The presence of greed/lust. Where a lost child might be found. Where good hunting might be found. When rains will come - ending a drought. Whether evil spirits are coming. Whether locusts or disease are coming. Whether a particular person is in danger (yes or no). Whether any taboos have been broken (yes or no and which ones). Whether a particular person speaks the truth (yes or no). Whether a particular visitor is dangerous or has evil intentions. The face of evil: The cause of trouble, murder, or bad medicine can be seen in the waters but requires an additional 90 P.P.E. (180 total points).', NULL, 'african-ceremonial'),
  ('Ceremony: Chant of Exorcism', 0, 90, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.87-88', 'rifts', 'Touch or 30 foot (9 m) area.', 'As long as the chant continues, about one hour.', NULL, 'Not applicable.', NULL, NULL, 'This powerful ceremony is usually conducted by a medicine man (who is impervious to possession), but again coordinated by priests. If a medicine man is not available a priest can perform the ceremony but runs the risk of being possessed. The other people and priests involved chant and strike sticks together while swaying back and forth with their eyes closed. As long as they keep their eyes shut the evil spirit cannot possess any of them. Meanwhile, the magic protects all others in the village as long as they stay behind closed doors or keep their eyes shut. The ceremony lasts one hour and at its end the possessing spirit is forced out without failure. The only person who is vulnerable is the priest who is performing the actual exorcism and he is +6 to save vs possession.', NULL, 'african-ceremonial'),
  ('Ceremony: Chant/Ritual to Remove Taboo (Curse)', 0, 40, '40 for the initial ritual.', NULL, 'import', 'Rifts World Book 4: Africa p.88', 'rifts', 'Special', 'Special', NULL, 'Not applicable.', NULL, NULL, 'Note: The ability to remove a taboo is included in this section to keep all the rituals together and easy to find. It is exclusive to the rain maker O.C.C. although priests may participate in the ritual. The victim of a taboo curse must first engage in a brief ritual of penance conducted by a medicine man. This ceremony is said to mark the aura of the character as being sorry and in the process of righting his wrong. To negate the bad medicine of a taboo, it is always required that the offending character(s) make amends/ apologizes for his indiscretions. This will require repairing damage made to the subject of the taboo or area/shrine of the taboo, protecting the taboo subject or area, helping the people (if any) who own the taboo subject, or performing one or more significant acts of kindness, generosity and/or heroism for a worthy person, group of people, or cause. Additionally, the character must perform a brief, nightly or daily prayer lasting only 1D4 minutes to help him reflect upon his life and the cause of his affliction (greed, arrogance, cruelty, carelessness, stupidity, etc.). A taboo curse is not easily removed and may take weeks, months or even years to rid oneself of it. This could send the character on one quest after another (G.M.s, use your discretion and be fair). Killing the taboo maker is an act of complete stupidity, although witches and other evil characters might suggest it. If the taboo maker is slain by the cursed character, the bad medicine can NEVER be removed by any means. Plus a second taboo curse is placed on the person (random roll or select one)! It is also important to note that in many cases the taboo maker has moved away or died years ago.', NULL, 'african-ceremonial'),
  ('Ceremony: Chant of Warning', 0, 120, '120 to provide magic bonuses.', NULL, 'import', 'Rifts World Book 4: Africa p.88', 'rifts', 'One mile (1.6 km)', 'As long as the chant continues.', NULL, 'Versus Horror Factor of 11.', NULL, NULL, 'This is an eerie magic chant performed only by priests to frighten enemies and invaders, both human and inhuman. The chant can be heard only by the enemy for a radius of one mile (1.6 km) per level of the priest leading the chant (who should be the most experienced). The chant is unnerving and evokes a horror factor of 11. All who fail to save vs horror factor will tum and run away. Those who save may continue but are jumpy and are -1 on initiative.', NULL, 'african-ceremonial'),
  ('Ceremony: Chant of Water Doubling', 0, 30, '30 for a rain maker or 50 for a priest.', NULL, 'import', 'Rifts World Book 4: Africa p.88', 'rifts', 'Touch', 'Instant', NULL, 'Not applicable.', NULL, NULL, 'Note: Exclusive to the priest and rain maker. In this ritual, the character chants and hums while pouring equal amounts of water from one container into two other containers. He then does a little rain style dance around the two containers, kneels down, looks into the sky and touches them. Magically, the amount of water doubles in both containers. Unfortunately, water that has been magically doubled once cannot be doubled again. The entire ritual takes about four minutes.', NULL, 'african-ceremonial'),
  ('Ceremony: Drums of Protection', 0, 140, '140 to provide magic bonuses.', NULL, 'import', 'Rifts World Book 4: Africa p.88', 'rifts', 'Two miles (3.2 km)', 'As long as the drums beat.', NULL, 'Not applicable', NULL, NULL, 'A message known to all the people of a tribe, tribal nation, allies and possibly even the enemy is the unmistakable sound of magic protection. This drum beat does two things: one, it warns those in the know that bad medicine is afoot. Second, it lets the perpetrator, typically a witch, demon, evil sorcerer or enemy, know that the tribe is aware of the presence of the bad medicine and the perpetrator and are prepared to fight. The focus and purpose of this drum beat is to encourage the defenders and fill them with confidence. At the same time, it may frighten the perpetrators of the trouble to leave the area and to take the bad medicine with them. All members and friends of the tribe are +1 on initiative and +1 on all saving throws. All bonuses remain in effect as long as the drums play.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance of Blessing Weapons', 0, 890, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.88-89', 'rifts', '10 feet.', 'Permanent', NULL, 'Not applicable', NULL, NULL, 'Limitations: One weapon per level of the priest conducting the ceremony; a dozen arrows or sling stones/bullets counts as one weapon. A bow and string counts as one weapon. This ritual enchants weapons with special magic properties. It involves many people, the playing of drums, and singing. Those who will use the weapons are signaled at the right moment to jump out of the singing crowd, grab their weapon (maximum one in each hand) and dance wildly while chanting and waving the weapons for a period of five minutes. After the allotted dancing, the ceremony is over. The weapons are endowed with the following magic bonuses and powers, but only when they are used by their respective warrior. In the hands of anybody else, the weapon has no magic - the items and the magic are linked to the person it was made for. When that person dies, it turns back into an ordinary item. Note: All weapons inflict their normal S.D.C. amount in mega-damage when used against mega-damage creatures and double damage to witches in human or werebeast form. Bow & Arrows: The bow shoots an additional 200 feet (61 m). The arrows inflict double damage and fly straight and true; +1 to strike. Knife: Never dulls, does an additional 2 points of damage and is +2 to strike when thrown. Spears or Javelin: Never breaks when used by its owner and +2 to strike even when thrown and +2 to damage. Sling and Stones: Double the range and damage. Staff: Never breaks when used by its owner and does an additional 1D6 damage. Sword: Double damage. Throwing Sticks or Irons: Double normal range and damage. War Club, Mace Hammer or Axe: Double damage and +1 to strike and parry. Armor & Shields: The S.D.C. of an ordinary suit of armor or shield turns into M.D.C. whenever engaged in battle against mega-damage forces, creatures, robots and energy weapons. Weapon Note: Swords are seldom used by most African tribes. The most common weapons are spears, war clubs/maces, staves, throwing sticks and the bow and arrow.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance to Chase Away Evil Spirits & Witches', 0, 750, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.89', 'rifts', 'Half mile (0.8 km) radius per level of the priest.', '24 hours per level of the channelling priest.', NULL, '16 to prevent paralysis, but must still leave the area.', NULL, NULL, 'This powerful magic ceremony involves singing and dancing to chase way evil spirits and witches. It is the priest(s) who conducts the ceremony but it can be a priest or medicine man (whichever is more experienced) who channels the magic. All witches and evil spirits who hear the music are racked with pain. Unless they flee the area they will be stricken by paralysis for one day per level of the priest or medicine man channelling the magic. The paralyzed witch or demon may fall victim to wild animals or enemies. Many tribes will go forth the next morning searching the bush for stricken witches and demons to destroy them. Any person possessed by an evil spirit will be identified by falling to the ground where they scream and flail about. A priest or medicine man can then restrain that person and perform an exorcism. Furthermore, no witch or evil spirit may come within earshot of the village (typically about one or two miles) for a period of one week per level of the channeler.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance of Flames', 0, 700, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.89', 'rifts', 'Self and others; one person per level of the ceremonial head priest.', 'Two hours per experience level of the priest conducting the ritual.', NULL, 'Not applicable', NULL, NULL, 'This hour long ceremony involves the drinking of libations, singing and dancing around a large bonfire. Towards the end of the ritual, people selected by the priest are given the gift of invulnerability - provided they jump into the fire and dance in its flames for three to five minutes. If they have faith in the priest and his magic, they are invulnerable and do not bum. Those who refuse to leap into the fire lose the power of invulnerability within one minute after the ceremony''s end. Those who dance in the flames have the following powers: Impervious to fire and heat, impervious to poison, and +5 to save vs all types of magic. Furthermore, those made invulnerab Ie see their S.D.C. points temporarily become M.D.C. points (mega-damage heals at the same rate as S.D.C. damage). The invulnerability lasts for two hours per level of the priest who conducted the ceremony. Typically only trusted priests, warriors, friends and heroes are selected to receive this powerful good medicine.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance of Good Medicine', 0, 475, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.89', 'rifts', 'Entire village.', '24 hours per level of priest.', NULL, 'Not applicable', NULL, NULL, 'The dance of good medicine is conducted by the priest for the purpose of creating good fortune for an important event or activity. Its magic hangs over the village and the people for one day (24 hours) per level of the priest conducting the song and dance. Typical events that elicit the good medicine dance include: Planting: The weather for the days of planting is perfect and crops will grow with few problems from insects and weather. The yield is 20% more than what might normally be expected. Harvesting: The harvesting of crops goes twice as quickly than one might expect, without any serious accidents or problems. First Fruit: Removes any bitterness or possible danger from eating this fruit; no stomach aches. Hunting: The subject of the hunt is found with relative ease, and the hunter(s) will not be bitten or mauled. Travel of Importance: The travelers will not be attacked or troubled by animals or insects and travel time is 20% faster than one might anticipate. Wedding: The married couple and all participants are filled with happiness, there are no squabbles or brawls and nothing goes wrong. Good Health: This dance is usually performed when word spreads about sickness in neighboring areas. The people and livestock are +2 to save vs normal disease and poisoning, +3 to save vs magic sickness and +1 to save vs the magic conjured by a witch.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance of Life', 0, 550, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.89-91', 'rifts', '100 foot (30.5 m) radius.', 'Dance period.', NULL, 'Not applicable.', NULL, NULL, 'This ceremony is used to help heal the sick and wounded, particularly important members of the tribe, fallen heroes and children. The priest(s) orchestrates the ceremony and either a priest or medicine man can channel the magic energy to help the stricken. When there are many, ten or more, the magic ceremony gives all the bonuses of +2 to save vs poison, sickness or magic, +20% to save vs coma and 1D6 hit points are restored at the ceremony''s end. Healing then continues at twice the normal rate! If all this energy is focused on one or two people, they are +40% to save vs coma, +4 to save vs poison, sickness or magic and 2D6 hit points are restored at the ceremony''s end. Healing then continues at twice the normal rate! Note: The characters are also attended to by a priest(s), healer or doctor who bandages wounds, stops bleeding, sets bones, etc.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance of Protection from Bad Medicine', 0, 550, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.91', 'rifts', 'Entire village regardless of size.', '24 hours per level of the priest.', NULL, 'Not applicable.', NULL, NULL, 'This chant and dance creates an aura of protection that covers the entire village. It is typically performed when the town is suspected to be the target of witchcraft or assault by evil spirits, including demons, creatures of magic and evil practitioners of magic. The aura of protection lasts one day (24 hours) per level of the priest who led the ceremony (ideally the priest with the highest level of experience). The magic is powerful and prevents any witch, demon, evil practitioner of magic, or their minions, including magic snakes, summoned insects, shadow beast, entities, etc., from entering the town - it works like a giant, superior circle of protection.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance of War', 0, 240, '240 to provide magic bonuses and penalties', NULL, 'import', 'Rifts World Book 4: Africa p.91', 'rifts', 'Two miles (3.2 km)', 'As long as the drums beat.', NULL, 'Not applicable for tribe members, enemies must roll a 16 or higher to save.', NULL, NULL, 'This powerful magic ritual involves the intense beating of drums and chanting that seems to build and build. The drum beat alerts other priests of a serious impending battle. It also lets the attackers know the tribe will fight with courage and to the death if necessary. The magic strengthens all the members of the village and weakens the enemy. All tribe members, friends and allies feel confident and excited. They are +1 on initiative, +1 to save vs horror factor and +1 on all saving throws. Warriors are also +1 to strike and have one additional attack per melee! The enemy is -1 to strike, parry and dodge, -1 on imitative and -2 to save vs horror factor. All bonuses and penalties remain in effect as long as the drums play and the chant continues, even if they can''t be heard once the battle has begun.', NULL, 'african-ceremonial'),
  ('Ceremony: Dance to Close a Dimensional Rift', 0, 540, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.91', 'rifts', '200 feet (61 m)', 'Instant results.', NULL, 'Standard.', NULL, NULL, 'Note: The medicine man, rain maker and priest all know this ritual. This frightening ceremony involves chanting, drums and concentration. The priest or medicine man must be within 200 feet of the rift, making him and the participants vulnerable to attack from entities and creatures that may emerge from it. The mystic nature of the dimensional gateway gives it an automatic save versus magic attack, but a roll of 16 or higher is needed to save vs magic ritual. The rift will instantly close and vanish if the ritual is successful. Failure means that the rift remains opened and the 540 P.P.E. points have been wasted for nothing. The ritual can be repeated if there is enough P.P.E. available or if a new group of ritual participants are available with sufficient energy resources. Note: Unlike the magic spell, the ritual performer does not permanently lose two P.P.E. points, but the amount of P. P.E. necessary is more than twice as great. The magic from the ritual does provide bonuses of +3 to save vs possession and horror factor to all participants in the ritual.', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Rain Dance', 0, 300, '300 during the rainy season, but 950 during times of drought.', NULL, 'import', 'Rifts World Book 4: Africa p.91', 'rifts', 'Half mile (0.8 km) radius per level of the rain maker.', 'One hour per level of the rain maker. Can be canceled by the rain maker at any time.', NULL, 'Not applicable.', 'See range.', NULL, 'Note: The rain dance is included in this section to keep all the rituals together and easy to find. It is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. The rain dance of the rain maker involves chanting while the rain maker builds a medium-sized fire. The fire is carefully smothered with wet leaves. The leaves are removed to allow the smoke to rise up into the sky. At this point, the participants sing and dance around the smoke, raising their hands and eyes to the sky. The pace of the dance quickens with each passing minute, the tempo kept by the rain maker striking two sticks together. If the magic is working, the sky will begin to darken. At the end of the ceremony, which lasts about 45 minutes, the rain maker picks up a drum and strikes it once with all his might (symbolizes the sound of thunder). Within 1D6 hours the rain will begin to fall. Rain will fall for a period of one hour per level of the rain maker. The magic gives the character complete control over the rain. This means he can make it rain lighter, heavier, control the area covered by the rain and stop it at any moment. Once stopped, the magic is ended. To get it to rain again a new ritual must be performed. Note: Too much rain may cause flash floods, rivers to over flow, and crops to be damaged. Greedy or evil rain makers sometimes black mail people into paying him more under the threat of destructive rains and lightning (remember this character can control and direct lightning during any storm).', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Dance of Bad Medicine', 0, 500, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.92', 'rifts', 'Half mile (0.8 km) radius per level of the rain maker.', 'Five minutes per level of the character. Can be canceled by the rain maker at any time.', NULL, 'Not applicable.', 'See range.', NULL, 'Note: The dance is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. Slimy things: small fish, snails, slugs, leeches, tiny frogs or any combination fall from the sky accompanied by a light rain. They are squishy, icky, and foul smelling. They are about the size of a man''s hand and most are still alive and squiggling around. The slimy things do no physical damage except to make the area and anybody caught in the rain stink for 2D4 days. Animals may panic (1-50%) and run away. The slimy creatures are not edible. Eating them will cause the eater to endure 4D6 hit point damage from poison and suffer from severe stomach cramps, fever, vomiting, and diarrhea for I D4 +1 days. Furthermore, the unnatural rain means two things: A rain maker is angry, the offending party has been branded, and the village or people are cursed with bad medicine. All people caught in the rain or who live in the area smell of bad medicine and will experience bad luck as long as the smell remains (2D4 days). Penalties from the bad medicine: -2 on initiative, -1 to parry and dodge, - I on all saving throws, and -15% on all skills. Anything else bad that happens will be attributed to the bad medicine. This is why nobody should cheat or anger a rain maker.', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Dance to Calm Storms', 0, 200, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.92', 'rifts', 'Half mile (0.8 km) radius per level of the rain maker.', 'One hour per level of the rain maker. Can be canceled by the rain maker at any time.', NULL, 'Not applicable.', 'See range.', NULL, 'Note: The dance is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. The rain maker can perform a dance and a song-like chant that enables him to calm and direct the most fearsome of storms. First, the intensity of the storm is reduced by two-thirds. Second, he keeps the eye of the storm away from the area under his control. Third, he prevents the falling of damaging hail and the striking of lightning in the area. If he so desires, he can direct as many as two mega-damage lightning strikes per melee round (15 seconds and count as all his melee actions) to strike wherever he''d like.', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Dance to Part Waters', 0, 200, '200 during the rain. 600 during clear skies.', NULL, 'import', 'Rifts World Book 4: Africa p.92', 'rifts', '100 feet (30.5 m) per level of experience.', 'Five minutes per level of experience.', NULL, 'Not applicable.', '100 feet wide by 500 feet long (30.5 by 153 m) path/length or area per level of experience.', NULL, 'Note: The dance is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. This ritual involves dance, chants and commands while waving a pair of torches. Its magic is used to push or hold back floodwaters or to magically part a river or lake! The area where the water has been parted is dry and can be walked on.', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Dance to Ride the Lightning', 0, 100, '100 during the rain. 200 during clear skies.', NULL, 'import', 'Rifts World Book 4: Africa p.92', 'rifts', 'Self & up to four others.', 'Instant', NULL, 'Not applicable.', NULL, NULL, 'Note: The dance is included in this section to keep all the rituals together and easy to find. It is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. The performance of a simple, circular dance and humming chant that lasts about five minutes, summons a bolt of lightning that seems to strike the rain maker. There is a blinding flash, a clap of thunder and the character is gone. All that''s left is a tiny cloud of swirling dust. Those who don''t know better may think he has been vaporized. In reality, he has been teleported to a different location. I D6 seconds after he has vanished, the character(s) reappears, miles away, in a flash of lightning and a clap of thunder. Where the lightning seems to strike the rain maker reappears. He can teleport as much as 1000 pounds (450 kg) of belongings or four other people, as long as they all took part in the dance and were clustered together when the lightning came for them. Teleportation range is limited to 20 miles (32 km) per experience level of the rain maker.', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Dance of Stones', 0, 400, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.92-93', 'rifts', '400 feet (122 m) per level of experience.', 'One minute per level of the rain maker. Can be canceled at any time.', NULL, 'Not applicable.', '20 foot (6 m) radius per level of the rain maker.', NULL, 'Note: The dance is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. This dance and chant, where the rain maker throws tiny pebbles into the air, enables him to cause stones to rain down from the sky. The stones are about the size of quarter and can be directed to fall on a specific person, house, vehicle or area. This is another magic ritual used against enemies, cheats, and those who have evoked his anger. One melee round (15 seconds) of exposure will inflict 3D4 X 10 S.D.C. points of damage to people and one M.D. to property. The stones are round like marbles and wet and slippery, making it impossible to move any faster than a speed of eight or one risks slips and falls. Victims of a fall lose one melee action and initiative and suffer 2D6 S.D.C. damage. The raining stones will damage property, smash windows, shred fabrics, destroy crops, kill animals, knock down tree branches, pockmark/dent and crack the surfaces of vehicles, and take hours to clean up.', NULL, 'african-ceremonial'),
  ('Ceremony: Rain Maker''s Dance of Weather Control', 0, 450, NULL, NULL, 'import', 'Rifts World Book 4: Africa p.93', 'rifts', 'Half mile (0.8 km) radius per level of the rain maker.', 'One hour per level of the rain maker. Can be canceled by the rain maker at any time.', NULL, 'Not applicable.', 'See range.', NULL, 'Note: The dance is exclusive to the rain maker O.C.C. although others may participate in the ritual and provide additional P.P.E. The rain maker can grab control of the weather in the area of his control.', NULL, 'african-ceremonial');

-- Read the result back.
SELECT 'ceremony rites inserted' AS assertion, count(*) AS got, 23 AS want
  FROM spells WHERE tradition = 'african-ceremonial' AND name LIKE 'Ceremony: %';

SELECT 'every one cites this book by page' AS assertion, count(*) AS got, 23 AS want
  FROM spells WHERE tradition = 'african-ceremonial'
   AND source_book LIKE 'Rifts World Book 4: Africa p.%';

SELECT 'every one carries a cost, at level 0' AS assertion, count(*) AS got, 23 AS want
  FROM spells WHERE tradition = 'african-ceremonial' AND ppe > 0 AND level = 0;

SELECT 'every one carries a description' AS assertion, count(*) AS got, 23 AS want
  FROM spells WHERE tradition = 'african-ceremonial' AND length(description) > 150;

SELECT 'the ten qualified costs carry their note' AS assertion, count(*) AS got, 10 AS want
  FROM spells WHERE tradition = 'african-ceremonial' AND ppe_note IS NOT NULL;

SELECT 'the rain maker has seven dances' AS assertion, count(*) AS got, 7 AS want
  FROM spells WHERE tradition = 'african-ceremonial' AND name LIKE 'Ceremony: Rain Maker''s %';

SELECT 'Dance of Blessing Weapons is the dearest rite, at 890' AS assertion, count(*) AS got, 1 AS want
  FROM spells WHERE tradition = 'african-ceremonial' AND ppe = 890
   AND ppe = (SELECT max(ppe) FROM spells WHERE tradition = 'african-ceremonial');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-africa-ceremony-spells.sql');
