-- The Gosai Assassin O.C.C., Palladium Fantasy RPG Book 9: The Baalgor Wastelands p.45.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-gosai-assassin-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'gosai-assassin', 'Gosai Assassin', 'palladium-fantasy', '---
id: gosai-assassin
men_of_arms: true
occ_group: men-of-arms
xp_table: [0, 2151, 4301, 9601, 18201, 28401, 38601, 54801, 75201, 100401, 132601, 185801, 240201, 295401, 365601]
name: Gosai Assassin
system: palladium-fantasy
source_book: Palladium Fantasy RPG Book 9: The Baalgor Wastelands p.45
race_restrictions:
  only: ["gosai"]
  note: "A Gosai occupation: the book prints it inside the Gosai entry as the Gosai Assassin Racial Character Class."
category: occ
tags: [combat, stealth, evil]
attribute_requirements: { IQ: 9, PP: 14 }
starting_money: "200"
bonuses:
  combat: { initiative: 1, pull_punch: 2 }
  saves: { horror_factor: 4 }
  at_level:
    - { level: 2, combat: { attacks: 1 } }
    - { level: 8, combat: { attacks: 1 } }
skills:
  hand_to_hand: { costs: {} }
  occ_skills:
    - { name: "Climbing", base: 50, per_level: 5, note: "Climb/Scale Walls (+10%); rappelling is a second percentile, 35% +5%. A Gosai''s prehensile feet add a further +10% to scaling walls; apply by hand." }
    - { name: "Concealment", base: 34, per_level: 4, note: "+14%" }
    - { name: "Detect Concealment", base: 35, per_level: 5, note: "+10%. The Assassin O.C.C. calls it Detect Concealment & Traps." }
    - { name: "Mathematics: Basic", base: 65, per_level: 5, note: "+20%" }
    - { name: "Pick Locks", base: 45, per_level: 5, note: "+15%" }
    - { name: "Prowl", base: 35, per_level: 5, note: "+10%" }
    - { name: "Tracking (people)", base: 35, per_level: 5, note: "+10%. The Assassin O.C.C. calls this Track Humanoids." }
    - { name: "Language: Native Tongue", base: 98, per_level: 0 }
    - { choose: 2, from: ["Language: Other", "Language: Dragonese"], bonus: 15, note: "Two languages of choice (+15% each)" }
    - { choose: 1, categories: [{ name: "Espionage", except: ["Disguise"] }], note: "One Espionage skill, in place of one of the Assassin''s four W.P.s. Never Disguise." }
    - { choose: 1, categories: ["Military"], note: "One Military skill, in place of one of the Assassin''s four W.P.s." }
    - { choose: 1, categories: ["Rogue"], note: "One Rogue skill, in place of one of the Assassin''s four W.P.s." }
    - { choose: 1, categories: ["Science", "Technical"], note: "One Scholar skill, in place of one of the Assassin''s four W.P.s. Scholar skills are filed under Technical and Science in this catalog." }
    - { name: "Hand to Hand: Skudasa", base: 0, per_level: 0, note: "In place of Hand to Hand: Assassin. Cannot be changed, and only the Gosai Assassin may take it." }
  occ_related_skills:
    count: 9
    minimums:
      - { count: 2, category: "Espionage" }
      - { count: 2, categories: ["Physical", "Rogue"] }
    categories:
      - { name: "Communications", bonus: 10, note: "+10%" }
      - "Domestic"
      - { name: "Espionage", except: ["Disguise"], bonus: 10, note: "+10%. Two of the nine must come from here. Never Disguise." }
      - { name: "Medical", only: ["First Aid"] }
      - { name: "Military", bonus: 10, note: "+10%" }
      - { name: "Physical", note: "Two of the nine must come from Physical or Rogue." }
      - { name: "Rogue", bonus: 10, note: "+10%. Two of the nine must come from Rogue or Physical." }
      - { name: "Science", only: ["Mathematics: Advanced"] }
      - { name: "Technical", note: "+15% on language and literacy skills only" }
      - { name: "Technical", only_prefix: ["Language", "Literacy"], bonus: 15, note: "+15% on language and literacy skills only." }
      - "Wilderness"
    schedule: [{ level: 3, count: 1 }, { level: 6, count: 1 }, { level: 9, count: 1 }, { level: 12, count: 1 }]
  secondary_skills:
    count: 2
    schedule: [{ level: 4, count: 2 }, { level: 8, count: 2 }, { level: 12, count: 2 }]
equipment_starting:
  - { item_id: "clothing", qty: 2 }
  - { choose: 1, label: "cape, cloak or jacket", qty: 1, from: ["cape-long", "cape-long-hooded", "jacket-light", "jacket-leather"] }
  - { item_id: "boots", qty: 1 }
  - { item_id: "gloves", qty: 1 }
  - { item_id: "belt", qty: 1 }
  - { item_id: "bedroll", qty: 1 }
  - { item_id: "purse-satchel", qty: 1 }
  - { item_id: "back-pack-pf", qty: 1 }
  - { item_id: "large-sack-pf", qty: 1 }
  - { item_id: "small-sack-pf", qty: 3 }
  - { item_id: "water-skin", qty: 1 }
  - { item_id: "lock-picking-tools", qty: 1 }
  - { item_id: "rope", qty: 2 }
  - { item_id: "grappling-hook", qty: 1 }
  - { item_id: "wooden-spike", qty: "1d4+1" }
  - { item_id: "small-hammer", qty: 1 }
  - { item_id: "small-mirror", qty: 1 }
  - { item_id: "tinder-box", qty: 1 }
restrictions:
  - "Refuses to employ hand to hand weapons of any sort: no W.P., no weapon among the starting equipment, and the claws, feet and pop kicks of Hand to Hand: Skudasa are his fighting."
  - "Cannot take a W.P., a Horsemanship skill or the Disguise skill - among the related skills, and among the secondary skills too."
  - "Metal: this entry states no armor rule for the Gosai Assassin. The Assassin''s studded leather is left out by inference from the Gosai''s contact allergy to metal (1D4 damage per touch, printed 44). The lock picks, grappling hook, hammer and mirror are carried as the Assassin''s list gives them; a G.M. may want them non-metal, which the book does not say."
  - "Armour, as the Assassin O.C.C. row has it (the starting studded leather itself is left out here, see the Metal line): an assassin can use any type from padded to full plate and most own two or three, chosen per assignment: light armour for stealth, heavy for an expected confrontation. Penalties are -15% to prowl and -20% to climb or scale walls in full splint or plate, -10% in chain or scale mail, -5% in studded leather; hard leather, soft leather and padded carry none."
  - "Beyond killing for hire, most assassins also sell the services of a thieves guild: spying and intelligence gathering, strong-arm work, kidnapping, breaking and entering, theft and smuggling. They charge 25-50% more than a thief for these, and the best can command double or triple."
  - "Alignment is the Assassin O.C.C.''s: anarchist or evil only."
  - "The cape, cloak or jacket has 1D6+1 inside pockets, with or without a hood."
  - "The +1 attack at levels two and eight is in addition to hand to hand and any other combat skill, not instead of it."
extraction_notes: |
  - Printed 45 (render p046), inside the Gosai entry''s O.C.C.s Available line: the Gosai Assassin R.C.C. is "identical to the Assassin O.C.C." except that Hand to Hand: Skudasa replaces Hand to Hand: Assassin, and one additional skill selection from each of Espionage, Military, Rogue and Scholar (four in all) replaces the Assassin''s four weapon proficiencies; the Gosai Assassin cannot take a W.P., a Horsemanship skill or the Disguise skill, and refuses to employ hand to hand weapons of any sort. Only the Gosai Assassin R.C.C. may take Hand to Hand: Skudasa.
  - Written out in full from production''s Palladium Fantasy `assassin` row (Palladium Fantasy RPG main book p.94-96) with those changes applied. Attribute requirements, bonuses, the fixed O.C.C. skills, the related-skill floors and counts, secondary skills, money (200 in gold) and the non-weapon equipment are the Assassin''s as that row stores them; this entry prints none of them itself.
  - The changes made: Hand to Hand: Skudasa for Hand to Hand: Assassin (hand_to_hand stays costs: {} - the Assassin''s style cannot be changed and no other is sold); the four W.P.s become four single picks from Espionage (never Disguise), Military, Rogue and Scholar; the related list loses Weapon Proficiencies and Horsemanship, and Espionage loses Disguise together with the +15% the Assassin gets on it.
  - Scholar is the book''s category name; the catalog files those skills under Technical and Science, so that pick spans both.
  - xp_table is this class''s OWN ladder, the "Gosai Assassin R.C.C." column on printed 215 (render p216), lower bounds 0, 2,151, 4,301, 9,601, 18,201, 28,401, 38,601, 54,801, 75,201, 100,401, 132,601, 185,801, 240,201, 295,401, 365,601 (level 15 runs to 425,800). It is not the Assassin''s ladder. No misprints in the column.
  - Hand to Hand: Skudasa, printed 45, level table as printed: 1 two attacks per melee and +2 strike; 2 +3 parry and dodge, +2 pull punch, +2 roll with punch/fall; 3 all kick attacks; 4 +1 attack and +1 initiative; 5 claws 3D6 and pop kick 5D6; 6 critical strike on an unmodified 17-20; 7 hand and foot claws as paired weapons, and may parry swords and other hand held weapons; 8 leap attack, +1 initiative, +2 pull punch; 9 +1 attack; 10 +2 parry and dodge; 11 body throw/flip, +1 initiative; 12 death blow on an unmodified 20; 13 +2 damage; 14 +1 attack; 15 +2 strike and disarm. The catalog''s Hand to Hand: Skudasa skill row carries the same fifteen levels.
  - category occ with race_restrictions only gosai: the book calls it an R.C.C., and it is an occupation only a Gosai takes. occ_group men-of-arms and men_of_arms true because it is the Assassin O.C.C., which the main book prints among the Men of Arms; it states no S.D.C. of its own.
  - tags: evil is carried from the Assassin O.C.C. (anarchist or evil only), which this entry does not change; the Gosai race line on the same page reads "Any, but usually selfish or aberrant evil" and is about the race.
  - Equipment is the Assassin''s without the two daggers, the three weapons of choice and the studded leather. The weapons go because the entry says he uses none. The studded leather is dropped by INFERENCE from the metal allergy on printed 44; this entry states no armor rule.
  - This entry prints no money or equipment line; both are the Assassin''s.
  - restrictions carries the production assassin row''s armor-penalty line and its thieves-guild-services line. That row''s weapon-quality line (every starting weapon a basic S.D.C. weapon of very good quality) was dropped because the class uses no weapons. The armor line''s opening clause about starting in studded leather is not repeated, since the studded leather is left out of the equipment.
  - Printed 215 (render p216): "about 25-30%" of Gosai are Gosai Assassins.
---

# Gosai Assassin

## Lore

Some Gosai make killing their profession and take it further than any ordinary assassin: they will not pick up a hand to hand weapon at all. In its place they learn Skudasa, an unarmed style found nowhere else that blends martial arts with an assassin''s training and is built around the race''s own claws and the snapping kicks of its pop-hinged knees. About 25-30% of the Gosai follow this path.

In every other way the Gosai Assassin works as any assassin does.

## GM Notes

Treat the class as the Assassin O.C.C. with three differences: Skudasa instead of Hand to Hand: Assassin, four extra skills (Espionage, Military, Rogue, Scholar) instead of four weapon proficiencies, and no W.P., Horsemanship or Disguise ever. Nobody else may learn Skudasa. Some Gosai Assassins have gone abroad to hire out, chiefly in the Western Empire, Timiro, the Old Kingdom and parts of the Eastern Territory.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'gosai-assassin');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'gosai-assassin';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-gosai-assassin-class.sql');
