-- Phase 3 of the NPC / bestiary work, tenth book: every species in the Nightbane
-- RPG core book's Denizens of the Nightlands and its vampires (printed 158-192) -
-- rows for creatures (migration 074) and their attacks in stat_attacks
-- (owner_kind 'creature').
--
-- One-off data script, run once per environment. NOT a migration.
--
-- The first NIGHTBANE book: system 'nightbane', an S.D.C. game, so every pool is
-- hit points and S.D.C. and no row carries M.D.C.
--
-- Nine rows are playable, each an already published class (the Doppleganger,
-- Ashmedai, Hunters, Namtar, Snake Bird, Secondary and Wild Vampires, Guardians
-- and Wampyr). The Hound Masters and Night Princes, which the book discourages
-- as player characters and which are not classes, are NPCs with its wording in
-- pools_note, as are the Master Vampire, the Hounds, the Waste Coyote and the
-- Lizard King. The Ashmedai (subtitled The Crawling Horrors) is one row.
--
-- NOT HERE: the Nightlords and their Avatars (printed 171-175), which are
-- individuals; Vampire Intelligences, which the book gives no stat block; the
-- Priest of Night, an occupation.
--
-- The Doppleganger uses a human's hit points and S.D.C. plus 20 (the book says
-- "normal rules"), so its pools are left unrolled with that in pools_note. The
-- Namtar's Hollow Man shell has its own figures, in pools_note.
--
-- EXTRACTED by four book-extract-workers, each given the NAMES of its species,
-- every number read off a 200 dpi render rather than the OCR cache, which carries
-- the digit cipher. RECONCILED by book-reconcile against the renders, row by
-- row; its corrections are applied. Every row passes creatureFormulaGaps, the
-- grammar the endpoint rolls with. description and natural_abilities are short
-- paraphrases - no sentence is the book's.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-creatures-nightbane.sql
--
-- BY CATEGORY:
--   monster (6): Doppleganger, The Hounds, Hound Masters, The Hunters, Snake Bird, The
--     Lizard King
--   demon (3): Ashmedai, Namtar (aka the Hollow Men), Night Princes (aka Squires)
--   animal (1): Waste Coyote
--   undead (4): The Master Vampire, The Secondary Vampire, Wild Vampires, The Wampyr
--   supernatural (1): The Guardians

INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'doppleganger', 'Doppleganger', 'monster', 'nightbane', 1, 'Any', '{"IQ":"3D6","ME":"3D6","MA":"3D6","PS":"3D6","PP":"3D6","PE":"3D6","PB":"3D6","Spd":"3D6"}', NULL, NULL, NULL, '1D4', 'ME+2D6', 'S.D.C. and Hit Points follow normal human rules given elsewhere in the book, plus 20 S.D.C. for a Doppleganger. A magician counterpart Doppleganger gets two-thirds the counterpart P.P.E. instead of 1D4. A psychic counterpart Doppleganger gains all the human powers and two-thirds the human I.S.P. instead of ME+2D6.', NULL, 9, NULL, 'Awakened Dopplegangers get plus 2 to save vs horror factor; all other bonuses as normal humans.', 'Same as normal humans; a player character Doppleganger uses the O.C.C. of its human counterpart to determine available skills.', 'Needs no food or water, feeding on ambient P.P.E. instead. Heals 1 HP/SDC plus P.E. bonus every hour. Immune to the vampire slow-kill bite and cannot be turned into a vampire, though a vampire can still kill it.', 'Only if the human counterpart is a magician; others have none', 'None until awakened; 40 percent of awakened Dopplegangers gain two minor powers from one category (physical, healing, or sensitive)', 'Human range, identical to the counterpart it copies', 'Human range, identical to the counterpart it copies', 'Average 200 years after appearing, usually fully grown; ages slowly', 'The Nightlands, mingling among ordinary Nightlands residents; some cross briefly to Earth', 'Hounds; Hound Masters; Night Princes; Hollow Men; human cultists; rebel Dopplegangers work with Nightbane, vampires, humans and even Guardians', NULL, 'Takes the O.C.C. of the human double it copies, for skill selection', 'A near-exact magical duplicate of a specific living human, dazed in the Nightlands until awakened to hunt or replace its counterpart on Earth.', 'Nightbane RPG p.158-160');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'hounds', 'The Hounds', 'monster', 'nightbane', 0, 'Diabolic (always)', '{"IQ":"2D4","ME":"3D4","MA":"3D4","PS":"3D6+14","PP":"3D6+6","PE":"4D6+4","PB":"1D6","Spd":"1D4x10"}', 'PEx3', '200', NULL, '1D6x10', NULL, 'Attributes are Supernatural (Strength and Endurance). A.R. 13 applies only against normal weapons; Hounds have no A.R. against magical or supernatural attacks.', 13, 13, '{"initiative":1,"strike":1,"parry":1,"dodge":1}', 'Plus 3 save vs magic and psionics, plus 4 save vs horror factor, plus 4 on all perception rolls, immune to illusion and concealment magic and psionics. Takes double damage from magic artifacts, weapons, Talents and powers/spells; takes half damage from all non-magical weapons and attacks. Combat equivalent to hand to hand: assassin, with one extra strike/attack per melee round from level one.', 'Minimal skills; natural tracking 80 percent; understands but cannot speak all languages magically; swimming and climbing 98 percent; W.P. polearm and sword.', 'Immune to illusions and concealment powers; nightvision 2000 ft; expert tracker; self-heals fully after standing still an hour; can smell and track supernatural beings by their signature at 60 ft, 50 percent plus 5 percent per level.', NULL, NULL, '7 feet tall (2.1 m)', '350 lbs (159 kg)', 'Unknown; may live centuries but are often killed in combat or war', 'The Nightlands and, since Dark Day, Earth streets in the thousands', 'Nightlords and their avatars; Dopplegangers (when commanding); Hollow Men; Hunters', 'Nightbane; other supernatural creatures', NULL, 'Skeletal metal-bodied constructs bred for war, tracking supernatural prey by scent and butchering it as shock troops for the Nightlords.', 'Nightbane RPG p.161-162');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'hound-masters', 'Hound Masters', 'monster', 'nightbane', 0, 'Diabolic or Miscreant (never Aberrant or good)', '{"IQ":"2D4+6","ME":"3D4+3","MA":"3D4+3","PS":"2D6+20","PP":"2D6+12","PE":"3D6+10","PB":"1D6","Spd":"1D6x10"}', 'PEx3', '250', NULL, '2D4x10', 'ME+1D6x10', 'Attributes are Supernatural (Strength and Endurance). A.R. 14 applies only against normal weapons; no A.R. against magical or supernatural attacks. I.S.P. also gains plus 2D6 per level of experience beyond the base formula. The book does not recommend it as a player character, though it says what happens if one is played.', 14, 14, '{"initiative":2,"strike":1,"parry":1,"dodge":1}', 'Plus 3 save vs magic and psionics, plus 6 save vs horror factor, plus 4 on all perception rolls, immune to illusion and concealment magic and psionics. Takes double damage from artifacts, weapons and powers/spells; takes half damage from non-magical weapons and attacks. Combat equivalent to hand to hand: assassin, with one extra attack per melee round from level one. Illusion shell: 4 I.S.P. to disguise self, 8 I.S.P. to disguise up to five others; lasts 10 minutes per level solo or 5 minutes per level for a group.', 'Minimal skills; natural tracking 85 percent; speaks all languages magically; swimming and climbing 98 percent; W.P. polearm and battle axe.', 'Immune to illusions and concealment powers; night vision 2000 ft; expert tracker (animals and humans 80%; its skill list says 85%); self-heals fully after standing still an hour; smells and tracks supernatural beings at 80 ft, 50 percent plus 5 percent per level.', NULL, 'Minor psychic abilities: mind block and empathy, plus its own illusion-shell power', '7 feet tall (2.1 m), plus horns', '350 lbs (159 kg)', 'Unknown; may live centuries but are often killed in combat or war', 'The Nightlands, leading Hound units, and occasionally Earth as renegade gang leaders', 'Nightlords and their avatars; Dopplegangers (when commanding); Hollow Men; Hounds (leading); Hunters', 'the Warlords (renegade Hound Masters clash with them)', 'Not recommended as a player character; if played, must be evil or at best a ruthless anarchist', 'Horned, cape-wearing Hound officers with speech and minor illusion powers, commanding squads of ordinary Hounds for the Nightlords.', 'Nightbane RPG p.162-163');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'hunters', 'The Hunters', 'monster', 'nightbane', 1, 'Diabolic', '{"IQ":"2D6","ME":"3D6","MA":"3D6","PS":"3D6+14","PP":"2D6+10","PE":"3D6+6","PB":"1D6","Spd":"1D4x10"}', 'PEx3', '180', NULL, '1D6x10', NULL, 'Attributes are Supernatural (Strength and Endurance). Speed is 1D4x10 on the ground, or 1D4x10+40 while flying. A.R. 13 applies only against normal weapons; no A.R. against magical or supernatural attacks.', 13, 15, '{"initiative":1,"strike":1,"parry":1,"dodge":1}', 'Plus 3 save vs magic and psionics, plus 5 save vs horror factor, plus 4 on all perception rolls, immune to illusion and concealment magic and psionics. Takes double damage from Artifact weapons and powers. Combat equivalent to hand to hand: assassin, with one extra attack from level one.; initiative: +1 ground / +3 air; dodge: +1 ground / +2 additional flying', 'Minimal skills; tracking (sight) 70 percent; understands but cannot speak all languages magically; swimming and climbing 98 percent; W.P. sword or polearm.', 'Winged, vulture-helmed fliers immune to illusions and concealment; nightvision 2000 ft; expert tracker; self-heals fully after standing still an hour; smells and tracks supernatural beings at 100 ft, 40 percent plus 5 percent per level.', NULL, NULL, '7 feet tall (2.1 m)', '400 lbs (181 kg)', 'Unknown; may live centuries but are often killed in combat or war', 'The Nightlands skies over roads and domains; also patrol Earth cities at night', 'Hounds; other Nightlord minions', NULL, NULL, 'Winged, beaked aerial scouts and assassins that fly alongside Hound patrols, hunting and messaging for the Nightlords.', 'Nightbane RPG p.164-165');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'ashmedai', 'Ashmedai', 'demon', 'nightbane', 1, 'Typically Diabolic or Miscreant, with a few Aberrant', '{"IQ":"2D6+12","ME":"2D6+10","MA":"2D6+10","PS":"3D6+14","PP":"2D6+12","PE":"3D6+12","PB":"1D4","Spd":"1D4x10"}', '2D4x10+20', '3D6x10+150', NULL, '2D4', '2D4x10+20', 'Attributes are considered Supernatural; P.B. varies with the assumed shape. S.D.C. of 3D6x10+150 is for base (true) form: minus 100 while wearing a human-sized shape, minus 120 in a small (dog-sized) shape, minus 180 in a tiny (bird/rat) shape, minimum 10. Hit Points stay constant across all forms.', NULL, 14, '{"strike":3,"parry":3,"dodge":3,"roll":5,"pull":5}', 'Plus 3 save vs magic, plus 5 save vs psionics, plus 8 save vs horror factor, not counting attribute bonuses.', 'Can learn 8 skills from any category (no prerequisite waivers) at plus 10 percent plus I.Q. bonus, plus 12 secondary skills; physical-skill combat bonuses apply only in human/humanoid shape; cannot learn hand to hand combat (has instinctive skills instead).', 'Eyeless in true form but sees the invisible and in total darkness to 2000 ft. Bio-regenerates 1D6x10 S.D.C./Hit Points per minute. Shape shifts at will into any living creature down to mouse-size (not insects), including custom monstrous forms; cannot take bio-mechanical forms.', NULL, 'Alter aura, empathy, mind block, see aura, and telepathy', '8 to 12 feet (2.4-3.6 m), head to tail tip, true form; tentacles reach 6 feet (1.8 m)', '300 to 800 lbs (136-362 kg), true form', 'Believed to average 300 years; some live longer', 'A hellish home dimension until summoned; renegades roam the Waste or nest in Earth cities (up to six per nest)', 'Hounds; Hunters; Hollow Men; Nightlords (as servants)', 'Nightlords and their minions (persecute renegade Ashmedai for treachery)', NULL, 'Eyeless, tentacled shape-shifting worm-demons that feed on terror-flavored life force, serving the Nightlords as spies and assassins.', 'Nightbane RPG p.165-166');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'namtar', 'Namtar (aka the Hollow Men)', 'demon', 'nightbane', 1, 'Diabolic or Miscreant', '{"IQ":"3D6+6","ME":"3D6","MA":"3D6","PS":"1D4","PP":"3D6","PE":"2D6","PB":"1D6","Spd":"2D4"}', 'PE+10', '10', NULL, '4D6+10', NULL, 'The Hollow Man construct the Namtar builds and rides inside has its own profile: P.S. 3D6+2, P.P. 3D6, P.E. 3D6, P.B. 3D4, Spd. 3D6+6 (PS/PE Supernatural); S.D.C. 2D4x10+80 with no hit points of its own (SDC only); A.R. 8. The Namtar own A.R. is 12.', 12, 9, '{"initiative":1,"dodge":4}', 'Horror Factor is 11 as the MIB, and 15 when the Namtar climbs out of a Hollow Man. +2 on all perception rolls, +6 save vs horror factor. Add one attack per melee when piloting a Hollow Man construct.', 'Select 10 skills from any category plus a +10% bonus, and 10 secondary skills; typically police and military-oriented skills plus 2-3 weapon proficiencies.', 'Builds human-shaped Hollow Man constructs from mud, blood and secretions to move among humans; perfect color vision, nightvision, understands/speaks all languages, climbs walls; construct fights on until -25 SDC then shatters.', 'Magic-like ability to create Hollow Men and to understand/speak all languages; nothing more.', NULL, 'Namtar 1D6+6 inches; Hollow Man construct typically 6 feet.', 'Namtar 1D4 lbs; Hollow Man construct typically 150-250 lbs.', '500 years.', 'Nightlord palaces in the Nightlands; Hollow Man constructs work as NSB agents (Men In Black) on Earth.', 'Nightlords; other supernatural evils', NULL, NULL, 'Tiny insect-like beings who inhabit blood-and-mud humanoid constructs to infiltrate human society as government agents.', 'Nightbane RPG p.167-168');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'waste-coyote', 'Waste Coyote', 'animal', 'nightbane', 0, 'Considered to be a Miscreant predator', '{"IQ":"2D4","ME":"2D6","MA":"2D6","PS":"1D6+24","PP":"1D6+14","PE":"1D6+20","PB":"1D6","Spd":"1D4x10"}', 'PEx2', '2D6x10+20', NULL, '4D6', NULL, NULL, NULL, 11, '{"attacks":3,"initiative":1,"strike":2,"dodge":3}', '+4 to perception rolls, +4 save vs magic and psionics; bonuses are in addition to attribute bonuses.', NULL, 'Good tracker by sight and scent (78%); hunts in packs of 4-12 led by an alpha, using decoys and ambush tactics; can go months or years without eating, possibly sustained by ambient P.P.E.', NULL, NULL, '8-12 feet long.', '400-800 lbs.', '60 years.', 'Deserts and mountains of the Nightlands; a pack of 2D6 may occasionally be brought to Earth via a Rift, gate or anomaly.', NULL, 'Hounds; Hunters; humans; other predators', NULL, 'Reptilian, bear-like pack predator of the Waste that ambushes travelers and rarely needs to eat.', 'Nightbane RPG p.168');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'snake-bird', 'Snake Bird', 'monster', 'nightbane', 1, 'Any', '{"IQ":"3D6+4","ME":"3D6","MA":"3D6","PS":"1D6","PP":"3D6+6","PE":"2D6+6","PB":"2D6+6","Spd":"1D6x10+50"}', 'PE', '5D6', NULL, 'PEx5', NULL, 'Hit Points: plus 1D4 per level of experience. P.P.E.: plus 12 per level of experience.', NULL, 8, '{"attacks":3,"initiative":1,"strike":5,"dodge":5,"damage":6}', 'Air bonuses shown above; on the ground only +2 to strike and dodge. Two attacks instead of three when relying on magic; +1 attack at levels four and eight. +2 save vs psionics, +2 save vs magic, +3 save vs horror factor; excludes P.P. bonuses.', 'Prowl (silent swooping attack) 62%, track by smell 50%, occult lore +20%; speaks Dragonese and two languages of choice at +20%; plus 8 secondary skills, mostly Technical category.', 'Flight; senses supernatural creatures within 100 feet; exceptional vision to 2 miles; nightvision 500 feet; regenerates 5 SDC/HP at the end of each melee round.', 'Natural spellcaster gaining spells via mystic revelation: 6 spells from levels 1-3 at first level, 2 more spells (of level equal or below current level) per additional level; otherwise works as the mystic class.', NULL, 'Body 4-5 feet long, wingspan 7-10 feet.', '15-20 lbs.', '300 years; a few reach 12th level or higher.', 'Any, prefers mountains; found in the Nightlands and occasionally on Earth and other dimensions.', 'occasional familiars to magicians or Nightbane', 'large predators; the Nightlords and their minions', 'Uses the Mystic experience table if played as a PC.', 'Sentient, brightly colored flying serpent and natural spellcaster, sometimes kept as a demonic pet.', 'Nightbane RPG p.169');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'lizard-king', 'The Lizard King', 'monster', 'nightbane', 0, 'Considered to be diabolic', '{"IQ":"1D6","ME":"2D6","MA":"2D6","PS":"2D6+29","PP":"1D6+15","PE":"2D6+17","PB":"2D4","Spd":"1D4x10"}', '1D6x10+20', '2D6x10+100', NULL, '6D6', NULL, 'Supernatural Strength and Endurance.', 12, 11, '{"attacks":4,"strike":3,"dodge":4}', 'A.R. 12 is against normal weapons only; zero against magical/supernatural attacks. +2 on all perception rolls, +3 save vs magic, +3 save vs psionics, +9 save vs Horror Factor; excludes attribute bonuses.', NULL, 'Psychic vampire that feeds on the death-agony P.P.E. of living things; can go 1D4 months without feeding or live indefinitely near a ley line/nexus; heals 1D4x10 SDC/HP per minute; nightvision 1000 feet, tracks by smell 54%.', NULL, NULL, '12-20 feet long.', '1 to 1.5 tons.', '40 years.', 'Any; favors areas around ley lines, in the Nightlands and occasionally on Earth.', NULL, 'minions of the Nightlords who hunt them on sight', NULL, 'Mutated, supernatural Komodo-dragon-like predator that feeds on the death agonies and P.P.E. of living things.', 'Nightbane RPG p.170');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'night-princes', 'Night Princes (aka Squires)', 'demon', 'nightbane', 0, 'Diabolic or Miscreant', '{"IQ":"3D6+6","ME":"3D6+6","MA":"3D6+6","PS":"3D6+10","PP":"3D6+4","PE":"2D6+18","PB":"3D6+6","Spd":"5D6"}', 'PEx2', '2D4x10+120', NULL, '1D4x100', NULL, 'Hit Points: plus 2D6 per level of experience. P.P.E.: plus 15 per level of experience. Formal designation is Ba''al-Zebul R.C.C.; Night Squires are simply low-level Night Princes who have not yet distinguished themselves. The book allows a G.M. to permit one as a player character but discourages it (p.176).', NULL, 9, '{"parry":1,"dodge":2,"roll":2,"pull":5}', 'Base Horror Factor 9, but can create illusions with an H.F. of up to 18 (illusion base H.F. 10, +1 per 3 extra P.P.E. spent). +4 save vs magic, +3 save vs psionics, +5 to perception rolls, +6 save vs horror factor. Combat is equivalent to Hand to Hand: Assassin, with one additional attack per melee at level one.', 'Occult Lore +20%, speaks 8 languages at 98%, plus 10 skills from any category (must include prerequisites) at +10%, plus 12 secondary skills.', 'Heals 1D4x10 SDC/HP per minute; sees the invisible and all illusions; impervious to mind control; nightvision 500 feet; senses ley lines/nexus points within a mile; needs no food, drink or air; feeds on the life force of others.', 'Natural illusion powers only (no true spellcasting); can replicate any illusionary spell effect.', NULL, 'Normal human size.', 'Normal human weight.', 'Unknown; presumed to be immortal.', 'Earth, posing as movie stars, jet-setters, corporate officers and political advisors; also the Nightlands.', 'Nightlords; Hound Masters; Hollow Men; Ashmedai', 'Nightbane; Guardians; vampires and wampyrs (who destroy them on sight)', 'G.M. Note: it might be possible to allow player character Night Princes, though this is discouraged.', 'Human-looking energy-vampire lieutenants of the Nightlords who deceive and manipulate humanity through illusion.', 'Nightbane RPG p.175-177');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'master-vampire', 'The Master Vampire', 'undead', 'nightbane', 0, 'Any evil', '{"IQ":"14+2D6","ME":"10+3D6","MA":"12+3D6","PS":"18+3D6","PP":"10+3D6","PE":"18+1D6","PB":"16+2D6","Spd":"10+4D6"}', '3D6x10', NULL, NULL, '1D6x10', '3D6x10', 'Book merges S.D.C. and Hit Points into one flat Hit Point Equivalent pool (3D6x10); no separate S.D.C. figure is given.', NULL, 14, '{"attacks":6,"initiative":3}', 'Plus 5 save vs Horror Factor, plus 4 perception, impervious to mind control and to psionic/magic sleep and paralysis; master psionic, save 10+ vs psionics.', 'Retains only the I.Q. bonus from past skills (O.C.C. bonuses forgotten), frozen at proficiency when turned; plus 3 new skills per 100 years from Communications, Domestic, Piloting, Technical, Rogue, Wilderness, W.P.', 'Six attacks per round, or up to two psionic combined with physical; regenerates 2D6 per melee, survives to -20 HP; shifts into bat, wolf or mist; near-immune to normal weapons; killed by decapitation plus fire, sunlight, running water, or loss of native soil; wards: crosses, garlic, wolfbay.', 'Retains pre-transformation spells if any, frozen at rebirth''s power level; cannot learn new magic or raise personal P.P.E.', 'Full vampire psionic list (about 4th-level powers) plus automatic mind control over lesser vampires and a telepathic link to its creations; master psionic (save 10+); I.S.P. 3D6x10.', 'Varies, generally human', 'Varies, generally human', 'Never ages; effectively immortal undead', 'Not stated', 'own kind/creations; occasionally Nightbane (uneasy, likely to be betrayed); ghouls; other supernaturals; humans if useful', 'the Nightlords/Ba''al; Guardians (feared above all); humankind (prey)', NULL, 'An evil human or humanoid who chose undeath, founding a vampire bloodline that anchors an alien vampire intelligence in the world.', 'Nightbane RPG p.179-181');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'secondary-vampire', 'The Secondary Vampire', 'undead', 'nightbane', 1, 'Selfish or evil; unprincipled good (selfish) possible for PCs fighting their bloodlust', '{"IQ":"3D6+2","ME":"3D6+6","MA":"3D6+6","PS":"3D6+14","PP":"3D6+8","PE":"1D6+16","PB":"2D6+4","Spd":"3D6+10"}', '3D4x10', NULL, NULL, '1D4x10', NULL, 'Book gives one flat equivalent of 3D4x10 hit points (S.D.C./Hit Points merged); no separate S.D.C. figure. No I.S.P. formula is printed for this subspecies, unlike the master and wild vampires.', NULL, 12, '{"attacks":5,"initiative":2}', 'Plus 3 save vs Horror Factor, plus 3 perception, plus 3 save vs magic/psionic mind control, impervious to psionic/magic sleep and paralysis; major psionic, save 12+ vs psionics.', 'Retains about 10 skills from its past life, frozen at first level proficiency; plus 2 more skills at levels 3, 6, 9, 11 and 13, from Communication, Domestic, Piloting, Technical, Rogue, Wilderness, W.P.', 'Five attacks per round, or up to two psionic combined with physical; regenerates 2D6 per melee, survives to -20 HP; shifts into bat, wolf or mist; near-immune to normal weapons; killed by decapitation plus fire, sunlight, running water, or loss of native soil; wards: crosses, garlic, wolfbay.', 'Retains about half of any pre-transformation spells, frozen at current power; cannot learn new spells.', 'Same vampire psionic list as the master; susceptible to a master''s mind control; major psionic (save 12+); no I.S.P. figure printed.', 'Varies, generally human', 'Varies, generally human', 'Presumed to be immortal', 'Not stated', 'own kind, though often independent of a master (especially unprincipled/anarchist ones); possibly Nightbane or humans for the rare good-aligned', 'the Nightlords; Guardians; family/friends they target as slow-kill victims', NULL, 'A vampire made by a master''s slow-kill bite; keeps more human memory than other undead and occasionally resists its bloodlust.', 'Nightbane RPG p.181-182');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'wild-vampires', 'Wild Vampires', 'undead', 'nightbane', 1, 'Evil or anarchist; mostly diabolic or miscreant, radiates supernatural evil', '{"IQ":"2D6+1","ME":"3D6+4","MA":"2D6+2","PS":"3D6+14","PP":"3D6+8","PE":"1D6+16","PB":"1D6+2","Spd":"5D6+10"}', '2D4x10', NULL, NULL, '6D6', '1D6x10', 'Book gives one flat 2D4x10 Hit Points figure (S.D.C./Hit Points merged); no separate S.D.C. figure.', NULL, 12, '{"attacks":5,"initiative":2}', 'Plus 2 save vs Horror Factor, plus 1 save vs magic/psionic mind control (plus any M.E. bonus), impervious to psionic/magic sleep and paralysis; minor psionic, save 12+ vs psionics.', 'Retains only 6 skills from its past life, frozen at second level, no bonuses; PCs add one secondary skill at levels 2, 4, 6, 8, 11 and 14, from Communication, Domestic, Piloting, Technical, Rogue, Wilderness, W.P.', 'Five attacks per round, or up to two psionic combined with physical; regenerates 2D6 per melee, survives to -20 HP; shifts into bat, wolf or mist; near-immune to normal weapons; killed by decapitation plus fire, sunlight, running water, or loss of native soil; wards: crosses, garlic, wolfbay.', NULL, 'Same vampire psionic list as the master; minor psionic (save 12+); I.S.P. 1D6x10.', 'Varies, generally human', 'Varies, generally human', 'Presumed to be immortal', 'Worst city slums or remote wilderness areas; small bands roam the Nightlands, especially the Waste', 'subservient to their master or secondary vampire creator; ultimately subservient to the vampire intelligence', 'hunted mercilessly by Nightlord minions; the Nightlords generally; Guardians', NULL, 'A feral, mentally diminished vampire born from starvation-driven madness or a secondary''s bite; savage and consumed by bloodlust.', 'Nightbane RPG p.182-183');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'guardians', 'The Guardians', 'supernatural', 'nightbane', 1, 'Almost always principled or scrupulous; evil Guardians are a rare, hunted minority', '{"IQ":"2D4+16","ME":"2D6+16","MA":"2D6+12","PS":"2D4+14","PP":"2D4+16","PE":"2D6+14","PB":"1D6+14","Spd":"2D6+20"}', 'PEx2', '2D6x10+100', NULL, 'PEx5', 'ME+1D6x10', 'Spd formula (2D6+20) is for running; Guardians can also hover (2 P.P.E.) or fly (6 P.P.E., 40 mph max, 2000 ft ceiling). Hit Points add 2D6 per level of experience. S.D.C. also gets unlisted skill bonuses. P.P.E. adds 20 per level. I.S.P. adds 10 per level. Horror Factor rises to 12 when a Guardian displays its energy powers, often read as awe or adoration instead of fear.', NULL, 9, '{"initiative":1,"dodge":1,"roll":2,"pull":4}', 'Plus 3 perception, plus 4 save vs magic, plus 3 save vs psionics, plus 5 save vs Horror Factor; master psionic.', 'Select 10 skills plus 8 secondary from a fixed, mostly non-technological list (Domestic, First Aid/holistic/paramedic, Physical, Pilot auto/motorcycle/horse, Technical, W.P., Wilderness); plus 1 skill at levels 3, 6, 9 and 12.', 'Precognitive hunches guide them to trouble; perfect nightvision and full-spectrum sight; rapid regeneration plus touch-healing costing P.P.E.; fires light bolts and shields; nullifies spells; hovers or flies; needs no food, water or air, only sunlight.', NULL, 'Empathy, mind block, presence sense, see aura; plus 1 sensitive or healing power per level after the first; master psionic; I.S.P. M.E. plus 1D6x10, plus 10 per level.', '5 feet (1.5 m) on average', 'Not stated', 'About 300-400 years, roughly four times a normal human''s', 'Soup kitchens, churches, temples, the biggest cities and worst slums; some keep a wilderness or mountaintop retreat', 'normal humans (who often view them as angels); psychics and practitioners of magic; dedicated, good-aligned Nightbane; occasional Wampyr or Doppleganger', 'true vampires; the Nightlords and their minions; diabolic Nightbane and other evil supernaturals', NULL, 'Amnesiac, light-wielding supernatural beings who heal and fight with equal ease, hunting evil while barely remembering their own origin.', 'Nightbane RPG p.189-192');
INSERT INTO creatures (slug, name, category, system, playable, alignment, attributes, hp, sdc, mdc, ppe, isp, pools_note, ar, horror_factor, combat, bonuses_note, skills_note, natural_abilities, magic, psionics, size, weight, life_span, habitat, allies, enemies, occ_note, description, source_book) VALUES (
  'wampyr', 'The Wampyr', 'undead', 'nightbane', 1, 'Any except principled; scrupulous ones avoid drinking from the unwilling', '{"IQ":"3D6+1","ME":"1D6+14","MA":"3D6+6","PS":"3D6+12","PP":"3D6+6","PE":"3D6+8","PB":"3D6+3","Spd":"3D6+6"}', 'PEx2', '2D6x10+20', NULL, '1D4+2', 'ME+2D4x10', 'Hit Points add 1D6 per level of experience (base P.E.x2 printed here). S.D.C. figure is ''plus those gained before the transformation from physical skills and O.C.C.s.'' Most P.P.E. is permanently lost during the transformation; 1D4+2 is what typically remains. I.S.P. adds 8 points per level of experience (base M.E. plus 2D4x10 printed here).', NULL, 11, NULL, '+1 on initiative, +3 on all perception rolls, +5 to save vs Horror Factor, +5 to save vs all forms of mind control and possession, and immune to vampire mind control powers.', 'Select 10 skills and 8 secondary skills, plus select an additional skill at levels four, seven, ten and twelve; chosen to conform with the character''s occupation/education before the transformation.', 'Regenerates 2D6 S.D.C./hit points per melee round like a true vampire, with supernatural strength and endurance and access to psychic powers; takes half damage from metal weapons but has none of the true vampire''s other invulnerabilities. Vulnerable: must drink a pint of blood every three days or, after a week, fall into a feeding frenzy; direct sunlight does 2D6 damage a minute and costs one attack, -1 on combat rolls, -2 on initiative and perception and -20% on skills while exposed.', 'None; Wampyrs cannot work magic, and any pre-transformation magic powers are lost forever.', 'Starts with all vampire psionic powers except super hypnotic suggestion; gains one additional power from any of the three psychic categories every level after the first.', 'As a normal human', 'As a normal human', 'Unknown, possibly limitless', 'Not stated', 'human vampire hunters and other enemies of vampires; some serve the Nightlords, hunting true vampires (evil/anarchist Wampyrs only); human and Nightbane groups, warily (good/anarchist Wampyrs); occasionally a good-aligned Guardian group', 'vampire intelligences and master vampires (attack on sight, no quarter); true vampires generally, who see Wampyrs as aberrations', NULL, 'A vampire whose slow-kill transformation didn''t fully take hold, leaving a free-willed, blood-drinking being vulnerable to sunlight but immune to most classic vampire weaknesses.', 'Nightbane RPG p.188-189');

INSERT INTO stat_attacks (owner_kind, owner_slug, name, damage, is_mega_damage, range, note, sort) VALUES
  ('creature', 'hounds', 'Darkblade Spear', '3D6+PS', 0, 'melee', 'cuts through all known materials including steel; rarely issued other weapons', 0),
  ('creature', 'hound-masters', 'Darkblade Spear', '3D6+PS', 0, 'melee', 'rarely issued other weapons', 0),
  ('creature', 'hunters', 'Darkblade Scimitar', '2D6+PS', 0, 'melee', 'typical weapon', 0),
  ('creature', 'hunters', 'Darkblade Spear (rare)', '3D6+PS', 0, 'melee', 'rarely wielded alternative', 1),
  ('creature', 'hunters', 'Beak', '3D6 S.D.C.', 0, 'melee', NULL, 2),
  ('creature', 'ashmedai', 'Tentacle', '1D6+6 added to supernatural P.S. damage', 0, '6 ft reach', 'true form only', 0),
  ('creature', 'ashmedai', 'Beretta 95 (NSB agents)', '2D6', 0, 'ranged', '20-round magazine, can fire bursts or full auto', 1),
  ('creature', 'waste-coyote', 'Bite', '4D6 SDC', 0, 'melee', '', 0),
  ('creature', 'waste-coyote', 'Claws', 'Supernatural PS +2D6 SDC', 0, 'melee', '', 1),
  ('creature', 'snake-bird', 'Claws', '2D6', 0, 'melee', '', 0),
  ('creature', 'snake-bird', 'Bite', '1D8 plus poison', 0, 'melee', 'poison: 3D6 direct to hit points round one, then 1D6 per melee for 1D6 melees unless a save vs poison is made (half damage on a success); affects supernatural beings too', 1),
  ('creature', 'lizard-king', 'Bite', '5D6 SDC', 0, 'melee', '', 0),
  ('creature', 'lizard-king', 'Kick', '3D6 SDC', 0, 'melee', '', 1),
  ('creature', 'lizard-king', 'Tail Swipe', '4D6 SDC', 0, 'melee', '', 2),
  ('creature', 'lizard-king', 'Head Butt', '2D6 SDC', 0, 'melee', '', 3),
  ('creature', 'lizard-king', 'Body Ram/Trample', '5D6 SDC', 0, 'melee', '', 4),
  ('creature', 'master-vampire', 'Killing Bite', '3D6+PS bonus', 0, 'melee', 'Also damages other vampires', 0),
  ('creature', 'master-vampire', 'Bat Form Bite', '2D6', 0, 'melee', 'S.D.C. damage, while in bat form', 1),
  ('creature', 'master-vampire', 'Bat Form Claws', '1D6+PS bonus', 0, 'melee', 'While in bat form', 2),
  ('creature', 'master-vampire', 'Wolf Form Bite', '5D6', 0, 'melee', 'No P.S. bonus; while in wolf form', 3),
  ('creature', 'secondary-vampire', 'Killing Bite', '2D6+PS bonus', 0, 'melee', 'Also damages other vampires', 0),
  ('creature', 'secondary-vampire', 'Bat Form Bite', '2D6', 0, 'melee', 'S.D.C. damage, while in bat form', 1),
  ('creature', 'secondary-vampire', 'Bat Form Claws', '1D6+PS bonus', 0, 'melee', 'While in bat form', 2),
  ('creature', 'secondary-vampire', 'Wolf Form Bite', '5D6', 0, 'melee', 'No P.S. bonus; while in wolf form', 3),
  ('creature', 'wild-vampires', 'Killing Bite', '2D6+PS bonus', 0, 'melee', 'Also damages other vampires', 0),
  ('creature', 'wild-vampires', 'Bat Form Bite', '2D6', 0, 'melee', 'S.D.C. damage, while in bat form', 1),
  ('creature', 'wild-vampires', 'Bat Form Claws', '1D6+PS bonus', 0, 'melee', 'While in bat form', 2),
  ('creature', 'wild-vampires', 'Wolf Form Bite', '5D6', 0, 'melee', 'No P.S. bonus; while in wolf form', 3),
  ('creature', 'guardians', 'Hand to Hand Strike', 'supernatural strength table', 0, 'melee', 'Typically Hand to Hand: Basic; varies with skill selected', 0),
  ('creature', 'guardians', 'Light Energy Bolt', '1D6 S.D.C. per P.P.E. spent', 0, 'line of sight', 'Plus 3 to strike', 1);

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 15 creatures are in' AS assertion, count(*) AS got, 15 AS want
  FROM creatures WHERE slug IN ('doppleganger', 'hounds', 'hound-masters', 'hunters', 'ashmedai', 'namtar', 'waste-coyote', 'snake-bird', 'lizard-king', 'night-princes', 'master-vampire', 'secondary-vampire', 'wild-vampires', 'guardians', 'wampyr');
SELECT 'and their 30 attacks' AS assertion, count(*) AS got, 30 AS want
  FROM stat_attacks WHERE owner_kind = 'creature' AND owner_slug IN ('doppleganger', 'hounds', 'hound-masters', 'hunters', 'ashmedai', 'namtar', 'waste-coyote', 'snake-bird', 'lizard-king', 'night-princes', 'master-vampire', 'secondary-vampire', 'wild-vampires', 'guardians', 'wampyr');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-creatures-nightbane.sql');
