-- The Humpback Whale R.C.C., Rifts World Book 7: Underseas p.90-92.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-humpback-whale-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'humpback-whale', 'Humpback Whale', 'rifts', '---
id: humpback-whale
name: Humpback Whale
system: rifts
source_book: Rifts World Book 7: Underseas p.90-92
category: rcc
attribute_dice:
  IQ: "2d6+6"
  ME: "2d6+10"
  MA: "2d6+10"
  PS: "3d6+30"
  PP: "3d6+6"
  PE: "3d6+10"
  PB: "2d6"
  Spd: "2d6+14"
hit_points_base: "P.E. x8, +10 per level"
sdc_base: "3d6x10"
ppe_base: "P.E. + 4d4x10, +20 per level"
bonuses:
  combat: { attacks_base: 1, strike: 1, dodge: 1, pull_punch: 1, roll: 2 }
  saves: { horror_factor: 5, toxins_poisons: 2, disease: 2, mind_control: 2 }
  at_level:
    - { level: 2, combat: { attacks: 1 } }
    - { level: 5, combat: { attacks: 1 } }
    - { level: 8, combat: { attacks: 1 } }
    - { level: 11, combat: { attacks: 1 } }
    - { level: 14, combat: { attacks: 1 } }
magic:
  type: "spell"
  spell_lists:
    spellsongs:
      - "Spellsong: Song of Calling"
      - "Spellsong: Song of Danger"
      - "Spellsong: Song of Doubt"
      - "Spellsong: Song of Fear"
      - "Spellsong: Song of Grief"
      - "Spellsong: Song of Joy"
      - "Spellsong: Song of Life"
      - "Spellsong: Song of Protection"
      - "Spellsong: Song of Revenge"
      - "Spellsong: Song of Reversal"
      - "Spellsong: Song of Sea Sickness"
      - "Spellsong: Song of Severing"
      - "Spellsong: Song of Sleep"
      - "Spellsong: Song of Strength"
      - "Spellsong: Song of Summoning"
      - "Spellsong: Song of Weaving"
      - "Spellsong: Sonic Boom"
      - "Spellsong: Sound Blast"
      - "Spellsong: Sound Spike"
      - "Spellsong: Stormsong"
      - "Spellsong: Valorsong"
  spells_starting_groups:
    - { count: 4, from_list: "spellsongs" }
  spells_schedule:
    - { level: 2, count: 2, from_list: "spellsongs" }
    - { level: 3, count: 1, from_list: "spellsongs" }
    - { level: 4, count: 1, from_list: "spellsongs" }
    - { level: 5, count: 1, from_list: "spellsongs" }
    - { level: 6, count: 1, from_list: "spellsongs" }
    - { level: 7, count: 1, from_list: "spellsongs" }
    - { level: 8, count: 1, from_list: "spellsongs" }
    - { level: 9, count: 1, from_list: "spellsongs" }
    - { level: 10, count: 1, from_list: "spellsongs" }
    - { level: 11, count: 1, from_list: "spellsongs" }
    - { level: 12, count: 1, from_list: "spellsongs" }
    - { level: 13, count: 1, from_list: "spellsongs" }
    - { level: 14, count: 1, from_list: "spellsongs" }
    - { level: 15, count: 1, from_list: "spellsongs" }
skills:
  occ_skills:
    - { name: "Swimming", base: 98, per_level: 0, note: "At 98%, a fixed figure." }
    - { name: "Track & Hunt Sea Animals", base: 40, per_level: 5, note: "+5%" }
    - { name: "Navigation: Underwater", base: 50, per_level: 4, note: "Printed as Underwater Navigation (+20%)." }
    - { name: "Undersea & Sea Survival", base: 35, per_level: 5, note: "Printed as Undersea Survival (+10%)." }
    - { choose: 1, from: ["Language: Other"], bonus: 5, note: "One human language of choice (+5%), probably American/English." }
  occ_related_skills:
    count: 3
    schedule: [{ level: 3, count: 1 }, { level: 7, count: 1 }, { level: 11, count: 1 }, { level: 15, count: 1 }]
    categories:
      - { name: "Communications", only: ["Radio: Basic", "Sing"] }
      - { name: "Domestic", only: ["Dance", "Fishing"] }
      - { name: "Espionage", only: ["Detect Ambush", "Detect Concealment", "Intelligence"] }
      - { name: "Pilot", only: ["Robots & Power Armor"] }
      - { name: "Rogue", except: ["Computer Hacking"], bonus: 4 }
      - { name: "Science", only: ["Mathematics: Basic"], bonus: -10 }
      - { name: "Technical", only_prefix: ["Language", "Lore"], only: ["Advanced Fishing", "Undersea Salvage"] }
      - { name: "Wilderness", only: ["Undersea & Sea Survival", "Track & Hunt Sea Animals"] }
    note: "Electrical, Mechanical, Military, Physical, Pilot Related and W.P. are barred entirely. Three of these entries reach across the catalog''s filing: the book grants SING under Domestic and the catalog files it under Communications; it grants PROWL under Rogue where the catalog files it under Physical; and its Technical line - language, lores and underwater skills only - is a prefix restriction rather than a name list. See extraction_notes. The -10% the book prints on the Communications line applies to Radio: Basic only and is NOT stored as a category bonus, because that would apply it to Sing as well. Pilot is barred except specially designed power armour. Medical is barred entirely here, unlike the dolphin, orca and sperm whale, which all get Sea Holistic Medicine."
  secondary_skills:
    count: 0
    schedule: [{ level: 3, count: 1 }, { level: 8, count: 1 }, { level: 12, count: 1 }, { level: 15, count: 1 }]
    note: "The character starts with NO secondary skills and gains one on the schedule above, without bonuses. Chosen from the same categories as the related skills."
restrictions:
  - "Alignment: any, but usually good - typically 50% scrupulous, 15% principled, 15% unprincipled, 10% anarchist and 10% other. The most reliably good-aligned of the four."
  - "THIS IS AN S.D.C. CREATURE, not a mega-damage one. It becomes mega-damage only while ley line charged."
  - "Natural A.R. 1D6+5."
  - "HIT POINTS AND S.D.C. BOTH HAVE TWO FIGURES AND THE SMALLER IS STORED. Hit points are P.E. x8 for females and young and P.E. x10 for a full-grown male, +10 per level either way. S.D.C. is 3D6x10 for females and young, 5D6x10 for a full-grown male."
  - "Horror Factor: 10 when angry or attacking."
  - "Size: males average 60 to 70 feet (18.3 to 21.3 m), females 40 to 48 feet (12.2 to 14.6 m). Weight 60 to 70 tons for a full-sized adult, 30 to 40 for a female."
  - "Average life span: 70 to 100 years, maturity at 11 to 13."
  - "ALL HUMPBACKS HAVE SOME PSIONIC POWER. Printed 92 rolls the degree on a table rather than granting a set, which is why no psionics block is stored - but unlike the dolphin and the orca, where most have none, here every character has something."
  - "Spellsong strength is +1 at levels two, five, eight and twelve. It is +6 to save against whale spellsongs specifically - the highest in the book - on top of +1 against magic generally."
  - "NO AUTOMATIC DODGE. It parries with nose or tail at +1."
  - "It is a filter feeder, straining krill and shrimp through baleen plates."
  - "The humpback gets +20% to Sing where other classes get +10%, and DOUBLE range on any spellsong that lists a doubled range for humpbacks."
  - "Speed is the CRUISE, not a sprint: the whale holds 10 to 12 mph for hours, covering 100 to 120 miles a day - up to 150 if pushed to exhaustion, which then halves speed and range for following days until it rests."
  - "Standard equipment: NONE, and money: none. Cetaceans neither need nor want possessions. One may keep a piece of artwork, a magic item or a keepsake - a toy, tool, weapon, article of clothing or photograph - to remember a friend or an occasion by."
  - "Cybernetics: none."
  - "DEHYDRATES OUT OF WATER AND IS ALL BUT IMMOBILE THERE - it can only flop and squirm. It survives about 15 minutes before the skin dries and it weakens, and dies in 30+3D4 minutes. Continuously bathed or sprinkled it lasts 60+6D6 minutes. Kept in a saltwater container with room to swim and fed, it can live indefinitely in theory - though many stop eating in captivity and die after 6D6 days unless they have a reason to live."
natural_abilities:
  - name: "Master of Spellsongs"
    description: "Other than the pneuma-biforms, the humpback is the most powerful of the Whale Singers. It selects four spellsongs at level one, two at level two, and one more every level after."
  - name: "True Song"
    description: "No other whale has the same variety or complexity of sound. A humpback''s songs are true songs - an ordered sequence of themes, motifs and phrases like a bird''s - which can be repeated exactly and taught to others. Clicks, chirps, yups, cries, moans and roars, mostly between 40Hz and 5kHz. One song lasts 6 to 40 minutes and can carry up to 116 miles (185 km), though most sounds reach 50 to 60 miles."
  - name: "Humpback Combat"
    description: "ONE attack per melee round at level one, and one more at levels two, five, eight, eleven and fourteen. Parries with nose or tail at +1. No automatic dodge."
  - name: "Resistant to Cold"
    description: "Cold does half damage."
  - name: "Depth Tolerance"
    description: "Survives the pressure and cold at depth. A dolphin manages a mile (1.6 km); of all the cetaceans only the sperm whale reaches the ocean floor, at two to three miles (3.2 to 4.8 km)."
  - name: "Hold Breath Underwater"
    description: "Most dolphins and porpoises hold their breath 2D4+10 minutes. Large whales of 20 to 40 feet manage 2D6+14 minutes; the Rorqual whales - blue, fin, humpback, minke, sei, Bryde''s - plus grey and sperm whales manage 2D6+24."
  - name: "Sense Magnetic North"
    description: "Unless injured or sick, always knows precisely where magnetic north lies. A powerful blow to the head knocks the ability out for 3D4 minutes."
  - name: "Electromagnetic Sensitivity"
    description: "Senses the electromagnetic activity in a living brain and nervous system like a living E.E.G. - detecting blood clots, tumours, brain or spinal damage, heart problems, paralysis, injury, fatigue and pain, and telling whether a creature is a minor, major or master psychic. It also sees electromagnetic energy directly, following energy trails in the earth like marked roads even in total darkness, and following the trail a ship or submarine leaves for up to twenty minutes after it passes."
  - name: "Sonic Echo-Location"
    description: "Natural sonar. Locates and identifies objects, terrain and creatures underwater without sight."
  - name: "Ultrasonic Probe"
    description: "A focused ultrasonic examination, used among other things to recognise a specific individual."
  - name: "Recognize Family Heritage"
    description: "Recognises relatives and descendants by song, appearance and ultrasonic probe. Base skill 50% +3% per level of experience."
  - name: "Ley Line Charged"
    description: "Absorbs ley line energy until the creature glows blue and becomes TEMPORARILY MEGA-DAMAGE: every available S.D.C. point and hit point converts at two M.D.C. per point. Swimming speed rises 25% and breath capacity 50%. It takes 1D4 melee rounds to charge, lasts while travelling along a ley line and for 3D4 melee rounds after leaving it, and can be done twice an hour. While charged the creature loses one attack per melee, all ultrasonic abilities are cut 40%, and it is +1 to save against all magic with any magic affecting it at half potency. Costs 5 P.P.E."
  - name: "Ley Line Energy Blast"
    description: "Creates and fires mystic energy bolts while on a ley line, at 1000 feet (305 m) plus 400 feet (122 m) per level. Damage is S.D.C. or M.D.C. as desired, regulated in 1D6 increments: 2D6 at levels one and two, and a further 1D6 every two levels after. Costs 1 P.P.E. for an S.D.C. bolt or 5 for M.D.C., whatever the damage."
  - name: "Ley Line Hopping"
    description: "At top speed, creates a small Rift that pops the creature and one passenger from one ley line to a neighbouring one, or between two points on the same line. Takes 1D4 melee rounds to focus; the neighbouring line can be no more than one mile per level away. Costs 10 P.P.E."
  - name: "Ley Line Speed Doubler"
    description: "Doubles natural swimming speed while travelling directly along a ley line, and costs NO P.P.E."
  - name: "Sense Ley Line and Magic Energy"
    description: "The same as the ley line walker''s."
  - name: "Read Ley Lines"
    description: "The same as the ley line walker''s."
  - name: "Ley Line Transmission"
    description: "The same as the ley line walker''s."
  - name: "Ley Line Rejuvenation"
    description: "Doubles the natural healing rate, the same as the ley line walker''s ability."
extraction_notes: |
  - Underseas, printed 90-92. The master of spellsongs: other than the
    pneuma-biforms, the most powerful of the Whale Singers, and the only
    cetacean here whose magic is spellsongs alone.
  - ITS SPELLSONG LADDER IS THE FULLEST IN THE BOOK - four at level one, two
    at level two, and one every level after - which is the same shape the
    Whale Singer O.C.C. uses. That is not a coincidence and it is why this
    class is worth having.
  - EVERY HUMPBACK IS PSIONIC TO SOME DEGREE, which is different from the
    dolphin and orca, where printed 80 and 88 leave 77% with nothing. No
    psionics block is stored either way, because printed 92 still rolls the
    degree on a table rather than granting a set - but the difference is
    recorded, because it is a real one.
  - MEDICAL IS BARRED ENTIRELY, where the other three cetaceans all get Sea
    Holistic Medicine. Transcribed as printed 91 gives it.
  - ITS SING BONUS AND ITS SPELLSONG RANGES ARE BOTH DOUBLED relative to the
    other cetaceans, and several spellsong rows name the humpback explicitly
    in their range lines. Neither is stored on this class: the Sing bonus
    belongs to whichever class grants the skill, and the doubled range lives
    on the spell rows.
  - HIT POINTS AND S.D.C. STORE THE FEMALE/YOUNG FIGURE, as on the other two
    whales.
---

# Humpback Whale

## Lore

There has always been something magical about the humpback whale and its haunting songs. No other whale has the same variety or complexity of sound, and the humpback''s are true songs - an ordered sequence of themes, motifs and phrases like a bird''s, which can be repeated exactly and taught to others.

A single song lasts between six and forty minutes and can be heard up to a hundred and sixteen miles away.

Since the development of Whale Singer spellsongs, the humpback has become one of their masters. Other than the pneuma-biforms, it is the most powerful of the Whale Singers.

## GM Notes

Humpbacks, like all baleen whales, are filter feeders. The whale opens its mouth wide to engulf water full of krill and shrimp, and the baleen plates growing down from the roof of its mouth strain them out as the water passes through.

Every humpback has some degree of psionic power - which is not true of dolphins or killer whales, where most have none at all.

Several spellsongs name the humpback explicitly in their range lines, doubling or in one case multiplying by ten what any other singer gets. A humpback in a party changes what the spellsong list is worth.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'humpback-whale');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'humpback-whale';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-humpback-whale-class.sql');
