-- The Algor R.C.C., Rifts Conversion Book One p.87-88.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-rifts-algor-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'rifts-algor', 'Algor', 'rifts', '---
id: rifts-algor
name: Algor
system: rifts
source_book: Rifts Conversion Book One p.87-88
category: rcc
men_of_arms: false
occ_restrictions:
  except: ["coalition-grunt", "coalition-juicer", "coalition-samas-pilot", "coalition-technical-officer", "cs-commando", "cs-cyborg-strike-trooper", "cs-eod-specialist", "cs-nautical-specialist", "cs-ranger", "cs-rcsg-scientist", "cs-rpa-fly-boy-ace", "cs-special-forces", "psycho-stalker", "dog-boy", "robot-pilot", "glitter-boy", "ngr-power-armor-commando", "ngr-robot-combat-pilot", "fq-descended-glitter-boy-pilot", "fq-glitter-girl-pilot", "fq-side-kick-rpa"]
  note: "Any O.C.C. except the Coalition military and the power armor and robot pilots. Tends toward traditional Men of Arms, Raider, Bounty Hunter, Trapper-Woodsman, Wilderness Scout, Vagabond and similar occupations. The ids name the Coalition O.C.C.s and the pilot O.C.C.s the catalog holds."
attribute_dice:
  IQ: "3d6"
  ME: "2d6"
  MA: "2d6"
  PS: "4d6+6"
  PP: "4d6"
  PE: "4d6+1"
  PB: "3d6"
  Spd: "2d6"
mdc_base: "P.E. attribute number +4d6"
ppe_base: "6d6"
horror_factor: 10
bonuses:
  saves: { horror_factor: 2 }
skills:
  occ_skills:
    - { name: "Language: Troll/Giant", base: 98, per_level: 0, note: "Troll/Giantese at 98%; typically illiterate." }
    - { name: "Language: Gobblely", base: 98, per_level: 0, note: "Gobblely at 98%." }
    - { choose: 1, categories: ["Weapon Proficiencies"], note: "One extra W.P. of choice." }
natural_abilities:
  - name: "Mega-Damage Creature"
    description: "On Rifts Earth an Algor becomes a minor Mega-Damage creature: the P.E. attribute number becomes M.D.C., plus 4D6 M.D.C. Heals 2D6 M.D.C. per 24 hours, and still needs M.D.C. body armor or magic for real protection. No natural A.R. In an S.D.C. setting it is a Hit Point and S.D.C. being instead: Hit Points P.E. attribute number +1D6 per level of experience, S.D.C. 60 plus those from the O.C.C. and physical skills."
  - name: "Bionic Strength"
    description: "On Rifts Earth the Algor''s P.S. counts as Bionic Strength: punches, kicks and head butts can be delivered as Mega-Damage power attacks, which count as two melee actions and typically inflict 1D6 to 2D4 M.D. per power strike. Ordinary damage is 2D4 S.D.C. + P.S. bonus from a punch or head butt, 4D4 S.D.C. + P.S. bonus from a kick."
  - name: "Frost Breath"
    description: "Range 30 feet (9 m), 4D6 M.D. on Rifts Earth (4D6 S.D.C. elsewhere). Usable twice per melee round: the first breath counts as one extra attack, the second as one of the character''s regular melee actions. +1 to strike with frost breath during hand to hand combat."
  - name: "Impervious to Cold"
    description: "No damage from cold, including Mega-Damage and magical cold."
  - name: "Nightvision"
    description: "60 feet (18.3 m); can see in total darkness. Good overall vision and hearing, and superior physical strength and endurance."
restrictions:
  - "Heat and fire based magic does 50% greater damage than usual."
  - "May use Mega-Damage weapons and armor, but avoids bionics."
extraction_notes: |
  - Rifts Conversion Book One printed 87-88 (file p088-p089). No Palladium Fantasy Algor row exists in the catalog on 2026-09-26; the id takes the `rifts-` prefix batch 1 set, because a Palladium Fantasy giant row could later exist and the prefix keeps the pair apart.
  - A MEGA-DAMAGE BEING ON RIFTS EARTH: mdc_base is the page''s "P.E. attribute number turned into M.D.C. plus an additional 4D6 M.D.C.". The S.D.C.-world Hit Points and S.D.C. are a natural ability rather than pools, as on `rifts-troll`, so no sdc pool bonus is stated.
  - Bionic Strength, natural A.R. (none) and the conditional +1 to strike with frost breath are prose; the app has no P.S. class key and a conditional bonus is not a flat one.
  - The frost breath''s extra attack is usable only as a breath, so it is prose and not `combat.attacks`. The page''s Attacks per Melee is "as per O.C.C., Hand to Hand and other physical skills, +1 as a breath attack".
  - Psionics: "Standard, about the same as humans", so no psionics block.
  - occ_restrictions excepts the Coalition O.C.C.s the catalog holds and the power armor and robot pilots (the Robot Pilot, the Glitter Boy, the NGR, Free Quebec and Coalition armor and robot pilots). An O.C.C. of either kind imported after this is allowed until it is added.
  - Height 14-16 feet; weight 600 to 1,500 pounds; life span 300 years. In the Lore.
  - The section-wide rule on printed 74 - a new arrival from the Palladium World picks up the regional language and two Modern W.P.s within weeks, then three Rifts skills from Communications, Pilot (basic vehicles), Technical and W.P. Modern after 2D4+4 months or one level, and one more language or skill every two levels - applies to a character who came from Palladium rather than one raised on Rifts Earth. It is not stored; the survey carries it.
---

# Algor

## Lore

The Algor are the legendary Frost Giants of the Palladium World, a fading race found almost only in the Great Northern Wilderness and the mountains that carry their name. They sided with the Elves in the Elf-Dwarf Wars and were nearly wiped out for it - first used, as they see it, by the Elves, then hunted by the Dwarves in revenge - so they hate Elves above all, Dwarves next, and humans who ally with either. The Wolfen once worshipped them as gods and remain their allies.

On Rifts Earth they turn up now and then in the cool, mountainous parts of North America, and whole clans are said to live in the mountains of Europe, India and China. Fewer than a hundred are believed to be on Rifts Earth.

**Alignment:** Any, but leans toward Unprincipled, Anarchist and Miscreant.

**Appearance:** Pale white or pale blue skin, golden or silver hair, dark eyes.

**Height:** 14 to 16 feet (4.2 to 4.9 m). **Weight:** 600 to 1,500 pounds (270 to 675 kg).

**Average Life Span:** 300 years.

## GM Notes

Algor are a simple wilderness people who prefer a quiet, secluded life, drawn to cold and snowbound places. They are hostile to humans, Elves and Dwarves, dislike Orcs and Goblins, and count Wolfen, Trolls, Jotan and Cyclops as traditional allies. On Rifts Earth they are taken for giant monsters or D-Bees.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'rifts-algor');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'rifts-algor';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-rifts-algor-class.sql');
