-- The Great Horned Dragon R.C.C., dragons-and-gods p.27-30.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-great-horned-dragon-class.sql
--
-- Generated by scripts/class-check.mjs --emit-script from a validated draft.
-- Apostrophes are doubled and non-ASCII is spliced with char(); CR is stripped.
-- Run class-check on THIS file before applying - the ASCII/CRLF pre-flight only
-- fires against the real artifact.


-- The class itself. INSERT ... WHERE NOT EXISTS rather than INSERT OR IGNORE,
-- so re-running the script is a no-op instead of a silent partial write.
INSERT INTO imported_classes (class_id, name, system, markdown, status, created_by)
SELECT 'great-horned-dragon', 'Great Horned Dragon', 'palladium-fantasy', '---
id: great-horned-dragon
name: Great Horned Dragon
system: palladium-fantasy
source_book: dragons-and-gods p.27-30
category: rcc
xp_table: [0, 3001, 5001, 10001, 20001, 30001, 50001, 80001, 120001, 170001, 230001, 300001, 380001, 470001, 600001]
starting_money: 0
equipment_starting: []
variants:
  - id: hatchling
    name: "Great Horned Dragon Hatchling"
    attribute_dice:
      IQ: "5d6"
      ME: "5d6"
      MA: "4d6"
      PS: "6d6"
      PP: "4d6"
      PE: "4d6"
      PB: "5d6"
      Spd: "4d6"
    hit_points_base: "1D4x100+50"
    sdc_base: "1D4x100 plus 4D6 per level of experience"
    ppe_base: "2D6x10 + P.E. attribute number, +10 points per level of experience"
    horror_factor: 12
    bonuses:
      combat: { attacks_base: 4, initiative: 2, strike: 1, parry: 1, dodge: 1, pull_punch: 2, roll: 1 }
      saves: { horror_factor: 4, spell_magic: 1, ritual_magic: 1, psionics: 1, mind_control: 1, possession: 1, illusionary_magic: 1, faerie_magic: 1, curses: 1, insanity: 1, toxins_poisons: 1, harmful_drugs: 1, disease: 1, pain: 1, fatigue: 1 }
  - id: adult
    name: "Adult Great Horned Dragon"
    attribute_dice:
      IQ: "2d6+18"
      ME: "2d6+18"
      MA: "2d6+18"
      PS: "2d6+40"
      PP: "2d6+12"
      PE: "3d6+12"
      PB: "4d6+12"
      Spd: "2d4x10"
    hit_points_base: "1D4x1000+500 + P.E. attribute number"
    sdc_base: "6D6x100"
    ppe_base: "2D6x100+200"
    horror_factor: 18
    skill_overrides:
      - { name: "Lore: Demons & Monsters", base: 98 }
      - { name: "Lore: Faeries & Creatures of Magic", base: 90 }
    bonuses:
      combat: { attacks_base: 8, initiative: 4, strike: 3, parry: 4, dodge: 4, pull_punch: 4, roll: 4 }
      saves: { horror_factor: 8, spell_magic: 4, ritual_magic: 4, psionics: 4, mind_control: 4, possession: 4, illusionary_magic: 4, faerie_magic: 4, curses: 4, insanity: 4, toxins_poisons: 4, harmful_drugs: 4, disease: 4, pain: 4, fatigue: 4 }
skills:
  hand_to_hand: { costs: {} }
  occ_skills:
    - { name: "Mathematics: Basic", base: 98, note: "A hatchling starts its language and math skills at 98%." }
    - { name: "Mathematics: Advanced", base: 98, note: "A hatchling starts its language and math skills at 98%." }
    - { name: "Language: Dragonese", base: 98, note: "Language skills start at 98% for a hatchling." }
    - { name: "Literacy: Dragonese/Elven", base: 98, note: "Language skills start at 98% for a hatchling." }
    - { choose: 4, from: ["Literacy: Other"], bonus: 68, note: "98% (catalog 30% +68). Literate in four other languages of choice. Taken once per language - the picker asks which." }
    - { choose: 10, from: ["Language: Other"], bonus: 48, note: "98% (catalog 50% +48). Speaks the four languages it reads plus six additional languages of choice. Taken once per language - the picker asks which." }
    - { name: "Lore: Demons & Monsters", base: 25, per_level: 5, note: "First level proficiency; the adult has 98%." }
    - { name: "Lore: Faeries & Creatures of Magic", base: 25, per_level: 5, note: "First level proficiency; the adult has 90%." }
    - { name: "Lore: Magic", base: 45, per_level: 5, note: "+20%" }
    - { name: "Gemology", base: 40, per_level: 5, note: "+15%" }
    - { name: "Sing", base: 50, per_level: 5, note: "+15%" }
  occ_related_skills:
    count: 20
    categories:
      - { name: "Communications", bonus: 5 }
      - { name: "Domestic", bonus: 5 }
      - { name: "Espionage", bonus: 5 }
      - { name: "Military", bonus: 5 }
      - { name: "Physical", except_prefix: ["Hand to Hand:"], bonus: 5 }
      - { name: "Rogue", bonus: 5 }
      - { name: "Science", bonus: 5 }
      - { name: "Technical", bonus: 5 }
      - { name: "Wilderness", bonus: 5 }
      - { name: "Weapon Proficiencies", bonus: 5 }
    note: "A total of 20 selections from Communications, Domestic, Espionage, Military, Physical (other than hand to hand combat skills), Rogue, Science, Scholar/Technical, Wilderness and Weapon Proficiencies, each +5%. Include the I.Q. bonus on all skills."
magic:
  type: "spell"
  spell_levels_allowed: [1, 2]
psionics:
  type: "major"
  isp_base: "2d4x10 + M.E. attribute number"
  powers_starting: 12
  powers_starting_groups:
    - { count: 6, categories: ["Sensitive"] }
    - { count: 6, categories: ["Physical"] }
  categories_allowed: ["Sensitive", "Physical"]
  powers_schedule:
    - { level: 4, count: 2 }
    - { level: 8, count: 2 }
natural_abilities:
  - name: "Natural Armor Rating"
    description: "A.R. 11 for a hatchling (15 for an adult)."
  - name: "Horror Factor"
    description: "12 for a hatchling, 18 for an adult."
  - name: "Supernatural Strength"
    description: "Damage varies with supernatural P.S."
  - name: "Flight"
    description: "Flying speed 2D4x10 for a hatchling (running speed is the Spd attribute)."
  - name: "Nightvision"
    description: "100 ft (30.5 m), with excellent color vision."
  - name: "See the Invisible"
    description: "Perceives invisible beings and objects."
  - name: "Turn Invisible at Will"
    description: "Can become invisible whenever it likes."
  - name: "Prehensile Tail"
    description: "The tail can grasp and strike."
  - name: "Bio-Regeneration"
    description: "Recovers 1D4x10 S.D.C. per melee round (1D4x10 per minute for minute)."
  - name: "Resistant to Fire and Cold"
    description: "Takes half damage, including mega-damage magic fire and plasma energy."
  - name: "Metamorphosis"
    description: "At will, 4 hours per level of experience for a hatchling (indefinite for an adult), as the species entry prints it; the general dragon rules (printed 15) say two hours per level for hatchlings, and triple the duration on or near a ley line or nexus."
  - name: "Teleport Self"
    description: "92%. At the hatchling stage a dragon can teleport only itself (printed 12)."
  - name: "Dimensional Teleport"
    description: "52% +4% per level of experience."
  - name: "Dragon Powers"
    description: "All the other dimensional powers, magic and knowledge common to most true dragons, described in the book''s general dragon section."
  - name: "Fire Breath"
    description: "Range 100 feet (30.5 m), six feet (1.8 m) wide, 4D6 S.D.C.; can be used as often as three times per melee round, and the width of the blast can catch several (2-6) opponents huddled close together."
special_abilities:
  - name: "Attacks per Melee"
    description: "Hatchling: Four physical attacks, or two by fire breath and two physical, or two by magic. Adult: eight physical, or three fire breath and five physical, or three by magic."
  - name: "Tail Strike"
    description: "The prehensile tail strikes like a whip for the same damage as a punch +3D6. The dragon may also fight with its fire breath, magic or a weapon."
  - name: "Magic Knowledge of Great Horned Dragon Hatchlings"
    description: "A full understanding of magic, and knows a total of 1D4+2 spells selected from levels 1-2. Additional spells are learned with the same ease and quickness as a first level wizard; by second level the typical hatchling has learned 3D4+2 more from levels 1-4. It can intuitively use all types of magic devices, read magic, use scrolls, and recognize magic circles and enchantments (40% +5% per level of experience). It can cast a maximum of two spells per level of experience."
  - name: "Psionics (Adult)"
    description: "I.S.P. 3D4x10+80 + M.E. attribute number. Considered a master psionic; knows all sensitive, physical and healing psi-powers, plus bio-manipulation and psi-sword."
  - name: "Magic (Adults and NPC hatchlings over 100 years old)"
    description: "Adults of 8th level or higher are likely to know all spell magic of levels 1-6, plus exorcism, resurrection, remove curse and 3D4+2 of choice from levels 7-15; 14th level or higher, all spells of levels 1-12 plus 2D4+4 higher; 20th level or higher, all spells of levels 1-15. There is a 01-70% chance an adult knows one additional area of magic at half its level of experience: 01-35 Summoner, 36-70 Diabolist, 71-80 Necromancer or priest (light or dark), 81-90 Warlock (one element only; leans toward fire or air), 91-00 another magical discipline or a nonmagic scholar, merchant or entertainer O.C.C. from Book 3: High Seas (O.C.C. skills and four other skills of that O.C.C.)."
restrictions:
  - "Optional player character, entirely at the Game Master''s discretion (printed 50)."
  - "Starts with no possessions (printed 50)."
  - "Uses the dragon experience table (printed 17) regardless of skills and interests."
  - "The hatchling''s attributes, hit points and S.D.C. are rerolled completely when the dragon reaches full maturity."
  - "Weakness for magic knowledge, magic weapons and ancient artifacts; a dragon obsessed with acquiring them is distracted and absent-minded (-15% on skill performance) and misses danger, the plight of others and potential enemies."
extraction_notes: |
  - Dragons and Gods printed 27 (heading and introduction), 28 (full-page art, no text),
    29 (stat block through Magic Knowledge), 30 (the rest of Magic Knowledge, Psionics,
    Habitat, Life Span, Enemies and Allies; the Rifts block is omitted as on chiang-ku-dragon).
    Printed 50 makes a hatchling of most species an optional player character, says to start
    with no possessions and to use the dragon experience table. Every number was read off a
    render of printed 29 and 30; the text layer agreed on each.
  - This is the Palladium Fantasy Great Horned Dragon. RUE''s dragon-hatchling ("Dragon
    Hatchling (Great Horned)") is the Rifts printing of the same species in another system,
    with different dice (I.Q. 5D6 alike, but P.E. 5D6 and P.B. 6D6 there, M.D.C. pools); it
    does not cover this one and neither replaces the other.
  - Shape: chiang-ku-dragon''s, which the sibling batch (kukulcan-dragon, lo-dox-dragon,
    night-stalker-dragon) also follows - a hatchling and an adult variant, each carrying
    attribute dice, pools, horror factor and bonuses (attacks_base included). The top-level
    skills, magic and psionics are the hatchling''s, because printed 50 makes only the
    hatchling a player character and a variant cannot override magic or psionics; the
    adult''s psionics and magic are special abilities. The adult variant''s skill_overrides
    restate the percentages the adult prints. starting_money 0 and equipment_starting []
    are printed 50''s "start with no possessions".
  - xp_table: the Dragon Exp. Table, printed 17, read off a render; the same ladder RUE''s
    dragon-hatchling stores. The table runs to level 30; the app stores 15.
  - Attributes (hatchling) as printed; Spd 4D6 is running, flying 2D4x10 is prose.
  - Hit points 1D4x100+50, S.D.C. 1D4x100 plus 4D6 per level, P.P.E. 2D6x10 plus P.E. plus
    10 per level, Horror Factor 12. sdc_base is stated, so no men_of_arms line.
  - Bonuses are in addition to attribute bonuses. "+1 on all other saving throws" is written
    out across the fourteen d20 saves, as on the Gargoyle Lord; coma_death_pct is left out.
  - Attacks: four physical, attacks_base 4. No hand to hand skill is granted, the related
    picks exclude hand to hand combat skills, and no style is sold (costs {}).
  - Skills: "Hatchlings start with the language and math skills at 98% proficiency, and all
    other skills start at first level proficiency." So basic and advanced math, Dragonese
    and every language and literacy are 98%; demon & monster lore (adult 98%) and faerie
    lore (adult 90%) print no bonus and start at catalog base; lore magic +20%, gemology
    +15% and sing +15% are catalog base plus the bonus. Dragonese is granted spoken and
    written; the four literacies are Literacy: Other; the spoken languages are ten
    Language: Other picks, the four it reads plus the six additional (judgement). The 20
    selections are occ_related_skills with the printed +5% on every category; Scholar/
    Technical is Technical.
  - Psionics: major; six powers from EACH of Sensitive and Physical, as two starting groups
    of six (twelve in all); two more at 4th and at 8th level from either. I.S.P. 2D4x10
    plus M.E.
  - Magic: "knows a total of 1D4+2 spells selected from levels 1-2". spells_starting takes
    an integer and the book prints dice, so no starting count is stored - the dice are in
    the Magic Knowledge ability, and spell_levels_allowed [1, 2] carries the level range.
    That is the sibling batch''s convention (the Kukulcan''s 1D4+4 air spells). "By 2nd
    level ... 3D4+2 additional spells from levels 1-4" describes learning, not a grant,
    and is prose. The adult and NPC-hatchling spell lists and the second-discipline table
    are a special ability.
  - Metamorphosis: the species entry prints 4 hours per level for a hatchling, while the
    general dragon rules (printed 15) limit hatchlings to two hours per level. The
    species figure is stored, as the more specific statement; both are prose.
  - The language and literacy picks carry the printed percentage as a bonus over the
    catalog''s Other rows (Language: Other 50%, Literacy: Other 30%), so each pick starts at
    the printed figure and still climbs; regression refuses a language pick frozen by base.
  - The adult: attacks_base on the adult variant from its printed attacks per melee - eight physical, or three fire breath and five physical, or three by magic.
    Its "+N on all other saving throws" is written out the same way.
  - Natural A.R. is prose (no key); horror_factor is stated on each variant.
---

## Lore

The Great Horned Dragon is the most feared and powerful of the known dragons of the Palladium World: a towering winged beast whose head, neck and spine are crowded with horns and spines of every size, the oldest growing them even along the arms of their wings. Skin colors range from light green to golden and orange.

Most adults are masters of the mystic arts, versed in two kinds of magic and given to scholarship when not exploring the Megaverse. They like humans above all other peoples, with Elves a close second, and often walk among them disguised by metamorphosis. Good Great Horned Dragons champion mortal causes against dark priests, evil gods and supernatural monsters (they loathe vampires), and some associate with the Gods of Light; the evil ones are among the most vile monsters in the Megaverse - despots, hidden powers behind thrones, conquerors, and manipulators who hoard wealth and magic.

A hatchling is powerful by human standards but only a fraction of the adult it will become: naive, brash, emotional and curious, roughly the equivalent of a young child in understanding of the world.

**Alignment:** Any, but tends toward principled and other good alignments, or aberrant evil (about 12%).

**Size (adult):** 20 to 30 feet (6 to 9 m) tall, up to 70 feet (21.3 m) long, wingspan 120 feet (36.6 m).

**Weight (adult):** 30 tons.

**Habitat:** Anywhere in the world, though a fondness for humans, Elves and adventure draws them to the more populated regions; a quest for magic or rare artifacts can take them anywhere, including other dimensions.

**Average Life Span:** 6000-8000 years; some have lived over 11,000.

**Enemies:** Supernatural monsters and power hungry forces of evil.

**Allies:** Other dragons with similar goals, spirits of light, and bold adventurers and powerful beings of all kinds; a special fondness for humans and humanoids in general.

## GM Notes

Average equivalent experience level of an adult is 2D4+8. The adult variant carries the adult''s attributes (Spd 2D4x10 running, 2D6x10+100 flying), pools, horror factor and bonuses; its psionics and magic are special abilities. The hatchling''s attributes, hit points and S.D.C. are rerolled completely at maturity.
', 'published', 'data-script'
WHERE NOT EXISTS (SELECT 1 FROM imported_classes WHERE class_id = 'great-horned-dragon');


-- Read the result back rather than trusting the exit code. d1-apply prints
-- these, and a CR in the stored markdown means the checkout mangled the file.
SELECT class_id, name, status, length(markdown) AS bytes, instr(markdown, char(13)) > 0 AS has_cr
  FROM imported_classes WHERE class_id = 'great-horned-dragon';

-- Records this run. REQUIRED: the smoke test fails a data script that has no
-- footer, or whose footer names a different file.
INSERT INTO data_script_runs (filename) VALUES ('add-great-horned-dragon-class.sql');
