-- Equipment from Rifts Ultimate Edition, printed pp.261-270.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local  apps/character-creator/db/add-rue-equipment.sql
--   node scripts/d1-apply.mjs --remote apps/character-creator/db/add-rue-equipment.sql
--
-- Read out of the equipment chapter with the app's own gear importer, in four
-- batches split on the book's own section boundaries so each carried a correct
-- category and none straddled two kinds of thing.
--
-- 109 rows: everything staged that collides with nothing already in the
-- catalog. 27 further rows are deliberately NOT here.
--
-- WHY THE IMPORTER COULD NOT MATCH ANY OF THIS ITSELF. It derives a slug from
-- the book's name, and the book writes "Belt, Ammo (with six pouches; military
-- style)" where a class equipment list produced the stub `ammo-belt`. Inverted
-- word order plus a parenthetical qualifier misses every time, so all 158 rows
-- staged as inserts - including the ones that ARE catalog items - and
-- confirming them wholesale would have duplicated 27 existing rows and none of
-- the 84 stubs would have been filled.
--
-- THE 27 HELD BACK are three different problems wearing one shape, which is why
-- they are a review rather than a rule:
--
--   identical item, identical price   First-Aid Kit 100 = 100, Wastelander
--                                     Motorcycle 18000 = 18000. Nothing to add.
--   the book distinguishes what the   Knife Large vs Knife Small vs the
--   catalog flattened                 catalog's one `knife`; "Dead Boy" CA-1,
--                                     CA-2 and Black Market are three armours.
--   same item, price disagrees        Belt, Utility 3 -> 5; Survival Knife
--                                     120 -> 300. RUE is the later book, so
--                                     that is an update, not a second row.
--
-- INSERT OR IGNORE on a UNIQUE slug: re-running adds nothing and cannot
-- overwrite a row that already exists.

INSERT OR IGNORE INTO gear
  (slug, name, category, weight_lbs, cost, damage, is_mega_damage, range, payload, rate_of_fire, ar, mdc, description, system, source_book)
VALUES
  ('band-aids-box-of-72-various-sizes', 'Band-Aids (box of 72; various sizes)', 'gear', NULL, 5, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('bandages-6-foot-1-8-m-roll', 'Bandages (6 foot/1.8 m roll)', 'gear', NULL, 5, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('bandoleer-with-pouches-and-or-belt-loops', 'Bandoleer (with pouches and or belt loops)', 'gear', NULL, 25, NULL, 0, NULL, NULL, NULL, NULL, NULL, '12-25 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('bicycle-basic', 'Bicycle (basic)', 'gear', NULL, 100, NULL, 0, NULL, NULL, NULL, NULL, NULL, '60-100 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('canteen-aluminum', 'Canteen: Aluminum', 'gear', NULL, 30, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('canteen-plastic', 'Canteen: Plastic', 'gear', NULL, 20, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cigarettes-16-in-a-pack', 'Cigarettes (16 in a pack)', 'gear', NULL, 6, NULL, 0, NULL, NULL, NULL, NULL, NULL, '2-6 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cigarette-lighter-refillable', 'Cigarette Lighter (refillable)', 'gear', NULL, 25, NULL, 0, NULL, NULL, NULL, NULL, NULL, '10-25 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cigarette-lighter-fluid', 'Cigarette Lighter Fluid', 'gear', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '6 credits per 16 ounce can.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cross-crucifix-wood-8-12-inches', 'Cross/Crucifix (wood; 8-12 inches)', 'gear', NULL, 10, NULL, 0, NULL, NULL, NULL, NULL, NULL, '2-10 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cross-crucifix-silver-4-6-inches', 'Cross/Crucifix (silver; 4-6 inches)', 'gear', NULL, 150, NULL, 0, NULL, NULL, NULL, NULL, NULL, '80-150 cr. (double for gold)', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cross-crucifix-silver-8-12-inches', 'Cross/Crucifix (silver; 8-12 inches)', 'gear', NULL, 400, NULL, 0, NULL, NULL, NULL, NULL, NULL, '200-400 cr. (double for gold)', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('disposable-lighter-or-box-of-200-matches', 'Disposable Lighter or Box of 200 matches', 'gear', NULL, 1, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('duffle-bag', 'Duffle Bag', 'gear', NULL, 80, NULL, 0, NULL, NULL, NULL, NULL, NULL, '25-80 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('fishing-line-per-50-feet-15-m', 'Fishing Line, per 50 feet (15 m)', 'gear', NULL, 5, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('flashlight-pen-pocket-size', 'Flashlight, pen/pocket size', 'gear', NULL, 6, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('grappling-hook-and-line-100-feet-30-m', 'Grappling Hook and Line (100 feet/30 m)', 'gear', NULL, 80, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('knife-skinning', 'Knife, Skinning', 'weapon', NULL, 200, '1D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, '80-200 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('knife-survival-commando', 'Knife, Survival Commando', 'weapon', NULL, 500, '2D4 S.D.C. & can saw wood', 0, NULL, NULL, NULL, NULL, NULL, '180-500 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('knife-throwing', 'Knife, Throwing', 'weapon', NULL, 600, '1D6 S.D.C.', 0, NULL, NULL, NULL, NULL, NULL, '200-600 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('knife-silver-plated', 'Knife, Silver Plated', 'weapon', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '+100 credits to normal cost of the weapon.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('machete-with-canvas-sheath', 'Machete with canvas sheath', 'weapon', NULL, 100, '2D4 S.D.C. damage', 0, NULL, NULL, NULL, NULL, NULL, '40-100 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('marker-pen-1', 'Marker Pen (1)', 'gear', NULL, 1, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('marker-pens-dozen', 'Marker Pens (dozen)', 'gear', NULL, 8, NULL, 0, NULL, NULL, NULL, NULL, NULL, '6-8 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('mechanical-pencil-lead-24-in-a-pack', 'Mechanical Pencil lead (24 in a pack)', 'gear', NULL, 10, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('pocket-or-signal-mirror', 'Pocket or Signal Mirror', 'gear', NULL, 5, NULL, 0, NULL, NULL, NULL, NULL, NULL, '2-5 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('rope-per-20-feet-6-m', 'Rope, per 20 feet (6 m)', 'gear', NULL, 15, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('sketch-book-100-sheets-soft-cover', 'Sketch Book (100 sheets, soft-cover)', 'gear', NULL, 4, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('sketch-book-100-sheets-hardcover', 'Sketch Book (100 sheets, hardcover)', 'gear', NULL, 12, NULL, 0, NULL, NULL, NULL, NULL, NULL, '8-12 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('spikes-wooden-stakes-6-wood', 'Spikes/Wooden Stakes (6, wood)', 'gear', NULL, 4, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('sunglasses-or-goggles-cheap', 'Sunglasses or Goggles (cheap)', 'gear', NULL, 50, NULL, 0, NULL, NULL, NULL, NULL, NULL, '15-50 cr.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('communicator-old-style-radio', 'Communicator, Old Style Radio', 'gear', 0.5, 150, NULL, 0, '3 miles (4.8 km)', NULL, NULL, NULL, NULL, 'Basically an enhanced "walkie-talkie," it is a basic instrument issued to all military personnel and field operatives. Was also used by the public in recreation. S.D.C.: 30. Cost: 150 credits per single unit. S.D.C.: 15 each. Excellent availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('communicators-small', 'Communicators: Small', 'gear', 0.3125, 1500, NULL, 0, 'Five miles (8 km)', NULL, NULL, NULL, NULL, 'The size of a pack of cigarettes or cell phone fitted with a handy clip and holster case to hook onto armor, pockets, collars and vests, as well as fit in pockets and belt pouches. S.D.C.: 10. Cost: 1,500 credits (3,500 credits for a communicator with one M.D.C. point). Excellent availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('communicators-medium', 'Communicators: Medium', 'gear', 1, 3000, NULL, 0, '10 miles (16 km)', NULL, NULL, NULL, NULL, 'The size of a 20th Century walkie-talkie. S.D.C.: 30. Cost: 3,000 credits (6,000 credits for a version that has 4 M.D.C.). Excellent availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('communications-helmet', 'Communications Helmet', 'gear', NULL, 5500, NULL, 1, '5 or 10 miles (8 or 16 km)', NULL, NULL, NULL, 30, 'A common protective helmet used by people in all walks of life, from messengers and laborers to adventurers and warriors. Its visor has automatic polarizing optics that adjust to the sun, and it has a radio receiver and transmitter built into it. Miniature headphones pipe the message to both ears and a slide-out microphone allows for two-way communication. M.D.C.: 30 or 50, for the helmet only. Cost: 5,500 or 10,000 credits respectively.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('computer-portable', 'Computer, Portable', 'gear', 1, 100, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'This is a fully functioning computer that is about the size of an opened paperback book or the size of an average human''s hands placed together. When closed, the handle can be folded up and the entire unit can easily fit in most jacket pockets. The computer can be powered by a small, rechargeable battery (about 24 hours of life) or plugged into an electrical outlet. A hard copy of text can be printed out on the thermal-paper printer, but a magnifying glass is needed to read the tiny print. Cost: From 100 credits (palm organizer) to tens of thousands of credits (mega-computer; military application), depending on the performance of the machine and its condition.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('computer-portable-field-unit', 'Computer: Portable Field Unit', 'gear', NULL, 2500, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Somewhat similar to others used across the Megaverse, the hand computer has a pistol grip for easier handling, and has a built-in scanner and laser distancer so it can be used to accurately range and measurements by pointing it at or along something. The standard unit comes with a clock and calendar, as well as a mathematics calculating capability, word processing and other basic programs. It comes with two universal cyberjack plugs and two 10-foot, 3 m cords.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('field-radio', 'Field Radio', 'gear', 16, 600, NULL, 0, '60 miles (96 km) in a city or area with radio clutter and disturbance, but 150 miles (240 km) in the wilderness', NULL, NULL, NULL, NULL, 'An inexpensive backpack style radio transmitter and receiver with wide-band, long-range capabilities, field strength detector and scrambler. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('language-translator-portable', 'Language Translator (Portable)', 'gear', 0.5, 9600, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A unique device that is programmed with the nine known languages of the Americas and can hold three additional languages. 12 others can be added with a supplemental language disc. The amazing device can recognize and monitor up to three different voices and two different languages or dialects. Level of accuracy is 98.7%, with a three second delay when directed at one individual, drops to 78% with a six second delay when translating three speakers simultaneously.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('long-range-military-field-radio', 'Long-Range "Military" Field Radio', 'gear', 25, 6000, NULL, 1, '300 miles (480 km) in a city or area with radio clutter and disturbance, but 500 miles (800 km) in the wilderness', NULL, NULL, NULL, 5, 'A backpack style radio transmitter and receiver with wide-band, long-range capabilities, frequency equalizer, field strength detector and scrambler. M.D.C.: 5 or 15 (the latter costs an extra 10,000 credits). Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('pdd-v-pocket-digital-disc-audio-and-video-player', 'PDD-V Pocket Digital Disc Audio and Video Player', 'gear', NULL, 12000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A slightly larger and more complex system that plays and records audio discs, but also plays video. A four inch, color monitor/TV screen displays the image. The unit can also be used with video equipment as a hand-held video monitor or attached to a larger screen to display its recording. Cost: Varies, usually 6000 to 12,000 credits.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('video-communicator', 'Video Communicator', 'gear', NULL, 10000, NULL, 0, '10 miles (16 km), double in open areas without radio clutter', NULL, NULL, NULL, NULL, 'Part radio and part television. It is a wide wristband or paperback book sized, hand-held device with a small video screen. Communications can be sent and received on either cellular telephone or radio waves. Optional hardline accessories are available at little cost.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('bio-comp-monitor', 'Bio-Comp Monitor', 'gear', NULL, 2500, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A portable computer and sensor system in which a sensor is clipped to the patient''s ears or two fingers to measure and record vital signs: blood pressure, temperature, heartbeat, respiration, level of hydration (or dehydration), and a number of specific chemical responses detectable through the skin. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('compu-drug-dispenser', 'Compu-Drug Dispenser', 'gear', NULL, 3000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A medical tool that is a combination computer, hypodermic gun, and chemical storage and dispensing unit. Can hold 48 different measured shots of drugs. Costs 3000 credits plus each drug dose (average drug dose costs 1D4x100 credits). Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('hypodermic-gun', 'Hypodermic Gun', 'gear', NULL, 200, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A quick, painless method of giving shots. Most hypodermic guns come with a self-cleaning mechanism that instantly cleans and sterilizes the needle after every use (drugs not included). Excellent availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('hypodermic-syringe', 'Hypodermic Syringe', 'gear', NULL, 24, NULL, 0, NULL, NULL, NULL, NULL, NULL, '10 cr. for the reusable type syringe, and 10 cr. for 24 disposable. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('irmss-internal-robot-medical-surgeon-system', 'IRMSS Internal Robot Medical Surgeon System', 'gear', NULL, 42000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An amazing medical device that injects a dozen microscopic robot units, about the size of a pinpoint, into the bloodstream to repair internal injury. The containment unit is placed over or near the suspected area of damage and the depression of a button releases the micro-surgeons into the body. The tiny robots search for the damage and repair it. Types of internal injury which they can repair include the removal of blood clots, repairing torn/ruptured veins, internal bleeding, and minor damage to internal organs. Equal to a medical doctor''s surgical skill of 75%. When the units are done, they simply turn off and are naturally flushed from the body (average life is one hour). They are not reusable. Each IRMSS holds 48 surgical robots for four uses. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('irvt-internal-robot-visual-transmitters-or-seekers', 'IRVT Internal Robot Visual Transmitters or "Seekers"', 'gear', NULL, 80000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'This is another nano-bot about the size of a pinhead. It is injected into the vein of a patient and goes traveling through the circulatory system. It is tracked and monitored via a homing device. The bot transmits a more powerful signal and video image of obstructions and damage to the veins and arteries as they are encountered. The bot is used primarily to locate blocked, pinched and damaged arteries, veins, and other internal passageways. Cost per unit - disposable (less than 33% can be safely retrieved, thus they harmlessly disintegrate inside the body after about 72 hours). Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('rau-robot-antiseptic-units-or-cleaners', 'RAU Robot Antiseptic Units or "Cleaners"', 'gear', NULL, 50000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A cleaner is a tiny robot roughly three inches (76 mm) long and one inch (25 mm) in diameter. They are reminiscent of a mechanical beetle that gently crawls along a wound or infected area destroying infection, removing pus and dead flesh, while cleaning the wound and spraying it with antiseptic protein for faster healing. The cleaners are usually sold and dispatched in pairs. Cost per pair. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('rmk-robot-medical-kit-or-knitter', 'RMK Robot Medical Kit or "Knitter"', 'gear', NULL, 24000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A unique medical kit, developed with the mastery of nano-technology, in which a half dozen tiny robots, about the size of a shirt button, are released and automatically seek out cuts in the skin. One sprays the wound with disinfectant, another sprays antibiotics, a third cuts away dead or infected flesh, while the other three surgically suture the cut closed. When the cut is repaired, the tiny bots return to their carrying unit, refill their supplies and wait till activated again. Equal to a paramedic suturing skill of 90%. Not effective against internal injury, broken bone, or severe wounds. But great for cuts, bruises, bullet and stab wounds. Excellent availability. Hot among adventurers.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('rsu-robot-sedative-units-or-sleepers', 'RSU Robot Sedative Units or "Sleepers"', 'gear', NULL, 100000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Four tiny robots, each the size of a pinhead, enter the brain and stimulate certain areas to make the patient relax and feel drowsy. The calming effect of these nano-bots causes the patient to breathe slow, even breaths, keeps the pulse rate steady and calm, and helps maintain normal blood pressure. When they are done the bots return to a tiny housing device. Cost per set of four. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('suture-gun', 'Suture Gun', 'gear', NULL, 100, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Effectively a staple-like gun that fires staples made of dissolvable sutures. The staples cause little pain or discomfort, leave little scarring and can be used to close a wound at lightning speed. Cost: 100 credits per gun and 10 credits per 5 feet (1.5 m) of suture.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('suture-tape', 'Suture Tape', 'gear', NULL, 20, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A special, antiseptic tape used to hold cuts closed instead of sutures. Cost: 20 credits per 30 foot (9 m) roll. Excellent availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('micro-scale', 'Micro Scale', 'gear', NULL, 120, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A digital pocket scale, about the size of a person''s hand or an old transistor radio. It can be hooked to a belt, slipped into a large pocket, sack, purse or a backpack. The scale can weigh up to 200 lbs (90 kg); digital display. Widely available.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('protein-healing-salve', 'Protein Healing Salve', 'gear', NULL, 100, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'This is a special high protein chemical solution that comes in a tube like toothpaste. The salve can be applied to burns, cuts, and rashes to increase the rate of healing (doubles normal healing). Costs 100 credits per eight ounce (0.23 liter) tube. Widely available.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('palm-bio-unit', 'Palm Bio-Unit', 'gear', NULL, 150, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A palm-size biological analyzer. The digital display can indicate body temperature, blood pressure, respiration, and dehydration level simply by inserting the patient''s finger into the finger scanner housing. Widely available.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('portable-bio-scan-bio-lab', 'Portable Bio-Scan & Bio-Lab', 'gear', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The bio-scan is an impressive biological monitoring device with a multitude of functions. Sensors are attached to the skin and body which send information to the computer display screen and/or to be recorded. Basic bio-mode indicates and records such basic body functions as body temperature, heartbeat rate, blood pressure, breathing, and glandular changes in the skin, including sweating.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('stress-evaluator', 'Stress Evaluator', 'gear', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Operates much like a polygraph machine, recording stress and anxiety (without attaching sensors) by monitoring the voice quality of its subject. A character with sensory equipment and Interrogation skills can use the device as a ''lie detector,'' but the information is often difficult to read and open to interpretation. Even a positive reading can not be declared absolute evidence of a falsehood. Chance of proper reading as a lie detector is 25% plus 5% per level of experience.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('toxic-analyzer', 'Toxic Analyzer', 'gear', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Can analyze any liquid (water, blood, etc.) and be able to identify 380 toxins dangerous to humans. Solid items, such as fruits and vegetables, must be pulped or squeezed in order to be analyzed.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('dosimeter-portable-unit', 'Dosimeter (portable unit)', 'gear', 20, 5000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Used to measure radiation. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('portable-laboratory', 'Portable Laboratory', 'gear', 58, 12000, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An impressive portable unit that can perform several functions: microscope, specimen slides and trays, incubation chamber, burners, instrument tray with tools, refrigeration chamber, insolation chamber, chemical cabinet, centrifuge device, dosimeter, micro-computer, digital camera, and toxic analyzer identical to the one used in the Portable Bio-Scan.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('portable-scan-dihalator', 'Portable Scan Dihalator', 'gear', NULL, 4200, NULL, 0, 'Radar/Sonar: 5 mile (8 km); Radio: 40 mile (64 km); Communicator: 3 miles (4.8 km)', NULL, NULL, NULL, NULL, 'A uniquely comprehensive sensory device with FULL scanning capabilities. Radar/Sonar range limited to 5 mile area. A trained operator (Sensory Equipment skill) can positively identify readings as specific objects or vehicles, pinpoint location, and estimate rate of travel and direction at 65% proficiency. Sensors include dosimeter, radar detector, heat, infrared, ultraviolet, microwave, and energy sensitive instruments; all of which identify, locate source, and record. Long-range, wide-band radio with scrambler. Detachable short-range (hand-held) communicator.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('stethoscope', 'Stethoscope', 'gear', NULL, 80, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('thermometer', 'Thermometer', 'gear', NULL, 3, NULL, 0, NULL, NULL, NULL, NULL, NULL, '3 credits for traditional oral type. 10-15 credits for battery operated digital type that gets temp by placing sensor tip in the car (the size of a small cell phone).', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('conventional-binoculars', 'Conventional Binoculars', 'gear', NULL, 400, NULL, 0, '1 mile (1.6 km)', NULL, NULL, NULL, NULL, 'Magnification through a series of lenses. Fair availability; rather outmoded.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('infrared-optic-system', 'Infrared Optic System', 'gear', NULL, 1000, NULL, 0, '1200 feet (366 m)', NULL, NULL, NULL, NULL, 'Relies on a source of infrared light, usually a pencil thin beam of light projected from the goggles or binoculars to illuminate its targets. The narrowness of the beam severely limits the scope of one''s view to a small area of about two square meters (21.5 sq. feet). This can make surveying a large area a problem. Another drawback is that the infrared light beam is clearly visible to another infrared optic system, giving away the operator''s position. These drawbacks are inherent to ALL infrared systems. Fair to good availability; rather outdated.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('multi-optics-helmet-m-o-h', 'Multi-Optics Helmet (M.O.H.)', 'gear', NULL, 2800, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A special multi-optics helmet is a special optical enhancement system built into a protective helmet. Includes: Targeting Sight range 1,600 feet; Infrared Optics System range 1,600 feet; Telescopic Monocular Lens range 2 miles; Thermal-Imager range 1600 feet. Special Bonus: +1 to strike when the optics and targeting sight are engaged. Note that the thermal-imager is a special, optical, heat sensory unit that allows the infrared radiation of warm objects to be converted into a visible image. Enables the pilot to see in darkness, shadows and through smoke.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('night-sight-passive', 'Night Sight (Passive)', 'gear', NULL, 1400, NULL, 0, '1600 feet (488 m)', NULL, NULL, NULL, NULL, 'A nightvision optics system that is an image intensifier, meaning that it is a passive system that does not emit any light of its own, but electronically amplifies existing ambient light to provide a visible picture. Good to excellent availability, especially at tech centers.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('optics-band', 'Optics Band', 'gear', NULL, 800, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A headband type optical system most often used in research, micro-repairs and scientific study. Its range is limited as it is designed for close work, not long-distance or combat surveillance. Features include: Infrared and Ultraviolet Optic System range 200 feet maximum; Magnification Lens (400x) range 7 feet; Night Sight range 200 feet; Adjustable Color Filters. Fair to good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('pocket-night-viewer', 'Pocket Night Viewer', 'gear', NULL, 800, NULL, 0, '800 feet (244 m)', NULL, NULL, NULL, NULL, 'A mini-night sight, usually a monocular style, easily concealed and portable. Fair availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('polarized-goggles', 'Polarized Goggles', 'gear', NULL, 1200, NULL, 1, NULL, NULL, NULL, NULL, 1, 'Light sensitive to automatically lighten and darken depending on the ambient light to protect the eyes from glare and bright light. High impact goggles have 1 M.D.C. Ordinary Polarized Goggles are 15 S.D.C.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('sunglasses-or-tinted-visor', 'Sunglasses or Tinted Visor', 'gear', NULL, 15, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Similar to Polarized Goggles (8 S.D.C.): 15 to 300 credits depending on the style and quality.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('thermal-imager-goggles', 'Thermal-Imager (goggles)', 'gear', NULL, 2000, NULL, 0, '1600 feet (488 m)', NULL, NULL, NULL, NULL, 'Basically an optical heat sensor, it converts the infrared radiation of warm objects into a visible image. This device allows its operator to see in darkness, shadows and through smoke. Battery powered and electrically cooled. A typical running life is 16 hours. Poor availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('ultraviolet-systems', 'Ultraviolet Systems', 'gear', NULL, 500, NULL, 0, '400 feet (122 m)', NULL, NULL, NULL, NULL, 'Enables its wearer to see into the ultraviolet range of light radiation. It''s usually integrated into a larger optics package rather than used alone.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('telescopic-scope', 'Telescopic Scope', 'gear', NULL, 1000, NULL, 0, NULL, NULL, NULL, NULL, NULL, '10x magnification ' || char(8211) || ' works like a pair of binoculars or camera lens. Typical range is 2000-6000 feet (610 to 1828 m).', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('cross-hair-sight', 'Cross-Hair Sight', 'gear', NULL, 500, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Targeting cross-hairs for better aim. When the cross-hairs are centered over the desired subject the aim is on target. Bonus: Add +1 to strike but only on aimed shots. This bonus is not applicable when laser targeting is engaged.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('infrared-scope', 'Infrared Scope', 'gear', NULL, 1000, NULL, 0, 'Maximum Range: 2000 feet (610 m)', NULL, NULL, NULL, NULL, 'Ancient technology and inferior to other passive optical enhancements. However, it is inexpensive and therefore popular among City Rats, bandits and adventurers down on their luck. The scope emits a narrow beam of infrared light that is invisible to human eyes. However, the light beam is visible to other characters using infrared vision, including most ''bots, power armor and a number of D-Bees. Those who can see the light can avoid it and/or follow it to its source, giving up its user''s location. Furthermore, the narrowness of the light beam limits the available viewing area to about seven feet (2.1 m).', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('laser-targeting', 'Laser Targeting', 'gear', NULL, 2000, NULL, 0, '4000 feet (1219 m)', NULL, NULL, NULL, NULL, 'Add +3 to strike on an aimed shot, but only when the laser targeting system is functioning. No bonus if the system is broken or turned off. Note: Laser targeting can be used in conjunction with a telescopic sight and/or thermal-imager.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('light-filters', 'Light Filters', 'gear', NULL, 25, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Simple transparent lens covers designed to filter sunlight and reduce glare.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('passive-nightvision', 'Passive Nightvision', 'gear', NULL, 6000, NULL, 0, '2000 feet (610 m)', NULL, NULL, NULL, NULL, 'This system amplifies existing ambient light to provide vision in darkness. It is also known as a ''starlight'' scope because it can amplify the light from stars and the moon to see when outdoors. If in absolute darkness, such as an underground tunnel, it is rendered useless - it must have some source of ambient light.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('thermal-imager-as-goggles', 'Thermal-Imager (as goggles)', 'gear', NULL, 12000, NULL, 0, '2000 feet (610 m)', NULL, NULL, NULL, NULL, 'A thermal-imaging system as goggles has a range equal to normal human sight and does not automatically come with a telescopic feature. However, it can be combined with a telescopic sight. A thermal-imager converts infrared radiation of warm objects into a visible image. The operator can see heat as represented by bands of color and is able to see in darkness, shadows and through smoke with 20/20 vision. Note: Can be added to a telescopic gun or camera scope (add the cost of the telescopic feature to the total cost).', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('dosimeter-sensor-equipment', 'Dosimeter (sensor equipment)', 'gear', 1, 200, NULL, 0, '20 feet (6.1 m)', NULL, NULL, NULL, NULL, 'Picks up and measures radiation levels. Hand-held. Wide availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('heat-sensor', 'Heat Sensor', 'gear', 8, 1200, NULL, 0, '250 feet (76.2 m); field of detection is 25 feet (7.6 m)', NULL, NULL, NULL, NULL, 'Special sensors pick up and measure heat emanations. Can monitor temperature, or made directional to pinpoint a specific heat point/target. Portable/hand-held.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('microwave-fence', 'Microwave Fence', 'gear', NULL, 20000, NULL, 0, 'Between transmitter posts is 500 feet (152 m); posts are 7 feet (2.1 m) high; can effectively cover a 14 mile (22.4 km) area', NULL, NULL, NULL, NULL, 'Transmitter and receiver sensor posts emit an invisible, microwave curtain or fence that will light up and send a signal to the control unit when an intruder breaches its curtain. Poor availability; primarily used for military purposes.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('motion-detection', 'Motion Detection', 'gear', 15, 400, NULL, 0, '60 feet (18.3 m)', NULL, NULL, NULL, NULL, 'Detects movement by measuring minute changes in the air and pinpoints location of the source of the changes in the air. Requires sensor placement and monitor screen. Portable. Fair availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('radar-detector-portable', 'Radar Detector (portable)', 'gear', NULL, 200, NULL, 0, 'Range of Detection: One mile (1.6 km)', NULL, NULL, NULL, NULL, 'Indicates the use/presence of radar in the area. Fair availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('radar-mini', 'Radar, Mini', 'gear', 18, 2500, NULL, 0, '5 miles (8 km)', NULL, NULL, NULL, NULL, 'A portable, mini-radar unit and monitor. Trained operators (Sensory Equipment skill) can positively identify readings/objects, pinpoint location and estimate rate of travel and direction. Can track up to 72 images simultaneously and identify over 500 targets. Can NOT track targets on ground level or flying under 200 feet (61 m) above the ground.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('radar-military-unit-large', 'Radar, Military Unit (large)', 'gear', 300, 16000, NULL, 0, '100 miles (160 km); double in wide open flat lands', NULL, NULL, NULL, NULL, 'Semi-portable, in that it can be pulled along on a trailer hitch or carried by a small truck or van. About the size of a desk. Trained operators (Sensory Equipment skill) can positively identify readings/objects, pinpoint location and estimate rate of travel and direction. Can track up to 300 targets simultaneously and identify over 1000 targets. Can NOT track targets on ground level or flying under 100 feet (30.5 m) above the ground.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('acoustic-noise-generator', 'Acoustic Noise Generator', 'gear', NULL, 900, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Muffles conversations, distorts bugging systems by 35%.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('keyhole-or-tube-microphones', 'Keyhole or Tube Microphones', 'gear', NULL, 150, NULL, 0, 'Picks up sounds up to 34 feet (10.3 m) away and transmits up to 1000 feet (305 m)', NULL, NULL, NULL, NULL, 'A microphone with a long, hollow tube which can be flexible or rigid, allowing it to be placed in cracks, mounted in walls or placed in similar, small, ''keyhole'' type crevices. Fair availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('video-wall-mount', 'Video Wall Mount', 'gear', NULL, 200, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'This small, remote video camera is only about the size of a man''s palm (5 inches/127 cm in diameter), thus it is easily concealed. The camera is backed with a powerful suction device that will adhere to any smooth surface, whether it be a wall, table, appliance, vehicle and so on. The video wall mount can broadcast continually for 72 hours, or by remote or preprogrammed, regulated intervals. The lens has limited mobility, able to rotate in about a 90 degree radius. Its audio capacity has twice the duration of its video transmission and is able to pick up sounds up to twenty feet (6.1 m) away with crystal clarity. The monitor can be the mini-handheld screen or any variety of larger or multi-unit monitors. Fair availability through the conventional market, but a hot commodity at 300 credits on the Black Market. Handheld monitor costs 150 credits.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('contact-microphone', 'Contact Microphone', 'gear', NULL, 170, NULL, 0, 'Picks up sounds up to 10 yards/meters away, and transmits up to 1000 feet (300 m)', NULL, NULL, NULL, NULL, 'Translates vibrations into sound, but requires a sounding board such as a wall, window, large object, etc. Can be as small as a tie tack.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('wireless-microphone', 'Wireless Microphone', 'gear', NULL, 250, NULL, 0, 'Can pick up sounds up to 14 feet (4.3 m) away and broadcast up to 300 feet (91 m) away', NULL, NULL, NULL, NULL, 'This compact microphone is about the size and thickness of a box of matches. Poor availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('tracer-bug', 'Tracer Bug', 'gear', NULL, 140, NULL, 0, 'Can be followed up to 8 miles (12.8 km) away', NULL, NULL, NULL, NULL, 'A tiny device about the size of a checker which has a sticky or magnetic side that can be attached to a vehicle or slipped into a person''s pocket, backpack, briefcase, etc. Battery powered, it has a limited life of 72 hours of constant transmission. Fair availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('pocket-scrambler', 'Pocket Scrambler', 'gear', NULL, 300, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The scrambler will distort or ''scramble'' outgoing radio signals, preventing interception and interpretation by the enemy. Good availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('ultraviolet-signaler', 'Ultraviolet Signaler', 'gear', NULL, 900, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The signaler is a small strip of ultraviolet sensors and another transmitter strip that can be adhered to a doorway, walls and so on, to create a beam of invisible light blocking that area. When the beam is broken by an intruder or vehicle, etc., it will send a silent signal to a monitoring device and/or trigger a video unit. Fair availability.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('video-camera-digital-mini', 'Video Camera, Digital (mini)', 'gear', NULL, 4200, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An advanced, studio quality camera about the size of a paperback novel or cell phone. Has both wide and narrow angle lenses. Records sound and image, low light capabilities (two candle light), records on one or three inch (2.5 to 7.6 cm) discs by digital meter; lens filters, telescopic lens (488 mm), carrying case and tripod included. Capable of radio telemetry when boosted by long-range radio. Half that for a traditional video camera. Good availability for both.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('speedster-hovercycle', 'Speedster Hovercycle', 'vehicle', NULL, 98000, '1D6 M.D. (laser) or 1D4 M.D. per burst (machine-gun)', 1, '1200 feet (366 m) laser / 2000 feet (610 m) machine-gun', '20 shots (laser) or 600 rounds/12 bursts (machine-gun)', NULL, NULL, 85, 'A fast all-terrain hover vehicle common throughout the land. Crew: One rider; one passenger is possible, but not comfortable on long trips. Weapons: Laser 1D6 M.D., range 1200 feet (366 m), payload is 20 shots. Or machine-gun: 1D4 M.D. per burst of 50 rounds, range 2000 feet (610 m), payload 600 rounds (12 bursts). Mini-missile launchers can be added to the sides. The small launchers fire two mini-missiles each and cost 55,000 credits for the pair.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('big-boss-atv', 'Big Boss ATV', 'vehicle', NULL, 24000, NULL, 0, NULL, NULL, NULL, NULL, 100, 'A popular all-terrain vehicle with good speed and good fuel milage. Vehicle Type: ATV Dune Buggy Type. Crew: One pilot and can accommodate three passengers comfortably.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('mountaineer-atv', 'Mountaineer ATV', 'vehicle', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An extremely popular armored, all-terrain vehicle. It has a pilot''s compartment that can seat five and a large, enclosed cargo bay (10x8x8 foot/3x2.4x2.4 m cargo area). Weapons: Often comes with a sunroof and standard laser rifle attached to the roof; 360 degree rotation and 90 degree arc of fire. Add cost of rifle to vehicle.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('wilk-s-atv-transport-vehicle', 'Wilk''s ATV Transport Vehicle', 'vehicle', NULL, 76000, NULL, 0, NULL, NULL, NULL, NULL, 210, 'Three wheeled armored ATV transport vehicle. Crew: One pilot and can accommodate four passengers comfortably, plus cargo area. Maximum Speed: 120 mph (192 km). Engine: Combustion or electric engine or nuclear. Maximum Range: 600 miles (960 km), has an extra large tank or batteries. Size: 25 feet (7.6 m) long, 18 feet (5.4 m) tall, 6 tons. M.D.C. by Location: Main Body: 210, Super Tires (4): 25 each, Reinforced Pilot''s Compartment: 50. Black Market Cost for basic vehicle (gasoline engine). Other features such as radar, radio, rail gun, etc. cost separately. 70,000 credits for electric engine and 500,000 for nuclear with a 20 year life. Additional armor can also be added at a cost of 10,000 credits per 30 M.D.C. Weapons: None are standard.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('gladiator-full-environmental-body-armor', 'Gladiator - Full Environmental Body Armor', 'armor', 21, 38000, NULL, 0, NULL, NULL, NULL, NULL, 70, 'One of the most popular medium-weight full environmental suits on the market. The body utilizes a new super lightweight fiber armor that resembles chain mail and light plates of armor. The suit offers excellent mobility and equally excellent physical protection. The fiber skirt is standard for both the male and female suit and offers one of the best forms of protection to the groin area. Comes in white, tan, silver, light grey, dark grey, and black. M.D.C. by Location: Main body: 70, Helmet: 45, Arms: 25 each, and Legs: 45 each. Fair mobility, -10% movement penalty.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('crusader-full-environmental-body-armor', 'Crusader - Full Environmental Body Armor', 'armor', 24, 55000, NULL, 0, NULL, NULL, NULL, NULL, 95, 'As the name implies, this full suit of body armor resembles the knights of the ancient Crusades, because of the styling of the armor plates and use of chain mail-like M.D.C. materials and knee length skirt. Recent fashion has provided a traditional knight''s surcoat and even the helmet is often designed to resemble the European knights of old. M.D.C. by Location: Main body: 95, Helmet: 50, Arms: 30 each, and Legs: 50 each. Fair mobility, -15% movement penalty.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('juicer-assassin-plate-armor-non-environmental', 'Juicer - Assassin Plate Armor (non-environmental)', 'armor', 14, 28000, NULL, 0, NULL, NULL, NULL, NULL, 45, 'This is the famous, traditional medium-weight armor worn by the chemically augmented Juicer. M.D.C. by Location: Main body: 45 (60 for heavier versions), Helmet: 30 (or 50), Arms: 12 (or 20) each, and Legs: 24 (or 35) each. Weight: 14 lbs (6.3 kg or 18 lbs/8 kg for heavy); good mobility (for Juicer), -5% movement penalty (-10% for anyone NOT a Juicer or Crazy). Black Market Cost: 28,000 credits for the medium-weight and 32,000 credits for the heavier model.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('urban-warrior-padded-environmental-body-armor', 'Urban Warrior - Padded Environmental Body Armor', 'armor', 11, 35000, NULL, 0, NULL, NULL, NULL, NULL, 50, 'A lightweight body armor that has been popular with adventurers and many city law enforcement officers for over a decade. This armor is a full body suit with special flexible padding and strategic placement of light metal plates. Usually comes in white, light grey, light green, and tan colors. M.D.C. by Location: Main body: 50, Helmet: 35, Arms: 16 each, and Legs: 30 each. Excellent mobility, -5% movement penalty.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('plastic-man-full-environmental-body-armor', 'Plastic-Man - Full Environmental Body Armor', 'armor', 13, 18000, NULL, 0, NULL, NULL, NULL, NULL, 35, 'An inexpensive armor made of lightweight M.D.C. polycarbonate plate. M.D.C. by Location: Main body: 35, Helmet: 30, Arms: 15 each, and Legs: 22 each. Fair mobility, -10% movement penalty.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('huntsman-plate-padded-armor-non-environmental', 'Huntsman - Plate & Padded Armor (non-environmental)', 'armor', 16, 24000, NULL, 0, NULL, NULL, NULL, NULL, 45, 'A lightweight body with a heavy plate and padded vest and padded armor with leg and arm plates. Much more macho and stylish than the Plastic-Man armor. M.D.C. by Location: Main body: 45, Helmet: 35, Arms: 15 each, and Legs: 25 each. Fair mobility, -10% movement penalty.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('bushman-full-composite-environmental-body-armor', 'Bushman - Full Composite Environmental Body Armor', 'armor', 17, 32000, NULL, 0, NULL, NULL, NULL, NULL, 60, 'A lightweight padding, Kevlar, and plate composite armor. Comes in green, tan, white, black, grey and camouflage. M.D.C. by Location: Main body: 60, Helmet: 50, Arms: 30 each, and Legs: 55 each. Fair mobility, -10% movement penalty.', 'rifts', 'Rifts Ultimate Edition p.261-270'),
  ('bushman-trooper', 'Bushman Trooper', 'armor', NULL, 46000, NULL, 0, NULL, NULL, NULL, NULL, 90, 'Also available is the Bushman Trooper. The only differences being it is a bit bulkier, has a main body of 90 M.D.C. (All other armor location are same as above), has -15% movement penalty and costs 46,000 credits.', 'rifts', 'Rifts Ultimate Edition p.261-270');

-- Read the result back rather than trusting the exit code.
SELECT count(*) AS rue_equipment FROM gear WHERE source_book = 'Rifts Ultimate Edition p.261-270';
SELECT count(*) AS gear_total FROM gear;

INSERT INTO data_script_runs (filename) VALUES ('add-rue-equipment.sql');
