-- Federation of Magic Techno-Wizard devices and weapons. Printed 112-120.
-- Twenty-five new gear rows: survey PR B (docs/surveys/fom.md).
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-fom-tw-gear.sql
--
-- ALL 25 ARE NEW - catalog-diff --table gear --remote, 2026-09-26: missing 25,
-- matched 0 against 3144 rows, and none of the 25 slugs exists. Every nearest
-- candidate was checked and is a different item: the Underseas "Sonic Rifle
-- (TW)" is not this book''s TW Sonic Rifle, the Manoan TW Energy Cell is South
-- America''s, and the Madhaven TW Storm Lance is not the TW Storm Rifle.
--
-- PRINTED 117 IS GLYPH-CORRUPT (cache p118, `corrupt_pages`) AND CARRIES FOUR
-- PRICES - the Dragonfire Flamethrower''s 150,000, the two grenades'' 25,000
-- each and the Shockstorm Landmine''s 100,000 (20,000 to recharge). All four
-- were read off a RENDER, which is legible: an encoding fault, not damaged ink.
-- The TW Disrupter''s effect duration was read off a render of printed 114 as
-- well: the text layer reads 204 where the ink prints 2D4. Printed 114-116 are
-- also interleaved in the text layer (the Nova Rifle''s stat lines follow the
-- Disrupter''s), so every stat line was attributed off the renders.
--
-- CATEGORY follows what the catalog already does with Techno-Wizard kit:
--   * guns, grenades, the mine and the enchanted melee weapons are 'weapon',
--     as tw-flaming-sword (RUE), the Madhaven TW blades and the New West TW
--     guns are.
--   * the P.P.E. energy cell is 'magic', as its nearest analogue, the Manoan
--     TW Energy Cell, is.
--   * the Shadow Cloak is 'gear': it does no damage, the book says it is not
--     armour, and the catalog files non-weapon TW devices (the TW Silencer,
--     the Psyscape and Madhaven devices) as gear.
--
-- SLUGS carry a tw- prefix on the thirteen items the book does not name "TW"
-- (Firebomb, Firestaff, Shadow Cloak ...), so a generic name from another book
-- can never collide with them. The energy cell is stormspire-ppe-energy-cell,
-- because the book presents it as Stormspire''s house clip.
--
-- THE CLIP IS BOTH A ROW AND A NOTE. Almost every weapon prints its own price
-- and "40,000 credits per clip"; that second figure is in each weapon''s
-- cost_note, and the clip itself is the stormspire-ppe-energy-cell row, whose
-- cost_note carries the 12,000-credit recharge price.
--
-- is_mega_damage IS 0 on five rows that do no mega-damage: the energy cell,
-- the TW Jammer (jams machines, harmless to people), the TW Disrupter (Energy
-- Disruption on equipment, harmless to the living), the Flash Freeze Grenade
-- (encases in ice, no damage) and the Whip of Pain (3D4 S.D.C. plus Agony).
-- The Shadow Cloak is the sixth 0, having no damage at all.
--
-- A PRICE RANGE STORES ITS LOW END in cost with the range in cost_note, per
-- the gear convention: the Scepter of Command (700,000 to one million), the
-- Firestaff and Draining Blade (2-3 million), the Paralysis Staff
-- (500,000-600,000), the Deathbringer (11-14 million; 10 million for the
-- weaker 5D6 version), the Battle Fury Blade (12-15 million) and the Shadow
-- Cloak (200,000-300,000). mdc holds the object''s own printed M.D.C. where
-- the book gives one (the staves, swords, scepter, cloak and the mine).
--
-- The Starfire Pulse Cannon mounts only on vehicles and robots, but it is here
-- and not in survey PR C: the book prices and describes it as a stand-alone
-- weapon, and PR C''s add-ons are the Zone Ranger''s priced options.
--
-- CREATION STATS (spells and P.P.E. to build) are in the description, as the
-- New West TW rows do it - the gear table has no column for them.
--
-- Rows were checked field by field against the page renders by a
-- book-reconcile pass before this script was generated.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('stormspire-ppe-energy-cell', 'Stormspire P.P.E. Energy Cell', 'rifts', 'magic', NULL, 40000, '40,000 credits each (Black Market). Recharging a spent cell in Stormspire costs 12,000 credits, sometimes as low as 10,000 during sales and promotions.', NULL, 0, NULL, 'Stores the P.P.E. for a set number of shots; the number depends on the weapon it is loaded into (see each Stormspire TW weapon).', NULL, NULL, NULL, NULL, 'The P.P.E. "energy cell" most Stormspire Techno-Wizard firearms need: essentially a limited energy-storage talisman built to look like an ordinary E-clip apart from a few magic symbols. The cells are uniform, so one clip fits any Stormspire TW weapon, and Stormspire and the Black Market are the only sources. Any mage who knows how to make talismans can recharge one. A Techno-Wizard can instead pump his own P.P.E. into a weapon, with or without a clip, at roughly 10 P.P.E. per blast for most pistols and 20 per blast for most rifles.', 'Rifts World Book 16: Federation of Magic p.112'),
('tw-firebolt-pistol', 'TW Firebolt Pistol', 'rifts', 'weapon', 3, 80000, '80,000 credits for the pistol (Black Market); 40,000 credits for each P.P.E. clip.', '4D6 M.D. per blast of magic fire', 1, '450 feet (137 m)', '10 shots per P.P.E. clip.', 'Single shots only', NULL, NULL, NULL, 'A medium-sized, durable Stormspire pistol that fires bolts of magical flame. Favoured by mercenaries and assassins for packing a rifle-like punch in a pistol; its weakness is a range well short of most high-tech pistols.', 'Rifts World Book 16: Federation of Magic p.113'),
('tw-jammer', 'TW Jammer', 'rifts', 'weapon', 1.2, 75000, '75,000 credits for the pistol (Black Market); 40,000 credits for each P.P.E. clip.', 'None to living beings. Jams or stalls a key mechanical function of the machine or weapon hit, the same basic effect as a 3rd level Negate Mechanics spell.', 0, '600 feet (183 m)', '10 shots per P.P.E. clip.', 'Single shots only', NULL, NULL, NULL, 'A light pistol whose only purpose is to take out other weapons: its pulse of magic energy temporarily negates a key mechanical function, so the target weapon will not shoot. Harmless to humans. Shooting at a machine smaller than man-sized requires a called shot; otherwise the shooter fires without any bonuses.', 'Rifts World Book 16: Federation of Magic p.113'),
('tw-shard-pistol', 'TW Shard Pistol', 'rifts', 'weapon', 2.5, 72000, '72,000 credits for the pistol (Black Market); 40,000 credits per P.P.E. clip.', '3D4 M.D. per shot (multiple shards); 4D6 M.D. per short burst', 1, '700 feet (210 m)', '12 shots per P.P.E. clip.', 'Single shots or short bursts only', NULL, NULL, NULL, 'An automatic pistol firing clusters of high-velocity ice fragments, much like a small rail gun, with a large, heavily reinforced barrel. A favoured tool of assassins because the shards melt away and leave no evidence of the weapon used.', 'Rifts World Book 16: Federation of Magic p.113'),
('tw-starfire-pistol', 'TW Starfire Pistol', 'rifts', 'weapon', 2, 80000, '80,000 credits for the pistol (Black Market); 40,000 credits per P.P.E. clip.', '3D6 M.D. per blue-white energy bolt', 1, '1000 feet (305 m)', '12 shots per P.P.E. clip.', 'Single shots only', NULL, NULL, NULL, 'A sleek, elegant pistol designed to appeal to the wealthy, which caught on with warriors for its range, accuracy, damage and ergonomic design. BONUS: +1 to strike. Its drawback is the price.', 'Rifts World Book 16: Federation of Magic p.113'),
('tw-shock-pistol', 'TW Shock Pistol', 'rifts', 'weapon', 2, 52000, '52,000 credits for the pistol (Black Market); 40,000 credits per P.P.E. clip.', '2D6 M.D. per blast of electricity', 1, '330 feet (100.5 m)', '10 shots per clip.', 'Single shots only', NULL, NULL, NULL, 'Fires blasts of electricity. Short range and minimal damage, but comparatively cheap; it is Stormspire''s stock weapon, made in greater numbers than any other pistol, and popular with adventurers and mercenaries because it is small and easy to conceal.', 'Rifts World Book 16: Federation of Magic p.113-114'),
('tw-nova-rifle', 'TW Nova Rifle', 'rifts', 'weapon', 10, 130000, '130,000 credits for the rifle (Black Market); 40,000 credits for each P.P.E. clip.', '1D4x10 M.D. to all targets in a 6 foot (1.8 m) radius', 1, '1200 feet (366 m)', '8 shots per P.P.E. clip.', 'Single shots only', NULL, NULL, NULL, 'A large, bulky rifle firing globes of red swirling energy that explode on impact, damaging a small area and so able to hit several targets at once. Not automatic. Used most by the mercenaries guarding Stormspire, where each squad carries one as fire support and mobile artillery.', 'Rifts World Book 16: Federation of Magic p.114'),
('tw-disrupter', 'TW Disrupter', 'rifts', 'weapon', 8, 150000, '150,000 credits for the rifle (Black Market); 40,000 credits per P.P.E. clip.', 'None to living creatures. Same effect as the Energy Disruption spell (Rifts RPG p.174) on high-tech equipment; the effect lasts 2D4 minutes.', 0, '500 feet (152 m)', '5 shots per P.P.E. clip.', 'Single shots only', NULL, NULL, NULL, 'A strange-looking rifle, very short and broad, firing spheres of crackling energy that are harmless to living creatures but wreak havoc on high-tech equipment. Limited range and ammunition. THE DURATION WAS READ OFF A RENDER of printed 114: the text layer reads 204 where the ink prints 2D4.', 'Rifts World Book 16: Federation of Magic p.114'),
('tw-fireburst-rifle', 'TW Fireburst Rifle', 'rifts', 'weapon', 10, 125000, '125,000 credits for the rifle (Black Market); 40,000 credits for each clip.', '3D6+6 M.D. per single shot; short burst x2, long burst x3; a spray does 3D6+6 M.D. to each of 1D6 targets', 1, '1200 feet (366 m)', '20 single shots per clip, and it holds two clips at a time (40 shots).', 'Standard, capable of bursts (no full melee burst) and sprays. A short burst uses three rounds, a long burst five, a spray ten.', NULL, NULL, NULL, 'A rifle built for an extremely high rate of fire, obvious from its two separate P.P.E. clips. It shoots mini-fireballs in clusters of three and is intended for anti-infantry work: the only TW weapon capable of long bursts and sprays. Because TW weapons generate spells there is no recoil, so an unskilled user rolls a straight die for a burst instead of taking the usual -6.', 'Rifts World Book 16: Federation of Magic p.115'),
('tw-force-cannon', 'TW Force Cannon', 'rifts', 'weapon', 42, 300000, '300,000 credits for the rifle (Black Market); 40,000 credits per P.P.E. clip.', '1D6x10+10 M.D. per shot (three force bolts)', 1, '2000 feet (610 m)', '6 shots per P.P.E. clip.', 'Single shots only', NULL, NULL, NULL, 'The largest man-portable weapon Stormspire produces, with a curved, shell-like organic look and three holes in its thick barrel; rumour says it was stolen from the Xiticix and modified, though it is larger and more powerful than any Xiticix force rifle seen. Each trigger pull unleashes three force bolts. Dragon Juicers and borgs especially love it. CHARACTERS WITHOUT A P.S. OF 22 OR GREATER ARE -2 TO STRIKE.', 'Rifts World Book 16: Federation of Magic p.115'),
('tw-storm-rifle', 'TW Storm Rifle', 'rifts', 'weapon', 8, 280000, '280,000 credits for the rifle (Black Market); 40,000 credits per P.P.E. clip.', 'Lightning: 5D6 M.D. per blast; or Wind Rush equal to a 3rd level strength spell', 1, 'Lightning 2000 feet (620 m as printed); Wind Rush 1000 feet (305 m)', '6 shots per P.P.E. clip.', 'Single shots', NULL, NULL, NULL, 'The most common of the TW rifles: solid, dependable, without huge upkeep, with decent range and firepower. It fires either magical lightning or a Wind Rush, and the shooter switches between them by concentrating and speaking the word lightning or wind. BONUS: +1 to strike.', 'Rifts World Book 16: Federation of Magic p.115-116'),
('tw-sonic-rifle', 'TW Sonic Rifle', 'rifts', 'weapon', 8, 320000, '320,000 credits for the rifle (Black Market); 40,000 credits per P.P.E. clip.', 'As the Shockwave spell to everything around the target; the target struck by the full brunt takes double damage', 1, '600 feet (183 m); the shockwave radiates 30 feet (9 m) around the target struck', '5 shots per P.P.E. clip.', 'Single shots', NULL, NULL, NULL, 'Unleashes a modified, longer-ranged Shockwave spell: an energy pulse that releases a shockwave the instant it hits. NOT the Underseas Sonic Rifle (TW), which is a different weapon.', 'Rifts World Book 16: Federation of Magic p.116'),
('tw-starfire-pulse-cannon', 'Starfire Pulse Cannon', 'rifts', 'weapon', 124, 520000, '520,000 credits for the cannon (Black Market); 40,000 credits per P.P.E. clip, 320,000 credits for all eight.', '2D6x10 M.D. per blue-white energy bolt', 1, '2000 feet (610 m)', 'Two shots per clip; eight P.P.E. clips fit into the top canister, for 16 shots in all.', 'Single shots only', NULL, NULL, NULL, 'A large, heavy TW cannon that can only be mounted on vehicles and robots, firing long-range blue-white energy bolts able to gut an enemy vehicle in a few shots. Extremely popular and often mounted on ATVs; the TW Battle Skimmer typically carries 4-6 of them. Its drawback is the expensive power supply. BONUS: +1 to strike. Stored as a weapon row rather than a vehicle add-on because the book prices and describes it as a stand-alone weapon.', 'Rifts World Book 16: Federation of Magic p.116'),
('tw-dragonfire-flamethrower', '"Dragonfire" Flamethrower', 'rifts', 'weapon', 8, 150000, '150,000 credits for the thrower (Black Market); 40,000 credits per clip.', '1D6x10 M.D. to everything in its 100 foot (30.5 m) length of fire; roughly a 2nd level Fire Gout spell', 1, '100 feet (30.5 m)', '5 blasts per P.P.E. clip.', 'Single shots only; the flame can be whipped back and forth to hit everything in a corridor 10 feet (3 m) wide and 100 feet (30.5 m) long, which uses three melee attacks', NULL, NULL, NULL, 'An ornately decorated TW flamethrower with a dragon''s head at the nozzle, made to appeal to the Cult of Dragonwright. It needs no fuel tank: magic provides the flames. PRICE READ OFF A RENDER of printed 117, one of this book''s glyph-corrupt pages.', 'Rifts World Book 16: Federation of Magic p.117'),
('tw-flash-freeze-grenade', 'Flash Freeze Grenade', 'rifts', 'weapon', 0.5, 25000, '25,000 credits per grenade (Black Market). One use.', 'No direct damage. Encases everything in a 10 foot (3 m) radius sphere in ice, basically the same as this book''s Ice spell; the ice lasts 3D6 minutes and has 50 M.D.C.', 0, 'Thrown 100 feet (30.5 m); affects a 10 foot (3 m) radius', 'One use.', 'One can be thrown with each attack', NULL, NULL, NULL, 'A normal-looking grenade painted white. On detonation it encases the area in solid ice; the sphere does not go through the ground, and a large target is only partly covered and can probably break free. A living creature fully encased enters suspended animation until the ice is removed. Blasting a victim out has a 50% chance per attempt of hurting both the ice and the victim, unless precision tools are used. PRICE READ OFF A RENDER of printed 117, one of this book''s glyph-corrupt pages.', 'Rifts World Book 16: Federation of Magic p.117'),
('tw-firebomb', 'Firebomb', 'rifts', 'weapon', 0.5, 25000, '25,000 credits each (Black Market). One use.', '6D6 M.D. to a 10 foot (3 m) radius', 1, 'Thrown 100 feet (30.5 m); affects a 10 foot (3 m) radius', 'One use.', 'One can be thrown per attack', NULL, NULL, NULL, 'A TW grenade that explodes in magical flame and flying embers. Painted red, it closely resembles a modern hand grenade and is easily confused with one. PRICE READ OFF A RENDER of printed 117, one of this book''s glyph-corrupt pages.', 'Rifts World Book 16: Federation of Magic p.117'),
('tw-shockstorm-landmine', 'Shockstorm Landmine', 'rifts', 'weapon', 5, 100000, '100,000 credits per mine (Black Market); 20,000 credits to recharge.', '2D6 M.D. to all susceptible targets in range; each attack hits automatically, and most mortal victims (01-70%) are knocked off their feet and lose one melee action and initiative', 1, '12 foot (3.6 m) radius', 'Once activated it keeps shocking living creatures, vehicles and metal (which it is drawn to) for one minute (4 melee rounds). A spent mine can be recharged and reset by a Techno-Wizard.', 'Special: one attack on every target in its 12 ft radius, twice per melee', NULL, NULL, 30, 'An anti-personnel mine that does not need to be stepped on: magical sensing triggers it when anything moves within five feet (1.5 m), and arcs of electricity leap to every target in the area for as long as they stay in it. A flat silver disk about half a foot (0.15 m) across. PRICE READ OFF A RENDER of printed 117, one of this book''s glyph-corrupt pages.', 'Rifts World Book 16: Federation of Magic p.117'),
('tw-whip-of-pain', 'Whip of Pain', 'rifts', 'weapon', 2, 200000, '200,000 credits (Black Market).', '3D4 S.D.C./H.P. as a barbed whip; when activated, inflicts the Agony spell (Rifts RPG p.177) on each target struck, effective against mortal and mega-damage beings', 0, '12 feet (3.6 m)', 'The user pumps in 20 P.P.E. (or 40 I.S.P.) to activate the magic, which then lasts one minute (4 melees).', 'Once activated, inflicts Agony on everyone it strikes with each attack for one minute (4 melees)', NULL, NULL, NULL, 'A black, 8 foot bull whip with small, razor-sharp barbs at the end, enchanted to immobilise the enemy with pain and leave them helpless against further attacks. A more conventional Techno-Wizard item: it has no clip and runs on the user''s own P.P.E. or I.S.P.', 'Rifts World Book 16: Federation of Magic p.118'),
('tw-scepter-of-command', 'Scepter of Command', 'rifts', 'weapon', 4, 700000, '700,000 to one million credits (Black Market).', '2D6 M.D. per physical strike, used as a mace (no P.P.E. cost)', 1, 'Melee', 'The user pumps in the P.P.E. (or double I.S.P.) for each spell power.', 'As hand to hand attacks', NULL, NULL, 100, 'A dark black and purple rod engraved with symbols, used as a blunt weapon or to release spell magic. POWERS: (1) Command Ghouls, 10 P.P.E. - commands 2D6 ghouls, as the Necromancy spell, for one hour; (2) Animate and Control Dead, 20 P.P.E., as the spell, command lasting one hour; (3) Domination, 10 P.P.E., as the spell; (4) Repel Animals, 7 P.P.E., as the spell, twice per 24 hours. BONUS: the user is +2 to save vs Necromantic magic. A more conventional Techno-Wizard item, powered by the user.', 'Rifts World Book 16: Federation of Magic p.118'),
('tw-firestaff', 'Firestaff', 'rifts', 'weapon', 5, 2000000, '2-3 million credits (Black Market).', '2D6+2 M.D. from physical attacks; the gold caps burn for 1D4 M.D. at a slight touch and 1D6 M.D. if an opponent grabs the metal', 1, 'Melee; spell ranges as the spells', 'The user pumps in the P.P.E. (or double I.S.P.) for each spell.', 'As hand to hand attacks or spell casting', NULL, NULL, 150, 'A 6-7 foot (1.8-2.1 m) staff of dark wood capped at each end with gold, often topped with a flame, phoenix or dragon figure. Weaker in melee than most rune weapons but a great power over fire; usually only experienced, wealthy sorcerers can afford to use it, and it is a favourite of Fire Warlocks. The staff regenerates 10 M.D.C. per day. SPELLS, each at 5th level: Ignite Flame (5), Fuel Flame (5), Fireblast (8), Fire Ball (10), Fire Blossom (20), Ballistic Fire (25), Ten Foot Wheel of Fire (40; 5D8 M.D.) and Extinguish Fire (8; cast up to 150 feet (46 m) away, affecting a 100 foot (30.5 m) area). CREATION: all of the above plus Ensorcel (400), Ironwood (150), Firequake (160) and Enchant Weapon (1000), over 2000 P.P.E. in all; three months to make.', 'Rifts World Book 16: Federation of Magic p.118'),
('tw-paralysis-staff', 'Paralysis Staff', 'rifts', 'weapon', 5, 500000, '500,000-600,000 credits (Black Market).', '1D6 M.D. from physical attacks, plus paralysis: the silver end numbs the part touched and paralyses the nearest limb, as the Paralysis: Lesser spell (standard save; supernatural beings and creatures of magic +2)', 1, 'Melee', 'The user pumps in 5 P.P.E. (or 10 I.S.P.) to activate it; the paralysis effect lasts 30 minutes per activation.', 'As hand to hand attacks', NULL, NULL, 100, 'A 6-7 foot (1.8-2.1 m) staff of light wood capped at each end with silver. Anyone other than the wielder who touches its upper half may be paralysed; the magic does not affect its user. The staff regenerates 10 M.D.C. per day. CREATION: Paralysis: Lesser (5), Ensorcel (400), Ironwood (150) and an additional 200 P.P.E.', 'Rifts World Book 16: Federation of Magic p.119'),
('tw-draining-blade', 'Draining Blade', 'rifts', 'weapon', 3, 2000000, '2-3 million credits (Black Market).', '4D6 M.D.; each target hit must save vs magic or suffer a 7th level Life Drain (Rifts RPG p.178) for 10 melee rounds. M.D. creatures take only the 4D6 M.D.', 1, 'Melee', 'The user pumps in 5 P.P.E. (or 10 I.S.P.) to activate it; the draining effect lasts 30 minutes per activation.', 'As hand to hand attacks', NULL, NULL, 150, 'A magic sword that weakens the spirit of its target as it cuts, often given to leaders as a symbol of command. A failed save halves the victim''s hit points, S.D.C. and speed, costs one melee attack and -10% on skills; it works on targets in body armour or power armour but nothing bigger. The sword regenerates 10 M.D.C. per day. CREATION: Life Drain (25), Energy Disruption (12), Sickness (50), Ensorcel (400) and Enchant Weapon (1000).', 'Rifts World Book 16: Federation of Magic p.119'),
('tw-deathbringer-sword', 'Deathbringer Sword', 'rifts', 'weapon', 6, 11000000, '11-14 million credits (Black Market). A Deathbringer made without Power Weapon, doing only 5D6 M.D., fetches 10 million.', '1D6x10 M.D. (5D6 M.D. if made without Power Weapon)', 1, 'Melee; Sub-Particle Acceleration 500 feet (152 m)', 'The wielder pays the P.P.E. for each spell power.', 'As hand to hand attacks', NULL, NULL, 250, 'Always a huge two-handed sword of black metal inscribed with magic symbols (not a true Rune sword): the most physically powerful weapon Stormspire makes, hard to produce, and rare. Weak against groups and at range, but beloved of Mystic Knights and Battle Magi for one-on-one fights. The sword regenerates 10 M.D.C. per day. POWERS: Invulnerability (50 P.P.E.), self only, for eight melee rounds, against everything but magic and psionics, and not extending to equipment; Sub-Particle Acceleration (20 P.P.E.), 500 feet (152 m), 1D6x10+5 M.D.; Spinning Blades (20 P.P.E.), self. BONUS: +1 to strike and parry. CREATION: the spells above plus Ensorcel, Featherlight (10), Power Weapon (35) and Enchant Weapon (1000); 3-4 months to make.', 'Rifts World Book 16: Federation of Magic p.119'),
('tw-battle-fury-blade', 'Battle Fury Blade', 'rifts', 'weapon', 7, 12000000, '12-15 million credits (Black Market); 2-3 months to make.', '6D6 M.D.; 1D6x10 M.D. per hit while the Battle Fury is active', 1, 'Melee', '40 P.P.E. channelled into the weapon invokes the Battle Fury for 12 melee rounds (3 minutes).', 'As hand to hand attacks; two strikes per attack during the Battle Fury', NULL, NULL, 200, 'Usually a Claymore, sometimes a Flamberge, polearm or large battle axe, always bright silver with etched designs; its powers are the same in any form. A favourite of Battle Magi, Mystic Knights, Cyber-Knights and Juicers. Regenerates 20 M.D.C. per day. THE BATTLE FURY: while active every hit does 1D6x10 M.D., every attack the wielder makes becomes two (opponents are -5 to parry the second), and the wielder is encased in magical force with 100 M.D.C. CREATION: Ensorcel (400), Speed Weapon (100), Power Weapon (35), Invincible Armor (30) and Enchant Weapon (1000).', 'Rifts World Book 16: Federation of Magic p.119-120'),
('tw-shadow-cloak', 'Shadow Cloak', 'rifts', 'gear', 1, 200000, '200,000-300,000 credits (Black Market).', NULL, 0, NULL, 'Each power is activated with the wearer''s P.P.E.: Shadow Meld 10, the living shadow 45.', NULL, NULL, NULL, 15, 'A pitch-black cloak sized for humans that will not fit anyone larger. It is fragile and not meant as armour. POWERS: (1) Shadow Meld, 10 P.P.E., as the spell at 5th level (10 minutes maximum); (2) the wearer''s shadow appears to come to life and distract opponents, as the Shadows of Death Necromancy spell, 45 P.P.E.: the wearer gains a Horror Factor of 12 and opponents are -2 on all combat bonuses. BONUS: +20% to hide in shadows when not Shadow Melding. CREATION: the two spells above plus Cloak of Darkness (6), Invincible Armor (30) and Energize Spell (12).', 'Rifts World Book 16: Federation of Magic p.120');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 25 Federation of Magic TW gear rows are in' AS assertion, count(*) AS got, 25 AS want
  FROM gear WHERE slug IN ('stormspire-ppe-energy-cell', 'tw-firebolt-pistol', 'tw-jammer', 'tw-shard-pistol', 'tw-starfire-pistol', 'tw-shock-pistol', 'tw-nova-rifle', 'tw-disrupter', 'tw-fireburst-rifle', 'tw-force-cannon', 'tw-storm-rifle', 'tw-sonic-rifle', 'tw-starfire-pulse-cannon', 'tw-dragonfire-flamethrower', 'tw-flash-freeze-grenade', 'tw-firebomb', 'tw-shockstorm-landmine', 'tw-whip-of-pain', 'tw-scepter-of-command', 'tw-firestaff', 'tw-paralysis-staff', 'tw-draining-blade', 'tw-deathbringer-sword', 'tw-battle-fury-blade', 'tw-shadow-cloak');
SELECT 'and every one cites Federation of Magic by page' AS assertion, count(*) AS got, 25 AS want
  FROM gear WHERE slug IN ('stormspire-ppe-energy-cell', 'tw-firebolt-pistol', 'tw-jammer', 'tw-shard-pistol', 'tw-starfire-pistol', 'tw-shock-pistol', 'tw-nova-rifle', 'tw-disrupter', 'tw-fireburst-rifle', 'tw-force-cannon', 'tw-storm-rifle', 'tw-sonic-rifle', 'tw-starfire-pulse-cannon', 'tw-dragonfire-flamethrower', 'tw-flash-freeze-grenade', 'tw-firebomb', 'tw-shockstorm-landmine', 'tw-whip-of-pain', 'tw-scepter-of-command', 'tw-firestaff', 'tw-paralysis-staff', 'tw-draining-blade', 'tw-deathbringer-sword', 'tw-battle-fury-blade', 'tw-shadow-cloak') AND source_book LIKE 'Rifts World Book 16: Federation of Magic p.%';
SELECT 'the four printed-117 prices read off the render' AS assertion, count(*) AS got, 4 AS want
  FROM gear WHERE (slug = 'tw-dragonfire-flamethrower' AND cost = 150000) OR (slug = 'tw-flash-freeze-grenade' AND cost = 25000)
     OR (slug = 'tw-firebomb' AND cost = 25000) OR (slug = 'tw-shockstorm-landmine' AND cost = 100000);

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-fom-tw-gear.sql');
