-- Rifts World Book 31: Triax 2, batch 1: gear. 45 new rows: the Triax
-- commercial products (printed 73-76), the new pistols, rifles, giant-size
-- and TX-H weapons, shields and WaffenTek energy weapons (96-107), the new
-- body armor (107-110), and the six XLH hardpoint weapon pods (174-175).
-- See apps/character-creator/docs/surveys/triax-2.md.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-triax-2-gear.sql
--
-- ALL 45 ARE NEW - every slug and model number queried against production
-- gear and vehicles, 2026-10-03, and the slugs again right before this file
-- was written.
--
-- EVERY NUMBER WAS READ OFF A RENDER and checked against a render again by
-- book-reconcile: 45 rows, no figure disagreed. The text layer swaps digits
-- for letters on several of these pages.
--
-- CONVENTIONS:
--   cost is a range's low end, with the printed wording in cost_note. No
--     price printed: cost NULL (the XLH pods, the TX-H weapons' giant mace).
--   The energy supplements print bare brand names (Metal, Rat, Zoom,
--     Pick-Up, Cataclysm); the rows add "Energy Drink" or "Energy Pills" so
--     the catalog name says what the item is.
--   The TX-H1 Electro-Mace prints two styles with their own damage and price
--     and is two rows (H1-M, H1-S). The older giant Electro-Mace this book
--     reprices at 70,000 credits is held as triax-electro-mace (WB5 p.150);
--     the new price is in tx-h1-m-electro-mace's cost_note, and the held row
--     is not touched.
--   The VS-101 Sonic Stun Projector is a vehicle-mounted crowd weapon sold as
--     one item; it is a gear row with its mobile unit's locations in the
--     description.
--   Grenades and shells priced inside a weapon's entry are in that weapon's
--     cost_note, not rows of their own.
--
-- NOT HERE, ON PURPOSE:
--   The TX-J50 Juicer EBA (printed 108-109) is held as tx-j50-juicer-eba from
--     Free Quebec p.51. Triax 2 prints different figures (main body 100,
--     30 lbs, 225,000 credits against 90, 20 lbs, 50,000); the held row
--     stands and the disagreement is in the survey.
--   The T-25 "Uber" Super-Exoskeleton prints M.D.C. by location and is a
--     vehicles row. The pilot's bionic body and XML interface are the
--     luftwaffe-cyborg-combat-pilot class's, not items.
--   The Jaeger shoulder modules (printed 125-126) carry no price and fit the
--     held x-535-hunter-jager; the vehicle features and add-on weapon systems
--     (printed 85-89) are a price list the survey leaves out.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('triax-instant-meal-paste-maker', 'Triax Instant Meal Paste Maker', 'rifts', 'gear', NULL, 175, '175 credits for the appliance; an ingredient refill costs 100 credits and makes 30+1D10 meals, about 3 credits a meal.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A countertop appliance about the size of a big cappuccino machine, popular with busy NGR professionals. A keypad picks a recipe and the machine mixes dehydrated ingredient pellets (fish, bread, sausage, ham, spices) with hot water into a thick paste dispensed into a bowl in under forty seconds; custom recipes can be programmed, and it also makes smoothies, energy drinks and supplement drinks. Compact enough to fit in a car or truck. Widely sold in the NGR and Poland and turns up elsewhere in Europe and North America, including Coalition cities.', 'Rifts World Book 31: Triax 2 p.73'),
('atomix-powder', 'Atomix Powder', 'rifts', 'gear', NULL, 40, '40 credits a box of about 20 doses. Triax energy supplements cost five times the European price on the North American Black Market.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A sweet-tart Triax energy powder sold in a baking-soda-sized box; mixed with water, cooked into rock candy or eaten straight. Two doses within an hour give +1 on initiative and +1 to P.S. for 1D4 hours, and tint everything the user sees yellow and green. While high the user suffers -2 on Perception Rolls, -5% on skills, -20% when resisting Seduction, and -2 against mind control magic or psionics that flatters the user. Minimal addictiveness even in large amounts; most popular with males.', 'Rifts World Book 31: Triax 2 p.74'),
('cataclysm-bootleg-energy-drink', 'Cataclysm (Bootleg Energy Drink)', 'rifts', 'gear', NULL, 50, '50 credits a can. German Black Market only, from drug dealers and disreputable venues; illegal to own, buy or sell, and sometimes hard to find.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A bootleg drink carrying the Triax name but not made by Triax; nutritious, tasty and dangerous. One can triggers a hallucination of the Great Cataclysm lasting 1D6x10 minutes (each further can adds 2D6x10), in which the user believes he is a god-like hero, fights with fists and imaginary powers, and acts out the delusion in the real world. While under, he is +2 to save vs magic and psionics, +6 to save vs drugs and stun, and impervious to Horror Factor, Seduction and possession. Highly addictive. Each can carries a cumulative 1% chance (capped at 50%) that the trip never ends: roll percentile - 01-33 the user lives half his time in the delusion, 34-66 he retreats into it (01-85%) for 4D6 hours whenever threatened or stressed, 67-00 he is lost in it permanently.', 'Rifts World Book 31: Triax 2 p.74-75'),
('metal-energy-drink', 'Metal Energy Drink', 'rifts', 'gear', NULL, 5, '5 credits per can.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Triax energy drink in a tall black can covered in demons, skulls and guitars, aimed at young males and laced with hormones and chemicals harvested from alien creatures. Two or more cans make a human hyperactive for one hour, with +1 initiative and +2 physical combat damage; for D-Bees the bonuses double and last 1D4 hours. Drawbacks: -2 on Perception Rolls, -1 parry/dodge, -3 pull punch/roll with impact, -5% on skills, and an aggressive, brawl-prone temper. Humans become addicted only at six or more cans a day; a D-Bee drinking more than 4-5 cans a week becomes an addict craving 2-6 a day.', 'Rifts World Book 31: Triax 2 p.75'),
('pick-up-energy-pills', 'Pick-Up Energy Pills', 'rifts', 'gear', NULL, 50, '50 credits per pack of 10 pills.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Triax pill sold as a natural enhancer for adults, with a smoother, longer high than the company''s drinks. It takes effect 45 minutes after a dose and lasts 1D10+2 hours: +1 on Perception Rolls, +1 on initiative, +5% to skill performance with skills done quickly, and no fatigue; an hour-long cool-down follows. Afterwards the user crashes at -2 on Perception Rolls, -2 on initiative and -10% to skills (which take twice as long) until he gets 1D6+7 hours of sleep. Very highly addictive - after about a month users feel they cannot work well without it.', 'Rifts World Book 31: Triax 2 p.75'),
('rat-energy-drink', 'Rat Energy Drink', 'rifts', 'gear', NULL, 10, 'A six-pack sells for 10 credits; a single can delivers a hit.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A cheap Triax drink marketed to City Rats, punks, Ghetto D-Bees and street gangs, promoted from booths in clubs and bars. Two cans within an hour give a mellow buzz and the ability to ignore fatigue and lack of sleep for two hours (half that for D-Bees); more acts like beer or wine without the hangover. A buzzed drinker (2-3 cans an hour) suffers -1 initiative, -2 Perception Rolls, -1 to every combat move and -10% on skills; penalties double when blitzed (4+ cans an hour), usually without the drinker noticing. About as addictive as alcohol.', 'Rifts World Book 31: Triax 2 p.75-76'),
('zoom-energy-drink', 'Zoom Energy Drink', 'rifts', 'gear', NULL, 3, 'Three credits per can.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Triax''s best-selling flagship energy drink since 101 P.A., sold in a spray-paint-style can with a screw top; humans find it harsh but D-Bees love it. Three cans within an hour give +1 attack per melee, +1 on initiative and resistance to fatigue and lack of sleep for 1D4+2 hours for D-Bees (half that for humans). Addiction comes from 3+ cans most days for three weeks or more: addicts are at -2 attacks per melee and -15% on skills except right after a can. Quitting brings 2D6+10 hours of sleep and doubled penalties for 1D6 days (penalty durations double for humans).', 'Rifts World Book 31: Triax 2 p.76'),
('cosmetic-perfection-system', 'Cosmetic Perfection System', 'rifts', 'gear', NULL, 650, '650 credits for the complete system; individual cosmetics 2-150 credits (about five uses each); nano-bots replaced and upgraded every three years for 300 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Triax makeup system that scans the user''s face once she has done her makeup and stores the look in a thousand nano-bots kept in a heated moisturizing towel. Laid over the face, the towel gives a 3-5 minute facial massage while the nano-bots reapply the makeup exactly, and it never runs or smears. A pocket Perfection Calibration Computer offers 1,600 variations. Bonus: +1 to P.B. for twelve hours. Not compatible with the Ultimate Perfection Skin Care System.', 'Rifts World Book 31: Triax 2 p.76'),
('ultimate-perfection-skin-care-system', 'Ultimate Perfection Skin Care System', 'rifts', 'cybernetics', NULL, 5500, '5,500 credits for the initial installation; a recharge at a certified Triax Beauty Perfection Clinic every 12+1D4 months costs 950 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Nano-bots surgically implanted in the upper skin of the face and neck, controlled from a small transmitter, that color hair, smooth wrinkles and simulate makeup on demand. They reduce wrinkles, lines and age spots by 60%, slow skin aging, hunt skin cancer and warn of other skin disease early. Bonus: +2 to P.B. and the user looks 3D4+7 years younger. No other cosmetics are needed, and it cannot be combined with the Cosmetic Perfection System.', 'Rifts World Book 31: Triax 2 p.76'),
('t-1011-x2-cyclops-booster', 'T-1011-X2 Cyclops Booster', 'rifts', 'armor', 5, 70000, '70,000 credits, not counting the suit itself.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A light exoskeleton augmentation fitted into existing T-10 Cyclops and T-11 Enhanced infantry armor in two hours by a certified Triax technician; it adds 5 pounds and does not change mobility. It raises human P.S. by 6 and Spd by 6, adds 4 feet (1.2 m) to leaps across or up, slows fatigue by 20%, and grants +1 parry, +1 dodge and +1 roll with impact. About 40% of NGR troops have it, officers and special forces first; the Air Force is not scheduled to get it. No M.D.C. of its own - it uses the host suit''s.', 'Rifts World Book 31: Triax 2 p.107-108'),
('t-e02-infiltrator-espionage-armor', 'T-E02 Infiltrator Espionage Armor', 'rifts', 'armor', 20, 730000, '730,000 credits; often twice that on the Black Market.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 90, 'Full environmental light infiltration armor for sabotage and espionage, with M.D.C. mesh at the joints and sound-muffling soles; excellent mobility, no penalties, +5% to Prowl. M.D.C. by location: Head/Helmet 50, Arms 34 each, Legs 45 each, Main Body 90. A pre-Rifts color-shifting camouflage system matches its surroundings and masks infrared and thermal emissions, making it invisible to thermal sensors. Comes with a utility belt, a dual holster and a Vibro-Knife in the boot (1D6 M.D.). A built-in jump pack leaps 30 feet (9.1 m) up or 40 feet (12.2 m) across (+30% with a running start), slows falls from up to 700 feet (213 m) for +3 to roll with impact and 10% damage, and adds +1 to dodge.', 'Rifts World Book 31: Triax 2 p.109-110'),
('td-10-sea-cyclops-dive-armor', 'TD-10 Sea Cyclops Dive Armor', 'rifts', 'armor', 20, 350000, '350,000 credits; seldom offered on the Black Market.', NULL, 0, NULL, NULL, NULL, NULL, NULL, 100, 'SCUBA body armor built for the NGR navy and Operation Sea Storm; very good mobility (only -5% on Climb, Prowl, Swim, Acrobatics and comparable skills). M.D.C.: Main Body 100, Head/Helmet 70, Legs 50 each, Arms 35 each. Rated to 1,000 feet (305 m) with a computer depth gauge, gyro and HUD depth alarm, and boots that take swim fins. A standard 40 M.D.C. rebreather pack gives 10 hours of silent, bubble-free air (including the suit''s 5-hour supply); the modular backpack mount also takes extra tanks (4 hours each, two maximum), a jet pack or a sealed container. A dozen maneuvering jets cut the swim penalty to -10%, and a multi-optic helmet band adds infrared, ultraviolet, thermal imaging and telescopic targeting.', 'Rifts World Book 31: Triax 2 p.110'),
('tx-6-revolver', 'TX-6 Revolver', 'rifts', 'weapon', 5, 12000, '12,000 credits.', '4D6 M.D.', 1, '800 feet (244 m)', 'Six rounds; reload one round per melee action, or all six in one action with a speed loader', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'A heavy, long-barreled high-tech revolver that shares its ammunition with the TX-5 Pump Pistol, TX-16 Pump Rifle and TX-17 Assault Rifle. It has become a popular sidearm with infantry and mercenaries, and has recently gone on sale on the German market with fair availability; a few have already reached gunslingers in the New West.', 'Rifts World Book 31: Triax 2 p.96'),
('tx-23-laser-assault-pistol', 'TX-23 Laser Assault Pistol', 'rifts', 'weapon', 5, 20000, '20,000 credits.', '2D6 M.D. per single shot; 5D6 M.D. per three shot pulse', 1, '800 feet (244 m)', '20 shots per standard E-Clip or 50 per Long E-Clip; a burst uses three shots', 'Each single shot or three shot burst is one melee attack', NULL, NULL, NULL, 'A compact, burst-capable laser pistol built for the Triax Security Forces, who wanted a concealable sub-machine pistol with more punch. The E-Clip loads downward ahead of the trigger guard rather than sliding in from the front, giving the gun a blocky look. It takes both standard and Long E-Clips.', 'Rifts World Book 31: Triax 2 p.96'),
('tx-25-ion-pistol', 'TX-25 Ion Pistol', 'rifts', 'weapon', 4.3, 27000, '27,000 credits.', '3D4+3 M.D. per blast', 1, '600 feet (183 m)', '12 shots per standard E-Clip or 24 per Long E-Clip', 'Single shots only; each shot is one melee attack', NULL, NULL, NULL, 'The NGR designation for the Q1-02 "Stopper" Ion Pistol carried by Free Quebec''s forces, developed jointly with Free Quebec. It is regarded as one of the finest energy pistols on the market.', 'Rifts World Book 31: Triax 2 p.96-97'),
('tx-27-particle-beam-pistol', 'TX-27 Particle Beam Pistol', 'rifts', 'weapon', 6.6, 45000, '45,000 credits.', '5D6+5 M.D. per blast; Critical Strike (double damage) on a Natural 19 or 20', 1, '500 feet (152 m)', '10 shots per E-Clip', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'An evolution of earlier Triax particle beam pistols with more damage and range. It is a killing weapon with little use away from the battlefield. The text once calls it the T-27.', 'Rifts World Book 31: Triax 2 p.97'),
('tx-sl12-sharpshooter-laser-rifle', 'TX-SL12 Sharpshooter Laser Rifle', 'rifts', 'weapon', 5, 47000, '47,000 credits.', '4D6 M.D.', 1, '3,500 feet (1067 m)', '15 shots per forward sliding E-Clip', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'A sniper rifle, forerunner of the TX-SL13, proven over four years of combat as one of the most stable and reliable Triax sniping platforms; favored by scouts, assassins, snipers and bounty hunters. It debuted what became Triax''s standard laser targeting system, and was the final Triax gun designed around the front sliding E-Clip, which gives it fine balance. Small payload and per-shot calibration make it a bad assault rifle. +2 to strike from laser targeting and balance.', 'Rifts World Book 31: Triax 2 p.97'),
('tx-sl13-ultra-sniper-rifle', 'TX-SL13 Ultra Sniper Rifle', 'rifts', 'weapon', 55, 90000, '90,000 credits for the weapon, plus 10,000 for the two heavy duty carrying cases (20 M.D.C. each). Made in small numbers for the NGR military only; not offered on the Black Market.', '1D4x10 M.D. per shot', 1, '5,000 feet (1524 m)', '8 shots per standard E-Clip or 16 per Long E-Clip, plus two shots every 30 minutes from the built-in nuclear power cell even with the clip empty; can also be cabled to a cyborg, power armor or vehicle power supply', 'Single shots only; each blast is one melee attack. No burst fire.', NULL, NULL, NULL, 'The "Ultra": a big single-shot, two-piece anti-Gargoyle sniper rifle, normally crewed by a sniper and spotter, that uses a miniature nuclear capacitor to hit like a vehicle-mounted laser. It has a heavy bipod, a sight that links to a helmet data port or headjack, and can be turret mounted. Fired without bracing, strike penalties are -9 for ordinary humanoids, -4 for power armor, cyborgs and anyone with Robotic or Augmented P.S., and -1 with Supernatural P.S.; even braced a quick shot is -1. +1 on a braced Aimed or Called Shot. The power cell lasts one year of constant use.', 'Rifts World Book 31: Triax 2 p.97-98'),
('tx-75-grenade-launcher', 'TX-75 Grenade Launcher', 'rifts', 'weapon', 20, 55000, '55,000 credits for the launcher. Grenades: 1,200 credits per standard issue DU fragmentation round, 800 per conventional fragmentation grenade, 1,000 per armor piercing round.', '5D6 M.D. to a 3 foot (0.9 m) radius from Depleted Uranium grenades; fragmentation 2D6+2 M.D. to a 12 foot (3.6 m) radius. Also fires conventional explosive, smoke, tear gas and stun grenades.', 1, '2,000 feet (610 m)', '30 round drum; an ammo backpack holds two more drums (60 grenades)', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'An anti-Gargoyle and anti-armor launcher firing rocket-assisted grenades, akin to Wellington Industries ramjet rounds, with fragmenting Depleted Uranium casings meant for Gargoyles and armored Brodkil. A P.S. under 20 means -2 to strike. +1 to strike from laser targeting when carefully aimed.', 'Rifts World Book 31: Triax 2 p.98-99'),
('tx-ss01-exterminator-shotgun', 'TX-SS01 Exterminator Shotgun', 'rifts', 'weapon', 15, 40000, '40,000 credits. Buckshot rounds 400 credits each; solid slug rounds 550 credits each.', 'Buckshot 2D6 M.D. to everything in a 6 foot (1.8 m) radius; solid slug 4D6 M.D. to one target', 1, '600 feet (183 m)', '8 rounds; single rounds can be hand loaded', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'A large-bore close-quarters shotgun built for cyborgs and troopers clearing Gargoyle nests, hatcheries and city streets; the ammunition line also includes smoke, flare, tear gas and other chemical shells. Firing it requires Augmented P.S. 16 or human P.S. 22; otherwise the shooter is -2 to strike, knocked back, and loses initiative and one attack. A solid slug forces man-sized to 16 foot targets to roll 12+ on 1D20 or be knocked down (lose initiative and one attack); those who save take an extra 1D6 M.D. The gun weighs 15 pounds, plus 8 with the ammo drum (the book also prints 20 pounds total).', 'Rifts World Book 31: Triax 2 p.99'),
('tx-46-particle-beam-rifle', 'TX-46 Particle Beam Rifle', 'rifts', 'weapon', 11, 76000, '76,000 credits. Unavailable on the Black Market.', '1D4x10+8 M.D.; Critical Strike (double damage) on a Natural 19 or 20', 1, '1,400 feet (426.7 m)', '24 shots', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'Successor to the TX-45 Particle Beam Rifle, with slightly more range and damage, built to put down large, fast-healing foes such as Gargoyles. It has a bigger barrel, its own laser targeting sight, a full stock, and still uses the FSE-Clip. +1 to strike on Aimed shots.', 'Rifts World Book 31: Triax 2 p.99'),
('tx-17-assault-rifle', 'TX-17 Assault Rifle', 'rifts', 'weapon', 15, 50000, '50,000 credits.', '4D6 M.D. per single round or 1D4x10+4 M.D. per three round burst', 1, '1,200 feet (366 m)', '30 or 45 round magazines, or a 105 round ammo drum (needs P.S. 20)', 'Each single shot or three round burst is one melee attack; selector switch', NULL, NULL, NULL, 'A conventional assault rifle reworked to fire the larger shells of the Triax pump weapons, with a straight magazine ahead of the trigger guard that takes several clip sizes. It has brackets for scopes and under-barrel laser sights or grenade launchers. With the drum attached it needs P.S. 20 (-2 to strike otherwise) and is clumsy for humans but fine for cyborgs and power armor. The rifle weighs 15 pounds, plus 5-7 for a clip; 20 pounds with a drum.', 'Rifts World Book 31: Triax 2 p.100'),
('tx-a1-concealed-shotgun', 'TX-A1 Concealed Shotgun', 'rifts', 'weapon', 12, 25000, '25,000 credits. Leather covering at a slight extra cost.', 'S.D.C. shotgun shell 4D6 S.D.C. to a 4 foot (1.2 m) radius; solid slug 5D6 S.D.C.; M.D. fragmentary explosive shell 2D6 M.D. to a 6 foot (1.8 m) radius; M.D. plasma explosive shell 3D6 M.D. to a 3 foot (0.9 m) radius; M.D. armor piercing round 2D6+2 M.D.', 1, 'S.D.C. shell or solid slug 300 feet (91.5 m); explosive and armor piercing rounds 500 feet (152 m)', 'Eight S.D.C. rounds and 8 M.D. rounds', 'Single shots only; each blast is one melee attack', NULL, NULL, NULL, 'A Triax Aktenkoffer (briefcase) gun: a hidden button turns the case into a pump shotgun, the lower half dropping and sliding back to form grip and stock, and a switch selects S.D.C. or M.D. ammunition. The M.D.C. plastic shell passes metal detectors and gives a false x-ray image of papers and files; it comes in silver, grey, brown or black. A favorite of Triax spies, assassins and bodyguards. The briefcase introduction calls it the TX-A1 Combat Shotgun.', 'Rifts World Book 31: Triax 2 p.100-101'),
('tx-a2-concealed-submachine-gun', 'TX-A2 Concealed Submachine-Gun', 'rifts', 'weapon', 12, 30000, '30,000 credits. Leather covering at a slight extra cost.', '1D6x10 S.D.C. per burst, or 2D6 M.D. per burst with M.D. ammunition', 1, '800 feet (244 m)', '30 S.D.C. bursts and 30 M.D. bursts', 'Burst fire only; each burst is one melee attack', NULL, NULL, NULL, 'The submachine-gun version of the Triax Aktenkoffer briefcase gun: the lower section folds up into a stock and exposes the grip, and the ammunition sits in that stock half. Like the shotgun it switches between S.D.C. and M.D. rounds, has a metal-detector-proof M.D.C. plastic case that fakes an innocent x-ray image, and is popular with Triax spies, assassins and bodyguards.', 'Rifts World Book 31: Triax 2 p.101'),
('vs-101-sonic-stun-projector', 'VS-101 Sonic Stun Projector', 'rifts', 'weapon', 2000, 345000, 'Civil defense (basic): 345,000 credits, or 1.5 million credits with a force field. Military defense (basic): 430,000 credits, or 1.6 million credits with a force field. Military combat version on a hover platform, force field included: 2 million credits. Not yet offered on the Black Market.', 'No damage; disorientation (see description)', 0, '2,500 feet (762 m) for full effect; halved among trees, buildings or other large structures', 'Continuous while powered (electrical or nuclear)', 'Continuous emission in all directions; a new save every two melee rounds', NULL, NULL, 120, 'A car-sized sonic emitter from the Passau Research Komplex that disorients every kind of Gargoyle in range; canines, Dog Boys and anything with keen hearing suffer half penalties, while Brodkil and humans are unaffected. Victims save on 14+ (no attribute bonuses) or have attacks halved, no initiative, half combat bonuses, Spd -70%, -50% on skills and no dodge bonuses in flight; a save halves the penalties. One operator (Literacy and Computer Operation); 12 x 5 x 4 feet, one ton (tripled on a hover platform that flies at 80 mph). Basic unit M.D.C.: Main Body 120, Control Panel 20. Mobile military unit: Main Body 170, Hover Platform 100, Hover Jets (3) 40 each, Control Panel 20, Force Field 200 (does not block the sound).', 'Rifts World Book 31: Triax 2 p.101-102'),
('tx-222-pulse-laser-giant-size', 'TX-222 Pulse Laser (Giant Size)', 'rifts', 'weapon', 135, 160000, 'Black Market 160,000+ credits; NGR Army only, rarely seen on the secondary market.', '1D6x10 M.D. per quadruple pulse burst', 1, '3,000 feet (914 m)', '40 bursts from the internal power supply, recharging one burst per 10 minutes when linked to a robot or power armor; a giant front sliding E-Clip also holds 40 bursts; effectively unlimited on the host''s power supply', 'Burst firing only; each burst is one melee attack; cannot make a Called Shot', NULL, NULL, NULL, 'A giant-sized burst-firing pulse laser derived from the TX-41 pulse rifle, more compact but more powerful. It is the Ulti-Max II''s primary handheld weapon, and some heavy Combat Cyborgs and Power Armor Commandos use it too; built mainly for 10-20 foot robots and power armor. Its bursts are less accurate than aimed fire.', 'Rifts World Book 31: Triax 2 p.102-103'),
('tx-252-rail-gun-giant-size', 'TX-252 Rail Gun (Giant Size)', 'rifts', 'weapon', 225, 150000, 'Black Market 150,000+ credits; NGR Army only, scarce on the secondary market.', '1D6x10 M.D. per 30 round burst', 1, '4,600 feet (1402 m)', '3,000 round drum (100 bursts)', 'Each burst is one melee attack', NULL, NULL, NULL, 'An enlarged, heavier-set take on the TX-500 ''Borg rail gun made as a handheld assault weapon for power armor and robots; standard issue to the Predator II. Shorter ranged than most Triax rail guns but harder hitting. Heavy cyborgs can fire it two-handed at -2 to strike. The gun weighs 225 pounds; each ammo drum, worn on the back or hip, adds 250.', 'Rifts World Book 31: Triax 2 p.103'),
('tx-249-particle-beam-rifle-giant-size', 'TX-249 Particle Beam Rifle (Giant Size)', 'rifts', 'weapon', 297, 190000, 'Black Market 190,000+ credits; NGR Army only, scarce on the secondary market.', '1D6x10+10 M.D.; Critical Strike (double damage) on a Natural 19 or 20', 1, '2,000 feet (610 m)', '33 blasts per oversized E-Clip, 66 from a larger back or hip power pack cabled to the rifle, effectively unlimited on the host''s power supply', 'Each blast is one melee attack', NULL, NULL, NULL, 'The first giant-sized particle beam rifle for power armor and robots, carried by the Ulti-Max II along with other heavy suits and ''Bots 10-20 feet tall. It normally draws on the host''s nuclear supply through a contact point in the hand rather than a cable, shortening the power supply''s life by 30-50%, but can take a giant E-Clip. Light power armor and heavy Combat Cyborgs usually fire it from a tripod; firing standing without penalty needs Robotic P.S. 26.', 'Rifts World Book 31: Triax 2 p.103'),
('tx-h1-m-electro-mace', 'TX-H1-M Electro-Mace', 'rifts', 'weapon', NULL, 35000, '35,000 credits for the mace. The older, truly giant-sized Electro-Mace for ''Bots 27 feet and larger is 70,000 credits.', '2D6 M.D. per strike, +1D6 when electrically charged; electrical blast 3D6 M.D.', 1, 'Hand to hand, or 1,000 feet (305 m) via electrical blast', 'Effectively unlimited; independent power supply', 'Three long-range blasts per melee', NULL, NULL, NULL, 'The mace style of the TX-H1, a restyled Electro-Mace for robots and power armor under 25 feet: a heavy ball on a handle, without the old hand cowling, that can still be pointed to fire an electrical discharge. It carries its own power supply and needs no cable. Anti-personnel and riot control; part of the TX-H melee line, which sells well outside the NGR.', 'Rifts World Book 31: Triax 2 p.103-104'),
('tx-h1-s-morning-star', 'TX-H1-S Morning Star', 'rifts', 'weapon', NULL, 45000, '45,000 credits.', '3D6 M.D. per strike, +1D6 when electrically charged; electrical blast 4D6+8 M.D.', 1, 'Hand to hand, or 1,000 feet (305 m) via electrical blast', 'Effectively unlimited; independent power supply', 'Three long-range blasts per melee', NULL, NULL, NULL, 'The spiked style of the TX-H1 Electro-Mace for robots and power armor under 25 feet, harder hitting than the plain mace. It can be pointed to fire an electrical discharge and runs on its own power supply. Anti-personnel and riot control.', 'Rifts World Book 31: Triax 2 p.103-104'),
('tx-h2-vibro-axe', 'TX-H2 Vibro-Axe', 'rifts', 'weapon', NULL, 22000, '22,000 credits.', '3D6 M.D.', 1, 'Hand to hand combat', 'Effectively unlimited', NULL, NULL, NULL, NULL, 'A big double-bladed Vibro-Axe for larger robots and power armor, the least novel of the TX-H line but long requested and cheaper than its siblings. Anti-personnel, close combat and firefighting.', 'Rifts World Book 31: Triax 2 p.104'),
('tx-h3-blast-hammer', 'TX-H3 Blast Hammer', 'rifts', 'weapon', NULL, 40000, '40,000 credits.', '2D6 M.D. blunt face or 2D6+2 M.D. spike; an activated blast adds 2D6 M.D. with an 80% chance to knock down a foe under 13 feet (3.9 m) tall, 40% for larger', 1, 'Hand to hand combat', '10 stored blasts; restores one per hour of normal movement, or one per 20 minutes of running or combat', NULL, NULL, NULL, NULL, 'One of the newest Triax melee weapons, shaped like a war hammer with a blunt face and a large spike. Once activated it stores kinetic energy from the wielder''s movement and releases it as a concussive blast on impact. A knocked-down victim loses initiative and one melee attack. For robots and power armor.', 'Rifts World Book 31: Triax 2 p.104'),
('tx-h5-plasma-whip', 'TX-H5 Plasma Whip', 'rifts', 'weapon', NULL, 110000, '110,000 credits. Poor availability on the secondary market.', '2D6+2 M.D. per lash or energy discharge; 6D6+3 M.D. per melee round to an entangled weapon, item or limb; spike end 1D6 S.D.C.; deactivated whip-line 2D4 S.D.C.', 1, '7 feet (2.1 m) as a whip; energy blast 200 feet (61 m)', '9 strikes and/or blasts on the internal supply (recharged at a military base or the factory); effectively unlimited on a robot or power armor power supply', 'Each whip strike or energy blast is one attack', NULL, NULL, NULL, 'A handle with a parrying spike at one end and a flexible filament that fills with superheated plasma when active, for robots and power armor. It can entangle a weapon or limb, burning it every round, and disarm; it cannot strike while something is entangled, prying it loose does 2D6 M.D. to whatever pries, and 20 M.D. cuts the line. Usually powered through a contact point in the ''Bot''s hand, as a cable could tangle. +2 to disarm and +2 to entangle. Brodkil both fear and covet it.', 'Rifts World Book 31: Triax 2 p.104-105'),
('tx-001-defense-shield', 'TX-001 Defense Shield', 'rifts', 'armor', 100, 200000, '200,000 credits, driven by the amount of M.D. material. Good availability.', '1D6 M.D. plus punch damage by Robotic P.S.', 1, 'Close combat', NULL, NULL, NULL, NULL, 160, 'A large shield, 7 feet tall and three and a half wide, giving extra protection to robots, power armor and heavy combat ''Borgs; used for defense and riot control and as a bludgeon. +1 to parry with the shield.', 'Rifts World Book 31: Triax 2 p.105'),
('tx-002-heavy-weapon-shield', 'TX-002 Heavy Weapon Shield', 'rifts', 'armor', 200, 400000, '400,000 credits for the shield; mini-missiles are bought separately.', 'Shield as a blunt weapon 1D6 M.D. plus punch damage by Robotic P.S.; mini-missiles vary by type, usually high explosive at 1D4x10 M.D. each', 1, 'Close combat as a melee weapon; one mile (1.6 km) for mini-missiles', '30 mini-missiles', 'Mini-missiles one at a time or in volleys of 2, 4, 8 or all 30', NULL, NULL, 160, 'A robot and power armor shield that hides a battery of 30 mini-missiles behind armored plates that flip open to fire; any mini-missile type works. Used for defense and riot control, and secondarily for assault and anti-armor. Weighs 200 pounds plus the missiles. +1 to parry with the shield. The text''s opening sentence calls it the TX-001 Heavy Weapon Shield.', 'Rifts World Book 31: Triax 2 p.106'),
('waffentek-wt-10-pre-rifts-laser-pistol', 'WaffenTek WT-10 "Pre-Rifts" Laser Pistol', 'rifts', 'weapon', 2, 6500, '6,500 credits. Excellent availability.', '2D4 M.D.', 1, '600 feet (183 m)', '25 shots per standard E-Clip', NULL, NULL, NULL, NULL, 'A cheap, easily made laser pistol based on early Golden Age designs that WaffenTek recovered and refined; the original maker was a small firm Triax bought out long ago. It is the gun that is always on the shelf when better Triax weapons are scarce or too costly.', 'Rifts World Book 31: Triax 2 p.106'),
('waffentek-wt-20-pre-rifts-laser-rifle', 'WaffenTek WT-20 "Pre-Rifts" Laser Rifle', 'rifts', 'weapon', 5, 10000, '10,000 credits.', '3D4 M.D.', 1, '1,400 feet (427 m)', '21 shots per standard E-Clip', NULL, NULL, NULL, NULL, 'An inexpensive WaffenTek laser rifle from a recovered pre-Rifts design, bought by sport hunters, wilderness scouts, competition shooters and homesteaders defending property on the border or outside the NGR.', 'Rifts World Book 31: Triax 2 p.106'),
('waffentek-volkspistole-vp-01', 'WaffenTek "VolksPistole" VP-01', 'rifts', 'weapon', 1.6, 3000, '3,000 credits.', '4D6 S.D.C.; cannot be converted to M.D. and does not hurt M.D.C. targets', 0, '500 feet (152 m)', '140 shots per standard E-Clip', NULL, NULL, NULL, NULL, 'The "People''s Gun": a deliberately S.D.C. laser pistol for civilian self-defense, selling the futuristic appeal of an energy weapon without Mega-Damage power. Controversial but a huge commercial success, it led WaffenTek to build a whole S.D.C. energy line. The low output allows a very large payload. The book gives its weight as 1.6 lbs (0.7 m), a metric slip.', 'Rifts World Book 31: Triax 2 p.106-107'),
('waffentek-hell-fighter-vp-02-sdc-laser-rifle', 'WaffenTek "Hell-Fighter" VP-02 S.D.C. Laser Rifle', 'rifts', 'weapon', 6, 5000, '5,000 credits.', 'Three settings: 5D6 S.D.C., 1D4x10 S.D.C. or 2D4x10 S.D.C.; cannot be converted to M.D.', 0, '1,800 feet (548.6 m)', '120 shots at the low setting, 60 at either higher setting', NULL, NULL, NULL, NULL, 'A light, simple S.D.C. laser rifle on VolksPistole technology, that sells well on the open market. Police and security teams carry it where Mega-Damage would be excessive, and it is common among wilderness folk, hunters, bandits, criminals, mercenaries and adventurers. Its optics and balance give +1 to strike when taking an Aimed shot. The book gives its weight as 6 lbs (2.7 m), a metric slip.', 'Rifts World Book 31: Triax 2 p.107'),
('xlh-rocket-mini-missile-pod', 'XLH Rocket/Mini-Missile Pod', 'rifts', 'weapon', NULL, NULL, NULL, 'Varies with missile; armor piercing (standard issue) 1D4x10 M.D.', 1, 'Varies with missile type; one mile (1.6 km) for armor piercing', '12 mini-missiles per pod', '1, 2, 4, 6 or all 12; can be fire-linked with other pods of the same type', NULL, NULL, NULL, 'A hardpoint pod of rapid-fire mini-missiles meant chiefly for ground targets and close aerial ones; primary purpose anti-personnel, secondary anti-aircraft and anti-missile. Any mini-missile can be loaded, armor piercing being standard, and pods of the same type can be fire-linked to launch together. Mounting it cancels any stealth the aircraft has. Like every XLH pod it is mounted in pairs, one under each side, and each pair costs the aircraft 5% of its speed and -1 to dodge; empty pods can be jettisoned. No price is printed.', 'Rifts World Book 31: Triax 2 p.174-175'),
('xlh-short-medium-range-missile-pod', 'XLH Short-Range/Medium-Range Missile Pod', 'rifts', 'weapon', NULL, NULL, NULL, 'Varies with missile type', 1, 'Varies with missile type', 'Six short-range or four medium-range missiles per pod', '1, 2, 4 or 6 short-range; 1, 2 or 4 medium-range; can be fire-linked with other pods of the same type', NULL, NULL, NULL, 'A hardpoint pod for larger missiles, aimed at aircraft first and fortifications or installations second. It takes any short- or medium-range missile and can be fire-linked with pods of the same type. Mounting it cancels any stealth the aircraft has. Like every XLH pod it is mounted in pairs, one under each side, and each pair costs the aircraft 5% of its speed and -1 to dodge; empty pods can be jettisoned. No price is printed.', 'Rifts World Book 31: Triax 2 p.175'),
('xlh-free-fall-bomb-ejector-rack', 'XLH Free-Fall Bomb Ejector Rack', 'rifts', 'weapon', NULL, NULL, NULL, 'Varies with bomb type; as medium-range missiles of the same type, with double the blast radius', 1, 'Dropped from the air onto a ground target', 'Four bombs per rack', '1, 2, 3 or all 4; can be fire-linked with other ejector racks', NULL, NULL, NULL, 'A hardpoint rack of free-fall bombs for stationary or slow targets, used against installations and fortifications and secondarily armor. Each bomb matches a medium-range missile in type and damage but cover twice the blast radius, and racks can be fire-linked to saturate an area. Mounting it cancels any stealth the aircraft has. Like every XLH pod it is mounted in pairs, one under each side, and each pair costs the aircraft 5% of its speed and -1 to dodge; empty pods can be jettisoned. No price is printed.', 'Rifts World Book 31: Triax 2 p.175'),
('xlh-pulse-laser-pod', 'XLH Pulse Laser Pod', 'rifts', 'weapon', NULL, NULL, NULL, '6D6 M.D. per pulse', 1, '6,000 feet (1,829 m)', 'Effectively unlimited; linked to the power source of the vehicle', 'Each pulse blast uses one attack', NULL, NULL, NULL, 'An external pulse laser pod, anti-aircraft and anti-Gargoyle with a defensive second role, drawing on the aircraft''s own power so it never runs dry. Pods can be fire-linked with one another and with the built-in weapons of the XML-280 Black Eagle or XML-285 Ghost. Mounting it cancels any stealth the aircraft has. Like every XLH pod it is mounted in pairs, one under each side, and each pair costs the aircraft 5% of its speed and -1 to dodge; empty pods can be jettisoned. No price is printed.', 'Rifts World Book 31: Triax 2 p.175'),
('xlh-rail-gun-pod', 'XLH Rail Gun Pod', 'rifts', 'weapon', NULL, NULL, NULL, '6D6 M.D. per 15 round short burst or 1D6x10 M.D. per 30 round long burst', 1, '6,000 feet (1,829 m)', '600 rounds per pod, enough for 20 long bursts', 'Each burst uses one melee attack; can be fire-linked with other pods of the same type', NULL, NULL, NULL, 'An external rail gun pod loaded with uranium ammunition (U- or DU-Rounds) for use on Gargoyles and other supernatural enemies, anti-aircraft first and assault second, with its ammunition held in a magazine inside the pod. Pods of the same type can be fire-linked. Mounting it cancels any stealth the aircraft has. Like every XLH pod it is mounted in pairs, one under each side, and each pair costs the aircraft 5% of its speed and -1 to dodge; empty pods can be jettisoned. No price is printed.', 'Rifts World Book 31: Triax 2 p.175'),
('xlh-stealth-missile-pod', 'XLH Stealth Missile Pod', 'rifts', 'weapon', NULL, NULL, NULL, 'Varies with missile; any short- or medium-range missile', 1, 'Varies with missile type', 'Five short-range or three medium-range missiles per pod', 'One at a time or volleys of 1, 3 or 5 short-range, or 1, 2 or 3 medium-range; can be fire-linked with other pods of the same type', NULL, NULL, NULL, 'A short- and medium-range missile pod built from the same radar-absorbent material and angular shaping as the Luftwaffe stealth airframes, anti-Gargoyle first and anti-aircraft second. It accepts any short- or medium-range missile, and matching pods fire-link. Unlike the other pods it costs only -5% to the aircraft''s stealth per pair. Like every XLH pod it is mounted in pairs, one under each side, and each pair costs the aircraft 5% of its speed and -1 to dodge; empty pods can be jettisoned. No price is printed.', 'Rifts World Book 31: Triax 2 p.175');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 45 rows are in and cite Triax 2' AS assertion, count(*) AS got, 45 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 31: Triax 2 p.%' AND slug IN ('triax-instant-meal-paste-maker', 'atomix-powder', 'cataclysm-bootleg-energy-drink', 'metal-energy-drink', 'pick-up-energy-pills', 'rat-energy-drink', 'zoom-energy-drink', 'cosmetic-perfection-system', 'ultimate-perfection-skin-care-system', 't-1011-x2-cyclops-booster', 't-e02-infiltrator-espionage-armor', 'td-10-sea-cyclops-dive-armor', 'tx-6-revolver', 'tx-23-laser-assault-pistol', 'tx-25-ion-pistol', 'tx-27-particle-beam-pistol', 'tx-sl12-sharpshooter-laser-rifle', 'tx-sl13-ultra-sniper-rifle', 'tx-75-grenade-launcher', 'tx-ss01-exterminator-shotgun', 'tx-46-particle-beam-rifle', 'tx-17-assault-rifle', 'tx-a1-concealed-shotgun', 'tx-a2-concealed-submachine-gun', 'vs-101-sonic-stun-projector', 'tx-222-pulse-laser-giant-size', 'tx-252-rail-gun-giant-size', 'tx-249-particle-beam-rifle-giant-size', 'tx-h1-m-electro-mace', 'tx-h1-s-morning-star', 'tx-h2-vibro-axe', 'tx-h3-blast-hammer', 'tx-h5-plasma-whip', 'tx-001-defense-shield', 'tx-002-heavy-weapon-shield', 'waffentek-wt-10-pre-rifts-laser-pistol', 'waffentek-wt-20-pre-rifts-laser-rifle', 'waffentek-volkspistole-vp-01', 'waffentek-hell-fighter-vp-02-sdc-laser-rifle', 'xlh-rocket-mini-missile-pod', 'xlh-short-medium-range-missile-pod', 'xlh-free-fall-bomb-ejector-rack', 'xlh-pulse-laser-pod', 'xlh-rail-gun-pod', 'xlh-stealth-missile-pod');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-triax-2-gear.sql');
