-- Rifts World Book 9: South America 2 - its gear. 60 new rows: hand weapons,
-- body armor and the class and monster magic items. Power armor, robots and
-- vehicles are add-south-america-2-vehicles.sql.
--
--   Empire of the Sun, printed 23-35 and 56-58: the True Inca's club, spear
--     and cloth armor, the Inca Warrior's Holy Axe, Amulet of Protection and
--     Holy Sun Sling, the Sun-Priest's holy symbol, the Rune Warrior's
--     Pattern Staff, the Energy Jar, the Inti and Illapa guns, Gilded and
--     Sinchi body armor
--   Forces of Darkness, printed 50 and 55: the Ancient's enchanted club and
--     poncho, the Pucara Red Giant's stone axe, hammer and two stone armors
--   The Arkhons, printed 79-84: nine weapons and Arkhon Body Armor
--   The Megaversal Legion, printed 113-115: six weapons, Mark I and Mark II
--   Silver River Republics, printed 163-168: ten weapons, seven body armors
--   The Larhold, printed 186-190: composite bow, saber, hide armor, demon-mask
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-south-america-2-gear.sql
--
-- ALL 60 ARE NEW. catalog-diff --table gear --remote, 2026-09-25, run
-- immediately before this file, matched none of the 54 extracted names, and
-- none of the 60 slugs exists in production.
--
-- READ FROM A SCAN (no text layer). Extracted in two slices by
-- book-extract-worker; every Arkhon stat block (79-84) and the Inti-20's
-- displaced triple-pulse line (57) were read off a render. book-reconcile
-- checked all 54 extracted rows against their stat blocks and agreed with
-- every one; it found the six Ancient and Pucara items (50, 55) missing, and
-- those were added by hand from the same pages.
--
-- CONVENTIONS:
--   * Holy, enchanted and monster-made items are 'magic', like the catalog's
--     other enchanted gear; the Amaki TW Psi-Blade is 'magic' too.
--   * The Megaversal Legion's gear has cost NULL: the book marks it not for
--     sale outside the Legion, and cost_note says so.
--   * Where a class entry prints different figures for the same item (the
--     Larhold composite bow and saber, Barbarian vs Shaman vs Renegade), every
--     figure is in damage with its page, not one chosen.
--   * The Pucara stone armors weigh "well over a hundred pounds (45 kg)"; 100
--     is stored as that floor and the description says so.
--   * Where the book prices a range, cost is the low end and cost_note the
--     range. A multi-page citation lists its pages; the first is the stat
--     block.
--   * DESCRIPTIONS ARE PARAPHRASES, never the book's prose.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book) VALUES
('true-inca-magic-club', 'Magic Club', 'rifts', 'magic', NULL, NULL, 'granted, not sold', '2D4 M.D. plus supernatural hand to hand damage', 1, 'melee', NULL, 'melee', NULL, NULL, NULL, 'A magical club given to True Incas, inflicting 2D4 M.D. in addition to the wielder''s supernatural P.S. hand to hand damage.', 'Rifts World Book 9: South America 2 p.23'),
('true-inca-enchanted-spear', 'Enchanted Spear', 'rifts', 'magic', NULL, NULL, 'granted, not sold', '2D6 M.D. plus supernatural hand to hand damage', 1, 'melee', NULL, 'melee', NULL, NULL, NULL, 'An enchanted spear given to True Incas, inflicting 2D6 M.D. in addition to the wielder''s supernatural P.S. hand to hand damage.', 'Rifts World Book 9: South America 2 p.23'),
('true-inca-enchanted-cloth-armor', 'Enchanted Cloth Armor', 'rifts', 'magic', NULL, NULL, 'granted, not sold', NULL, 1, NULL, NULL, NULL, NULL, NULL, 90, 'The body armor issued to True Incas: cloth robes woven with magic, providing 90 M.D.C. of protection.', 'Rifts World Book 9: South America 2 p.23'),
('holy-axe', 'Holy Axe', 'rifts', 'magic', NULL, NULL, 'issued equipment, not sold', '4D6+6 M.D.', 1, 'melee', NULL, 'melee', NULL, NULL, NULL, 'A minor holy weapon issued to every Inca Warrior. Inflicts 4D6+6 M.D., can heal 1D8+1 S.D.C. or M.D.C. points to its wielder six times a day, and glows golden when wielded against supernatural beings.', 'Rifts World Book 9: South America 2 p.23-24'),
('amulet-of-protection', 'Amulet of Protection', 'rifts', 'magic', NULL, NULL, 'issued equipment, not sold', NULL, 1, NULL, 'six activations per day, each lasting 10 minutes', NULL, NULL, NULL, 100, 'An amulet issued to Inca Warriors that projects the Armor of Ithan spell at 10th level strength (100 M.D.C.), activated at will up to six times a day, each activation lasting 10 minutes.', 'Rifts World Book 9: South America 2 p.23-24'),
('holy-sun-sling', 'Holy Sun Sling', 'rifts', 'magic', NULL, NULL, 'issued equipment, not sold', '4D6 M.D.', 1, '2000 feet (610 m)', NULL, NULL, NULL, NULL, NULL, 'A magical sling issued to Inca Warriors that fires small balls of magical fire, inflicting 4D6 M.D. at a range of 2000 feet (610 m).', 'Rifts World Book 9: South America 2 p.23-24'),
('sun-priest-holy-symbol', 'Holy Symbol of Viracocha', 'rifts', 'magic', NULL, NULL, 'issued to every priest, not sold; only works for the priest it was made for', '3D6 M.D. (to a being with hatred for the pantheon who willingly touches it)', 1, 'self/touch', 'three castings per day per spell, each at 10th level proficiency, no P.P.E. cost', NULL, NULL, NULL, NULL, 'A gold ceremonial-knife-shaped amulet given to every Inca priest, shaped like Viracocha''s face/headgear (blade) and body (handle). Three times a day it casts, at 10th level proficiency and no P.P.E. cost: armor of Ithan, circle of protection (superior), and heal wounds. It burns anyone with hatred for the pantheon who willingly touches it for 3D6 M.D., and can repel vampires like a cross. Only works for the priest it was made for.', 'Rifts World Book 9: South America 2 p.25-26'),
('pattern-staff', 'Pattern Staff', 'rifts', 'magic', NULL, NULL, 'created during initiation, not sold', 'energy beam: 1D6 M.D. per P.P.E. point spent, +3 to strike', 1, '100 feet (30.5 m) per level of experience', NULL, NULL, NULL, NULL, NULL, 'A crystalline magical construct staff symbiotically linked to a Rune Warrior''s life force, created during initiation. Has 1D4x100+200 M.D.C., only damaged if deliberately targeted, and regenerates 10 M.D.C. per hour. Can transfer up to 100 M.D.C. of its life force to the wearer over 24 hours (if the staff is destroyed the warrior takes 2D6x10 M.D.), and can fire an energy beam doing 1D6 M.D. per P.P.E. point spent (+3 to strike, range 100 feet/30.5 m per level of experience).', 'Rifts World Book 9: South America 2 p.30'),
('energy-jar', 'Energy Jar (Jar of Power)', 'rifts', 'magic', NULL, 50, '50 to 100 credits per P.P.E. point stored', NULL, 0, NULL, 'stores 2D6 P.P.E. per level of the caster who made it; fully discharges whenever used', NULL, NULL, NULL, NULL, 'A jar or drinking vessel painted with an intricate geometric line pattern that acts as a magic energy matrix, storing 2D6 P.P.E. per level of the drawing line maker. The energy is usable by any practitioner of magic but is entirely expended when released. Sold in the Empire of the Sun and trading partners like New Babylon for 50 to 100 credits per P.P.E. point stored.', 'Rifts World Book 9: South America 2 p.35'),
('inti-10-variable-laser-pistol', 'Inti-10 Variable Laser Pistol', 'rifts', 'weapon', 2, 10000, NULL, '2D4+2 M.D.', 1, '1000 feet (305 m)', '10 shots', 'Standard', NULL, NULL, NULL, 'The Inca Army''s standard sidearm, made in Arequipa. Its variable-frequency laser can defeat laser-resistant armor (like Glitter Boy alloys) 1D4 attacks after the first hit, though it was originally developed, unsuccessfully, as a countermeasure against Arkhon body armor.', 'Rifts World Book 9: South America 2 p.56'),
('inti-20-variable-laser-rifle', 'Inti-20 Variable Laser Rifle', 'rifts', 'weapon', 4, 18000, NULL, '2D6+6 M.D. per single shot or 1D4x10+10 M.D. for a triple pulse', 1, '2000 feet (610 m)', '24 shots', 'Standard', NULL, NULL, NULL, 'The standard-issue long-arm of the Inca Army, carried by about 60% of infantry. Like the Inti-10 pistol, its variable-frequency laser defeats laser-resistant armor 1D4 attacks after the first hit.', 'Rifts World Book 9: South America 2 p.56-57'),
('illapa-1-rocket-pistol', 'Illapa-1 Rocket Pistol', 'rifts', 'weapon', 5, 14000, '14,000 credits; each bullet costs 20 credits', '2D6+4 M.D. per shot', 1, '600 feet (183 m)', '80 shots in drum magazine or 20 in a small clip', 'Standard', NULL, NULL, NULL, 'Named for the Inca thunder god, this pistol fires fat 15mm explosive bullets from a front-mounted drum magazine, making it front-heavy and clumsy but effective against Arkhon composite armor.', 'Rifts World Book 9: South America 2 p.57'),
('illapa-5-rocket-rifle', 'Illapa-5 Rocket Rifle', 'rifts', 'weapon', 9, 26000, NULL, '4D6 M.D. per shot; 3-round burst 1D4x10 M.D.; 10-round burst 2D4x10 M.D.', 1, '2400 feet (731.5 m)', '60 shot drum magazine', 'Selective fire: single aimed shots, 3-round bursts, 10-round bursts; a disengage mechanism prevents full-automatic fire', NULL, NULL, NULL, 'A drum-fed rifle firing longer, harder-hitting 15mm cartridges than the Illapa-1 pistol, carried by 30-50% of Inca troops especially against the energy-resistant Arkhons.', 'Rifts World Book 9: South America 2 p.57'),
('gilded-body-armor', 'Gilded Body Armor', 'rifts', 'armor', 21, 50000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 70, 'Ornate solid-metal-plate armor with a helmet styled after Inti''s half-moon headgear, reserved for officers and elite units. Fair to good mobility (-10% prowl penalty). Nazca line makers sometimes inscribe magic patterns in it, which are destroyed once half the armor''s M.D.C. is depleted.', 'Rifts World Book 9: South America 2 p.58'),
('sinchi-body-armor', 'Sinchi Body Armor', 'rifts', 'armor', 10, 25000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 45, 'A light, serviceable jumpsuit-style military armor worn by the rank and file of the Inca army, with articulated plates at elbows/knees and a face-plated helmet. Good mobility (-5% prowl penalty); issued in mountain or jungle camouflage patterns, and favored (often repainted) by priests and magicians.', 'Rifts World Book 9: South America 2 p.58'),
('tb-3-tri-beam-energy-pistol', 'TB-3 Tri-Beam Energy Pistol', 'rifts', 'weapon', 2, 12000, 'poor availability outside Arkhon-influenced areas', '2D4 M.D.; double damage to most materials except force/energy fields and Arkhon composite armor', 1, '500 feet (152 m)', '15 shots', 'Single shots only (each counts as one melee attack); no burst capability', NULL, NULL, NULL, 'A stubby, short-barreled tri-beam pistol issued to Arkhon support personnel; humans are at -1 to strike until practicing for 1D4 hours. Traded copies carry an Earth E-clip adapter and a self-destruct system that triggers if the outer casing is tampered with.', 'Rifts World Book 9: South America 2 p.79-80'),
('tb-9-auto-pistol', 'TB-9 Auto-Pistol', 'rifts', 'weapon', 5, 30000, 'not normally sold; captured weapons cost 30,000-90,000 credits, +50% with an Earth E-clip adapter', '4D6 M.D.; double damage to most materials except force/energy fields and Arkhon composite armor', 1, '1200 feet (365 m)', '30 shots', 'Standard', NULL, NULL, NULL, 'A heavy pistol/light sub-machinegun issued to Arkhon officers, pilots, vehicle crews, military police and intelligence units; usable two-handed.', 'Rifts World Book 9: South America 2 p.80'),
('tb-prime-tri-beam-energy-rifle', 'TB-Prime Tri-Beam Energy Rifle', 'rifts', 'weapon', 10, 60000, 'not for sale; captured rifles cost 60,000-160,000 credits, +30% with an Earth E-clip adapter', '5D6 M.D. tri-beam (double damage to most materials except force/energy fields and Arkhon composite armor); grenades 4D6 M.D. to a 12 foot (3.65 m) area', 1, '2000 feet (610 m)', '30 tri-beam blasts, and 3 grenades', 'Standard', NULL, NULL, NULL, 'The Arkhon army''s standard battle rifle, combining a tri-beam weapon with a semi-automatic 3-round grenade launcher. Known among the Andean people as demon rifles.', 'Rifts World Book 9: South America 2 p.80-81'),
('m-100-tri-beam-crew-served-gun', 'M-100 Tri-Beam Crew Served Gun', 'rifts', 'weapon', 21, 130000, 'rarely available; price starts at 130,000+ credits', 'single shot 5D6 M.D.; 3-round burst 1D4x10+10 M.D.; double damage to most materials except force/energy fields and Arkhon composite armor', 1, '3000 feet (914 m)', '60 shots in an extended magazine; does not accept Arkhon or Earth standard clips (a jury-rigged clip provides 15 shots with an Arkhon clip or 10 with an Earth clip)', 'Standard burst firing', NULL, NULL, NULL, 'A medium-machinegun-equivalent support weapon fired from a bipod, typically crewed by a two-man team. Can chew through a main battle tank''s front armor with a few long bursts; issued one per 10-soldier Arkhon squad alongside a BM-2 or BRL-3.', 'Rifts World Book 9: South America 2 p.81'),
('bm-2-backpack-mortar-system', 'BM-2 Backpack Mortar System', 'rifts', 'weapon', 30, 120000, '120,000 to 200,000 credits; smart bombs cost 3,000 credits each, rarely available outside the Arkhon Army', 'Fragmentary Bombs: 3D6 M.D. to a 20 foot (6.1 m) radius; Anti-Armor: 6D6 M.D. to a 2 foot (0.6 m) radius', 1, 'up to 2 miles (3.2 km); minimum range 300 feet (91.4 m)', '18 bomblets in the magazine; reload magazine takes 5 minutes, changing magazines takes 1 melee round for two people or 4 melees for one', 'Single shot, burst of three, or long burst of six; each counts as one melee attack', NULL, NULL, NULL, 'A backpack-worn mortar linked to the wearer''s helmet HUD; the gunner verbally gives a range and coordinates and the launch tube self-orients. Bomblets have 1 M.D.C. each, leave no contrail (called shot at -4 to strike), and can be primed as fragmentary (air-burst) or anti-armor (impact). About 30% of ammo is smart-guided (+3 to strike).', 'Rifts World Book 9: South America 2 p.81-82'),
('brl-3-backpack-rocket-launcher', 'BRL-3 Backpack Rocket Launcher', 'rifts', 'weapon', 30, 150000, '150,000 credits, rarely available; Cordoba/Santiago copies carry only 6 mini-missiles and cost 100,000 credits', '2D4x10 M.D. direct hit, plus 4D6 M.D. to an additional 10 foot (3.0 m) radius around the strike point', 1, 'Guided: 5 miles (8 km); Direct Fire: line of sight to 2000 feet (610 m)', '12 rockets, each about twice the size of a grenade', 'Each missile shot counts as one hand to hand attack; cannot fire volleys', NULL, NULL, NULL, 'A backpack-mounted anti-armor/anti-structure rocket launcher usable in guided mode (helmet-projected aiming point, +3 to strike) or direct fire (fired over the shoulder like a bazooka). Reloading takes one melee attack/action. Captured launchers are copied by Cordoba and Santiago using conventional mini-missiles in direct-fire mode only. On the printed page the stat block for this weapon appears in the right column above its own heading, ahead of the Tri-Blade Energy Sword heading that actually follows it.', 'Rifts World Book 9: South America 2 p.82'),
('tri-blade-energy-sword', 'Tri-Blade Energy Sword', 'rifts', 'weapon', 3, 50000, 'rarely available; 50,000 credits or higher', '3D6 M.D.; double damage to most materials except force/energy fields and Arkhon composite armor', 1, 'hand to hand melee weapon', 'an Arkhon E-clip powers it for 8 hours of continuous use; activating it always consumes at least one minute''s worth of energy', 'Hand to hand combat only', NULL, NULL, NULL, 'A sword hilt with three thin wires that, when activated, form a tri-beam energy blade able to slice through most alloys and construction materials. Issued to officers; many soldiers buy a personal blade as a badge of courage.', 'Rifts World Book 9: South America 2 p.82'),
('fr-5-flechette-rifle', 'FR-5 Flechette Rifle', 'rifts', 'weapon', 15, 30000, 'poor availability; would be around 30,000 credits outside the Arkhon Freehold', '6D6 M.D. per shot; wild bursts spread flechettes over an area, doing 2D4 M.D. to each target hit', 1, '1200 feet (365 m)', '20 shot box magazine', 'Single shot only', NULL, NULL, NULL, 'An antigravity-accelerated flechette rifle issued to about 30% of Arkhon troops as a hedge against energy-resistant foes; each cartridge holds 10 flechettes. Does double damage to Arkhon body armor.', 'Rifts World Book 9: South America 2 p.83'),
('fra-1-flechette-auto-cannon', 'FRA-1 Flechette Auto-Cannon', 'rifts', 'weapon', 30, 80000, '80,000 credits or more; rarely available outside the army', '1D4x10 M.D. per shot; 10-round burst 2D6x10+10 M.D. (burst can spray an area, doing single-shot damage to affected targets)', 1, '4000 feet (1220 m)', '30 round drum magazine or 200-round belt', 'Standard', NULL, NULL, NULL, 'A flechette machinegun/auto-cannon support weapon fed from a drum or disintegrating belt, used as a squad weapon, carried by power armor/cyborg soldiers, or vehicle-mounted. Cannot be fired from the shoulder/hip unless the wielder has natural P.S. 24, supernatural P.S. 18, or is a cyborg/power armor with P.S. 20+.', 'Rifts World Book 9: South America 2 p.83'),
('arkhon-body-armor', 'Arkhon Body Armor', 'rifts', 'armor', 20, 40000, '40,000-60,000 credits for a modified suit usable by humans with no penalty; poor availability outside the Arkhon Freehold', NULL, 1, NULL, NULL, NULL, NULL, NULL, 85, 'Sealed, non-powered battle armor made of an advanced ceramic-plastic composite taking half damage from energy weapons but double damage from physical attacks (bullets, missile hits, M.D. punches, magic weapons). Excellent mobility (-5% prowl penalty). Fitted for Arkhon bodies; a human wearing an unmodified suit gets A.R. 17 and only 75 M.D.C. due to exposed gaps. Earth-made repairs (ordinary M.D.C. alloy patches) only restore 60% of damage taken, and after more than 30 M.D.C. is patched this way the suit loses its special energy/physical damage properties. A modified 110 M.D.C. version is issued to elite Arkhon troops (per page 79).', 'Rifts World Book 9: South America 2 p.83-84'),
('iar-20-inertia-rifle', 'IAR-20 Inertia Rifle', 'rifts', 'weapon', 6, NULL, 'Not for sale outside the Megaversal Legion', 'Single shot: 2D6 M.D. Burst of 15 rounds: 1D4x10 M.D. Long burst of 30 rounds: 2D4x10+10 M.D. IAR-20G grenade launcher variant (about 20% of these rifles): grenades do 3D6 M.D. to a 20 ft (6.1 m) blast radius', 1, '3000 feet (914 m) for bullets and grenades', '90 shot magazine; the IAR-20G''s tubular grenade launcher holds 7 grenades', 'Single shots, or bursts of 15 or 30 rounds; single shot only when firing the IAR-20G''s grenade launcher', NULL, NULL, NULL, 'Light, compact Dakir I-Beam rifle with a folding stock, short carbine-length barrel and a round top-mounted magazine; fires an accelerated 7mm round with no recoil. Used by about 60 percent of the Legion''s human-sized infantry. Roughly 20 percent of these rifles (the IAR-20G) carry an attached shotgun-style grenade launcher.', 'Rifts World Book 9: South America 2 p.113-114'),
('iar-2-auto-pistol', 'IAR-2 Auto-Pistol', 'rifts', 'weapon', 3, NULL, 'Not for sale outside the Megaversal Legion', '3D6 M.D.', 1, '1000 feet (305 m)', '20 rounds', 'Standard', NULL, NULL, NULL, 'I-Beam sidearm used by officers and pilots, and as a back-up weapon for line soldiers. Uses the same inertia-beam technology as the IAR-20 rifle; has a cylindrical magazine on top of the receiver.', 'Rifts World Book 9: South America 2 p.114'),
('hiar-22-heavy-i-beam-rifle', 'HIAR-22 Heavy I-Beam Rifle', 'rifts', 'weapon', 24, NULL, 'Not for sale outside the Megaversal Legion', 'I-Beam rounds: single shot 2D6 M.D.; burst of 15 rounds 1D4x10 M.D.; long burst of 30 rounds 2D4x10+10 M.D. Vibro-Axe attachment: 3D6 M.D. plus supernatural P.S. damage', 1, '3000 feet (914 m)', '150 shot oversized magazine', 'Single shots, or bursts of 15 or 30 rounds', NULL, NULL, NULL, 'Ojahee-sized version of the IAR-20 rifle, fitted like the HRP-1 with a vibro-axe attachment. Damage and range match the IAR-20, but it carries an oversized magazine for extra ammunition.', 'Rifts World Book 9: South America 2 p.114'),
('arp-1-plasma-assault-rifle', 'ARP-1 Plasma Assault Rifle', 'rifts', 'weapon', 8, NULL, 'Not for sale outside the Megaversal Legion', '3D6+4 M.D. per shot; three round burst does 1D6x10+10 M.D.', 1, '2000 feet (610 m)', '30 shots', 'Single shot or three round burst only; no recoil, so aimed bursts are possible at +3 to strike', NULL, NULL, NULL, 'Light, powerful thin-plasma rifle designed for human-sized users and limited to line infantrymen; easy to use and carry. Concentrated fire from several ARP-1s can melt down most M.D.C. vehicles, though it has proved less effective against the Arkhons.', 'Rifts World Book 9: South America 2 p.114'),
('hrp-1-plasma-heavy-rifle', 'HRP-1 Plasma Heavy Rifle', 'rifts', 'weapon', 30, NULL, 'Not for sale outside the Megaversal Legion', 'Plasma: 1D6x10+10 M.D. per blast. Vibro-Axe: 3D6 M.D. plus supernatural P.S. damage', 1, '3000 feet (914 m)', '20 shots per E-Clip', 'Single shot only', NULL, NULL, NULL, 'Long, heavy plasma rifle built along the lines of a musket to ease Ojahee warriors into using advanced weapons; carries a vibro-axe attachment like traditional Ojahee musketoons.', 'Rifts World Book 9: South America 2 p.115'),
('h-11a-howitzer', 'H-11A Howitzer', 'rifts', 'weapon', 120, NULL, 'Not for sale', 'High Explosive: 1D6x10 M.D. to a 40 foot (12.2 m) radius. Anti-Armor: 2D4x10 M.D. to a 3 foot (0.9 m) radius. Fragmentary: 4D6 M.D. to a 100 foot (30.5 m) radius', 1, '2000 feet (610 m) direct fire, or 2 miles (3.2 km) indirect fire', '10 round drum (revolver cylinder, hand-reloadable or swappable)', 'Each shot counts as one hand to hand attack; Fragmentary and High-Explosive rounds can be lobbed in a high arc and home in (plus 2 to strike) on enemies within a 500 foot/152 m radius of the arc''s descent', NULL, NULL, NULL, 'A 75mm hand-held howitzer using RD-field recoil dampening so a human can fire it like a heavy rifle. Requires P.S. 24+ to use without penalty (P.S. 19-23 is -2 to strike, P.S. 16-18 is -4, weaker users cannot fire it without power armor); worn with a harness that halves those penalties versus firing it unharnessed. Shells are compact (about 3 in/75mm thick, 5 in/13cm long) and can be fired direct or indirect.', 'Rifts World Book 9: South America 2 p.115'),
('mark-i-body-armor', 'Mark I Body Armor', 'rifts', 'armor', 20, NULL, 'Not for sale', NULL, 1, NULL, NULL, NULL, NULL, NULL, 90, 'Legion body armor for humans and humanoids: breastplate and articulated leg/arm plates, with a helmet open-T slit fitted with M.D.C. glass covering it to stay airtight while accommodating a grafted visor. Has a built-in inertial shield that automatically parries incoming physical attacks (bullets, missiles, rail gun slugs, not energy or hand-to-hand) at plus 3, stopping up to three projectiles per round; a failed parry still halves damage. Minus 5 percent prowl penalty (good mobility).', 'Rifts World Book 9: South America 2 p.115'),
('mark-ii-body-armor', 'Mark II Body Armor', 'rifts', 'armor', 50, NULL, 'Not for sale', NULL, 1, NULL, NULL, NULL, NULL, NULL, 150, 'Larger version of the Mark I armor sized for large humanoids (7 feet/2.1 m tall or taller, especially the Ojahee); same inertial shield as the Mark I. Minus 5 percent prowl penalty (good mobility) if the wearer has P.S. 24 or higher (16+ if supernatural); otherwise minus 15 percent prowl, speed halved, and all attack actions at minus 1.', 'Rifts World Book 9: South America 2 p.115'),
('np-10-plasma-net-launcher', 'NP-10 Plasma Net Launcher', 'rifts', 'weapon', 8, 20000, '20,000 credits; each replacement net-grenade costs 300 credits', 'Special: entangles the victim (4 melee actions to break free, half that for supernatural P.S. 40+), then bursts into flame for 4D6 M.D. per melee round for 1D4 rounds until the net is consumed; the entangled victim cannot strike or parry, is -2 to dodge, and moves at Spd 4', 1, '500 feet (152 m)', 'One shot only; a bandoleer holds 20 net-grenades', 'Each shot counts as one melee attack/action', NULL, NULL, NULL, 'Cordoban single-shot 50mm launcher whose missile blossoms in mid-air into a net of mega-damage metal strands studded with small plasma charges; once a target is entangled the charges ignite and burn through the net (and the victim) within a minute. Issued to Cordoba patrols and also sold to civilian hunters and wilderness scouts.', 'Rifts World Book 9: South America 2 p.163'),
('ip-7-ion-pistol', 'IP-7 Ion Pistol', 'rifts', 'weapon', 3, 15000, NULL, '2D6 M.D.', 1, '600 feet (183 m)', '12 shots', 'Standard', NULL, NULL, NULL, 'Italo Industries sidearm commonly issued to Cordoba and Santiago soldiers and Achilles militia; carried by officers and security personnel, and as a back-up gun for line soldiers.', 'Rifts World Book 9: South America 2 p.163'),
('i-9-heavy-ion-rifle', 'I-9 Heavy Ion Rifle', 'rifts', 'weapon', 8, 20000, NULL, '4D6 M.D.', 1, '2000 feet (610 m)', '20 shots', 'Standard', NULL, NULL, NULL, 'Italo Industries rifle carried by Cordoba and Santiago soldiers and other adventurers; a suspiciously high number have also turned up with Shining Path guerrillas, leading Cordoban authorities to suspect Italo Industries of selling to them.', 'Rifts World Book 9: South America 2 p.163'),
('i-11-long-gun', 'I-11 Long Gun', 'rifts', 'weapon', 28, 50000, NULL, '1D6x10 M.D. per blast', 1, '4000 feet (1220 m)', '10 shots', 'Single shots only (each counts as one melee attack)', NULL, NULL, NULL, 'Cordoba/Santiago sniper/heavy hunting rifle favored by assassins, sharpshooters and the plains ''borg, who can tote its length (almost six feet/1.8 m) and weight thanks to their cybernetic horses. Enhanced sights give +1 to strike on aimed shots.', 'Rifts World Book 9: South America 2 p.164'),
('equalizer-combat-shotgun', 'Equalizer Combat Shotgun', 'rifts', 'weapon', 10, 12000, '12,000 credits for the gun; ammunition sold per round (see damage). A Cordoban knock-off reduces the 16mm APE cartridge to 4D6 M.D. and range to 500 ft/152 m', 'Varies by cartridge: Standard 12-gauge buckshot 4D6 S.D.C. (1 credit/round); standard 12-gauge slugs 5D6 S.D.C. (2 credits/round); 16mm Armor Piercing Explosive (APE) 5D6 M.D., no blast radius (100 credits/round); 16mm Fragmentary Grenade (FG) 2D4 M.D. to a 10 ft/3.0 m blast radius (500 credits/round); 16mm Smoke, blocks vision in a 20 ft/6.1 m radius (100 credits/round); 16mm Tear Gas, save vs non-lethal poison or be blinded (-6 to strike/parry/dodge) in a 20 ft/6.1 m radius (200 credits/round)', 1, '1000 feet (305 m) for 16mm rounds, 300 feet (91.4 m) for regular shotgun rounds', 'Box magazine 10 rounds or drum magazine 20 rounds; can use either', 'Each shot counts as one melee attack; cannot fire bursts', NULL, NULL, NULL, 'Achilles Republic smooth-bore, semi-automatic shotgun firing 16mm explosive cartridges as well as regular 12-gauge shells, flares, and smoke/tear gas grenades. Rugged and water-resistant (functions after 24 hours submerged in a swamp or mud). Exported by Amaki traders from New Babylon; also bought in bulk by Santiago''s militia.', 'Rifts World Book 9: South America 2 p.164'),
('lightbringer-laser-rifle', 'Lightbringer Laser Rifle', 'rifts', 'weapon', 6, 15000, NULL, '4D4 M.D. per single blast, or 1D4x10+10 M.D. per multiple pulse burst (3 simultaneous shots)', 1, '2000 feet (610 m)', '30 shots', 'Standard', NULL, NULL, NULL, 'Achilles Republic bull-pup laser rifle with a long carrying handle running the weapon''s length, sized to let mutants with larger-than-human hands carry it comfortably. Used by about half of Achilles'' soldiers.', 'Rifts World Book 9: South America 2 p.165'),
('amaki-blast-sword', 'Amaki Blast-Sword', 'rifts', 'weapon', 4, 25000, '25,000 credits; higher for more richly decorated models', 'Plasma Discharge: 3D6 M.D. Plasma Blade: 2D6+6 M.D.', 1, 'Plasma Discharge: 500 feet (152 m). Plasma Blade: hand to hand combat', '20 shots; each shot keeps the plasma blade active for 10 minutes; once all shots are used the blade goes inert until a new E-clip is inserted', 'Equal to the number of hand to hand attacks per melee', NULL, NULL, NULL, 'New Babylon fencing weapon shaped like a blunt foil with an angled pistol-grip handle. Fires plasma discharges or holds a continuous plasma-stream blade in place with a magnetic field; light enough for fencing-style use. A status symbol among New Babylon''s middle and upper classes, often richly decorated with gold and jewels.', 'Rifts World Book 9: South America 2 p.165'),
('amaki-blast-rifle', 'Amaki Blast Rifle', 'rifts', 'weapon', 10, 20000, NULL, '6D6 M.D. per blast', 1, '2000 feet (610 m)', '15 shots', 'Single shot only', NULL, NULL, NULL, 'Standard issue rifle of the New Babylon Army, also sold in small numbers to the Empire of the Sun and the Achilles Republic. Fires an explosive packet of charged particles; richly decorated, often with a barrel shaped like a fish, snake or dragon with an open mouth for a muzzle.', 'Rifts World Book 9: South America 2 p.165'),
('amaki-tw-psi-blade', 'Amaki TW Psi-Blade', 'rifts', 'magic', 3, 30000, NULL, 'Adds 2D6 M.D. to the damage of the wielder''s psi-sword (e.g. a 5th level Mind Melter''s normal 6D6 M.D. psi-sword becomes 8D6 M.D.; a 3rd level cyber-knight''s 2D6 M.D. psi-sword becomes 4D6 M.D.)', 1, 'Hand to hand combat', 'I.S.P. cost is the same as the super-psionic power; cyber-knights and duelists must spend 2 I.S.P. per minute to activate the weapon', 'Not applicable', NULL, NULL, NULL, 'Amaki Techno-Wizard device that amplifies a psi-sword; usable only by master psionics with that power (or cyber-knights/duelists who can extend a psi-sword). Mostly wielded by Amaki Duelists. Owning one marks the user as a New Babylonian and/or Duelist, which can mean trouble elsewhere in South America.', 'Rifts World Book 9: South America 2 p.165-166'),
('atl-7-anti-tank-laser-rifle', 'ATL-7 Anti-Tank Laser Rifle', 'rifts', 'weapon', 30, 100000, '100,000 credits; poor availability', '3D6x10+20 M.D. per shot', 1, '3000 feet (914 m)', '1 shot per E-Clip', 'Single shot only; each shot empties an entire E-Clip', NULL, NULL, NULL, 'Pre-Rifts anti-armor design that dumps an entire E-clip''s energy into one shot. Requires two normal humans to carry (its barrel is heavily insulated against heat) though cyborgs and power armor troopers can use it alone; takes two melee actions to reload by hand.', 'Rifts World Book 9: South America 2 p.166'),
('gaucho-combat-armor', 'Gaucho Combat Armor', 'rifts', 'armor', 14, 40000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 45, 'Modular armor for horsemen or bike riders, padded at the back of the legs and rear for comfortable riding, with a lighter inner layer (45 M.D.C., 14 lbs/6.3 kg, -5% prowl) to which heavier outer plates can be added (100 M.D.C. total, plates add 40 lbs/18 kg, -30% prowl and -1 to all combat actions if fighting on foot while wearing the plates). Favored by plainsmen as well as guerrillas, adventurers and bandits.', 'Rifts World Book 9: South America 2 p.166'),
('battle-infantry-armor', 'Battle Infantry Armor', 'rifts', 'armor', 22, 30000, 'Black market cost, since it is standard Cordoban army issue', NULL, 1, NULL, NULL, NULL, NULL, NULL, 60, 'Cordoban army standard combat armor based on pre-Rifts military designs: solid breastplate, helmet with transparent faceplate, and vertical strips on the legs and forearms. Copies and stolen suits circulate among bandits, guerrillas and adventurers; official colors are khaki/camouflage, black market suits come painted in various colors. -15% prowl penalty (fair mobility).', 'Rifts World Book 9: South America 2 p.167'),
('armored-fatigues', 'Armored Fatigues', 'rifts', 'armor', 24, 35000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 65, 'Santiago armed forces armored uniform, a knock-off of a pre-Rifts model: reinforced jump-suit with overlapping scale armor on chest and upper arms, solid shin guards, and a fully enclosed helmet. Military versions are painted green or black; civilian models (50 M.D.C.) are sold legally with less protection. -15% prowl penalty (fair mobility).', 'Rifts World Book 9: South America 2 p.167'),
('duelist-articulated-armor', 'Duelist Articulated Armor', 'rifts', 'armor', 10, 120000, '120,000 credits; refitting a suit that belonged to someone else costs 20,000 credits', NULL, 1, NULL, NULL, NULL, NULL, NULL, 75, 'Nano-technology-manufactured Amaki armor custom-fitted to its wearer, so closely articulated it acts as a second skin with no encumbrance and no prowl penalty. Helmet designs can be customized with crests, horns, plumes and other decorations. Worn almost exclusively by Amaki duelists; close enough a fit to conceal under capes and loose robes, but cannot be worn under other body armor. Nearly as expensive as powered armor.', 'Rifts World Book 9: South America 2 p.167-168'),
('blood-rider-claw-armor', 'Blood Rider Claw Armor', 'rifts', 'armor', 18, 35000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 65, 'Stylized body armor made to look like overlapping teeth, claws or bones, most often painted red, always worn by Blood Riders; non-Blood Riders who wear it risk angering the real Blood Riders. Printed name sets the word Claw off in quotation marks. -8% prowl penalty (good mobility).', 'Rifts World Book 9: South America 2 p.168'),
('amaki-combat-armor', 'Amaki Combat Armor', 'rifts', 'armor', 20, 50000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 90, 'Heavy, thick-plated and well-articulated combat armor favored by New Babylon military forces; the helmet has a protruding lower jaw to fit the Amaki beards and usually a metallic crest down the center. Sold openly by New Babylon; some humanoid units in Achilles use it instead of their standard issue. -8% prowl penalty (good mobility).', 'Rifts World Book 9: South America 2 p.168'),
('customizable-armor', 'Customizable Armor', 'rifts', 'armor', 25, 45000, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 75, 'Achilles Republic armor built to be quickly adjusted to fit beings from 4 to 8 feet (1.2 to 2.4 m) tall, in a wide variety of widths and limb lengths, with add-ons for tails, extra limbs and wings. Used by mutant animals as well as D-Bees such as wolfen and ogres. -15% prowl penalty (fair mobility).', 'Rifts World Book 9: South America 2 p.168'),
('larhold-composite-bow', 'Larhold Composite Bow', 'rifts', 'weapon', NULL, NULL, NULL, 'Barbarian R.C.C. entry, page 186: hand to hand damage based on supernatural P.S., plus 6 M.D.; usable only by beings with supernatural P.S. 16 or higher. Larhold Shaman O.C.C. entry, page 190: hand to hand damage based on supernatural P.S., plus 3 M.D.; usable only by beings with supernatural P.S. 18 or higher, or robot P.S. 30 or higher. The two entries give different bonus damage and different minimum strength.', 1, '800 feet (244 m), both entries', NULL, NULL, NULL, NULL, NULL, 'Traditional Larhold bow made from the supernaturally tough sinews and bones of their War Bisons; so stiff that not even cyborgs can bend it, and its arrows can penetrate power armor plating.', 'Rifts World Book 9: South America 2 p.186, 190'),
('larhold-saber', 'Larhold Saber', 'rifts', 'weapon', NULL, NULL, NULL, 'Barbarian R.C.C., page 186, and Shaman O.C.C., page 190, entries agree: 2D6 M.D. plus the wielder supernatural P.S. damage. The Larhold Human Renegade O.C.C. entry, page 187, instead does 1D4 M.D. if wielded by someone without supernatural strength, or 2D6 M.D. plus supernatural P.S. damage when the wielder is charged up via the renegade Temporary Superhuman Transformation ability.', 1, 'Hand to hand combat', NULL, NULL, NULL, NULL, NULL, 'M.D. alloy saber traditionally carried by Larhold warriors and shamans, and also issued, in a weaker unpowered form, to human Larhold renegades.', 'Rifts World Book 9: South America 2 p.186-187, 190'),
('larhold-hide-armor', 'Larhold Hide Armor', 'rifts', 'armor', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 70, 'Traditional Larhold armor cured from the hide of a War Bison into M.D.C. leather breastplates, helmets and shields; -10% prowl penalty (good mobility). Standard equipment for Larhold Barbarians, Human Renegades and Shamans alike; wearers may also wear captured armor instead.', 'Rifts World Book 9: South America 2 p.186, 187, 190'),
('demon-mask', 'Demon-Mask', 'rifts', 'gear', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Bizarre demonic-design mask worn with the Shaman Robes as the true Larhold shaman symbol of office; carries a Horror Factor of 7 against Larhold or anyone who knows and fears Larhold shamans. Wearing it without being a true shaman is a capital offense among the Larhold, and another shaman can instantly detect an impostor.', 'Rifts World Book 9: South America 2 p.190'),
('ancient-enchanted-club', 'Ancient Enchanted Club', 'rifts', 'magic', NULL, NULL, NULL, '3D6 M.D. plus supernatural P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'The enchanted club most Ancients (the undead Inca R.C.C.) carry, adding mega-damage to the undead''s supernatural strength. No price printed; it is monster equipment rather than trade goods.', 'Rifts World Book 9: South America 2 p.50'),
('ancient-enchanted-poncho-and-mask', 'Ancient Enchanted Poncho and Face Mask', 'rifts', 'magic', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 120, 'The Ancients'' body armor: an enchanted poncho and face mask with 120 M.D.C. that also protects the wearer from flame attacks until it is destroyed. No price or weight printed.', 'Rifts World Book 9: South America 2 p.50'),
('pucara-stone-axe', 'Pucara Giant Stone Axe', 'rifts', 'weapon', NULL, NULL, NULL, '3D6 M.D. plus P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'A typical Pucara Red Giant weapon: a giant stone axe dealing mega-damage on top of the giant''s supernatural strength. Sized for a giant; no price or weight printed.', 'Rifts World Book 9: South America 2 p.55'),
('pucara-stone-hammer', 'Pucara Giant Stone Hammer', 'rifts', 'weapon', NULL, NULL, NULL, '4D6 M.D. plus P.S. damage', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'A typical Pucara Red Giant weapon: a giant stone hammer, heavier-hitting than the axe, dealing mega-damage on top of the giant''s supernatural strength. No price or weight printed.', 'Rifts World Book 9: South America 2 p.55'),
('pucara-stone-plate-armor', 'Pucara Stone Plate Armor', 'rifts', 'armor', 100, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 150, 'Red Giant plate armor made of solid stone, 150 M.D.C. The book says only that it weighs well over a hundred pounds (45 kg); 100 is stored as that floor. No price printed.', 'Rifts World Book 9: South America 2 p.55'),
('pucara-stone-half-plate', 'Pucara Stone Half Plate', 'rifts', 'armor', 100, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 90, 'The lighter Red Giant stone armor: half plate of solid stone, 90 M.D.C. Like the full plate it weighs well over a hundred pounds (45 kg); 100 is stored as that floor. No price printed.', 'Rifts World Book 9: South America 2 p.55');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 60 South America 2 gear rows are in' AS assertion, count(*) AS got, 60 AS want
  FROM gear WHERE slug IN ('true-inca-magic-club', 'true-inca-enchanted-spear', 'true-inca-enchanted-cloth-armor', 'holy-axe', 'amulet-of-protection', 'holy-sun-sling', 'sun-priest-holy-symbol', 'pattern-staff', 'energy-jar', 'inti-10-variable-laser-pistol', 'inti-20-variable-laser-rifle', 'illapa-1-rocket-pistol', 'illapa-5-rocket-rifle', 'gilded-body-armor', 'sinchi-body-armor', 'tb-3-tri-beam-energy-pistol', 'tb-9-auto-pistol', 'tb-prime-tri-beam-energy-rifle', 'm-100-tri-beam-crew-served-gun', 'bm-2-backpack-mortar-system', 'brl-3-backpack-rocket-launcher', 'tri-blade-energy-sword', 'fr-5-flechette-rifle', 'fra-1-flechette-auto-cannon', 'arkhon-body-armor', 'iar-20-inertia-rifle', 'iar-2-auto-pistol', 'hiar-22-heavy-i-beam-rifle', 'arp-1-plasma-assault-rifle', 'hrp-1-plasma-heavy-rifle', 'h-11a-howitzer', 'mark-i-body-armor', 'mark-ii-body-armor', 'np-10-plasma-net-launcher', 'ip-7-ion-pistol', 'i-9-heavy-ion-rifle', 'i-11-long-gun', 'equalizer-combat-shotgun', 'lightbringer-laser-rifle', 'amaki-blast-sword', 'amaki-blast-rifle', 'amaki-tw-psi-blade', 'atl-7-anti-tank-laser-rifle', 'gaucho-combat-armor', 'battle-infantry-armor', 'armored-fatigues', 'duelist-articulated-armor', 'blood-rider-claw-armor', 'amaki-combat-armor', 'customizable-armor', 'larhold-composite-bow', 'larhold-saber', 'larhold-hide-armor', 'demon-mask', 'ancient-enchanted-club', 'ancient-enchanted-poncho-and-mask', 'pucara-stone-axe', 'pucara-stone-hammer', 'pucara-stone-plate-armor', 'pucara-stone-half-plate');
SELECT 'and every one cites South America 2 by page' AS assertion, count(*) AS got, 60 AS want
  FROM gear WHERE source_book LIKE 'Rifts World Book 9: South America 2 p.%';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-south-america-2-gear.sql');
