-- Phase 2a of the NPC / bestiary work: the 29 named people the imported books stat
-- who are not gods - the first rows of notable_npcs (migration 072) and their
-- 69 attacks in stat_attacks (migration 073).
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/add-notable-npcs.sql
--
-- FOUND by listing every stat block carrying a Real/True/Greek Name line or a
-- numeric experience level (the filing rule of migration 072) in the cached
-- books, minus the gods, which are Phase 2b. Underseas' Kraken is an Alien
-- Intelligence and waits for 2b with them.
--
-- EXTRACTED by one book-extract-worker per book, every number read off a 200 dpi
-- render rather than the OCR cache - the text layers carry the digit cipher -
-- and every printed folio checked against scripts/books.json. RECONCILED by
-- book-reconcile against the renders, row by row; its corrections are applied.
--
-- WHAT A ROW HOLDS. The book's numbers for one person, as printed: combat totals
-- already include every bonus, which is why a campaign copy applies no class
-- rules over them. `skills` holds percentile skills only; W.P.s and Hand to Hand
-- are in skills_note. Magic, psionics and super powers are the book's NAMES,
-- prose by decision (2026-09-17). description, disposition and
-- natural_abilities are short paraphrases - no sentence is the book's.
--
-- BY BOOK:
--   Rifts World Book 16: Federation of Magic (9): Brethan D'zir, Coran D'zir, Leizak D'zir, Alistair Dunscon, Mestoph Denali, Kara Zayne, Dan Ironforge, K'zaa, Dragonbane
--   Revised Heroes Unlimited (5): Power Master, Task Master, Shadow Master, Brain Storm, Gold Falcon
--   Rifts World Book 22: Free Quebec (6): James Lome, Sylvain Richard, Julie Tremblay, Jean Desjardins, Robert Miller, Robert Carlye
--   Rifts World Book 14: New West (6): Gwen Severson, Jacob Whispering Wind, Essai Ramirez, Katherine Delgado, Thadius Geller, Roderick Warrington III
--   Rifts World Book 10: Juicer Uprising (2): Arthur Night, Knight Hunter
--   Rifts Dimension Book 2: Phase World (1): Knife Master

INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'brethan-dzir', 'Brethan D''zir', NULL, 'High Lord Magus, First Among Equals', 'rifts', 'Unknown; supernatural on a god-like level', '24th level Lord Magus', 24, 'Scrupulous', 'Thousands if not millions of years old', '17 feet (5.2 m) tall', 'two tons', '{"IQ":24,"ME":22,"MA":26,"PS":42,"PP":24,"PE":30,"PB":14,"Spd":25}', NULL, NULL, 16500, 8000, NULL, NULL, 15, '{"attacks":9,"initiative":6,"strike":9,"parry":9,"dodge":9,"pull":6,"roll":4}', 'critical hit natural 19-20; Knockout on natural 20; 9 physical or 3 spell attacks/melee; teleport self 98%, dimensional teleport 90%', '[{"name":"Communication skills (all)","pct":98},{"name":"Medical skills (all)","pct":98},{"name":"Science skills (all)","pct":98},{"name":"Technical skills (all)","pct":86},{"name":"Swimming","pct":98},{"name":"Climbing (dual roll 90%/80%)","pct":90},{"name":"Language: American","pct":98},{"name":"Language: Spanish","pct":98},{"name":"Language: Elven/Dragonese","pct":98},{"name":"Language: Demongogian","pct":98}]', 'Hunting (no % printed); W.P. sword, W.P. staff, W.P. blunt; literate in all languages he speaks at 98%', 'Feeds on ley line magic, no need to eat/drink; fast bio-regen; invisibility at will; keen hawk-like sight; immune to S.D.C. weapons; resists heat/cold; teleports.', 'All common spell magic in Rifts RPG and this book, levels 1-15; Good knowledge of dimensional travel; Spell Strength 17', NULL, 'Epic Scale (optional); God-like perceptions (optional); Deific Power: Create Deific Portal; Deific Power: Display Deific Omen; Deific Power: Manifestation', NULL, 'Access to rare Techno-Wizard and magical devices (will not use rune weapons, Bio-Wizard creations, or anything linked to Necromancy/Undead)', NULL, 'Calm, dignified and diplomatic leader; slow to anger but capable of great force when needed.', 'His brothers (Coran, Leizak); Residents of Dweomer City; Federation of Magic factions loyal to him', 'Grim Reapers; Lord Alistair Dunscon; Coalition States; the Undead; Necromancers; Witches', 'Eldest and public spokesman of The Three, the godlike Lords of Magic who rule Dweomer City; head of the Brotherhood of Magic.', 'Rifts World Book 16: Federation of Magic p.25');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'coran-dzir', 'Coran D''zir', NULL, 'High Lord Battler', 'rifts', 'Unknown; supernatural on a god-like level', '20th level Battle Magus', 20, 'Aberrant evil', 'Thousands if not millions of years old', '16 feet (4.9 m) tall', '1.8 tons', '{"IQ":20,"ME":21,"MA":22,"PS":53,"PP":26,"PE":32,"PB":10,"Spd":33}', NULL, NULL, 13500, 6600, NULL, NULL, 16, '{"attacks":12,"initiative":10,"strike":12,"parry":12,"dodge":12,"entangle":6,"disarm":8,"pull":8,"roll":8}', 'critical hit natural 18-20; knockout on natural 20; kick attack, jump kick, leap attack, paired weapons (up to 4); +12 to save vs Horror Factor; 12 physical or 2 spell attacks/melee; teleport self 95%, dimensional teleport 80%', '[{"name":"Espionage skills (all)","pct":92},{"name":"Military skills (all)","pct":92},{"name":"Rogue skills (all)","pct":92},{"name":"Wilderness skills (all)","pct":84},{"name":"Lore skills (all)","pct":84},{"name":"Language: American","pct":98},{"name":"Language: Spanish","pct":98},{"name":"Language: Elven/Dragonese","pct":98},{"name":"Language: Demongogian","pct":98}]', 'All W.P.s at 15th level; literate in all languages he speaks at 98%', 'Feeds on ley line magic, no need to eat/drink; fast bio-regen; invisibility at will; keen hawk-like sight; immune to S.D.C. weapons; resists heat/cold; teleports.', 'All combat/offensive spells levels 1-15; All metamorphosis, flying, teleportation and dimension spells; Spell Strength 15', NULL, 'Epic Scale (optional); God-like perceptions (optional); Deific Power: Hellfire Blasts; Deific Power: Forge Holy Weapon; Deific Power: Manifestation', NULL, 'Battle Sword: giant (8ft/2.4m) mystic sword, 2D4x10 M.D. (+100 M.D. vs gods/alien intelligences), casts spells as an 8th-level fire warlock (Lower Temperature, River of Lava, Fire Whip, Flame of Life; 6 total/24hr), Fire Ball 1D6x10 M.D. at 2000ft (610m), indestructible; Armor of Flames: 1500 M.D.C. (regen 250 M.D.C./24hr), grapple damage, only worn in battle', NULL, 'Ruthless militant strategist and deadliest fighter of The Three; capable of compassion toward allies.', 'His brothers; Residents of Dweomer City; Any who fight his enemies', 'Grim Reapers; Lord Alistair Dunscon; Coalition States; the Undead; Necromancers; Witches', 'Combat-focused member of The Three, styled the Avenger; Dweomer''s chief enforcer and deadliest fighter.', 'Rifts World Book 16: Federation of Magic p.26-27');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'leizak-dzir', 'Leizak D''zir', NULL, 'High Lord Creator', 'rifts', 'Unknown; supernatural on a god-like level', '15th level High Magus, 12th level Stone Master, 9th level Temporal Wizard', 15, 'Unprincipled', 'Thousands if not millions of years old', '17 feet (5.2 m) tall', '1.7 tons', '{"IQ":26,"ME":28,"MA":20,"PS":40,"PP":24,"PE":28,"PB":10,"Spd":20}', NULL, NULL, 12000, 7400, NULL, NULL, 15, '{"attacks":7,"initiative":4,"strike":6,"parry":5,"dodge":5,"pull":4,"roll":4}', 'critical hit natural 19-20; +8 to save vs Horror Factor; 7 physical or 3 spell attacks/melee; teleport self 98%, dimensional teleport 96%', '[{"name":"Communication skills (all)","pct":98},{"name":"Science skills (all)","pct":98},{"name":"Mechanical skills (all)","pct":98},{"name":"Technical skills (all)","pct":80},{"name":"Electrical skills (all)","pct":80},{"name":"Rogue skills (all)","pct":80},{"name":"Pilot boats/ships","pct":90},{"name":"Horsemanship: Knight","pct":90},{"name":"Language: American","pct":98},{"name":"Language: Spanish","pct":98},{"name":"Language: Faeriespeak","pct":98},{"name":"Language: Elven/Dragonese","pct":98},{"name":"Language: Demongogian","pct":98}]', 'Pilot-related skills at 90%; W.P. sword, W.P. knife, W.P. revolver, W.P. energy pistol all at 14th level; literate in all languages he speaks at 98%', 'Feeds on ley line magic, no need to eat/drink; fast bio-regen; invisibility at will; keen hawk-like sight; immune to S.D.C. weapons; resists heat/cold; teleports.', 'All spells levels 8-15; All creation, transformation and illusion spells; All stone magic; All Temporal Magic; Spell Strength 17', NULL, 'Epic Scale (optional); God-like perceptions (optional); Deific Power: Create Deific Portal; Deific Power: Forge Holy Weapon; Deific Power: Weaponwright; Deific Power: Transmutation', NULL, 'Access to rare Techno-Wizard and magical devices (will not use rune weapons, Bio-Wizard creations, or anything linked to Necromancy/Undead)', NULL, 'Quiet, analytical and patient; most cerebral, least battle-oriented of the three; a devoted teacher.', 'His brothers; Residents of Dweomer City; Federation of Magic factions who accept him', 'Grim Reapers; Lord Alistair Dunscon; Coalition States; the Undead; Necromancers; Witches', 'Most scholarly of The Three; mentors Dweomer''s High Magi and safeguards the city''s magical concealment and defenses.', 'Rifts World Book 16: Federation of Magic p.27');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'alistair-dunscon', 'Alistair Dunscon', 'Alistair Winston Dunscon', 'Lord Dunscon, "the Mad"', 'rifts', 'Once human, now immortal (quasi-supernatural)', '10th level Ley Line Walker and 8th level Shifter', 10, 'Diabolic', '105 (appears to be in his 30s)', '5 feet, 11 inches tall (1.75 m)', '150 lbs. (67.5 kg)', '{"IQ":28,"ME":13,"MA":17,"PS":11,"PP":20,"PE":17,"PB":16,"Spd":14}', NULL, NULL, 58, 1458, NULL, NULL, 14, '{"attacks":4,"initiative":2,"strike":4,"parry":6,"dodge":6,"pull":2,"roll":4}', 'Critical strike on 19-20; body flip/throw; +3 to save vs psionic attack; +1 to save vs magic; had 79 H.P./36 S.D.C. before becoming immortal (now a 58 M.D.C. creature)', '[{"name":"Language: American","pct":98},{"name":"Language: Dragonese/Elven","pct":98},{"name":"Language: Demongogian","pct":90},{"name":"Language: Spanish","pct":98},{"name":"Language: Gobblely","pct":98}]', 'All Ley Line Walker O.C.C. skills at 98%, all Shifter O.C.C. skills at 90%; all lore, history, science and computer skills (incl. hacking); read sensory equipment, basic electronics/mechanics, pilot hover vehicle/cycle, horsemanship (general), all communication skills at 90%; W.P. staff & W.P. energy pistol 10th level, W.P. knife & W.P. energy rifle 8th level; hand to hand basic 10th level', 'Immortal: impervious to S.D.C. weapons, disease, poison, radiation, possession; resists cold/heat/fire; fast bio-regen; resists mind control; must drain P.P.E. from a sentient sacrifice weekly to survive.', 'All spell magic (Rifts RPG and this book); All Necromancer Magic; Excellent understanding of Bio-Wizardry, Bio-Wizard devices and symbiotes; Spell Strength 15', NULL, NULL, NULL, 'Bio-Wizard symbiotes, weapons and devices; Daemonfist: greatest rune staff, Diabolic alignment IQ18, 1D6x10 M.D./blow, Soul Drinker, wielder''s spells cast 3 levels higher, Summon Demons (1D4/day, 10 min/level), Blood Ritual (sacrifice 4 sentients to summon demons); Skin of the Demon: living Bio-Wizard armor, 300 M.D.C. (regen 4D6 M.D.C./min), half damage from fire/plasma; Soul Bottle: spirit-torture device; Bands of Denial: blocks armor-piercing spells entirely; assorted standard and Techno-Wizard magic items', 'Treasure trove worth 40+ million credits, 10 million Universal credits, plus wealth of his Kingdom and the City of Brass', 'Megalomaniacal and hate-driven; calculating, cruel and sadistic, tempered by a twisted sense of humor.', 'Demons (in general); the Grim Reapers; Lord Splynncryth of Atlantis', 'Prosek family; Coalition States; Lords of Magic; Dweomer City; rival Brotherhoods of magic', 'Immortal, demon-empowered ruler of the True Federation of Magic and the City of Brass; obsessive rival of the Lords of Magic.', 'Rifts World Book 16: Federation of Magic p.40-41');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'mestoph-denali', 'Mestoph Denali', 'Bridget Daniels', 'Demonic Advisor; Mestoph the Enforcer, Mestoph the Black', 'rifts', 'Once human, now a Hidden Corrupt; supernatural being', '9th level Corrupt', 9, 'Diabolic', 'Approximately 200 (appears early 30s)', '6 feet, 8 inches (2 m)', '180 pounds (81 kg) of muscle', '{"IQ":12,"ME":17,"MA":12,"PS":36,"PP":23,"PE":20,"PB":13,"Spd":45}', NULL, NULL, 101, 95, NULL, NULL, 15, '{"attacks":7,"initiative":4,"strike":8,"parry":4,"dodge":4,"pull":6,"roll":4}', '+2 to save vs magic; impervious to poison, toxins, drugs, disease; resistant to cold, heat, fire (half damage); +6 to save vs Horror Factor; never fatigues; horror factor listed as 15 specifically ''as one of Dunscon''s Advisors''', '[{"name":"Camouflage","pct":60},{"name":"Recognize weapon quality","pct":65},{"name":"Demolitions","pct":84},{"name":"Demolitions disposal","pct":84},{"name":"Escape artist","pct":70},{"name":"Intelligence","pct":64},{"name":"Tracking","pct":85},{"name":"Wilderness survival","pct":80},{"name":"Palming","pct":60},{"name":"Pick pockets","pct":65},{"name":"Seduction","pct":54},{"name":"Streetwise","pct":62},{"name":"Horsemanship: Exotic","pct":80},{"name":"Language: Demongogian","pct":98},{"name":"Language: American","pct":98},{"name":"Basic math","pct":90}]', 'W.P. knife, W.P. blunt, W.P. energy rifle, W.P. heavy energy weapon', 'Standard Corrupt abilities; impervious to poison/toxins/disease, resists elements, never fatigues.', 'Shadow Meld; Levitate; Agony; Blind; Shatter; Mystic Fulcrum; Aura of Power', NULL, NULL, NULL, 'Laser scalpels; Vibro-Blades; electro-stunners; various CS energy weapons; Black Halberd (favorite): magical polearm, 6D6 M.D., hurled to 1000 ft (305 m), double damage to good-aligned supernatural beings', 'Personal treasure trove of gems/jewelry worth 8+ million credits, plus half a million in universal credits', 'Vengeful, bloodthirsty and sadistic; blames others, especially men, for her misfortunes.', 'Lord Dunscon; other council members; other Corrupt', 'Pretty much everyone else', 'A rare ''Hidden'' Corrupt who retained her human personality; Dunscon''s Enforcer, leading brutal raids and punitive squads.', 'Rifts World Book 16: Federation of Magic p.43-44');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'kara-zayne', 'Kara Zayne', NULL, 'Head of the Mystic Triad', 'rifts', NULL, '8th level Lord Magus', 8, 'Scrupulous', '31, but looks 23 - ages one year for every five', '5 feet, 5 inches tall (1.67 m)', '130 lbs. (59 kg)', '{"IQ":24,"ME":17,"MA":15,"PS":14,"PP":23,"PE":23,"PB":14,"Spd":12}', NULL, NULL, 46, 172, 30, NULL, NULL, '{"attacks":5,"initiative":2,"strike":6,"parry":7,"dodge":7,"pull":3,"roll":3}', '+4 to save vs mind control; +1 to save vs psionics; +4 to save vs Horror Factor; +2 to save vs illusions; +6 to save vs magic; +4 to save vs poison & disease; critical strike on 19-20; body flip/throw; +5% to save vs coma & death; fatigues at half rate; holds breath 3 min; +5% balance', NULL, 'All skills standard for Lord Magus O.C.C.', 'Standard Lord Magus O.C.C. abilities; fatigues at half rate, holds breath 3 minutes, good balance and coordination.', 'Standard Lord Magus spells; Spell Strength 14', 'Sense evil; Sense magic; See aura; Mind block; Astral projection; Object read; See the invisible', NULL, NULL, 'Magic armor; Battle Fury sword', NULL, 'Idealistic, friendly and self-sacrificing; struggles to keep her humanity and stay connected to ordinary people.', 'Fellow Mystic Triad members; Citizens of Magestar and Dweomer City; the Cyber-Knights', 'The Coalition; Grim Reapers; Necromancers', 'Youngest-ever Lord Magus trainee who left Dweomer City''s isolationism to found Magestar and lead the Mystic Triad.', 'Rifts World Book 16: Federation of Magic p.54-55');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'dan-ironforge', 'Dan Ironforge', 'Dannythelgon Ironforge', 'High Magus of the Mystic Triad', 'rifts', 'Dwarf', '6th level High Mage', 6, 'Scrupulous', '44', '3 feet, 10 inches tall (1.17 m)', '170 lbs. (67.5 kg)', '{"IQ":20,"ME":15,"MA":9,"PS":16,"PP":22,"PE":19,"PB":9,"Spd":11}', 39, 38, NULL, 128, NULL, NULL, NULL, '{"attacks":5,"initiative":2,"strike":8,"parry":9,"dodge":9,"pull":2,"roll":3}', 'Critical strike on natural 19-20; +5 to save vs magic; +2 to save vs poison; +3 to save vs mind control; +3 to save vs Horror Factor; fatigues at half rate; holds breath ~3 min; good balance; nightvision 90 ft (27m); +5% on mechanical, military, electrical, computer skills', '[{"name":"Dwarven","pct":98},{"name":"Language: American","pct":98},{"name":"Magic Lore","pct":95},{"name":"Demon Lore","pct":75},{"name":"Faerie Lore","pct":65},{"name":"Carpentry","pct":80},{"name":"Basic Mechanics","pct":80}]', 'W.P. Staff, Hand to Hand: Basic', 'Dwarven nightvision 90 ft; +5% mechanical/military/electrical/computer skills; fatigues at half rate; good balance.', 'Standard High Magus spells; Spell Strength 13', NULL, NULL, NULL, 'Quite a collection of weapons and equipment (unspecified; prefers to create items rather than carry them)', NULL, 'Good-natured, industrious daydreamer; grumbles about Council duties but secretly enjoys building Magestar.', 'Dweomer City; the Lords of Magic; Cyber-Knights; citizens of Magestar', 'The Coalition; Grim Reapers; Necromancers', 'Dwarven High Mage and master craftsman of magic items; member of the Mystic Triad and Magestar''s Town Council.', 'Rifts World Book 16: Federation of Magic p.57');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'kzaa', 'K''zaa', 'Kyarennzaa Distorynn', 'Master of Stormspire', 'rifts', 'Lizard Mage', '14th level Ley Line Walker, 10th level Techno-Wizard', 14, 'Aberrant evil', '374 years', '7 feet (2.1 m) tall', '250 lbs. (112.5 kg)', '{"IQ":22,"ME":20,"MA":15,"PS":21,"PP":22,"PE":14,"PB":6,"Spd":12}', NULL, NULL, 900, 2200, 152, NULL, 17, '{"attacks":5,"initiative":2,"strike":8,"parry":8,"dodge":8}', '+4 to save vs magic', '[{"name":"Language: Dragonese/Elven","pct":98},{"name":"Dwarven","pct":98},{"name":"Wolfen","pct":98},{"name":"Language: Demongogian","pct":98},{"name":"Language: American","pct":98},{"name":"Language: Spanish","pct":98},{"name":"Recognize magic items","pct":80},{"name":"Recognize precious metals/stones","pct":80},{"name":"Read mystic symbols","pct":98},{"name":"Recognize enchantment","pct":98},{"name":"Recognize magic circles","pct":98},{"name":"Magic Lore","pct":98},{"name":"Demon Lore","pct":98},{"name":"Faerie Lore","pct":98}]', NULL, 'Keen vision, sharp hearing, warm-blooded.', 'All power words, all wards, all circles of protection; Summoning Circles (elementals, serpents, greater demons); Power Circles: Dimensional Rift, Force, Death, Power, Power Matrix, Teleport; All Ley Line Walker spells levels 1-15', 'All sensitive and physical psionic powers; Deaden pain; Psychic surgery; Psychic diagnosis; Bio-manipulation; Super regeneration; Telemechanics; Electrokinesis', NULL, NULL, 'Huge trove of magical items, especially Techno-Wizard devices (no fixed favorite)', NULL, 'Amoral but good-humored merchant-wizard; friendly and cheerful so long as things go his way; prefers subtle vengeance over violence.', 'The Federation of Magic (loosely); Denizens of Stormspire; the Grim Reapers; Society of Sages', 'Lord Dunscon and his True Federation of Magic; the Coalition; the Splugorth (business rival)', 'Wealth-obsessed Lizard Mage Techno-Wizard who rules Stormspire, the Megaverse''s leading Techno-Wizard manufacturing city.', 'Rifts World Book 16: Federation of Magic p.61-62');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'dragonbane', 'Dragonbane', 'Philip Montgomery', NULL, 'rifts', NULL, '10th level Dragon Juicer', 10, 'Aberrant', '29; three years as a Dragon Juicer', '6 feet (1.8 m)', '210 lbs. (94.5 kg), all muscle', '{"IQ":10,"ME":12,"MA":10,"PS":32,"PP":24,"PE":25,"PB":12,"Spd":65}', NULL, NULL, 245, 70, NULL, NULL, NULL, '{"attacks":8,"initiative":4,"strike":7,"parry":11,"dodge":11,"roll":8}', '+21 S.D.C. damage; critical strike on 19-20; Knockout/stun on 17-20; +40% save vs coma/death; +11 to save vs toxins; +5 to save vs magic; +2 to save vs psionics; +4 to save vs mind control; +5 to save vs Horror Factor; automatic parry or dodge on all attacks', '[{"name":"Swimming","pct":98},{"name":"Horsemanship: Exotic","pct":70},{"name":"Language: American","pct":98},{"name":"Language: Dragonese/Elven","pct":98}]', 'W.P. energy rifle, W.P. sword, W.P. heavy energy, W.P. axe; Hand to Hand: Assassin, Boxing, Wrestling', 'Supernatural strength/endurance; long leaps (20ft by 40ft); automatic parry/dodge; nightvision 100ft, hawk-like vision, keen smell; sees the invisible; immune to disease/normal heat/cold; fast bio-regen; sustained by ancient dragon blood.', NULL, NULL, NULL, NULL, NULL, NULL, 'Loyal, stoic bodyguard who kills without glee or remorse, simply doing what''s necessary.', 'K''zaa, Lord of Stormspire', NULL, 'K''zaa''s loyal bodyguard and first successful Dragon Juicer; hunts dangerous dragons and dinosaurs on his master''s orders.', 'Rifts World Book 16: Federation of Magic p.62');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'power-master', 'Power Master', 'Roger Monroe', NULL, 'heroes-unlimited', 'Mutant', 'Criminal (extortionist, terrorist)', 2, 'Miscreant', '20', '6ft 8in', '250lbs', '{"IQ":8,"ME":9,"MA":7,"PS":24,"PP":9,"PE":12,"PB":14,"Spd":8}', 19, 96, NULL, NULL, NULL, NULL, NULL, '{"attacks":5}', '+10% to skills (Scholastic Bonus); +9 to damage (from P.S. 24)', '[{"name":"Auto Mechanics","pct":66},{"name":"Mechanical Engineer","pct":65},{"name":"Locksmith","pct":45},{"name":"Swimming","pct":76},{"name":"Dance","pct":52},{"name":"Cook","pct":62},{"name":"Pilot: Auto","pct":88},{"name":"Pilot: Auto, Race Car","pct":65},{"name":"Pilot: Small Truck","pct":68}]', 'Math: Basic, Boxing, Wrestling, Hand to Hand: Expert, Body Building, General Athletics, W.P. Blade, W.P. Blunt', 'Mutant with light/energy manipulation, energy resistance, bent light, enhanced vision, and a stocky, unusually strong physique.', NULL, NULL, 'Energy Expulsion: Light; Energy Expulsion: Energy; Energy Resistance; Bend Light; Advanced Vision; Unusual Physical Trait: Stocky/Broad', NULL, NULL, NULL, 'Arrogant, reckless bully who believes his body is the ultimate weapon; cheats and shows off in combat.', 'Shadow Master (Crime Masters, contemptuous rivalry); Task Master (Crime Masters, feared)', NULL, 'Mutant enforcer for the Crime Masters, immensely strong and broad-framed, guarding the mall''s main entrance during the hostage extortion.', 'Revised Heroes Unlimited p.233-234');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'task-master', 'Task Master', 'John Talbot', NULL, 'heroes-unlimited', 'Special Training', 'Mercenary', 7, 'Diabolic', '46', '5ft 8in', '170lbs', '{"IQ":12,"ME":13,"MA":11,"PS":16,"PP":11,"PE":14,"PB":15,"Spd":16}', 38, 46, NULL, NULL, NULL, NULL, NULL, '{"attacks":5}', '+15% to skills (Scholastic Bonus)', '[{"name":"Math: Basic","pct":98},{"name":"Biology","pct":98},{"name":"Sculpture","pct":95},{"name":"Computer Operation","pct":98},{"name":"Swim: Basic","pct":98},{"name":"Explosives (dual roll 80%/70%)","pct":80},{"name":"Investigative","pct":85},{"name":"Escape Artist","pct":88},{"name":"Prowl","pct":85},{"name":"Tracking (dual roll 85%/80%)","pct":85},{"name":"Disguise","pct":65},{"name":"Electronics: Basic","pct":75},{"name":"Pick Pockets","pct":60},{"name":"Pilot: Auto","pct":98},{"name":"Pilot: Airplane","pct":84},{"name":"First Aid","pct":68}]', 'Hand to Hand: Assassin, Athletics, Running, Body Building, W.P. Automatic Pistol, W.P. Rifle', 'No super powers; a trained human mercenary/sniper relying on skill, weapons and physical conditioning.', NULL, NULL, NULL, NULL, 'Sap Glove (lead lined, +2 to damage); Utility belt; .45 Colt; 9mm P5 Walther Mini-Uzi; 7.62mm G3 sniper rifle (Heckler and Koch); 8 throwing knives; Rifle-launched grenades; Smoke pellets; Night sight goggles (built into riot helmet)', NULL, 'Calm, professional killer who enjoys the hunt and shows no regard for others'' lives; the perfect hired gun.', 'Shadow Master (hired him, working relationship); Power Master (Crime Masters, but slaps him down often)', NULL, 'Handsome, white-haired veteran mercenary and de facto second-in-command of the Crime Masters, hired by Shadow Master; guards a side entrance.', 'Revised Heroes Unlimited p.234-235');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'shadow-master', 'Shadow Master', 'Jason Camtatka', NULL, 'heroes-unlimited', 'Experiment/Darkness Control', 'Criminal', 6, 'Miscreant', '30', '6ft', '190lbs', '{"IQ":23,"ME":12,"MA":11,"PS":13,"PP":12,"PE":13,"PB":12,"Spd":10}', 41, 48, NULL, NULL, NULL, NULL, NULL, '{"attacks":5}', '+8% +10% I.Q. bonus (Scholastic Bonus); Note: +10% on all skills from I.Q. bonus', '[{"name":"Math: Basic","pct":98},{"name":"Math: Advanced","pct":98},{"name":"Computer Operation","pct":98},{"name":"Photography","pct":98},{"name":"Writing","pct":92},{"name":"Art (draw)","pct":96},{"name":"Auto Mechanic (dual roll 72%/53%)","pct":72},{"name":"Computer Programming","pct":72},{"name":"Disguise","pct":62},{"name":"Electronics","pct":72},{"name":"Forgery","pct":52},{"name":"Pick Pockets","pct":65},{"name":"Pick Locks","pct":66},{"name":"Pilot: Auto","pct":98},{"name":"Pilot: Motorcycle","pct":98},{"name":"Pilot: Airplane","pct":98}]', 'Chemistry, Chemistry: Analytical, W.P. Automatic Pistol', 'Experiment-derived darkness control power category; no separate ability breakdown printed beyond the category name.', NULL, NULL, 'Darkness Control', NULL, '.45 Colt; .22 Erma Olympia; 2 knives; 2 smoke pellets; Gas filter-nose and mouth piece', NULL, 'Cold, brilliant, and ruthless leader with little real loyalty to his crew; prepared to kill hostages to escape.', 'Task Master (quiet working relationship); Power Master (subordinate, viewed with contempt)', NULL, 'Genius leader of the Crime Masters with an experiment-derived darkness power; masterminds the mall hostage extortion and guards the captives.', 'Revised Heroes Unlimited p.235');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'brain-storm', 'Brain Storm', 'Jeff Erickson', NULL, 'heroes-unlimited', 'Natural Psionic', 'Comic Shop Clerk', 2, 'Unprincipled', '18', '5ft 10in', '160lbs', '{"IQ":12,"ME":19,"MA":15,"PS":17,"PP":11,"PE":20,"PB":15,"Spd":12}', 24, 47, NULL, NULL, 62, NULL, NULL, '{"attacks":3}', '+12% to skills (Scholastic Bonus)', '[{"name":"Math: Basic","pct":98},{"name":"Math: Advanced","pct":72},{"name":"Chemistry","pct":70},{"name":"Chemistry: Analytical","pct":65},{"name":"Swimming: Basic","pct":76},{"name":"Swimming: Advanced","pct":70},{"name":"Fishing","pct":60},{"name":"Pilot: Automobile","pct":88},{"name":"Pilot: Motorcycle","pct":68},{"name":"Pilot: Sailboat","pct":68},{"name":"Pilot: Motorboat","pct":68},{"name":"Navigation","pct":54}]', 'Boxing, Hand to Hand: Basic, Athletics: General, Body Building', 'Newly-manifested natural psionic with telekinesis, hydrokinesis, and bio-regeneration, plus minor psychic senses; untrained in combat use of his powers.', NULL, 'major abilities: Telekinesis, Hydrokinesis, Bio-Regeneration; secondary abilities: See Aura, Sixth Sense, Detect Psionics, Alter Aura, Object Read, Death Trance', NULL, NULL, NULL, NULL, 'Frightened, reluctant college freshman coerced into villainy by blackmail; fights defensively unless cornered.', NULL, 'Gold Falcon (blackmailing him)', '18-year-old University of Las Vegas freshman whose new psionic powers were discovered by Gold Falcon, who blackmails him into staging a fake Hoover Dam threat.', 'Revised Heroes Unlimited p.236-237');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'gold-falcon', 'Gold Falcon', 'Steve Douglas', NULL, 'heroes-unlimited', 'Experiment (accidental)', 'Seven-Eleventeen night clerk, opportunist', 2, 'Miscreant', '28', '6ft 1in', '190lbs', '{"IQ":10,"ME":9,"MA":14,"PS":14,"PP":15,"PE":8,"PB":13,"Spd":10}', 9, 81, NULL, NULL, NULL, NULL, NULL, '{"attacks":4}', '+5% to skills (Scholastic Bonus)', '[{"name":"Math: Basic","pct":98},{"name":"Computer Programming","pct":75},{"name":"Computer Operation","pct":55},{"name":"Writing: Creative","pct":30},{"name":"Pilot: Automobile","pct":88},{"name":"Pilot: Motorcycle","pct":68},{"name":"Pilot: Truck","pct":68},{"name":"Pick Locks","pct":45},{"name":"Pick Pockets","pct":40}]', 'Acrobatics, Gymnastics, Hand to Hand: Expert, Swimming: Basic, General Athletics, Prowl, W.P. Knife, W.P. Revolver', 'Accidental radiation exposure gave him electrical-field projection, gliding flight, heightened hearing, and enhanced vision.', NULL, NULL, 'Energy Expulsion: Electrical Field; Flight: Glide; Heightened Sense of Hearing; Super Vision: Advanced Sight', NULL, '.45 Colt (plus 36 extra bullets); 2 knives; 4 high explosive grenades; 2 grey smoke grenades; 1 canister of tear gas', NULL, 'Solitary, mean-spirited bully; cocky, overconfident, and willing to betray an accomplice to save himself.', 'Brain Storm/Jeff Erickson (coerced accomplice); unnamed henchmen', 'police', 'Convenience-store clerk turned petty criminal after a leaking store microwave gave him powers; plans an armored-car heist using Jeff Erickson as a diversion.', 'Revised Heroes Unlimited p.237');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'james-lome', 'James Lome', NULL, 'Prime Minister of Free Quebec', 'rifts', NULL, '10th level Scholar/Politician/Leader', 10, 'Aberrant', '48', '6 feet, 1 inch (1.84 m)', '185 lbs (83 kg)', '{"IQ":21,"ME":17,"MA":26,"PS":15,"PP":17,"PE":20,"PB":15,"Spd":19}', 56, 22, NULL, 14, NULL, NULL, NULL, '{"attacks":6,"initiative":6,"strike":3,"parry":5,"dodge":6,"roll":2,"damage":3}', '+7% to skills, +1 save vs insanity/psionics, 70% to trust/intimidate, +3 save vs Magic, +10% save vs coma/death, critical strike on 18-20', '[{"name":"Literacy: American","pct":98},{"name":"Literacy: Old French","pct":98},{"name":"Language: American","pct":98},{"name":"Language: Spanish","pct":98},{"name":"Language: Old French","pct":98},{"name":"Language: Techno-Can","pct":98},{"name":"Language: Euro","pct":98},{"name":"Basic Math","pct":98},{"name":"Advanced Math","pct":98},{"name":"Radio: Basic","pct":98},{"name":"Computer Operations","pct":98},{"name":"Pilot Automobile","pct":95},{"name":"Pilot Hover Craft","pct":98},{"name":"Lore: Demons and Monsters","pct":97},{"name":"Lore: D-Bees and Magic","pct":97},{"name":"Writing","pct":97},{"name":"Anthropology","pct":82},{"name":"Intelligence","pct":75},{"name":"Prowl","pct":77},{"name":"Streetwise","pct":56},{"name":"Land Navigation","pct":72},{"name":"Wilderness Survival","pct":67}]', 'Hand to Hand: Expert (10th level); W.P. E-Pistol, W.P. Knife, W.P. E-Rifle (10th level), W.P. Blunt (3rd level)', NULL, NULL, NULL, NULL, 'Amplified hearing and sound filtration; Toxic filter', 'Vibro-Knife (hip-sheath); Wilk''s 320 Laser Pistol; Wilk''s 457 rifle (favorite); T-40 "Plain-Clothes" business suits/tuxedos/coats; QEBA-10 Body Armor (80 M.D.C., field/speeches only)', NULL, 'Demanding, charismatic leader; forgives one failure but never a second; ruthless strategist who hates failure.', NULL, NULL, 'Ten-year Prime Minister of Free Quebec; a war-veteran politician credited with the nation''s military buildup and secession from the Coalition States.', 'Rifts World Book 22: Free Quebec p.142');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'sylvain-richard', 'Sylvain Richard', 'Sylvain Joseph Richard', 'Radio Personality', 'rifts', NULL, '6th level City Rat', 6, 'Anarchist with delusions of self-importance', '27', '5 feet, 10 inches (1.78 m)', '160 lbs (72 kg)', '{"IQ":14,"ME":12,"MA":24,"PS":13,"PP":19,"PE":11,"PB":17,"Spd":31}', 39, 18, NULL, 7, NULL, NULL, NULL, '{"attacks":5,"strike":4,"parry":6,"dodge":6,"roll":6}', 'critical strike on natural 18-20; 80% to trust/intimidate; 35% to charm/impress', '[{"name":"Streetwise","pct":60},{"name":"Language: American","pct":98},{"name":"Radio: Basic","pct":80},{"name":"Pilot Motorcycle","pct":95},{"name":"Pilot Automobile","pct":80},{"name":"Basic Math","pct":80},{"name":"Prowl","pct":70},{"name":"Find Contraband, Weapons and Cybernetics","pct":61},{"name":"Computer Operation","pct":75},{"name":"Writing","pct":60},{"name":"Literacy","pct":65}]', 'Hand to Hand: Martial Arts (6th level); W.P. Knife; W.P. Energy Pistol; Acrobatics; Athletics; Running', NULL, NULL, NULL, NULL, NULL, 'Vibro-Knife; C-18 Laser Pistol; Plain-Clothes leather jacket with M.D.C. padding (A.R. 10, M.D.C. 12)', NULL, 'Charismatic, naive true-believer radio celebrity; enjoys debate and adoration, easily led by those he trusts.', 'Julie Tremblay; Prime Minister James Lome', 'Coalition States / Emperor Prosek (on CS most-wanted list)', 'Third-generation radio celebrity and C.F.Q.C. part-owner, unwittingly used by PM Lome as a propaganda mouthpiece against the Coalition.', 'Rifts World Book 22: Free Quebec p.145');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'julie-tremblay', 'Julie Tremblay', 'Julie Marie Tremblay', 'Official Radio Correspondent (Captain)', 'rifts', NULL, '6th level CS Military Specialist', 6, 'Scrupulous', '25', '5 feet, 10 inches (1.78 m)', '150 lbs, all muscle (67.5 kg)', '{"IQ":14,"ME":17,"MA":24,"PS":15,"PP":19,"PE":12,"PB":15,"Spd":14}', 39, 18, NULL, 7, NULL, NULL, NULL, '{"attacks":5,"initiative":6,"strike":4,"parry":7,"dodge":9,"roll":2}', 'pin/incapacitate on natural 18-20; critical strike on natural 18-20; 80% to trust/intimidate', '[{"name":"Radio Basic","pct":80},{"name":"Literacy","pct":65},{"name":"Language: American","pct":98},{"name":"Computer Operations","pct":85},{"name":"Intelligence","pct":62},{"name":"Pilot Hover Craft","pct":85},{"name":"Pilot Robots and Power Armor","pct":71},{"name":"Read Sensory Instruments","pct":70},{"name":"Pick Locks","pct":65},{"name":"Wilderness Survival","pct":65},{"name":"Escape Artist","pct":65},{"name":"Detect Ambush","pct":65},{"name":"Parachuting","pct":85},{"name":"Military Etiquette","pct":80},{"name":"Play Musical Instrument (clarinet)","pct":70}]', 'Hand to Hand: Expert (5th level); Robot Combat: Elite (SAMAS); Boxing; Wrestling; W.P. Energy Pistol; W.P. Energy Rifle; W.P. Knife', NULL, NULL, NULL, NULL, 'Amplified hearing and sound filtration system; Toxic filter; Artificial spleen (bio-system replacement, accidental injury)', 'Vibro-Knife (worn at all times); C-18 Laser Pistol; C-12 Laser Rifle; "Plain Clothes" Armor (28 M.D.C.); Standard Military body armor (80 M.D.C.)', NULL, 'Confident, disciplined career officer and perfectionist; mildly resents the attention Sylvain Richard receives.', 'Sylvain Richard; Prime Minister James Lome', 'Coalition propaganda machine (branded her a traitor)', 'National Assembly''s official radio correspondent and a CS Military Specialist Captain, appointed to steer Sylvain Richard''s broadcasts.', 'Rifts World Book 22: Free Quebec p.146-147');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'jean-desjardins', 'Jean Desjardins', NULL, '"Franko" - Lunatic Visionary', 'rifts', NULL, '9th level Wilderness Scout', 9, 'Miscreant', '37', '6 feet (1.8 m)', '175 lbs (78.75 kg)', '{"IQ":16,"ME":20,"MA":21,"PS":14,"PP":18,"PE":16,"PB":12,"Spd":19}', 52, 54, NULL, 7, NULL, NULL, 10, '{"attacks":7,"initiative":6,"strike":4,"parry":9,"dodge":10,"roll":4}', 'Horror/Awe Factor 15 to those in his organization; critical strike on 18-20; +3 save vs psionic attack; 65% to trust/intimidate; mild schizophrenic (paranoia, delusions, obsession)', '[{"name":"Cooking","pct":80},{"name":"Climbing","pct":98},{"name":"Language: American","pct":98},{"name":"Language: Dragonese/Elven","pct":98},{"name":"Language: Techno-Can","pct":98},{"name":"Language: Inuit","pct":98},{"name":"Land Navigation","pct":88},{"name":"Horsemanship","pct":92},{"name":"Identify Plants","pct":85},{"name":"Fishing","pct":90},{"name":"Prowl","pct":85},{"name":"Track Animals","pct":80},{"name":"Wilderness Survival","pct":90},{"name":"Pilot Hover Vehicle","pct":90},{"name":"Disguise","pct":75}]', 'Climbing also 90% rappel ("98%/90%"); Hand to Hand: Expert (9th level); Boxing; Sniper; W.P. Knife, W.P. Energy Rifle, W.P. Energy Pistol (all 9th level)', NULL, NULL, NULL, NULL, 'Amplified hearing and sound filtration (bionic); Gyro-compass and clock calendar (bionic)', 'L-20 laser pulse rifle; Wilk''s 320 Laser Pistol; Vibro-Knife (1D6 M.D.); Survival knife; NG-S2 survival pack; Infrared distancing binoculars; Thermo-imaging rifle scope; 2 smoke grenades; 2 fragmentation grenades; Huntsman body armor (60 M.D.C.)', '1000 credits; 12,000 credits worth of Black Market equipment/supplies on his person for trade', 'Passionate but secretive extremist; hides his identity, prefers whispering through chosen speakers to addressing crowds directly.', '"Colonel" Robert Miller (originally inspired him, no recent contact); six deranged personal followers', 'Free Quebec authorities; Coalition troops; D-Bees', 'Schizophrenic, messianic extremist behind les Soldats de St. Jean''s most violent wing; his true appearance is unknown to any authority.', 'Rifts World Book 22: Free Quebec p.150');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'robert-miller', 'Robert Miller', NULL, '"Colonel" - les Soldats de St. Jean Chapter Colonel', 'rifts', NULL, '7th level Wilderness Scout and something of a Rogue Scholar', 7, 'Scrupulous (albeit a bit deluded)', '41', '6 feet, 2 inches (1.88 m)', '175 lbs (78.75 kg)', '{"IQ":15,"ME":18,"MA":21,"PS":14,"PP":15,"PE":17,"PB":11,"Spd":14}', 52, 54, NULL, 9, NULL, NULL, 8, '{"attacks":6,"strike":2,"parry":3,"dodge":3,"roll":2}', 'Horror/Awe Factor 12 to his followers, none to "Franko"; +2 save vs psionic attacks; 65% to trust/intimidate; +5% save vs coma/death; +1 save vs magic; critical on 18-20', '[{"name":"Literacy","pct":98},{"name":"Language: American","pct":98},{"name":"Language: Old French","pct":98},{"name":"Language: Inuit","pct":98},{"name":"Basic Math","pct":98},{"name":"Computer Operations","pct":70},{"name":"Pilot Automobile","pct":90},{"name":"Horsemanship","pct":80},{"name":"Land Navigation","pct":82}]', 'Hand to Hand: Expert (7th level); Boxing; W.P. Energy Rifle, W.P. Energy Pistol, W.P. Bolt-Action Rifle, W.P. Knife (all 7th level); Climbing; Hunting; Fishing', NULL, NULL, NULL, NULL, NULL, 'Wilk''s 457 energy rifle; F-18 laser pistol; NG-S2 survival pack; 2 Vibro-Knives; full wilderness gear; Huntsman body armor; repainted captured Dead Boy armor (for combat)', 'Access to over 500,000 credits worth of equipment, money and stores (not counting items stolen from the CS)', 'Quiet, thoughtful, benevolent leader and tactician; tolerates dissent, prefers driving off D-Bees rather than slaughtering them.', '"Franko"/Jean Desjardins (originally inspired him, no direct contact in years); his brigade of armed civilians and support personnel', 'Coalition States (raids/robs CS troops near the border)', 'Influential southwestern Free Quebec chapter leader of les Soldats de St. Jean, commanding nearly a brigade of guerrillas against the CS.', 'Rifts World Book 22: Free Quebec p.151-152');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'robert-carlye', 'Robert Carlye', 'Robert Williams Carlye', 'Professor, leader of the COF (Children of Freedom)', 'rifts', NULL, '10th level Scholar and Terrorist Leader', 10, 'Miscreant', '51', '6 feet, 2 inches (1.86 m)', '285 lbs (128 kg)', '{"IQ":21,"ME":8,"MA":20,"PS":14,"PP":9,"PE":10,"PB":9,"Spd":9}', 46, 22, NULL, 4, NULL, NULL, NULL, '{"attacks":4,"parry":2,"dodge":2,"roll":2}', '60% to evoke trust/intimidate; Hand to Hand: Basic, but only at 3rd level', '[{"name":"Literacy: American","pct":98},{"name":"Literacy: Euro","pct":98},{"name":"Literacy: Old French","pct":98},{"name":"Language: American","pct":98},{"name":"Language: Old French","pct":98},{"name":"Language: Euro","pct":98},{"name":"Language: Inuit","pct":98},{"name":"Basic Math","pct":98},{"name":"Advanced Math","pct":98},{"name":"Anthropology","pct":98},{"name":"Computer Operations","pct":98},{"name":"Computer Programming","pct":98},{"name":"History","pct":98},{"name":"Law","pct":98},{"name":"Writing","pct":98},{"name":"Swim","pct":98},{"name":"Fish","pct":98},{"name":"Pilot Sail Boat","pct":98},{"name":"Pilot Hover Craft","pct":98},{"name":"Radio: Basic","pct":90},{"name":"TV/Video","pct":87},{"name":"Computer Hacking","pct":67},{"name":"Dance","pct":67},{"name":"Sing","pct":92},{"name":"Art","pct":77},{"name":"Forgery","pct":72}]', 'Hand to Hand: Basic (3rd level only); W.P. Energy Pistol (10th level); W.P. Blunt (3rd level)', NULL, NULL, NULL, NULL, NULL, 'Weighted walking stick (M.D.C. material, for show); Q1-01 Laser Pistol; Pocket knife; T-40 "Plain-Clothes" business suits and robe (25 M.D.C. each); Specially made non-environmental armor with helmet (50 M.D.C.)', NULL, 'Fire-and-brimstone visionary preacher-scholar; utterly convinced he''s right, disorganized tactically, indifferent to followers'' suffering.', 'Capt. Jeunet and other Children of Freedom henchmen', 'Coalition States; Quebec Military and Government', 'Bald, imposing scholar leading the Children of Freedom terrorist militia, staging attacks on both CS and Quebec forces to further his own vision.', 'Rifts World Book 22: Free Quebec p.175');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'gwen-severson', 'Gwen Severson', NULL, 'Mayor', 'rifts', 'Human', 'master politician', 9, 'Anarchist with leanings toward unprincipled; often does the right thing even when tempted otherwise, but not always', '45', '5 feet, 10 inches (1.75 m)', NULL, '{"IQ":18,"ME":15,"MA":24,"PS":12,"PP":15,"PE":26,"PB":24,"Spd":14}', 43, 35, 78, 7, 85, NULL, NULL, '{"attacks":5,"strike":2,"parry":3,"dodge":3,"roll":3,"damage":2}', 'P.E. considered supernatural; MDC 78 is a side effect of daily use of the Chichen Itza healing well water (reverts to SDC 35 if supply stops); critical strike 19-20', NULL, NULL, 'Heals rapidly from constant use of Chichen Itza''s healing well water; regenerates 4D6 MDC/minute; the water also grants MDC-creature status and slows aging.', NULL, 'Sixth sense; Total recall; Object read; See aura; Mind block; Empathy; Telepathy; Presence sense', NULL, NULL, 'Silver cross (worn, non-religious); Small silver dagger; Six-shooter with silver bullets', NULL, 'Charming master politician skilled at deflecting hard questions; not a fighter, relies on bodyguards; secretly allied with vampires.', 'The Lost (vampire group); Town of Silvereno; 1st Cavalry (certain high-ranking members)', NULL, 'Mayor of Silvereno for 12 years; secretly a mega-damage being sustained by the healing well of Chichen Itza, in a secret protective pact with a vampire group.', 'Rifts World Book 14: New West p.45-46');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'jacob-whispering-wind', 'Jacob Whispering Wind', NULL, 'Sheriff', 'rifts', 'Human/Indian', 'Arapaho Spirit Warrior', 7, 'Principled', NULL, '5 feet, 6 inches', NULL, '{"IQ":15,"ME":21,"MA":19,"PS":24,"PP":22,"PE":17,"PB":14,"Spd":24}', 39, 49, NULL, 125, 66, NULL, NULL, '{"attacks":6,"initiative":3,"strike":6,"parry":7,"dodge":7,"pull":3,"roll":3,"damage":9}', 'Hand to hand: expert; critical strike 18-20; kick attacks 1D6+9 damage or 2D4+9 S.D.C. from auto-kick', '[{"name":"Read and write","pct":60},{"name":"Math","pct":80},{"name":"Identify plants & fruits","pct":65},{"name":"Fish","pct":80},{"name":"Cook","pct":75},{"name":"Radio: basic","pct":70},{"name":"Track (humanoids)","pct":70},{"name":"Track animals","pct":70},{"name":"Land navigation","pct":75},{"name":"Wilderness survival","pct":70}]', 'Hunting (no % printed), W.P. archery, W.P. blunt (war club), W.P. energy pistol, W.P. energy rifle (all 7th level)', 'Arapaho eagle-totem spirit warrior: flies as the eagle, speaks with birds, superior vision/tracking, bonus SDC and attacks, and a vengeance cry that penalizes marked foes.', 'Fly as the eagle (5 PPE); Speak with birds (10 PPE); Spirit of the Eagle (10 PPE: +50 SDC, +1 combat action, +1 attack, +10 SDC h2h damage); Eyes of the Eagle (8 PPE: 2-mile vision, tracking 75%); Eagle''s Cry (25 PPE: marks target, -4 initiative/-2 bonuses/-2 attacks vs accuser until vengeance served)', 'Clairvoyance; Sixth sense', NULL, NULL, 'Wilk''s-Remi laser rifle; CFT 1886er; Neural mace; Pocket knife; Apache war club; Magical Apache war necklace/amulet (100 MDC, regenerates 1D4x10 MDC/hr, only he can wear it); Magical eagle''s talon', NULL, 'Stern, intelligent, alert Apache lawman; courageous, resourceful, unwavering in duty; distrusts the Mayor''s evasiveness.', 'Silvereno townspeople; His deputies; Various Indian and wilderness friends', NULL, 'Apache warrior turned town sheriff of Silvereno for two years; highly respected for fairness and courage; suspects (but hasn''t proven) vampires operate in the area.', 'Rifts World Book 14: New West p.48-49');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'essai-ramirez', 'Essai Ramirez', NULL, 'The Vampire Lord', 'rifts', 'Master Vampire', 'Master Vampire', 8, 'Aberrant', NULL, '5 feet, 9 inches', '140 lbs (63 kg)', '{"IQ":18,"ME":20,"MA":26,"PS":36,"PP":25,"PE":23,"PB":20,"Spd":32}', NULL, NULL, 200, 40, 165, NULL, 14, '{"attacks":7,"initiative":3,"strike":9,"parry":12,"dodge":12,"roll":6}', 'All attributes considered supernatural; printed as single combined ''M.D.C./Hit Points: 200'' value (no separate SDC); inflicts M.D. from punches/kicks (supernatural PS); critical strike 18-20', '[{"name":"Land navigation","pct":65},{"name":"Wilderness survival","pct":70}]', 'W.P. energy pistol, W.P. energy rifle, W.P. knife (all 8th level)', 'Master vampire: impervious except to wood, silver, holy water, sunlight, magic; shapeshifts to bat/wolf/mist; regenerates 2D6 HP/melee; smells blood 1 mile; summons rodents, canines, fog.', NULL, 'Mind control; Link with minions; Death trance; Alter aura; Empathy; Mind block; Presence sense; Sense evil; Deaden pain; Induce sleep; Hypnotic suggestion; Super hypnotic suggestion', NULL, NULL, '50 M.D.C. breast plate; NG-P7 Particle beam rifle; TX 500 rail gun; Ring of Agony (casts agony 4x/day, +4 spell strength, equal to 6th-level spell, save 16+); Necklace of Speed of the Snail (casts 4x/day at 6th level, +4 spell strength); Vials of Chichen Itza healing well water', NULL, 'Calm, cold, and calculating; regards mortals as pawns, playthings, and food, but follows his own code of ethics.', 'The Lost (vampire group he leads); Mayor Gwen Severson', NULL, 'Ancient master vampire secretly leading the vampire group ''The Lost'' in Silvereno on behalf of a vampire intelligence in Chichen Itza; poses as Katherine''s mysterious gambler lover.', 'Rifts World Book 14: New West p.51');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'katherine-delgado', 'Katherine Delgado', NULL, 'The Vampire Queen', 'rifts', 'Secondary Vampire', 'Secondary Vampire', 6, 'Miscreant', NULL, '5 feet, 8 inches (1.72 m)', NULL, '{"IQ":16,"ME":18,"MA":22,"PS":26,"PP":22,"PE":25,"PB":26,"Spd":21}', NULL, NULL, 110, 30, 120, NULL, 12, '{"attacks":6,"initiative":3,"strike":6,"parry":8,"dodge":8,"roll":5}', 'All attributes considered supernatural; printed as single combined ''M.D.C./Hit Points: 110'' value (no separate SDC); supernatural PS does mega-damage; critical strike on natural 20', NULL, NULL, 'Secondary vampire: impervious except to wood, silver, holy water, sunlight, magic; shapeshifts to bat/wolf/mist; regenerates 2D6 HP/melee; summons rodents, canines, fog; keen senses.', NULL, 'Mind control; Link with minions; Death trance; Alter aura; Empathy; Mind block; Presence sense; Sense evil; Deaden pain; Induce sleep; Hypnotic suggestion; Super hypnotic suggestion', NULL, NULL, 'Ancient blades / Vibro-Blades and other hand weapons; Remi-Derringer energy pistol; Rings and gem-studded necklaces (~150,000 credits); Magical Indian war spear (5D6 S.D.C. to humans, 5D6 M.D. to supernatural creatures/M.D.C. structures, double damage to vampires; thrown 500 ft with 4 PPE or 8 ISP)', NULL, 'Cruel and possessive; sees humans as prey; obsessively devoted to Essai and prone to violent jealous rages.', 'Essai Ramirez (true love); The vampire intelligence of Chichen Itza', NULL, 'Secondary vampire and Essai''s devoted lover; owns and runs the Lucky Lady saloon/brothel in Silvereno, using it to pick out victims for the vampires.', 'Rifts World Book 14: New West p.51-52');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'thadius-geller', 'Thadius Geller', NULL, 'Doctor', 'rifts', 'Human', 'Trader', 10, 'Unprincipled (with tendencies toward scrupulous good)', 'mid to late 40''s', '5 feet, 11 inches (1.8 m)', '230 lbs (104 kg)', '{"IQ":13,"ME":12,"MA":15,"PS":10,"PP":11,"PE":13,"PB":11,"Spd":5}', 46, 10, NULL, NULL, NULL, NULL, NULL, '{"attacks":6,"strike":1,"parry":2,"dodge":2,"pull":4,"roll":4,"damage":2}', 'Hand to hand: basic; critical strike 19-20; judo-style body throw/flip (no damage dice printed); recovering alcoholic', '[{"name":"Literacy: American and Spanish","pct":98},{"name":"Pilot: Automobile","pct":98},{"name":"Mathematics: Basic","pct":98},{"name":"Mathematics: Advanced","pct":98},{"name":"Computer Operation","pct":98},{"name":"Computer Programming","pct":98},{"name":"Play Trombone","pct":85},{"name":"Dance","pct":75},{"name":"Horsemanship: General","pct":76},{"name":"Streetwise","pct":66},{"name":"Lore: Demons/Monsters","pct":70},{"name":"Writing","pct":80},{"name":"First Aid","pct":90}]', 'Speaks American and Spanish (language, no % printed), W.P. Energy Pistol', NULL, NULL, NULL, NULL, NULL, 'NGR-G10 Soldier armor (worn only if desperate); Triax TX-43 Laser rifle (2D6 S.D.C. / 2D6 M.D. / 4D6 M.D. settings, 2000 ft/610m range)', 'Bulk of money tied up in the Carnival; keeps an emergency petty-cash fund of roughly 40,000-60,000 credits', 'Good-hearted flimflam man and small-time con artist who genuinely believes his carnival improves people''s lives.', 'Byaltur (carnival security chief, usually escorts/guards Geller)', NULL, 'Self-styled ''Doctor'' and impresario running Doctor Geller''s Carnival of Wonders, a travelling show in the Pecos Empire; not much of a fighter, more a promoter and businessman.', 'Rifts World Book 14: New West p.68');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'roderick-warrington-iii', 'Roderick Warrington III', NULL, 'The Remarkable Roddy (also formerly the supervillain "Lightning Rod")', 'rifts', 'Human D-Bee from an Earth-like planet without Rifts', 'D-Bee Supervillain', 8, 'Miscreant', 'mid to late 30''s', '5 feet, 6 inches (1.6 m)', '145 lbs (66 kg)', '{"IQ":10,"ME":10,"MA":9,"PS":8,"PP":9,"PE":11,"PB":9,"Spd":11}', 40, 70, NULL, NULL, NULL, NULL, NULL, '{"attacks":6,"initiative":2,"strike":2,"parry":3,"dodge":3,"pull":3,"roll":3,"damage":2}', 'Hand to hand: Martial Arts; +1 extra attack if flying; leap attack and entangle abilities (no numeric bonus printed); critical strike 18-20; jump kick and judo-style body throw/flip (no dice printed); unusual physical trait: all head/facial hair permanently fallen out (wears a toupee)', '[{"name":"Language: American","pct":98},{"name":"Literacy: American","pct":98},{"name":"Pilot: Automobile","pct":98},{"name":"Pilot: Race Car","pct":90},{"name":"Pilot: Motorcycle","pct":88},{"name":"Pilot: Motorboat","pct":88},{"name":"Mathematics: Basic","pct":98},{"name":"Mathematics: Advanced","pct":92},{"name":"Computer Operation","pct":98},{"name":"Computer Programming","pct":98},{"name":"Photography","pct":85},{"name":"First Aid","pct":85},{"name":"Dance","pct":82},{"name":"Sing","pct":75},{"name":"Write","pct":62}]', 'Acrobatics (3rd level)', NULL, NULL, NULL, 'Chameleon (Major: 95% prowl, blend into environment up to 90%, hold breath 10 min, feign death, adhere to sheer surfaces); Energy Expulsion: Electricity (Minor); Manipulate Kinetic Energy (Minor: kinetic attacks vs. him only half damage, mental parry of one kinetic attack at +4, can redirect thrown objects); Wingless Flight (Minor: 340 mph/546 km; while flying +2 strike, +2 parry, +4 dodge under 80 mph, +6 dodge at 90+ mph, +4 S.D.C. damage per 20 mph)', NULL, 'Maverick body armor (emergency use only); Particle beam rifle (emergency use only)', '2D4x10,000 credits cash on hand, plus 4D4x1,000 credits in other items; ~100,000 credits in gems kept nearby; up to 450,000 more credits accessible', 'Cocky ex-supervillain turned conniving crook; still craves wealth and comfort, willing to lie, cheat, steal, and kill for it.', 'Byaltur (Security Chief, 7th level retired Bounty Hunter); "Weasel" Wallace (8th level professional thief/master pickpocket); Trader Bob (7th level Smuggler); Kate "The Knife" Kelly (6th level Gunslinger, girlfriend); A gang of five pickpockets (6th-7th level thieves)', NULL, 'D-Bee refugee from an alternate Earth of superheroes; former supervillain ''Lightning Rod,'' accidentally teleported to Rifts Earth; now poses as carnival aerialist while secretly running theft, smuggling, and blackmail.', 'Rifts World Book 14: New West p.69-70');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'arthur-night', 'Arthur Night', NULL, 'Leader of the Grim Reaper Cult', 'rifts', 'Elf', 'Necromancer', 15, 'Diabolic and insane', NULL, NULL, NULL, '{"IQ":19,"ME":11,"MA":19,"PS":13,"PP":11,"PE":17,"PB":14,"Spd":16}', 71, 21, NULL, 192, NULL, NULL, 13, '{"attacks":5,"strike":2,"parry":5,"dodge":5,"roll":2,"damage":3}', 'Attacks per melee: 5 physical, or 2 by magic; 60% trust/intimidate; critical strike on 18-20; knock out/stun on unmodified 18-20; critical strike from behind = triple damage; death blow on natural 20; +40 M.D.C. if wearing skull of an ancient demon; Death Vessel grants +10 to save vs psionic attacks and immunity to possession/mind control', '[{"name":"Demon and Monster Lore","pct":98},{"name":"Holistic Medicine","pct":98},{"name":"Wilderness Survival","pct":98}]', 'Hand to Hand: Basic (15th level); W.P. energy rifle, energy pistol, knife', 'Unites with the dead (attaches dead limbs/parts to himself); animates/controls up to 60 dead; vampires can neither mind-control him nor slay him with their bite; unusually slowed aging', 'All necromantic spells; All common spell magic, levels 1-13 (non-death spells cost double P.P.E.)', NULL, NULL, NULL, 'Vibro-Knife; Laser Pistol (1D6 M.D.); Bracelet of Protection (grants 300 M.D.C. for up to 4 hrs, 4x/day); Ring of the Elements (cast any warlock spell at 6th level, free P.P.E., 4x/day); Death Vessel (amulet, +1,000 P.P.E. reservoir, regenerates 50 P.P.E./hr, protects vs possession/mind control); Huntsman Armor (40 M.D.C.); Skull of an ancient demon (+40 M.D.C. when worn)', '~150 million credits, via the cult', 'Utterly insane servant of Death; hides his cult activities behind the harmless public persona of herbalist "Aramis Knight."', 'Alana Black (9th level Necromancer); Otto Schroder (12th level Shifter); Memtar the Destroyer (8th level witch of the Death entity); Overlord Wycleen (renegade Splugorth High Lord); Grim Reaper cult (~500 members, ~1,000 pawns incl. several hundred Juicers)', NULL, 'Elven necromancer, secretly ruler of the Grim Reaper death-cult headquartered beneath Laramy, publicly posing as a kind herbalist.', 'Rifts World Book 10: Juicer Uprising p.97-98');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'knight-hunter', 'Knight Hunter', 'Ralph Miller', 'Murder-Wraith', 'rifts', 'Undead (Murder-Wraith; formerly human)', 'Juicer Murder-Wraith', 5, 'Diabolic', NULL, NULL, NULL, '{"IQ":8,"ME":6,"MA":4,"PS":36,"PP":23,"PE":24,"PB":3,"Spd":63}', 61, 329, NULL, 48, NULL, NULL, 13, '{"attacks":7,"initiative":4,"strike":6,"parry":6,"dodge":6,"roll":8,"pull":8}', '+8 to save vs magic, +3 to save vs psionics, +10 to save vs horror factor; damage is per supernatural P.S. (no numeric bonus printed); M.D.C. by armor only (usually wears none) and impervious to normal weapons and M.D. weapons as an undead', '[{"name":"Wilderness Survival","pct":60},{"name":"Prowl","pct":65},{"name":"detect ambush","pct":60}]', 'Hand to Hand: assassin and boxing; several W.P.''s (unspecified)', 'Full type abilities are in the generic Murder-Wraith entry, cross-referenced not reprinted here; undead, supernatural strength, resists normal/M.D. weapons', NULL, NULL, NULL, NULL, NULL, 'No personal use for it, but has amassed 50,000 credits'' worth of items, which Aramis lets him keep', 'A conniving, self-pitying loser even in undeath; guilt-ridden over murdering his brother Armand, secretly resentful but too afraid to turn on his master Aramis.', 'None, other than the Grim Reapers (serves Aramis Night)', 'Cyber-Knights (attacks any on sight); Armand Miller (his brother, whom he murdered)', 'Undead Murder-Wraith, formerly the Juicer Ralph Miller; jealous of his Cyber-Knight brother, he was made undead by the Grim Reapers and now hunts Cyber-Knights for his master Aramis Night.', 'Rifts World Book 10: Juicer Uprising p.98-99');
INSERT INTO notable_npcs (slug, name, real_name, title, system, race, occ, level, alignment, age, height, weight, attributes, hp, sdc, mdc, ppe, isp, ar, horror_factor, combat, bonuses_note, skills, skills_note, natural_abilities, magic, psionics, super_powers, cybernetics, weapons_and_equipment, money, disposition, allies, enemies, description, source_book) VALUES (
  'knife-master', 'Knife Master', 'Arno the Freelancer', 'Leader of the Society of the Knife', 'rifts', 'Wormwood native (appears human)', 'Freelancer (former), now Witch', 8, 'Diabolic', NULL, NULL, NULL, '{"IQ":13,"ME":11,"MA":18,"PS":35,"PP":27,"PE":20,"PB":9,"Spd":24}', NULL, NULL, 248, 18, NULL, NULL, 8, '{"attacks":5,"initiative":2,"strike":8,"parry":12,"dodge":12,"roll":7,"pull":7}', 'Horror Factor only applies if his true nature is discovered; +5 to save vs magic, +3 to save vs poison and disease, +6 to save vs horror factor; bio-regenerates 1D4x10 M.D.C. per hour', '[{"name":"Language: American","pct":98},{"name":"Language: Trade Three","pct":98},{"name":"Language: Trade Four","pct":98},{"name":"Language: Trade Six","pct":98},{"name":"Language: Demongogian","pct":80},{"name":"Demon and Monster Lore","pct":75},{"name":"Prowl","pct":70},{"name":"Streetwise","pct":57}]', 'W.P. knife, W.P. sword; Hand to Hand: Assassin (8th level) plus boxing', 'Gift of Power: enhanced physique and supernatural strength; bio-regenerates 1D4x10 M.D.C./hour; natural M.D.C. being as a Wormwood native', NULL, NULL, NULL, NULL, 'Magical Knife (3D6 M.D., returns when thrown); NE-4 plasma cartridge pistol; Wormwood chain mail (40 M.D.C.); Naruni Force Field (110 M.D.C.)', 'Millions, perhaps billions, of credits at his disposal', 'Ruthless, embittered pact-bound leader who vents frustration on others; efficient businessman with no tolerance for disobedience.', 'Trader Smythers / Naruni Enterprises (illegal-weapons arrangement); An unnamed alien intelligence on Level Ten (his true patron); Supernatural creatures on Levels Nine and Ten', NULL, 'A Wormwood-native freelancer-turned-witch who secretly is the masked Knife Master, leader of Center''s criminal Society of the Knife, bound in servitude to a hidden alien intelligence.', 'Rifts Dimension Book 2: Phase World p.23-24');

INSERT INTO stat_attacks (owner_kind, owner_slug, name, damage, is_mega_damage, range, note, sort) VALUES
  ('notable_npc', 'brethan-dzir', 'Restrained Punch', '5D6+27 S.D.C.', 0, 'melee', NULL, 0),
  ('notable_npc', 'brethan-dzir', 'Normal Punch', '6D6 M.D.', 1, 'melee', NULL, 1),
  ('notable_npc', 'brethan-dzir', 'Power Punch', '2D4x10 M.D.', 1, 'melee', 'counts as 2 attacks', 2),
  ('notable_npc', 'brethan-dzir', 'Kick', '1D4x10 M.D.', 1, 'melee', NULL, 3),
  ('notable_npc', 'brethan-dzir', 'Leap Kick', '2D4x10 M.D.', 1, 'melee', 'counts as 2 attacks', 4),
  ('notable_npc', 'brethan-dzir', 'Stomp', '2D6 : 4D6 M.D. (as printed)', 1, 'melee', 'printed with a colon between two dice terms; unclear if this is a range or a typo', 5),
  ('notable_npc', 'brethan-dzir', 'Body Flip/Throw', '4D6 M.D.', 1, 'melee', NULL, 6),
  ('notable_npc', 'coran-dzir', 'Restrained Punch', '1D6x10+38 S.D.C.', 0, 'melee', NULL, 0),
  ('notable_npc', 'coran-dzir', 'Normal Punch', '1D6x10 M.D.', 1, 'melee', NULL, 1),
  ('notable_npc', 'coran-dzir', 'Power Punch', '2D6x10 M.D.', 1, 'melee', 'counts as 2 attacks', 2),
  ('notable_npc', 'coran-dzir', 'Kick', '1D6x10 M.D.', 1, 'melee', NULL, 3),
  ('notable_npc', 'coran-dzir', 'Leap Kick', '2D6x10 M.D.', 1, 'melee', 'counts as 2 attacks', 4),
  ('notable_npc', 'coran-dzir', 'Body Flip/Throw', '6D6 M.D.', 1, 'melee', 'and usual penalties', 5),
  ('notable_npc', 'coran-dzir', 'Head Butt', '5D6 M.D.', 1, 'melee', NULL, 6),
  ('notable_npc', 'coran-dzir', 'Quadruple Punch', '4D6x10 M.D.', 1, 'melee', 'uses four melee attacks', 7),
  ('notable_npc', 'coran-dzir', 'Battle Sword', '2D4x10 M.D. (+100 M.D. vs gods/alien intelligences)', 1, 'melee', 'indestructible', 8),
  ('notable_npc', 'coran-dzir', 'Battle Sword Fire Ball', '1D6x10 M.D.', 1, '2000 feet (610 m)', 'counts as one melee attack', 9),
  ('notable_npc', 'leizak-dzir', 'Restrained Punch', '4D6+23 S.D.C.', 0, 'melee', NULL, 0),
  ('notable_npc', 'leizak-dzir', 'Normal Punch', '5D6 M.D.', 1, 'melee', NULL, 1),
  ('notable_npc', 'leizak-dzir', 'Power Punch', '1D6x10 M.D.', 1, 'melee', 'counts as 2 attacks', 2),
  ('notable_npc', 'leizak-dzir', 'Kick', '6D6 M.D.', 1, 'melee', NULL, 3),
  ('notable_npc', 'leizak-dzir', 'Leap Kick', '1D6x10 M.D.', 1, 'melee', 'counts as 2 attacks', 4),
  ('notable_npc', 'leizak-dzir', 'Stomp', '2D6 M.D.', 1, 'melee', NULL, 5),
  ('notable_npc', 'leizak-dzir', 'Head Butt', '3D6 M.D.', 1, 'melee', NULL, 6),
  ('notable_npc', 'leizak-dzir', 'Body Flip/Throw', '4D6 M.D.', 1, 'melee', NULL, 7),
  ('notable_npc', 'alistair-dunscon', 'Daemonfist (rune staff)', '1D6x10 M.D.', 1, 'melee', 'Soul Drinker; wielder''s spells cast 3 levels higher', 0),
  ('notable_npc', 'mestoph-denali', 'Restrained Punch', '5D6+21 S.D.C.', 0, 'melee', NULL, 0),
  ('notable_npc', 'mestoph-denali', 'Normal Punch', '5D6 M.D.', 1, 'melee', NULL, 1),
  ('notable_npc', 'mestoph-denali', 'Claw', '6D6 M.D.', 1, 'melee', NULL, 2),
  ('notable_npc', 'mestoph-denali', 'Power Punch', '1D6x10 M.D.', 1, 'melee', 'counts as 2 attacks', 3),
  ('notable_npc', 'mestoph-denali', 'Power Swipe/Claw', '2D4x10 M.D.', 1, 'melee', 'counts as 2 attacks', 4),
  ('notable_npc', 'mestoph-denali', 'Kick', '5D6 M.D.', 1, 'melee', NULL, 5),
  ('notable_npc', 'mestoph-denali', 'Black Halberd', '6D6 M.D.', 1, 'melee or hurled 1000 ft (305 m)', 'double damage to good-aligned supernatural beings', 6),
  ('notable_npc', 'kzaa', 'Bite', '2D6 S.D.C.', 0, 'melee', NULL, 0),
  ('notable_npc', 'kzaa', 'Restrained Claw', '4D6+6 S.D.C.', 0, 'melee', NULL, 1),
  ('notable_npc', 'kzaa', 'Full Strength Punch', '2D6 M.D.', 1, 'melee', NULL, 2),
  ('notable_npc', 'kzaa', 'Power Punch', '4D6 M.D.', 1, 'melee', 'counts as 2 attacks', 3),
  ('notable_npc', 'dragonbane', 'Punch', '4D6 M.D.', 1, 'melee', NULL, 0),
  ('notable_npc', 'dragonbane', 'Power Punch', '1D4x10 M.D.', 1, 'melee', 'counts as 2 attacks', 1),
  ('notable_npc', 'dragonbane', 'Kick', '5D6 M.D.', 1, 'melee', NULL, 2),
  ('notable_npc', 'dragonbane', 'Head Butt', '3D6 M.D.', 1, 'melee', NULL, 3),
  ('notable_npc', 'dragonbane', 'Stomp', '1D4 M.D.', 1, 'melee', NULL, 4),
  ('notable_npc', 'jean-desjardins', 'Vibro-Knife', '1D6 M.D.', 1, 'melee', NULL, 0),
  ('notable_npc', 'robert-carlye', 'Weighted walking stick', '2D4 S.D.C.', 0, 'melee', 'M.D.C. material; mostly for show, not needed', 0),
  ('notable_npc', 'robert-carlye', 'Pocket knife', '1D4 S.D.C.', 0, 'melee', NULL, 1),
  ('notable_npc', 'gwen-severson', 'Judo style body flip', '1D6+2 S.D.C.', 0, 'melee', 'victim loses one action', 0),
  ('notable_npc', 'jacob-whispering-wind', 'Eagle''s talon (magic)', '4D6 M.D. melee, or 4D6+5 M.D. ranged (4 PPE/attack)', 1, '200 ft (61 m) thrown, returns to Sheriff', 'counts as one melee action when thrown', 0),
  ('notable_npc', 'jacob-whispering-wind', 'Kick attack', '1D6+9', 0, 'melee', NULL, 1),
  ('notable_npc', 'essai-ramirez', 'Bite', '3D6 M.D.', 1, 'melee', NULL, 0),
  ('notable_npc', 'essai-ramirez', 'Restrained punch', '6D6+21 S.D.C.', 0, 'melee', NULL, 1),
  ('notable_npc', 'essai-ramirez', 'Full strength punch', '7D6 M.D.', 1, 'melee', NULL, 2),
  ('notable_npc', 'essai-ramirez', 'Power punch', '1D6x10 M.D.', 1, 'melee', NULL, 3),
  ('notable_npc', 'essai-ramirez', 'Kick', '4D6 M.D.', 1, 'melee', NULL, 4),
  ('notable_npc', 'essai-ramirez', 'Judo style body flip', '6D6+21 S.D.C. or 1D6 M.D.C.', 1, 'melee', 'victim loses one action', 5),
  ('notable_npc', 'katherine-delgado', 'Bite', '2D6 M.D.C.', 1, 'melee', NULL, 0),
  ('notable_npc', 'katherine-delgado', 'Restrained punch', '5D6+21 S.D.C.', 0, 'melee', NULL, 1),
  ('notable_npc', 'katherine-delgado', 'Full strength punch', '5D6 M.D.', 1, 'melee', NULL, 2),
  ('notable_npc', 'katherine-delgado', 'Power punch', '1D6x10 M.D.', 1, 'melee', NULL, 3),
  ('notable_npc', 'katherine-delgado', 'Kick', '4D6 M.D.', 1, 'melee', NULL, 4),
  ('notable_npc', 'katherine-delgado', 'Judo style body flip', '5D6+11 S.D.C. or 1D4 M.D.', 1, 'melee', 'victim loses one action', 5),
  ('notable_npc', 'thadius-geller', 'Kick attack', '1D6', 0, 'melee', NULL, 0),
  ('notable_npc', 'thadius-geller', 'Triax TX-43 Laser rifle', '2D6 S.D.C. / 2D6 M.D. / 4D6 M.D. (selectable)', 1, '2000 ft (610 m)', 'three damage settings', 1),
  ('notable_npc', 'roderick-warrington-iii', 'Electrical energy bolt', 'up to 10D6 S.D.C.', 0, NULL, '+1 wild shot, +3 aimed shot', 0),
  ('notable_npc', 'roderick-warrington-iii', 'Kick attack', '1D8', 0, 'melee', NULL, 1),
  ('notable_npc', 'arthur-night', 'Laser Pistol', '1D6 M.D.', 1, NULL, NULL, 0),
  ('notable_npc', 'arthur-night', 'Vibro-Knife', NULL, 1, NULL, 'damage die not printed', 1),
  ('notable_npc', 'knight-hunter', 'Physical attack (unarmed, per supernatural P.S.)', 'per supernatural P.S. (die not printed)', 1, NULL, 'no weapon listed; damage type (M.D. vs S.D.C.) not explicitly stated', 0),
  ('notable_npc', 'knife-master', 'Magical Knife', '3D6 M.D. plus hand to hand damage', 1, 'thrown, returns to hand', NULL, 0),
  ('notable_npc', 'knife-master', 'NE-4 plasma cartridge pistol', NULL, 1, NULL, 'damage die not printed here', 1);

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 29 notable NPCs are in' AS assertion, count(*) AS got, 29 AS want
  FROM notable_npcs WHERE slug IN ('brethan-dzir', 'coran-dzir', 'leizak-dzir', 'alistair-dunscon', 'mestoph-denali', 'kara-zayne', 'dan-ironforge', 'kzaa', 'dragonbane', 'power-master', 'task-master', 'shadow-master', 'brain-storm', 'gold-falcon', 'james-lome', 'sylvain-richard', 'julie-tremblay', 'jean-desjardins', 'robert-miller', 'robert-carlye', 'gwen-severson', 'jacob-whispering-wind', 'essai-ramirez', 'katherine-delgado', 'thadius-geller', 'roderick-warrington-iii', 'arthur-night', 'knight-hunter', 'knife-master');
SELECT 'and their 69 attacks' AS assertion, count(*) AS got, 69 AS want
  FROM stat_attacks WHERE owner_kind = 'notable_npc' AND owner_slug IN ('brethan-dzir', 'coran-dzir', 'leizak-dzir', 'alistair-dunscon', 'mestoph-denali', 'kara-zayne', 'dan-ironforge', 'kzaa', 'dragonbane', 'power-master', 'task-master', 'shadow-master', 'brain-storm', 'gold-falcon', 'james-lome', 'sylvain-richard', 'julie-tremblay', 'jean-desjardins', 'robert-miller', 'robert-carlye', 'gwen-severson', 'jacob-whispering-wind', 'essai-ramirez', 'katherine-delgado', 'thadius-geller', 'roderick-warrington-iii', 'arthur-night', 'knight-hunter', 'knife-master');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('add-notable-npcs.sql');
