-- Step 4 of the Nightbane extraction plan (apps/character-creator/docs/surveys/nightbane-core.md):
-- Firearm accessories, ammunition, body armor and optics. Printed 223-225. 91 rows.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/zzzzzzzzzzzzz-nb-gear-d-accessories-armor-optics.sql
--
-- D4 (#1126): every item in the equipment chapter is its own `nightbane` row, on
-- Nate's word, read off the Nightbane pages rather than shared with Heroes Unlimited's
-- rows for the near-identical chapter. HU's scripts (add-hu-gear-*.sql) are the
-- PRECEDENT for shape - names, where a combined entry splits into priced rows, which
-- column a number goes in - and each row here was diffed against its HU counterpart
-- to catch misreads. Where the two books disagree, this file holds what Nightbane
-- prints; the PR lists every disagreement and its evidence.
--
-- Slugs are the name plus `-nb`, so no Nightbane row can collide with a row of
-- another game. `cost` is dollars, a range's low end; NULL where the page prints no
-- price, with any printed wording in cost_note. Citations are printed folios
-- (cache page = folio + 1).

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('magazine-clip-pouch-automatic-pistol-nb', 'Magazine Clip Pouch (Automatic Pistol)', 'nightbane', 'gear', NULL, 10, '$10 for 2 clips, $16 for 4', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A specially designed ammo pouch for 2 (slimline) or 4 (heavy-duty) clips. Choice of camouflage, green, khaki or black. The 2-clip price is stored and cost_note carries both.', 'Nightbane RPG p.223'),
  ('magazine-clip-pouch-sub-machinegun-nb', 'Magazine Clip Pouch (Sub-Machinegun)', 'nightbane', 'gear', NULL, 12, '$12 for 2 cells, $18 for 4', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A specially designed ammo pouch for 2 (slimline) or 4 (heavy-duty) clips. Choice of camouflage, green, khaki or black. The 2-clip price is stored and cost_note carries both.', 'Nightbane RPG p.223'),
  ('magazine-clip-pouch-5-56mm-assault-rifle-20-round-nb', 'Magazine Clip Pouch (5.56mm Assault Rifle, 20-round)', 'nightbane', 'gear', NULL, 14, '$14 for 2 clips, $20 for 4', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A specially designed ammo pouch for 2 (slimline) or 4 (heavy-duty) clips. Choice of camouflage, green, khaki or black. The 2-clip price is stored and cost_note carries both.', 'Nightbane RPG p.223'),
  ('magazine-clip-pouch-5-56mm-assault-rifle-30-round-nb', 'Magazine Clip Pouch (5.56mm Assault Rifle, 30-round)', 'nightbane', 'gear', NULL, 18, '$18 for 2 clips, $24 for 4', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A specially designed ammo pouch for 2 (slimline) or 4 (heavy-duty) clips. Choice of camouflage, green, khaki or black. The 2-clip price is stored and cost_note carries both.', 'Nightbane RPG p.223'),
  ('magazine-clip-pouch-7-62mm-assault-rifle-20-round-nb', 'Magazine Clip Pouch (7.62mm Assault Rifle, 20-round)', 'nightbane', 'gear', NULL, 18, '$18 for 2 clips, $22 for 4', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A specially designed ammo pouch for 2 (slimline) or 4 (heavy-duty) clips. Choice of camouflage, green, khaki or black. The 2-clip price is stored and cost_note carries both.', 'Nightbane RPG p.223'),
  ('magazine-clip-pouch-7-62mm-assault-rifle-30-round-nb', 'Magazine Clip Pouch (7.62mm Assault Rifle, 30-round)', 'nightbane', 'gear', NULL, 20, '$20 for 2 clips, $26 for 4', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A specially designed ammo pouch for 2 (slimline) or 4 (heavy-duty) clips. Choice of camouflage, green, khaki or black. The 2-clip price is stored and cost_note carries both.', 'Nightbane RPG p.223'),
  ('magazine-ammo-bag-nb', 'Magazine Ammo Bag', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 223.', 'Nightbane RPG p.223'),
  ('assault-rifle-case-nb', 'Assault Rifle Case', 'nightbane', 'gear', NULL, 70, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 223.', 'Nightbane RPG p.223'),
  ('rifle-case-nb', 'Rifle Case', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 223.', 'Nightbane RPG p.223'),
  ('sub-machinegun-case-nb', 'Sub-Machinegun Case', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 223.', 'Nightbane RPG p.223'),
  ('shotgun-bandoleer-nb', 'Shotgun Bandoleer', 'nightbane', 'gear', NULL, 24, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Brown leather with a heavy-duty brass belt buckle. The shotgun version holds 56 rounds and the 40mm grenade version 18. Printed 223 sets the $24 as its own sentence closing the entry, after both versions.', 'Nightbane RPG p.223'),
  ('wrist-cartridge-bandoleer-nb', 'Wrist Cartridge Bandoleer', 'nightbane', 'gear', NULL, 15, '$15 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Perfect for concealing 3 extra cartridges.', 'Nightbane RPG p.223'),
  ('metal-ammunition-box-50-caliber-nb', 'Metal Ammunition Box (.50 caliber)', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A waterproof ammo box designed for easy storage and carrying.', 'Nightbane RPG p.223'),
  ('metal-ammunition-box-30-caliber-nb', 'Metal Ammunition Box (.30 caliber)', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A waterproof ammo box designed for easy storage and carrying.', 'Nightbane RPG p.223'),
  ('field-gun-cleaning-kit-nb', 'Field Gun Cleaning Kit', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A complete cleaning kit contained in its own pouch.', 'Nightbane RPG p.223'),
  ('gun-repair-kit-nb', 'Gun Repair Kit', 'nightbane', 'gear', 4, 250, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A 4lb kit. Each tool is fitted into a separate loop, with plenty of room for spare bolts, screws, springs and cleaning rods, in a 12 by 8 by 2 inch case. Attaches to a harness or is worn over the shoulder on the included strap.', 'Nightbane RPG p.223'),
  ('magazine-clips-nb', 'Magazine Clips', 'nightbane', 'gear', NULL, NULL, '$.89 each - BELOW THE RESOLUTION of an integer cost column, so it is recorded here rather than rounded to a dollar', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Any weapon, any size, from a 7-round pistol to a 30-round rifle.', 'Nightbane RPG p.223'),
  ('web-belt-military-nb', 'Web Belt (military)', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A classic military belt complete with buckle and pouch fasteners, in camouflage, green or khaki. NOT the same item as the Web Belt with holster, ammo pouches and accessory clips on printed 222, which is $60.', 'Nightbane RPG p.223'),
  ('battle-harness-nb', 'Battle Harness', 'nightbane', 'gear', NULL, 120, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A combination of suspenders and belt designed to distribute the weight of ammo pouches and accessories. Camouflage, black, grey, brown, cream or khaki.', 'Nightbane RPG p.223'),
  ('battle-pack-nb', 'Battle Pack', 'nightbane', 'gear', NULL, 350, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A lightweight frame in heavy-duty, water resistant canvas, with multiple interior and exterior compartments and fasteners for exterior pouches and grenades. Camouflage, green or khaki.', 'Nightbane RPG p.223'),
  ('multi-purpose-pouch-nb', 'Multi-Purpose Pouch', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An all-around utility pouch designed for attachment to a web belt or battle harness.', 'Nightbane RPG p.223'),
  ('silencer-revolver-nb', 'Silencer (Revolver)', 'nightbane', 'gear', NULL, 350, 'Not available on the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-like attachment which fits over the barrel of a gun to muffle the sound of the report. REDUCES RANGE BY 10%.', 'Nightbane RPG p.223'),
  ('silencer-automatic-pistol-nb', 'Silencer (Automatic Pistol)', 'nightbane', 'gear', NULL, 500, 'Not available on the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-like attachment which fits over the barrel of a gun to muffle the sound of the report. REDUCES RANGE BY 10%.', 'Nightbane RPG p.223'),
  ('silencer-bolt-action-rifle-nb', 'Silencer (Bolt Action Rifle)', 'nightbane', 'gear', NULL, 600, 'Not available on the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-like attachment which fits over the barrel of a gun to muffle the sound of the report. REDUCES RANGE BY 10%.', 'Nightbane RPG p.223'),
  ('silencer-automatic-rifle-nb', 'Silencer (Automatic Rifle)', 'nightbane', 'gear', NULL, 1500, 'Not available on the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-like attachment which fits over the barrel of a gun to muffle the sound of the report. REDUCES RANGE BY 10%.', 'Nightbane RPG p.223'),
  ('silencer-sub-machinegun-nb', 'Silencer (Sub-Machinegun)', 'nightbane', 'gear', NULL, 2000, 'Not available on the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-like attachment which fits over the barrel of a gun to muffle the sound of the report. REDUCES RANGE BY 10%.', 'Nightbane RPG p.223'),
  ('flash-suppressor-revolver-nb', 'Flash Suppressor (Revolver)', 'nightbane', 'gear', NULL, 250, 'Not available in the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-shaped attachment that fits over the barrel of a gun or a silencer and masks the gun''s flash; usually used for covert night operations. REDUCES RANGE BY 15%, or 25% if both a silencer and a flash suppressor are used.', 'Nightbane RPG p.223'),
  ('flash-suppressor-automatic-pistol-nb', 'Flash Suppressor (Automatic Pistol)', 'nightbane', 'gear', NULL, 450, 'Not available in the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-shaped attachment that fits over the barrel of a gun or a silencer and masks the gun''s flash; usually used for covert night operations. REDUCES RANGE BY 15%, or 25% if both a silencer and a flash suppressor are used.', 'Nightbane RPG p.223'),
  ('flash-suppressor-bolt-action-rifle-nb', 'Flash Suppressor (Bolt Action Rifle)', 'nightbane', 'gear', NULL, 1200, 'Not available in the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-shaped attachment that fits over the barrel of a gun or a silencer and masks the gun''s flash; usually used for covert night operations. REDUCES RANGE BY 15%, or 25% if both a silencer and a flash suppressor are used.', 'Nightbane RPG p.223'),
  ('flash-suppressor-sub-machinegun-nb', 'Flash Suppressor (Sub-Machinegun)', 'nightbane', 'gear', NULL, 1600, 'Not available in the commercial market', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A barrel-shaped attachment that fits over the barrel of a gun or a silencer and masks the gun''s flash; usually used for covert night operations. REDUCES RANGE BY 15%, or 25% if both a silencer and a flash suppressor are used.', 'Nightbane RPG p.223'),
  ('ammunition-22-caliber-nb', 'Ammunition, .22 caliber', 'nightbane', 'gear', NULL, 12, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-32-caliber-nb', 'Ammunition, .32 caliber', 'nightbane', 'gear', NULL, 14, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-38-caliber-nb', 'Ammunition, .38 caliber', 'nightbane', 'gear', NULL, 18, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-45-a-c-p-nb', 'Ammunition, .45 A.C.P.', 'nightbane', 'gear', NULL, 28, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-41-magnum-nb', 'Ammunition, .41 Magnum', 'nightbane', 'gear', NULL, 30, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-44-magnum-nb', 'Ammunition, .44 Magnum', 'nightbane', 'gear', NULL, 32, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-357-magnum-nb', 'Ammunition, .357 Magnum', 'nightbane', 'gear', NULL, 28, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-9mm-and-7-65mm-nb', 'Ammunition, 9mm and 7.65mm', 'nightbane', 'gear', NULL, 30, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-5-56mm-rifle-nb', 'Ammunition, 5.56mm (rifle)', 'nightbane', 'gear', NULL, 40, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-7-62mm-rifle-nb', 'Ammunition, 7.62mm (rifle)', 'nightbane', 'gear', NULL, 48, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('ammunition-tracer-cartridge-nb', 'Ammunition, Tracer Cartridge', 'nightbane', 'gear', NULL, 45, 'per box of 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100.', 'Nightbane RPG p.223'),
  ('ammunition-hollow-point-surcharge-nb', 'Ammunition, Hollow Point (surcharge)', 'nightbane', 'gear', NULL, 12, 'ADD $12.00 to the price of a box', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223 gives this as an ADD-ON to the price of a box of 100, not a price of its own. The figure is the surcharge.', 'Nightbane RPG p.223'),
  ('ammunition-full-metal-jacketed-surcharge-nb', 'Ammunition, Full Metal Jacketed (surcharge)', 'nightbane', 'gear', NULL, 25, 'ADD $25.00 to the price of a box', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223 gives this as an ADD-ON to the price of a box of 100, not a price of its own. The figure is the surcharge.', 'Nightbane RPG p.223'),
  ('ammunition-teflon-armor-piercing-surcharge-nb', 'Ammunition, Teflon armor piercing (surcharge)', 'nightbane', 'gear', NULL, 100, 'ADD $100.00; not available to the public', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223 gives this as an ADD-ON to the price of a box of 100, not a price of its own. The figure is the surcharge. Printed 223 marks this with an asterisk: NOT available at the neighborhood gun shop, but can be tracked down through the black market and illegal arms dealers. The added price is a MINIMUM and can cost two or three times more.', 'Nightbane RPG p.223'),
  ('ammunition-exploding-shell-surcharge-nb', 'Ammunition, Exploding Shell (surcharge)', 'nightbane', 'gear', NULL, 200, 'ADD $200.00; not available to the public', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223 gives this as an ADD-ON to the price of a box of 100, not a price of its own. The figure is the surcharge. Printed 223 marks this with an asterisk: NOT available at the neighborhood gun shop, but can be tracked down through the black market and illegal arms dealers. The added price is a MINIMUM and can cost two or three times more.', 'Nightbane RPG p.223'),
  ('ammunition-dum-dum-surcharge-nb', 'Ammunition, Dum Dum (surcharge)', 'nightbane', 'gear', NULL, 10, 'ADD $10.00 to $30.00; handmade, black market, any caliber', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223 gives this as an ADD-ON to the price of a box of 100, not a price of its own. The figure is the surcharge. Printed 223 marks this with an asterisk: NOT available at the neighborhood gun shop, but can be tracked down through the black market and illegal arms dealers. The added price is a MINIMUM and can cost two or three times more.', 'Nightbane RPG p.223'),
  ('40mm-grenade-cartridge-nb', '40mm Grenade Cartridge', 'nightbane', 'gear', NULL, 700, '$700.00 per 100', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 223, AMMUNITION - prices per BOX OF 100. Printed 223 marks this with an asterisk: NOT available at the neighborhood gun shop, but can be tracked down through the black market and illegal arms dealers. The added price is a MINIMUM and can cost two or three times more.', 'Nightbane RPG p.223'),
  ('padded-or-quilt-armor-nb', 'Padded or Quilt Armor', 'nightbane', 'armor', 66, 175, NULL, NULL, 0, NULL, NULL, NULL, 8, 15, 'Ancient style. THE PRINTED WEIGHT IS 66lbs, heavier than the Plate armor four rows below it at 58lbs and almost certainly a book error for 6lbs. Confirmed on a 150 dpi render of printed 223: the page really says 66. Transcribed as printed rather than corrected. Table note: the costs reflect the rarity of manufacturers/builders and the time involved in construction; homemade armor is possible at half cost, with A.R. reduced by 2 and S.D.C. by 20%.', 'Nightbane RPG p.223'),
  ('soft-leather-armor-nb', 'Soft Leather Armor', 'nightbane', 'armor', 8, 300, NULL, NULL, 0, NULL, NULL, NULL, 9, 20, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('studded-leather-armor-nb', 'Studded Leather Armor', 'nightbane', 'armor', 20, 600, NULL, NULL, 0, NULL, NULL, NULL, 12, 38, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('chain-mail-nb', 'Chain Mail', 'nightbane', 'armor', 40, 900, NULL, NULL, 0, NULL, NULL, NULL, 13, 44, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('scale-mail-nb', 'Scale Mail', 'nightbane', 'armor', 45, 1500, NULL, NULL, 0, NULL, NULL, NULL, 15, 75, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('plate-and-mail-nb', 'Plate and Mail', 'nightbane', 'armor', 52, 2000, NULL, NULL, 0, NULL, NULL, NULL, 15, 100, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('plate-armor-nb', 'Plate Armor', 'nightbane', 'armor', 58, 2800, NULL, NULL, 0, NULL, NULL, NULL, 16, 150, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('plastic-plated-armor-nb', 'Plastic Plated Armor', 'nightbane', 'armor', 28, 3000, NULL, NULL, 0, NULL, NULL, NULL, 13, 80, 'Ancient style, printed 223.', 'Nightbane RPG p.223'),
  ('concealed-armor-nb', 'Concealed Armor', 'nightbane', 'armor', 12, 1200, NULL, NULL, 0, NULL, NULL, NULL, 10, 50, 'A modern LIGHT half suit. Half suits or vest types usually protect the upper body front, back, side, waist and groin. Concealed styles are tough thin armor designed to be sewn into clothes or hidden under them; the other half suits are generally bulky or worn atop clothes. All modern armor is designed for flexibility and mobility and does not interfere with movement, prowl or speed. The table is on printed 223 and its notes run onto 224.', 'Nightbane RPG p.223'),
  ('riot-jacket-nb', 'Riot Jacket', 'nightbane', 'armor', 12, 900, NULL, NULL, 0, NULL, NULL, NULL, 10, 60, 'A modern LIGHT half suit, printed 223.', 'Nightbane RPG p.223'),
  ('armor-vest-nb', 'Armor Vest', 'nightbane', 'armor', 10, 800, NULL, NULL, 0, NULL, NULL, NULL, 10, 50, 'A modern LIGHT half suit. Printed 223 heads this row simply Vest; named in full here so it is legible out of the table.', 'Nightbane RPG p.223'),
  ('point-blank-vest-nb', 'Point Blank Vest', 'nightbane', 'armor', 14, 1100, NULL, NULL, 0, NULL, NULL, NULL, 10, 70, 'A modern LIGHT half suit, printed 223.', 'Nightbane RPG p.223'),
  ('hard-armor-vest-nb', 'Hard Armor Vest', 'nightbane', 'armor', 15, 1400, NULL, NULL, 0, NULL, NULL, NULL, 12, 120, 'A modern LIGHT half suit, printed 223. Printed 224: hard armor is composed of ceramics (pure alumina or boron carbide), often combined with steel, provides the most effective protection and can even stop 7.62mm NATO and 5.56mm rifle bullets.', 'Nightbane RPG p.223'),
  ('frag-cape-vest-nb', 'Frag. Cape/Vest', 'nightbane', 'armor', 16, 1400, NULL, NULL, 0, NULL, NULL, NULL, 13, 120, 'A modern HEAVY full suit. Full suits are all bulky suits worn on top of clothes and provide the greatest protection (note on printed 224).', 'Nightbane RPG p.223'),
  ('riot-armor-nb', 'Riot Armor', 'nightbane', 'armor', 17, 1600, NULL, NULL, 0, NULL, NULL, NULL, 14, 180, 'A modern HEAVY full suit, printed 223.', 'Nightbane RPG p.223'),
  ('hard-armor-nb', 'Hard Armor', 'nightbane', 'armor', 20, 2200, NULL, NULL, 0, NULL, NULL, NULL, 16, 260, 'A modern HEAVY full suit, printed 223. Printed 224: hard armor is composed of ceramics (pure alumina or boron carbide), often combined with steel, provides the most effective protection and can even stop 7.62mm NATO and 5.56mm rifle bullets.', 'Nightbane RPG p.223'),
  ('class-4-armor-nb', 'Class 4 Armor', 'nightbane', 'armor', 20, 2800, NULL, NULL, 0, NULL, NULL, NULL, 17, 280, 'A modern HEAVY full suit, printed 223.', 'Nightbane RPG p.223'),
  ('binocular-best-magnification-nb', 'Binocular, best magnification', 'nightbane', 'gear', NULL, 1600, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 2000ft. Binocular and telescopic sights magnify an image area through a system of lenses. Printed 224.', 'Nightbane RPG p.224'),
  ('binocular-medium-magnification-nb', 'Binocular, medium magnification', 'nightbane', 'gear', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft. Printed 224.', 'Nightbane RPG p.224'),
  ('binocular-low-magnification-nb', 'Binocular, low magnification', 'nightbane', 'gear', NULL, 600, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft. Printed 224.', 'Nightbane RPG p.224'),
  ('weapon-sight-best-magnification-nb', 'Weapon Sight, best magnification', 'nightbane', 'gear', NULL, 800, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 224.', 'Nightbane RPG p.224'),
  ('weapon-sight-medium-magnification-nb', 'Weapon Sight, medium magnification', 'nightbane', 'gear', NULL, 400, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 224.', 'Nightbane RPG p.224'),
  ('weapon-sight-low-magnification-nb', 'Weapon Sight, low magnification', 'nightbane', 'gear', NULL, 230, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 224.', 'Nightbane RPG p.224'),
  ('infrared-goggles-mercury-battery-type-nb', 'Infrared Goggles (mercury battery type)', 'nightbane', 'gear', NULL, 550, 'fair availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1200ft (360m). An infrared system relies on a source of infrared light, usually a pencil-thin beam projected from the goggles or binoculars, to illuminate its targets. THE BEAM LIMITS THE VIEW to a small area of about two square meters (7ft), making surveying a large area a problem, and is clearly visible to another infrared optic system, giving away the operator''s position. Both drawbacks are inherent to ALL infrared systems. The introductory paragraph gives the system ''Cost: about $1000; fair availability''; the table''s itemised prices are stored.', 'Nightbane RPG p.224'),
  ('infrared-goggles-new-superior-type-nb', 'Infrared Goggles (new superior type)', 'nightbane', 'gear', NULL, 880, 'fair availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1200ft (360m). Printed 224.', 'Nightbane RPG p.224'),
  ('infrared-binoculars-nb', 'Infrared Binoculars', 'nightbane', 'gear', NULL, 2100, 'fair availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1200ft (360m). Printed 224.', 'Nightbane RPG p.224'),
  ('infrared-monocular-eyepiece-nb', 'Infrared Monocular Eyepiece', 'nightbane', 'gear', NULL, 800, 'fair availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1200ft (360m). Printed 224.', 'Nightbane RPG p.224'),
  ('infrared-weapon-sight-nb', 'Infrared Weapon Sight', 'nightbane', 'gear', NULL, 1200, 'fair availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1200ft (360m). Printed 224.', 'Nightbane RPG p.224'),
  ('infrared-distancing-binoculars-nb', 'Infrared Distancing Binoculars', 'nightbane', 'gear', NULL, 6700, 'Not commercially available', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 2 miles (3km). A high-powered optical enhancement device with infrared adjustments, cross hair indicator lines and a digital readout of estimated distance and rate of travel. The I.D. binoculars are extremely popular among spies for field work and exploration, and are also used by the military.', 'Nightbane RPG p.224'),
  ('ultraviolet-optic-system-nb', 'Ultraviolet Optic System', 'nightbane', 'gear', NULL, 500, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 400ft (120m). Enables its wearer to see into the ultraviolet range of light radiation. Usually integrated into a larger optics package rather than used alone. Printed 224 heads it Ultraviolet Systems.', 'Nightbane RPG p.224'),
  ('night-sight-goggles-nb', 'Night Sight Goggles', 'nightbane', 'gear', NULL, 5200, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). A night vision system is an image intensifier - a PASSIVE system that emits no light of its own and electronically amplifies existing ambient light to provide a visible picture. The introductory paragraph gives the system ''Cost: $1400; poor availability''; the table''s itemised prices are stored.', 'Nightbane RPG p.224'),
  ('night-sight-binoculars-nb', 'Night Sight Binoculars', 'nightbane', 'gear', NULL, 6400, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). Printed 224.', 'Nightbane RPG p.224'),
  ('night-sight-monocular-eyepiece-nb', 'Night Sight Monocular Eyepiece', 'nightbane', 'gear', NULL, 1900, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). Printed 224.', 'Nightbane RPG p.224');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('night-sight-weapon-sight-nb', 'Night Sight Weapon Sight', 'nightbane', 'gear', NULL, 1800, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). Printed 224.', 'Nightbane RPG p.224'),
  ('pocket-night-viewer-nb', 'Pocket Night Viewer', 'nightbane', 'gear', NULL, 800, 'THE BOOK PRICES THIS TWICE AND DIFFERENTLY. Its own description on printed 224 says $800; the Night Sights table on the same page lists it at $1500.00. The DESCRIPTION wins', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 800ft (240m). A mini night sight, usually a monocular style, easily concealed and portable. Poor availability.', 'Nightbane RPG p.224'),
  ('night-sight-large-tripod-mount-nb', 'Night Sight Large Tripod Mount', 'nightbane', 'gear', NULL, 14000, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Night Sights (range 1600ft) table, printed 224.', 'Nightbane RPG p.224'),
  ('thermo-imager-goggles-nb', 'Thermo-Imager Goggles', 'nightbane', 'gear', NULL, 22000, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). An optical heat sensor that converts the infrared radiation of warm objects into a visible image, letting its operator see in darkness, shadows and through smoke. Battery powered and electrically cooled, with a typical running life of 16 hours. THE INTRODUCTORY PARAGRAPH SAYS ''Cost: about $1400; poor availability'', an order of magnitude below every figure in its own table; the table''s itemised prices are stored and the paragraph''s figure is recorded here.', 'Nightbane RPG p.224'),
  ('thermo-imager-binoculars-nb', 'Thermo-Imager Binoculars', 'nightbane', 'gear', NULL, 20000, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). Printed 224.', 'Nightbane RPG p.224'),
  ('thermo-imager-monocular-eyepiece-nb', 'Thermo-Imager Monocular Eyepiece', 'nightbane', 'gear', NULL, 18000, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). Printed 224.', 'Nightbane RPG p.224'),
  ('thermo-imager-weapon-sight-nb', 'Thermo-Imager Weapon Sight', 'nightbane', 'gear', NULL, 18000, 'poor availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Range 1600ft (480m). Printed 224.', 'Nightbane RPG p.224'),
  ('multi-optics-helmet-m-o-h-nb', 'Multi-Optics Helmet (M.O.H.)', 'nightbane', 'gear', NULL, 38000, 'Available to high-tech organizations', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An optical enhancement system built into a protective helmet: a targeting sight to 1600ft (480m), an infrared optics system to 1600ft (480m), a telescopic monocular lens to 2 miles (3km), and a thermo-imager to 1600ft (480m) that converts the infrared radiation of warm objects into a visible image, seeing in darkness, shadows and through smoke. SPECIAL BONUS: +1 to strike when the optics and targeting sight are engaged.', 'Nightbane RPG p.224'),
  ('optics-band-nb', 'Optics Band', 'nightbane', 'gear', NULL, 2800, NULL, NULL, 0, '7ft', NULL, NULL, NULL, NULL, 'A headband optical system most often used in research, micro-repairs and scientific study; its range is limited because it is designed for close work, not long-distance or combat surveillance. Infrared and ultraviolet optic system to 200ft (90m) maximum, a magnification lens to the 400th power with a range of 7ft (2m), a night sight to 200ft (90m), and adjustable color filters. The entry begins on printed 224 and its features and price are on 225.', 'Nightbane RPG p.224-225'),
  ('pocket-range-finder-nb', 'Pocket Range Finder', 'nightbane', 'gear', NULL, 58, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A compact, easy to use optical range finder: look through the viewfinder and adjust the focus knob until the image is clear, and the range in feet AND meters appears below the target.', 'Nightbane RPG p.225'),
  ('illuminating-peglight-nb', 'Illuminating Peglight', 'nightbane', 'gear', NULL, 50, '$50 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Designed for military use as markers for routes and minefields. Emits beta light, which gives off no heat and no infrared emissions. Can be seen from up to 150ft.', 'Nightbane RPG p.225');

-- Read the result back. This batch asserts its OWN rows and nothing else.
SELECT 'all 91 rows of this script are in, as nightbane' AS assertion, count(*) AS got, 91 AS want
  FROM gear WHERE system = 'nightbane' AND source_book LIKE 'Nightbane RPG p.%'
   AND slug IN ('magazine-clip-pouch-automatic-pistol-nb', 'magazine-clip-pouch-sub-machinegun-nb', 'magazine-clip-pouch-5-56mm-assault-rifle-20-round-nb', 'magazine-clip-pouch-5-56mm-assault-rifle-30-round-nb', 'magazine-clip-pouch-7-62mm-assault-rifle-20-round-nb', 'magazine-clip-pouch-7-62mm-assault-rifle-30-round-nb', 'magazine-ammo-bag-nb', 'assault-rifle-case-nb', 'rifle-case-nb', 'sub-machinegun-case-nb', 'shotgun-bandoleer-nb', 'wrist-cartridge-bandoleer-nb', 'metal-ammunition-box-50-caliber-nb', 'metal-ammunition-box-30-caliber-nb', 'field-gun-cleaning-kit-nb', 'gun-repair-kit-nb', 'magazine-clips-nb', 'web-belt-military-nb', 'battle-harness-nb', 'battle-pack-nb', 'multi-purpose-pouch-nb', 'silencer-revolver-nb', 'silencer-automatic-pistol-nb', 'silencer-bolt-action-rifle-nb', 'silencer-automatic-rifle-nb', 'silencer-sub-machinegun-nb', 'flash-suppressor-revolver-nb', 'flash-suppressor-automatic-pistol-nb', 'flash-suppressor-bolt-action-rifle-nb', 'flash-suppressor-sub-machinegun-nb', 'ammunition-22-caliber-nb', 'ammunition-32-caliber-nb', 'ammunition-38-caliber-nb', 'ammunition-45-a-c-p-nb', 'ammunition-41-magnum-nb', 'ammunition-44-magnum-nb', 'ammunition-357-magnum-nb', 'ammunition-9mm-and-7-65mm-nb', 'ammunition-5-56mm-rifle-nb', 'ammunition-7-62mm-rifle-nb', 'ammunition-tracer-cartridge-nb', 'ammunition-hollow-point-surcharge-nb', 'ammunition-full-metal-jacketed-surcharge-nb', 'ammunition-teflon-armor-piercing-surcharge-nb', 'ammunition-exploding-shell-surcharge-nb', 'ammunition-dum-dum-surcharge-nb', '40mm-grenade-cartridge-nb', 'padded-or-quilt-armor-nb', 'soft-leather-armor-nb', 'studded-leather-armor-nb', 'chain-mail-nb', 'scale-mail-nb', 'plate-and-mail-nb', 'plate-armor-nb', 'plastic-plated-armor-nb', 'concealed-armor-nb', 'riot-jacket-nb', 'armor-vest-nb', 'point-blank-vest-nb', 'hard-armor-vest-nb', 'frag-cape-vest-nb', 'riot-armor-nb', 'hard-armor-nb', 'class-4-armor-nb', 'binocular-best-magnification-nb', 'binocular-medium-magnification-nb', 'binocular-low-magnification-nb', 'weapon-sight-best-magnification-nb', 'weapon-sight-medium-magnification-nb', 'weapon-sight-low-magnification-nb', 'infrared-goggles-mercury-battery-type-nb', 'infrared-goggles-new-superior-type-nb', 'infrared-binoculars-nb', 'infrared-monocular-eyepiece-nb', 'infrared-weapon-sight-nb', 'infrared-distancing-binoculars-nb', 'ultraviolet-optic-system-nb', 'night-sight-goggles-nb', 'night-sight-binoculars-nb', 'night-sight-monocular-eyepiece-nb', 'night-sight-weapon-sight-nb', 'pocket-night-viewer-nb', 'night-sight-large-tripod-mount-nb', 'thermo-imager-goggles-nb', 'thermo-imager-binoculars-nb', 'thermo-imager-monocular-eyepiece-nb', 'thermo-imager-weapon-sight-nb', 'multi-optics-helmet-m-o-h-nb', 'optics-band-nb', 'pocket-range-finder-nb', 'illuminating-peglight-nb');

SELECT 'every one has a description' AS assertion, count(*) AS got, 91 AS want
  FROM gear WHERE system = 'nightbane' AND length(description) > 0
   AND slug IN ('magazine-clip-pouch-automatic-pistol-nb', 'magazine-clip-pouch-sub-machinegun-nb', 'magazine-clip-pouch-5-56mm-assault-rifle-20-round-nb', 'magazine-clip-pouch-5-56mm-assault-rifle-30-round-nb', 'magazine-clip-pouch-7-62mm-assault-rifle-20-round-nb', 'magazine-clip-pouch-7-62mm-assault-rifle-30-round-nb', 'magazine-ammo-bag-nb', 'assault-rifle-case-nb', 'rifle-case-nb', 'sub-machinegun-case-nb', 'shotgun-bandoleer-nb', 'wrist-cartridge-bandoleer-nb', 'metal-ammunition-box-50-caliber-nb', 'metal-ammunition-box-30-caliber-nb', 'field-gun-cleaning-kit-nb', 'gun-repair-kit-nb', 'magazine-clips-nb', 'web-belt-military-nb', 'battle-harness-nb', 'battle-pack-nb', 'multi-purpose-pouch-nb', 'silencer-revolver-nb', 'silencer-automatic-pistol-nb', 'silencer-bolt-action-rifle-nb', 'silencer-automatic-rifle-nb', 'silencer-sub-machinegun-nb', 'flash-suppressor-revolver-nb', 'flash-suppressor-automatic-pistol-nb', 'flash-suppressor-bolt-action-rifle-nb', 'flash-suppressor-sub-machinegun-nb', 'ammunition-22-caliber-nb', 'ammunition-32-caliber-nb', 'ammunition-38-caliber-nb', 'ammunition-45-a-c-p-nb', 'ammunition-41-magnum-nb', 'ammunition-44-magnum-nb', 'ammunition-357-magnum-nb', 'ammunition-9mm-and-7-65mm-nb', 'ammunition-5-56mm-rifle-nb', 'ammunition-7-62mm-rifle-nb', 'ammunition-tracer-cartridge-nb', 'ammunition-hollow-point-surcharge-nb', 'ammunition-full-metal-jacketed-surcharge-nb', 'ammunition-teflon-armor-piercing-surcharge-nb', 'ammunition-exploding-shell-surcharge-nb', 'ammunition-dum-dum-surcharge-nb', '40mm-grenade-cartridge-nb', 'padded-or-quilt-armor-nb', 'soft-leather-armor-nb', 'studded-leather-armor-nb', 'chain-mail-nb', 'scale-mail-nb', 'plate-and-mail-nb', 'plate-armor-nb', 'plastic-plated-armor-nb', 'concealed-armor-nb', 'riot-jacket-nb', 'armor-vest-nb', 'point-blank-vest-nb', 'hard-armor-vest-nb', 'frag-cape-vest-nb', 'riot-armor-nb', 'hard-armor-nb', 'class-4-armor-nb', 'binocular-best-magnification-nb', 'binocular-medium-magnification-nb', 'binocular-low-magnification-nb', 'weapon-sight-best-magnification-nb', 'weapon-sight-medium-magnification-nb', 'weapon-sight-low-magnification-nb', 'infrared-goggles-mercury-battery-type-nb', 'infrared-goggles-new-superior-type-nb', 'infrared-binoculars-nb', 'infrared-monocular-eyepiece-nb', 'infrared-weapon-sight-nb', 'infrared-distancing-binoculars-nb', 'ultraviolet-optic-system-nb', 'night-sight-goggles-nb', 'night-sight-binoculars-nb', 'night-sight-monocular-eyepiece-nb', 'night-sight-weapon-sight-nb', 'pocket-night-viewer-nb', 'night-sight-large-tripod-mount-nb', 'thermo-imager-goggles-nb', 'thermo-imager-binoculars-nb', 'thermo-imager-monocular-eyepiece-nb', 'thermo-imager-weapon-sight-nb', 'multi-optics-helmet-m-o-h-nb', 'optics-band-nb', 'pocket-range-finder-nb', 'illuminating-peglight-nb');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('zzzzzzzzzzzzz-nb-gear-d-accessories-armor-optics.sql');
