-- The 18 spells of Spoiling Magic, Rifts World Book 18: Mystic Russia
-- pp.76-79. Batch 1 of the mystic-russia ingestion.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/zzzzzzzzzz-mr-spoiling-spells.sql
--
-- Read from the book's TEXT LAYER (.cache/books/mystic-russia, page_offset 1),
-- parsed rather than transcribed: the level comes from the book's own
-- `Level N` heading, never from a description, and every block was cut at its
-- title so no spell can inherit its neighbour's prose.
--
-- THE NAME PREFIX IS DECISION D1 in apps/character-creator/docs/surveys/
-- mystic-russia.md. This catalog namespaces a tradition's spells - 365 of its
-- 773 rows do - and the precedent is New West's `Clouds of ...` families and
-- Underseas' `Spellsong` and `Dolphin`. None of these 18 collides with an
-- existing row, checked with prefixes and plurals folded, so no row here needs
-- `same_spell_as` and NO EXISTING ROW CHANGES VALUE.
--
-- `tradition = 'spoiling'` is the functional half and is NOT decoration: a
-- level-gated spell pick reaches a tradition only when the class names it in
-- magic.spell_traditions_allowed (js/leveling.js). It is its own value rather
-- than being folded in with the book's other three because the book gates it
-- outright - "Spoiling magic is exclusive to the various Witch O.C.C.s and no
-- other" (printed 76). A shared value would hand it to the Necromancer.
--
-- Levels run L1:4 L2:2 L3:2 L4:2 L5:2 L6:2 L7:1 L8:2 L10:1. THE BOOK HAS NO LEVEL NINE HERE - its headings go
-- Level Eight then Level Ten, verified against every `Level N` heading in the
-- band. Nothing was dropped.
--
-- Two costs are schedules rather than numbers, so `ppe` holds the minimum and
-- `ppe_note` carries the rest, per migration 021: Wither Thy Enemies (30 vs
-- mortals, 60 vs Mega-Damage beings) and Demon Charms (75 temporary, 200
-- permanent).

INSERT INTO spells
  (name, level, ppe, ppe_note, variant_note, source, source_book, system, range, duration, damage, saving_throw, area_of_effect, casting_time, description, same_spell_as, tradition)
VALUES
  ('Spoiling: Sense Poison', 1, 3, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.76', 'rifts', 'Touch or within 12 feet (3.6 m); line of sight. Can be performed on oneself or two others by touch.', 'The sensing ability lasts for five minutes per level of the spell caster.', NULL, 'Not applicable.', NULL, NULL, 'The character can sense if the food has been poisoned, even if it appears to be perfectly fine. Moreover, he or she knows exactly what the poison is and the level of danger it represents.', NULL, 'spoiling'),
  ('Spoiling: Sense Bad Food & Drink', 1, 4, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.76', 'rifts', 'Touch or within 12 feet (3.6 m); line of sight. Can be performed on oneself or two others by touch.', 'The sensing ability lasts for five minutes per level of the spell caster.', NULL, 'Not applicable.', NULL, NULL, 'The character can sense if food or drink is spoiled or magically tainted even if it appears to be perfectly fine. The sense is so acute that those enchanted can pinpoint the specific tainted food or drink out of a banquet table full of food.', NULL, 'spoiling'),
  ('Spoiling: Spoil Water', 1, 3, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.76', 'rifts', 'Touch or within 40 feet (12.2 m).', 'Permanent', NULL, '-4 to save because the target is not a living creature. As much as ten gallons per level of the witch can be affected. A successful save means the magic fails and has no effect.', NULL, NULL, 'The witch spoils the water or any type of drink by spitting into it. The water is discolored, has a slight odor, and tastes so bitter or acidic that it is impossible to drink. Water blessed by a priest or Old Believer, as well as holy water and alcohol, are impervious to this magic.', NULL, 'spoiling'),
  ('Spoiling: Curdle Milk', 1, 3, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.76', 'rifts', 'Touch or within 40 feet (12.2 m).', 'Permanent', NULL, '-4 to save because the target is not a living creature. A successful save means the magic fails and has no effect.', NULL, NULL, 'The Night Witch can spoil and cause milk (any kind) to curdle by either dipping her finger into the milk, or by staring at it for one full melee round (15 seconds). As much as five gallons per level of the witch can be affected. The milk is sour and foul smelling, and impossible to drink. This power can also be used to ruin fruit juices, cottage cheese, cream, ice cream and butter Level Two', NULL, 'spoiling'),
  ('Spoiling: Spoil Wine', 2, 6, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Touch or within 40 feet (12.2 m).', 'Permanent', NULL, '-4 to save because the target is not a living creature. A successful save means the magic fails and has no effect.', NULL, NULL, 'In much the same way that the Night Witch can spoil milk (any kind) by dipping her finger into the liquid, or by staring at it for one full melee round (15 seconds), she can turn wine to vinegar. As much as two gallons per level of the witch can be affected.', NULL, 'spoiling'),
  ('Spoiling: Spoil Eggs', 2, 6, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Touch or within 40 feet (12.2 m).', 'Permanent', NULL, '-4 to save because the target is not a living creature. A successful save means the magic fails and has no effect.', NULL, NULL, 'The Night Witch can rot fresh eggs (any kind) still in their shell or eggs prepared for eating by touching them (affecting as many as she can hold in her arms) or by staring at them for one full melee round (15 seconds). As much as two dozen per level of the witch can be affected. The moment the egg is cracked open there is a foul smell, indicating the egg is no good, and the yoke is grey with specks of blood. Level Three', NULL, 'spoiling'),
  ('Spoiling: Spoil Sleep', 3, 8, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Touch or up to 60 feet (18.3 m) away; line of sight.', 'Eight hours per level of the spell caster.', 'Superficial, but those deprived of sleep will be tired, irritable and function in a reduced capacity; reduce initiative by half, Spd by 30% and skill performance by 30%.', 'Standard', NULL, NULL, 'Causes the bed to become infested with bedbugs, fleas, spiders, cockroaches, mice and similar small but disgusting biting and squirming creatures. No matter what is done, the bed remains infested with the creatures, making sleep even in the same room impossible. The witch can cancel the magic at any time, or the bed can be "cleansed" through Dispel Magic, Remove Curse, and Circle of Protection: Superior.', NULL, 'spoiling'),
  ('Spoiling: Use Poison Flawlessly', 3, 6, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Self or as many as two others by touch.', 'Five minutes per level of the spell caster.', NULL, 'Not applicable.', NULL, NULL, 'When this spell is cast, the witch can use poisonous, toxic, and acidic substances without fear of infecting herself, spilling a pinch, or misuse. All brews, concoctions and applications are mixed or applied perfectly. Level Four', NULL, 'spoiling'),
  ('Spoiling: Cursed Bread', 4, 10, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'The cursed bread affects all who eat it.', 'Symptoms and penalties last two hours per level of the witch.', NULL, 'For those eating the bread the save is standard. A successful save means the magic has no ill effect.', NULL, NULL, 'Note: Can curse two loaves of bread per level of experience. Those who eat the cursed bread suffer from bloating, stomach pain and 1D6 points of damage direct to Hit Points. Penalties last for two hours per level of the witch: -2 on initiative, -1 to on all combat maneuvers, and reduce speed and skill performance by 10%. The magic Negate Poisons spell will negate the symptoms and penalties, but not the damage inflicted. Those who are impervious to poison are not affected. Mega-Damage creatures only suffer one point of damage and -1 on initiative as they feel a little light-headed.', NULL, 'spoiling'),
  ('Spoiling: Dry Mother''s Milk', 4, 13, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Touch or within 60 feet (18.3 m).', '24 hours per level of the spell caster.', NULL, '-1 to save because the target is typically an animal. A successful save means the magic fails and has no effect.', NULL, NULL, 'By tying a knot in a milking animal''s tail, that animal can no longer give milk until the knot is undone or cut out, and a successful Remove Curse is performed, or the spell duration lapses. It causes the afflicted cow, goat or similar milk giving animal to go dry; incapable of giving milk. The Night Witch can stop the curse at any time. It also stops when the witch is slain. This magic can also afflict human mothers trying to breast feed; same basic process but with the witch pinching a breast. The milk from animals such as cows and goats is usually very important to farmers and peasants. The purpose of this cruel magic is to prevent proper nourishment and confound farmers and herdsmen. In some cases, depriving an entire village or farmstead. Level Five', NULL, 'spoiling'),
  ('Spoiling: Impervious to Disease', 5, 13, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Self or as many as two others by touch.', '30 minutes per level of the spell caster.', NULL, 'Not applicable.', NULL, NULL, 'The individual(s) protected by this magic is immune to all normal and magical diseases, no matter how potent, deadly or debilitating.', NULL, 'spoiling'),
  ('Spoiling: Spoil & Taint Food', 5, 15, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.77', 'rifts', 'Touch and sprinkle of component.', 'Permanent', NULL, '-4 to save because the target is not a living creature. The base save is 12, but a successful save means the magic fails and has no effect. People who eat spoiled food must make a save vs non-lethal poison (16 or higher), although the damage inflicted may be deadly to children, the sick and elderly.', NULL, NULL, 'A spell that requires the symbolic sprinkling of a pinch of living or powdered insects (typically fly larvae/maggots) or other poisonous or repulsive substance. Affects up to 20 pounds (9 kg) of food per level of the witch. She can affect any food from grains to processed meats and canned foods. Every item touched even by a single grain of the sprinkled substance is spoiled. In each case, !D6xlO% of the food +2% per level of experience is obviously spoiled, but the rest can be salvaged. However, the salvaging of edible food may be too time intensive to make it practical to save much if any of it. The Cause of the spoiling is one of the following: Spoiled by insect infestation; Mold and mildew; Rot and bacteria; Vermin and/or then- waste (mice, rats, etc.). Note: Eating spoiled food results in food poisoning that inflicts 3D6 points of damage direct to Hit Points, unless the victim makes a successful save vs poison. A successful save means no damage and all penalties are reduced to half. A failed roll to save means the character suffers the 3D6 damage to Hit Points, plus feels feverish, dizzy and nauseous (no initiative, -2 on all combat maneuvers, and reduce speed and skill performance by 25%). Symptoms and penalties linger for 1D4 days. The magic Negate Poisons spell will negate the symptoms and penalties, but not the damage inflicted. Those who are impervious to poison are not affected. Mega-Damage creatures only suffer one point of damage and -1 on initiative as they feel a little light-headed. Level Six', NULL, 'spoiling'),
  ('Spoiling: Spoil Concentration', 6, 15, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.78', 'rifts', 'Touch or within 60 feet (18.3 m); line of vision.', 'One hour per level of the spell caster.', NULL, 'Standard', NULL, NULL, 'The victim is easily distracted and not very alert or focused, missing even many obvious things. Reduce skill performance by 10%, initiative by half, and -1 melee attacks/actions. Remove Curse and Restoration spells will restore the concentration and negate any skill penalties. Psionic probes will reveal a magical mental block but only the psionic powers of Hypnotic Suggestion (used in this case, to remove the magical block) and Mind Bond, or the Mind Bleeder''s power of Mental Block Removal can destroy the magic and restore spoiled concentration.', NULL, 'spoiling'),
  ('Spoiling: Track Thy Enemy', 6, 15, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.78', 'rifts', 'Self or other by touch; line of sight up to 40 feet (12m) away.', 'One hour per level of the spell caster, or until the soil is spilled or put down.', NULL, '16, standard for rituals. A failed roll means the victim can be easily followed wherever he goes. A successful save means the magic fails. New components must be gathered to attempt the magic again.', NULL, NULL, 'The Witch gathers the soil around the footprint of the character she intends to track. The soil is put in a small bag or pouch and either hung around the neck or held in hand. The tracking ability can be transferred to one of her demon minions or human henchmen by touch while the spell is being cast. Whomever the tracker may be, it is that individual who must hold onto the soil. As long as that character wears or holds the soil, he can track that one person (or animal) flawlessly (98%). The moment the small bag of soil is put down or spilled, the magic is broken. Those magically pursued in this fashion can not successfully cover or hide their trail from this enchanted tracker, not even by climbing a tree or walking through water. Flying disrupts the tracking enchantment, but even then, the tracker will have a genuine idea of what direction the character has travelled, and can pick up the trail at a later time where the pursued sets his feet back to Earth. Level Seven', NULL, 'spoiling'),
  ('Spoiling: Spoil Memory', 7, 20, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.78', 'rifts', 'Touch or within 60 feet (18.3 m); line of vision.', 'One hour per level of the spell caster.', NULL, '-2 to save.', NULL, NULL, 'The victim can either be made to have trouble remembering things in general (the performance of all skills are -20% and they take 25% longer to perform), or to forget one small, specific thing, such as having seen the witch or one of her associates, the date and/or time of an appointment, the name of a particular person, the location of a particular item, and so on. In the alternative, one entire skill, fighting ability, spell, or memory of a specific person or event can be temporarily spoiled and forgotten, but it will return as soon as the spell duration lapses or the witch is slain. Of course, the witch can remove the spell at any time. Remove Curse and Restoration spells will restore the memory and negate any skill penalties. Psionic probes will reveal a magical mental block but only the psionic powers of Hypnotic Suggestion (used in this case, to remove the magical block) and Mind Bond, or the Mind Bleeder''s power of Mental Block Removal, can destroy the magic and restore spoiled memory. Level Eight', NULL, 'spoiling'),
  ('Spoiling: Spoil the Mind with Numbing Madness', 8, 25, NULL, NULL, 'import', 'Rifts World Book 18: Mystic Russia p.78', 'rifts', 'Touch or within 60 feet (18.3 m); line of vision.', 'Three minutes per level of the spell caster.', NULL, 'Standard', NULL, NULL, 'The afflicted individual stares out blindly, reacting only to attacks specifically directed at him. During this period, the victim froths at the mouth and is incapable of performing skills, taking action (other than self-defense), speaking or thinking. While under the enchantment, he or she can be led by the hand, pushed or dragged, and similarly manipulated, provided the manipulator has no ill intent on the individual. However, the afflicted character will instantly recognize the evil mage who has ruined his mind. All other people are barely noticed. If he should slay the Night Witch, the magic is instantly broken and all others cursed by the witch are restored to normal.', NULL, 'spoiling'),
  ('Spoiling: Wither Thy Enemies', 8, 30, '30 against mortals, 60 against Mega-Damage beings who are not supernatural or creatures of magic (they are immune).', NULL, 'import', 'Rifts World Book 18: Mystic Russia p.79', 'rifts', '10 miles (16 km) per level of the spell caster. This is a ritual requiring the enchantment of components. The victim must be within the range of the spell to be affected.', 'Until the victim dies or the magic spell is broken.', 'See penalties and wasting below. Can result in death.', 'Special; see below. -2', NULL, NULL, 'This spoiling magic makes its victim sick and waste away. It requires bits of the intended victim''s hair or that person''s footprint to cast harmful magic upon him. In the latter case, the Witch gathers the soil around the footprint and puts it in a bag or pouch and attaches it to a tree or chimney. As the hair or earth dries, so too does the victim of the enchantment wither away. The victim suffers from an unquenchable thirst, feels feverish and hot. With each passing day the victim looks more worn out and gaunt, regardless of how much rest, food or water he might get. Suffers the following penalties and deterioration with each passing day: -1 point from S.D.C. and Hit Points, -1 from Spd attribute, -5% to skill performance, and healing potions and magic have no effect. After the tenth day, the victim also sees his attacks/actions per melee round reduced by half and any combat bonuses reduced to zero. He continues to wither and waste away until down to six hit points. At this point the character gets to try to save vs magic. If that roll fails, the character will lapse into a coma and die in six days! The witch can break the spell at any time. The spell can also be instantly broken by finding the bag with the soil or hair, removing it from its perch in a tree or on a chimney and spilling the contents on the ground, or by killing the witch responsible. A successful Remove Curse can also break the spell. Moving out of range of the magic only offers conditional relief; the disease stops progressing, but the victim does not recover any Hit Points or S.D.C. by any means. Furthermore, the ailment continues the moment he reenters the enchanted area around the sack. Level Ten', NULL, 'spoiling'),
  ('Spoiling: Demon Charms', 10, 75, '75 for a temporary cursed item, 200 to make the item permanently cursed. Permanently enchanted items have 50', NULL, 'import', 'Rifts World Book 18: Mystic Russia p.79', 'rifts', 'Touch or within 60 feet (18.3 m); line of vision.', 'The toxic magic on the enchanted object lasts for 15 minutes per level of the spell caster, and poisons every bit of food or drink it touches. The venomous curse on the object can be made permanent as well.', NULL, 'Standard', NULL, NULL, 'M.D.C. but can be destroyed. Furthermore, all such cursed items become inert and return to the ordinary the instant the evil witch dies. These cursed "charms" are not pieces of jewelry but utensils used in the preparation, serving or eating of food and drinks. The Night Witch has the power to enchant one particular object such as a fork, spoon, ladle, pot, pan, pitcher, goblet, glass, etc., cursed with spoilage. Any food it touches (or in the case of pots, pans and other containers, any food or drink placed inside it) becomes magically, but imperceptibly spoiled/poisoned. In this particular case, the food or drink is not obviously tainted and tastes good. However, all who eat the bad food get seriously ill. Eating the bad food inflicts 6D6 points of damage directly to Hit Points, unless the victim makes a successful save vs lethal poison. A successful save means no damage and all penalties from illness are reduced to half. Duration is also halved. A failed roll to save means the character takes 6D6 points of damage directly to Hit Points, plus suffers from high fever, dizziness, headache and nausea. Penalties: No initiative, reduce combat bonuses, attacks per melee round, speed and skill performance by 50%! Symptoms and penalties linger for 1D4+2 days. Victims also continue to suffer 1D6 points of damage, directly to Hit Points, every day that they are ill! Vile witches can make entire communities sick, and kill scores of people (children and the elderly being the most susceptible) by using one such item. Just imagine the harm that could be done by serving stew or soup with a cursed Demon Charmed ladle at a church or social function - each scoop of food is sickness and potential death. The magic Negate Poison spell will prevent further physical damage but the symptoms and penalties persist unabated. Only the witch who made the cursed item(s) or a successful Remove Curse spell can negate the penalties and illness. Note: Those who are impervious to poison are not affected. Mega-Damage creatures only suffer 2D6 M.D. and 1D4 M.D. per each subsequent day, and all penalties are half of those previously noted.', NULL, 'spoiling');

-- Read the result back.
SELECT 'spoiling spells inserted' AS assertion, count(*) AS got, 18 AS want
  FROM spells WHERE tradition = 'spoiling';

SELECT 'every one is prefixed' AS assertion, count(*) AS got, 18 AS want
  FROM spells WHERE tradition = 'spoiling' AND name LIKE 'Spoiling: %';

SELECT 'every one cites this book by page' AS assertion, count(*) AS got, 18 AS want
  FROM spells WHERE tradition = 'spoiling'
   AND source_book LIKE 'Rifts World Book 18: Mystic Russia p.%';

SELECT 'every one carries a cost' AS assertion, count(*) AS got, 18 AS want
  FROM spells WHERE tradition = 'spoiling' AND ppe > 0;

SELECT 'every one carries a description' AS assertion, count(*) AS got, 18 AS want
  FROM spells WHERE tradition = 'spoiling' AND length(description) > 40;

SELECT 'the two variable costs carry their schedule' AS assertion, count(*) AS got, 2 AS want
  FROM spells WHERE tradition = 'spoiling' AND ppe_note IS NOT NULL;

SELECT 'no existing row was touched' AS assertion, count(*) AS got, 0 AS want
  FROM spells WHERE tradition = 'spoiling' AND source <> 'import';

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('zzzzzzzzzz-mr-spoiling-spells.sql');
