-- Step 4 of the Nightbane extraction plan (apps/character-creator/docs/surveys/nightbane-core.md):
-- Ancient, oriental and exotic weapons and ninja equipment. Printed 204-209. 114 rows.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/zzzzzzzzzzzzz-nb-gear-a-ancient-weapons.sql
--
-- D4 (#1126): every item in the equipment chapter is its own `nightbane` row, on
-- Nate's word, read off the Nightbane pages rather than shared with Heroes Unlimited's
-- rows for the near-identical chapter. HU's scripts (add-hu-gear-*.sql) are the
-- PRECEDENT for shape - names, where a combined entry splits into priced rows, which
-- column a number goes in - and each row here was diffed against its HU counterpart
-- to catch misreads. Where the two books disagree, this file holds what Nightbane
-- prints; the PR lists every disagreement and its evidence.
--
-- Slugs are the name plus `-nb`, so no Nightbane row can collide with a row of
-- another game. `cost` is dollars, a range's low end; NULL where the page prints no
-- price, with any printed wording in cost_note. Citations are printed folios
-- (cache page = folio + 1).

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('axe-battle-nb', 'Axe, Battle', 'nightbane', 'weapon', 4.6, 240, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Axes, ancient weapons table, printed 204. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.204'),
  ('axe-throwing-nb', 'Axe, Throwing', 'nightbane', 'weapon', 3, 100, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Axes, ancient weapons table, printed 204. One-handed. Average length .4m/1.25ft.', 'Nightbane RPG p.204'),
  ('axe-stone-nb', 'Axe, Stone', 'nightbane', 'weapon', 4, 100, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Axes, ancient weapons table, printed 204. One-handed. Average length .6m/2.0ft. Printed 204 gives the weight as 1.8kg/4.0kg - the second unit is the book''s own slip for lb.', 'Nightbane RPG p.204'),
  ('axe-bipennis-2-head-nb', 'Axe, Bipennis (2-head)', 'nightbane', 'weapon', 6, 120, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Axes, ancient weapons table, printed 204. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.204'),
  ('oncin-pick-nb', 'Oncin Pick', 'nightbane', 'weapon', 4, 220, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Axes, ancient weapons table, printed 204. Two-handed. Average length 1.0m/3.75ft. Spelled Oncin Pick on printed 204 and transcribed as printed.', 'Nightbane RPG p.204'),
  ('awl-pike-nb', 'Awl Pike', 'nightbane', 'weapon', 6, 445, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 3.2m/10ft.', 'Nightbane RPG p.204'),
  ('beaked-axe-nb', 'Beaked Axe', 'nightbane', 'weapon', 5, 540, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.3m/7.5ft. Printed 204 lists a SECOND, different Beaked Axe under Spears - 1.4m/4.5ft, 1-8, $430. Two weapons, one name; this is the pole arm.', 'Nightbane RPG p.204'),
  ('berdiche-nb', 'Berdiche', 'nightbane', 'weapon', 7, 550, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.1m/7.0ft.', 'Nightbane RPG p.204'),
  ('glaive-nb', 'Glaive', 'nightbane', 'weapon', 6, 540, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.3m/7.5ft.', 'Nightbane RPG p.204'),
  ('guisarme-nb', 'Guisarme', 'nightbane', 'weapon', 6, 550, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.5m/7.25ft.', 'Nightbane RPG p.204'),
  ('halberd-nb', 'Halberd', 'nightbane', 'weapon', 5, 660, NULL, '3-18', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.2m/7.25ft.', 'Nightbane RPG p.204'),
  ('sabre-halberd-nb', 'Sabre Halberd', 'nightbane', 'weapon', 7, 650, NULL, '3-18', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.4m/8.0ft.', 'Nightbane RPG p.204'),
  ('hippe-nb', 'Hippe', 'nightbane', 'weapon', 6, 750, NULL, '3-18', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.3m/7.5ft.', 'Nightbane RPG p.204'),
  ('lucerne-hammer-nb', 'Lucerne Hammer', 'nightbane', 'weapon', 6.5, 540, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.9m/9.75ft.', 'Nightbane RPG p.204'),
  ('military-fork-nb', 'Military Fork', 'nightbane', 'weapon', 5, 330, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.1m/7.0ft.', 'Nightbane RPG p.204'),
  ('pike-nb', 'Pike', 'nightbane', 'weapon', 8, 445, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 5.0m/16ft.', 'Nightbane RPG p.204'),
  ('runka-nb', 'Runka', 'nightbane', 'weapon', 6, 445, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.3m/7.5ft.', 'Nightbane RPG p.204'),
  ('scythe-nb', 'Scythe', 'nightbane', 'weapon', 5, 445, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.4m/8.0ft.', 'Nightbane RPG p.204'),
  ('voulge-nb', 'Voulge', 'nightbane', 'weapon', 5, 550, NULL, '3-18', 0, NULL, NULL, NULL, NULL, NULL, 'Pole arms, ancient weapons table, printed 204. Two-handed. Average length 2.1m/7.0ft.', 'Nightbane RPG p.204'),
  ('short-spear-nb', 'Short Spear', 'nightbane', 'weapon', 4, 130, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Spears, ancient weapons table, printed 204. One-handed. Average length 1.2-1.8m/4-6ft.', 'Nightbane RPG p.204'),
  ('long-spear-nb', 'Long Spear', 'nightbane', 'weapon', 6.5, 180, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Spears, ancient weapons table, printed 204. Two-handed. Average length 2.1-3.0m/7-10ft.', 'Nightbane RPG p.204'),
  ('javelin-nb', 'Javelin', 'nightbane', 'weapon', 4, 180, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Spears, ancient weapons table, printed 204. One-handed. Average length 2.1m/7.0ft.', 'Nightbane RPG p.204'),
  ('beaked-axe-spear-nb', 'Beaked Axe (spear)', 'nightbane', 'weapon', 5, 430, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Spears, ancient weapons table, printed 204. One-handed. Average length 1.4m/4.5ft. Printed 204 heads this row Beaked Axe, the same name it gives a POLE ARM earlier in the table at 2.3m/7.5ft, 2-12, $540. The qualifier is added here so the two are separable; the book prints the bare name.', 'Nightbane RPG p.204'),
  ('trident-nb', 'Trident', 'nightbane', 'weapon', 4, 240, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Spears, ancient weapons table, printed 204. Two-handed. Average length 1.5m/5.0ft.', 'Nightbane RPG p.204'),
  ('lance-nb', 'Lance', 'nightbane', 'weapon', 8, 460, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Spears, ancient weapons table, printed 204. One-handed. Average length 4.0m/13ft.', 'Nightbane RPG p.204'),
  ('daggers-and-knives-nb', 'Daggers and Knives', 'nightbane', 'weapon', 1, 30, '$30-100', '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Knives, ancient weapons table, printed 204. One-handed. Average length .2-.5m/10-20in..', 'Nightbane RPG p.204'),
  ('short-sword-nb', 'Short Sword', 'nightbane', 'weapon', 3, 240, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Short swords, ancient weapons table, printed 205. One-handed. Average length .7m/2.5ft.', 'Nightbane RPG p.205'),
  ('sabre-nb', 'Sabre', 'nightbane', 'weapon', 3, 230, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Short swords, ancient weapons table, printed 205. One-handed. Average length .6m/2.0ft.', 'Nightbane RPG p.205'),
  ('scimitar-nb', 'Scimitar', 'nightbane', 'weapon', 3.5, 235, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Short swords, ancient weapons table, printed 205. One-handed. Average length .7m/2.5ft.', 'Nightbane RPG p.205'),
  ('falchion-nb', 'Falchion', 'nightbane', 'weapon', 4, 350, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Short swords, ancient weapons table, printed 205. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.205'),
  ('cutlass-nb', 'Cutlass', 'nightbane', 'weapon', 3, 235, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Short swords, ancient weapons table, printed 205. One-handed. Average length .6m/2.0ft.', 'Nightbane RPG p.205'),
  ('bastard-nb', 'Bastard', 'nightbane', 'weapon', 4.5, 450, NULL, '1-8+2', 0, NULL, NULL, NULL, NULL, NULL, 'Large swords, ancient weapons table, printed 205. Two-handed. Average length 1.0m/3.75ft.', 'Nightbane RPG p.205'),
  ('broadsword-nb', 'Broadsword', 'nightbane', 'weapon', 3.5, 340, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Large swords, ancient weapons table, printed 205. One-handed. Average length .9m/3.0ft.', 'Nightbane RPG p.205'),
  ('claymore-nb', 'Claymore', 'nightbane', 'weapon', 6.5, 560, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Large swords, ancient weapons table, printed 205. Two-handed. Average length 1.2m/4.0ft. Printed 205 separates the two weights with a dash (2.9kg - 6.5lb) rather than a slash.', 'Nightbane RPG p.205'),
  ('flamberge-nb', 'Flamberge', 'nightbane', 'weapon', 7.5, 670, NULL, '3-18', 0, NULL, NULL, NULL, NULL, NULL, 'Large swords, ancient weapons table, printed 205. Two-handed. Average length 1.3m/4.25ft.', 'Nightbane RPG p.205'),
  ('long-sword-nb', 'Long Sword', 'nightbane', 'weapon', 3.5, 455, NULL, '1-8+2', 0, NULL, NULL, NULL, NULL, NULL, 'Large swords, ancient weapons table, printed 205. One-handed. Average length .9m/3.0ft.', 'Nightbane RPG p.205'),
  ('2-handed-espandon-nb', '2-handed Espandon', 'nightbane', 'weapon', 4.5, 460, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Large swords, ancient weapons table, printed 205. Two-handed. Average length .9m/3.0ft.', 'Nightbane RPG p.205'),
  ('ball-and-chain-nb', 'Ball and Chain', 'nightbane', 'weapon', 4.5, 250, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Ball and chain, ancient weapons table, printed 205. One-handed. Average length .9m/3.0ft.', 'Nightbane RPG p.205'),
  ('flail-nb', 'Flail', 'nightbane', 'weapon', 5.5, 355, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Ball and chain, ancient weapons table, printed 205. Two-handed. Average length 1.6m/5.25ft.', 'Nightbane RPG p.205'),
  ('goupillon-flail-nb', 'Goupillon Flail', 'nightbane', 'weapon', 4.5, 460, NULL, '3-18', 0, NULL, NULL, NULL, NULL, NULL, 'Ball and chain, ancient weapons table, printed 205. Two-handed. Average length .5m/2.0ft.', 'Nightbane RPG p.205');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('mace-and-chain-nb', 'Mace and Chain', 'nightbane', 'weapon', 4.5, 280, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Ball and chain, ancient weapons table, printed 205. One-handed. Average length .9m/3.0ft.', 'Nightbane RPG p.205'),
  ('nunchaku-nb', 'Nunchaku', 'nightbane', 'weapon', 2.5, 30, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Ball and chain, ancient weapons table, printed 205. Two-handed. Average length .8m/2.75ft. Also described on printed 207 (usually called Numchuks): can be used as a paired weapon for striking, and can entangle only if one weapon is used with two hands. That entry prices it at $30 each, 1D8 - the same as this table row, so it is one row.', 'Nightbane RPG p.205'),
  ('arab-mace-nb', 'Arab Mace', 'nightbane', 'weapon', 3, 240, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .6m/2.0ft.', 'Nightbane RPG p.205'),
  ('mace-nb', 'Mace', 'nightbane', 'weapon', 4.5, 240, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .7m/2.5ft.', 'Nightbane RPG p.205'),
  ('cudgel-nb', 'Cudgel', 'nightbane', 'weapon', 2.5, 240, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.205'),
  ('club-stick-pipe-nb', 'Club/Stick/Pipe', 'nightbane', 'weapon', 3, 10, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.205'),
  ('hercules-club-nb', 'Hercules Club', 'nightbane', 'weapon', 5.5, 260, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. Two-handed. Average length 1.2m/4.0ft.', 'Nightbane RPG p.205'),
  ('horseman-hammer-nb', 'Horseman Hammer', 'nightbane', 'weapon', 3.5, 145, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.205'),
  ('maul-nb', 'Maul', 'nightbane', 'weapon', 4, 100, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length 1.2m/4.0ft.', 'Nightbane RPG p.205'),
  ('morning-star-nb', 'Morning Star', 'nightbane', 'weapon', 2.5, 240, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .8m/2.75ft.', 'Nightbane RPG p.205'),
  ('war-club-wood-nb', 'War Club (wood)', 'nightbane', 'weapon', 3, 75, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .9m/3.0ft.', 'Nightbane RPG p.205'),
  ('war-hammer-nb', 'War Hammer', 'nightbane', 'weapon', 4.5, 190, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Blunt weapons, ancient weapons table, printed 205. One-handed. Average length .7m/2.5ft.', 'Nightbane RPG p.205'),
  ('short-staff-nb', 'Short Staff', 'nightbane', 'weapon', 3, 120, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Staves, ancient weapons table, printed 205. One-handed. Average length 1.2-1.8m/4-6ft. Printed 205 heads this row simply Short, under STAVES. Named in full here so it is legible out of the table.', 'Nightbane RPG p.205'),
  ('long-staff-nb', 'Long Staff', 'nightbane', 'weapon', 5, 125, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Staves, ancient weapons table, printed 205. Two-handed. Average length 1.9-2.7m/7-9ft. Printed 205 heads this row simply Long, under STAVES.', 'Nightbane RPG p.205'),
  ('bo-staff-nb', 'Bo Staff', 'nightbane', 'weapon', 3, 120, 'the book prints two prices: $120 in the description on printed 206, $140 in the table on printed 205', '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Staves, ancient weapons table, printed 205. Two-handed. Average length 2.8m/9.5ft. Printed 206 describes it: staff techniques were probably most advanced in the martial arts schools of samurai Japan, and the staff should be about a foot taller than its owner. PRICE: the table on printed 205 gives $140 and the description on printed 206 gives $120; the description wins. The damage agrees - the table writes 1-8 and the description 1D8.', 'Nightbane RPG p.205-206'),
  ('quarterstaff-nb', 'Quarterstaff', 'nightbane', 'weapon', 3.5, 130, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Staves, ancient weapons table, printed 205. Two-handed. Average length 1.8m/6.0ft.', 'Nightbane RPG p.205'),
  ('iron-staff-nb', 'Iron Staff', 'nightbane', 'weapon', 7, 245, NULL, '1-8+2', 0, NULL, NULL, NULL, NULL, NULL, 'Staves, ancient weapons table, printed 205. Two-handed. Average length 1.8-2.1m/6-7ft.', 'Nightbane RPG p.205'),
  ('short-bow-nb', 'Short Bow', 'nightbane', 'weapon', 1, 130, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. Two-handed.', 'Nightbane RPG p.205'),
  ('arrows-short-bow-nb', 'Arrows (short bow)', 'nightbane', 'weapon', NULL, 20, '$20 per dozen', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. One-handed. Printed 205 indents this under Short Bow as simply Arrows; a second Arrows row sits under Long Bow at $40 a dozen.', 'Nightbane RPG p.205'),
  ('long-bow-nb', 'Long Bow', 'nightbane', 'weapon', 2, 270, NULL, '2-12', 0, NULL, NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. Two-handed.', 'Nightbane RPG p.205'),
  ('arrows-long-bow-nb', 'Arrows (long bow)', 'nightbane', 'weapon', NULL, 40, '$40 per dozen', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. One-handed. Printed 205 indents this under Long Bow as simply Arrows.', 'Nightbane RPG p.205'),
  ('cross-bow-nb', 'Cross Bow', 'nightbane', 'weapon', 7, 160, NULL, '1-8', 0, '500-700ft', NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. Two-handed. The book prints a RANGE where the other rows print a length: 500-700ft.', 'Nightbane RPG p.205'),
  ('bolts-nb', 'Bolts', 'nightbane', 'weapon', NULL, 35, '$35 per dozen', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. One-handed.', 'Nightbane RPG p.205'),
  ('sling-nb', 'Sling', 'nightbane', 'weapon', 0.125, 40, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Missile weapons, ancient weapons table, printed 205. One-handed. Printed weight is 2.0oz.', 'Nightbane RPG p.205'),
  ('black-jack-nb', 'Black Jack', 'nightbane', 'weapon', 3, 10, NULL, '1-4', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length 10in.', 'Nightbane RPG p.205'),
  ('dart-nb', 'Dart', 'nightbane', 'weapon', 0.375, 2, NULL, '1-4', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length 6.0in. Printed weight is 6oz.', 'Nightbane RPG p.205'),
  ('bull-whip-nb', 'Bull Whip', 'nightbane', 'weapon', 3, 60, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length 2.4m/8.0ft.', 'Nightbane RPG p.205'),
  ('cat-o-nine-tails-nb', 'Cat-o-Nine Tails', 'nightbane', 'weapon', 1, 100, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length .8m/3.0ft.', 'Nightbane RPG p.205'),
  ('meat-cleaver-nb', 'Meat Cleaver', 'nightbane', 'weapon', 1, 10, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length .3m/1.0ft.', 'Nightbane RPG p.205'),
  ('frying-pan-nb', 'Frying Pan', 'nightbane', 'weapon', 1, 10, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length .3m/1.0ft.', 'Nightbane RPG p.205'),
  ('hand-pick-nb', 'Hand Pick', 'nightbane', 'weapon', 0.5, 5, NULL, '1-4', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length 7.0in. Printed weight is 8.0oz.', 'Nightbane RPG p.205'),
  ('large-pick-mattock-nb', 'Large Pick/Mattock', 'nightbane', 'weapon', 5, 50, NULL, '1-8', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. Two-handed. Average length 1.2m/4.0ft.', 'Nightbane RPG p.205'),
  ('shovel-nb', 'Shovel', 'nightbane', 'weapon', 5, 40, NULL, '1-6', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. Two-handed. Average length 1.2m/4.0ft.', 'Nightbane RPG p.205'),
  ('hammer-tool-nb', 'Hammer (tool)', 'nightbane', 'weapon', 3, 10, NULL, '1-4', 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous (no W.P. bonuses), ancient weapons table, printed 205. One-handed. Average length 10in.', 'Nightbane RPG p.205'),
  ('aikuchi-tanto-nb', 'Aikuchi/Tanto', 'nightbane', 'weapon', NULL, 20, '$20 to $1,000, varying with quality and beauty', '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'Curved Japanese daggers. The Tanto has a hilt, the Aikuchi does not. Can also be thrown.', 'Nightbane RPG p.206'),
  ('bisento-nb', 'Bisento', 'nightbane', 'weapon', NULL, 600, NULL, '2D6', 0, NULL, NULL, NULL, NULL, NULL, 'A spear with a broad, curved blade, large enough to count as a kind of pole arm. Must be imported from Japan.', 'Nightbane RPG p.206'),
  ('blow-gun-nb', 'Blow Gun', 'nightbane', 'weapon', NULL, 45, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A favorite weapon of the ninja. Effective range no more than 50ft. THE DART ITSELF DOES NO DAMAGE - it is usually coated with poison or drugs, which is why the damage column is empty rather than zero.', 'Nightbane RPG p.206'),
  ('ninja-bow-nb', 'Ninja Bow', 'nightbane', 'weapon', NULL, 500, NULL, '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'Bows, printed 206. The ninja favored a short, none too powerful bow that could be disassembled and easily hidden. Effective range 400ft.', 'Nightbane RPG p.206'),
  ('samurai-long-bow-nb', 'Samurai Long Bow', 'nightbane', 'weapon', NULL, 1000, '$1,000 or more for high quality', '2D6', 0, NULL, NULL, NULL, NULL, NULL, 'Bows, printed 206. Probably the most powerful weapon of its type in the world; a separate skill learned by the ninja. Effective range 800ft.', 'Nightbane RPG p.206'),
  ('modern-commercial-hunting-bow-nb', 'Modern Commercial Hunting Bow', 'nightbane', 'weapon', NULL, 200, NULL, '1D10', 0, NULL, NULL, NULL, NULL, NULL, 'Bows, printed 206, priced beside the ninja and samurai bows as the modern commercial equivalent.', 'Nightbane RPG p.206');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('heavy-crossbow-nb', 'Heavy Crossbow', 'nightbane', 'weapon', NULL, 300, NULL, '2D6', 0, NULL, NULL, NULL, NULL, NULL, 'Crossbows, printed 206. Two-handed. Crossbows are now commonly available by mail order in the U.S.', 'Nightbane RPG p.206'),
  ('pistol-style-crossbow-nb', 'Pistol-Style Crossbow', 'nightbane', 'weapon', NULL, 150, NULL, '1D10', 0, NULL, NULL, NULL, NULL, NULL, 'Crossbows, printed 206. A 40lb pistol-style crossbow. Crossbows are now commonly available by mail order in the U.S.', 'Nightbane RPG p.206'),
  ('daisho-nb', 'Daisho', 'nightbane', 'weapon', NULL, 150, '$150 for fair quality, $1,200 for an authentic high quality', '1D8+2 (long), 1D6 (short)', 0, NULL, NULL, NULL, NULL, NULL, 'Literally "the long and the short": the traditional Japanese weapon made up of a Wakizashi and a Katana, which can be used as paired weapons. Using both together is a separate skill.', 'Nightbane RPG p.206'),
  ('jitte-or-sai-nb', 'Jitte or Sai', 'nightbane', 'weapon', NULL, 50, '$50 per pair', '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'Printed as Jitte or Sai (Paired Weapons). Oversized three-pronged forks, generally designed to be used as a pair, one in each hand. Excellent for countering the massive attack force of the samurai sword blade: a skilled user can entangle an opponent with one hand and attack with the other.', 'Nightbane RPG p.206'),
  ('katana-nb', 'Katana', 'nightbane', 'weapon', NULL, 300, 'from $300 for a manufactured version to at least $5,000 for top quality', '2D6 regular quality, 3D6 top quality (authentic)', 0, NULL, NULL, NULL, NULL, NULL, 'The primary weapon of the Samurai warrior; a long sword up to 3ft in length. There is an enormous difference in the quality of these weapons.', 'Nightbane RPG p.206'),
  ('kyoketsu-shogi-nb', 'Kyoketsu-Shogi', 'nightbane', 'weapon', NULL, 100, NULL, '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'Kusari-Gama/Kyoketsu-Shogi, printed 206-207. Made with rope, with an iron ring on one end and a double blade on the other; one end can entangle while the other strikes. Usually used as a climbing device, but doubles as a somewhat less damaging Kusari-Gama. Cannot be used by anyone not trained in hand to hand martial arts or assassin.', 'Nightbane RPG p.206-207'),
  ('kusari-gama-nb', 'Kusari-Gama', 'nightbane', 'weapon', NULL, 300, NULL, '1D10', 0, NULL, NULL, NULL, NULL, NULL, 'Kusari-Gama/Kyoketsu-Shogi, printed 206-207. A chain with a weight on one end and a sickle weapon on the other, another ninja favorite; one end can entangle while the other strikes. Cannot be used by anyone not trained in hand to hand martial arts or assassin.', 'Nightbane RPG p.206-207'),
  ('kawanga-nb', 'Kawanga', 'nightbane', 'weapon', NULL, 50, NULL, '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'A ninja combination of rope and grapple used for climbing and fighting. A separate chain weapon.', 'Nightbane RPG p.207'),
  ('manriki-gusari-nb', 'Manriki-Gusari', 'nightbane', 'weapon', NULL, 30, NULL, '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'A chain weapon with solid, blunt weights on each end, used like a Kusari-Gama - entangling with one end, striking with the other. Easy to disassemble and conceal, and easy to make from a length of chain and lead weights found in any hardware store.', 'Nightbane RPG p.207'),
  ('naginata-yari-nb', 'Naginata/Yari', 'nightbane', 'weapon', NULL, 150, NULL, '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'Naginata have curved blades and Yari straight ones; otherwise alike, and used as spears. Very difficult to conceal.', 'Nightbane RPG p.207'),
  ('no-dachi-nb', 'No-Dachi', 'nightbane', 'weapon', NULL, 750, '$750 and up', '3D6', 0, NULL, NULL, NULL, NULL, NULL, 'A huge two-handed sword, 5 to 6ft long, carried on the back and pulled from the scabbard over the shoulder. Does much more damage than most weapons in its class.', 'Nightbane RPG p.207'),
  ('sa-tjat-koen-nb', 'Sa Tjat Koen', 'nightbane', 'weapon', NULL, 150, NULL, '1D10', 0, NULL, NULL, NULL, NULL, NULL, 'A Malaysian weapon like Nunchaku with a second chain and third handle attached. Can entangle like nunchaku but can NOT be used as a paired weapon.', 'Nightbane RPG p.207'),
  ('shikomi-zue-nb', 'Shikomi-Zue', 'nightbane', 'weapon', NULL, 150, NULL, '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'A hollow bamboo staff with a concealed, spring-loaded blade, released by a trigger stud that can be pressed or turned. Ninja commonly disguised themselves as blindmen and carried it. Usable as a somewhat fragile (S.D.C. 50) Bo Staff or as a spear.', 'Nightbane RPG p.207'),
  ('shuriken-nb', 'Shuriken', 'nightbane', 'weapon', NULL, 5, '$5.00 each for high quality', '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'The famous "throwing stars" of the ninja, designed less for deadly effect than for ease of concealment and usefulness in discouraging an opponent''s pursuit.', 'Nightbane RPG p.207'),
  ('throwing-knives-japanese-nb', 'Throwing Knives (Japanese)', 'nightbane', 'weapon', NULL, 3, '$3.00 each for high quality', '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'Shuriken, printed 207, prices these beside shuriken and notes that throwing knives require a different technique than shuriken.', 'Nightbane RPG p.207'),
  ('wakizashi-nb', 'Wakizashi', 'nightbane', 'weapon', NULL, 300, 'varies with quality; printed 207 refers the reader to the Katana prices', '1D8 regular quality, 2D6 top quality', 0, NULL, NULL, NULL, NULL, NULL, 'The short sword favored by the samurai. The ninja short sword has a straighter blade but is otherwise just like a wakizashi.', 'Nightbane RPG p.207'),
  ('tonfa-nb', 'Tonfa', 'nightbane', 'weapon', NULL, 40, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'A short wood weapon ideal for parrying and close combat.', 'Nightbane RPG p.207'),
  ('climbing-claws-tekagi-or-shuko-nb', 'Climbing Claws (Tekagi or Shuko)', 'nightbane', 'gear', NULL, 85, '$85 per pair', '1', 0, NULL, NULL, NULL, NULL, NULL, 'Ninja equipment, generally not commonly available to the public. A metal or leather band that wraps around the palm between thumb and fingers, the inside surface carrying two to six spikes for climbing wood and stone surfaces. ADDS +15% TO CLIMBING SKILLS. The illustration on printed 208 labels it a climbing tool and weapon with a damage rating of 1.', 'Nightbane RPG p.208'),
  ('climbing-spikes-nb', 'Climbing Spikes', 'nightbane', 'gear', NULL, 45, '$45 per pair', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Ninja equipment. Spiked claws attached to the soles of the feet for climbing. ADDS +15% TO CLIMBING SKILL. Normal walking or running is impossible while wearing them.', 'Nightbane RPG p.208'),
  ('eggshell-bomb-nb', 'Eggshell Bomb', 'nightbane', 'gear', NULL, 5, '$5.00 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Ninja equipment. An eggshell filled with pepper, metal shavings and other secret substances; when tossed it shatters into a small cloud of blinding, irritating smoke. DOES NO DAMAGE, but all victims must save against poison gas. Blinded victims are -6 to strike, parry and dodge.', 'Nightbane RPG p.208'),
  ('ippon-sugi-nobori-nb', 'Ippon-Sugi Nobori', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Ninja equipment. A short length of spike-studded wood with ropes attached to each end, used much like a lumberjack''s or lineman''s leather climbing belt. ONLY for climbing trees and telephone poles. ADDS 25% TO CLIMBING SKILL.', 'Nightbane RPG p.208'),
  ('ninja-emergency-kit-nb', 'Ninja Emergency Kit', 'nightbane', 'gear', NULL, 120, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Ninja equipment; ninjas keep several hidden in various places. A small cloth bag holding a Kyoketsu-Shogi, 6 shuriken, 12 caltrops, a 3ft towel, a small cooking pot, paper and pencil, matches, a first-aid kit (bandages, disinfectant, small scissors, painkiller), lock picks, spare clothing, an eggshell filled with blinding powder, and enough rice, soybean curd and tea for 7 days of tight rations.', 'Nightbane RPG p.208'),
  ('ninja-clothing-nb', 'Ninja Clothing', 'nightbane', 'gear', NULL, 600, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Ninja equipment. Completely black for concealment in darkness or completely white for snow: jacket, hakama (pants), tabi (socks) and belt. Leggings, separate sleeves from elbow to back of hand, a groin protector and a body protector are made of quilted padding and used as protection. Numerous pockets and compartments conceal shuriken, garrote, caltrops, lock picks and other ninja items.', 'Nightbane RPG p.208'),
  ('chain-per-foot-nb', 'Chain (per foot)', 'nightbane', 'gear', NULL, 1, 'about $1.00 per foot; cost varies with thickness and tensile strength', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Rope and Chain, printed 208. Available in just about any hardware store. Modern chain is usually well tested and reinforced.', 'Nightbane RPG p.208'),
  ('rope-per-foot-nb', 'Rope (per foot)', 'nightbane', 'gear', NULL, NULL, 'about $.25 per foot - below the resolution of an integer cost column, so it is recorded here rather than rounded', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Rope and Chain, printed 208. Available in just about any hardware store. Modern rope is usually well tested and reinforced. Cost varies with thickness and tensile strength.', 'Nightbane RPG p.208'),
  ('ninja-rope-ladder-per-foot-nb', 'Ninja Rope Ladder (per foot)', 'nightbane', 'gear', NULL, NULL, '$.75 per foot - below the resolution of an integer cost column', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed as Rope Ladder. Loops knotted into it every two feet or so (depending on the height of the owner), with a 3 pound weight attached to the bottom end; the top end is often tied to a grappling hook. Easy to use and easy to conceal.', 'Nightbane RPG p.208'),
  ('tetsubishi-ninja-caltrops-nb', 'Tetsubishi (ninja caltrops)', 'nightbane', 'gear', NULL, 2, '$2.00 each', '1', 0, NULL, NULL, NULL, NULL, NULL, 'Ninja caltrops in a variety of styles, all designed so the metal barbs point upwards however they land. Damage is rarely more than 1 point, but someone with a caltrop in their foot is not likely to continue walking until they pull it out.', 'Nightbane RPG p.208'),
  ('african-throwing-knives-nb', 'African Throwing Knives', 'nightbane', 'weapon', NULL, 80, '$80-$150', '1D8', 0, NULL, NULL, NULL, NULL, NULL, 'Other Ancient Exotic Weapons, printed 208; illustrated there as throwing irons.', 'Nightbane RPG p.208'),
  ('bola-nb', 'Bola', 'nightbane', 'weapon', NULL, 40, NULL, '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'Two or three heavy balls attached to a long cord, used primarily in South America to ENTANGLE cattle.', 'Nightbane RPG p.209'),
  ('boomerang-nb', 'Boomerang', 'nightbane', 'weapon', NULL, 10, '$10-$20 each', '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'The infamous aborigine throwing stick.', 'Nightbane RPG p.209'),
  ('chakram-nb', 'Chakram', 'nightbane', 'weapon', NULL, 10, '$10 each', '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'A flat steel ring with a sharpened outer edge.', 'Nightbane RPG p.209'),
  ('katar-nb', 'Katar', 'nightbane', 'weapon', NULL, 200, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'A Hindu double blade weapon that might be thought of as a small sword, usually about one and a half feet long.', 'Nightbane RPG p.209'),
  ('tiger-claws-or-bagh-nakh-nb', 'Tiger Claws or Bagh Nakh', 'nightbane', 'weapon', NULL, 40, NULL, '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'A small set of steel claws that fit in one''s hand, favored by assassins in India and the Middle East. This row is the CLAWS ALONE.', 'Nightbane RPG p.209'),
  ('tiger-claws-with-blades-bich-hwa-bagh-nakh-nb', 'Tiger Claws with Blades (Bich''Hwa Bagh Nakh)', 'nightbane', 'weapon', NULL, 70, '$70 to $150', '1D6 knife, 1D4 claw', 0, NULL, NULL, NULL, NULL, NULL, 'Printed 209 notes tiger claws were often combined with knives (Bich''Hwa Bagh Nakh), and prices claws and blades separately from the claws alone.', 'Nightbane RPG p.209');

-- Read the result back. This batch asserts its OWN rows and nothing else.
SELECT 'all 114 rows of this script are in, as nightbane' AS assertion, count(*) AS got, 114 AS want
  FROM gear WHERE system = 'nightbane' AND source_book LIKE 'Nightbane RPG p.%'
   AND slug IN ('axe-battle-nb', 'axe-throwing-nb', 'axe-stone-nb', 'axe-bipennis-2-head-nb', 'oncin-pick-nb', 'awl-pike-nb', 'beaked-axe-nb', 'berdiche-nb', 'glaive-nb', 'guisarme-nb', 'halberd-nb', 'sabre-halberd-nb', 'hippe-nb', 'lucerne-hammer-nb', 'military-fork-nb', 'pike-nb', 'runka-nb', 'scythe-nb', 'voulge-nb', 'short-spear-nb', 'long-spear-nb', 'javelin-nb', 'beaked-axe-spear-nb', 'trident-nb', 'lance-nb', 'daggers-and-knives-nb', 'short-sword-nb', 'sabre-nb', 'scimitar-nb', 'falchion-nb', 'cutlass-nb', 'bastard-nb', 'broadsword-nb', 'claymore-nb', 'flamberge-nb', 'long-sword-nb', '2-handed-espandon-nb', 'ball-and-chain-nb', 'flail-nb', 'goupillon-flail-nb', 'mace-and-chain-nb', 'nunchaku-nb', 'arab-mace-nb', 'mace-nb', 'cudgel-nb', 'club-stick-pipe-nb', 'hercules-club-nb', 'horseman-hammer-nb', 'maul-nb', 'morning-star-nb', 'war-club-wood-nb', 'war-hammer-nb', 'short-staff-nb', 'long-staff-nb', 'bo-staff-nb', 'quarterstaff-nb', 'iron-staff-nb', 'short-bow-nb', 'arrows-short-bow-nb', 'long-bow-nb', 'arrows-long-bow-nb', 'cross-bow-nb', 'bolts-nb', 'sling-nb', 'black-jack-nb', 'dart-nb', 'bull-whip-nb', 'cat-o-nine-tails-nb', 'meat-cleaver-nb', 'frying-pan-nb', 'hand-pick-nb', 'large-pick-mattock-nb', 'shovel-nb', 'hammer-tool-nb', 'aikuchi-tanto-nb', 'bisento-nb', 'blow-gun-nb', 'ninja-bow-nb', 'samurai-long-bow-nb', 'modern-commercial-hunting-bow-nb', 'heavy-crossbow-nb', 'pistol-style-crossbow-nb', 'daisho-nb', 'jitte-or-sai-nb', 'katana-nb', 'kyoketsu-shogi-nb', 'kusari-gama-nb', 'kawanga-nb', 'manriki-gusari-nb', 'naginata-yari-nb', 'no-dachi-nb', 'sa-tjat-koen-nb', 'shikomi-zue-nb', 'shuriken-nb', 'throwing-knives-japanese-nb', 'wakizashi-nb', 'tonfa-nb', 'climbing-claws-tekagi-or-shuko-nb', 'climbing-spikes-nb', 'eggshell-bomb-nb', 'ippon-sugi-nobori-nb', 'ninja-emergency-kit-nb', 'ninja-clothing-nb', 'chain-per-foot-nb', 'rope-per-foot-nb', 'ninja-rope-ladder-per-foot-nb', 'tetsubishi-ninja-caltrops-nb', 'african-throwing-knives-nb', 'bola-nb', 'boomerang-nb', 'chakram-nb', 'katar-nb', 'tiger-claws-or-bagh-nakh-nb', 'tiger-claws-with-blades-bich-hwa-bagh-nakh-nb');

SELECT 'every one has a description' AS assertion, count(*) AS got, 114 AS want
  FROM gear WHERE system = 'nightbane' AND length(description) > 0
   AND slug IN ('axe-battle-nb', 'axe-throwing-nb', 'axe-stone-nb', 'axe-bipennis-2-head-nb', 'oncin-pick-nb', 'awl-pike-nb', 'beaked-axe-nb', 'berdiche-nb', 'glaive-nb', 'guisarme-nb', 'halberd-nb', 'sabre-halberd-nb', 'hippe-nb', 'lucerne-hammer-nb', 'military-fork-nb', 'pike-nb', 'runka-nb', 'scythe-nb', 'voulge-nb', 'short-spear-nb', 'long-spear-nb', 'javelin-nb', 'beaked-axe-spear-nb', 'trident-nb', 'lance-nb', 'daggers-and-knives-nb', 'short-sword-nb', 'sabre-nb', 'scimitar-nb', 'falchion-nb', 'cutlass-nb', 'bastard-nb', 'broadsword-nb', 'claymore-nb', 'flamberge-nb', 'long-sword-nb', '2-handed-espandon-nb', 'ball-and-chain-nb', 'flail-nb', 'goupillon-flail-nb', 'mace-and-chain-nb', 'nunchaku-nb', 'arab-mace-nb', 'mace-nb', 'cudgel-nb', 'club-stick-pipe-nb', 'hercules-club-nb', 'horseman-hammer-nb', 'maul-nb', 'morning-star-nb', 'war-club-wood-nb', 'war-hammer-nb', 'short-staff-nb', 'long-staff-nb', 'bo-staff-nb', 'quarterstaff-nb', 'iron-staff-nb', 'short-bow-nb', 'arrows-short-bow-nb', 'long-bow-nb', 'arrows-long-bow-nb', 'cross-bow-nb', 'bolts-nb', 'sling-nb', 'black-jack-nb', 'dart-nb', 'bull-whip-nb', 'cat-o-nine-tails-nb', 'meat-cleaver-nb', 'frying-pan-nb', 'hand-pick-nb', 'large-pick-mattock-nb', 'shovel-nb', 'hammer-tool-nb', 'aikuchi-tanto-nb', 'bisento-nb', 'blow-gun-nb', 'ninja-bow-nb', 'samurai-long-bow-nb', 'modern-commercial-hunting-bow-nb', 'heavy-crossbow-nb', 'pistol-style-crossbow-nb', 'daisho-nb', 'jitte-or-sai-nb', 'katana-nb', 'kyoketsu-shogi-nb', 'kusari-gama-nb', 'kawanga-nb', 'manriki-gusari-nb', 'naginata-yari-nb', 'no-dachi-nb', 'sa-tjat-koen-nb', 'shikomi-zue-nb', 'shuriken-nb', 'throwing-knives-japanese-nb', 'wakizashi-nb', 'tonfa-nb', 'climbing-claws-tekagi-or-shuko-nb', 'climbing-spikes-nb', 'eggshell-bomb-nb', 'ippon-sugi-nobori-nb', 'ninja-emergency-kit-nb', 'ninja-clothing-nb', 'chain-per-foot-nb', 'rope-per-foot-nb', 'ninja-rope-ladder-per-foot-nb', 'tetsubishi-ninja-caltrops-nb', 'african-throwing-knives-nb', 'bola-nb', 'boomerang-nb', 'chakram-nb', 'katar-nb', 'tiger-claws-or-bagh-nakh-nb', 'tiger-claws-with-blades-bich-hwa-bagh-nakh-nb');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('zzzzzzzzzzzzz-nb-gear-a-ancient-weapons.sql');
