-- Step 4 of the Nightbane extraction plan (apps/character-creator/docs/surveys/nightbane-core.md):
-- Machineguns, heavy, special and energy weapons, gases, explosives, miscellaneous modern weapons. Printed 218-222. 88 rows.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/zzzzzzzzzzzzz-nb-gear-c-heavy-and-special-weapons.sql
--
-- D4 (#1126): every item in the equipment chapter is its own `nightbane` row, on
-- Nate's word, read off the Nightbane pages rather than shared with Heroes Unlimited's
-- rows for the near-identical chapter. HU's scripts (add-hu-gear-*.sql) are the
-- PRECEDENT for shape - names, where a combined entry splits into priced rows, which
-- column a number goes in - and each row here was diffed against its HU counterpart
-- to catch misreads. Where the two books disagree, this file holds what Nightbane
-- prints; the PR lists every disagreement and its evidence.
--
-- Slugs are the name plus `-nb`, so no Nightbane row can collide with a row of
-- another game. `cost` is dollars, a range's low end; NULL where the page prints no
-- price, with any printed wording in cost_note. Citations are printed folios
-- (cache page = folio + 1).

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('light-machinegun-30-5-62mm-and-7-62mm-calibre-nb', 'Light Machinegun (.30, 5.62mm and 7.62mm Calibre)', 'nightbane', 'weapon', 15, 2000, '$2000.00 and up (mostly illegal)', '5D6 per round', 0, '3000ft', '.30, 5.62mm and 7.62mm in 100, 200 and 250 round belts', NULL, NULL, NULL, 'The most common kinds of light machinegun found in military forces the world over. Printed weight is a RANGE, 15 to 25lbs; the low end is stored. Rate of fire: can empty the weapon in two melee rounds. The page writes the middle calibre as 5.62mm and it is transcribed as printed.', 'Nightbane RPG p.218'),
  ('heavy-machinegun-50-and-14-5mm-nb', 'Heavy Machinegun (.50 and 14.5mm)', 'nightbane', 'weapon', 30, 6000, '$6000 and up (highly illegal)', '7D6 per round', 0, '3000ft', '.50 and 14.5mm belts of varying sizes', NULL, NULL, NULL, 'Commonly mounted on armored military vehicles and usually found only in military units. Accuracy is poor - they are meant for use against large vehicles or massed soldiers - but they punch right through armor or engine blocks. Printed weight is a RANGE, 30 to 100lbs; the low end is stored.', 'Nightbane RPG p.218'),
  ('rocket-launcher-nb', 'Rocket Launcher', 'nightbane', 'weapon', 12, 900, 'mostly illegal', '1D4x100', 0, '3600ft (1200m)', NULL, NULL, NULL, NULL, 'Called the "Super Bazooka", designed as an antitank weapon but sometimes used against bunkers. Length 61 inches (1549mm). Blast radius 50ft (15m). Printed weight is 12lbs (5.4kg) for the front and rear tubes plus 9lbs for the rocket; the tubes are stored.', 'Nightbane RPG p.218'),
  ('66mm-light-antitank-weapon-law-nb', '66mm Light Antitank Weapon (LAW)', 'nightbane', 'weapon', 5.2, 1000, 'mostly illegal', '1D6x100', 0, '1000ft (325m)', 'Single shot and discard', NULL, NULL, NULL, 'Light and disposable, a favorite for taking out "hardened" positions where the enemy has metal or concrete protection. Against tanks it is not as effective, killing only about 10% of the time. Size 35 inches (889mm) extended. Blast radius 50ft (15m). Weight 5.2lbs (2.6kg).', 'Nightbane RPG p.218'),
  ('90mm-recoilless-rifle-nb', '90mm Recoilless Rifle', 'nightbane', 'weapon', 35, 1600, 'highly illegal', '2D4x100', 0, '1200ft (400m)', 'Breech', NULL, NULL, NULL, 'Looks like a bazooka or rocket launcher and fires a single antitank round. Blast radius 80ft (24m). Rate of fire: (rapid) 10 rounds per minute to a maximum of 5 rounds, sustained 1 round per minute; at the rapid rate a 15 minute cooling period must be observed after every 5 rounds. Weight 35lbs (16kg), unloaded.', 'Nightbane RPG p.218'),
  ('40mm-grenade-launcher-mounted-on-rifle-nb', '40mm Grenade Launcher Mounted on Rifle', 'nightbane', 'weapon', 11, 1000, 'highly illegal', '1D4x100', 0, '1150ft (350m)', 'Single shot', NULL, NULL, NULL, 'Basically an M-79 installed under the barrel of an M-16 assault rifle. Weight 11lbs (5kg). Length 15.6 inches (361mm). Blast radius 20ft (6.1m). Rate of fire 3-5 rounds per minute.', 'Nightbane RPG p.218'),
  ('tranquilizer-rifle-nb', 'Tranquilizer Rifle', 'nightbane', 'weapon', NULL, 1000, NULL, 'Renders its victim unconscious within 1D4 melees; effects last 4D4 minutes. Saving throw vs toxin', 0, '800ft (240m)', 'Hand loaded, maximum capacity two', NULL, NULL, NULL, 'A rifle designed to fire a tranquilizer dart. Effective range is about half that of a normal rifle. Both darts can be fired per melee and require the following melee as reload time. Rate of fire 2 per melee. Requires W.P. Rifle. Darts are priced separately.', 'Nightbane RPG p.218'),
  ('dart-gun-nb', 'Dart Gun', 'nightbane', 'weapon', NULL, 500, NULL, 'Renders victim unconscious; effects last 4D4 minutes. Saving throw vs toxin', 0, '110ft (33.5m)', NULL, NULL, NULL, NULL, 'Rate of fire 2 per melee. Requires a W.P. with Pistol or Revolver. Darts are priced separately.', 'Nightbane RPG p.218'),
  ('tranquilizer-darts-nb', 'Tranquilizer Darts', 'nightbane', 'gear', NULL, 10, '$10.00 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 218 prices darts separately under both the Tranquilizer Rifle ("Cost (darts): $10.00") and the Dart Gun ("Costs (darts): $10.00 each"), at the same figure for each.', 'Nightbane RPG p.218'),
  ('gas-gun-pistol-nb', 'Gas Gun (pistol)', 'nightbane', 'weapon', NULL, 200, NULL, 'Varies with the type of gas used', 0, '160ft (48.8m)', 'One gas canister', NULL, NULL, NULL, 'A long, wide, tubular barreled handgun that fires a gas canister: tear gas, tranquilizer (knockout), nerve gas, or smoke gas/screen. Rate of fire 1 per melee. Requires a W.P. with Pistol. The canister types are priced separately and are their own rows.', 'Nightbane RPG p.219'),
  ('tear-gas-canister-gas-gun-nb', 'Tear Gas Canister (gas gun)', 'nightbane', 'gear', NULL, 50, '$50.00', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'For the Gas Gun on printed 219, which prices tear gas and tranquilizer gas canisters together at $50.00. NOT the same item as the Tear Gas on printed 221, which is $40.00 each.', 'Nightbane RPG p.219'),
  ('tranquilizer-gas-canister-gas-gun-nb', 'Tranquilizer Gas Canister (gas gun)', 'nightbane', 'gear', NULL, 50, '$50.00', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'For the Gas Gun on printed 219, priced with the tear gas canister at $50.00.', 'Nightbane RPG p.219'),
  ('nerve-gas-canister-gas-gun-nb', 'Nerve Gas Canister (gas gun)', 'nightbane', 'gear', NULL, 75, '$75.00', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'For the Gas Gun on printed 219 ("Cost of Nerve Gas: $75.00"). NOT the same item as the Nerve Gas (paralysis) on printed 221, which is $120.00 each.', 'Nightbane RPG p.219'),
  ('smoke-gas-canister-gas-gun-nb', 'Smoke Gas Canister (gas gun)', 'nightbane', 'gear', NULL, 25, '$25.00', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'For the Gas Gun on printed 219 ("Cost of Smoke: $25.00"); the gun''s list of gases calls it Smoke Gas/Screen.', 'Nightbane RPG p.219'),
  ('stun-gun-blaster-nb', 'Stun Gun (blaster)', 'nightbane', 'weapon', NULL, 4000, NULL, 'Special - victims are dazed, -10 to strike, parry and dodge, for 2D4 melees. A successful save vs toxins means the person fought the effect off and is unimpaired; roll to save against each blast that strikes', 0, '100ft (30.5m)', '10 charges', NULL, NULL, NULL, 'A pistol that fires an energy charge which short circuits the nervous system. Rate of fire 5 per melee. Requires a W.P. with Energy Pistol. Energy clips are priced separately.', 'Nightbane RPG p.219'),
  ('stun-gun-energy-clip-nb', 'Stun Gun Energy Clip', 'nightbane', 'gear', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 219 prices the stun gun''s energy clips separately from the gun ("Cost (energy clips): $1000.00").', 'Nightbane RPG p.219'),
  ('standard-laser-pistol-nb', 'Standard Laser Pistol', 'nightbane', 'weapon', 1.5, 300000, NULL, '4D6 or 5D6', 0, '600ft (183m)', '10 blasts', NULL, NULL, NULL, 'Attacks per melee: up to four blasts. Weight 1.5lbs (.7kg). Energy weapons are highly experimental, rare and terribly expensive: printed 219 notes each is carefully hand built, and that mass production would drop the cost to about 10% of it.', 'Nightbane RPG p.219'),
  ('standard-laser-pistol-energy-clip-nb', 'Standard Laser Pistol Energy Clip', 'nightbane', 'gear', NULL, 25000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 219: "An energy clip costs $25,000."', 'Nightbane RPG p.219'),
  ('standard-laser-pistol-with-energy-hip-pack-nb', 'Standard Laser Pistol with Energy Hip-Pack', 'nightbane', 'weapon', 16, 180000, NULL, '4D6 or 5D6', 0, '300ft (91.5m)', '20 blasts', NULL, NULL, NULL, 'Printed 219 gives this as a Note under the Standard Laser Pistol: a laser pistol with a 16lb (7.3kg) energy hip-pack, with a range of 300ft and a limited E-clip capacity of 20. It is a separate row because it carries its own price.', 'Nightbane RPG p.219'),
  ('standard-laser-rifle-nb', 'Standard Laser Rifle', 'nightbane', 'weapon', 7, 400000, NULL, '6D6', 0, '4000ft (1200m)', '20 blasts', NULL, NULL, NULL, 'Attacks per melee: four. Printed weight 7lbs (2.3kg).', 'Nightbane RPG p.219'),
  ('standard-laser-rifle-energy-clip-nb', 'Standard Laser Rifle Energy Clip', 'nightbane', 'gear', NULL, 25000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 219: "An energy clip costs $25,000."', 'Nightbane RPG p.219'),
  ('heavy-laser-with-back-pack-nb', 'Heavy Laser (with back-pack)', 'nightbane', 'weapon', 22, 1000000, '$1,000,000 for the whole unit', '6D6+10', 0, '2000ft (609.6m)', 'Energy back-pack capacity 100; requires 24 hours for the pack to regenerate', NULL, NULL, NULL, 'Attacks per melee: up to six blasts. Printed weight is 6lbs (2.7kg) for the gun and 16lbs (7.3kg) for the pack; 22 is the pair, because the price is for the whole unit.', 'Nightbane RPG p.219'),
  ('mini-laser-tool-nb', 'Mini-Laser (tool)', 'nightbane', 'weapon', 0.25, 300000, NULL, '1D6 or 2D6', 0, '300ft (90m)', '20 charges', NULL, NULL, NULL, 'A utility tool used by mechanics and communications engineers, slightly longer than a normal writing pen (about 8 inches) and twice as wide; carried in pockets, on utility belts, in mini-tool packs or a boot. Attacks per melee: two. Printed weight 4 ounces (113.4gms). Short burst: 1D6 for one energy charge or 2D6 for two. Continual beam: 1D6 for two charges or 2D6 for three charges per melee.', 'Nightbane RPG p.220'),
  ('mini-laser-energy-clip-nb', 'Mini-Laser Energy Clip', 'nightbane', 'gear', NULL, 10000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 220: "An energy clip costs $10,000."', 'Nightbane RPG p.220'),
  ('particle-beam-rifle-nb', 'Particle Beam Rifle', 'nightbane', 'weapon', 12, 800000, NULL, '1D6x10 or 2D8x10', 0, '4000ft (1200m)', '10 blasts', NULL, NULL, NULL, 'Comes equipped with an infrared, telescopic targeting scope. Attacks per melee: two. Weight 12lbs (5.4kg). PARTICLE BEAM WEAPONS HAVE THEIR OWN STRIKE RULE, printed 220: only a roll of 11 through 20 hits; 11-17 is only a nick, which grazes the target and does 10 to 60 points of damage; 18, 19 or 20 is a direct hit.', 'Nightbane RPG p.220'),
  ('particle-beam-rifle-energy-clip-nb', 'Particle Beam Rifle Energy Clip', 'nightbane', 'gear', NULL, 30000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 220: "An energy clip costs $30,000."', 'Nightbane RPG p.220'),
  ('simple-blaster-ion-nb', 'Simple Blaster (Ion)', 'nightbane', 'weapon', 2, 200000, NULL, '2D6+2', 0, '400ft (122m)', '14 blasts', NULL, NULL, NULL, 'Attacks per melee: up to seven blasts. Weight 2lbs (.9kg).', 'Nightbane RPG p.220'),
  ('simple-blaster-energy-clip-nb', 'Simple Blaster Energy Clip', 'nightbane', 'gear', NULL, 20000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 220: "An energy clip costs $20,000."', 'Nightbane RPG p.220'),
  ('heavy-ion-blaster-nb', 'Heavy Ion Blaster', 'nightbane', 'weapon', 2, 250000, NULL, '4D6', 0, '200ft (61m)', '10 blasts', NULL, NULL, NULL, 'Attacks per melee: up to four blasts. Weight 2lbs (.9kg).', 'Nightbane RPG p.220'),
  ('heavy-ion-blaster-energy-clip-nb', 'Heavy Ion Blaster Energy Clip', 'nightbane', 'gear', NULL, 20000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 220: "An energy clip costs $20,000."', 'Nightbane RPG p.220'),
  ('m-2a1-7-portable-flamethrower-nb', 'M-2A1-7 Portable Flamethrower', 'nightbane', 'weapon', 42.5, 400, 'mostly illegal', '5D10, plus ignition of all combustible material', 0, '70ft (20m) unthickened; 150ft (45m) thickened', 'Manual', NULL, NULL, NULL, 'With a solid stream of fire a soldier could clear out an entire enemy machinegun nest. In confined spaces (inside a bunker, foxhole or building) everyone in the target area is affected equally. Only 1 shot per combat round with incendiaries. Weight 42.5lbs (19kg).', 'Nightbane RPG p.220'),
  ('an-m14-th3-incendiary-hand-grenade-nb', 'AN-M14 TH3 Incendiary Hand Grenade', 'nightbane', 'weapon', 1.5, 30, NULL, 'Up to 12ft from impact 1D100+20 S.D.C. or 1 M.D.C.; 12-24ft away 1D100; 24-36ft away 3D10; 36-120ft away 1D10. Burns for 10 melee rounds', 0, NULL, NULL, NULL, NULL, NULL, 'One of the most dangerous weapons and not just for the enemy: it is difficult or impossible to throw it far enough to avoid getting hit with fragments. Time delay fuse 4-5 seconds. Effective casualty radius lethal up to 60ft (18m), dangerous to 120ft (36m). Printed weight 24 ounces (.9kg); the ounce figure is stored. Only 1 shot per combat round with incendiaries. The M.D.C. figure is an equivalence printed beside the S.D.C. number, not a mega-damage rule.', 'Nightbane RPG p.220'),
  ('molotov-cocktail-nb', 'Molotov Cocktail', 'nightbane', 'weapon', NULL, NULL, 'NO PRICE IS PRINTED. The entry gives a thrown range and damage and stops, which is the finished state for this row rather than a gap', 'Up to a 12ft area - 3D6. Burns for 4 melee rounds', 0, '30ft (9m) thrown', NULL, NULL, NULL, NULL, 'Printed 220. Only 1 shot per combat round with incendiaries.', 'Nightbane RPG p.220'),
  ('flare-gun-nb', 'Flare Gun', 'nightbane', 'weapon', 2, 200, '$200 for the gun only; wide availability', '2D6 per melee ignited (5 melees)', 0, '300ft (91.5m)', NULL, NULL, NULL, NULL, 'Attacks per melee: two. Weight 2lbs (.9kg). Has not changed much over the decades; generally used as a signal or to light up an area - used for luminescence it lights a 300ft (90m) area for about five melees (75 seconds). NOT intended to be a weapon and not balanced for aiming, so W.P. handgun skill bonuses do NOT apply. Flares are priced separately.', 'Nightbane RPG p.220'),
  ('flare-gun-flares-nb', 'Flare Gun Flares', 'nightbane', 'gear', NULL, 10, '$10 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 220 prices the flares separately from the gun ("flares cost $10 each"). Wide availability.', 'Nightbane RPG p.220'),
  ('hand-held-flares-nb', 'Hand-Held Flares', 'nightbane', 'gear', 0.375, 3, '$3 each; wide availability', 'One point', 0, 'Hand held', NULL, NULL, NULL, NULL, 'Attacks per melee equal to hand to hand attacks. Printed weight 6 ounces (170gms). Generally used to mark an area or for signaling, similar to those used by present day truck drivers.', 'Nightbane RPG p.220-221'),
  ('rocket-flare-nb', 'Rocket Flare', 'nightbane', 'weapon', 0.3125, 10, '$10 each; wide availability', '2D6', 0, '300ft (90m) straight up', 'One', NULL, NULL, NULL, 'A hand-held flare with a disposable, one time launch mechanism. Commonly used for expeditions in the wild. A -3 to strike penalty applies if used as a weapon. Attacks per melee: one. Printed weight 5 ounces (141gms).', 'Nightbane RPG p.221'),
  ('rocket-parachute-flare-nb', 'Rocket Parachute Flare', 'nightbane', 'gear', NULL, 10, '$10 per flare', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A signal flare fired from a single hand launch tube or flare gun that deploys a parachute-supported star. No visible rocket trail is left in its launch path to give away the firer''s position. Maximum height 1000ft (305m), 30 seconds of illumination, 200,000 candela. Available colors white, red, green and yellow. The launcher is priced separately.', 'Nightbane RPG p.221'),
  ('rocket-parachute-flare-launcher-nb', 'Rocket Parachute Flare Launcher', 'nightbane', 'gear', NULL, 300, '$300 for the launcher', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 221 prices the launcher separately from the flares ("$10 per flare, plus $300 for the launcher").', 'Nightbane RPG p.221'),
  ('distress-signal-kit-nb', 'Distress Signal Kit', 'nightbane', 'gear', NULL, 120, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A tube launcher and six red flares. Maximum height 900ft (275m), 30 seconds of illumination, 10,000 candela.', 'Nightbane RPG p.221');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('mini-signal-cartridges-nb', 'Mini Signal Cartridges', 'nightbane', 'gear', NULL, 250, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A lightweight signal cartridge designed for military special forces, fired from a single-handed, lightweight, pen-type launcher. Maximum height 320ft (98m), 10 seconds of illumination, 150,000 candela. Colors green, red or white.', 'Nightbane RPG p.221'),
  ('tear-gas-nb', 'Tear Gas', 'nightbane', 'gear', NULL, 40, '$40.00 each', 'None; victims are -6 to strike, parry and dodge and lose any chance for initiative', 0, NULL, NULL, NULL, NULL, NULL, 'An extremely potent irritant that temporarily impairs vision and respiration: eyes burn and water profusely, skin burns (a sensation, not in actuality) and breathing is very difficult. Effects are immediate. NO saving throw, but gas masks counter it effectively. NOT the same item as the Tear Gas Canister for the gas gun on printed 219, which is $50.00.', 'Nightbane RPG p.221'),
  ('knockout-gas-nb', 'Knockout Gas', 'nightbane', 'gear', NULL, 60, '$60.00 each', 'None; induces drowsiness within 1D4 melees and sleep within 1D4 minutes', 0, NULL, NULL, NULL, NULL, NULL, 'Tranquilizers; anesthesia-type mists. A successful saving throw vs toxins means the body fought off the effects and is unimpaired, but the player rolls once for every minute (four melees) of exposure. Gas masks counter it effectively.', 'Nightbane RPG p.221'),
  ('nerve-gas-paralysis-nb', 'Nerve Gas (paralysis)', 'nightbane', 'gear', NULL, 120, '$120.00 each', 'None; causes paralysis, taking effect within 2D4 melees', 0, NULL, NULL, NULL, NULL, NULL, 'Attacks the nervous system, causing paralysis; takes effect within 2D4 melees (two minutes). A successful saving throw vs toxins fights off the effects (and the character should get out quick); roll for each minute (four melees) exposed. GAS MASKS ARE USELESS against most nerve agents; Atropine Injectors negate the effects. NOT the same item as the Nerve Gas Canister for the gas gun on printed 219, which is $75.00.', 'Nightbane RPG p.221'),
  ('atropine-injector-nb', 'Atropine Injector', 'nightbane', 'gear', NULL, 400, '$400.00 per dosage', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An anti-nerve gas agent that negates nerve gas. One injector is needed for every ten minutes of exposure and must be administered immediately.', 'Nightbane RPG p.221'),
  ('explosive-grenade-nb', 'Explosive Grenade', 'nightbane', 'weapon', 0.625, 60, '$60 each on the black-market chart on printed 221, which lists it as Hand Grenades, 30% availability', '2D4x10', 0, '100ft (30m)', NULL, NULL, NULL, NULL, 'Effective casualty radius 20ft. Printed weight 10 ounces (283 grams). Illegal. Its own entry says only "Cost: See Explosives Chart below", so the price comes from that chart. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('smoke-grenade-nb', 'Smoke Grenade', 'nightbane', 'weapon', 0.625, 30, '$30 each on the black-market chart on printed 221, 40% availability', 'None; creates a smoke filled area for cover or as a signal', 0, '100ft', NULL, NULL, NULL, NULL, 'Opponents cannot see into or through the smoke, and those whose vision is obscured are -6 to strike. Effective casualty radius 20ft. Colors: black, grey, red, yellow. Printed weight 10 ounces (283 grams). Its own entry says "Cost: See Below"; the price is the black-market chart''s Smoke Grenades row. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('rifle-launcher-grenades-nb', 'Rifle Launcher Grenades', 'nightbane', 'weapon', NULL, 80, '$80 each on the black-market chart on printed 221, which lists it as Rifle Launched Grenades, 20% availability', '2D4x10 to a 20ft area', 0, '1150ft (350m)', 'Single shot', NULL, NULL, NULL, 'Explosive or smoke grenades fired from an assault rifle; the stated damage and effects of those grenades apply. The entry prints no cost line of its own; the price is the black-market chart''s Rifle Launched Grenades row. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('dynamite-nb', 'Dynamite', 'nightbane', 'gear', NULL, 30, '$30 per stick; 45% black-market availability', 'One stick: 1D4x10. Effective casualty radius 10ft (3m)', 0, NULL, NULL, NULL, NULL, NULL, 'A nitroglycerin based explosive widely used in mining and road construction, detonated with blasting caps, fuses and timing devices. Wick fuses are rarely used today. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('detonation-caps-fuses-nb', 'Detonation Caps/Fuses', 'nightbane', 'gear', NULL, 30, '$30 each; 32% black-market availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Black-market price chart, printed 221. Dynamite is detonated with blasting caps, fuses and timing devices, and plastic and gelatin explosives can only be activated by an electrical blasting cap (printed 221-222). Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('plastic-explosive-nb', 'Plastic Explosive', 'nightbane', 'gear', NULL, 100, '$100 per each 2oz; 19% black-market availability', '2 ounces is equal to one stick of dynamite: 1D4x10. The blast is where the plastic was placed, about one foot', 0, NULL, NULL, NULL, NULL, NULL, 'A very localized blast explosive that can be molded and formed like putty. INERT - slamming it into a wall does nothing; it is activated only by an electrical blasting cap passing a charge through it, but any electrical charge, blast or bolt is 55% likely to detonate it. Depending on what is exploded it could cause much more additional destruction. Used to open safes and for sabotage; NOT an effective area effect weapon. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221-222'),
  ('gelatin-explosive-nb', 'Gelatin Explosive', 'nightbane', 'gear', NULL, 140, '$140 per ounce; 18% black-market availability', 'As plastic explosive: 2 ounces equal one stick of dynamite, 1D4x10, in about a one foot area', 0, NULL, NULL, NULL, NULL, NULL, 'Printed 221-222 describes plastic and gelatin explosives together and gives them the same behaviour: molded like putty, inert until an electrical blasting cap fires it, 55% chance any electrical charge, blast or bolt detonates it, used to open safes and for sabotage. Only the price differs. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221-222'),
  ('liquid-nitroglycerin-nb', 'Liquid Nitroglycerin', 'nightbane', 'gear', NULL, 200, '$200 per ounce; 20% black-market availability', 'One ounce is equal to four sticks of dynamite: 4D4x10. Effective casualty radius 20ft (6.1m)', 0, NULL, NULL, NULL, NULL, NULL, 'An extremely dangerous, unstable chemical explosive concentrate. A severe jar, jerk or bump can cause it to detonate: 30% chance. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('mortar-shells-nb', 'Mortar Shells', 'nightbane', 'gear', NULL, 100, '$100 each; 10% black-market availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Priced on the black-market chart on printed 221. No damage figure is printed for them. Black-market prices may be increased by 100% by circumstance or the individual seller, and there is always a 20% chance the item is fake or a dud.', 'Nightbane RPG p.221'),
  ('homemade-bombs-nb', 'Homemade Bombs', 'nightbane', 'gear', NULL, NULL, 'NO PRICE IS PRINTED. The entry is a single sentence with no stats, which is the finished state for this row rather than a gap', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 222, in the explosives section: homemade bombs usually incorporate chemicals or dynamite. Nothing else is printed.', 'Nightbane RPG p.222'),
  ('black-jack-modern-nb', 'Black Jack (modern)', 'nightbane', 'weapon', 2, 20, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'A small hand held club, usually handmade, 10 inches long, weighing 2 to 4 pounds; the low end of the printed range is stored. THE BOOK PRINTS A SECOND, DIFFERENT BLACK JACK on printed 205 among the ancient miscellaneous weapons. Two entries, one name; the qualifier is added here and the book prints the bare name.', 'Nightbane RPG p.222'),
  ('brass-knuckles-nb', 'Brass Knuckles', 'nightbane', 'weapon', NULL, 20, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'Printed 222.', 'Nightbane RPG p.222'),
  ('cattle-prod-nb', 'Cattle Prod', 'nightbane', 'weapon', NULL, 20, NULL, '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'An electric rod operated on "C" cell batteries that emits a 4500 volt shock when touched to the skin. 12 or 22 inch lengths.', 'Nightbane RPG p.222'),
  ('itching-powder-nb', 'Itching Powder', 'nightbane', 'gear', NULL, NULL, 'NO FIRM PRICE IS PRINTED - the book says only a couple of bucks per ounce from a novelty shop, which is not a figure this column can hold', 'None; victims are very uncomfortable, distracted and -3 on initiative for 1D4 hours or until washed off', 0, 'Varies with the application', NULL, NULL, NULL, NULL, 'Can be used as a powder, launched in a grenade, housed in a pellet that ruptures on impact, and similar devices. Affects only bare skin.', 'Nightbane RPG p.222'),
  ('hair-spray-nb', 'Hair Spray', 'nightbane', 'gear', NULL, 3, NULL, 'None; victims are -6 to strike, parry and dodge for 1D4 melees', 0, '3ft (.9m)', NULL, NULL, NULL, NULL, 'Can be used to temporarily blind an opponent.', 'Nightbane RPG p.222'),
  ('mace-chemical-spray-nb', 'Mace (chemical spray)', 'nightbane', 'weapon', NULL, 16, '$16.00, with about 20 sprays before empty', 'None; victims are -6 to strike, parry and dodge for 4D4 melees', 0, '4 to 6ft (1.2 to 1.8m)', NULL, NULL, NULL, NULL, 'A stinging chemical spray that blinds an opponent, much better than hair spray. THE BOOK PRINTS A SECOND, DIFFERENT MACE on printed 205 among the blunt weapons. The qualifier is added here; the book prints the bare name.', 'Nightbane RPG p.222'),
  ('modern-crossbow-nb', 'Modern Crossbow', 'nightbane', 'weapon', NULL, 180, NULL, '2D6', 0, '500ft (150m)', '150lb draw weight', NULL, NULL, NULL, 'With a rifle stock.', 'Nightbane RPG p.222'),
  ('slap-glove-nb', 'Slap Glove', 'nightbane', 'weapon', NULL, 30, NULL, '+2 to damage', 0, NULL, NULL, NULL, NULL, NULL, 'Six ounces of powdered lead built into each glove just above the knuckles, padding the wearer and adding weight and strength to the force of one blow. Available from most security guard suppliers.', 'Nightbane RPG p.222'),
  ('fiberglass-nightstick-nb', 'Fiberglass Nightstick', 'nightbane', 'weapon', NULL, 10, NULL, '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'Printed 222.', 'Nightbane RPG p.222'),
  ('steel-rod-encased-nightstick-nb', 'Steel Rod Encased Nightstick', 'nightbane', 'weapon', NULL, 20, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'Printed 222.', 'Nightbane RPG p.222'),
  ('s-w-a-t-entry-tool-hooligan-tool-nb', 'S.W.A.T. Entry Tool (Hooligan Tool)', 'nightbane', 'weapon', NULL, 240, NULL, '1D8 (either end)', 0, NULL, NULL, NULL, NULL, NULL, 'A long, one inch thick, stress proof bar, heat treated for durability and strength. One end is a large chisel, spike-like pry bar; the other a claw/chisel point (crowbar-like). Used to pry open security doors and grilles. Pops normal door locks on a roll to strike of 8-20, and heavy locks and security door locks on 12-20.', 'Nightbane RPG p.222'),
  ('combat-bush-knife-nb', 'Combat Bush Knife', 'nightbane', 'weapon', NULL, 200, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'A heavy-duty, all-purpose survival knife with the best carbon steel 7in blade.', 'Nightbane RPG p.222'),
  ('slimpack-throwing-knife-nb', 'Slimpack Throwing Knife', 'nightbane', 'weapon', NULL, 50, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'A perfectly balanced 6in blade with a flat lambskin sheath, perfect for concealment.', 'Nightbane RPG p.222'),
  ('belt-throwing-knife-set-nb', 'Belt Throwing Knife Set', 'nightbane', 'weapon', NULL, 135, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'Four ultrathin throwing knives in a single belt sheath designed for an easy, fast draw.', 'Nightbane RPG p.222'),
  ('polycarbonate-knife-nb', 'Polycarbonate Knife', 'nightbane', 'weapon', NULL, 300, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'A 7in knife with a silk sheath, guaranteed not to show up on metal detectors. Balanced for throwing, yet with a keen edge for slicing.', 'Nightbane RPG p.222'),
  ('small-boot-knife-nb', 'Small Boot Knife', 'nightbane', 'weapon', NULL, 20, NULL, '1D4', 0, NULL, NULL, NULL, NULL, NULL, 'For easy concealment.', 'Nightbane RPG p.222'),
  ('bayonet-nb', 'Bayonet', 'nightbane', 'weapon', NULL, 140, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'Attaches to combat rifles.', 'Nightbane RPG p.222'),
  ('slr-60-spike-launch-rod-nb', 'SLR-60/Spike Launch Rod', 'nightbane', 'gear', 2, 1200, NULL, '2D6', 0, '200ft (60m)', '30 charges', NULL, NULL, NULL, 'A small 2ft (.6m) rod-like device used for climbing: it fires a small (6 inch) metal spike up to 60 meters, carrying a high test line with it for scaling surfaces. Comes with 130 meters of heavy-duty cord, a detachable spool and a feeder with digital counter. Attacks per melee: one. Weight 2lbs (.9kg). Additional spikes and spools are priced separately.', 'Nightbane RPG p.222'),
  ('slr-60-spikes-nb', 'SLR-60 Spikes', 'nightbane', 'gear', NULL, 30, '$30 a dozen', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Additional spikes for the SLR-60.', 'Nightbane RPG p.222'),
  ('slr-60-line-spool-nb', 'SLR-60 Line Spool', 'nightbane', 'gear', NULL, 200, '$200 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An additional clip-in, prewound spool of 400ft (130m) line for the SLR-60.', 'Nightbane RPG p.222'),
  ('grappling-hook-line-nb', 'Grappling Hook & Line', 'nightbane', 'gear', 2, 150, '$150 for hook and 300ft of line', '1D4', 0, '100ft (30.5m)', NULL, NULL, NULL, NULL, 'A typical grappling hook and line for scaling surfaces. Attacks per melee equal to hand to hand attacks. Weight 2lbs (.9kg).', 'Nightbane RPG p.222'),
  ('ankle-holster-nb', 'Ankle Holster', 'nightbane', 'gear', NULL, 34, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Padded for comfort with a velcro closure. Fits a snub-nosed revolver or any small frame automatic, and can be concealed under a pant leg.', 'Nightbane RPG p.222'),
  ('inside-trouser-holster-nb', 'Inside Trouser Holster', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Clips on the belt or waistband of pants.', 'Nightbane RPG p.222'),
  ('side-holster-nb', 'Side Holster', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Fits onto a belt.', 'Nightbane RPG p.222'),
  ('belt-slide-holster-nb', 'Belt Slide Holster', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 222.', 'Nightbane RPG p.222');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('belt-thumbreak-holster-nb', 'Belt Thumbreak Holster', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 222.', 'Nightbane RPG p.222'),
  ('patrolman-police-style-belt-and-holster-nb', 'Patrolman, Police-Style Belt and Holster', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'With 24 bullet loops.', 'Nightbane RPG p.222'),
  ('police-style-shoulder-holster-nb', 'Police-style Shoulder Holster', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 222.', 'Nightbane RPG p.222'),
  ('military-style-shoulder-holster-nb', 'Military-style Shoulder Holster', 'nightbane', 'gear', NULL, 70, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 222.', 'Nightbane RPG p.222'),
  ('horizontal-shoulder-holster-nb', 'Horizontal Shoulder Holster', 'nightbane', 'gear', NULL, 85, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 222.', 'Nightbane RPG p.222'),
  ('scoped-shoulder-holster-nb', 'Scoped Shoulder Holster', 'nightbane', 'gear', NULL, 90, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Firearm accessories price list, printed 222.', 'Nightbane RPG p.222'),
  ('concealed-wallet-holster-nb', 'Concealed Wallet Holster', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'For small automatic weapons; fits easily into a back trouser pocket.', 'Nightbane RPG p.222'),
  ('web-belt-with-holster-nb', 'Web Belt with Holster', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'With a holster, two ammo pouches and four accessory attachment clips.', 'Nightbane RPG p.222');

-- Read the result back. This batch asserts its OWN rows and nothing else.
SELECT 'all 88 rows of this script are in, as nightbane' AS assertion, count(*) AS got, 88 AS want
  FROM gear WHERE system = 'nightbane' AND source_book LIKE 'Nightbane RPG p.%'
   AND slug IN ('light-machinegun-30-5-62mm-and-7-62mm-calibre-nb', 'heavy-machinegun-50-and-14-5mm-nb', 'rocket-launcher-nb', '66mm-light-antitank-weapon-law-nb', '90mm-recoilless-rifle-nb', '40mm-grenade-launcher-mounted-on-rifle-nb', 'tranquilizer-rifle-nb', 'dart-gun-nb', 'tranquilizer-darts-nb', 'gas-gun-pistol-nb', 'tear-gas-canister-gas-gun-nb', 'tranquilizer-gas-canister-gas-gun-nb', 'nerve-gas-canister-gas-gun-nb', 'smoke-gas-canister-gas-gun-nb', 'stun-gun-blaster-nb', 'stun-gun-energy-clip-nb', 'standard-laser-pistol-nb', 'standard-laser-pistol-energy-clip-nb', 'standard-laser-pistol-with-energy-hip-pack-nb', 'standard-laser-rifle-nb', 'standard-laser-rifle-energy-clip-nb', 'heavy-laser-with-back-pack-nb', 'mini-laser-tool-nb', 'mini-laser-energy-clip-nb', 'particle-beam-rifle-nb', 'particle-beam-rifle-energy-clip-nb', 'simple-blaster-ion-nb', 'simple-blaster-energy-clip-nb', 'heavy-ion-blaster-nb', 'heavy-ion-blaster-energy-clip-nb', 'm-2a1-7-portable-flamethrower-nb', 'an-m14-th3-incendiary-hand-grenade-nb', 'molotov-cocktail-nb', 'flare-gun-nb', 'flare-gun-flares-nb', 'hand-held-flares-nb', 'rocket-flare-nb', 'rocket-parachute-flare-nb', 'rocket-parachute-flare-launcher-nb', 'distress-signal-kit-nb', 'mini-signal-cartridges-nb', 'tear-gas-nb', 'knockout-gas-nb', 'nerve-gas-paralysis-nb', 'atropine-injector-nb', 'explosive-grenade-nb', 'smoke-grenade-nb', 'rifle-launcher-grenades-nb', 'dynamite-nb', 'detonation-caps-fuses-nb', 'plastic-explosive-nb', 'gelatin-explosive-nb', 'liquid-nitroglycerin-nb', 'mortar-shells-nb', 'homemade-bombs-nb', 'black-jack-modern-nb', 'brass-knuckles-nb', 'cattle-prod-nb', 'itching-powder-nb', 'hair-spray-nb', 'mace-chemical-spray-nb', 'modern-crossbow-nb', 'slap-glove-nb', 'fiberglass-nightstick-nb', 'steel-rod-encased-nightstick-nb', 's-w-a-t-entry-tool-hooligan-tool-nb', 'combat-bush-knife-nb', 'slimpack-throwing-knife-nb', 'belt-throwing-knife-set-nb', 'polycarbonate-knife-nb', 'small-boot-knife-nb', 'bayonet-nb', 'slr-60-spike-launch-rod-nb', 'slr-60-spikes-nb', 'slr-60-line-spool-nb', 'grappling-hook-line-nb', 'ankle-holster-nb', 'inside-trouser-holster-nb', 'side-holster-nb', 'belt-slide-holster-nb', 'belt-thumbreak-holster-nb', 'patrolman-police-style-belt-and-holster-nb', 'police-style-shoulder-holster-nb', 'military-style-shoulder-holster-nb', 'horizontal-shoulder-holster-nb', 'scoped-shoulder-holster-nb', 'concealed-wallet-holster-nb', 'web-belt-with-holster-nb');

SELECT 'every one has a description' AS assertion, count(*) AS got, 88 AS want
  FROM gear WHERE system = 'nightbane' AND length(description) > 0
   AND slug IN ('light-machinegun-30-5-62mm-and-7-62mm-calibre-nb', 'heavy-machinegun-50-and-14-5mm-nb', 'rocket-launcher-nb', '66mm-light-antitank-weapon-law-nb', '90mm-recoilless-rifle-nb', '40mm-grenade-launcher-mounted-on-rifle-nb', 'tranquilizer-rifle-nb', 'dart-gun-nb', 'tranquilizer-darts-nb', 'gas-gun-pistol-nb', 'tear-gas-canister-gas-gun-nb', 'tranquilizer-gas-canister-gas-gun-nb', 'nerve-gas-canister-gas-gun-nb', 'smoke-gas-canister-gas-gun-nb', 'stun-gun-blaster-nb', 'stun-gun-energy-clip-nb', 'standard-laser-pistol-nb', 'standard-laser-pistol-energy-clip-nb', 'standard-laser-pistol-with-energy-hip-pack-nb', 'standard-laser-rifle-nb', 'standard-laser-rifle-energy-clip-nb', 'heavy-laser-with-back-pack-nb', 'mini-laser-tool-nb', 'mini-laser-energy-clip-nb', 'particle-beam-rifle-nb', 'particle-beam-rifle-energy-clip-nb', 'simple-blaster-ion-nb', 'simple-blaster-energy-clip-nb', 'heavy-ion-blaster-nb', 'heavy-ion-blaster-energy-clip-nb', 'm-2a1-7-portable-flamethrower-nb', 'an-m14-th3-incendiary-hand-grenade-nb', 'molotov-cocktail-nb', 'flare-gun-nb', 'flare-gun-flares-nb', 'hand-held-flares-nb', 'rocket-flare-nb', 'rocket-parachute-flare-nb', 'rocket-parachute-flare-launcher-nb', 'distress-signal-kit-nb', 'mini-signal-cartridges-nb', 'tear-gas-nb', 'knockout-gas-nb', 'nerve-gas-paralysis-nb', 'atropine-injector-nb', 'explosive-grenade-nb', 'smoke-grenade-nb', 'rifle-launcher-grenades-nb', 'dynamite-nb', 'detonation-caps-fuses-nb', 'plastic-explosive-nb', 'gelatin-explosive-nb', 'liquid-nitroglycerin-nb', 'mortar-shells-nb', 'homemade-bombs-nb', 'black-jack-modern-nb', 'brass-knuckles-nb', 'cattle-prod-nb', 'itching-powder-nb', 'hair-spray-nb', 'mace-chemical-spray-nb', 'modern-crossbow-nb', 'slap-glove-nb', 'fiberglass-nightstick-nb', 'steel-rod-encased-nightstick-nb', 's-w-a-t-entry-tool-hooligan-tool-nb', 'combat-bush-knife-nb', 'slimpack-throwing-knife-nb', 'belt-throwing-knife-set-nb', 'polycarbonate-knife-nb', 'small-boot-knife-nb', 'bayonet-nb', 'slr-60-spike-launch-rod-nb', 'slr-60-spikes-nb', 'slr-60-line-spool-nb', 'grappling-hook-line-nb', 'ankle-holster-nb', 'inside-trouser-holster-nb', 'side-holster-nb', 'belt-slide-holster-nb', 'belt-thumbreak-holster-nb', 'patrolman-police-style-belt-and-holster-nb', 'police-style-shoulder-holster-nb', 'military-style-shoulder-holster-nb', 'horizontal-shoulder-holster-nb', 'scoped-shoulder-holster-nb', 'concealed-wallet-holster-nb', 'web-belt-with-holster-nb');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('zzzzzzzzzzzzz-nb-gear-c-heavy-and-special-weapons.sql');
