-- Triax vessels from printed pages 071-105.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/zzzzzz-triax-vessels-p071-105.sql
--
-- BOOK-INGEST-AUDIT.md F3. The vessels were excluded from every batch of
-- this book because `gear` holds one mdc, one damage, one range and one
-- payload, and a vessel here has M.D.C. by LOCATION and several numbered
-- weapon systems with four stats each. Migration 048 gave them three tables
-- of their own - vehicles, vehicle_locations, vehicle_weapons - and this is
-- the data that was waiting on them.
--
-- A VESSEL BELONGS TO THE SLICE ITS NAME HEADING FALLS IN. That rule is why
-- no vessel is split across two of these files and none is imported twice:
-- a reader whose stat block runs past a page boundary read on to finish it,
-- and a reader who met a block already in progress skipped it.
--
-- INSERT OR IGNORE THROUGHOUT, and the readbacks COUNT rather than trusting
-- the exit code - an IGNORE that collides is silent, which is exactly how a
-- row goes missing without an error.
--
-- mdc_main_body is the main body ONLY. The full printed block is in
-- vehicle_locations, main body included, so it can be rendered in the order
-- the book sets it; a reader wanting a total must sum the rows.
--
-- A LOCATION WHOSE M.D.C. THE BOOK PRINTS AS A FORMULA carries mdc NULL and
-- the formula in mdc_note. The EIR-50 Gurgoyle Android is the whole reason:
-- its block is printed as dice, not numbers, because the machine is built to
-- match whatever gurgoyle it is imitating.

INSERT OR IGNORE INTO vehicles
  (slug, name, system, vehicle_class, crew, passengers, speed_ground,
   speed_air, speed_water, dimensions, weight_tons, mdc_main_body, cost,
   cost_note, description, source_book)
VALUES
('x-2500-black-knight', 'X-2500 Black Knight', 'rifts', 'robot', 'Two: One pilot and a co-pilot/gunner.', 'Four human-size passengers can also be accommodated.', 'Running: 70 mph (112.6 km) maximum. Cruising speed usually around 40 mph (64 km). Well suited for most terrains including underwater; reasonably good climbing mountains, cannot climb sheer walls.', 'Flying: Not possible. Leaping: 20 feet (6 m) high/lengthwise from stationary; 30 feet (9 m) high or 40 feet (13.7 m) lengthwise from a running start.', NULL, 'Height: 35 feet (10.7 m) from bottom of feet to top of sensor head; antenna adds another four feet (1.2 m). Width: 23 feet (6.9 m) shoulder to shoulder. Length: 9 feet (2.7 m)', '30 tons', 750, 45000000, '45 million credits for an undamaged unit with all weapon systems intact (Black Market Cost)', 'One of the NGR''s largest robot vehicles at 35 feet tall, a ground infantry assault robot armed with an ion cannon, electro-mace, forearm lasers and vibro-swords, leg missile launchers and grenade tubes, used to take on the largest monsters and enemy robots.', 'Rifts World Book 5: Triax and the NGR p.73-74'),
('x-2700-dragonwing', 'X-2700 Dragonwing', 'rifts', 'robot', 'One pilot and typically a co-pilot/gunner.', 'Two human-size passengers can also be accommodated.', 'Running: 40 mph (64 km) maximum. Cruising speed usually around 25 mph (40 km). Suited for most terrains including outer space and underwater.', 'Full hover and evasive flight; cruise 1 to 300 mph (1.6-482.7 km) up to Mach 2 (approx 1340 mph/2144 km). Altitude as high as 45,000 feet (13,716 m) and as low as five feet (1.5 m). Leaping: 10 feet (3 m) high/lengthwise from stationary; Jet Assisted Leaps: 100 feet (30.5 m) high or lengthwise without flying.', 'Underwater: Maximum speed of 50 mph (80 km). Maximum depth of 600 feet (183 m).', 'Height: 30 feet (9.1 m) from bottom of feet to top of back; antenna adds another 10 feet (3 m). Width: 16 feet (4.9 m) shoulder to shoulder. Length: 27 feet (8.2 m)', '28 tons', 525, 45000000, '45 million credits for an undamaged unit with all weapon systems intact (Black Market Cost)', 'The only giant NGR infantry robot capable of true flight, reaching Mach 2 and using radar-reflective paint to remain largely invisible to radar; used for aerial combat against gargoyles and flying monsters, escort, extraction and deep reconnaissance.', 'Rifts World Book 5: Triax and the NGR p.75-78'),
('x-5000-devastator', 'X-5000 Devastator', 'rifts', 'robot', 'Two: One pilot and a co-pilot/gunner. A communications officer and/or intelligence officer is optional.', 'The giant bot can accommodate as many as six additional human-size passengers comfortably and contains four man-size suits of body armor as part of its armaments; typically the T-31 Super Trooper or X-10A Predator, or basic X-535 Jager.', 'Running: 40 mph (64 km) maximum. Cruising speed usually around 20 mph (32 km). Suitable for most terrains including outer space and underwater.', 'Leaping: Not possible. Flying: Not possible.', NULL, 'Height: 50 feet (15.2 m) from bottom of feet to top of sensor head; ion cannon adds another 20 feet (6 m) when stowed upward. Width: 30 feet (9 m) shoulder to shoulder. Length: 25 feet (7.6 m)', '150 tons', 1500, 150000000, '150 million credits! (Black Market Cost)', 'The largest infantry robot Triax has ever created, standing 50 feet tall as a walking artillery platform with two long-range cannons and over a hundred missiles, serving as the cornerstone of mobile assault forces despite slow speed and vulnerability to fast, close-in opponents.', 'Rifts World Book 5: Triax and the NGR p.79-81'),
('dv-12-dyna-bot', 'DV-12 Dyna-Bot', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Running: 120 mph (192 km) maximum. Running does NOT tire the robot; speed maintained indefinitely.', 'None, without the addition of a T-100 Eagle jet pack. Leaping: limited to approximately 12 feet (3.7 m) high or lengthwise; running leap at 60+ mph (96 km) adds 2D6+6 yards/meters.', NULL, 'Height: 7 feet, 4 inches (2.2 m). Width: 3 feet (0.9 m). Length: 3 feet (0.9 m)', '500 lbs (225 kg)', 130, 3000000, 'Black market sells the bots for three million credits new and undamaged, complete with combat program, assault rifle and bot weapon systems; Very poor availability. Combat version without weapons/programming costs two and a half million credits. A bootleg DV-12 combat program costs 500,000 credits.', 'An expendable, artificial-intelligence-driven man-sized assault robot used by the NGR as laborers, guards, infantry troops and hunter/killers, especially against gargoyles and other Monster Zone enemies; convertible between labor and combat programming in under a minute.', 'Rifts World Book 5: Triax and the NGR p.82-84'),
('dv-15-sentry-bot', 'DV-15 Sentry-Bot', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Running: 100 mph (160 km) maximum. Running does NOT tire the robot; speed maintained indefinitely.', 'None, without the addition of a T-100 Eagle jet pack. Leaping: limited to approximately 12 feet (3.7 m) high or lengthwise; running leap at 60+ mph (96 km) adds 2D6+6 yards/meters.', NULL, 'Height: 8 feet (2.4 m). Width: 3 feet (0.9 m). Length: 3 feet (0.9 m)', '650 lbs (292.5 kg)', 160, 3000000, 'Black market sells the bots for three million credits, new and undamaged; Sentry-bots have not been sold overseas in the Americas.', 'A heavier-armored modification of the DV-12 Dyna-bot with a multi-sensor crown, used by the NGR military mainly as tireless, incorruptible guards and defenders for prisoners, bases, and strategic locations.', 'Rifts World Book 5: Triax and the NGR p.84-86'),
('dv-40-hunter-killer-drone', 'DV-40 Hunter/Killer Drone', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Running: 70 mph (112 km) maximum. Running does NOT tire the robot; speed maintained indefinitely.', 'None, without the addition of a T-100 Eagle jet pack. Leaping: approximately 25 feet (7.6 m) high or lengthwise; running leap at 50+ mph (80 km) adds 2D6+6 yards/meters.', NULL, 'Height: 13 feet (3.9 m). Width: 7 feet (2.1 m). Length: 4 feet, 5 inches (1.35 m)', 'One ton', 300, 10000000, 'Black market sells the DV-40 for 10 million credits, new and undamaged. Poor availability.', 'A larger, giant-sized hunter/killer robot drone used to defoliate forests, destroy enemy strongholds, and conduct special-forces-style tactical assaults, typically sent in groups of three, sometimes accompanied by DV-12 Dyna-bots.', 'Rifts World Book 5: Triax and the NGR p.87-90'),
('eir-10-gargoyle-drone', 'EIR-10 Gargoyle Drone', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Running: 40 mph (64 km) maximum, faster than most real gargoyles (15-35 mph/24-56 km). Running does NOT tire the robot; speed maintained indefinitely.', 'Flying/Gliding: Limited. Maximum speed 40 mph (64 km); maximum height 500 feet (153 m); flight maintained up to 15 minutes before losing altitude. Leaping: normal leap 20 feet (6 m) high/lengthwise; running leap adds 1D6+6 yards/meters; jet thruster assisted leaps up to 80 feet (24.4 m) high/lengthwise.', NULL, 'Height: 15 feet (4.6 m). Width: Body 6 feet (1.8 m), wing span 25 feet (7.6 m). Length: Body 4 feet (1.2 m); tail an additional 10-15 feet (3-4.6 m) long.', '2000 lbs (900 kg)', 250, NULL, 'Not available; unknown to the black market. Estimated value is 10 million credits.', 'An Enemy Infiltration Robot (EIR) sculpted and skinned to impersonate a winged gargoyle, used by the NGR as a spy and assassin behind enemy lines; capable of only limited flight/gliding compared to a real gargoyle, and self-destructs when destroyed to avoid capture.', 'Rifts World Book 5: Triax and the NGR p.91-92'),
('eir-15-gargoyle-manned-robot', 'EIR-15 Gargoyle Manned Robot', 'rifts', 'robot', 'One human pilot - typically commando or intelligence.', NULL, 'Running: 40 mph (64 km) maximum, faster than most real gargoyles (15-35 mph/24-56 km). Running does NOT tire the robot or pilot; speed maintained indefinitely.', 'Flying/Gliding: Limited. Maximum speed 40 mph (64 km); maximum height 500 feet (153 m); flight maintained up to 15 minutes. Leaping: normal leap 20 feet (6 m) high/lengthwise; running leap adds 1D6+6 yards/meters; jet thruster assisted leaps up to 80 feet (24.4 m) high/lengthwise.', NULL, 'Height: 20 feet (6 m). Width: Body 8 feet (2.4 m), wing span 30 feet (9 m). Length: Body 6 feet (1.8 m); tail an additional 10-15 feet (3-4.6 m) long.', '3000 lbs (1350 kg)', 280, NULL, 'Not available; unknown to the black market. Estimated value is 10 million credits.', 'A larger, human-piloted version of the EIR-10 gargoyle infiltration robot reserved for commandos and intelligence officers, letting a human pilot infiltrate as a living gargoyle for deep espionage and exploration of Monster Zones.', 'Rifts World Book 5: Triax and the NGR p.93-94'),
('eir-20-gurgoyle-drone', 'EIR-20 Gurgoyle Drone', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Running: 50 mph (80 km) maximum, faster than most real gurgoyles (15-35 mph/24-56 km). Running does NOT tire the robot; speed maintained indefinitely.', 'Flying: Not applicable. Leaping: normal leap 20 feet (6 m) high/lengthwise; running leap adds 1D6+6 yards/meters.', NULL, 'Height: 10 feet (3 m). Width: 4 feet (1.2 m). Length: 3 feet (0.9 m); tail an additional 8 feet (2.4 m) long.', '1000 lbs (450 kg)', 200, NULL, 'Not available; unknown to the black market. Estimated value is 8 million credits.', 'The smaller, wingless gurgoyle version of the Enemy Infiltration Robot, used by the NGR as a spy and assassin to infiltrate enemy forces, perform reconnaissance, and ferret out gargoyle sympathizers and bandits.', 'Rifts World Book 5: Triax and the NGR p.94-95'),
('eir-30-gargoylite-drone', 'EIR-30 Gargoylite Drone', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Running: 10 mph (16 km) maximum.', 'Flying: concealed thrusters (beneath wings/tail/feet) give maximum speed 120 mph (192 km), maximum height 5000 feet (1530 m); flight maintained indefinitely. Leaping: normal leap 5 feet (1.5 m) high/lengthwise; running leap adds 1D6 feet; jet thruster assisted leaps up to 80 feet (24.4 m) high/lengthwise.', NULL, 'Height: 3 feet (0.9 m). Width: 1 foot, 5 inches (0.35 m). Length: 1 foot, 5 inches (0.35 m); stubby tail adds another 1 foot (0.3 m).', '100 lbs (45 kg)', 50, NULL, 'Not available; unknown to the black market. Estimated value is 10 million credits.', 'A small, inexpensive reconnaissance and surveillance drone built to resemble the diminutive gargolyite, used for spying, theft, sabotage and smuggling out prisoners and information; can zoom away on concealed thrusters if suspected of being an EIR.', 'Rifts World Book 5: Triax and the NGR p.95-96'),
('eir-50-gurgoyle-android', 'EIR-50 Gurgoyle Android', 'rifts', 'drone', 'None; artificial intelligence', NULL, 'Average Speed Running: 22.5 mph (36 km); a speed attribute of 33. Effectively the same as a living gurgoyle.', NULL, NULL, 'Average Height: Typically 10 feet (3 m) tall, but can range from 8 to 12 feet (2.4-3.6 m). (Statistical Data otherwise effectively the same as a living gurgoyle.)', '1300 lbs (585 kg)', NULL, NULL, 'Not available; unknown to the black market. Estimated value unknown.', 'An experimental organic robot: the living brain of a recently deceased gurgoyle replaced with a robot brain controlling the mega-damage flesh-and-blood body, giving a near-undetectable infiltrator intended to eventually replace the EIC-100 gurgoyle cyborg.', 'Rifts World Book 5: Triax and the NGR p.96-97'),
('eic-100-gurgoyle-cyborg', 'EIC-100 Gurgoyle Cyborg', 'rifts', 'borg', 'One human volunteer - typically with a background in intelligence.', NULL, 'Running: 90 mph (144 km) maximum; roughly two and a half times faster than most real gurgoyles. Cyborgs fatigue at one-third the rate of a normal human.', 'Flying: Via jet pack only. Leaping: 20 feet (6 m) high/lengthwise; running leap adds 1D6+6 yards/meters.', NULL, 'Average Height: 9 feet (2.7 m). Width: 3 feet, 6 inches (1 m). Length: 3 feet (0.9 m); tail an additional 8 feet (2.4 m) long.', '1200 lbs (540 kg)', 250, NULL, 'Not available; unknown to the black market. Estimated value is two million credits.', 'The NGR''s best infiltration operative: a full-conversion cyborg housed in a gurgoyle-shaped bionic body with cosmetic artificial skin, giving human judgment, emotion and improvisation the robot EIR drones lack, used for reconnaissance, intelligence, sabotage and assassination.', 'Rifts World Book 5: Triax and the NGR p.97-99'),
('vx-300-striker', 'VX-300 Striker', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 120 mph (192 km) maximum.', 'Flying: Via jet pack only. Leaping: 20 feet (6 m) high/lengthwise; running leap adds 30 additional feet (9 m).', NULL, 'Average Height: 7 feet, 6 inches (2.2 m). Width: 3 feet, 6 inches (1 m). Length: 2 feet, 6 inches (0.7 m).', '600 lbs (270 kg)', 180, 2000000, 'Two to four million credits with all standard features and weapons. Poor availability.', 'A light assault cyborg for reconnaissance, guerrilla warfare and seek-and-destroy missions, roughly human size with a removable armored helmet, gauntlet and missile plate that reveal the pilot''s human face and hand.', 'Rifts World Book 5: Triax and the NGR p.99-101'),
('vx-320-cyclops', 'VX-320 Cyclops', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 100 mph (160 km) maximum.', 'Flying: Via jet pack only; see the T-100 Eagle jet pack. Leaping: 15 feet (4.6 m) high/lengthwise; running leap adds 30 additional feet (9 m).', NULL, 'Average Height: 6 feet, 6 inches (2 m). Width: 3 feet, 6 inches (1 m). Length: 2 feet, 6 inches (0.7 m).', '500 lbs (225 kg)', 180, 2000000, 'Two to four million credits with all standard features and weapons. Fair availability.', 'A light, human-looking cyborg named for the single slot visor built into its head; removable gauntlets and forearm plates reveal human-looking hands and arms beneath.', 'Rifts World Book 5: Triax and the NGR p.101-103'),
('vx-340-slasher', 'VX-340 Slasher (Gold Type)', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 100 mph (160 km) in standard light infantry armor or 120 mph (192 km) in light espionage armor or no additional armor.', 'Flying: Via jet pack only; see the T-100 Eagle jet pack (half speed only, due to weight). Leaping: 25 feet (7.6 m) high/lengthwise; running leap adds 30 additional feet (9 m).', NULL, 'Average Height: 8 feet (2.4 m). Width: 4 feet (1.2 m). Length: 3 feet (0.9 m) body; 4 feet (1.2 m) including small launch tubes.', '1000 lbs (450 kg)', 180, 5000000, 'Five million credits with all standard features and weapons. Poor availability.', 'A full conversion cyborg known as the ''Gold Type'' with a monstrous head to intimidate opponents; favors mobility and free hands for explosives and assault weapons over heavy forearm weapons, often sent on espionage or seek-and-destroy missions.', 'Rifts World Book 5: Triax and the NGR p.103-104'),
('vx-370-stopper', 'VX-370 Stopper (Blue Type)', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 100 mph (160 km) in the standard light infantry cyborg armor.', 'Flying: Via jet pack only; see the T-100 Eagle jet pack. Leaping: 15 feet (4.6 m) high/lengthwise; running leap adds 30 additional feet (9 m).', NULL, 'Average Height: 8 feet (2.4 m). Width: 4 feet (1.2 m). Length: 3 feet (0.9 m) (body itself).', '1400 lbs (630 kg)', 200, 5000000, 'Five million credits with all standard features and weapons. Poor availability.', 'A medium-heavy assault cyborg known as the ''Blue Type,'' strong, fast and agile with a monstrous head to intimidate opponents; equipped with a heavy particle beam weapon arm and a mini-machinegun.', 'Rifts World Book 5: Triax and the NGR p.105-106');

INSERT OR IGNORE INTO vehicle_locations
  (vehicle_slug, location, mdc, mdc_note, ordinal)
VALUES
('x-2500-black-knight', 'Electro-Mace (1)', 300, NULL, 1),
('x-2500-black-knight', 'Ton Cannon (1; shoulder)', 150, 'single-asterisk small/difficult target, -3 to strike (sensor head -2); printed as ''Ton Cannon'' in the M.D.C. table but called ''Ion Cannon'' in the Weapon Systems list below (weapon #1) - book naming inconsistency, see flags', 2),
('x-2500-black-knight', 'Leg Missile Launchers (4)', 100, NULL, 3),
('x-2500-black-knight', 'Grenade Tubes (8; on feet)', 12, 'single-asterisk small/difficult target, -3 to strike', 4),
('x-2500-black-knight', 'Lower Arms (2)', 200, NULL, 5),
('x-2500-black-knight', 'Upper Arms (2)', 150, NULL, 6),
('x-2500-black-knight', 'Shoulders (2)', 300, NULL, 7),
('x-2500-black-knight', 'Hands (2)', 120, 'single-asterisk small/difficult target, -3 to strike', 8),
('x-2500-black-knight', 'Legs (2)', 350, NULL, 9),
('x-2500-black-knight', 'Feet (2)', 200, NULL, 10),
('x-2500-black-knight', 'Ankle Searchlights (2)', 20, 'single-asterisk small/difficult target, -3 to strike', 11),
('x-2500-black-knight', 'Leg Spotlights (2; below knees)', 5, 'single-asterisk small/difficult target, -3 to strike', 12),
('x-2500-black-knight', 'Chest Searchlight (1)', 5, 'single-asterisk small/difficult target, -3 to strike', 13),
('x-2500-black-knight', 'Head & Sensors (1)', 275, NULL, 14),
('x-2500-black-knight', 'Main Body', 750, 'double-asterisk: depleting main body shuts armor down completely, making it useless', 15),
('x-2500-black-knight', 'Reinforced Pilot''s Compartment (in chest)', 150, NULL, 16),
('x-2700-dragonwing', 'Tail Swivel Lasers (2; small)', 15, 'single-asterisk small/difficult target, -3 to strike', 1),
('x-2700-dragonwing', 'Weapon Arms (2)', 200, NULL, 2),
('x-2700-dragonwing', 'Forward Machineguns (2: head)', 30, 'single-asterisk small/difficult target, -3 to strike', 3),
('x-2700-dragonwing', 'Forearm Directional Thrusters (4)', 20, NULL, 4),
('x-2700-dragonwing', 'Main Arms (2)', 200, NULL, 5),
('x-2700-dragonwing', 'Hands (2)', 120, 'single-asterisk small/difficult target, -3 to strike', 6),
('x-2700-dragonwing', 'Legs (2)', 300, NULL, 7),
('x-2700-dragonwing', 'Feet Thrusters (2)', 200, NULL, 8),
('x-2700-dragonwing', 'Tail Thrusters (4)', 120, NULL, 9),
('x-2700-dragonwing', 'Main Hatch (1; top)', 120, 'single-asterisk small/difficult target, -3 to strike', 10),
('x-2700-dragonwing', 'Escape Hatch (1; rear)', 75, 'single-asterisk small/difficult target, -3 to strike', 11),
('x-2700-dragonwing', 'Directional Thrusters (10, small)', 10, 'single-asterisk small/difficult target, -3 to strike', 12),
('x-2700-dragonwing', 'Ankle Spotlights (2)', 10, 'single-asterisk small/difficult target, -3 to strike', 13),
('x-2700-dragonwing', 'Chest Searchlights (2)', 30, 'single-asterisk small/difficult target, -3 to strike', 14),
('x-2700-dragonwing', 'Head & Sensors (1)', 275, 'single-asterisk small/difficult target, -3 to strike', 15),
('x-2700-dragonwing', 'Main Body', 525, 'double-asterisk: depleting main body shuts armor down completely, making it useless', 16),
('x-2700-dragonwing', 'Reinforced Pilot''s Compartment (in chest)', 150, NULL, 17),
('x-5000-devastator', 'Super Laser Cannon (1; handheld)', 250, NULL, 1),
('x-5000-devastator', 'Super Ion Cannon (1; back)', 250, NULL, 2),
('x-5000-devastator', 'Long-range Missile Launchers (4; lower legs)', 200, NULL, 3),
('x-5000-devastator', 'Medium Range Missile Launchers (2; forearm)', 100, NULL, 4),
('x-5000-devastator', 'Mini-Missile Launchers (2; head fins)', 100, 'single-asterisk small/difficult target, -3 to strike (sensor head -2)', 5),
('x-5000-devastator', 'Belly Gun (1)', 100, 'single-asterisk small/difficult target, -3 to strike', 6),
('x-5000-devastator', 'Cooling Pylons (4)', 150, NULL, 7),
('x-5000-devastator', 'Lower Arms (2)', 200, NULL, 8),
('x-5000-devastator', 'Upper Arms (2)', 200, NULL, 9),
('x-5000-devastator', 'Shoulders (2)', 350, NULL, 10),
('x-5000-devastator', 'Hands (2)', 150, NULL, 11),
('x-5000-devastator', 'Legs (2)', 500, NULL, 12),
('x-5000-devastator', 'Feet (2)', 250, NULL, 13),
('x-5000-devastator', 'Leg Searchlights (2)', 25, 'single-asterisk small/difficult target, -3 to strike', 14),
('x-5000-devastator', 'Leg Spotlights (2; below knees)', 5, 'single-asterisk small/difficult target, -3 to strike', 15),
('x-5000-devastator', 'Head Searchlight (1; forehead)', 10, 'single-asterisk small/difficult target, -3 to strike', 16),
('x-5000-devastator', 'Main Hatch (1; near head)', 150, NULL, 17),
('x-5000-devastator', 'Emergency Escape Hatches (2)', 10, NULL, 18),
('x-5000-devastator', 'Head & Sensors (1)', 375, NULL, 19),
('x-5000-devastator', 'Main Body', 1500, 'double-asterisk: depleting main body shuts armor down completely, making it useless', 20),
('x-5000-devastator', 'Reinforced Pilot''s Compartment (in chest)', 150, NULL, 21),
('dv-12-dyna-bot', 'Hands (2)', 15, NULL, 1),
('dv-12-dyna-bot', 'Arms (2)', 40, NULL, 2),
('dv-12-dyna-bot', 'Laser Fingers (2; one on each hand)', 2, NULL, 3),
('dv-12-dyna-bot', 'TX-50 Rail Gun (1)', 20, NULL, 4),
('dv-12-dyna-bot', 'Legs (2)', 60, NULL, 5),
('dv-12-dyna-bot', 'Head', 40, 'single-asterisk: destroying head eliminates optics/sensors; robot usually shuts down, but ~1 in 10 continues fighting blindly with no combat bonuses; small/difficult target, called shot at -2 to strike', 6),
('dv-12-dyna-bot', 'Main Body', 130, 'double-asterisk: depleting main body effectively destroys the bot; no additional body armor or power armor can be worn by dyna-bots', 7),
('dv-15-sentry-bot', 'TX-30 Ion Pulse Rifle (1)', 5, NULL, 1),
('dv-15-sentry-bot', 'Searchlight (1; neck area)', 5, NULL, 2),
('dv-15-sentry-bot', 'Laser Fingers (2; one on each hand)', 2, NULL, 3),
('dv-15-sentry-bot', 'Hands (2)', 15, NULL, 4),
('dv-15-sentry-bot', 'Arms (2)', 45, NULL, 5),
('dv-15-sentry-bot', 'Legs (2)', 70, NULL, 6),
('dv-15-sentry-bot', 'Head', 50, 'single-asterisk: destroying head eliminates optics/sensors; ~1 in 10 continues fighting blindly with no combat bonuses; small/difficult target, called shot at -2 to strike', 7),
('dv-15-sentry-bot', 'Main Body', 160, 'double-asterisk: depleting main body effectively destroys the bot; no additional body armor or power armor can be worn', 8),
('dv-40-hunter-killer-drone', 'TX-41 Laser Pulse Rifle (1, large)', 50, NULL, 1),
('dv-40-hunter-killer-drone', 'Searchlight (1; visor in head)', 5, 'single-asterisk small/difficult target, called shot at -3 to strike', 2),
('dv-40-hunter-killer-drone', 'Chainsaw (1; left hand)', 20, 'single-asterisk small/difficult target, called shot at -3 to strike', 3),
('dv-40-hunter-killer-drone', 'Vibro-Sword (1; right arm)', 25, 'single-asterisk small/difficult target, called shot at -3 to strike', 4),
('dv-40-hunter-killer-drone', 'Grenade Launcher (1; neck collar)', 15, 'single-asterisk small/difficult target, called shot at -3 to strike', 5),
('dv-40-hunter-killer-drone', 'Flamethrowers (2)', 15, 'single-asterisk small/difficult target, called shot at -3 to strike', 6),
('dv-40-hunter-killer-drone', 'Hands (2)', 40, 'single-asterisk small/difficult target, called shot at -3 to strike', 7),
('dv-40-hunter-killer-drone', 'Arms (2)', 100, NULL, 8),
('dv-40-hunter-killer-drone', 'Legs (2)', 120, NULL, 9),
('dv-40-hunter-killer-drone', 'Head', 90, 'small/difficult target, called shot at -2 to strike; destroying head eliminates optics/sensors, ~1 in 5 continues fighting blindly with no combat bonuses', 10),
('dv-40-hunter-killer-drone', 'Main Body', 300, 'double-asterisk: depleting main body effectively destroys the bot; no additional body armor or power armor can be worn', 11),
('eir-10-gargoyle-drone', 'Hands (2)', 25, 'small/difficult target, called shot at -2 to strike', 1),
('eir-10-gargoyle-drone', 'Arms (2)', 60, NULL, 2),
('eir-10-gargoyle-drone', 'Legs (2)', 130, NULL, 3),
('eir-10-gargoyle-drone', 'Wings (2)', 110, NULL, 4),
('eir-10-gargoyle-drone', 'Tail (1)', 100, 'small/difficult target, called shot at -2 to strike', 5),
('eir-10-gargoyle-drone', 'Laser Fingers (2; one on each hand)', 8, NULL, 6),
('eir-10-gargoyle-drone', 'Horns (2; head)', 10, NULL, 7),
('eir-10-gargoyle-drone', 'Head', 80, 'small/difficult target, called shot at -2 to strike; destroying head triggers self-destruct: 1D6x10 M.D. to everything in a 100 ft/30.5 m blast radius', 8),
('eir-10-gargoyle-drone', 'Main Body', 250, 'double-asterisk: depleting main body effectively destroys the bot and activates the self-destruct mechanism', 9),
('eir-15-gargoyle-manned-robot', 'Hands (2)', 30, 'small/difficult target, called shot at -2 to strike', 1),
('eir-15-gargoyle-manned-robot', 'Arms (2)', 80, NULL, 2),
('eir-15-gargoyle-manned-robot', 'Legs (2)', 150, NULL, 3),
('eir-15-gargoyle-manned-robot', 'Wings (2)', 110, NULL, 4),
('eir-15-gargoyle-manned-robot', 'Tail (1)', 100, 'small/difficult target, called shot at -2 to strike', 5),
('eir-15-gargoyle-manned-robot', 'Laser Fingers (2; one on each hand)', 10, NULL, 6),
('eir-15-gargoyle-manned-robot', 'Horns (2; head)', 10, NULL, 7),
('eir-15-gargoyle-manned-robot', 'Head', 80, 'small/difficult target, called shot at -2 to strike; destroying head eliminates optics/sensors, forcing pilot to rely on own senses, halving bot''s bonuses and attacks per melee', 8),
('eir-15-gargoyle-manned-robot', 'Pilot''s Compartment', 50, NULL, 9),
('eir-15-gargoyle-manned-robot', 'Main Body', 280, 'double-asterisk: depleting main body effectively destroys the bot and activates the self-destruct mechanism (1D6x10 M.D. in 100 ft/30.5 m radius; 4D6x10 to internal workings/pilot area)', 10),
('eir-20-gurgoyle-drone', 'Hands (2)', 25, 'small/difficult target, called shot at -2 to strike', 1),
('eir-20-gurgoyle-drone', 'Arms (2)', 60, NULL, 2),
('eir-20-gurgoyle-drone', 'Legs (2)', 130, NULL, 3),
('eir-20-gurgoyle-drone', 'Tail (1)', 100, 'small/difficult target, called shot at -2 to strike', 4),
('eir-20-gurgoyle-drone', 'Laser Fingers (2; one on each hand)', 8, NULL, 5),
('eir-20-gurgoyle-drone', 'Horns (2; head)', 10, NULL, 6),
('eir-20-gurgoyle-drone', 'Head', 80, 'small/difficult target, called shot at -2 to strike; destroying head triggers self-destruct: 1D6x10 M.D. in a 100 ft/30.5 m blast radius', 7),
('eir-20-gurgoyle-drone', 'Main Body', 200, 'double-asterisk: depleting main body effectively destroys the bot and activates the self-destruct mechanism', 8),
('eir-30-gargoylite-drone', 'Hands (2)', 5, 'small/difficult target, called shot at -3 to strike', 1),
('eir-30-gargoylite-drone', 'Arms (2)', 15, NULL, 2),
('eir-30-gargoylite-drone', 'Legs (2)', 30, NULL, 3),
('eir-30-gargoylite-drone', 'Wings (2)', 10, NULL, 4),
('eir-30-gargoylite-drone', 'Tail (1)', 10, 'small/difficult target, called shot at -3 to strike', 5),
('eir-30-gargoylite-drone', 'Laser Fingers (2; one on each hand)', 2, NULL, 6),
('eir-30-gargoylite-drone', 'Head', 30, 'small/difficult target, called shot at -3 to strike; destroying head initiates self-destruct: 4D6 M.D. in a 50 ft/15.2 m blast radius', 7),
('eir-30-gargoylite-drone', 'Main Body', 50, 'double-asterisk: depleting main body effectively destroys the bot and activates the self-destruct mechanism', 8),
('eir-50-gurgoyle-android', 'Hands (2)', 20, NULL, 1),
('eir-50-gurgoyle-android', 'Arms (2)', NULL, '2D4 x 10 each (dice formula as printed)', 2),
('eir-50-gurgoyle-android', 'Legs (2)', NULL, '2D6 x 10 each (dice formula as printed)', 3),
('eir-50-gurgoyle-android', 'Tail (1)', NULL, '2D6 x 10 (dice formula as printed)', 4),
('eir-50-gurgoyle-android', 'Cyber-Laser Fingers (2; one on each hand)', 8, NULL, 5),
('eir-50-gurgoyle-android', 'Horns (2; head)', 10, NULL, 6),
('eir-50-gurgoyle-android', 'Head', NULL, 'single-asterisk; 2D4 x 10 (dice formula as printed); destroying head eliminates optics and the artificial brain, killing the android; small/difficult target, called shot at -2 to strike', 7),
('eir-50-gurgoyle-android', 'Main Body', NULL, 'double-asterisk; 1D4 x 100 (dice formula as printed); depleting main body effectively destroys/kills the android', 8),
('eic-100-gurgoyle-cyborg', 'Hands (2)', 20, NULL, 1),
('eic-100-gurgoyle-cyborg', 'Arms (2)', 60, NULL, 2),
('eic-100-gurgoyle-cyborg', 'Legs (2)', 90, NULL, 3),
('eic-100-gurgoyle-cyborg', 'Tail (1)', 100, NULL, 4),
('eic-100-gurgoyle-cyborg', 'Horns (2; head)', 10, NULL, 5),
('eic-100-gurgoyle-cyborg', 'Head', 100, 'single-asterisk; the gurgoyle head is large and reinforced; destroying the head kills the character; small/difficult target, called shot at -3 to strike', 6),
('eic-100-gurgoyle-cyborg', 'Main Body', 250, 'double-asterisk; plus 135 from gurgoyle body armor; depleting main body destroys the artificial body but emergency systems keep brain/vital organs alive for 36 hours', 7),
('vx-300-striker', 'Hand (1)', 10, NULL, 1),
('vx-300-striker', 'Right Arm (1)', 40, NULL, 2),
('vx-300-striker', 'Gun Arm (1)', 60, NULL, 3),
('vx-300-striker', 'Ammo-Drum (1, back)', 60, NULL, 4),
('vx-300-striker', 'Shoulders & Launchers (2)', 50, NULL, 5),
('vx-300-striker', 'Legs (2)', 75, NULL, 6),
('vx-300-striker', 'Head', 60, 'reinforced; destroying head kills the character; small/difficult target, called shot at -3 to strike', 7),
('vx-300-striker', 'Main Body', 180, 'plus an additional 100 M.D.C. from light espionage body armor plates that hook directly to the bionic body; depleting main body destroys the artificial body but emergency systems keep brain/vital organs alive for 36 hours', 8),
('vx-320-cyclops', 'Hands (2)', 10, NULL, 1),
('vx-320-cyclops', 'Arms (2)', 40, NULL, 2),
('vx-320-cyclops', 'Forearm Guns (2)', 10, NULL, 3),
('vx-320-cyclops', 'Grenade Launcher (1)', 30, NULL, 4),
('vx-320-cyclops', 'Legs (2)', 70, NULL, 5),
('vx-320-cyclops', 'Head', 50, 'reinforced; destroying head kills the character; small/difficult target, called shot at -3 to strike', 6),
('vx-320-cyclops', 'Main Body', 180, 'plus an additional 100 M.D.C. from light body armor plates that hook directly to the bionic body', 7),
('vx-340-slasher', 'Hands (2)', 15, 'difficult target, called shot at -4 to strike', 1),
('vx-340-slasher', 'Arms (2)', 40, NULL, 2),
('vx-340-slasher', 'Vibro-Blades (2)', 10, NULL, 3),
('vx-340-slasher', 'Mini-Missile Launch Tubes (4, back)', 20, 'difficult target, called shot at -4 to strike', 4),
('vx-340-slasher', 'TX-500 Rail Gun (1)', 75, NULL, 5),
('vx-340-slasher', 'Rail Gun Drum (1)', 75, NULL, 6),
('vx-340-slasher', 'Legs (2)', 80, NULL, 7),
('vx-340-slasher', 'Head', 90, 'reinforced; destroying head kills the character; small/difficult target, called shot at -3 to strike', 8),
('vx-340-slasher', 'Main Body (normal)', 180, 'plus an additional 270 M.D.C. from its light infantry armor (hooks directly to the bionic body)', 9),
('vx-370-stopper', 'Hand (1)', 15, 'printed as singular ''Hand (1)'' with plural ''15 each'' - unlike every other entry in the book, which uses this format only for multiple items; transcribed as printed, see flags', 1),
('vx-370-stopper', 'Arms (2)', 50, NULL, 2),
('vx-370-stopper', 'Legs (2)', 80, NULL, 3),
('vx-370-stopper', 'Head', 90, 'reinforced; destroying head kills the character; small/difficult target, called shot at -3 to strike', 4),
('vx-370-stopper', 'Main Body (standard)', 200, 'plus an additional 280 M.D.C. from its light infantry armor (hooks directly to the bionic body)', 5);

INSERT OR IGNORE INTO vehicle_weapons
  (vehicle_slug, ordinal, name, damage, is_mega_damage, range,
   rate_of_fire, payload, bonus, note)
VALUES
('x-2500-black-knight', 1, 'Ion Cannon (1)', '1D6 x 10 per blast', 1, '4000 feet (1200 m)', 'Equal to combined hand to hand attacks (usually 4-8)', 'Effectively unlimited', NULL, 'M.D.C. table lists this location as ''Ton Cannon (1; shoulder)''; Weapon Systems text calls it ''Ion Cannon'' - see flags'),
('x-2500-black-knight', 2, 'Forearm Lasers (2)', '3D6 M.D. per single blast or 6D6 M.D. per simultaneous double blast', 1, '4000 feet (1200 m)', 'Equal to combined hand to hand attacks (usually 4-8)', 'Effectively unlimited', NULL, NULL),
('x-2500-black-knight', 3, 'Forearm Vibro-Sword (2)', '5D6 M.D.', 1, 'Hand to hand', NULL, NULL, '+1 to strike and +1 to parry in hand to hand combat', 'Weapon is eight feet long (2.4 m)'),
('x-2500-black-knight', 4, 'Electro-Mace (1)', '4D6 M.D. per strike (blunt); +10 M.D. if electrically charged; or up to three electrical blasts of 1D4x10 M.D. each', 1, 'Electrical discharge max 1000 feet (305 m)', 'Combined hand to hand attacks (usually 4-8); electrical blast max 3/melee', 'Effectively unlimited', NULL, NULL),
('x-2500-black-knight', 5, 'Lower Leg Mini-Missile Launchers (4)', 'Varies with missile type; standard armor piercing (1D4x10 M.D.) or plasma (1D6x10)', 1, 'Usually about a mile', 'One at a time or volleys of 2, 3 or 4', '56 total; 14 in each launcher', NULL, NULL),
('x-2500-black-knight', 6, 'Grenade Tubes (8)', 'Varies with type', 0, '500 feet (152 m)', 'One at a time or volleys of 2 or 4', '32 total; 4 in each launch tube. Typically 10 smoke, 22 tear gas (or 10, 14 and 8 fragmentation)', NULL, NULL),
('x-2500-black-knight', 7, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', NULL, NULL, NULL, 'Restrained Punch 1D6 M.D.; Full Strength Punch 3D6 M.D.; Power Punch 6D6 M.D.(2 atk); Vibro-Blade 5D6; Electro-Mace 4D6(uncharged)/4D6+10(charged); Crush/Pry/Tear 2D6; Kick 3D6; Leap Kick 5D6(2atk); Body Flip/Throw 1D6; Body Block/Ram 2D6; Stomp 2D4 vs targets <=10ft. Bonuses: +2 strike,+4 parry,+3 dodge,+2 roll w/impact,+2 pull punch,+2 actions lvl1,+1 add''l at 3,6,10,14.'),
('x-2700-dragonwing', 1, 'Weapon Arms - Laser Cannon', '1D4 x 10 per blast; double if both weapon arms synchronized on same target (counts as one melee action)', 1, '6000 feet (1828 m)', 'Equal to combined hand to hand attacks (usually 4-8)', 'Effectively unlimited', '+1 to strike, +1 to parry and dodge', 'Special Feature: own laser targeting and short-range radar tracking (3 mile/4.8 km radar range)'),
('x-2700-dragonwing', 1, 'Weapon Arms - Ion Cannon', '1D4 x 10 M.D. per blast; double if synchronized on same target; quadruple if both ion cannons and both laser cannons synchronous at close range (2000 ft/610 m), counts as two melee actions', 1, '2000 feet (610 m)', 'Equal to combined hand to hand attacks (usually 4-8)', 'Effectively unlimited', '+1 to strike, +1 to parry and dodge', NULL),
('x-2700-dragonwing', 2, 'Forward Rapid-Fire Machineguns (2)', '2D4 M.D. per burst of 20 rounds or 4D4 M.D. per simultaneous double burst (40 rounds); low radiation U-Rounds 2D6 M.D. or 4D6 M.D. (double) to supernatural monsters', 1, '4000 feet (1200 m)', 'Equal to combined hand to hand attacks (usually 4-8)', '6000 rounds total; 3000 per machinegun (300 bursts, 150 per gun)', NULL, NULL),
('x-2700-dragonwing', 3, 'Concealed Chest Missiles', 'Varies with missile type; standard armor piercing (2D4x10 M.D.; multi-warhead) or plasma (2D6x10)', 1, '40+ miles (64+ km)', 'One at a time or volleys of two or four', '12 missiles', NULL, NULL),
('x-2700-dragonwing', 4, 'Tail Swivel Laser Mounts (2)', '3D6 M.D. per single blast or 6D6 from simultaneous blast from both', 1, '6000 feet (1828 m)', 'Equal to combined hand to hand attacks (usually 4-8)', 'Effectively unlimited', NULL, NULL),
('x-2700-dragonwing', 5, 'Optional Electro-Mace (1)', '4D6 M.D. per strike (blunt); +10 M.D. if charged; or up to three electrical blasts of 1D4x10 M.D. each', 1, 'Electrical blast max 1000 feet (305 m)', 'Combined hand to hand attacks (usually 4-8); electrical blast max 3/melee', 'Effectively unlimited', NULL, 'Identical to the one used by the Black Knight'),
('x-2700-dragonwing', 6, 'Optional: Slammer Concussion Bombs', '1D4 x 10 M.D. to entire 90 foot (27.4 m) diameter blast radius; knockdown (01-88%) and stun (01-65%) as per Slammer missiles', 1, '6000 feet (1830 m)', 'One at a time or clusters of two to ten', '20 total', NULL, NULL),
('x-2700-dragonwing', 7, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', NULL, NULL, NULL, 'Restrained Punch 1D6; Full Strength Punch 3D6; Power Punch 6D6(2atk); Crush/Pry/Tear 2D6; Kick 3D6; Leap Kick 5D6(2atk); Thruster Blast from Feet 2D6; Body Flip/Throw 1D6; Body Block/Ram 2D6(running); Flying Body Block/Ram 5D6@100mph,1D6x10@200mph,2D4x10@300mph,4D4x10@500mph,4D6x10@Mach1,1D4x100@Mach2 (half damage self at Mach speed); Electro-Mace 4D6(uncharged)/4D6+10(charged); Stomp 2D4 vs targets <=10ft. Bonuses: +2 strike,+4 parry,+3 dodge ground/+5 dodge flying Mach1+,+2 roll w/impact,+2 pull punch,+2 actions lvl1,+1 add''l at 3,6,10,14.'),
('x-5000-devastator', 1, 'TX-5000 Super Laser Cannon (1)', '1D6 x 10 M.D. per single full power blast, or 4D6 M.D. low power blasts', 1, '8000 feet (2438 m)', 'Equal to combined hand to hand attacks (usually 4-8)', '50 full strength blasts; low power blasts fired indefinitely', '+2 to strike', 'Special Feature: Independent and coordinated targeting'),
('x-5000-devastator', 2, 'TX-5001 Super Ion Cannon (1)', '2D4 x 10 M.D. per blast', 1, '4000 feet (1200 m)', 'Equal to combined hand to hand attacks (usually 4-8)', 'Effectively unlimited', '+1 to strike', 'Special Feature: Independent and coordinated targeting'),
('x-5000-devastator', 3, 'Long-Range Missile Launchers (4)', 'Varies with missile type; standard proton torpedoes (4D6x10 M.D.), nuclear multi-warhead (4D6x10 M.D.) or heavy plasma (3D6x10 M.D.); all smart bombs, +5 to strike', 1, 'Usually about 1000+ miles (1640+ km)', 'One at a time or volleys of two or four', '32 missiles total; 8 in each launcher', NULL, NULL),
('x-5000-devastator', 4, 'Medium Range Missile Launchers (2)', 'Varies with missile type; standard armor piercing (2D4x10 M.D.; multi-warhead) or plasma (2D6x10); all missiles +3 to strike', 1, 'Usually about 40+ miles (64+ km)', 'One at a time or volleys of two or four', '16 missiles; 8 in each launcher', NULL, NULL),
('x-5000-devastator', 5, 'Mini-Missile Launchers (2)', 'Varies with missile type; standard armor piercing (1D4x10 M.D.) or plasma (1D6x10)', 1, 'Usually about a mile', 'One at a time or volleys of 2, 3 or 4', '60 total; 30 in each launcher compartment', NULL, NULL),
('x-5000-devastator', 6, 'Ion Belly Gun Turret', '4D6 M.D. per single blast or 1D4 x 10 per dual simultaneous blast', 1, '4000 feet (1200 m)', 'Equal to combined hand to hand attacks (usually 4-6)', 'Effectively unlimited', NULL, 'Turret can fire one gun or both simultaneously; entire upper torso rotates 360 degrees'),
('x-5000-devastator', 7, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', NULL, NULL, NULL, 'Restrained Punch 2D6; Full Strength Punch 1D6x10; Power Punch 2D6x10(2atk); Crush/Pry/Tear 1D6x10; Kick 1D6x10; Leap Kick Not possible; Body Flip/Throw 4D6; Body Block/Ram 1D6x10; Stomp 6D6 vs targets <=15ft. Bonuses: +1 strike(plus weapon bonuses),+1 parry,No dodge,No roll w/impact,No pull punch,+1 add''l action at levels 2,6,10,14.'),
('dv-12-dyna-bot', 1, 'TX-50 Rail Gun (1 or 2)', 'A full damage burst fires 20 rounds and inflicts 5D6 M.D.; a single round does 1D4 M.D.', 1, '4000 feet (1200 m)', 'Equal to the bot''s hand to hand attacks (usually 6)', 'Short clip 200 rounds (10 bursts), light drum 600 rounds (30 bursts), or heavy belt-feed drum 2000 rounds (100 bursts)', NULL, NULL),
('dv-12-dyna-bot', 2, 'Laser finger guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if both fingers fire simultaneously on an aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('dv-12-dyna-bot', 3, 'Concealed Particle Beam Rod (light)', '5D6+6 M.D.', 1, '1600 feet (488 m)', 'Equal to the number of hand to hand melee attacks', 'Effectively unlimited', NULL, 'Concealed in one of the legs, powered by the bot''s nuclear battery; weighs 15 lbs (7 kg)'),
('dv-12-dyna-bot', 4, 'Chemical spray from the mouth', NULL, 0, NULL, NULL, 'Total of 60 doses', NULL, 'Releases toxic mists (same as bionics, Rifts RPG p.240); combat models usually equipped with tranquilizer/sleep spray or tear gas'),
('dv-12-dyna-bot', 5, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Six (6) attacks per melee', NULL, NULL, 'Restrained Punch 2D6+25 S.D.C.; Full Strength Punch 2D6 M.D.; Power Punch 4D6+4 M.D.; Head Butt 1D6 M.D.; Kick 1D8 M.D.; Jump Kick/Leap Attack double damage (2D8 M.D.); Judo throw/flip 1D4 M.D.; critical on natural 19-20. Extensive combat bonuses from programming/sensors listed in text; impervious to poison, gas, biological agents, psionic/magic mind control, charms, bio-manipulation and S.D.C. attacks.'),
('dv-15-sentry-bot', 1, 'TX-30 Ion Pulse Rifle', '2D6 M.D. single shot or 6D6 M.D. pulse mode (3 simultaneous blasts at a single target)', 1, '2000 feet (610 m)', 'Equal to the bot''s hand to hand attacks (usually 6)', '40 shot short E-clip or 50 shot long E-clip', NULL, 'Weighs 7 lbs (3 kg); any handheld weapon can be used in its place'),
('dv-15-sentry-bot', 2, 'DV Laser finger guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if simultaneous aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('dv-15-sentry-bot', 3, 'DV Concealed Particle Beam Rod (light)', '5D6+6 M.D.', 1, '1600 feet (488 m)', 'Equal to the number of hand to hand melee attacks', 'Effectively unlimited', NULL, 'Concealed in one of the legs; weighs 15 lbs (7 kg)'),
('dv-15-sentry-bot', 4, 'Chemical spray from the mouth', NULL, 0, NULL, NULL, 'Total of 60 doses', NULL, 'Sentry models usually equipped with tranquilizer/sleep spray or tear gas'),
('dv-15-sentry-bot', 5, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Six (6) attacks per melee', NULL, NULL, 'Restrained Punch 2D6+25 S.D.C.; Full Strength Punch 2D6 M.D.; Power Punch 4D6+4 M.D.(2atk); Head Butt 1D6 M.D.; Kick 1D8 M.D.; Jump Kick/Leap Attack double damage (2D8 M.D.); Judo throw/flip 1D4 M.D.; critical on natural 19-20. Impervious to poison, gas, biological agents, psionic/magic mind control, charms, bio-manipulation and S.D.C. attacks.'),
('dv-15-sentry-bot', 6, 'TX-50 Rail Gun (1, optional)', 'See DV-12 Dyna-bot for complete details', 1, NULL, NULL, NULL, NULL, 'Optional accessory for the DV-15'),
('dv-15-sentry-bot', 8, 'Hand Grenades', 'Varies; see the X-60 Flanker for grenade descriptions', 0, NULL, NULL, 'Two to eight tear gas/stun or smoke grenades', NULL, 'Provided to impair/confuse attackers or escaping prisoners'),
('dv-40-hunter-killer-drone', 1, 'TX-41 Laser Pulse Rifle (1)', '3D6 M.D. per single shot or 1D6 x 10 M.D. per rapid fire pulse of 3 shots (nearly simultaneous)', 1, '4000 feet (1200 m)', 'Equal to the total number of hand to hand attacks', '100; giant energy clip in front of gun, or cable-connected to bot''s energy supply for effectively indefinite payload (cable can be cut); second E-clip concealed in left leg', NULL, 'Variable frequency laser with 12 light frequencies, changeable by touch or voice command; setting 7 counters the USA-10 Glitter Boy'),
('dv-40-hunter-killer-drone', 2, 'DV-40 Grenade Launcher (1)', 'Varies; typically fragmentation (2D6 M.D. to 20 ft/6 m radius), plasma (5D6 M.D. to 12 ft/3.6 m diameter), smoke (no damage), or riot control/tear gas/stun', 1, '300 feet (91.5 m)', 'One at a time or volleys of two or three fired in rapid succession', '48 total; typically 4 smoke, 4 tear gas, 20 plasma, 20 fragmentation', NULL, NULL),
('dv-40-hunter-killer-drone', 3, 'DV-40 Concealed Particle Beam Rod (1)', '5D6+6 M.D.', 1, '1600 feet (488 m)', 'Equal to the number of hand to hand melee attacks', 'Effectively unlimited', NULL, 'Concealed in the right arm; weighs 15 lbs (7 kg)'),
('dv-40-hunter-killer-drone', 4, 'DV-40 Laser finger guns (2)', 'Two settings: 2D6 M.D. or 3D6 M.D. per finger; double damage if both fingers fire simultaneously on an aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', NULL, NULL),
('dv-40-hunter-killer-drone', 5, 'Forearm Vibro-Sword (1)', '3D6 M.D.', 1, 'Hand to hand', NULL, NULL, '+1 to strike and +1 to parry in hand to hand combat', 'Located in the right forearm; three feet long (0.9 m)'),
('dv-40-hunter-killer-drone', 6, 'Diamond Tipped Chainsaw (1)', '3D6 M.D. per melee attack or 3D6 x 6 M.D. per one full melee (15 seconds) of cutting', 1, 'Touch', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', NULL, 'Located on the left arm; can cut mega-damage steel, concrete and rock'),
('dv-40-hunter-killer-drone', 7, 'Flamethrowers (2)', '1D4 M.D. per single blast or 2D4 per simultaneous double blast of napalm-like fire; 01-90% chance of igniting combustibles, +1D4 M.D./melee burning for 2D4 minutes', 1, '200 feet (61 m)', 'Equal to number of hand to hand attacks (usually 6)', '50 blasts total, 25 from each', NULL, 'Mounted on the rib cage area, 360-degree rotation'),
('dv-40-hunter-killer-drone', 9, 'Optional TX-843P Interchangeable Particle Beam Cannon (1)', '2D4 x 10 M.D. per single blast', 1, '3000 feet (914 m)', 'Equal to number of hand to hand attacks (usually 6)', 'Effectively unlimited', NULL, 'Mounted on shoulders via TX-481 universal mounts (as X-535 Jager); weighs three tons with own energy supply; reduces speed/combat bonuses by 25%'),
('dv-40-hunter-killer-drone', 10, 'Optional TX-884I Interchangeable Ion Cannon & Missile Launcher (1)', 'Ion Cannon: 1D6 x 10 per blast. Missiles: varies with type (armor piercing 2D4x10, plasma 2D6x10)', 1, 'Cannon 4000 feet (1200 m); Missiles 40+ miles (64+ km)', 'Cannon equal to hand to hand attacks (usually 6); missiles one at a time or volleys of two or four', 'Cannon effectively unlimited; missiles 12 total, 6 per launcher', '+1 to strike (cannon)', 'Reduces robot''s speed by 50%; overall weight 6 tons'),
('dv-40-hunter-killer-drone', 11, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Six (6) attacks per melee', NULL, NULL, 'Restrained Punch 1D6 M.D.C.; Full Strength Punch 3D6 M.D.; Power Punch 5D6 M.D.(2atk); Chainsaw 3D6; Vibro-sword 3D6; Head Butt 1D6; Kick 2D6; Body Block 2D6(+1D6 running); Jump Kick/Leap Attack 4D6(2atk); Judo throw/flip 1D6; critical on natural 19-20.'),
('eir-10-gargoyle-drone', 1, 'Laser Eyes (2)', '2D6 M.D. per single eye blast or 4D6 M.D. per double blast (both eyes simultaneously, counts as one melee action)', 1, '2000 feet (610 m)', 'Equal to the bot''s total number of hand to hand attacks per melee', 'Effectively unlimited', '+1 to strike', '180 degree rotation/arc of fire - look and shoot'),
('eir-10-gargoyle-drone', 2, 'Laser Finger Guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if simultaneous aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('eir-10-gargoyle-drone', 3, 'Concealed Vibro-blades in the Forearms (2)', '4D6 M.D. each', 1, 'Hand to hand', 'Equal to the number of hand to hand melee attacks', NULL, NULL, 'Used only for assassination or when the bot has no other course of defense'),
('eir-10-gargoyle-drone', 4, 'Chemical spray from the mouth', NULL, 0, NULL, NULL, 'Total of 60 doses', NULL, 'Combat models usually equipped with tranquilizer/sleep spray or tear gas'),
('eir-10-gargoyle-drone', 5, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Seven (7) attacks per melee', NULL, NULL, 'Restrained Punch 3D6+25 S.D.C.; Full Strength Punch 4D6 M.D.; Power Punch 1D4x10 M.D.; Tail Strike 2D6; Bite 2D4; Head Butt 1D6; Kick 4D6; Jump Kick/Leap Attack 1D4x10; Judo throw/flip 1D6; critical on natural 19-20. Tail is prehensile and can pick up/carry things.'),
('eir-15-gargoyle-manned-robot', 1, 'Weapon Systems (identical to EIR-10 drone)', NULL, 1, NULL, NULL, NULL, NULL, 'Book states: ''Identical to the drone, only operated by the pilot.'' An internal computer and language translator lets the pilot understand and reply in the appropriate monster language. Attacks Per Melee: pilot''s hand to hand plus one additional attack/action at levels 1, 3, 5, 8 and 12 of the pilot''s experience. See EIR-10 Gargoyle Drone for the itemized weapon stats (laser eyes, laser finger guns, concealed forearm vibro-blades, chemical spray, hand to hand).'),
('eir-20-gurgoyle-drone', 1, 'Laser Eyes (2)', '2D6 M.D. per single eye blast or 4D6 M.D. per double blast (both eyes simultaneously, counts as one melee action)', 1, '2000 feet (610 m)', 'Equal to the bot''s total number of hand to hand attacks per melee', 'Effectively unlimited', '+1 to strike', '180 degree rotation/arc of fire - look and shoot'),
('eir-20-gurgoyle-drone', 2, 'Laser Finger Guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if simultaneous aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('eir-20-gurgoyle-drone', 3, 'DV-40 Concealed Particle Beam Rod (1)', '5D6+6 M.D.', 1, '1600 feet (488 m)', 'Equal to the number of hand to hand melee attacks', 'Effectively unlimited', NULL, 'Concealed in the right leg'),
('eir-20-gurgoyle-drone', 4, 'Chemical spray from the mouth', NULL, 0, NULL, NULL, 'Total of 60 doses', NULL, 'Combat models usually equipped with tranquilizer/sleep spray or tear gas'),
('eir-20-gurgoyle-drone', 5, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Seven (7) attacks per melee', NULL, NULL, 'Restrained Punch 3D6+15 S.D.C.; Full Strength Punch 3D6 M.D.; Power Punch 1D4x10 M.D.; Tail Strike 2D6; Bite 2D4; Head Butt 1D6; Kick 4D6; Jump Kick/Leap Attack 1D4x10; Judo throw/flip 1D6; critical on natural 19-20. Tail is prehensile.'),
('eir-30-gargoylite-drone', 1, 'Laser Finger Guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if simultaneous aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('eir-30-gargoylite-drone', 2, 'Chemical spray from the mouth', NULL, 0, NULL, NULL, 'Total of 15 doses', NULL, 'Combat models usually equipped with tranquilizer/sleep spray or tear gas'),
('eir-30-gargoylite-drone', 3, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Five (5) attacks per melee', NULL, NULL, 'Restrained Punch 1D6+5 S.D.C.; Full Strength Punch 1D4 M.D.; Power Punch 2D4 M.D.; Tail Strike not applicable (too small); Bite 1 M.D.; Head Butt 4D6+5 S.D.C.; Kick 1D4 M.D.; Jump Kick/Leap Attack 1D6 M.D. Small size makes it a poor unarmed combatant; ideally uses a human-size energy handgun.'),
('eir-50-gurgoyle-android', 1, 'Laser Finger Guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if simultaneous aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', 'One finger on each hand is artificial and contains the laser'),
('eir-50-gurgoyle-android', 2, 'Garrote Wrist Wire (1)', 'Equal to a power punch: 6D6 M.D. per melee action (every time it is pulled tighter)', 1, 'Hand to hand', NULL, NULL, NULL, 'A thin, giant-sized, thick wire hidden in a cybernetic housing, used for assassination, usually from behind'),
('eir-50-gurgoyle-android', 3, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Seven (7) attacks per melee', NULL, NULL, 'Restrained Punch 3D6+15 S.D.C.; Full Strength Punch 3D6 M.D.; Power Punch 6D6 M.D.; Tail Strike 2D6; Bite 1D6; Head Butt 1D4(not advisable); Kick 3D6; Jump Kick/Leap Attack 6D6; Judo throw/flip 1D6; critical on natural 19-20. Tail is prehensile.'),
('eic-100-gurgoyle-cyborg', 1, 'Laser Eyes (2)', '2D6 M.D. per single eye blast or 4D6 M.D. per double blast (both eyes simultaneously, counts as one melee action)', 1, '2000 feet (610 m)', 'Equal to the borg''s total number of hand to hand attacks per melee', 'Effectively unlimited', '+1 to strike', '180 degree rotation/arc of fire - look and shoot'),
('eic-100-gurgoyle-cyborg', 1, 'Particle Beam Eyes (2)', '5D6+6 M.D. per single eye blast or 1D6 x 10+12 M.D. per double blast (both eyes simultaneously, counts as one melee action)', 1, '800 feet (245 m)', 'Equal to the character''s total number of hand to hand attacks per melee', 'Effectively unlimited', '+1 to strike', 'Exclusive to the NGR military - an over-sized head like the gurgoyle''s is needed; more damage but shorter range than the laser variant'),
('eic-100-gurgoyle-cyborg', 2, 'Laser Finger Guns (2)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D. per finger; double damage if simultaneous aimed shot', 1, '2000 feet (610 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('eic-100-gurgoyle-cyborg', 3, 'VX-40 Concealed Particle Beam Rod (1)', '5D6+6 M.D.', 1, '1600 feet (488 m)', 'Equal to the number of hand to hand melee attacks', 'Effectively unlimited', NULL, 'Concealed in the right leg'),
('eic-100-gurgoyle-cyborg', 4, 'Chemical spray from the mouth', NULL, 0, NULL, NULL, 'Total of 15 doses', NULL, 'Combat models usually equipped with tranquilizer/sleep spray or tear gas'),
('eic-100-gurgoyle-cyborg', 5, 'Retractable Vibro-Blade', '2D6 M.D.', 1, 'Hand to hand', NULL, NULL, NULL, 'A large vibro-sword concealed in the right or left arm'),
('eic-100-gurgoyle-cyborg', 6, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Character''s hand to hand combat skill/experience, plus one additional attack from heightened reflexes and one from the prehensile tail', NULL, NULL, 'Restrained Punch 1D6+15 S.D.C.; Full Strength Punch 1D4 M.D.; Power Punch 2D6 M.D.; Tail Strike 1D6; Bite 6D6 S.D.C.; Head Butt 1D4; Kick 1D4; Jump Kick/Leap Attack 2D4; Judo throw/flip 6D6 S.D.C. Bonuses: +1 initiative, +1 pull punch, +1 roll w/impact, +2 save vs horror factor.'),
('vx-300-striker', 1, 'VX-300 Multiple Grenade Launcher System', 'Special VX-300 fragmentation grenades: 3D6 M.D. to a 50 ft (15 m) radius; or plasma 5D6 M.D. to a 12 ft (3.6 m) radius; or tear gas/stun or smoke', 1, '300 feet (91.5 m)', 'One at a time or volleys of two, three or four', '25 total; seven in each shoulder, five on the forearm, six in the belly. Typical combo: 3 stun/tear gas, 8 plasma, 14 fragmentation', NULL, NULL),
('vx-300-striker', 2, 'VX-300 Rail Gun-Arm (1, standard issue)', 'A full damage burst fires 20 rounds and inflicts 4D6 M.D.; a single round does two M.D.; DU-rounds 5D6 M.D.; U-rounds 5D6 M.D. (also diminishes healing in supernatural beings)', 1, '4000 feet (1200 m)', 'Equal to the character''s hand to hand attacks per melee round (usually 4 to 6)', 'Short clip 200 rounds (10 bursts) or 2000 round drum (100 bursts)', '+1 to strike', 'Built into the borg as part of the left forearm; can be replaced with a mechanical human-like arm or other weapon arm; own laser targeting/distancing, telescopic sight and nightvision scope, range 6000 ft/1828 m'),
('vx-300-striker', 3, 'Laser Finger Gun (1)', 'Three settings: 1D6 x 10 S.D.C., or 1D6 M.D., or 2D6 M.D.', 1, '500 feet (152 m)', 'Equal to the total number of hand to hand attacks', 'Effectively unlimited', '+1 to strike', NULL),
('vx-300-striker', 4, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Character''s hand to hand combat skill/experience plus one additional attack from heightened reflexes', NULL, '+3 to strike, parry and dodge from P.P. 21', 'Restrained Punch 1D6+9 S.D.C.; Full Strength Punch 3D6+9 S.D.C.; Power Punch 1D4 M.D.(2atk); Head Butt 2D6 S.D.C.; Kick 3D6+9 S.D.C.; Jump Kick/Leap Attack 1D6 M.D.(2atk); Judo throw/flip 2D6 S.D.C. Combat Bonuses: +2 initiative, +2 pull punch, +2 roll w/impact, +1 save vs horror factor.'),
('vx-320-cyclops', 1, 'VX-320 Multiple Grenade Launcher System', 'Special fragmentation grenades: 3D6 M.D. to a 50 ft (30.5 m as printed) radius; or plasma 5D6 M.D. to a 12 ft (3.6 m) radius; or tear gas/stun or smoke', 1, '300 feet (91.5 m)', 'One at a time or volleys of two, three or four', '25 total; seven in each shoulder, five on the forearm, six in the belly. Typical combo: 10 plasma, 3 smoke, 12 fragmentation', NULL, 'Radius given as ''50 feet (30.5 m)'' in the text, which is an internally inconsistent conversion (50 ft is ~15.2 m) - transcribed as printed, see flags'),
('vx-320-cyclops', 2, 'VX-320 Wide Beam Ion Disrupter (1)', '2D6 M.D. per blast to everything within a 10 foot (3 m) diameter; 4D6 M.D. at point-blank range (within 4 feet/1.2 m)', 1, '60 feet (18.3 m)', 'Maximum of twice per melee round; each blast counts as one melee action/attack', 'Effectively unlimited; patched into the borg''s power supply', NULL, 'Fires an energy pulse/sphere that expands to strike multiple close targets'),
('vx-320-cyclops', 3, 'Laser Forearm Gun (1)', '2D6 M.D. per blast', 1, '2000 feet (609 m)', 'Equal to the total number of hand to hand attacks', '20 shots per E-clip', NULL, 'Right arm; no penalty or bonus to strike (light design)'),
('vx-320-cyclops', 4, 'Ion Forearm Gun (1)', '3D6 M.D. per blast', 1, '1000 feet (305 m)', 'Equal to the total number of hand to hand attacks', '20 shots per E-clip', NULL, 'Left arm; no penalty or bonus to strike (light design)'),
('vx-320-cyclops', 5, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Character''s hand to hand combat skill/experience plus one additional attack from heightened reflexes', NULL, '+3 to strike, parry and dodge from P.P. 21', 'Restrained Punch 1D6+9 S.D.C.; Full Strength Punch 3D6+9 S.D.C.; Power Punch 1D4 M.D.; Head Butt 2D6 S.D.C.; Kick 3D6+9 S.D.C.; Jump Kick/Leap Attack 1D6 M.D.; Judo throw/flip 2D6 S.D.C. Combat Bonuses: +2 initiative, +2 pull punch, +2 roll w/impact, +1 save vs horror factor.'),
('vx-340-slasher', 1, 'Concealed Vibro-Blades (2)', '2D6 M.D. per strike', 1, 'Hand to hand', 'Total hand to hand melee actions', NULL, NULL, 'Each forearm has a vibro-sword that extends/retracts at will; borg''s P.P. 24 gives +5 strike/parry bonus not including W.P. Sword bonuses'),
('vx-340-slasher', 2, 'VX-340 Mini-Missile Tube Launchers (4)', 'Varies with missile type; standard armor piercing (1D4x10 M.D.) or plasma (1D6x10); fragmentation seldom used', 1, 'Usually about a mile', 'One at a time or volleys of two or three', 'Four total; one in each tube', NULL, NULL),
('vx-340-slasher', 3, 'Concealed Leg Laser Rod (1)', '3D6 M.D. per blast', 1, '3000 feet (914 m)', 'Equal to the total number of hand to hand attacks', '20 shots per E-clip', NULL, 'Right or left hip; release, point and shoot'),
('vx-340-slasher', 4, 'TX-500 or TX-250 Triax Borg Rail Gun (1; standard issue, pick one)', 'Full burst 30 rounds 6D6 M.D.; half burst 15 rounds 3D6 M.D.; one round 1D4 M.D.; DU rounds add 2D6 M.D. (full burst) or 1D6 M.D. (half burst)', 1, '4000 feet (1200 m)', 'One burst per hand to hand melee action/attack', 'Heavy ammo-drum 1170 rounds (39 full bursts); light drum/belt 390 rounds (13 full bursts); mini-clip 90 rounds (3 full bursts)', '+1 to strike', 'Weighs 80 lbs (36.3 kg) gun, 50 lbs (22.7 kg) power pack; 85,000 credits market cost, Fair availability; telescopic, nightvision scope and laser targeting'),
('vx-340-slasher', 5, 'Concealed Weapon Compartments', 'Pair of vibro-knives (1D6 M.D.) and two to eight hand grenades (any type)', 1, NULL, NULL, NULL, NULL, 'Two concealed compartments in the chest'),
('vx-340-slasher', 6, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Character''s hand to hand combat skill/experience plus one additional attack from heightened reflexes', NULL, '+5 to strike, parry and dodge from P.P. 24', 'Restrained Punch 1D6+12 S.D.C.; Full Strength Punch 3D6+12 S.D.C.; Power Punch 1D4 M.D.(2atk); Head Butt 2D6 S.D.C.; Kick 4D6+12 S.D.C.; Jump Kick/Leap Attack 2D4 M.D.(2atk); Judo throw/flip 3D6 S.D.C.; Full Speed Ram/Body Block 1D4 M.D.(2atk). Combat Bonuses: +2 initiative, +3 pull punch, +1 roll w/impact, +1 save vs horror factor.'),
('vx-370-stopper', 1, 'VX-370 Particle Beam Weapon Arm (1, standard issue)', '6D6+6 M.D. per blast', 1, '1000 feet (305 m)', 'Equal to the character''s total number of hand to hand attacks per melee', '50 shots; independent regenerating power supply recharges 10 blasts/hour, or a standard energy rifle E-clip can be inserted for 10 blasts/clip', NULL, 'Penalty: -1 to strike and parry; the arm is heavy and a bit awkward. Right or left forearm.'),
('vx-370-stopper', 2, 'VX-370 Mini-machinegun (1, standard issue)', 'A full damage burst fires 30 rounds and inflicts 2D4 M.D.', 1, '2000 feet (609 m)', 'Equal to the character''s hand to hand attacks per melee round (usually 4 to 6)', '2000 round drum, capable of firing 66 full bursts (30 rounds each)', NULL, 'Penalty: -1 to strike and parry; the arm is heavy and a bit awkward. Gun-arm 25 lbs (11 kg), ammo-drum 40 lbs (18 kg)'),
('vx-370-stopper', 3, 'Concealed Leg Laser Rod (1)', '3D6 M.D. per blast', 1, '3000 feet (914 m)', 'Equal to the total number of hand to hand attacks', '20 shots per E-clip', NULL, 'Left hip; release, point and shoot'),
('vx-370-stopper', 4, 'Hand to Hand Combat', NULL, 1, 'Hand to hand', 'Character''s hand to hand combat skill/experience plus one additional attack from heightened reflexes', NULL, '+4 to strike, parry and dodge from P.P. 22', 'Restrained Punch 1D6+12 S.D.C.; Full Strength Punch 3D6+12 S.D.C.; Power Punch 1D4 M.D.(2atk); Head Butt 2D6 S.D.C.; Kick 4D6+12 S.D.C.; Jump Kick/Leap Attack 2D4 M.D.(2atk); Judo throw/flip 3D6 S.D.C.; Full Speed Ram/Body Block 1D4 M.D.(2atk). Combat Bonuses: +1 initiative, +1 pull punch, +1 save vs horror factor.');

-- Read the result back rather than trusting the exit code. INSERT OR IGNORE
-- is silent on collision, so what matters is how many rows are THERE.
SELECT 'vessels from p071-105' AS assertion,
       count(*) AS got, 16 AS want
  FROM vehicles WHERE slug IN ('x-2500-black-knight', 'x-2700-dragonwing', 'x-5000-devastator', 'dv-12-dyna-bot', 'dv-15-sentry-bot', 'dv-40-hunter-killer-drone', 'eir-10-gargoyle-drone', 'eir-15-gargoyle-manned-robot', 'eir-20-gurgoyle-drone', 'eir-30-gargoylite-drone', 'eir-50-gurgoyle-android', 'eic-100-gurgoyle-cyborg', 'vx-300-striker', 'vx-320-cyclops', 'vx-340-slasher', 'vx-370-stopper');

SELECT 'their M.D.C.-by-location rows' AS assertion,
       count(*) AS got, 159 AS want
  FROM vehicle_locations WHERE vehicle_slug IN ('x-2500-black-knight', 'x-2700-dragonwing', 'x-5000-devastator', 'dv-12-dyna-bot', 'dv-15-sentry-bot', 'dv-40-hunter-killer-drone', 'eir-10-gargoyle-drone', 'eir-15-gargoyle-manned-robot', 'eir-20-gurgoyle-drone', 'eir-30-gargoylite-drone', 'eir-50-gurgoyle-android', 'eic-100-gurgoyle-cyborg', 'vx-300-striker', 'vx-320-cyclops', 'vx-340-slasher', 'vx-370-stopper');

SELECT 'their weapon systems' AS assertion,
       count(*) AS got, 87 AS want
  FROM vehicle_weapons WHERE vehicle_slug IN ('x-2500-black-knight', 'x-2700-dragonwing', 'x-5000-devastator', 'dv-12-dyna-bot', 'dv-15-sentry-bot', 'dv-40-hunter-killer-drone', 'eir-10-gargoyle-drone', 'eir-15-gargoyle-manned-robot', 'eir-20-gurgoyle-drone', 'eir-30-gargoylite-drone', 'eir-50-gurgoyle-android', 'eic-100-gurgoyle-cyborg', 'vx-300-striker', 'vx-320-cyclops', 'vx-340-slasher', 'vx-370-stopper');

SELECT 'every location row points at a vessel that exists' AS assertion,
       count(*) AS got, 0 AS want
  FROM vehicle_locations l
  LEFT JOIN vehicles v ON v.slug = l.vehicle_slug
  WHERE v.slug IS NULL;

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('zzzzzz-triax-vessels-p071-105.sql');
