-- Step 4 of the Nightbane extraction plan (apps/character-creator/docs/surveys/nightbane-core.md):
-- Containers, miscellaneous equipment, acids and clothing. Printed 228-231. 218 rows.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/zzzzzzzzzzzzz-nb-gear-f-containers-equipment-clothing.sql
--
-- D4 (#1126): every item in the equipment chapter is its own `nightbane` row, on
-- Nate's word, read off the Nightbane pages rather than shared with Heroes Unlimited's
-- rows for the near-identical chapter. HU's scripts (add-hu-gear-*.sql) are the
-- PRECEDENT for shape - names, where a combined entry splits into priced rows, which
-- column a number goes in - and each row here was diffed against its HU counterpart
-- to catch misreads. Where the two books disagree, this file holds what Nightbane
-- prints; the PR lists every disagreement and its evidence.
--
-- Slugs are the name plus `-nb`, so no Nightbane row can collide with a row of
-- another game. `cost` is dollars, a range's low end; NULL where the page prints no
-- price, with any printed wording in cost_note. Citations are printed folios
-- (cache page = folio + 1).

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('saddlebag-horse-nb', 'Saddlebag (horse)', 'nightbane', 'gear', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('small-pocket-purse-nb', 'Small Pocket Purse', 'nightbane', 'gear', NULL, 5, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('belt-purse-nb', 'Belt Purse', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Attaches to a belt. Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('shoulder-purse-small-nb', 'Shoulder Purse - Small', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('shoulder-purse-large-nb', 'Shoulder Purse - Large', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('small-sack-nb', 'Small Sack', 'nightbane', 'gear', NULL, 6, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('large-sack-nb', 'Large Sack', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('knapsack-nb', 'Knapsack', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('back-pack-nb', 'Back Pack', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('cloth-handle-bag-nb', 'Cloth Handle Bag', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('tobacco-pouch-nb', 'Tobacco Pouch', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('waterskin-2-pints-nb', 'Waterskin - 2 pints', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('waterskin-half-gallon-nb', 'Waterskin - half gallon', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('waterskin-1-gallon-nb', 'Waterskin - 1 gallon', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('cask-wooden-4-gallons-nb', 'Cask, Wooden - 4 gallons', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('cask-wooden-10-gallons-nb', 'Cask, Wooden - 10 gallons', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('cask-wooden-25-gallons-nb', 'Cask, Wooden - 25 gallons', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('vial-glass-2-ounce-nb', 'Vial, Glass - 2 ounce', 'nightbane', 'gear', NULL, 4, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('jar-glass-1-pint-nb', 'Jar, Glass - 1 pint', 'nightbane', 'gear', NULL, 4, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('jar-2-pints-nb', 'Jar - 2 pints', 'nightbane', 'gear', NULL, 2, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228. Printed below the $4.00 1 pint glass jar above it; this line does not say glass, and the render confirms $2.00.', 'Nightbane RPG p.228'),
  ('jar-4-pints-nb', 'Jar - 4 pints', 'nightbane', 'gear', NULL, 4, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('jar-1-gallon-nb', 'Jar - 1 gallon', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('jug-half-gallon-nb', 'Jug - half gallon', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('jug-1-gallon-nb', 'Jug - 1 gallon', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('jug-5-gallons-nb', 'Jug - 5 gallons', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('small-wood-crate-nb', 'Small Wood Crate', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('medium-wood-crate-nb', 'Medium Wood Crate', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('large-wood-crate-nb', 'Large Wood Crate', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Containers price list, printed 228.', 'Nightbane RPG p.228'),
  ('trunk-small-wood-nb', 'Trunk, Small Wood', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, 30, '25lbs.', 'Nightbane RPG p.228'),
  ('trunk-large-wood-nb', 'Trunk, Large Wood', 'nightbane', 'gear', NULL, 200, NULL, NULL, 0, NULL, NULL, NULL, NULL, 70, '50lbs.', 'Nightbane RPG p.228'),
  ('small-metal-security-box-nb', 'Small Metal Security Box', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, 30, '5lb.', 'Nightbane RPG p.228'),
  ('large-metal-security-box-nb', 'Large Metal Security Box', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, 90, '15lbs.', 'Nightbane RPG p.228'),
  ('metal-trunk-small-nb', 'Metal Trunk, Small', 'nightbane', 'gear', NULL, 250, NULL, NULL, 0, NULL, NULL, NULL, NULL, 100, '35lbs.', 'Nightbane RPG p.228'),
  ('metal-trunk-large-nb', 'Metal Trunk, Large', 'nightbane', 'gear', NULL, 500, NULL, NULL, 0, NULL, NULL, NULL, NULL, 200, '80lbs.', 'Nightbane RPG p.228'),
  ('small-safe-nb', 'Small Safe', 'nightbane', 'gear', NULL, 900, NULL, NULL, 0, NULL, NULL, NULL, NULL, 350, '50lbs.', 'Nightbane RPG p.228'),
  ('large-safe-nb', 'Large Safe', 'nightbane', 'gear', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, 1000, '300lbs.', 'Nightbane RPG p.228'),
  ('bullet-resistant-attache-case-nb', 'Bullet Resistant Attache Case', 'nightbane', 'gear', NULL, 440, NULL, NULL, 0, NULL, NULL, NULL, 15, 140, 'Miscellaneous equipment, printed 228.', 'Nightbane RPG p.228'),
  ('courier-briefcase-nb', 'Courier Briefcase', 'nightbane', 'gear', NULL, 225, NULL, NULL, 0, NULL, NULL, NULL, 11, 90, 'Miscellaneous equipment, printed 228.', 'Nightbane RPG p.228'),
  ('acoustic-noise-generator-nb', 'Acoustic Noise Generator', 'nightbane', 'gear', NULL, 900, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Muffles conversations and distorts bugging systems by 30%.', 'Nightbane RPG p.228'),
  ('camouflage-paint-kit-nb', 'Camouflage Paint Kit', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '4 spray cans plus 6 stencils for easy camouflaging of vehicles, bunkers and any field equipment. One kit covers approximately 100 square feet of surface. Available in jungle, forest or arctic.', 'Nightbane RPG p.228');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('camouflage-tape-nb', 'Camouflage Tape', 'nightbane', 'gear', NULL, 6, '$6.00 per roll', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The ever popular duct tape, in rolls 26ft long and two inches wide. Available in jungle, forest or desert camouflage, or in olive drab.', 'Nightbane RPG p.228'),
  ('camouflage-compact-nb', 'Camouflage Compact', 'nightbane', 'gear', NULL, 18, '$18.00 each', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A one-man kit for camouflage or night operations with enough face and hand paint for 6 applications. Mirror, brush and disposable cleaning pads are included in a neat black case 4 inches in diameter and half an inch high.', 'Nightbane RPG p.228'),
  ('climbing-kit-nb', 'Climbing Kit', 'nightbane', 'gear', NULL, 1100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A complete set of equipment for rappelling, rock scaling or climbing: 3,600ft reels of 4500 test rope (each reel weighs 40lbs), an adjustable harness with clamps, 6 pairs of canvas climbing gloves, 48 clamps, 48 fasteners, 48 pitons, 3 hammers, 2 grappling hooks and one pulley. Weight with shipping crate is 190lbs.', 'Nightbane RPG p.228'),
  ('ear-protector-headphones-nb', 'Ear Protector Headphones', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The answer to the Demo expert''s and grenadier''s dreams. The same model is used by airport workers to preserve hearing in noisy environments.', 'Nightbane RPG p.228'),
  ('electro-adhesive-pads-and-generator-nb', 'Electro-Adhesive Pads and Generator', 'nightbane', 'gear', NULL, 40000, '$40,000 for the two pads and the hip or back-pack generator; not commonly available', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A hand-held device that adheres strongly to any metal surface by passing a small current through two metal electrodes. These pads are commonly used by astronauts and can be used in astronauts'' shoes, but the hand-held pads are much more flexible and generally preferred. Two pads plus a hip or back-pack generator. Can hold up to 1000lbs; works ONLY on metal.', 'Nightbane RPG p.228'),
  ('electro-adhesive-shoes-nb', 'Electro-Adhesive Shoes', 'nightbane', 'gear', NULL, 50000, '$50,000; not commonly available', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The shoe form of the Electro-Adhesive Pad, priced separately in the same entry on printed 228. Can hold up to 1000lbs; works only on metal.', 'Nightbane RPG p.228'),
  ('flashlight-small-nb', 'Flashlight - Small', 'nightbane', 'gear', NULL, 5, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('flashlight-medium-nb', 'Flashlight - Medium', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('flashlight-large-nb', 'Flashlight - Large', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('flashlight-unbreakable-kel-lite-small-nb', 'Flashlight - Unbreakable (Kel-lite), Small', 'nightbane', 'gear', NULL, 24, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('flashlight-unbreakable-kel-lite-medium-nb', 'Flashlight - Unbreakable (Kel-lite), Medium', 'nightbane', 'gear', NULL, 28, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('flashlight-unbreakable-kel-lite-large-nb', 'Flashlight - Unbreakable (Kel-lite), Large', 'nightbane', 'gear', NULL, 32, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('flashlight-unbreakable-kel-lite-very-large-nb', 'Flashlight - Unbreakable (Kel-lite), Very Large', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('rechargeable-unbreakable-flashlight-20-000-candle-power-nb', 'Rechargeable Unbreakable Flashlight (20,000 candle power)', 'nightbane', 'gear', NULL, 130, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '10 times brighter than most conventional types; quartz-halogen bulb, 12 inches (0.3m), 1.8lbs, 20,000 candle power.', 'Nightbane RPG p.228'),
  ('rechargeable-unbreakable-flashlight-35-000-candle-power-nb', 'Rechargeable Unbreakable Flashlight (35,000 candle power)', 'nightbane', 'gear', NULL, 160, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The 35,000 candle power version of the rechargeable unbreakable flashlight, priced separately in the same entry on printed 228.', 'Nightbane RPG p.228'),
  ('portable-halogen-spotlight-nb', 'Portable Halogen Spotlight', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '50,000 candle power.', 'Nightbane RPG p.228'),
  ('treated-torch-nb', 'Treated Torch', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('candle-stick-per-dozen-nb', 'Candle Stick - Per Dozen', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('oil-lantern-6-hours-1-pint-nb', 'Oil Lantern - 6 hours/1 pint', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('oil-lantern-12-hours-2-pints-nb', 'Oil Lantern - 12 hours/2 pints', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('oil-lamp-6-hours-nb', 'Oil Lamp - 6 hours', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('padlock-light-nb', 'Padlock - Light', 'nightbane', 'gear', NULL, 5, NULL, NULL, 0, NULL, NULL, NULL, NULL, 25, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('padlock-medium-nb', 'Padlock - Medium', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, 50, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('padlock-heavy-nb', 'Padlock - Heavy', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, 75, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('padlock-burglar-proof-nb', 'Padlock - Burglar proof', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, 80, '60% chance to be picked.', 'Nightbane RPG p.228'),
  ('handcuffs-regular-nb', 'Handcuffs - Regular', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, 60, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('handcuffs-heavy-nb', 'Handcuffs - Heavy', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, 120, 'Miscellaneous equipment price list, printed 228.', 'Nightbane RPG p.228'),
  ('medical-bag-nb', 'Medical Bag', 'nightbane', 'gear', NULL, 275, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'An 8lb complete Medic''s field kit: adhesive pads, bandages, gauze pads, adhesive tape, splints, sterile gloves, scissors, forceps, thermometer, needle, razor blades, pins, medicine, ointment and salt tablets. Back pack and shoulder straps; available in camouflage, green or khaki.', 'Nightbane RPG p.228'),
  ('professional-medical-kit-nb', 'Professional Medical Kit', 'nightbane', 'gear', NULL, 200, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A comprehensive first aid kit with six doses each of antibiotics, anti-inflammatories, sedatives and painkillers; an assorted mini-instrument pack with scalpels, scissors, probes, etc., a dozen in all; tape, bandages, sutures and four air filters.', 'Nightbane RPG p.228'),
  ('professional-medical-kit-open-market-without-drugs-nb', 'Professional Medical Kit (open market, without drugs)', 'nightbane', 'gear', NULL, 1500, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The same kit WITHOUT the drugs, which is the form printed 228 says is available on the open market, at a cost of $1500.', 'Nightbane RPG p.228'),
  ('machete-nb', 'Machete', 'nightbane', 'gear', NULL, 30, NULL, '1D6', 0, NULL, NULL, NULL, NULL, NULL, 'Complete with canvas sheath.', 'Nightbane RPG p.228'),
  ('wirecutters-nb', 'Wirecutters', 'nightbane', 'gear', NULL, 65, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '8 inch wirecutter with nonconducting handles to avoid the nasty "shock" of electrified fences. Complete with belt sheath.', 'Nightbane RPG p.228'),
  ('rations-nb', 'Rations', 'nightbane', 'gear', 200, 470, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Dry field rations; each 15lb case includes 12 meals. A crate is stocked with 12 cases and has a total shipping weight of 200lbs.', 'Nightbane RPG p.229'),
  ('food-ration-packs-nb', 'Food Ration Packs', 'nightbane', 'gear', NULL, 2000, '$2000. Limited availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A food pack of concentrated, vitamin enriched, freeze-dried rations, enough to easily last two weeks; can be stretched to last four weeks if necessary. Geared for two-man consumption.', 'Nightbane RPG p.229'),
  ('padded-helmet-nb', 'Padded Helmet', 'nightbane', 'gear', NULL, 25, '$25 to $75', NULL, 0, NULL, NULL, NULL, 10, NULL, 'A padded helmet, A.R. 10.', 'Nightbane RPG p.229'),
  ('protective-goggles-or-tinted-visor-nb', 'Protective Goggles or Tinted Visor', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Designed for use outdoors or for welding. Unbreakable plastic lenses. Printed 229 ALSO lists a plain Protective Goggles at $10.00 in the price lines a few entries later; both are rows, each as printed.', 'Nightbane RPG p.229'),
  ('face-protector-and-gas-mask-nb', 'Face Protector and Gas Mask', 'nightbane', 'gear', NULL, 200, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The mask can attach to most standard helmets, providing added protection to the face and eyes. Tinted visor and detachable air filter are standard.', 'Nightbane RPG p.229'),
  ('face-protector-and-gas-mask-with-independent-oxygen-nb', 'Face Protector and Gas Mask with Independent Oxygen', 'nightbane', 'gear', NULL, 600, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The same mask with gas mask modification and an independent oxygen supply (2 hours), priced in the same entry on printed 229.', 'Nightbane RPG p.229'),
  ('conventional-air-filter-nb', 'Conventional Air Filter', 'nightbane', 'gear', NULL, 75, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Fits over nose and mouth.', 'Nightbane RPG p.229'),
  ('conventional-gas-mask-nb', 'Conventional Gas Mask', 'nightbane', 'gear', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'With a superior filtering system.', 'Nightbane RPG p.229');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('gas-mask-nb', 'Gas Mask', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Will filter out CS, smoke and a variety of military gases. Note: NOT recommended as protection against nerve gas or radiation.', 'Nightbane RPG p.229'),
  ('sunglasses-light-adjusting-nb', 'Sunglasses - Light Adjusting', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('sunglasses-aviator-nb', 'Sunglasses - Aviator', 'nightbane', 'gear', NULL, 45, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('shooting-glasses-nb', 'Shooting Glasses', 'nightbane', 'gear', NULL, 72, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Change color and density in response to changes in light and weather. Also reduces glare and improves visibility.', 'Nightbane RPG p.229'),
  ('protective-goggles-nb', 'Protective Goggles', 'nightbane', 'gear', NULL, 10, '$10.00 in the price lines; the `Protective Goggles or Tinted Visor` entry on the same page prints $20.00', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('basic-phone-nb', 'Basic Phone', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('telephone-answering-machine-nb', 'Telephone Answering Machine', 'nightbane', 'gear', NULL, 120, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('tape-recorder-nb', 'Tape Recorder', 'nightbane', 'gear', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, '30-60 min. recording time; pocket size. Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('basic-computer-nb', 'Basic Computer', 'nightbane', 'gear', NULL, 650, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('ibm-compatible-ms-dos-nb', 'IBM Compatible (MS Dos)', 'nightbane', 'gear', NULL, 1800, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('ibm-computer-top-of-the-line-nb', 'IBM Computer (top of the line)', 'nightbane', 'gear', NULL, 20000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('monitor-black-and-white-nb', 'Monitor - Black and White', 'nightbane', 'gear', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('monitor-green-or-amber-nb', 'Monitor - Green or Amber', 'nightbane', 'gear', NULL, 250, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('monitor-full-color-nb', 'Monitor - Full Color', 'nightbane', 'gear', NULL, 800, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('basic-printer-nb', 'Basic Printer', 'nightbane', 'gear', NULL, 250, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('letter-quality-printer-nb', 'Letter Quality Printer', 'nightbane', 'gear', NULL, 650, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('laser-printer-top-quality-nb', 'Laser Printer (top quality)', 'nightbane', 'gear', NULL, 2800, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('telephone-modem-nb', 'Telephone Modem', 'nightbane', 'gear', NULL, 150, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Miscellaneous equipment price list, printed 229.', 'Nightbane RPG p.229'),
  ('jet-pack-nb', 'Jet Pack', 'nightbane', 'gear', NULL, 80000, '$80,000.00, plus $500.00 per tank of fuel - one tank is the 40 minute flight capacity', NULL, 0, NULL, NULL, NULL, NULL, 100, 'Speed: 80mph maximum. Duration of flight: 40 minutes maximum. Maximum height: 300ft. Jet Pack S.D.C.: 100.', 'Nightbane RPG p.229'),
  ('space-suit-nb', 'Space Suit', 'nightbane', 'gear', NULL, 250000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Complete: a self-contained environmental suit, insulated, heat and cold shielded, oxygen and life support system; the whole works.', 'Nightbane RPG p.229'),
  ('organic-acid-nb', 'Organic Acid', 'nightbane', 'gear', NULL, 75, '$75.00 per half gallon. The cost line calls this one Organic I', '2-12 per melee for four melees', 0, NULL, NULL, NULL, NULL, NULL, 'Affects only organic substances. All acids are not common household items and must be acquired from a chemical supplier, industry or an illegal outlet. From a supplier or industry, large bulk orders may be required; from an illegal outlet availability is extremely low (9% chance of getting the item) and the cost is multiplied ten times.', 'Nightbane RPG p.229'),
  ('organic-acid-concentrated-nb', 'Organic Acid (concentrated)', 'nightbane', 'gear', NULL, 120, '$120.00 per half gallon. The cost line calls this one Organic II', '4-24 per melee for four melees', 0, NULL, NULL, NULL, NULL, NULL, 'The concentrated form; affects organic substances. All acids are not common household items and must be acquired from a chemical supplier, industry or an illegal outlet. From a supplier or industry, large bulk orders may be required; from an illegal outlet availability is extremely low (9% chance of getting the item) and the cost is multiplied ten times.', 'Nightbane RPG p.229'),
  ('cleanser-nb', 'Cleanser', 'nightbane', 'gear', NULL, 180, '$180.00 per half gallon', '2-12 to organic, 1-6 to all other substances', 0, NULL, NULL, NULL, NULL, NULL, 'Does 2-12 damage to organic and 1-6 damage to all other substances. All acids are not common household items and must be acquired from a chemical supplier, industry or an illegal outlet. From a supplier or industry, large bulk orders may be required; from an illegal outlet availability is extremely low (9% chance of getting the item) and the cost is multiplied ten times.', 'Nightbane RPG p.229'),
  ('metal-dissolver-nb', 'Metal Dissolver', 'nightbane', 'gear', NULL, 600, '$600.00 per half gallon', '4-24 per melee for four melees, 1-8 per melee to organics and plastics', 0, NULL, NULL, NULL, NULL, NULL, 'Industrial. All acids are not common household items and must be acquired from a chemical supplier, industry or an illegal outlet. From a supplier or industry, large bulk orders may be required; from an illegal outlet availability is extremely low (9% chance of getting the item) and the cost is multiplied ten times.', 'Nightbane RPG p.229'),
  ('nylon-cord-nb', 'Nylon Cord', 'nightbane', 'gear', NULL, 100, 'about $100. Good availability', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A variety of heavy-duty, all-purpose nylon rope or cord. Average tension strength is 600lbs (270kg); average length is 300ft (90m).', 'Nightbane RPG p.229'),
  ('police-style-jumpsuit-nb', 'Police Style Jumpsuit', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'One-piece, zippers down the middle; large zippered chest pockets (2), front pockets (2), rear pockets (2), pencil/pen slot (left arm), sleeves and leg cuffs zipper for adjustability, bi-swing pleated back, and padded knees.', 'Nightbane RPG p.229'),
  ('heavy-camouflage-coveralls-tiger-stripe-camouflage-nb', 'Heavy Camouflage Coveralls - Tiger Stripe Camouflage', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Heavy Camouflage Coveralls (jumpsuit style): insulated lining for cold weather (above freezing level cold), wrist and ankle elastic for tight fit, 6 pockets (chest, hip, rear). Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('heavy-camouflage-coveralls-tree-bark-camouflage-nb', 'Heavy Camouflage Coveralls - Tree Bark Camouflage', 'nightbane', 'gear', NULL, 85, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Heavy Camouflage Coveralls (jumpsuit style): insulated lining for cold weather (above freezing level cold), wrist and ankle elastic for tight fit, 6 pockets (chest, hip, rear). Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('heavy-camouflage-coveralls-black-or-white-nb', 'Heavy Camouflage Coveralls - Black or White', 'nightbane', 'gear', NULL, 75, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Heavy Camouflage Coveralls (jumpsuit style): insulated lining for cold weather (above freezing level cold), wrist and ankle elastic for tight fit, 6 pockets (chest, hip, rear). Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('heavy-camouflage-coveralls-green-nb', 'Heavy Camouflage Coveralls - Green', 'nightbane', 'gear', NULL, 75, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Heavy Camouflage Coveralls (jumpsuit style): insulated lining for cold weather (above freezing level cold), wrist and ankle elastic for tight fit, 6 pockets (chest, hip, rear). Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('light-camouflage-coveralls-tiger-stripe-camouflage-nb', 'Light Camouflage Coveralls - Tiger Stripe Camouflage', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Light Camouflage Coveralls (jumpsuit style): cotton and polyester blend. Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('light-camouflage-coveralls-tree-bark-camouflage-nb', 'Light Camouflage Coveralls - Tree Bark Camouflage', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Light Camouflage Coveralls (jumpsuit style): cotton and polyester blend. Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('light-camouflage-coveralls-black-or-white-nb', 'Light Camouflage Coveralls - Black or White', 'nightbane', 'gear', NULL, 45, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Light Camouflage Coveralls (jumpsuit style): cotton and polyester blend. Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('light-camouflage-coveralls-green-nb', 'Light Camouflage Coveralls - Green', 'nightbane', 'gear', NULL, 45, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Light Camouflage Coveralls (jumpsuit style): cotton and polyester blend. Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('3-d-camouflage-suit-nb', '3-D Camouflage Suit', 'nightbane', 'gear', NULL, 150, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A multi-shade of drab green and brown, with approximately 250 individual hanging strips to blend into the foliage. Bonus: +10% on prowl skill when in woodland environment.', 'Nightbane RPG p.229'),
  ('below-30-degree-coveralls-nb', 'Below 30 Degree Coveralls', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Insulated for prolonged exposure in the extreme cold, with thick turtleneck collar that covers chin, nose and mouth. The outer fabric is an acid resistant cotton/polyester twill; zippers at leg bottoms for easy removal; knit, windproof cuffs; sleeve pockets (one each arm) and six large pockets. Comes with zip-off hood. Suitable for up to 20 degrees below zero Fahrenheit.', 'Nightbane RPG p.229'),
  ('work-overalls-nb', 'Work Overalls', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Jumpsuit style.', 'Nightbane RPG p.229'),
  ('expendable-lab-coat-or-coveralls-nb', 'Expendable Lab Coat or Coveralls', 'nightbane', 'gear', NULL, 6, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Made from a special non-woven fabric that is acid, grease and lint resistant. Can be worn once or a dozen times, then thrown away.', 'Nightbane RPG p.229'),
  ('battle-dress-uniform-fatigues-pants-tiger-stripe-camouflage-nb', 'Battle Dress Uniform (Fatigues) - Pants - Tiger Stripe Camouflage', 'nightbane', 'gear', NULL, 30, 'Pants: 6 pockets, adjustable waist tab, button fly, drawstring cuffs', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) pants: 6 pockets, adjustable waist tab, button fly, drawstring cuffs. Combat/hunting clothing, printed 229.', 'Nightbane RPG p.229'),
  ('battle-dress-uniform-fatigues-pants-tree-bark-camouflage-nb', 'Battle Dress Uniform (Fatigues) - Pants - Tree Bark Camouflage', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) pants: 6 pockets, adjustable waist tab, button fly, drawstring cuffs. Combat/hunting clothing; the pants list begins on printed 229 and continues on 230.', 'Nightbane RPG p.230');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('battle-dress-uniform-fatigues-pants-s-w-a-t-black-nb', 'Battle Dress Uniform (Fatigues) - Pants - S.W.A.T. Black', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) pants: 6 pockets, adjustable waist tab, button fly, drawstring cuffs. Combat/hunting clothing; the pants list begins on printed 229 and continues on 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-pants-olive-green-nb', 'Battle Dress Uniform (Fatigues) - Pants - Olive Green', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) pants: 6 pockets, adjustable waist tab, button fly, drawstring cuffs. Combat/hunting clothing; the pants list begins on printed 229 and continues on 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-pants-white-or-khaki-nb', 'Battle Dress Uniform (Fatigues) - Pants - White or Khaki', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) pants: 6 pockets, adjustable waist tab, button fly, drawstring cuffs. Combat/hunting clothing; the pants list begins on printed 229 and continues on 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-shirt-tiger-stripe-camouflage-nb', 'Battle Dress Uniform (Fatigues) - Shirt - Tiger Stripe Camouflage', 'nightbane', 'gear', NULL, 30, 'Shirts: 4 pockets', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) shirt, 4 pockets. Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-shirt-tree-bark-camouflage-nb', 'Battle Dress Uniform (Fatigues) - Shirt - Tree Bark Camouflage', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) shirt, 4 pockets. Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-shirt-s-w-a-t-black-nb', 'Battle Dress Uniform (Fatigues) - Shirt - S.W.A.T. Black', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) shirt, 4 pockets. Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-shirt-olive-green-nb', 'Battle Dress Uniform (Fatigues) - Shirt - Olive Green', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) shirt, 4 pockets. Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('battle-dress-uniform-fatigues-shirt-white-or-khaki-nb', 'Battle Dress Uniform (Fatigues) - Shirt - White or Khaki', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Battle Dress Uniform (Fatigues) shirt, 4 pockets. Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('military-field-jacket-nb', 'Military Field Jacket', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Includes adjustable collar and cuffs, epaulets, 4 large outer pockets with heavy brass zippers, hidden hood, waist cord and snap closures.', 'Nightbane RPG p.230'),
  ('reversible-flight-jacket-light-nb', 'Reversible Flight Jacket - Light', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Comes in navy blue, grey, green and brown.', 'Nightbane RPG p.230'),
  ('extreme-cold-weather-flight-jacket-nb', 'Extreme Cold Weather Flight Jacket', 'nightbane', 'gear', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Heavy, insulated. Comes in navy blue, grey, green, brown and white.', 'Nightbane RPG p.230'),
  ('battle-dress-utility-lightweight-nb', 'Battle Dress Utility - Lightweight', 'nightbane', 'gear', NULL, 65, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Shirt and pants in choice of arctic, desert, jungle or autumn forest camouflage. The shirt has two breast pockets, one pen pocket and one (left-side) interior pocket; the pants have hip, butt and thigh pockets. Lightweight is for desert and jungle.', 'Nightbane RPG p.230'),
  ('battle-dress-utility-medium-weight-nb', 'Battle Dress Utility - Medium Weight', 'nightbane', 'gear', NULL, 90, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The same Battle Dress Utility shirt and pants in medium weight, for forest and mountain; priced in the same entry on printed 230.', 'Nightbane RPG p.230'),
  ('battle-dress-utility-arctic-weight-nb', 'Battle Dress Utility - Arctic Weight', 'nightbane', 'gear', NULL, 365, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The same Battle Dress Utility shirt and pants in arctic weight (down lined); priced in the same entry on printed 230.', 'Nightbane RPG p.230'),
  ('battle-jacket-nb', 'Battle Jacket', 'nightbane', 'gear', NULL, 225, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Comes equipped with breast, hip and interior pockets on both sides. A hidden pocket on the inside of the back is also useful. Available in camouflage, khaki, green or black.', 'Nightbane RPG p.230'),
  ('arctic-parka-nb', 'Arctic Parka', 'nightbane', 'gear', NULL, 450, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'High quality down lining provides protection in sub-zero conditions. Same pocket arrangement as Battle Jacket. Available in green and white only.', 'Nightbane RPG p.230'),
  ('wool-sweaters-nb', 'Wool Sweaters', 'nightbane', 'gear', NULL, 150, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Finest British quality knit with leather reinforcements at shoulders, elbows and neck. Available in cream, green or black.', 'Nightbane RPG p.230'),
  ('ponchos-nb', 'Ponchos', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Waterproof nylon. Useful for rain protection, ground cover, emergency tent, etc. 5ft by 5ft square. Available in camouflage. The general purpose list on the same page prints a separate Rain Poncho at $30.00.', 'Nightbane RPG p.230'),
  ('camouflage-t-shirt-nb', 'Camouflage T-Shirt', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('khaki-bush-shorts-nb', 'Khaki Bush Shorts', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Combat/hunting clothing, printed 230.', 'Nightbane RPG p.230'),
  ('police-style-riot-helmet-nb', 'Police Style Riot Helmet', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'With ventilated transparent face shield.', 'Nightbane RPG p.230'),
  ('combat-helmet-nb', 'Combat Helmet', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Complete with liner and camouflage cover.', 'Nightbane RPG p.230'),
  ('safari-hat-nb', 'Safari Hat', 'nightbane', 'gear', NULL, 125, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A wide-brimmed hat perfect for shading the eyes in tropical sunlight and classy enough for an evening out on the town. Fasteners on each side for an easy ''Aussie style'' flip. Available in camouflage, cream, green or khaki.', 'Nightbane RPG p.230'),
  ('utility-cap-nb', 'Utility Cap', 'nightbane', 'gear', NULL, 14.5, '$14.50 - the only price on either page that is not a whole dollar', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'A classic ''marine cover.'' Available in choice of camouflage, green or khaki.', 'Nightbane RPG p.230'),
  ('beret-nb', 'Beret', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'The classic wool beret. Available in green, black, or jungle camouflage.', 'Nightbane RPG p.230'),
  ('bandanna-nb', 'Bandanna', 'nightbane', 'gear', NULL, 5, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'In choice of colors.', 'Nightbane RPG p.230'),
  ('head-net-nb', 'Head Net', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Covers hair and face, leaving only a slit for the eyes.', 'Nightbane RPG p.230'),
  ('camouflage-face-veil-nb', 'Camouflage Face Veil', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Hats and head coverings, printed 230.', 'Nightbane RPG p.230'),
  ('navy-style-face-mask-nb', 'Navy Style Face Mask', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Water and wind proof vinyl with soft wool lining; mouth tab with snap closure.', 'Nightbane RPG p.230'),
  ('dancer-s-leotards-nb', 'Dancer''s Leotards', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('speed-suit-nb', 'Speed Suit', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Jumpsuit style. Trim cut, polyester/cotton fabric with one breast pocket and two front pockets. Used by race car drivers and pit crews.', 'Nightbane RPG p.230'),
  ('shop-service-coat-nb', 'Shop Service Coat', 'nightbane', 'gear', NULL, 30, 'knee length, 4 pockets', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Knee length, 4 pockets. General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('turtleneck-shirt-nb', 'Turtleneck Shirt', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('thermal-parka-hooded-sweat-shirt-nb', 'Thermal Parka, Hooded Sweat Shirt', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('sweat-shirt-nb', 'Sweat Shirt', 'nightbane', 'gear', NULL, 16, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('flannel-shirt-nb', 'Flannel Shirt', 'nightbane', 'gear', NULL, 14, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('t-shirt-nb', 'T-Shirt', 'nightbane', 'gear', NULL, 6, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('dress-shirt-nb', 'Dress Shirt', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('work-pants-nb', 'Work Pants', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('denim-jeans-nb', 'Denim Jeans', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('coveralls-work-nb', 'Coveralls - Work', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('coveralls-insulated-nb', 'Coveralls - Insulated', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('work-apron-denim-3-pocket-nb', 'Work Apron - Denim, 3 pocket', 'nightbane', 'gear', NULL, 12, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('machinist-s-apron-6-pocket-nb', 'Machinist''s Apron - 6 pocket', 'nightbane', 'gear', NULL, 18, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('lab-coat-nb', 'Lab Coat', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('windbreaker-jacket-nb', 'Windbreaker Jacket', 'nightbane', 'gear', NULL, 18, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('light-lined-jacket-nb', 'Light Lined Jacket', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('winter-jacket-waist-length-nb', 'Winter Jacket - Waist Length', 'nightbane', 'gear', NULL, 55, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('winter-jacket-hip-length-nb', 'Winter Jacket - Hip Length', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('reversible-hunting-parka-nb', 'Reversible Hunting Parka', 'nightbane', 'gear', NULL, 70, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('insulated-survival-vest-6-pocket-nb', 'Insulated Survival Vest - 6 pocket', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('survival-coat-insulated-4-big-pockets-and-hood-nb', 'Survival Coat - Insulated - 4 big pockets and hood', 'nightbane', 'gear', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('wool-cap-nb', 'Wool Cap', 'nightbane', 'gear', NULL, 80, '$80.00 as printed, between a $100.00 survival coat and a $10.00 ski mask', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('winter-ski-mask-nb', 'Winter Ski Mask', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('arctic-trooper-hat-with-fur-earflaps-nb', 'Arctic Trooper Hat with Fur Earflaps', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('work-gloves-nb', 'Work Gloves', 'nightbane', 'gear', NULL, 4, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('leather-racing-gloves-nb', 'Leather Racing Gloves', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('dress-winter-gloves-nb', 'Dress Winter Gloves', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('heavy-winter-gloves-nb', 'Heavy Winter Gloves', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('wool-mittens-nb', 'Wool Mittens', 'nightbane', 'gear', NULL, 14, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('leather-chopper-mitts-nb', 'Leather Chopper Mitts', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('lectra-mitts-nb', 'Lectra-Mitts', 'nightbane', 'gear', NULL, 30, 'the book''s line reads `Lectra-Mitts - Warmest Hand Protection Possible`', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Warmest hand protection possible. General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('tennis-shoes-nb', 'Tennis Shoes', 'nightbane', 'gear', NULL, 16, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('running-shoes-nb', 'Running Shoes', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('work-shoes-nb', 'Work Shoes', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('dress-shoes-boots-nb', 'Dress Shoes/Boots', 'nightbane', 'gear', NULL, 80, '$80 and up - the book prints `$80+`', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('steel-toe-shoes-nb', 'Steel Toe Shoes', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('steel-toe-boots-nb', 'Steel Toe Boots', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('work-boots-nb', 'Work Boots', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('waterproof-hunter-s-boots-nb', 'Waterproof Hunter''s Boots', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('high-quality-hunter-woodsman-insulated-boot-nb', 'High Quality Hunter/Woodsman, insulated boot', 'nightbane', 'gear', NULL, 140, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('waterproof-rubber-boots-ankle-high-nb', 'Waterproof Rubber Boots - Ankle High', 'nightbane', 'gear', NULL, 20, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('waterproof-rubber-boots-hip-high-nb', 'Waterproof Rubber Boots - Hip High', 'nightbane', 'gear', NULL, 50, 'the book prints this one as `50.00` with NO dollar sign, on a continuation line under Ankle High', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('rain-poncho-nb', 'Rain Poncho', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230. The combat/hunting list on the same page prints a separate Ponchos entry at $35.00.', 'Nightbane RPG p.230'),
  ('raincoat-nb', 'Raincoat', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('rain-suit-coat-pants-nb', 'Rain Suit - Coat & Pants', 'nightbane', 'gear', NULL, 45, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('rain-hat-nb', 'Rain Hat', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('hard-hat-nb', 'Hard Hat', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('sport-caps-nb', 'Sport Caps', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('baseball-cap-nb', 'Baseball Cap', 'nightbane', 'gear', NULL, 8, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230');

INSERT INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, description, source_book)
VALUES
  ('hat-short-brim-nb', 'Hat - Short Brim', 'nightbane', 'gear', NULL, 40, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('hat-large-brim-nb', 'Hat - Large Brim', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('hat-leather-large-brim-nb', 'Hat - Leather, large brim', 'nightbane', 'gear', NULL, 50, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'General purpose clothes price list, printed 230.', 'Nightbane RPG p.230'),
  ('cape-short-nb', 'Cape - Short', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('cape-long-nb', 'Cape - Long', 'nightbane', 'gear', NULL, 150, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('cape-long-and-hooded-nb', 'Cape - Long and Hooded', 'nightbane', 'gear', NULL, 175, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('robe-light-nb', 'Robe - Light', 'nightbane', 'gear', NULL, 30, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('robe-heavy-nb', 'Robe - Heavy', 'nightbane', 'gear', NULL, 60, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('robe-hooded-nb', 'Robe - Hooded', 'nightbane', 'gear', NULL, 80, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('bathrobe-nb', 'Bathrobe', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-jacket-nb', 'Security Guard Uniform - Jacket', 'nightbane', 'gear', NULL, 35, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-shirt-nb', 'Security Guard Uniform - Shirt', 'nightbane', 'gear', NULL, 18, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-tie-nb', 'Security Guard Uniform - Tie', 'nightbane', 'gear', NULL, 4, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-trousers-nb', 'Security Guard Uniform - Trousers', 'nightbane', 'gear', NULL, 25, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-regulation-hat-nb', 'Security Guard Uniform - Regulation Hat', 'nightbane', 'gear', NULL, 15, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-trouser-belt-nb', 'Security Guard Uniform - Trouser Belt', 'nightbane', 'gear', NULL, 10, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-belt-and-holster-nb', 'Security Guard Uniform - Belt and Holster', 'nightbane', 'gear', NULL, 60, 'the book''s line reads `Traditional belt and holster with 28 bullet loops`', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231'),
  ('security-guard-uniform-badge-and-i-d-pocket-case-nb', 'Security Guard Uniform - Badge and I.D. Pocket Case', 'nightbane', 'gear', NULL, 18, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 'Printed 231, closing the clothing lists. The book''s note on this page: generally DOUBLE OR TRIPLE the price for fancy/dress articles, and multiply the price by 10 TIMES (or more, in some cases) for custom-made articles. The security guard uniform is usually navy blue or brown.', 'Nightbane RPG p.231');

-- Read the result back. This batch asserts its OWN rows and nothing else.
SELECT 'all 218 rows of this script are in, as nightbane' AS assertion, count(*) AS got, 218 AS want
  FROM gear WHERE system = 'nightbane' AND source_book LIKE 'Nightbane RPG p.%'
   AND slug LIKE '%-nb' AND (source_book GLOB 'Nightbane RPG p.22[89]*' OR source_book GLOB 'Nightbane RPG p.23[01]*');

SELECT 'every one has a description' AS assertion, count(*) AS got, 218 AS want
  FROM gear WHERE system = 'nightbane' AND length(description) > 0
   AND slug LIKE '%-nb' AND (source_book GLOB 'Nightbane RPG p.22[89]*' OR source_book GLOB 'Nightbane RPG p.23[01]*');

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('zzzzzzzzzzzzz-nb-gear-f-containers-equipment-clothing.sql');
