-- Rifts World Book 24: China 1, batch 1: the 24 demonic curses.
--
-- One-off data script, run once per environment. NOT a migration.
--
--   node scripts/d1-apply.mjs --local  apps/character-creator/db/~058-china-1-demonic-curses.sql
--   node scripts/d1-apply.mjs --remote apps/character-creator/db/~058-china-1-demonic-curses.sql
--
-- WHY THESE ARE SPELLS. The schema has no table for curses, and every ghost,
-- demon and Yama King in this book lists the curses it can lay by name. Nate
-- decided on 2026-10-01 (survey decision D1,
-- apps/character-creator/docs/surveys/china-1.md) that they are `spells` rows
-- in a tradition of their own, so the bestiary rows that follow can name rows
-- that exist.
--
-- THE AUTHORITY is the book's own list at the head of the chapter (printed 55,
-- cache p056): 24 names. The chapter (printed 55-60) carries 24 description
-- headings and they are the same 24. Read off the OCR cache (a scan, offset
-- +1, scripts/books.json).
--
-- NAMES. `Demonic Curse: <name>`, the book's name with its leading "Curse of
-- (the/a/an)" dropped, which is how the creature entries cite them ("Drought,
-- Forefather, Heritage"). The prefix is NOT `Curse: `: that prefix belongs to
-- general invocations (Curse: Phobia, Book of Magic) and these are not
-- learnable. Tradition `demonic-curse`; js/traditions.js title-cases an
-- unlisted slug to "Demonic Curse", so no label is added.
--
-- LEVEL 0 AND 0 P.P.E., BOTH ON PURPOSE. The book states no level, so level 0
-- (the precedent Wormwood's prayers and Africa's Bad Medicine set). It states
-- no per-curse cost either: casting any curse spends half the creature's total
-- P.P.E. (printed 54), which is in ppe_note on every row. source-coverage's
-- `spell stubs` line counts level 0 with 0 P.P.E., so these 24 raise it by 24;
-- like the 19 it already counted, each carries a ppe_note and is finished.
--
-- THE RULES COMMON TO ALL 24 (printed 54), stated once here and carried in
-- saving_throw, casting_time and ppe_note rather than in each description:
-- save on 16 or higher with bonuses to save vs magic at half; one curse per
-- victim, one casting a month; mortals and the mortal world only; Remove Curse
-- works at -25%.
--
-- DESCRIPTIONS ARE SUMMARIES written for this catalog, with every number the
-- book prints. Two OCR digit repairs, each the only reading the dice allow:
-- Hunger's percentile split printed as `0/-50%` and `5/-00%` is 01-50% and
-- 51-00%.
--
-- NOT MODELLED, kept as text: the Minor Disorder's six afflictions, Numbness's
-- three body parts and Headaches' three stages each carry their own penalties,
-- and the village-wide curses (Animal Disease, Drought, Pestilence, Plague,
-- Pox) scale by the casting creature's level.

INSERT INTO spells
  (name, level, ppe, ppe_note, source, source_book, system, range, duration, damage, saving_throw, area_of_effect, casting_time, description, tradition)
VALUES
  ('Demonic Curse: Ancestors', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.55', 'rifts', NULL, '4D6 weeks; each visitation lasts 1D6x10 minutes', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'The victim is haunted by the ghosts of 1D4 disapproving ancestors, usually of an alignment opposite to his own. They appear when he blunders and without warning, to criticise, nag, offer advice that may be good or bad, play poltergeist pranks and break his sleep. Visits run from once or twice a day to a dozen, more often for a victim who argues or who welcomes them. While a ghost is present: -2 on initiative, -1 attack per melee round and -10% on skill performance.', 'demonic-curse'),
  ('Demonic Curse: Animal Disease', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.55', 'rifts', NULL, '3D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One farm or area of land, up to one square mile (1.6 km)', 'Once per month; one curse per victim', 'One type of animal on the victim''s land (all fowl, all horses, all cattle, dogs, pigs and so on) sickens and wastes away. 1D6x10+30% of them die within 1D6+20 days and their flesh is unfit to eat. The sick animals have Spd, P.S. and P.E. reduced by 75% and cannot work. A human who eats one suffers the Curse of Stomach Sickness for 1D4+2 days. Losing the dogs or cats may bring predators or vermin. If the victim owns no land or animals the curse falls on a relative''s or friend''s property, or on the place he was born, lives or buys from. Special way to lift it: rural people know that killing the cursed person as a sacrifice ends the sickness, and the animals recover in 2D4 days.', 'demonic-curse'),
  ('Demonic Curse: Bad Luck/Misfortune', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.55', 'rifts', NULL, '4D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'Constant misfortune: gear breaks, animals go lame, money is lost, he is cheated, loses at gambling, and any injury or sickness leads to complications. In a group he is the one singled out for a brawl, theft, interrogation or worse. The victim has NO bonuses to save against anything (unmodified rolls only), and his bonuses to parry, dodge and pull punch are halved.', 'demonic-curse'),
  ('Demonic Curse: Barrenness', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.55-56', 'rifts', NULL, '5D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal, or all the animals one person owns or part-owns', 'Once per month; one curse per victim', 'Cast on animals, everything the victim owns becomes infertile for the duration: no eggs, no milk, no births, and young due within 1D4 weeks are stillborn. Cast on a person, a man becomes impotent and infertile; a woman cannot conceive, a pregnancy under 24 weeks miscarries within 1D6 days, and a later one ends in a stillbirth after 2D6+20 days of pain. Penalties: M.A. and M.E. reduced by half, P.E. and P.B. by 10% (adjust attribute bonuses to match), and -10% on skill performance. The book suggests it as a plot device for an NPC who hires the player characters.', 'demonic-curse'),
  ('Demonic Curse: Delirium', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.56', 'rifts', NULL, '1D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'A fever leaves the victim delirious and confused. All combat bonuses are reduced to zero, attacks per melee and Spd are halved, and every skill is performed at only 30%. He does not always know the people around him, relives the past or imagines another time and place, takes the one who cursed him for his best friend, mistakes ghosts for the living and is often oblivious to danger.', 'demonic-curse'),
  ('Demonic Curse: Drought', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.56', 'rifts', NULL, '4D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'The victim''s land and crops', 'Once per month; one curse per victim', 'Rain skips the victim''s land. 2D4x10% of the crops, fruit and vegetation wither, starting with the most valuable; wells and streams run dry, and brush fires and dust storms may follow. Even four weeks ruins a season''s crop (stunted, poor, half the usual amount). If he owns no land the curse falls on his family, home town or current home. No penalty to the victim himself, but everyone knows who brought it. Special way to lift it: killing the cursed person as a sacrifice ends the drought and brings rain.', 'demonic-curse'),
  ('Demonic Curse: Feebleness', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.56', 'rifts', NULL, '2D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'The victim is weak, tires twice as fast and is spent after modest exertion. P.S., P.P., P.E. and Spd are reduced by half (attribute bonuses to match), S.D.C. by half, and attacks per melee round are -1. Skills take twice as long and he must rest often.', 'demonic-curse'),
  ('Demonic Curse: Fever', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.56', 'rifts', NULL, '2D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'The victim falls ill with fever: -3 on initiative, -2 to strike, parry, dodge and disarm, -20% on skill performance, weak, sluggish and wanting sleep. Asleep, he hears nothing and only shaking wakes him. He must drink to avoid dehydration; fever with dehydration doubles the penalties and halves P.P.E., I.S.P., P.S. and Spd.', 'demonic-curse'),
  ('Demonic Curse: Fleas', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.56', 'rifts', NULL, '4D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'The victim is infested with fleas, lice or other biting insects that no bath, shaving or medicine removes. M.A. is reduced by half and P.B. by 10%; -1 on initiative, -1 to strike, parry and dodge, and -5% on skill performance.', 'demonic-curse'),
  ('Demonic Curse: Forefather', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.56-57', 'rifts', NULL, '6D6 weeks; the damage to his reputation may outlast it by years', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'The victim is exposed as the descendant of someone notorious and is made to answer for that forefather''s crime or shame. His own reputation is tarnished, old feuds revive, he may be shunned, and people seek revenge or demand he right the wrong: a quest, a favour or a series of tests. Righting it could instead make his name. No mechanical penalty; he may have to hide who he is.', 'demonic-curse'),
  ('Demonic Curse: Headaches', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.57', 'rifts', NULL, '3D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'Daily, pounding migraines that worsen the longer the curse runs. First week: -1 to strike, parry and dodge, -5% on all skills. Second to fourth week: all combat bonuses (initiative included) reduced by half, -1 attack per melee, S.D.C. reduced by half, -15% on all skills. Fifth week onward: combat bonuses reduced to zero, saving throws by half, only two attacks per melee, S.D.C. zero, Hit Points reduced by 1D4x10%, skills take three times as long at -40%, he always acts last and can cast only one spell per melee round. The list at the head of the chapter calls this one debilitating.', 'demonic-curse'),
  ('Demonic Curse: Heritage (Children)', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.57', 'rifts', NULL, 'Until the curse is lifted or the victim makes good with the one who cursed him', NULL, '16 or higher; bonuses to save vs magic count at half', 'One of the victim''s children, or another younger relative he loves', 'Once per month; one curse per victim', 'The curse falls on one of the victim''s children, usually the first born or the youngest, or failing that on a younger sibling, cousin, nephew, grandchild or stepchild. Every aura reading and form of fortune telling shows the child doomed to tragedy and an early death, and those close to the child suffer too. The child bears the Curse of Bad Luck/Misfortune at half its usual penalties. Killing the creature responsible usually makes the curse permanent unless the cursed youngster is the one who confronts it, by killing it or striking a deal.', 'demonic-curse'),
  ('Demonic Curse: Hunger', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.57', 'rifts', NULL, '4D6 weeks; 1D6x10 weeks when cursed by a Preta', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'The belly bloats as if starving, all food tastes like paste and nothing satisfies. Constant stomach ache and weakness: P.E. and Spd reduced by 20%, S.D.C. by half, and -1 attack per melee round. Roll percentile: 01-50% the victim gains 2D4x10 pounds (9 to 18 kg), P.B. reduced by 10%; 51-00% he loses 2D4x10 pounds, P.B. and P.S. reduced by 20%.', 'demonic-curse'),
  ('Demonic Curse: Interesting Life', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.57-58', 'rifts', NULL, '6D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'People good and bad notice and target the victim. A favour won brings an enemy with it, thieves and con artists pick him, animals balk or bite, creditors come for a relative''s debts. A minor ailment turns into the worse one, and a one-in-a-hundred mischance happens to him. Any sickness, magic or poison runs its full duration but at half the usual penalties. Penalties are as the situation dictates.', 'demonic-curse'),
  ('Demonic Curse: Lameness', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.58', 'rifts', NULL, '5D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal, or his riding animal', 'Once per month; one curse per victim', 'Cast on a riding animal, it goes lame within 1D6 minutes, as does any replacement and any animal pulling a wagon he rides in. The victim himself has a stabbing pain in his feet and legs whenever he puts weight on them: Spd and S.D.C. reduced by half, Hit Points by 10%, -2 to strike and pull punch, -3 to parry and disarm, -6 to dodge, entangle and roll with impact. P.S. and damage bonuses are also halved.', 'demonic-curse'),
  ('Demonic Curse: Minor Disorder', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.58', 'rifts', NULL, '2D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal at a time', 'Once per month; one curse per victim', 'Meant to humiliate. One affliction: Headaches (mild, 1D4x10 minutes each, -5% on skills while one is on). Hiccups or speech impediment (one spell per melee round, and ridicule). Indigestion (flatulence after eating or drinking anything but water; -1 to strike, parry and dodge; trackers by scent are +20%; Prowl -10%, or -25% within an hour of eating). Muscle Stiffness (-1 on initiative, -1 to strike, parry and dodge, Spd reduced by 10%). Nausea (speeds over 40 mph/64 km, sudden motion or disgusting sights force him to do nothing for one melee round or vomit, losing initiative and all actions that round and -2 to parry, dodge and roll with impact). Sneezing or coughing (fits of 2D6 minutes: -1 to initiative, parry and dodge, -20 to prowl or hide).', 'demonic-curse'),
  ('Demonic Curse: Numbness', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.58', 'rifts', NULL, '3D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'One part of the body goes numb for the duration. Fingers and arms: -30% on skills needing the hands, cannot grip (a rival P.S. of 9 or more pulls an item away), -1 to strike, -3 to parry and disarm, cannot pull punches. Feet and legs: speed reduced by 40%, no leaping, Acrobatics or Gymnastics, other leg skills take twice as long at -40%, -3 to dodge and roll with impact. Face and mouth: -2 on P.B., M.A. reduced by 2, speech and vocal skills -30%, one spell per melee round.', 'demonic-curse'),
  ('Demonic Curse: Pestilence/Locusts', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.58-59', 'rifts', NULL, '1D4 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One prepared meal, or 100 acres of the victim''s land per level of the creature', 'Once per month; one curse per victim', 'Cast on prepared food, the whole meal rots and fills with maggots. Cast on a person, locusts, beetles and other insects infest land he owns or is tied to and devour 6D6 acres of crops, fruit and vegetation every day, the most valuable first. Even one week ruins a season. If he owns no land it falls on his family''s holdings, then his home town or current home. No penalty to the victim himself, but everyone knows who brought it. Special way to lift it: the cursed person must be eaten alive or killed by a predatory animal as a sacrifice, which stops the swarm and spares what remains.', 'demonic-curse'),
  ('Demonic Curse: Plague', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.59', 'rifts', NULL, '1D4+1 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal, or a community: 2D6 people per day for each level of the creature', 'Once per month; one curse per victim', 'Typhus or bubonic plague: cough, high fever and red blotches. Laid on one person, more often on someone he loves, or on his birthplace or home, where a new 2D6 people fall ill each day for as many days as the creature has levels. For every day of illness: -1 on initiative, -1 to strike, parry, dodge and disarm, -5% on skills, -1 attack and -2 Spd. After seven days the sick collapse; every day after that there is a 01-20% chance of coma, and a save vs coma and death (+20% with medical, psionic or magical care). About 50-60% of the afflicted die. Reserved for the most powerful or vile demons and ghosts. Special way to lift it: killing the cursed person as a sacrifice stops the disease, and the sick recover within 48 hours.', 'demonic-curse'),
  ('Demonic Curse: Pox', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.59', 'rifts', NULL, '1D4+1 weeks', '1D6 direct to Hit Points per day for 1D6+2 days, from the eighth day', '16 or higher; bonuses to save vs magic count at half', 'One mortal, or the nearest community: 2D6 adults for each level of the creature', 'Once per month; one curse per victim', 'An itchy red rash with low fever, tiredness and no appetite, usually laid on the nearest community even if the victim is only passing through. Adults: -1 on initiative, -2 to strike, parry and dodge, -10% on skills, and attacks per melee reduced by half. After the first seven days the sick take 1D6 damage direct to Hit Points each day for 1D6+2 days; by day 15 the damage stops but the penalties last to the end. Seldom fatal to adults, but for every adult 1D6 children also sicken (a child under 12 has 2D6+4 Hit Points, a teen 2D6+10). Lost Hit Points return only by psionic or magical healing. Killing the cursed person does NOT lift this one.', 'demonic-curse'),
  ('Demonic Curse: Rags', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.59-60', 'rifts', NULL, '4D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'Any clothing or armor the victim wears or carries tears and breaks, turning to rags within a week of being acquired. S.D.C. armor and clothing lose 10 S.D.C. per day; magical and M.D.C. armor lose 10% of their M.D.C. per week, and are useless at zero. His gear always looks dirty and shabby: M.A. and P.B. reduced by 20%.', 'demonic-curse'),
  ('Demonic Curse: Stomach Sickness', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.60', 'rifts', NULL, '3D6 weeks; each episode lasts 4D6 minutes', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'Waves of nausea, cramping and vertigo under stress or exertion, after eating and from not eating. Speed reduced by half, -1 attack per melee round, and no initiative (he acts last). Speeds over 40 mph (64 km), sudden motion or disgusting sights force him to do nothing for one melee round or vomit, losing all actions that round at -4 to parry and dodge. A further -2 to strike, parry and dodge when dizzy.', 'demonic-curse'),
  ('Demonic Curse: Wasting', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.60', 'rifts', NULL, '3D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'Within a week the victim turns pale or grey with dark-ringed, yellowed eyes, loses 10 pounds (4.5 kg) and looks like a vampire or a walking corpse. M.A. and P.B. reduced by half. Each week of the curse his normal S.D.C. is reduced by 10% and he loses one Hit Point, never falling below 10 Hit Points; neither recovers until the curse ends.', 'demonic-curse'),
  ('Demonic Curse: Wicked Haunting', 0, 0, 'No fixed cost: casting any curse spends half the creature''s total P.P.E.', 'import', 'Rifts World Book 24: China 1 p.60', 'rifts', NULL, '6D6 weeks', NULL, '16 or higher; bonuses to save vs magic count at half', 'One mortal', 'Once per month; one curse per victim', 'A Preta, a Fox Spirit or a Haunting Entity follows the victim, striking at him and those around him at random times each day. It breaks his sleep (four hours a night at best), hides his belongings, spoils his food, appears at the worst moments, sets animals howling, mocks him and urges him to evil, whatever his alignment. Distracted and short of sleep: -1 to strike, parry and dodge, and -5% on skill performance.', 'demonic-curse');

SELECT 'the 24 demonic curses exist' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE tradition = 'demonic-curse';

SELECT 'every one is prefixed, level 0, costed by note and cites the book' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE tradition = 'demonic-curse' AND name LIKE 'Demonic Curse: %'
   AND level = 0 AND ppe = 0 AND ppe_note IS NOT NULL AND system = 'rifts'
   AND source_book LIKE 'Rifts World Book 24: China 1 p.%';

SELECT 'every one has a duration and a description' AS assertion, count(*) AS got, 24 AS want
  FROM spells WHERE tradition = 'demonic-curse'
   AND duration IS NOT NULL AND length(description) > 100;

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('~058-china-1-demonic-curses.sql');
