-- Nine Iron Juggernauts of Tolkeen and seven cyborg bodies, as vessel rows.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
-- Rifts Book of Magic, printed 343-347: the Blazing, Earthwake, Fury,
-- Iron-Dragonfly, Sea Viper, Thundering, Warhawk, Wing Blade and Millipede
-- Iron Juggernauts. The book's first full inventory (2026-10-03, in its
-- survey) found the catalog held none of them. They are `robot`, as the seven
-- Federation of Magic automatons the same chapter prints are.
-- Rifts World Book 8: Japan, printed 101-109: the four Dragon 'Borg bodies.
-- Rifts World Book 25: China 2, printed 128-132: the three Geo-Borg bodies.
-- The seven classes for those bodies exist and carry M.D.C. by location and
-- built-in weapons as prose; these are the bodies as `borg` rows, the shape
-- Warlords of Russia gave its cyborgs (PR #1617) the day after Japan shipped.
-- The classes are NOT rewired here: each still describes its body in prose.
--
-- EVERY NUMBER WAS READ OFF A RENDER and checked against a render again by
-- book-reconcile: about 700 figures, none wrong. Every slug was queried
-- against production vehicles, gear and imported_classes first.
--
-- CONVENTIONS (as the Triax 2 and Warlords of Russia vessels):
--   cost is the lowest printed price, with the wording in cost_note; the
--     juggernauts print no price and are NULL.
--   Seven juggernauts print a Main Body figure and no location list, size or
--     weight; only the Wing Blade and the Millipede print locations.
--   A body's slug leads with its model number, so it cannot be mistaken for
--     its class id.
--   A dragon 'borg's tail prints a rate (50 M.D.C. per 6 ft), not a total: mdc
--     is NULL and the rate is in mdc_note.
--   Numbered items that are not weapons (training, feature lists, handheld
--     catalog weapons) are left out, so a 'borg's ordinals have gaps.
--   A book slip is stored as printed and named in the row: "P.P. 23" in two
--     hand to hand blocks whose bodies print P.P. 22, the Wing Blade tail's
--     (1.2 m), and the Millipede's page reference.

INSERT OR IGNORE INTO vehicles (slug, name, system, vehicle_class, crew, passengers, speed_ground, speed_air, speed_water, dimensions, weight_tons, mdc_main_body, is_mega_damage, ar, cost, cost_note, description, source_book) VALUES
('iron-juggernaut-blazing', 'Blazing Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 50 mph (80 km); double on a ley line. Leaping: 20 feet (6.1 m) high and 40 feet (12 m) long. Maximum range: unlimited.', NULL, NULL, NULL, NULL, 910, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas.', 'A fire-wreathed Tolkeen war machine classed as an Iron Juggernaut TW Combat Robot, first described in Coalition Wars One p.81. It has supernatural P.S. 29, P.P. 22 and an I.Q. of 7-14, takes six physical attacks or two spells a melee round, and is +3 on initiative, +6 to strike with punches and kicks, +4 to strike at range, +3 to parry and dodge, +4 to pull punch, +1 to roll, +10 vs Horror Factor and +6 vs mind control. It speaks only in crackling 3-6 word phrases, sees clearly for a mile (1.6 km) with 180 degree peripheral vision and 2,000 foot (610 m) nightvision, sees the invisible, understands every language and never tires, eats or breathes.', 'Rifts Book of Magic p.343-344'),
('iron-juggernaut-earthwake', 'Earthwake Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 60 mph (96 km); double on a ley line. Leaping: 15 feet (4.6 m) high and 30 feet (9.1 m) long; double that from a running start, and double it again on a ley line. Maximum range: unlimited.', NULL, NULL, NULL, NULL, 1187, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas.', 'An amphibious earth-and-water Iron Juggernaut of Tolkeen, classed as a TW Combat Robot and first described in Coalition Wars Three p.74. It has supernatural P.S. 42, P.P. 22 and an I.Q. of 6-14 and takes nine physical attacks (seven in the water) or two spells a melee round; underwater it is +1 on initiative, +5 to strike, +3 to parry, +2 to automatic dodge, +4 to pull punch and +2 to roll, all doubled on dry land where the automatic dodge becomes an ordinary +4 dodge, with +10 vs Horror Factor and +8 vs mind control. It sees two miles (3.2 km) and through dark, murky water, has 180 degree peripheral vision and 3,000 foot (914 m) nightvision, sees the invisible, understands all languages, navigates on land at 98%, senses depth and water temperature and finds water within 50 miles (80 km) at 88%.', 'Rifts Book of Magic p.344'),
('iron-juggernaut-fury', 'Fury Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 50 mph (80 km); double on a ley line. It is a tracked all-terrain vehicle and can climb inclines as steep as 90 degrees. Maximum range: unlimited.', NULL, NULL, NULL, NULL, 1340, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas. Printed under the heading Black Market Cost.', 'A tracked earth-and-air Iron Juggernaut of Tolkeen, classed as a TW Combat Robot and first described in Coalition Wars One p.86. It has supernatural P.S. 40, P.P. 24 and an I.Q. of 8-14, takes six physical attacks or two spells a melee round, and is +4 on initiative, +7 to strike with punches and kicks, +9 with its forearm blades, +3 with its ion cannons, +9 to parry, +2 to dodge, +8 to pull punch, +10 vs Horror Factor and +8 vs mind control. It rumbles out 3-6 word phrases, sees two miles (3.2 km) with 180 degree peripheral vision and 6,000 foot (1,829 m) nightvision, sees the invisible, understands all languages and needs no air, food, drink or rest.', 'Rifts Book of Magic p.344'),
('iron-juggernaut-iron-dragonfly', 'Iron-Dragonfly Heavy Air Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 30 mph (48 km), double on a ley line. Leaping: 10 feet (3 m) high and 15 feet (4.6 m) long. Maximum range: unlimited.', 'Flying: 600 mph (960 km); double on a ley line. Max. altitude is 20,000 feet (6,096 m).', NULL, NULL, NULL, 1210, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas.', 'Tolkeen''s heavy flying Iron Juggernaut, classed as a TW Combat Robot and first described in Coalition Wars Three p.68; it outflies SAMAS, most flying power armor and many aircraft. It has supernatural P.S. 35, P.P. 20 and an I.Q. of 7-14, takes six physical attacks or two spells a melee round, and is +2 on initiative, +7 to strike with punches and kicks (+3 with energy blasts), +10 to parry, +3 to dodge (+5 in flight), +5 to pull punch, +1 to roll, +9 vs Horror Factor and +6 vs mind control. Its voice is a roaring wind limited to 1-6 word phrases; it sees three miles (4.8 km) and through smoke, has 180 degree peripheral vision and 6,000 foot (1,829 m) nightvision, sees the invisible and understands all languages.', 'Rifts Book of Magic p.345'),
('iron-juggernaut-sea-viper', 'Sea Viper Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 35 mph (56 km). On dry land a leap is 10 feet (3 m) high or 20 feet (6.1 m) lengthwise. Maximum range: unlimited.', NULL, 'Underwater: 100 mph (160 km or 86 knots); double that on a ley line. Can dive at double speed for up to 1,000 feet (305 m). Maximum depth tolerance is three miles (4.8 km). Can remain underwater indefinitely. Leaping: 20 feet (6.1 m) high and 60 feet (18.3 m) long; double if swimming at top speed and double again when swimming along a ley line.', NULL, NULL, 690, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas.', 'Tolkeen''s underwater Iron Juggernaut, classed as a TW Combat Robot and first described in Coalition Wars Three p.70. It has supernatural P.S. 24, P.P. 22 and an I.Q. of 7-14 and takes eight physical attacks (six out of the water) or two spells a melee round; in the water it is +4 on initiative, +10 to strike, +8 to parry, +6 to automatic dodge, +6 to pull punch, +4 to disarm, +2 to roll, +10 vs Horror Factor and +6 vs mind control, and every bonus is halved on land. It speaks in deep phrases of up to eight words, sees two miles (3.2 km) and through smoke with 280 degree peripheral vision and 6,000 foot (1,829 m) nightvision, sees the invisible, understands all languages, senses water depth and magnetic north, navigates underwater at 98% and has sonic echo-location.', 'Rifts Book of Magic p.345'),
('iron-juggernaut-thundering', 'Thundering Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 100 mph (160 km); double on a ley line. Leaping: 60 feet (18.3 m) high and 120 feet (36.6 m) long; double when on a ley line. Maximum range: unlimited.', 'Flying: 60 mph (96 km) only on a ley line. Triple speed when riding during a Ley Line Storm.', NULL, NULL, NULL, 1130, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas.', 'A fast storm-and-air Iron Juggernaut of Tolkeen, classed as a TW Combat Robot and first described in Coalition Wars One p.83. It has supernatural P.S. 34, P.P. 26 and an I.Q. of 7-14, takes nine physical attacks or three spells a melee round, and is +6 on initiative, +9 to strike with punches and kicks, +11 with its forearm blades, +3 with energy weapons, +7 to parry, +5 to dodge, +6 to pull punch, +2 to roll, +10 vs Horror Factor and +6 vs mind control. It sees two miles (3.2 km) and through smoke, has 180 degree peripheral vision and 6,000 foot (1,829 m) nightvision, sees the invisible, understands all languages and never breathes, eats, drinks or tires.', 'Rifts Book of Magic p.345-346'),
('iron-juggernaut-warhawk', 'Warhawk Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 40 mph (64 km); double on a ley line. Leaping: 20 feet (6 m) high and 40 feet (12 m) across. Maximum range: unlimited.', 'Flying: 350 mph (560 km); double on a ley line. Max altitude is 15,000 feet (4,572 m).', NULL, NULL, NULL, 770, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being made of iron and elemental fury. Not available for sale, although the Splugorth would love to get a few for their gladiatorial arenas.', 'A silent-flying fire-and-air Iron Juggernaut of Tolkeen, classed as a TW Combat Robot and first described in Coalition Wars Two p.61; it outperforms SAMAS, most power armor and some aircraft and prowls at 65%. It has supernatural P.S. 27, P.P. 23 and an I.Q. of 7-14, takes eight physical attacks or two spells a melee round, and is +3 on initiative, +9 to strike with punches and kicks, +4 with energy blasts, +7 to parry, +5 to dodge, +7 to automatic dodge while airborne, +6 to pull punch, +3 to roll, +9 vs Horror Factor and +6 vs mind control. It whispers hoarsely in phrases of under eight words, sees three miles (4.8 km) with 180 degree peripheral vision and 2,000 foot (610 m) nightvision, sees the invisible and understands all languages.', 'Rifts Book of Magic p.346'),
('iron-juggernaut-wing-blade', 'Wing Blade Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Crawling: 30 mph (48 km; double on a ley line). Maximum range: unlimited.', 'Flying: 300 mph (480 km; double along ley lines). Altitude is 32,000 feet.', NULL, NULL, NULL, 1480, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being. No sale or availability line is printed.', 'A winged, many-legged ice-and-water Iron Juggernaut of Tolkeen that fights entirely with its blades, classed as a TW Combat Robot and first described in Coalition Wars 6: Final Siege p.59. It has supernatural P.S. 40, P.P. 26 and an I.Q. of 7-14, takes ten physical attacks or two spells a melee round, and is +6 on initiative, +10 to strike, +7 to parry, +5 to dodge, +6 to pull punch, +2 to roll, +10 vs Horror Factor and +6 vs mind control. It hisses 3-6 word phrases like escaping steam, has hawk-like sight to two miles (3.2 km), 180 degree peripheral vision and 6,000 foot (1829 m) nightvision, sees the invisible and understands all languages.', 'Rifts Book of Magic p.346-347'),
('iron-juggernaut-millipede', 'Millipede Iron Juggernaut', 'rifts', 'robot', 'Uncertain. Intelligence suggests one human or D-Bee and one or two Elementals or primordial elemental force.', NULL, 'Running: 100 mph (160 km; double on a ley line). Leaping: Not possible. Maximum range: unlimited.', 'Flying: Not possible.', 'Full underwater capabilities; no speed is printed.', '34 feet (10.4 m) tall, 32 feet (9.75 m) wide, and 90 feet (27.4 m) long.', NULL, 1880, 1, NULL, NULL, 'Presumably millions of credits, but it acts and thinks like a living being, so it is less a possession or machine and more of a supernatural being. No sale or availability line is printed.', 'The largest Iron Juggernaut in this book, a 90 foot, 38-legged earth machine that was massive and rare even in Tolkeen, classed as a TW Combat Robot and credited to Coalition Wars 6: Final Siege (the page reference is printed as p. 629). It has supernatural P.S. 40, P.P. 26 and an I.Q. of 7-14, takes twelve attacks a melee round, and is +5 on initiative, +9 to strike with punches, +5 with energy weapons, +4 to parry, +1 to dodge, +4 to pull punch, +10 vs Horror Factor and +5 vs mind control. It hisses 3-6 word phrases like steam, has hawk-like sight to two miles (3.2 km), 180 degree peripheral vision and 6,000 foot (1829 m) nightvision, sees the invisible and understands all languages.', 'Rifts Book of Magic p.347'),
('at-c8000-wing-blade-cyborg', 'AT-C8000 Wing Blade Dragon ''Borg', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 120 mph (192 km). Leaping: 25 feet (7.6 m) high or lengthwise; a running leap adds 1D4x10 additional yards/meters.', 'Flying: Via jet pack only. The wings give +10% to the jet pack piloting skill; with one or both wings destroyed the ''borg can still fly on the detachable jet pack at -20% on piloting skill. No flying speed is printed.', NULL, 'Height: the bulk of the body stands five feet (1.5 m) tall; with wings folded and neck and head hung low, 7 feet (2.1 m) (5 feet/1.5 m when crouched); wings extended add 12 feet (3.6 m). Width: 2 1/2 feet (0.75 m) for the body itself, 3 1/2 feet (1 m) with the wings folded. Length: the neck adds six feet (1.8 m) and the tail another 12 feet (3.6 m), for a total length of 23 feet.', '1000 lbs (450 kg)', 270, 1, NULL, 6000000, 'Six million credits with all standard features and weapons. Poor availability; outside of the Republic only Ichto makes them, and at 10% more money. Armatech makes the dragon ''borgs exclusively for the military and police of the Republic of Japan; they are not available to the public.', 'The Republic of Japan''s espionage and light assault dragon body, nicknamed the Snoop: a slender, four-armed full conversion frame with folding bat wings, a long snaking neck for peering around corners and a bladed prehensile tail. It is equal to P.S. 24, P.P. 22 and Spd 176, runs on a nuclear supply with an average life of 20 years, and carries six video cameras in its neck and knees. This row is the body alone; the pilot is the class dragon-borg-wing-blade, which also lists the standard bionic features.', 'Rifts World Book 8: Japan p.101-102'),
('at-c9000-tsunami-cyborg', 'AT-C9000 Tsunami Dragon ''Borg', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 120 mph (192 km). Leaping: 25 feet (7.6 m) high or lengthwise; a running leap adds 1D4x10 additional yards/meters.', 'Flying: Via jet pack only. 100 mph (160 kph) maximum speed. Range is limited to twelve hours at maximum speed before the jet pack needs to cool down; indefinite with rest stops and low speed (80 mph/108 kph or less, as printed). The wings give +10% to the jet pack piloting skill; with one or both wings destroyed the ''borg can still fly at -20% on piloting skill.', NULL, 'Height: 10 feet (3 m) when standing up straight (head to toes); the usual stooped posture reduces this to 7-8 feet (2.1 to 2.4 m). Width: 2 1/2 feet (0.75 m) for the body itself, 3 1/2 feet (1 m) with the wings folded. Length: the tail adds 6 feet (1.8 m), for a total length of 16 feet.', '1200 lbs (540 kg)', 320, 1, NULL, 8000000, 'Eight million credits with all standard features and weapons. Poor availability; outside of the Republic only Ichto makes them, and at 10% more money. Armatech makes the dragon ''borgs exclusively for the military and police of the Republic of Japan; they are not available to the public.', 'The second largest of the Republic of Japan''s dragon bodies, a heavy assault full conversion frame for army and police work with folding wings, a striking tail and a built-in jet pack. Its right arm ends in a mini-gun and vibro-axe instead of a hand, it is equal to P.S. 26, P.P. 23 and Spd 176, and its nuclear supply averages a 20 year life. This row is the body alone; the pilot is the class dragon-borg-tsunami, which also lists the standard bionic features and the insanity rolls. Printed 103 is a full-page illustration.', 'Rifts World Book 8: Japan p.102-105'),
('at-c10000-imperial-dragon-cyborg', 'AT-C10000 Imperial Dragon Combat ''Borg', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 120 mph (192 km) on four legs; drops to 20 mph (32 kph) on two legs. Leaping: the snake body springs 30 feet (9 m) high or lengthwise; a running leap adds 1D4x10 additional yards/meters.', 'Flying: Not possible.', NULL, 'Height: 5 feet (1.5 m) while on all fours; rearing up on its hind legs it can stand 9 feet (2.7 m) tall. Width: 2 1/2 feet (0.75 m) for the body itself. Length: 24 feet (7.2 m) from head to tail.', '1500 lbs (675 kg)', 350, 1, NULL, 10000000, 'Ten million credits with all standard features and weapons. Poor availability; outside of the Republic only Ichto makes them, and at 10% more money. Armatech makes the dragon ''borgs exclusively for the military and police of the Republic of Japan; they are not available to the public.', 'A four-legged, serpentine heavy assault body that is a true dragon in shape rather than a humanoid, armed almost like a tank and fielded mostly by the Army of the New Republic. Its low profile and twisting frame suit guerrilla fighting on slopes no biped can climb; it is equal to P.S. 30, P.P. 22 and Spd 176 on a nuclear supply averaging 20 years. This row is the body alone; the pilot is the class dragon-borg-imperial-combat, which also lists the standard bionic features and the insanity rolls.', 'Rifts World Book 8: Japan p.105-107'),
('at-c12000-flame-cloud-cyborg', 'AT-C12000 Flame Cloud Dragon Attack ''Borg', 'rifts', 'borg', 'One human volunteer.', NULL, 'Running: 120 mph (192 km) on four legs; drops to 20 mph (32 kph) on two legs. Leaping: the snake body springs 30 feet (9 m) high or lengthwise; a running leap adds 1D4x10 additional yards/meters.', 'Flying: 500 mph (800 kph) maximum. At maximum speed (300-500 mph/480-800 kph) it cannot maneuver and flies in a straight line only: hitting it requires a called shot at -2, but it cannot parry or dodge. Cruising speed is 200 mph (320 kph). Range: maximum speeds for 8 hours before needing to cool off, or 24 hours at cruising speeds; indefinitely at cruising speeds with frequent rest stops. Destroying one jet thruster reduces maximum speed by 70% and the pilot is -25% to all rolls; destroying both grounds it, and if in the air it crashes.', NULL, 'Height: 5 feet (1.5 m) while on all fours; rearing up on its hind legs it can stand 9 feet (2.7 m) tall. Width: 2 1/2 feet (0.75 m) for the body itself; the jet thrusters add an additional 5 feet (1.5 m) to the sides. Length: 24 feet (7.2 m) from head to tail.', '1500 lbs (675 kg)', 320, 1, NULL, 12000000, 'Twelve million credits with all standard features and weapons. Poor availability; outside of the Republic only Ichto makes them, and at 10% more money. Armatech makes the dragon ''borgs exclusively for the military and police of the Republic of Japan; they are not available to the public.', 'The wingless flying version of the Imperial, a serpentine heavy air assault body carried by two side-mounted jet thrusters to near-supersonic speed and named for its diving plasma-breath strafing run. It is quick but clumsy until it slows to 60-100 mph (96-160 kph), is equal to P.S. 24, P.P. 22 and Spd 176, and runs on a nuclear supply averaging 20 years. This row is the body alone; the pilot is the class dragon-borg-flame-cloud, which also lists the standard bionic features and the insanity rolls.', 'Rifts World Book 8: Japan p.107-109'),
('db-800-demon-eater-cyborg', 'Demon-Eater Cyborg (DB-800)', 'rifts', 'borg', NULL, NULL, 'Running: 60 (96 km) in heavy armor, printed without a unit; in light or no armor speed is 100 mph (160 km). Leaping: up to 50 feet (15.2 m) up or across, double the distance with a running start at full speed. Wall-crawling: clings to and moves along walls and ceilings at half its maximum running speed.', 'Flying: Via jet pack only.', NULL, 'Height: 12 feet (3.7 m). Width at Shoulders: 4 feet (1.2 m).', 'One ton', 220, 1, NULL, 12000000, '12 million credits.', 'The Geofront''s heavy full conversion body, a twelve foot, twin-tailed machine styled as a demon so that it can stalk, ambush and fight real ones tooth and claw. It has Bionic P.S. 35, P.P. 24 and Speed 98, runs on nuclear power, and climbs sheer walls and ceilings on electro-magnets and climbing fibers, prowling there at 70% below Speed 22 (15 mph/24 km) and gaining +2 on initiative and +2 to strike when it drops on a foe by surprise; the heavy armor slows it and costs -50% to Prowl on the ground. This row is the body alone; the pilot is the class geofront-demon-eater-geo-borg, which also lists the standard bionic features.', 'Rifts World Book 25: China 2 p.128-130'),
('ab-830-assault-geo-borg', 'Assault Geo-Borg (AB-830)', 'rifts', 'borg', NULL, NULL, 'Running: 120 (192 km) in light armor, printed without a unit; without armor it can run at 140 mph (224 km). Heavy armor reduces speed by half (70 mph/112 km). Leaping: with the micro-boosters, up to 60 feet (18.3 m) high and 100 feet (30.5 m) across (half that distance without the boosters).', 'Flying: Via jet pack only.', NULL, 'Height: 7 feet (2.1 m). Width: 2.5 feet (.7 m).', '600 lbs (270 kg)', 180, 1, NULL, 8000000, '8 million credits.', 'The Geofront''s stealth and infiltration full conversion body, built to keep human proportions and a human face under the helmet so its wearer passes for an ordinary soldier. It has Bionic P.S. 30, P.P. 24 and Speed 144 on nuclear power, with micro-boosters in the back and legs for long leaps; the optional 240 M.D.C. heavy armor halves its speed and costs -50% to Prowl, so it is seldom worn. This row is the body alone; the pilot is the class geofront-assault-geo-borg, which also lists the standard bionic features and the hand weapons it usually carries.', 'Rifts World Book 25: China 2 p.130-131'),
('ab-955-lion-geo-borg', 'Lion Geo-Borg (AB-955)', 'rifts', 'borg', NULL, NULL, 'Running: 140 mph (224 km). Leaping: up to 20 feet (6.1 m) high and 30 feet (9.1 m) across; increase by 50% with a running start.', 'Cannot fly.', 'Can swim at 40 mph (64 km) and survive depths of up to 800 feet (244 m).', 'Height: 4 feet (1.2 m). Width: 3 feet (0.9 m) at the hips.', '2 tons', 280, 1, NULL, 8000000, 'Mass production should get the cost down to around 8-10 million credits.', 'A human brain in the body of a giant mechanical lion, the Geofront''s newest full conversion design, made for deep reconnaissance in forest and jungle where it may pass for a Nature Spirit. It has Bionic P.S. 44, P.P. 24 and Speed 144 on nuclear power and a hide that feels like living fur, but it cannot hold weapons in its paws and is -60% on skills that need hands; about 200 prototypes are fielded and a thousand more are being built. This row is the body alone; the pilot is the class geofront-lion-geo-borg, which also lists the standard bionic features.', 'Rifts World Book 25: China 2 p.131-132');

INSERT OR IGNORE INTO vehicle_locations (vehicle_slug, location, mdc, mdc_note, ordinal) VALUES
  ('iron-juggernaut-blazing', 'Main Body', 910, 'Regenerates 3D6 M.D. per melee round. Impervious to possession, disease, gases, toxins, cold, heat, fire, plasma, lava, magic fires and nuclear fire. Magic weapons whose magic is cold or ice inflict double damage. No other location is printed.', 1),
  ('iron-juggernaut-earthwake', 'Main Body', 1187, 'Regenerates 1D4x10 M.D. per melee round. Impervious to possession, disease, gases, toxins and normal cold and heat. Electricity, lightning, storms (including Ley Line Storms, tornadoes and hurricanes) and explosions do half damage. Most M.D. weapons and spells do normal damage; Rune weapons inflict double damage. No other location is printed.', 1),
  ('iron-juggernaut-fury', 'Main Body', 1340, 'Regenerates 6D6 M.D.C. per melee round. Cold-based magic including ice spells and weapons, wands and weapons made from a Millennium Tree, and Rune weapons all inflict double damage. No other location is printed.', 1),
  ('iron-juggernaut-iron-dragonfly', 'Main Body', 1210, 'Regenerates 4D6 M.D.C. per melee round. Magic weapons whose magic is fire or earth based inflict double damage. No other location is printed.', 1),
  ('iron-juggernaut-sea-viper', 'Main Body', 690, 'Regenerates 3D6 M.D.C. per melee round. Impervious to possession, disease, gases, toxins, pollution and ordinary cold. Electricity, sonic attacks, explosives and magic-based cold and water attacks do half damage; magic weapons and other M.D. attacks do full damage; M.D. fire, plasma, magic fires and nuclear fire do double damage. No other location is printed.', 1),
  ('iron-juggernaut-thundering', 'Main Body', 1130, 'Regenerates 5D6 M.D.C. per melee round. Impervious to possession, disease, gases, toxins, cold, heat, lightning and hurricanes; lasers do half damage. Magic weapons that are the creation of Bio-Wizardry or Rune Magic inflict double damage. No other location is printed.', 1),
  ('iron-juggernaut-warhawk', 'Main Body', 770, 'Regenerates 3D6 M.D.C. per melee round. Impervious to possession, disease, gases, toxins, cold, heat and ordinary fire. M.D. fire, plasma, magic fires, nuclear fire, electricity and sonic attacks do half damage. Magic weapons whose magic is cold, ice or water based inflict double damage, as does the fire cast by some Russian demons and gods. No other location is printed.', 1),
  ('iron-juggernaut-wing-blade', 'Main Body', 1480, 'Regenerates 3D6 M.D. per melee round. Impervious to possession, disease, gases, toxins, cold, heat, fire, plasma, lava, magic fires and nuclear fire. Magic weapons whose magic is cold or ice inflict double damage.', 1),
  ('iron-juggernaut-wing-blade', 'Wings', 200, 'each; the number of wings is not printed', 2),
  ('iron-juggernaut-wing-blade', 'Tail Blade', 200, NULL, 3),
  ('iron-juggernaut-wing-blade', 'Scythe Arm', 440, NULL, 4),
  ('iron-juggernaut-wing-blade', 'Small Legs', 80, 'printed without "each"; the hand to hand block counts twelve small spiked legs', 5),
  ('iron-juggernaut-millipede', 'Main Body', 1880, 'Regenerates 3D6 M.D. per melee round. Impervious to possession, disease, gases, toxins, cold, heat, fire, plasma, lava, magic fires and nuclear fire. Magic weapons whose magic is cold or ice inflict double damage.', 1),
  ('iron-juggernaut-millipede', 'Forward Arms', 600, 'each; the number is not printed', 2),
  ('iron-juggernaut-millipede', 'Forward Cannons', 400, 'each; the number is not printed here (the weapon line is Plasma Cannons (2))', 3),
  ('iron-juggernaut-millipede', 'Forward Turrets', 150, 'each; the number is not printed', 4),
  ('iron-juggernaut-millipede', 'Rear Robot Fighters (2)', 700, 'each', 5),
  ('iron-juggernaut-millipede', 'Legs (38)', 110, 'each', 6),
  ('at-c8000-wing-blade-cyborg', 'Hands (2)', 15, 'each; difficult target: called shot only, and even then -3 to strike', 1),
  ('at-c8000-wing-blade-cyborg', 'Arms (4)', 40, 'each', 2),
  ('at-c8000-wing-blade-cyborg', 'Legs (2)', 110, 'each', 3),
  ('at-c8000-wing-blade-cyborg', 'Tail (1)', NULL, '50 M.D.C. per 6 ft (1.2 m) length, as printed; difficult target: called shot only, and even then -3 to strike', 4),
  ('at-c8000-wing-blade-cyborg', 'Cheek Blades (2)', 10, 'each; difficult target: called shot only, and even then -3 to strike', 5),
  ('at-c8000-wing-blade-cyborg', 'Wings (2; folding)', 90, 'each', 6),
  ('at-c8000-wing-blade-cyborg', 'Head', 90, 'reinforced; destroying the head kills the character', 7),
  ('at-c8000-wing-blade-cyborg', 'Neck', 120, 'reinforced', 8),
  ('at-c8000-wing-blade-cyborg', 'Neck Cameras (4; two on each side)', 2, 'each; difficult target: called shot only, and even then -3 to strike', 9),
  ('at-c8000-wing-blade-cyborg', 'Knee Cameras (2; one each)', 2, 'each; difficult target: called shot only, and even then -3 to strike', 10),
  ('at-c8000-wing-blade-cyborg', 'Nose Horn/Grapnel (1)', 15, 'difficult target: called shot only, and even then -3 to strike', 11),
  ('at-c8000-wing-blade-cyborg', 'Head Horns (2; back of head)', 10, 'each; difficult target: called shot only, and even then -3 to strike', 12),
  ('at-c8000-wing-blade-cyborg', 'Removable Jet Thruster (1, back)', 80, 'difficult target: called shot only, and even then -3 to strike', 13),
  ('at-c8000-wing-blade-cyborg', 'Tiny Maneuvering Thrusters (10; legs and back)', 5, 'each; difficult target: called shot only, and even then -3 to strike', 14),
  ('at-c8000-wing-blade-cyborg', 'Main Body', 270, 'cannot wear additional body armor (built in). Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 36 hours; 125 points below zero destroys the ''borg with no hope of recovery', 15),
  ('at-c9000-tsunami-cyborg', 'Hands (2)', 17, 'each, as printed, although the right arm carries a mini-gun in place of a hand; difficult target: called shot only, and even then -3 to strike', 1),
  ('at-c9000-tsunami-cyborg', 'Left Arm (1)', 50, NULL, 2),
  ('at-c9000-tsunami-cyborg', 'Right Weapon Arm (1)', 60, NULL, 3),
  ('at-c9000-tsunami-cyborg', 'Legs (2)', 120, 'each', 4),
  ('at-c9000-tsunami-cyborg', 'Tail/Particle Beam Cannon (1)', 70, 'difficult target: called shot only, and even then -3 to strike', 5),
  ('at-c9000-tsunami-cyborg', 'Wings (2; folding)', 100, 'each', 6),
  ('at-c9000-tsunami-cyborg', 'Head/Neck', 100, 'reinforced; destroying the head kills the character', 7);

INSERT OR IGNORE INTO vehicle_locations (vehicle_slug, location, mdc, mdc_note, ordinal) VALUES
  ('at-c9000-tsunami-cyborg', 'Jet Thruster/Mini-Missile Launcher (1, back)', 80, 'difficult target: called shot only, and even then -3 to strike', 8),
  ('at-c9000-tsunami-cyborg', 'Tiny Maneuvering Thrusters (10; legs and back)', 5, 'each; difficult target: called shot only, and even then -3 to strike', 9),
  ('at-c9000-tsunami-cyborg', 'Main Body', 320, 'cannot wear additional body armor (built in). Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 36 hours; 125 points below zero destroys the ''borg with no hope of recovery', 10),
  ('at-c10000-imperial-dragon-cyborg', 'Hands/Feet (2)', 20, 'each; difficult target: called shot only, and even then -3 to strike', 1),
  ('at-c10000-imperial-dragon-cyborg', 'Forelegs/Arms (2)', 50, 'each', 2),
  ('at-c10000-imperial-dragon-cyborg', 'Hind Legs (2)', 60, 'each', 3),
  ('at-c10000-imperial-dragon-cyborg', 'Prehensile Tail (1)', NULL, '50 M.D.C. per 6 ft (1.8 m) length; difficult target: called shot only, and even then -3 to strike', 4),
  ('at-c10000-imperial-dragon-cyborg', 'Double Laser Turrets (2, on rear sides)', 80, 'each; difficult target: called shot only, and even then -3 to strike', 5),
  ('at-c10000-imperial-dragon-cyborg', 'Mini-Missile Launchers (2, on sides)', 100, 'each; difficult target: called shot only, and even then -3 to strike', 6),
  ('at-c10000-imperial-dragon-cyborg', 'Triple-Barrelled Particle Beam Gun (1)', 100, NULL, 7),
  ('at-c10000-imperial-dragon-cyborg', 'Smoke Dispenser (1)', 20, NULL, 8),
  ('at-c10000-imperial-dragon-cyborg', 'Head', 100, 'reinforced; difficult target: called shot only, and even then -3 to strike; destroying the head kills the character', 9),
  ('at-c10000-imperial-dragon-cyborg', 'Main Body', 350, 'cannot wear additional body armor (built in). Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 36 hours; 125 points below zero destroys the ''borg with no hope of recovery', 10),
  ('at-c12000-flame-cloud-cyborg', 'Hands/Feet (2)', 20, 'each; difficult target: called shot only, and even then -3 to strike', 1),
  ('at-c12000-flame-cloud-cyborg', 'Forelegs/Arms (2)', 50, 'each', 2),
  ('at-c12000-flame-cloud-cyborg', 'Hind Legs (2)', 50, 'each', 3),
  ('at-c12000-flame-cloud-cyborg', 'Laser Gun (2)', 50, 'each', 4),
  ('at-c12000-flame-cloud-cyborg', 'Prehensile Tail (1)', NULL, '50 M.D.C. per 6 ft (1.8 m) length; difficult target: called shot only, and even then -3 to strike', 5),
  ('at-c12000-flame-cloud-cyborg', 'Jet Thrusters (2, on sides)', 120, 'each; destroying one reduces maximum speed by 70% and the pilot is at -25% to all rolls; destroying both leaves the ''borg unable to fly, and if in the air it crashes', 6),
  ('at-c12000-flame-cloud-cyborg', 'Particle Beam Cannon (2, on rear sides of the tail)', 70, 'each; difficult target: called shot only, and even then -3 to strike', 7),
  ('at-c12000-flame-cloud-cyborg', 'Head', 100, 'reinforced; difficult target: called shot only, and even then -3 to strike; destroying the head kills the character', 8),
  ('at-c12000-flame-cloud-cyborg', 'Main Body', 320, 'cannot wear additional body armor (built in). Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 36 hours; 125 points below zero destroys the ''borg with no hope of recovery', 9),
  ('db-800-demon-eater-cyborg', 'Hands (2)', 35, 'each', 1),
  ('db-800-demon-eater-cyborg', 'Arms (2)', 100, 'each', 2),
  ('db-800-demon-eater-cyborg', 'Legs (2)', 170, 'each', 3),
  ('db-800-demon-eater-cyborg', 'Feet (2)', 100, 'each', 4),
  ('db-800-demon-eater-cyborg', 'Tails (2)', 80, 'each', 5),
  ('db-800-demon-eater-cyborg', 'Head', 140, 'reinforced; small and difficult target: called shot only, and even then -3 to strike; destroying the head kills the character', 6),
  ('db-800-demon-eater-cyborg', 'Main Body', 220, 'plus an additional 340 M.D.C. for its heavy armor that hooks right onto the body. Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 18 plus 2D6 hours; more than 100 M.D.C. below zero destroys the unit with no hope of recovery', 7),
  ('ab-830-assault-geo-borg', 'Hands (2)', 10, 'each', 1),
  ('ab-830-assault-geo-borg', 'Arms (2)', 40, 'each', 2),
  ('ab-830-assault-geo-borg', 'Legs (2)', 80, 'each', 3),
  ('ab-830-assault-geo-borg', 'Head', 90, 'reinforced; small and difficult target: called shot only, and even then -3 to strike; destroying the head kills the character', 4),
  ('ab-830-assault-geo-borg', 'Main Body', 180, 'plus an additional 140 M.D.C. for light espionage armor that hooks right onto the body; the heavy armor instead provides 240 M.D.C. at half speed and -50% Prowl. Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 18 plus 2D6 hours; more than 100 M.D.C. below zero destroys the unit with no hope of recovery', 5),
  ('ab-955-lion-geo-borg', 'Claws (2)', 25, 'each', 1),
  ('ab-955-lion-geo-borg', 'Arms/Front Legs (2)', 70, 'each', 2),
  ('ab-955-lion-geo-borg', 'Legs, Hind (2)', 120, 'each', 3),
  ('ab-955-lion-geo-borg', 'Head', 150, 'reinforced; small and difficult target: called shot only, and even then -3 to strike; destroying the head kills the character', 4),
  ('ab-955-lion-geo-borg', 'Main Body', 280, 'reinforced. Depleting it destroys the artificial body, but emergency systems keep the brain and vital organs alive for 18 plus 2D6 hours; more than 100 M.D.C. below zero destroys the unit with no hope of recovery', 5);

INSERT OR IGNORE INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note) VALUES
  ('iron-juggernaut-blazing', 1, 'Flaming Fists (2)', 'Flaming punch: 1D4x10 M.D. plus combustibles ignite and burn. Flamethrower-like gout: 1D6x10 M.D. plus combustibles ignite (counts as two attacks). Fire Balls: 4D6 M.D. per single fire ball, 1D4x10+4 M.D. per dual blast.', 1, 'Ranged attacks: 1,600 feet (488 m).', 'Equal to the number of attacks per melee round.', 'Unlimited.', '+6 to strike with punches; +4 to strike with ranged attacks.', NULL),
  ('iron-juggernaut-blazing', 2, 'Laser Beam Eyes', '3D6 M.D.', 1, '2,000 feet (610 m).', 'Equal to the number of attacks per melee round.', 'Unlimited.', '+4 to strike with ranged attacks.', NULL),
  ('iron-juggernaut-blazing', 3, 'Other Weapons: Spiked Shield, Steam Attack', NULL, 1, NULL, NULL, NULL, NULL, 'Named only; this book prints no statistics for it. The block is a summary of the Coalition Wars entry it cites.'),
  ('iron-juggernaut-blazing', 4, 'Magic Spells', 'By spell: Lantern Light, Fireblast, Fire Whip and all Fire Elemental spells levels 1-4.', 0, NULL, 'Two by spell per melee round, in place of the six physical attacks.', 'P.P.E.: 1D4x100+360.', NULL, 'Cast at 6th level proficiency.'),
  ('iron-juggernaut-earthwake', 1, 'Lava Bolts from the Fingers', '6D6 M.D. from one large bolt, or 4D6 M.D. from a volley of four small bolts fired from the fingers (1D6 M.D. each).', 1, '1,200 feet (366 m).', 'Each blast or volley counts as a single attack.', 'Unlimited.', NULL, NULL),
  ('iron-juggernaut-earthwake', 2, 'Forearm Spear Launchers (2)', '1D6 M.D. per individual spear, 3D6 for a volley of three fired simultaneously at the same target, 5D6 for a volley of six and 1D4x10+6 for a volley of nine.', 1, '1,200 feet (366 m).', 'Single shot or volleys of three, six or nine.', 'Unlimited. Spears are magically replenished at the beginning of each melee round.', NULL, NULL),
  ('iron-juggernaut-earthwake', 3, 'Other Weapons: Mini-Missile Launcher, Steam Attack', NULL, 1, NULL, NULL, NULL, NULL, 'Named only; this book prints no statistics for it. The block is a summary of the Coalition Wars entry it cites.'),
  ('iron-juggernaut-earthwake', 4, 'Magic Spells', 'By spell: Chameleon (6), Climb (3), Concealment (6), Detect Concealment (6), Fool''s Gold (10), Repel Animals (7), Dispel Magic Barriers (20), Locate (30), Stone to Flesh (30), Speed of the Snail (50), Purification (20), Water to Wine (40), and all Earth Elemental spells levels 1-3.', 0, NULL, 'Two by magic spell per melee round, in place of the physical attacks.', 'P.P.E.: 1D4x100+224.', NULL, 'Cast at 6th level proficiency.'),
  ('iron-juggernaut-fury', 1, 'Ion Cannons (2)', '6D6 M.D. per blast.', 1, '3,000 feet (914 m).', 'Equal to the number of attacks per melee round.', 'Unlimited.', '+3 to strike.', NULL),
  ('iron-juggernaut-fury', 2, 'Forearm Blades (2)', '7D6 M.D. (single blade; 2D6 M.D. plus normal punch damage) or 2D4x10 M.D. (simultaneous double blade strike).', 1, NULL, 'Equal to the number of attacks per melee round.', NULL, '+9 to strike.', NULL),
  ('iron-juggernaut-fury', 3, 'Other Weapons: Steam Attack', NULL, 1, NULL, NULL, NULL, NULL, 'Named only; this book prints no statistics for it. The block is a summary of the Coalition Wars entry it cites.'),
  ('iron-juggernaut-fury', 4, 'Magic Spells', 'By spell: Cleanse, Manipulate Objects, Throwing Stones, Shatter, Create Wood, Mystic Fulcrum, Light Target, all Earth Elemental spells levels 1-4 and all Air Elemental spells levels 1-2, plus the Air Elemental spells Energy Disruption, Energy Field, Electric Arc, Dissipate Gases, Call Lightning, Ball Lightning and Electric Field.', 0, NULL, 'Two by magic per melee round, in place of the six physical attacks.', 'P.P.E.: 1D6x100+600.', NULL, 'All at 6th level proficiency.'),
  ('iron-juggernaut-iron-dragonfly', 1, 'Scythe Hands (2)', 'Metal Blades: 1D4x10+4 M.D. Electrified Blades: 1D6x10 M.D. (supernatural P.S. included). Cross Blade Lightning Strike: 6D6 M.D. per bolt.', 1, '1,600 feet (488 m) for energy blast.', 'Equal to the number of attacks per melee round.', 'Unlimited.', '+7 to strike with punches and kicks; +3 to strike with energy blasts.', NULL),
  ('iron-juggernaut-iron-dragonfly', 2, 'Forearm Mini-Missile Launchers (2)', '1D4x10 (armor piercing) or 1D6x10 (plasma).', 1, 'One mile (1.6 km).', 'Single shot or volleys of two, four or six.', '18 per arm for 36 total.', NULL, NULL),
  ('iron-juggernaut-iron-dragonfly', 3, 'Other Weapons: Steam Attack', NULL, 1, NULL, NULL, NULL, NULL, 'Named only; this book prints no statistics for it. The block is a summary of the Coalition Wars entry it cites.'),
  ('iron-juggernaut-iron-dragonfly', 4, 'Magic Spells', 'By spell: Blinding Flash (1), Globe of Daylight (2), Energy Bolt (5), Thunderclap (4), Fingers of the Wind (5), Float in Air (5), Energy Disruption (12), Impervious to Energy (20), Wind Rush (20), Dispel Magic Barrier (20), Summon Fog (140). Air Elemental spells: Stop Wind (5), Change Wind Direction (6), Howling Wind (7), Call Lightning (10), Ball Lightning (15), Miasma (7), Dissipate Gases (15), Invisible Wall (30), Electrical Field (35), Darken Sky (25) and Atmosphere Manipulation (50).', 0, NULL, 'Two by magic per melee round, in place of the six physical attacks.', 'P.P.E.: 1D4x100+188.', NULL, 'No proficiency level is printed in this block.'),
  ('iron-juggernaut-sea-viper', 1, 'Blade Hands (2)', '4D6 M.D. for most attacks, 6D6 M.D. for spinning blade attack.', 1, NULL, NULL, NULL, '+10 to strike in the water; half that out of it.', NULL),
  ('iron-juggernaut-sea-viper', 2, 'Blade Feet (2)', '5D6 M.D.', 1, NULL, NULL, NULL, '+10 to strike in the water; half that out of it.', NULL),
  ('iron-juggernaut-sea-viper', 3, 'Magic Spells', 'By spell: Turn Dead (6), Negate Magic (30), Energy Bolt (5), Magic Net (7), Escape (8), Summon Fog (140), Summon Rain (200), Summon Storm (300), Cleanse (6), Orb of Cold (6), Wave of Frost (6), Frost Blade (15), Create Water (15) and all Water Elemental spells levels 1-3.', 0, NULL, 'Two by magic per melee round, in place of the physical attacks.', 'P.P.E.: 1D4x100+175.', NULL, 'Cast at sixth level proficiency. This block prints no Other Weapons line.'),
  ('iron-juggernaut-thundering', 1, 'Forearm Blades (2)', '6D6 M.D. for single strike, 1D4x10+4 M.D. for double strike.', 1, NULL, 'Equal to the number of attacks per melee round.', NULL, '+11 to strike.', NULL),
  ('iron-juggernaut-thundering', 2, 'Mini-Missile Launcher', '1D4x10 M.D. (armor piercing) or 1D6x10 M.D. (plasma).', 1, 'One mile (1.6 km).', 'One or two at a time.', 'Six total.', NULL, NULL),
  ('iron-juggernaut-thundering', 3, 'Other Weapons: Electrical Bolts from the Eyes, Forearm Laser', NULL, 1, NULL, NULL, NULL, '+3 to strike with energy weapons.', 'Named only; this book prints no statistics for it. The block is a summary of the Coalition Wars entry it cites.'),
  ('iron-juggernaut-thundering', 4, 'Magic Spells', 'By spell: Light Target, Wind Rush, Electric Arc, Wave of Frost, and all Air Elemental spells levels 1-4.', 0, NULL, 'Three by magic per melee round, in place of the nine physical attacks.', 'P.P.E.: 1D4x100+300.', NULL, 'Cast at 6th level proficiency.'),
  ('iron-juggernaut-warhawk', 1, 'Pole Arm', '4D6 M.D. (sickle blade) or 1D6x10 M.D. (lightning strike).', 1, '3,000 feet (914 m) for lightning strike. Hand to hand for sickle blade.', 'Equal to the number of attacks per melee round.', 'Unlimited.', '+4 to strike with energy blasts.', NULL),
  ('iron-juggernaut-warhawk', 2, 'Silver Sword Forearm Blades (2)', '6D6 M.D. each.', 1, NULL, NULL, NULL, NULL, NULL);

INSERT OR IGNORE INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note) VALUES
  ('iron-juggernaut-warhawk', 3, 'Other Weapons: Steam Attack', NULL, 1, NULL, NULL, NULL, NULL, 'Named only; this book prints no statistics for it. The block is a summary of the Coalition Wars entry it cites.'),
  ('iron-juggernaut-warhawk', 4, 'Magic Spells', 'By spell: Cloud of Smoke (2), Globe of Daylight (2), Thunderclap (4), Ignite Fire (6), Fuel Flame (5), Fire Bolt (7), Fire Ball (10), Energy Disruption (12), Impervious to Energy (20), Wind Rush (20), Magic Pigeon (20), Cleanse (6), Shatter (5), Lantern Light (1), Light Target (6), Manipulate Objects (2+), Chromatic Protection (10), Reflection (7), Featherlight (10), Implosion Neutralizer (12), Electric Arc (8), Fireblast (8), Wall of Wind (40), Shockwave (35).', 0, NULL, 'Two by magic per melee round, in place of the eight physical attacks.', 'P.P.E.: 1D4x100+155.', NULL, 'All spells are at 6th level proficiency.'),
  ('iron-juggernaut-wing-blade', 1, 'Mega-Damage Hand to Hand Combat', 'Wing Strike with the blunt edge of a blade: 1D6x10+25 S.D.C., or 4D6 M.D. from a full strength strike. Scythe Blade: 7D6+10 M.D.; Power Punch/Stab: 2D4x10+10 M.D. (counts as two melee attacks). Blade Strike from one Lower (leg) Appendage: 6D6 M.D.; Power Strike/Stab: 1D6x10+6 (counts as two melee attacks). Simultaneous Blade Strike: 1D6x10+6 M.D. (counts as two attacks). Tail Blade: 5D6 M.D. Small Leg Blades (near hip): 4D6 M.D. Small Spiked Legs (12): 2D6 M.D. each. Flying Body Block: 3D6 M.D. and a 01-80% likelihood of knocking any opponent its size or smaller off its feet (victim loses two melee actions and initiative).', 1, NULL, 'Ten physical attacks per melee round. The small spiked legs can stab in groups of 2, 4 or 6, but each leg strike counts as one melee action/attack.', NULL, '+10 to strike.', 'Inflicts double damage to creatures vulnerable to silver or magic. The small spiked legs stab and hold: once stabbed in they are not released to stab again. The block prints no separate weapon systems and no Other Weapons line.'),
  ('iron-juggernaut-wing-blade', 2, 'Magic Spells', 'By spell: Freeze Water (8), Sheet of Ice (15), Hail (20), Shards of Ice (15), Wall of Ice (20), Ten Foot Ball of Ice (30), Orb of Cold (6), Foul Water (6), Float on Water (4), Liquids to Water (10), Lantern Light (1), Globe of Daylight (2), Thunder Clap (2), and Northwind.', 0, NULL, 'Two by spell per melee round, in place of the ten physical attacks.', 'P.P.E.: 1D4x100+140.', NULL, 'All cast at 6th level spell strength. The predominantly Water Elemental spells are described in Rifts Conversion Book One and in the Book of Magic.'),
  ('iron-juggernaut-millipede', 1, 'Plasma Cannons (2)', '1D6x10 M.D. per single blast, 2D6x10 per dual blast.', 1, '4000 feet (1219 m).', NULL, 'Unlimited.', '+5 to strike with energy weapons.', 'No rate of fire is printed for this weapon.'),
  ('iron-juggernaut-millipede', 2, 'Forearm Lasers', '4D6 M.D.', 1, '2,000 feet (610 m).', 'Each blast counts as one melee attack.', 'Unlimited.', '+5 to strike with energy weapons.', NULL),
  ('iron-juggernaut-millipede', 3, 'Flame Thrower (1; mouth)', '1D4x10 M.D. per "bolt," or 5D6 M.D. from a stream of fire.', 1, 'Fire Bolt: 2,000 feet (610 m). Flaming Stream: 300 feet (91.5 m).', 'Each blast counts as one melee attack.', 'Unlimited.', NULL, NULL),
  ('iron-juggernaut-millipede', 4, 'Mini-Missiles (12; forearm)', '1D4x10 or 1D6x10 depending on the missile.', 1, 'One mile (1.6 km).', NULL, '36 total.', NULL, 'No rate of fire is printed.'),
  ('iron-juggernaut-millipede', 5, 'Other Weapons: Hand to Hand Punch Attacks and Steam Attack', '6D6 M.D. for a full strength punch.', 1, NULL, NULL, NULL, '+9 to strike with punches.', 'The steam attack is named only; no statistics are printed for it.'),
  ('iron-juggernaut-millipede', 6, 'Magic Spells', 'By spell: all first level Earth Elemental magic plus Dirt to Sand (6), Crumble Stone (10), Mend Stone (15), Dig (8), Wall of Stone (15), Animate Object (12), Hopping Stones (6), Quicksand (15), and Sand Storm (15).', 0, NULL, NULL, 'Available P.P.E.: 1D4x100+100.', NULL, 'At 6th level spell strength. Attacks per melee is printed as Twelve, with no by-spell count.'),
  ('at-c8000-wing-blade-cyborg', 1, 'Prehensile Tail (1)', 'Three pairs of launchable vibro-blades: the two smaller ones inflict 2D6 M.D., the large one 3D6 M.D. Fixed tip vibro-blade stab: 1D6 M.D. Tail strike (blunt): 6D6 S.D.C.; restrained attack does half damage.', 1, 'Tail reach is 12 feet (3.6 m); flying blades: 500 feet (152 m), limited to line of sight.', 'Total hand to hand melee actions; each strike by a flying blade counts as one of the character''s melee attacks/actions.', NULL, '-1 to strike for each blade that is in flight.', 'Primary purpose: anti-personnel. The blades launch like mini-missiles and are directed by remote control; if not destroyed (15 M.D.C. for small, 25 for large) they return and can be reattached. The tail also feels around narrow openings, grabs small objects, parries, entangles, and its tip hooks on to help in climbing.'),
  ('at-c8000-wing-blade-cyborg', 2, 'Concealed Mouth Particle Beam Gun (1)', '1D4x10 M.D. per blast.', 1, '1200 feet (365 m)', 'Equal to the total number of hand to hand attacks.', '24 per hour, but is patched into power supply so it regenerates.', NULL, 'Primary purpose: anti-armor and anti-cyborg.'),
  ('at-c8000-wing-blade-cyborg', 3, 'Grappling Spike (nose horn)', '1D4 M.D.', 1, '200 feet (61 m)', 'Equal to the total number of hand to hand attacks.', 'One', NULL, 'Primary purpose: climbing tool; anti-armor and anti-cyborg. The horn jabs, stabs and parries, or its tip is fired on a cable for climbing or snagging vehicles and bots; afterwards the spike is retracted or the line cut and the spike abandoned.'),
  ('at-c8000-wing-blade-cyborg', 4, 'Cheek Blades', '1D6 M.D.', 1, NULL, NULL, NULL, NULL, 'Used for parrying and slashing with the head.'),
  ('at-c8000-wing-blade-cyborg', 6, 'Concealed Weapon Compartments', NULL, 0, NULL, NULL, 'Two concealed compartments in each leg. One contains a vibro-blade dagger (or stun stick or laser rod) and a pair of stun/flash grenades; the other typically two extra E-clips and an RMK medical kit (for use on others).', NULL, 'The standard snoop. No damage is printed here; the contents are catalog items. The non-weapon feature list prints one concealed compartment in each leg.'),
  ('at-c8000-wing-blade-cyborg', 7, 'Hand to Hand Combat', 'Restrained Punch: 1D6+12 S.D.C. Full Strength Punch: 3D6+12 S.D.C. Power Punch: 1D4 M.D. (counts as 2 melee attacks). Head Butt: 2D6 S.D.C. Kick: 4D6+12 S.D.C. Jump Kick/Leap Attack: 2D4 M.D. (counts as 2 melee attacks). Judo Style Throw/Flip: 3D6 S.D.C. Full Speed Ram/Body Block: 1D4 M.D. (counts as 2 melee attacks).', 1, NULL, 'Attacks per melee equal the character''s hand to hand combat skill selection and experience, +2 additional attacks per melee (includes tail, neck and arm bonuses).', NULL, '+2 on initiative, +2 to parry, +1 to dodge, +2 to pull punch, +1 to roll with punch/fall/impact, and +2 to save vs horror factor; plus P.P. 22 bonus of +4 to strike, parry and dodge.', 'The cyborg''s physical strength is S.D.C. based except for the occasional special attack such as a power punch. Also see the vibro-blade tail mega-damage.'),
  ('at-c9000-tsunami-cyborg', 1, 'Striking Tail/Particle Beam Gun', 'Tail strike (blunt): 6D6 S.D.C.; restrained attacks do half damage. With the vibro-blade, the strike inflicts 2D4 M.D. Particle Beam: 5D6 M.D.', 1, 'Tail reach is 6 feet (3.6 m), as printed; Particle Beam Weapon: 1,000 feet (305 m).', 'Total hand to hand melee actions.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-personnel, assault. The tail is not flexible enough to grab things; a vibro-blade and a particle beam weapon are built into its tip.'),
  ('at-c9000-tsunami-cyborg', 2, 'Arm Mini-Gun/Vibro-Axe', 'Mini-Gun: a burst is 20 rounds and inflicts 1D4x10 M.D.; can only fire bursts. The vibro-axe inflicts 4D6 M.D.', 1, '2000 feet/610 m (mini-gun); hand to hand (vibro-axe)', 'Equal to the total number of hand to hand attacks.', 'Mini-Gun: 1000 rounds in canister; that''s fifty bursts.', NULL, 'Primary purpose: anti-armor and anti-cyborg. The right arm holds the mini-gun, firing explosive bullets, in place of a hand; the rest of the arm is the ammo canister, with the vibro-axe below the gun.'),
  ('at-c9000-tsunami-cyborg', 3, 'Mini-Missiles (2)', 'Varies with missile type.', 1, 'About one mile.', 'One at a time, or in volleys of two.', 'Two mini-missiles.', NULL, 'Primary purpose: anti-aircraft, anti-armor. Secondary purpose: defense. Mounted on the back, on top of the jet thruster system.'),
  ('at-c9000-tsunami-cyborg', 4, 'Laser Eyes', 'Single beam does 2D6 M.D.; simultaneous double beam blast inflicts 4D6 M.D.', 1, '1000 feet (305 m).', 'Equal to the total number of hand to hand attacks.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-cyborg. Secondary purpose: defense. The two beams always fire together unless the head has taken more than 20 M.D.C. of damage, which disables one eye laser; 40 M.D.C. or more disables both.'),
  ('at-c9000-tsunami-cyborg', 5, 'Concealed Weapon Compartments', NULL, 0, NULL, NULL, 'Two concealed compartments in each leg. One contains a vibro-blade dagger (or stun stick or laser rod) and a pair of stun/flash grenades; the other typically two extra E-clips and an RMK medical kit (for use on others).', NULL, 'The standard Tsunami. No damage is printed here; the contents are catalog items. The non-weapon feature list prints one concealed compartment in each leg.'),
  ('at-c9000-tsunami-cyborg', 6, 'Hand to Hand Combat', 'Restrained Punch: 1D6+13 S.D.C. Full Strength Punch: 3D6+13 S.D.C. Power Punch: 1D4 M.D. (counts as 2 melee attacks). Head Butt: 2D6 S.D.C. Kick: 4D6+13 S.D.C. Jump Kick/Leap Attack: 2D4 M.D. (counts as 2 melee attacks). Judo Style Throw/Flip: 3D6 S.D.C. Full Speed Ram/Body Block: 1D4 M.D. (counts as 2 melee attacks).', 1, NULL, 'Attacks per melee equal the character''s hand to hand combat skill selection and experience, +1 additional attack per melee (includes tail bonuses).', NULL, '+2 on initiative, +2 to parry, +1 to dodge, +2 to pull punch, +1 to roll with punch/fall/impact, and +2 to save vs horror factor; plus P.P. 23 bonus of +4 to strike, parry and dodge.', 'The cyborg''s physical strength is S.D.C. based except for the occasional special attack such as a power punch. Also see the vibro-blade tail mega-damage.'),
  ('at-c10000-imperial-dragon-cyborg', 1, 'Triple-Barrelled Particle Beam Gun', '1D6x10+10 M.D. per triple blast; each individual gun does 4D6 M.D.', 1, '3000 feet (915 m).', 'Total hand to hand melee actions.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-armor, assault. The main gun.'),
  ('at-c10000-imperial-dragon-cyborg', 2, 'Mini-Missile Launchers (2)', 'Varies with missile type.', 1, 'About one mile.', 'One at a time, or in volleys of two, three or six.', 'Six total; three per launcher.', NULL, 'Primary purpose: anti-aircraft, anti-armor. Secondary purpose: defense. One launcher on each side.'),
  ('at-c10000-imperial-dragon-cyborg', 3, 'Double Laser Turrets (2)', 'Each double laser blast inflicts 4D6 M.D.; a simultaneous two-turret blast does 1D6x10 M.D. (counts as two melee attacks/actions).', 1, '4000 feet (1200 m)', 'Equal to the total number of hand to hand attacks.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-personnel, anti-aircraft. Secondary purpose: defense. Two dual laser mini-turrets on the flanks that swivel to fire front, sides, rear and straight up.');

INSERT OR IGNORE INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note) VALUES
  ('at-c10000-imperial-dragon-cyborg', 4, 'Head Lasers', 'Single beam does 2D6 M.D.; simultaneous triple beam blast inflicts 6D6 M.D.', 1, '1000 feet (305 m).', 'Equal to the total number of hand to hand attacks.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-cyborg. Secondary purpose: defense. A row of three laser guns above the eyes; more than 5 points of damage to the head puts one gun out of commission, and 15 or more points of mega-damage destroys the system.'),
  ('at-c10000-imperial-dragon-cyborg', 5, 'Smoke Dispenser', 'Varies with gas type.', 0, 'Each gas release/attack covers a 30 foot (9 m) area; additional attacks add a similar amount to the air.', 'Equal to the total number of hand to hand attacks.', 'Four canisters, each with 10 releases/attacks; up to four different gases, one in each canister.', NULL, 'Primary purpose: chemical warfare. Secondary purpose: defense. Four tubes on the lower front torso; common loads are smoke, mace, tear gas, tranquilizer/sleep gas and fire-extinguishing foam, with the same effects as the chemical spray bionic system.'),
  ('at-c10000-imperial-dragon-cyborg', 6, 'Vibro-Claws/Vibro-Tail', 'Each attack inflicts 3D6 M.D. Tail strike (blunt): 6D6 S.D.C.; restrained attack does half damage.', 1, NULL, NULL, NULL, NULL, 'The forelegs, hind legs and the end of the tail are all tipped with vibro-blades. The tail can feel around narrow openings, grab small objects, slash, parry or entangle.'),
  ('at-c10000-imperial-dragon-cyborg', 7, 'Hand to Hand Combat', 'Restrained Punch: 1D6+15 S.D.C. Full Strength Punch: 3D6+15 S.D.C. Power Punch: 1D4 M.D. (counts as 2 melee attacks). Head Butt: 2D6 S.D.C. Kick: 4D6+15 S.D.C. Jump Kick/Leap Attack: 2D4 M.D. (counts as 2 melee attacks). Judo Style Throw/Flip: 3D6 S.D.C. Full Speed Ram/Body Block: 1D4 M.D. (counts as 2 melee attacks).', 1, NULL, 'Attacks per melee equal the character''s hand to hand combat skill selection and experience, +1 additional attack per melee (includes tail bonuses).', NULL, '+1 on initiative, +1 to parry, +2 to dodge, +2 to pull punch, and +2 to save vs horror factor; plus P.P. 23 bonus of +4 to strike, parry and dodge (printed as P.P. 23 although the body is P.P. 22).', 'The cyborg''s physical strength is S.D.C. based except for the occasional special attack such as a power punch. Also see the vibro-blade tail mega-damage.'),
  ('at-c12000-flame-cloud-cyborg', 1, 'Flame Breath Plasma System', '1D6x10 M.D. per flame blast. The flame also starts fires if used against anything flammable.', 1, '2000 feet (610 m).', 'Total hand to hand melee actions.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-armor, assault. A plasma projector in the head breathes jets of plasma from the mouth; used mostly to strafe ground targets.'),
  ('at-c12000-flame-cloud-cyborg', 2, 'Laser Guns (2)', '4D6 M.D. per blast.', 1, '4000 feet (1200 m)', 'Equal to the total number of hand to hand attacks.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-aircraft, anti-armor. Secondary purpose: defense. Mounted on the jet thrusters, firing from ports on the sides of the exhaust system.'),
  ('at-c12000-flame-cloud-cyborg', 3, 'Tail Double Particle Beam Cannon', 'Each double particle beam blast inflicts 1D4x10+10 M.D. A single blast does 4D6 M.D.', 1, '4000 feet (1200 m)', 'Equal to the total number of hand to hand attacks.', 'Effectively unlimited.', NULL, 'Primary purpose: anti-armor, anti-aircraft. Secondary purpose: defense. Two beam cannon on the tail that rotate to aim in any direction.'),
  ('at-c12000-flame-cloud-cyborg', 4, 'Vibro-Claws/Vibro-Tail', 'Each attack inflicts 3D6 M.D. Tail strike (blunt): 6D6 S.D.C.; restrained attacks do half damage.', 1, NULL, NULL, NULL, NULL, 'The forelegs, hind legs and the end of the tail are all tipped with vibro-blades. The tail can feel around narrow openings, grab small objects, slash, parry or entangle.'),
  ('at-c12000-flame-cloud-cyborg', 5, 'Hand to Hand Combat', 'Restrained Punch: 1D6+13 S.D.C. Full Strength Punch: 3D6+13 S.D.C. Power Punch: 1D4 M.D. (counts as 2 melee attacks). Head Butt: 2D6 S.D.C. Kick: 4D6+13 S.D.C. Jump Kick/Leap Attack: 2D4 M.D. (counts as 2 melee attacks). Judo Style Throw/Flip: 3D6 S.D.C. Full Speed Ram/Body Block: 1D4 M.D. (counts as 2 melee attacks).', 1, NULL, 'Attacks per melee equal the character''s hand to hand combat skill selection and experience, +1 additional attack per melee (includes tail bonuses).', NULL, '+1 on initiative (+2 to initiative in the air), +1 to parry, +1 to dodge, +2 to dodge in the air (if flying at below cruise speed), +2 to pull punch, and +2 to save vs horror factor; plus P.P. 23 bonus of +4 to strike, parry and dodge (printed as P.P. 23 although the body is P.P. 22).', 'The cyborg''s physical strength is S.D.C. based except for the occasional special attack such as a power punch. Also see the vibro-blade tail mega-damage.'),
  ('db-800-demon-eater-cyborg', 1, 'Concealed Forearm Particle Beam Weapons (2)', '5D6 M.D. per single blast, 1D6x10 M.D. if both arms are pointed at the same target.', 1, '300 feet (91.5 m).', 'Each individual blast counts as one melee attack; a dual blast counts as two rapid succession melee attacks, though an opponent dodges it as one.', 'Effectively unlimited, tied to the ''Borg''s power supply.', NULL, 'Above the wrists of both forearms; point and shoot. A heavy close combat weapon.'),
  ('db-800-demon-eater-cyborg', 2, 'Concealed Laser Eyes (2)', '2D6 M.D. per single blast, 4D6 M.D. if both eyes fire simultaneously at the same target.', 1, '1000 feet (305 m).', 'Each individual or simultaneous dual blast counts as one melee attack.', 'Effectively unlimited, tied to the ''Borg''s power supply.', NULL, 'Located under the eyes.'),
  ('db-800-demon-eater-cyborg', 3, 'Dual Prehensile Tails (2)', 'Blunt Tail Strike: 1D8 M.D. Blade Strike: 2D6+2 (printed without a unit, under the Mega-Damage heading).', 1, 'Reach: 12 feet (3.6 m).', 'Each tail strike counts as one melee attack/action.', NULL, 'Adds two attacks per melee round, +1 to strike, +2 to parry, +2 to disarm, +5 to entangle.', 'For climbing, scaling walls, swinging and close combat. Each tail ends in a curved blade that stabs, cuts and slashes and can be driven into rock and concrete for climbing.'),
  ('db-800-demon-eater-cyborg', 4, 'Prehensile Tongue (1)', '5D6 S.D.C. or 1D6x10 S.D.C. on a power punch/strike.', 0, 'Extends up to two and a half feet (0.76 m).', NULL, NULL, NULL, 'Added for dramatic effect as much as anything; strikes or stabs in close combat.'),
  ('db-800-demon-eater-cyborg', 5, 'Bionic Jaws & Teeth', '1D4 M.D. from a nip, 2D6 M.D. from a bite.', 1, NULL, NULL, NULL, NULL, 'For close combat with demons and other supernatural predators that bite and claw.'),
  ('db-800-demon-eater-cyborg', 9, 'Bionic Strength & Damage', '2D6+13 S.D.C. damage, or 2D4 M.D. with a power punch or kick (counts as two melee attacks).', 1, NULL, NULL, NULL, NULL, 'Bionic P.S. of 35. Printed in the statistical data, not in the numbered list; the ordinal follows the list''s last number.'),
  ('ab-830-assault-geo-borg', 1, 'Concealed Forearm Laser Beam Weapons (2)', '2D6 M.D. per single blast, 4D6 M.D. if both arms are pointed at the same target.', 1, '2000 feet (610 m).', 'Each individual blast counts as one melee attack; a dual blast counts as two rapid succession melee attacks, though an opponent dodges it as one.', 'Effectively unlimited, tied to the ''Borg''s power supply.', NULL, 'Above the wrists of both forearms; point and shoot. A multipurpose weapon for long range and close combat.'),
  ('ab-830-assault-geo-borg', 2, 'Concealed Compartments (2): Exploding Throwing Irons', '1D4 M.D. as a Vibro-Blade weapon only, +4D6 M.D. explosive damage.', 1, '300 feet (91.5 m).', 'Each throw of one or two blades counts as one melee attack.', 'Three in each leg, plus an additional 6-12 usually carried hooked inside the long vest. The compartments are printed as located in the hips.', NULL, 'Each hip compartment holds three crescent shaped throwing irons, set to explode on contact, after a three second delay, or on a detonation signal from the transmitter on the left wrist.'),
  ('ab-830-assault-geo-borg', 5, 'Bionic Strength & Damage', '2D6+8 S.D.C. damage, or 1D4 M.D. with a power punch or kick (counts as two melee attacks).', 1, NULL, NULL, NULL, NULL, 'Bionic P.S. of 30. Printed in the statistical data, not in the numbered list; the ordinal follows the list''s last number.'),
  ('ab-955-lion-geo-borg', 1, 'Concealed Forehead Lasers (2)', '2D6 M.D. per single blast, 4D6 M.D. if both are fired simultaneously at the same target.', 1, '1000 feet (305 m).', 'Each individual or dual blast counts as one melee attack.', 'Effectively unlimited, tied to the ''Borg''s power supply.', NULL, 'The pair of small gem-like items in the forehead between the eyes.'),
  ('ab-955-lion-geo-borg', 2, 'Concealed Pair of Extendible Arms (2)', NULL, 0, 'Reach: 3.5 feet (0.1 m), as printed.', NULL, NULL, NULL, 'Not a weapon in itself: a pair of light mechanical arms that extend from the chest to manipulate machines, use weapons and even drive a car (at a -25% skill penalty). Arm stats: P.S. 10, P.P. 10. They can hold any light Geofront weapon or tool, limited by weight and size.'),
  ('ab-955-lion-geo-borg', 5, 'Bionic Strength & Damage', '2D6+22 S.D.C. damage from a blunt pawing strike, 3D4 M.D. with a blunt power punch (counts as two attacks), 3D6+3 M.D. for Vibro-Claw strike kick, 3D6 M.D. from bite attack.', 1, NULL, NULL, NULL, NULL, 'Bionic P.S. of 44. Printed in the statistical data, not in the numbered list; the ordinal follows the list''s last number.');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 16 juggernauts and bodies are in' AS assertion, count(*) AS got, 16 AS want
  FROM vehicles WHERE slug IN ('iron-juggernaut-blazing', 'iron-juggernaut-earthwake', 'iron-juggernaut-fury', 'iron-juggernaut-iron-dragonfly', 'iron-juggernaut-sea-viper', 'iron-juggernaut-thundering', 'iron-juggernaut-warhawk', 'iron-juggernaut-wing-blade', 'iron-juggernaut-millipede', 'at-c8000-wing-blade-cyborg', 'at-c9000-tsunami-cyborg', 'at-c10000-imperial-dragon-cyborg', 'at-c12000-flame-cloud-cyborg', 'db-800-demon-eater-cyborg', 'ab-830-assault-geo-borg', 'ab-955-lion-geo-borg');
SELECT 'their 79 locations are in' AS assertion, count(*) AS got, 79 AS want
  FROM vehicle_locations WHERE vehicle_slug IN ('iron-juggernaut-blazing', 'iron-juggernaut-earthwake', 'iron-juggernaut-fury', 'iron-juggernaut-iron-dragonfly', 'iron-juggernaut-sea-viper', 'iron-juggernaut-thundering', 'iron-juggernaut-warhawk', 'iron-juggernaut-wing-blade', 'iron-juggernaut-millipede', 'at-c8000-wing-blade-cyborg', 'at-c9000-tsunami-cyborg', 'at-c10000-imperial-dragon-cyborg', 'at-c12000-flame-cloud-cyborg', 'db-800-demon-eater-cyborg', 'ab-830-assault-geo-borg', 'ab-955-lion-geo-borg');
SELECT 'their 71 weapon entries are in' AS assertion, count(*) AS got, 71 AS want
  FROM vehicle_weapons WHERE vehicle_slug IN ('iron-juggernaut-blazing', 'iron-juggernaut-earthwake', 'iron-juggernaut-fury', 'iron-juggernaut-iron-dragonfly', 'iron-juggernaut-sea-viper', 'iron-juggernaut-thundering', 'iron-juggernaut-warhawk', 'iron-juggernaut-wing-blade', 'iron-juggernaut-millipede', 'at-c8000-wing-blade-cyborg', 'at-c9000-tsunami-cyborg', 'at-c10000-imperial-dragon-cyborg', 'at-c12000-flame-cloud-cyborg', 'db-800-demon-eater-cyborg', 'ab-830-assault-geo-borg', 'ab-955-lion-geo-borg');
SELECT 'each main body location equals mdc_main_body' AS assertion, count(*) AS got, 0 AS want
  FROM vehicles v JOIN vehicle_locations l ON l.vehicle_slug = v.slug AND l.location = 'Main Body'
  WHERE v.slug IN ('iron-juggernaut-blazing', 'iron-juggernaut-earthwake', 'iron-juggernaut-fury', 'iron-juggernaut-iron-dragonfly', 'iron-juggernaut-sea-viper', 'iron-juggernaut-thundering', 'iron-juggernaut-warhawk', 'iron-juggernaut-wing-blade', 'iron-juggernaut-millipede', 'at-c8000-wing-blade-cyborg', 'at-c9000-tsunami-cyborg', 'at-c10000-imperial-dragon-cyborg', 'at-c12000-flame-cloud-cyborg', 'db-800-demon-eater-cyborg', 'ab-830-assault-geo-borg', 'ab-955-lion-geo-borg') AND l.mdc <> v.mdc_main_body;

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('~085-iron-juggernauts-and-cyborg-bodies.sql');
