-- Book of Magic: herb magic, Herbs of Legend and corrupted Millennium weapons (printed 279-294)
-- 97 gear rows.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/~110-book-of-magic-herbs-and-millennium-weapons.sql
--
-- Written by scripts/rows-sql.mjs from 1 worker file(s). Every value is
-- printable ASCII and every row cites its book. Rows are keyed on their
-- portable identity, never an id; a row already held is left as it is.

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book, vehicle_slug) VALUES
  ('herb-alder-leaf', 'Alder Leaf (Herb Magic)', 'rifts', 'magic', NULL, 10000, '10,000 credits per leaf.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Enchanted alder leaf. Burning three summons a Lesser Air Elemental. 20 P.P.E. per leaf to enchant.', 'Rifts Book of Magic p.279-280', NULL),
  ('herb-alder-wand', 'Alder Wand (Herb Magic)', 'rifts', 'magic', NULL, 600000, '600,000 credits and up.', NULL, 0, NULL, NULL, NULL, NULL, 20, NULL, 'Druid-made wand that commands the Lesser Air Elemental summoned with alder leaves (one at a time) and holds Lesser Air Elementals at bay; useless against Greater Air Elementals. 450 P.P.E. to enchant.', 'Rifts Book of Magic p.279-280', NULL),
  ('herb-amaranth-potion-of-youth', 'Amaranth Potion of Youth', 'rifts', 'magic', NULL, 450000, '450,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drinker looks 4D4 years younger, hair and color restored, feels strong; +2 to save vs poison, disease and magic illness, +20% vs coma/death. Lasts three months. Addictive: afterwards the user feels 4D4 years older and tires easily. Doses do not stack. 500 P.P.E. per dose.', 'Rifts Book of Magic p.280', NULL),
  ('herb-ash-leaf-compress', 'Ash Leaf Compress (Herb Magic)', 'rifts', 'magic', NULL, 5000, '5,000 credits per leaf.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Enchanted ash leaf used as a compress on blisters and open sores: restores 1D4 Hit Points or S.D.C. One leaf works three times. 15 P.P.E. per leaf.', 'Rifts Book of Magic p.280', NULL),
  ('herb-ash-healing-wand', 'Ash Healing Wand (Herb Magic)', 'rifts', 'magic', NULL, 350000, '350,000 credits and up.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Wand of ash that heals 1D6 Hit Points or S.D.C., three times per day. 350 P.P.E. to enchant the wand or staff.', 'Rifts Book of Magic p.280', NULL),
  ('herb-rowan-bark-pinch', 'Rowan Bark, Pinch (Herb Magic)', 'rifts', 'magic', NULL, 100, '100 credits for a pinch.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Enchanted rowan (mountain ash) bark, chewed or powdered and eaten: stops internal bleeding and restores 1D6 Hit Points or S.D.C. 750 P.P.E. enchants up to five pounds (2.3 kg) of bark.', 'Rifts Book of Magic p.280', NULL),
  ('herb-rowan-tea-or-potion', 'Rowan Tea or Potion (Herb Magic)', 'rifts', 'magic', NULL, 30000, '30,000 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea or potion of enchanted rowan bark: regrows small missing parts such as fingers, toes, ears and nose and restores 2D6 Hit Points or S.D.C.', 'Rifts Book of Magic p.280', NULL),
  ('herb-rowan-salve', 'Rowan Salve (Herb Magic)', 'rifts', 'magic', NULL, 100000, '100,000 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Salve of enchanted rowan bark: applied within 15 minutes it rejoins a severed limb of any size to the body.', 'Rifts Book of Magic p.280', NULL),
  ('herb-belladonna-paralysis-potion', 'Belladonna Paralysis Potion', 'rifts', 'magic', NULL, 6000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Paralysis as the spell, lasting 2D4 minutes. 30 P.P.E. per potion.', 'Rifts Book of Magic p.280', NULL),
  ('herb-belladonna-mega-damage-poison', 'Belladonna Mega-Damage Poison', 'rifts', 'magic', NULL, 15000, NULL, '2D4x10 M.D.', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'Magic poison that harms Mega-Damage creatures: temporary paralysis and 2D4x10 M.D. Lasts 1D6 minutes. 55 P.P.E. per potion.', 'Rifts Book of Magic p.280', NULL),
  ('herb-blackthorn-berries-or-potion', 'Blackthorn Berries or Potion (Herb Magic)', 'rifts', 'magic', NULL, 500, '500 credits per three berries or one potion.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Three enchanted sloe berries eaten, or one potion: +2 to save vs magic and psionic attacks from evil beings and +2 to save vs Horror Factor for 20 minutes. 15 P.P.E. per berry.', 'Rifts Book of Magic p.280', NULL),
  ('herb-black-hellebore-incense-leaf', 'Black Hellebore Incense Leaf', 'rifts', 'magic', NULL, 30, '30 credits a leaf.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Dried enchanted leaf burnt as incense for a calm train of thought, used for meditation and divination. 15 P.P.E.', 'Rifts Book of Magic p.280', NULL),
  ('herb-black-hellebore-psionic-protection-potion', 'Black Hellebore Potion of Psionic Protection', 'rifts', 'magic', NULL, 10000, '10,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Potion or tea: +6 to save vs chemical mind control and hallucinogenics, +5 vs psionic attack, +2 vs possession, for 15 minutes. 65 P.P.E.', 'Rifts Book of Magic p.280', NULL),
  ('herb-black-hellebore-cure-insanity-curse-potion', 'Black Hellebore Potion: Cure Curse of Insanity', 'rifts', 'magic', NULL, 40000, '40,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Potion that cures magic curses of insanity, 1-60% chance of success. 115 P.P.E.', 'Rifts Book of Magic p.280', NULL),
  ('herb-carline-thistle-storm-wand', 'Carline Thistle Storm Wand', 'rifts', 'magic', NULL, 12000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Wand or walking stick with three flowers that stand open in fair weather and close fully when a storm is 4D4 minutes away. 175 P.P.E. to create.', 'Rifts Book of Magic p.280', NULL),
  ('herb-castor-potion-see-the-invisible', 'Castor Bean Potion: See the Invisible', 'rifts', 'magic', NULL, 3000, 'Around 3,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Potion of enchanted castor beans to see the invisible, typically for ten minutes. 100 P.P.E.', 'Rifts Book of Magic p.280', NULL),
  ('herb-castor-potion-negate-magic-blindness', 'Castor Bean Potion: Negate Magic Blindness', 'rifts', 'magic', NULL, 3000, 'Around 3,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Potion of enchanted castor beans that negates blindness caused by magic. 100 P.P.E.', 'Rifts Book of Magic p.280', NULL),
  ('herb-castor-eye-lotion', 'Castor Eye Lotion (Herb Magic)', 'rifts', 'magic', NULL, 3000, 'Around 3,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Magic lotion that washes and heals eyes harmed by poison, acid or pollutants. 100 P.P.E.', 'Rifts Book of Magic p.280', NULL),
  ('herb-catnip-flower', 'Catnip Flower (Herb Magic)', 'rifts', 'magic', NULL, 1000, '1,000 credits per flower.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Chewed: +1 on initiative and +2 to strike, but -1 to parry and dodge. Dried and burnt as incense it wards off wild felines and the Kinnie Ger faerie folk. 50 P.P.E. per flowering stem.', 'Rifts Book of Magic p.280-281', NULL),
  ('herb-cedar-staff', 'Cedar Staff (Herb Magic)', 'rifts', 'magic', NULL, 200000, '200,000 credits and up.', '2D6 S.D.C.; 2D6 M.D. against energy beings', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'While one end touches the ground the holder is impervious to lightning and electricity and takes half damage from other energy blasts. 350 P.P.E. to create.', 'Rifts Book of Magic p.281', NULL),
  ('herb-red-clover-ointment', 'Red Clover Ointment (Herb Magic)', 'rifts', 'magic', NULL, 300, '300 credits an ounce.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Magic ointment that heals burns, rashes and itchy bites, restoring 1D4 S.D.C. Five buds make three ounces; 10 P.P.E. per flower.', 'Rifts Book of Magic p.281', NULL),
  ('herb-red-clover-flower', 'Red Clover Flower (Herb Magic)', 'rifts', 'magic', NULL, 100, '100 credits per flower.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Magic food: three flowers eaten give the nourishment of a full meal. 10 P.P.E. per flower.', 'Rifts Book of Magic p.281', NULL),
  ('herb-white-clover-three-leaf-charm', 'Three Leaf Clover Charm (Herb Magic)', 'rifts', 'magic', NULL, 30000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Lucky charm against witches: owner is impervious to possession and +1 to save vs any spell cast by a witch. 210 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-white-clover-four-leaf-charm', 'Four Leaf Clover Charm (Herb Magic)', 'rifts', 'magic', NULL, 50000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Charm: owner sees the invisible, is impervious to magic curses and illnesses, and is +1 to save vs possession, witch and Faerie magic. 290 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-dwarf-elder-sobriety-potion', 'Dwarf Elder Sobriety Potion', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Makes a drunk instantly sober and keeps a sober drinker from getting drunk for one hour. One sprig per potion, 25 P.P.E. per sprig.', 'Rifts Book of Magic p.281', NULL),
  ('herb-black-elder-potion-minor-curse', 'Black Elder Potion: Minor Curse', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Foul potion similar to the Minor Curse spell; lasts 1D6 hours. One sprig per potion, 25 P.P.E. per sprig.', 'Rifts Book of Magic p.281', NULL),
  ('herb-black-elder-potion-sickness', 'Black Elder Potion: Sickness', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Foul potion similar to the Sickness spell; lasts 1D6 hours. One sprig per potion, 25 P.P.E. per sprig.', 'Rifts Book of Magic p.281', NULL),
  ('herb-black-elder-potion-luck-curse', 'Black Elder Potion: Luck Curse', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Foul potion similar to the Luck Curse spell; lasts 1D6 hours. One sprig per potion, 25 P.P.E. per sprig.', 'Rifts Book of Magic p.281', NULL),
  ('herb-ergot-hallucination-potion', 'Ergot Hallucination Potion', 'rifts', 'magic', NULL, 500, '500 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drinker hallucinates as the spell and fights illusionary monsters for 3D4 minutes. 100 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-ergot-potion-see-through-illusions', 'Ergot Potion: See Through Illusions', 'rifts', 'magic', NULL, 20000, '20,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drinker is unaffected by illusionary magic for 2D4 minutes. 100 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-ergot-minds-eye-potion', 'Ergot Mind''s Eye Potion', 'rifts', 'magic', NULL, 20000, '20,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Gives See Aura, See the Invisible, Sixth Sense and Clairvoyance for 2D4 melees. 100 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-foxglove-negate-poison-potion', 'Foxglove Negate Poison Potion', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Potion that negates poison. One sprig per potion, 35 P.P.E. per sprig.', 'Rifts Book of Magic p.281', NULL),
  ('herb-ginseng-potion-impervious-to-fatigue', 'Ginseng Potion: Impervious to Fatigue', 'rifts', 'magic', NULL, 1000, '1,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drinker works for 1D4+1 hours without fatigue. 60 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-ginseng-potion-super-speed', 'Ginseng Potion: Super-Speed', 'rifts', 'magic', NULL, 4000, '4,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Running speed +40, +1 on initiative and +2 to dodge, for ten minutes per level of the potion maker. 60 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-holy-thistle-leaf', 'Holy Thistle Leaf (Herb Magic)', 'rifts', 'magic', NULL, 100, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Chewed, or brewed as tea: removes food poisoning, cramps and hangovers. 20 P.P.E. per leaf.', 'Rifts Book of Magic p.281', NULL),
  ('herb-holy-thistle-potion-cure-magic-disease', 'Holy Thistle Potion: Cure Magic and Alien Disease', 'rifts', 'magic', NULL, 30000, '30,000+ credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Cures magic sicknesses and diseases and alien diseases. 200 P.P.E. per dose.', 'Rifts Book of Magic p.281', NULL),
  ('herb-holy-thistle-potion-supernatural-strength', 'Holy Thistle Potion: Supernatural Strength', 'rifts', 'magic', NULL, 30000, '30,000+ credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drinker''s own P.S. becomes supernatural, inflicting Mega-Damage, for 4D4 minutes. 140 P.P.E. per dose.', 'Rifts Book of Magic p.281', NULL),
  ('herb-horsetail-potion-impervious-to-gases', 'Horsetail Potion: Impervious to Gases', 'rifts', 'magic', NULL, 5000, '5,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Impervious to magic and toxic gases of all kinds for 20 minutes. 100 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-horsetail-potion-breathe-without-air', 'Horsetail Potion: Breathe Without Air', 'rifts', 'magic', NULL, 5000, '5,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Breathe without air for 20 minutes. 100 P.P.E.', 'Rifts Book of Magic p.281', NULL),
  ('herb-jimsonweed-leaf', 'Jimsonweed Leaf (Herb Magic)', 'rifts', 'magic', NULL, 500, '500 credits per leaf.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Smoked, it keeps Faerie Folk away and gives +1 to save vs Faerie Magic. Chewed, the user sees the invisible while it is in the mouth (+1 vs Faerie Magic), but is nauseous after 10 minutes and poisoned after 20 (2D4x10 damage, paralysis 1D4 minutes; attacks, bonuses and speed halved for 3D6 hours). 15 P.P.E. per leaf.', 'Rifts Book of Magic p.281-282', NULL);

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book, vehicle_slug) VALUES
  ('herb-jimsonweed-potion-negate-faerie-food', 'Jimsonweed Potion: Negate Faerie Food', 'rifts', 'magic', NULL, 25000, '25,000 to 50,000 credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Negates or reverses the effects of Faerie foods and drinks. 136 P.P.E. per potion.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mandrake-root-bit', 'Mandrake Root, Bit (Herb Magic)', 'rifts', 'magic', NULL, 500, '500 credits per bit; a root divides into 10 bits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Chewed, or brewed as tea: dowsing or a glimpse of the future, with the narcotic penalties of the plant (no initiative, -2 to strike, parry and dodge, attacks per melee halved). 50 P.P.E. per root.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mandrake-potion-befuddle', 'Mandrake Potion: Befuddle', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Befuddle as the spell, for 2D4 minutes. 50 P.P.E. per potion.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mandrake-potion-empathy', 'Mandrake Potion: Empathy', 'rifts', 'magic', NULL, 5000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Empathy as the psionic power, for 3D4 minutes. 40 P.P.E. per dose.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mandrake-potion-telepathy', 'Mandrake Potion: Telepathy', 'rifts', 'magic', NULL, 10000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Telepathy as the psionic power, for 3D4 minutes. 50 P.P.E. per dose.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mandrake-bio-manipulation-voodoo-doll', 'Bio-Manipulation Voodoo Doll (Mandrake)', 'rifts', 'magic', NULL, 150000, NULL, NULL, 0, '100 ft (30.5 m), line of sight', NULL, NULL, NULL, NULL, NULL, 'A whole mandrake root made into a magic weapon. The user nibbles the root and concentrates on one victim in line of sight to inflict any one Bio-Manipulation affliction per melee, kept up or changed each melee. One victim at a time. 300 P.P.E. to create.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mistletoe-potion-charismatic-aura', 'Mistletoe Potion: Charismatic Aura', 'rifts', 'magic', NULL, 50000, '50,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Charismatic Aura, equal to a 5th level spell. 75 P.P.E. per dose.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mistletoe-potion-impervious-to-fire', 'Mistletoe Potion: Impervious to Fire', 'rifts', 'magic', NULL, 50000, '50,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Impervious to Fire, equal to a 5th level spell. 75 P.P.E. per dose.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mistletoe-potion-float-in-air', 'Mistletoe Potion: Float in Air', 'rifts', 'magic', NULL, 50000, '50,000 credits per dose.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Float in Air, equal to a 5th level spell. 75 P.P.E. per dose.', 'Rifts Book of Magic p.282', NULL),
  ('herb-mistletoe-amulet', 'Mistletoe Amulet (Herb Magic)', 'rifts', 'magic', NULL, 20000, '20,000+ credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A preserved sprig that serves as an amulet, as the Amulet invocation. 290 P.P.E. each.', 'Rifts Book of Magic p.282', NULL),
  ('herb-holy-water-vial', 'Holy Water, Vial (Herb Magic, Oak or Rue)', 'rifts', 'magic', NULL, 100, '100 credits per vial.', '3D6 Hit Points/M.D. to vampires and other demons', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Holy water made with enchanted oak or rue. Burns vampires and other demons like acid for 3D6 Hit Points/M.D.; poured in a circle it bars vampires and some other demons from entering. 20 P.P.E. per vial. Printed twice, under Oak and under Rue, with the same figures.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-magic-acorn', 'Magic Acorn (Oak, Herb Magic)', 'rifts', 'magic', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'One acorn gives the nourishment of a full meal. 20 P.P.E. per acorn.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-magic-leaf', 'Magic Oak Leaf (Herb Magic)', 'rifts', 'magic', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Eaten or made into a tea or potion: Chameleon as the spell for 10 minutes. 25 P.P.E. per leaf.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-magic-bark', 'Magic Oak Bark (Herb Magic)', 'rifts', 'magic', NULL, 40000, '40,000+ credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'An acorn-sized piece eaten or made into a tea or potion: Armor of Ithan with 60 M.D.C. for 20 minutes. 45 P.P.E. per piece.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-magic-root', 'Magic Oak Root (Herb Magic)', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Eaten or made into a tea or potion: track animals at 88% for one hour. 25 P.P.E. per chunk.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-oracle-tea', 'Oak Oracle Tea (Herb Magic)', 'rifts', 'magic', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea of oak leaf and bark: Oracle as the spell. 70 P.P.E. to make the brew.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-wand-of-dowsing', 'Oak Wand of Dowsing (Herb Magic)', 'rifts', 'magic', NULL, 25000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A Y-shaped branch that locates other oak trees, water and ley lines. 130 P.P.E.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-throwing-stick', 'Magic Oak Throwing Stick (Herb Magic)', 'rifts', 'weapon', NULL, 135000, NULL, '1D6 S.D.C. to mortal foes; 2D6 M.D. to supernatural opponents', 0, 'double the normal range', NULL, NULL, NULL, NULL, NULL, 'Returns when thrown. 330 P.P.E.', 'Rifts Book of Magic p.282', NULL),
  ('herb-oak-staff-of-strength', 'Oak Staff of Strength (Herb Magic)', 'rifts', 'magic', NULL, 220000, NULL, '4D6 S.D.C. to mortal foes; M.D. to supernatural opponents', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A branch that cannot be broken or bent. Owner is +1 to save vs all magic and psionic attacks, +1 to save vs Horror Factor, fatigues at half the usual rate and carries weight as if he had supernatural strength. 670 P.P.E.', 'Rifts Book of Magic p.282', NULL),
  ('herb-rue-sleep-potion', 'Rue Sleep Potion', 'rifts', 'magic', NULL, 5000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Magical Sleep as the spell; sleeps ten minutes per level of the potion maker. 40 P.P.E. per dose.', 'Rifts Book of Magic p.282', NULL),
  ('herb-rue-wand-of-sleep', 'Rue Wand of Sleep', 'rifts', 'magic', NULL, 10000, NULL, NULL, 0, '20 ft (6 m) or by touch', 'three times a day', NULL, NULL, NULL, NULL, 'A preserved sprig of rue fixed to a wand: casts the Sleep spell three times a day. 230 P.P.E. per wand.', 'Rifts Book of Magic p.282', NULL),
  ('herb-rue-anti-magic-wand-or-staff', 'Rue Anti-Magic Wand or Staff', 'rifts', 'magic', NULL, 1000000, 'One million credits.', 'Staff: 2D6 S.D.C. to mortal foes; 2D6 M.D. to creatures of magic', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Holder is +6 to save vs all magic and can cast Dispel Magic Barrier, Negate Magic and Anti-Magic Cloud once per day each, at the level of its creator. 1,930 P.P.E.', 'Rifts Book of Magic p.282', NULL),
  ('herb-solomons-seal-leaf', 'Solomon''s Seal Leaf (Herb Magic)', 'rifts', 'magic', NULL, 20000, '20,000 credits per leaf.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Burning three enchanted leaves summons a Lesser Elemental of earth, water, fire or air. 50 P.P.E. per leaf.', 'Rifts Book of Magic p.282-283', NULL),
  ('herb-solomons-seal-sprig-of-elemental-control', 'Solomon''s Seal Sprig of Elemental Control', 'rifts', 'magic', NULL, 900000, '900,000 credits and up.', NULL, 0, NULL, NULL, NULL, NULL, 9, NULL, 'Commands the Lesser Elemental summoned by the leaves (one at a time) and holds Lesser Elementals at bay; useless against Greater Elementals. 750 P.P.E. to enchant.', 'Rifts Book of Magic p.282-283', NULL),
  ('herb-willow-potion-impervious-to-energy', 'Willow Potion: Impervious to Energy', 'rifts', 'magic', NULL, 20000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Drinker is impervious to energy attacks for five minutes per level of the maker. 75 P.P.E.', 'Rifts Book of Magic p.283', NULL),
  ('herb-willow-lightning-rod-staff', 'Willow Lightning Rod Staff', 'rifts', 'magic', NULL, 250000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Stuck in the ground it draws all lightning and electrical discharges to itself within a 100 ft (30.5 m) radius; alternately anyone holding it is impervious to electricity. The staff is unharmed by electricity and impervious to all energy attacks. 350 P.P.E.', 'Rifts Book of Magic p.283', NULL),
  ('herb-wormwood-powder-pound', 'Magic Wormwood Powder or Ointment (per pound)', 'rifts', 'magic', NULL, 1000, 'Black Market cost: 1,000 credits a pound.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Keeps away Goblins, ordinary worms and larvae, and Worms of Taut: none can cross a line of it, pass a doorway lined with it, or open a knob or box covered in it. 100 P.P.E. enchants up to 10 pounds (4.5 kg) per level of experience.', 'Rifts Book of Magic p.283', NULL),
  ('brain-tree-oracle-tea-or-potion', 'Brain Tree Oracle Tea or Potion', 'rifts', 'magic', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Oracle as the spell. 70 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('brain-tree-potion-eyes-of-thoth', 'Brain Tree Potion: Eyes of Thoth', 'rifts', 'magic', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Eyes of Thoth, equal to a 10th level spell. 36 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('brain-tree-potion-trance', 'Brain Tree Potion: Trance', 'rifts', 'magic', NULL, 12000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Trance, equal to a 10th level spell. 64 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('brain-tree-staff-of-spirits', 'Staff of Spirits (Brain Tree)', 'rifts', 'magic', NULL, 1000000, 'A million+ credits.', NULL, 0, NULL, 'each spell three times per 24 hours', NULL, NULL, NULL, NULL, 'A wood or metal staff set with a small brain tree lobe. Casts Commune with Spirits, Control Entity, Banishment (entity), Turn Dead and Exorcism at 10th level. 490 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('brain-tree-electrokinesis-rod', 'Electrokinesis Rod (Brain Tree)', 'rifts', 'magic', NULL, 400000, '400,000+ credits.', NULL, 0, NULL, '100 I.S.P., recovers 10 per hour', NULL, NULL, NULL, NULL, 'Usually a scepter-style wand; may be a staff or a helmet. Gives the user Electrokinesis as a 10th level Mind Melter with 100 I.S.P. of its own, recovering 10 I.S.P. per hour. 275 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('brain-tree-crystal-ball', 'Crystal Ball (Brain Tree)', 'rifts', 'magic', NULL, 250000000, '250 million credits and higher.', NULL, 0, '300 miles (480 km)', NULL, NULL, NULL, NULL, NULL, 'Super rare. The user sees and hears what a person or animal he has met and knows is doing, for 5 minutes per level of the viewer. 1,234 P.P.E. for one ball.', 'Rifts Book of Magic p.284', NULL),
  ('cobra-vine-salve-cure-vampires-bite', 'Cobra Vine Salve: Cure a Vampire''s Bite', 'rifts', 'magic', NULL, 300000, '300,000+ credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Salve from the plant''s sack-like root: cures any infection in a vampire''s bite and dispels the vampire''s control over the victim. 380 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('cobra-vine-blood-tea', 'Cobra Vine Blood Tea', 'rifts', 'magic', NULL, 450000, '450,000+ credits.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea or tonic from the blood stored in the plant''s root: cures anemia, leukemia, bone cancer, blood poisoning and other diseases of the blood. 550 P.P.E.', 'Rifts Book of Magic p.284', NULL),
  ('dagdas-scepter-oracle', 'Dagda''s Scepter Oracle Tea, Potion or Snuff', 'rifts', 'magic', NULL, 2000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Oracle as the spell. 70 P.P.E.', 'Rifts Book of Magic p.284-285', NULL),
  ('dagdas-scepter-sense-magic-and-evil', 'Dagda''s Scepter: Sense Magic and Evil', 'rifts', 'magic', NULL, 200, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea, potion or snuff, equal to an 8th level spell. 25 P.P.E.', 'Rifts Book of Magic p.284-285', NULL),
  ('dagdas-scepter-commune-with-spirits', 'Dagda''s Scepter: Commune with Spirits', 'rifts', 'magic', NULL, 1000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea, potion or snuff, equal to an 8th level spell. 50 P.P.E.', 'Rifts Book of Magic p.284-285', NULL),
  ('dagdas-scepter-impervious-to-fire', 'Dagda''s Scepter: Impervious to Fire', 'rifts', 'magic', NULL, 3000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea or potion, equal to an 8th level spell. 50 P.P.E.', 'Rifts Book of Magic p.284-285', NULL),
  ('dagdas-scepter-resist-fire', 'Dagda''s Scepter: Resist Fire', 'rifts', 'magic', NULL, 500, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea or potion, equal to an 8th level spell. 20 P.P.E.', 'Rifts Book of Magic p.284-285', NULL);

INSERT OR IGNORE INTO gear (slug, name, system, category, weight_lbs, cost, cost_note, damage, is_mega_damage, range, payload, rate_of_fire, ar, sdc, mdc, description, source_book, vehicle_slug) VALUES
  ('dagdas-scepter-invulnerability', 'Dagda''s Scepter: Invulnerability', 'rifts', 'magic', NULL, 10000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Tea or potion, equal to an 8th level spell. 80 P.P.E.', 'Rifts Book of Magic p.284-285', NULL),
  ('dagdas-scepter-healing-ointment', 'Dagda''s Scepter Healing Ointment', 'rifts', 'magic', NULL, 5000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Heals burns, restoring 4D6 Hit Points or S.D.C., or cuts and open sores, restoring 1D6 S.D.C.; reduces scarring. 80 P.P.E.', 'Rifts Book of Magic p.284-285', NULL),
  ('faeries-cauldron-bowl-ppe-battery', 'Faeries'' Cauldron Bowl (P.P.E. Battery)', 'rifts', 'magic', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'A bowl broken off the alien mushroom at the stem stays fresh and holds magic energy that can be drawn like a talisman: a small bowl 2D6 P.P.E., a large bowl or the root bulb 5D6 P.P.E. Once drained it shrivels and spoils; spoiled mushroom is poisonous (cramps, vomiting and vertigo for 3D6 hours, bonuses and speed halved, skills -20%). No price printed.', 'Rifts Book of Magic p.285', NULL),
  ('faeries-cauldron-blood-toxin', 'Faeries'' Cauldron Blood Toxin', 'rifts', 'magic', NULL, 45000, NULL, '2D4x100 Hit Points/S.D.C. to humanoids; 2D4x10 M.D. to Mega-Damage creatures', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Humanoid blood left in a cauldron becomes a deadly toxin that must be ingested: 2D4x100 Hit Points and S.D.C. to humanoids, 2D4x10 M.D. to Mega-Damage creatures.', 'Rifts Book of Magic p.285', NULL),
  ('faeries-cauldron-faerie-blood-potion', 'Faeries'' Cauldron Faerie Blood Potion', 'rifts', 'magic', NULL, 200000, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Faerie blood in a cauldron becomes a potion: the drinker shrinks to 12 inches (0.3 m), sprouts butterfly wings, flies at 45 mph (72 km), prowls at 55%, sees the invisible, and is +3 to save vs magic and +6 vs Faerie Magic, but all attributes, combat bonuses, S.D.C./M.D.C. and skills are halved. Lasts 2D4 hours and cannot be negated.', 'Rifts Book of Magic p.285', NULL),
  ('faeries-cauldron-dragon-blood-metamorphosis-potion', 'Faeries'' Cauldron Dragon Blood Potion of Metamorphosis', 'rifts', 'magic', NULL, 150000, '150,000+ credits per potion.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Dragon''s blood in a cauldron becomes a potion of metamorphosis into any living creature (any of the metamorphosis spells, plant included). Lasts 2D4 hours and cannot be canceled.', 'Rifts Book of Magic p.285', NULL),
  ('faeries-cauldron-potion-water-to-wine', 'Faeries'' Cauldron Potion: Water to Wine', 'rifts', 'magic', NULL, 350, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Poured into one to ten gallons (3.8 to 38 liters) of water it makes good wine. Equal to a 7th level spell. 25 P.P.E.', 'Rifts Book of Magic p.286', NULL),
  ('faeries-cauldron-potion-spoil-food-or-water', 'Faeries'' Cauldron Potion: Spoil Food or Water', 'rifts', 'magic', NULL, 500, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Spoils one to ten gallons (3.8 to 38 liters) of drink or up to 70 pounds (31 kg) of food. Equal to a 7th level spell. 35 P.P.E.', 'Rifts Book of Magic p.286', NULL),
  ('faeries-cauldron-potion-negate-poison', 'Faeries'' Cauldron Potion: Negate Poison', 'rifts', 'magic', NULL, 50000, '50,000+ credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Negates poison, M.D. poisons included. Equal to a 7th level spell. 30 P.P.E.', 'Rifts Book of Magic p.286', NULL),
  ('faeries-cauldron-potion-metamorphosis', 'Faeries'' Cauldron Potion: Metamorphosis (any type)', 'rifts', 'magic', NULL, 250000, '250,000+ credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Any one type of metamorphosis potion, equal to a 7th level spell. 85 P.P.E. each.', 'Rifts Book of Magic p.286', NULL),
  ('faeries-cauldron-potion-petrification', 'Faeries'' Cauldron Potion: Petrification', 'rifts', 'magic', NULL, 750000, '750,000+ credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'The drinker turns to stone, permanently unless stone to flesh magic reverses it. May be hidden in under eight ounces (0.2 liters) of another drink. 213 P.P.E.', 'Rifts Book of Magic p.286', NULL),
  ('faeries-cauldron-potion-stone-to-flesh', 'Faeries'' Cauldron Potion: Stone to Flesh', 'rifts', 'magic', NULL, 500000, '500,000+ credits each.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Poured on the head of a petrified victim it restores him; drunk beforehand it makes the drinker impervious to petrification for 20 minutes. 113 P.P.E.', 'Rifts Book of Magic p.286', NULL),
  ('snapper-heart-root', 'Snapper Heart Root', 'rifts', 'magic', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Two to four ounces of the alien plant''s root act as a strong stimulant and mild hallucinogenic: +2 on initiative, +1 to parry and dodge, +2 to P.S. and Spd. for about 2D4x10 minutes, with reckless overconfidence. Afterwards speed is halved, combat bonuses -1 and skills -20% for 1D4 hours. Addictive. As a tea, potion or snuff the duration is half. No price printed.', 'Rifts Book of Magic p.286', NULL),
  ('corrupt-executioners-blade', 'Corrupt Executioner''s Blade', 'rifts', 'weapon', 22, 2000000, 'Two to four million credits is average; has sold for twice as much.', '5D6 M.D.; double with Death Strike', 1, NULL, 'each spell four times per 24 hours', NULL, NULL, NULL, NULL, 'A double-bladed axe of enchanted black metal with a corrupted Millennium Staff as its handle. 2D4x100 M.D.C., damaged only when targeted, regenerating 1D4x10 per 24 hours; stores 2D4x10 P.P.E. Death Strike: for six minutes anyone struck must save vs magic (14 or higher) or take double damage. Strength of the Dead: plunged into a slain creature it gives the wielder half the S.D.C. and Hit Points (or M.D.C.) the creature had, for 12 minutes. Both at 6th level, no P.P.E. cost.', 'Rifts Book of Magic p.293', NULL),
  ('corrupt-mantle-of-power', 'Corrupt Mantle of Power', 'rifts', 'armor', 7, 1000000, 'One to two million credits; can sell for as high as three million.', NULL, 1, NULL, 'each spell three times per 24 hours', NULL, NULL, NULL, 100, 'Cloak and hood made from a Millennium Tree leaf, dyed red or black and enhanced by Splugorth Bio-Wizardry; worn as enchanted body armor. Casts at 4th level, no P.P.E. cost: Aura of Power (seems three levels higher and 50% stronger, +1D4+2 M.A., four minutes), Aura of Death (seems undead, two minutes), Charismatic Aura (+8 P.B.; trust, or Horror Factor 13, or 01-80% to be believed) and Mask of Deceit (another face while the hood is up and two minutes after). Saving throw 12 or higher.', 'Rifts Book of Magic p.293-294', NULL),
  ('corrupt-millennium-slayer', 'Corrupt Millennium Slayer', 'rifts', 'weapon', 10, 2000000, 'Two million credits and up; rare.', '4D6 M.D.; double to plant life; triple to Millennium Trees and items made from them', 1, NULL, NULL, NULL, NULL, NULL, NULL, 'A sword with a corrupted Millennium Wand in its hilt. 1D4x100 M.D.C., damaged only when targeted, regenerating 3D6 per 24 hours. Wielder is +2 to save vs the magic of a Millennium staff or wand; Horror Factor 15 to Millennium Druids. The wand cannot be returned to a tree unless burnt to ash.', 'Rifts Book of Magic p.294', NULL),
  ('corrupt-serpent-slayer', 'Corrupt Serpent-Slayer', 'rifts', 'weapon', 10, 2000000, 'Average 2D4 million credits; Dragon Juicers and the Society of Sages will pay 16-20 million. Very rare; officially outlawed in Atlantis.', '4D6 M.D.; double to dragons and other supernatural serpents', 1, 'thrown 1200 ft (366 m)', NULL, 'Equal to the wielder''s hand to hand attacks', NULL, NULL, NULL, 'A spear, javelin or trident made from a Millennium Staff of the Serpent. 2D4x100 M.D.C., damaged only when targeted, regenerating 1D4x10 per 24 hours. +1 to strike when thrown; a throw that misses or hits a non-serpent returns to hand (two melee actions). A natural 20 stuns a serpent, costing it two melee actions. Wielder is impervious to dragon fire and all breath attacks. Left impaled, a dragon cannot touch it to pull it out, and its teleports cost it 4D6 M.D. at -30%.', 'Rifts Book of Magic p.294', NULL);

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'gear rows, part 1: 40 are in' AS assertion, count(*) AS got, 40 AS want
  FROM gear WHERE slug IN ('herb-alder-leaf', 'herb-alder-wand', 'herb-amaranth-potion-of-youth', 'herb-ash-leaf-compress', 'herb-ash-healing-wand', 'herb-rowan-bark-pinch', 'herb-rowan-tea-or-potion', 'herb-rowan-salve', 'herb-belladonna-paralysis-potion', 'herb-belladonna-mega-damage-poison', 'herb-blackthorn-berries-or-potion', 'herb-black-hellebore-incense-leaf', 'herb-black-hellebore-psionic-protection-potion', 'herb-black-hellebore-cure-insanity-curse-potion', 'herb-carline-thistle-storm-wand', 'herb-castor-potion-see-the-invisible', 'herb-castor-potion-negate-magic-blindness', 'herb-castor-eye-lotion', 'herb-catnip-flower', 'herb-cedar-staff', 'herb-red-clover-ointment', 'herb-red-clover-flower', 'herb-white-clover-three-leaf-charm', 'herb-white-clover-four-leaf-charm', 'herb-dwarf-elder-sobriety-potion', 'herb-black-elder-potion-minor-curse', 'herb-black-elder-potion-sickness', 'herb-black-elder-potion-luck-curse', 'herb-ergot-hallucination-potion', 'herb-ergot-potion-see-through-illusions', 'herb-ergot-minds-eye-potion', 'herb-foxglove-negate-poison-potion', 'herb-ginseng-potion-impervious-to-fatigue', 'herb-ginseng-potion-super-speed', 'herb-holy-thistle-leaf', 'herb-holy-thistle-potion-cure-magic-disease', 'herb-holy-thistle-potion-supernatural-strength', 'herb-horsetail-potion-impervious-to-gases', 'herb-horsetail-potion-breathe-without-air', 'herb-jimsonweed-leaf') AND source_book IS NOT NULL;
SELECT 'gear rows, part 2: 40 are in' AS assertion, count(*) AS got, 40 AS want
  FROM gear WHERE slug IN ('herb-jimsonweed-potion-negate-faerie-food', 'herb-mandrake-root-bit', 'herb-mandrake-potion-befuddle', 'herb-mandrake-potion-empathy', 'herb-mandrake-potion-telepathy', 'herb-mandrake-bio-manipulation-voodoo-doll', 'herb-mistletoe-potion-charismatic-aura', 'herb-mistletoe-potion-impervious-to-fire', 'herb-mistletoe-potion-float-in-air', 'herb-mistletoe-amulet', 'herb-holy-water-vial', 'herb-oak-magic-acorn', 'herb-oak-magic-leaf', 'herb-oak-magic-bark', 'herb-oak-magic-root', 'herb-oak-oracle-tea', 'herb-oak-wand-of-dowsing', 'herb-oak-throwing-stick', 'herb-oak-staff-of-strength', 'herb-rue-sleep-potion', 'herb-rue-wand-of-sleep', 'herb-rue-anti-magic-wand-or-staff', 'herb-solomons-seal-leaf', 'herb-solomons-seal-sprig-of-elemental-control', 'herb-willow-potion-impervious-to-energy', 'herb-willow-lightning-rod-staff', 'herb-wormwood-powder-pound', 'brain-tree-oracle-tea-or-potion', 'brain-tree-potion-eyes-of-thoth', 'brain-tree-potion-trance', 'brain-tree-staff-of-spirits', 'brain-tree-electrokinesis-rod', 'brain-tree-crystal-ball', 'cobra-vine-salve-cure-vampires-bite', 'cobra-vine-blood-tea', 'dagdas-scepter-oracle', 'dagdas-scepter-sense-magic-and-evil', 'dagdas-scepter-commune-with-spirits', 'dagdas-scepter-impervious-to-fire', 'dagdas-scepter-resist-fire') AND source_book IS NOT NULL;
SELECT 'gear rows, part 3: 17 are in' AS assertion, count(*) AS got, 17 AS want
  FROM gear WHERE slug IN ('dagdas-scepter-invulnerability', 'dagdas-scepter-healing-ointment', 'faeries-cauldron-bowl-ppe-battery', 'faeries-cauldron-blood-toxin', 'faeries-cauldron-faerie-blood-potion', 'faeries-cauldron-dragon-blood-metamorphosis-potion', 'faeries-cauldron-potion-water-to-wine', 'faeries-cauldron-potion-spoil-food-or-water', 'faeries-cauldron-potion-negate-poison', 'faeries-cauldron-potion-metamorphosis', 'faeries-cauldron-potion-petrification', 'faeries-cauldron-potion-stone-to-flesh', 'snapper-heart-root', 'corrupt-executioners-blade', 'corrupt-mantle-of-power', 'corrupt-millennium-slayer', 'corrupt-serpent-slayer') AND source_book IS NOT NULL;

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('~110-book-of-magic-herbs-and-millennium-weapons.sql');
