-- Rifts World Book 32: Lemuria - six symbiotic combat vehicles and the Moai Stone Guardian
-- 7 vehicle rows, with 43 locations and 41 weapon entries.
--
-- One-off data script, run once per environment. NOT a migration - it adds
-- rows, not schema.
--
--   node scripts/d1-apply.mjs --local apps/character-creator/db/~175-lemuria-vehicles.sql
--
-- Written by scripts/vessel-sql.mjs from 1 worker file(s). Every value
-- is printable ASCII, every row cites its book, and a Main Body location
-- agrees with its vehicle's mdc_main_body.

INSERT OR IGNORE INTO vehicles (slug, name, system, vehicle_class, crew, passengers, speed_ground, speed_air, speed_water, dimensions, weight_tons, mdc_main_body, is_mega_damage, ar, cost, cost_note, description, source_book) VALUES
  ('lemurian-sea-dart-interceptor', 'Sea Dart Interceptor', 'rifts', 'Flying Submersible Fighter-Interceptor', 'One. No room for a passenger.', NULL, 'None.', 'Mach 3 (2,310 mph/3,696 km) maximum; hovers and takes off and lands vertically. Within 3 feet (0.9 m) of the ground or water surface: up to Mach 1 (770 mph/1,232 km).', 'Surface 120 mph (192 km); underwater 100 mph (160 km) maximum. Maximum depth 5 miles (8 km).', 'Height 6 feet (1.8 m), width 6.5 feet (2 m), length 11 feet (3.3 m).', '2 tons', 227, 1, NULL, 3000000, '3 million credits to raise the symbiote and prepare the lodestone.', 'One-seat stone air-sub of the Sea Sentinels, flown in ''tridents'' of 3-6; small enough to read as a missile. Like every Lemurian symbiotic vehicle the hull is Stone Magic lodestone and a living Symbiote Conduit is its power source, computer and co-pilot: it links psychically with the pilot, flies alone at 60% with three attacks and no bonuses (an untrained pilot also flies at 60%), locks out strangers and keeps the cabin breathable indefinitely. Pilots use the Symbiote Conduit Combat Vehicle skill. A force field at zero recharges in 3 hours on a ley line, 1.5 hours at a nexus or stone pyramid, or for 2 P.P.E. per M.D.C. point. Losing both rear thrusters cuts speed 60%. Cargo: a pistol, rifle and survival kit. The conduit lives 100 years and must charge 3 hours on a ley line (1 hour at a nexus or pyramid) every seven days, or weapons and torpedo recharging fail and speed drops to 300 mph air, 40 mph surface, 30 mph underwater.', 'Rifts World Book 32: Lemuria p.145-147'),
  ('lemurian-cloud-shell', 'Cloud Shell', 'rifts', 'Flying Submersible Fighter-Interceptor', 'One.', 'Three human-sized passengers behind the pilot, or two in Bio-Armor; cramped on long trips.', 'Not possible.', 'Mach 2 (1,540 mph/2,464 km); hovers and takes off or lands vertically. Within 3 feet (0.9 m) of the ground or water surface: up to 500 mph (800 km).', 'Underwater 100 mph (160 km or 86 knots) maximum. Maximum depth 5 miles (8 km).', 'Height 8 feet (2.4 m), width 10 feet (3 m), length 32 feet (9.8 m).', '12 tons', 300, 1, NULL, 7000000, '7 million credits to raise the symbiote and prepare the lodestone; priceless to outside powers such as the Federation of Magic, Psyscape or Lazlo.', 'Model Ao Pua. Almond-shaped stone air-sub whose lid opens like a clam; near silent in air and water, VTOL, and able to dive into the sea at full speed. As with all Lemurian symbiotic vehicles the hull is Stone Magic lodestone around a living Symbiote Conduit that is power source, computer and co-pilot: psychic link with the pilot, flies alone at 60% with three attacks and no bonuses (untrained pilots also 60%), locks out strangers, and sustains air indefinitely. Pilots use the Symbiote Conduit Combat Vehicle skill. A depleted force field recharges in 3 hours on a ley line, 1.5 hours at a nexus or stone pyramid, or at 2 P.P.E. per M.D.C. point. Cargo: about 4x6x6 feet behind the seat if no passenger rides. The conduit lives 100 years and must charge 3 hours on a ley line (1.5 hours at a nexus or pyramid) every seven days, or weapons and torpedo recharging fail and speed drops to 300 mph air, 40 mph surface, 30 mph underwater.', 'Rifts World Book 32: Lemuria p.147-148'),
  ('lemurian-cloud-wind', 'Cloud Wind (Flying Submersible Transport)', 'rifts', 'Flying Submersible Transport', 'Six: captain, communication officer (usually a Mind Melter or other telepath), tactical officer or spell caster, pilot, co-pilot and an advisor (Biomancer, Sea Inquisitor, second Mind Melter, Scout, etc.). Can run with as few as three. Half or more of a full crew wear Bio-Armor.', 'Dormitory bunks for up to 12 in the cargo hold; the cargo bay can instead take an extra 24 passengers or troops (18 in heavy Bio-Armor).', 'Not possible.', 'Mach 2 (1,540 mph/2,464 km); hovers and takes off or lands vertically. Within 15 feet (4.6 m) of the ground or water surface: up to 500 mph (800 km).', 'Underwater 80 mph (128 km or 69 knots) maximum. Maximum depth 5 miles (8 km).', 'Height 30 feet (9.1 m), width 160 feet (48 m), length 120 feet (36 m).', '50 tons', 920, 1, NULL, 30000000, '30 million credits to raise the symbiote and prepare the lodestone.', 'Model Ao Maani. Stone troop and cargo carrier shaped like a tailless manta ray; it can open gaps in its drive field so troops, small craft, probes, missiles and torpedoes leave or enter while under way, and often lies powered down on the sea bed as a command post or field hospital. As with all Lemurian symbiotic vehicles the hull is Stone Magic lodestone around a living Symbiote Conduit that is power source, computer and co-pilot: psychic link with the crew, flies alone at 60% with three attacks and no bonuses, locks out strangers, sustains air indefinitely. A depleted force field recharges in 3 hours on a ley line, 1.5 hours at a nexus or stone pyramid, or at 2 P.P.E. per M.D.C. point. Aboard: 6 crew rooms, a mess hall seating five, medical station, armory, and a bay holding a Serpent Hunter with sea serpent, 4 Wind Seers, 2 Scuttlers or 2 Sea Darts. The conduit lives 100 years and must charge 24 hours on a ley line (12 at a nexus or pyramid) every seven days, or weapons and torpedo recharging fail and speed drops to 100 mph air, 30 mph on or under water.', 'Rifts World Book 32: Lemuria p.148-150'),
  ('lemurian-wave-shadow-submarine', 'Wave Shadow Submarine', 'rifts', 'All-Purpose Combat Submarine', '12: captain, second officer, communications officer, sensor operator, 2 engineers, 4 gunners and two specialists (Biomancer, Sea Inquisitor, Mind Melter, Scout, etc.).', 'Standard troops: two infantry platoons (80 warriors in light to medium Bio-Armor), one heavy combat squad (10 in heavy Bio-Armor), one reconnaissance squad (Scouts, Biomancers, other mages and/or psychics) and 1-4 Serpent Hunters with their sea serpents. The Serpent Hunters may give way to a medical platoon and a volunteer platoon on rescue missions.', 'Not possible.', 'Not possible.', 'Surface 40 mph (64 km); underwater 60 mph (96 km) maximum. Maximum depth 5 miles (8 km).', 'Height 42 feet (12.8 m), width 100 feet (30.5 m), length 340 feet (103 m).', '2,200 tons', NULL, 1, NULL, 70000000, '70-80 million credits to raise the symbiotes and prepare the lodestone.', 'Lemuria''s commonest full-size submarine and mobile command base, built like a giant Cloud Shell. It carries 4 Cloud Shells, 8-10 Sea Darts, 6 Scuttlers, 2 Cloud Winds and 6 Wind Seers (half to two-thirds fewer on cargo or rescue runs) and up to 500 tons of cargo. As with all Lemurian symbiotic vehicles the hull is Stone Magic lodestone and living Symbiote Conduits are power source, computer and co-pilot: psychic link with the crew, able to run the ship at 60% with three attacks and no bonuses, locking out strangers and sustaining air indefinitely. It has three symbiotes, one per section; all three must die to shut it down. A depleted force field recharges in 3 hours on a ley line, 1.5 hours at a nexus or stone pyramid, or at 2 P.P.E. per M.D.C. point. The conduits live 100 years and must charge 48 hours on a ley line (24 at a nexus or pyramid) every ten days, or weapons and torpedo recharging fail and speed drops to 30 mph.', 'Rifts World Book 32: Lemuria p.150-151'),
  ('lemurian-scuttler-submersible-tank', 'Scuttler Submersible Tank', 'rifts', 'Submersible Amphibious Armored Vehicle', 'One, with room for one gunner.', 'Two passengers/troops.', '60 mph (96 km).', 'Not possible.', 'Surface 60 mph (96 km); underwater 35 mph (56 km). Maximum depth 4 miles (6.4 km).', 'Height 8 feet (2.4 m), width 10 feet (3 m), length 22 feet (6.7 m).', '8 tons', 320, 1, NULL, 4000000, '4 million credits to raise the symbiote and prepare the lodestone.', 'Compact, heavily armored stone sub used as a tank for city defense, raids and beach assaults; slow, so Cloud Winds or Wave Shadows carry it to the fight. A rippling propulsion skirt drives it underwater and rides a cushion of air on land like a hover tank. Its TK projector equals Robotic P.S. 40. As with all Lemurian symbiotic vehicles the hull is Stone Magic lodestone around a living Symbiote Conduit that is power source, computer and co-pilot: psychic link with the pilot, drives alone at 60% with three attacks and no bonuses (untrained pilots also 60%), locks out strangers, sustains air indefinitely. A depleted force field recharges in 3 hours on a ley line, 1.5 hours at a nexus or stone pyramid, or at 2 P.P.E. per M.D.C. point. Cargo: a rifle, pistol and survival gear. The conduit lives 100 years and must charge 2 hours on a ley line (1 at a nexus or pyramid) every seven days, or weapons fail and speed drops to 20 mph on land or underwater.', 'Rifts World Book 32: Lemuria p.152-153'),
  ('lemurian-wind-seer', 'Wind Seer', 'rifts', 'Unmanned Sensor Probe and Assassin Drone', 'None; unmanned.', NULL, 'Not possible.', 'Mach 1 (770 mph/1,232 km); hovers and takes off or lands vertically. Within 3 feet (0.9 m) of the ground or water surface: up to 500 mph (800 km). On patrol or observing it usually stays under 50 mph (80 km).', 'Underwater 100 mph (160 km) maximum. Maximum depth 8 miles (12.8 km).', 'Sphere 3.5 feet (1 m) in diameter.', '550 lbs (248 kg)', 90, 1, NULL, 2000000, '2 million credits to raise the symbiote and prepare the lodestone.', 'Pilotless stone orb: a Symbiote Conduit in a spherical shell, used as probe, sentry and assassin drone. Lightly armed, it tails and watches targets or guards sites and relays what it senses to the pilot of a larger vehicle; silent, unobtrusive, and the deepest diver of the family, so it scouts ocean trenches. As with all Lemurian symbiotic vehicles the shell is Stone Magic lodestone and the living symbiote is power source and brain, acting on its own with three attacks, no bonuses and 60% piloting. A depleted force field recharges in 3 hours on a ley line, 1.5 hours at a nexus or stone pyramid, or at 2 P.P.E. per M.D.C. point. No cargo. The conduit lives 100 years and must charge 2 hours on a ley line (1 at a nexus or pyramid) every seven days, or its weapon fails and speed drops to 100 mph in the air and 30 mph underwater.', 'Rifts World Book 32: Lemuria p.153-154'),
  ('lemurian-moai-stone-guardian', 'Moai Stone Guardian', 'rifts', 'Stone guardian (piloted magical stone automaton)', 'Optional. It can be given orders and sent off, led by spoken or telepathic commands, or piloted from inside the head. The commander or pilot must be Lemurian, of Principled or Scrupulous alignment, and know the secret activation and command words.', 'Small Moai: pilot only (or one passive passenger instead). Large: pilot and two passengers. Giant: pilot and five passengers. Passengers must be of good or selfish alignment; evil characters cannot enter.', 'Running 40 mph (64 km), double along a ley line; the same along the ocean floor.', '60 mph (96 km), double along a ley line; maximum altitude 5 miles (8 km). Can hover in air and water.', '50 mph (80 km/43 knots) underwater, double along a ley line. Maximum depth 6 miles (9.6 km), for the Moai and anyone inside.', 'Small (64%): 13 feet (4 m) tall, 7.5 feet (2.3 m) wide at the shoulders, 6.6 feet (2 m) nose to back of head. Large (34%): 33 feet (10 m) tall, 16 feet (4.9 m) wide, 14 feet (4.3 m) long. Giant (2%, only 22 exist): 72 feet (21.9 m) tall, 34 feet (10.3 m) wide, 26 feet (7.9 m) long.', 'Small 14 tons; Large 82 tons; Giant 150 tons', NULL, 1, NULL, NULL, NULL, 'Easter Island''s giant-headed stone statues, magic automatons made to fight supernatural evil and the undead, in three sizes (Supernatural P.S. 27, 37 or 47). Who may operate one: a Lemurian Stone Master of 6th level or higher and good alignment, any member of the Lemurian royal family, or a trained Lemurian Moai pilot - always of pure Lemurian blood, Principled or Scrupulous, and knowing the secret command words. How: by voice or telepathy from outside (one leader can direct 1-7), or seated in the sealed head, where the statue moves as the pilot thinks; there are no controls and riders see through its eyes. Breaking into the sealed chamber takes 245 M.D.C. Unled, it fights as a four-attack automaton without human judgment. No cargo. Magic powered: a small Moai rests 8 hours on a ley line monthly, a large 16 hours every two weeks, a giant 24 hours weekly (half that at a nexus or ley line triangle). Unpowered, everything is halved for 1D4+1 days, then it freezes. Nobody can make new ones.', 'Rifts World Book 32: Lemuria p.29-32');

INSERT OR IGNORE INTO vehicle_locations (vehicle_slug, location, mdc, mdc_note, ordinal) VALUES
  ('lemurian-sea-dart-interceptor', 'Jet Thrusters (2, back)', 100, 'Each. If the rear thrusters are destroyed speed falls by 60%, but the craft still flies and moves through water.', 1),
  ('lemurian-sea-dart-interceptor', 'Force Field', 80, NULL, 2),
  ('lemurian-sea-dart-interceptor', 'Pilot Compartment/Symbiote', NULL, '6D6+30. Cannot be targeted until the main body and force field are both gone, except by a Called Shot while the vessel is open for the pilot. Killing the symbiote disables the craft until a new one is implanted.', 3),
  ('lemurian-sea-dart-interceptor', 'Main Body', 227, 'At zero the vehicle shuts down completely: it falls from the air or sinks.', 4),
  ('lemurian-cloud-shell', 'Stonecaster/Nose of the Vessel', 180, NULL, 1),
  ('lemurian-cloud-shell', 'Pilot Compartment/Symbiote', NULL, '6D6+50. Cannot be targeted until the main body and force field are both gone, except by a Called Shot while the vessel is open for a passenger or the pilot. Killing the symbiote disables the craft until a new one is implanted.', 2),
  ('lemurian-cloud-shell', 'Force Field', 120, NULL, 3),
  ('lemurian-cloud-shell', 'Main Body', 300, 'At zero the vehicle shuts down completely: it falls from the air or sinks.', 4),
  ('lemurian-cloud-wind', 'Front Launch Bay Door', 300, NULL, 1),
  ('lemurian-cloud-wind', 'Rear Cargo Door', 225, NULL, 2),
  ('lemurian-cloud-wind', 'Wings (2)', 250, 'Each. The wings hold the torpedoes and missiles.', 3),
  ('lemurian-cloud-wind', 'Symbiote', NULL, '1D6x10+40. Cannot be targeted until the main body and force field are both gone, except by a Called Shot while the vessel is open for a passenger or the pilot. Killing the symbiote disables the craft until a new one is implanted.', 4),
  ('lemurian-cloud-wind', 'Force Field', 200, NULL, 5),
  ('lemurian-cloud-wind', 'Main Body', 920, 'At zero the vehicle shuts down completely: it falls from the air or sinks.', 6),
  ('lemurian-wave-shadow-submarine', 'Main Cannon (1)', 180, NULL, 1),
  ('lemurian-wave-shadow-submarine', 'Stonecasters (2)', 135, 'Each.', 2),
  ('lemurian-wave-shadow-submarine', 'Pilot Compartment/Symbiotes (3)', NULL, '6D6+60. One Symbiote Conduit sits in each main section and cannot be targeted until that section''s main body and the force field have each been destroyed; then a Called Shot can hit it. Killing it disables that section until a new symbiote is implanted.', 3),
  ('lemurian-wave-shadow-submarine', 'Force Field (Main Body)', 200, NULL, 4),
  ('lemurian-wave-shadow-submarine', 'Main Body: Forward Section', 470, 'At zero the stonecasters (printed as ''three'') and torpedo launchers are knocked out.', 5),
  ('lemurian-wave-shadow-submarine', 'Main Body: Mid-Section', 440, 'At zero the ion weapon is knocked out, 2D4x10% of the troops and cargo spill into the sea, and speed falls by 30%.', 6),
  ('lemurian-wave-shadow-submarine', 'Main Body: Rear Section', 460, 'At zero speed falls by 50%. Losing all M.D.C. in every section destroys the submarine and it sinks.', 7),
  ('lemurian-scuttler-submersible-tank', 'Stone Cannon', 135, 'Small, difficult target: needs a Called Shot, and the shot is still at -3 to strike.', 1),
  ('lemurian-scuttler-submersible-tank', 'Pilot Compartment/Symbiote', NULL, '6D6+50. Cannot be targeted until the main body and force field are both gone, except by a Called Shot while the vessel is open for a passenger or the pilot. Killing the symbiote disables the tank until a new one is implanted.', 2),
  ('lemurian-scuttler-submersible-tank', 'Force Field', 120, NULL, 3),
  ('lemurian-scuttler-submersible-tank', 'Main Body', 320, 'At zero the vehicle shuts down completely: it stops dead on land or sinks.', 4),
  ('lemurian-wind-seer', 'Symbiote', NULL, '6D6+12. A hard target: the force field and the main body shell must both be destroyed before it can be harmed. Killing it disables the drone until a new symbiote is implanted.', 1),
  ('lemurian-wind-seer', 'Force Field', 50, NULL, 2),
  ('lemurian-wind-seer', 'Main Body', 90, 'At zero the drone shuts down completely.', 3),
  ('lemurian-moai-stone-guardian', 'Small Moai: Head', 400, 'Destroying the head shatters the Moai into 1D6+1 pieces; see the Ley Line Healing entry.', 1),
  ('lemurian-moai-stone-guardian', 'Small Moai: Arms (2)', 110, 'Each.', 2),
  ('lemurian-moai-stone-guardian', 'Small Moai: Hands (2)', 50, 'Each.', 3),
  ('lemurian-moai-stone-guardian', 'Small Moai: Legs (2)', 150, 'Each.', 4),
  ('lemurian-moai-stone-guardian', 'Small Moai: Main Body', 330, 'At zero the Moai shuts down, falls on its face and expels anyone inside.', 5),
  ('lemurian-moai-stone-guardian', 'Large Moai: Head', 1100, 'Destroying the head shatters the Moai into 1D6+1 pieces.', 6),
  ('lemurian-moai-stone-guardian', 'Large Moai: Arms (2)', 220, 'Each.', 7),
  ('lemurian-moai-stone-guardian', 'Large Moai: Hands (2)', 95, 'Each.', 8),
  ('lemurian-moai-stone-guardian', 'Large Moai: Legs (2)', 300, 'Each.', 9),
  ('lemurian-moai-stone-guardian', 'Large Moai: Main Body', 900, 'At zero the Moai shuts down, falls on its face and expels anyone inside.', 10),
  ('lemurian-moai-stone-guardian', 'Giant Moai: Head', 2000, 'Destroying the head shatters the Moai into 1D6+1 pieces.', 11),
  ('lemurian-moai-stone-guardian', 'Giant Moai: Arms (2)', 330, 'Each.', 12);

INSERT OR IGNORE INTO vehicle_locations (vehicle_slug, location, mdc, mdc_note, ordinal) VALUES
  ('lemurian-moai-stone-guardian', 'Giant Moai: Hands (2)', 140, 'Each.', 13),
  ('lemurian-moai-stone-guardian', 'Giant Moai: Legs (2)', 560, 'Each.', 14),
  ('lemurian-moai-stone-guardian', 'Giant Moai: Main Body', 1700, 'At zero the Moai shuts down, falls on its face and expels anyone inside.', 15);

INSERT OR IGNORE INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note) VALUES
  ('lemurian-sea-dart-interceptor', 1, 'Ionic Charge Imbalancer', '5D6 M.D. per blast', 1, '1,500 feet (457 m) in all environments; double on or within one mile (1.6 km) of a ley line or nexus point', 'Each blast counts as one melee attack/action.', 'Effectively unlimited as long as the vessel is charged.', NULL, 'Ion pulses channelled through the drive; fires 360 degrees without turning the craft. Assault and anti-aircraft.'),
  ('lemurian-sea-dart-interceptor', 2, 'Symbiotic Living Torpedoes', '2D6 M.D. warning shot, 4D6 M.D. full strength, or 1D4x10+2 M.D. power attack (uses both of the torpedo''s attacks). Suicide detonation: 2D4x10 M.D.', 1, 'About 4,000 feet (1,219 m) per melee round; chases a target up to 4 miles (6.4 km)', 'Launching one counts as one of the pilot''s melee attacks; the torpedo then has two attacks of its own before returning.', 'Two re-useable Living Torpedoes.', '+3 to strike', 'Living fish launched from the belly; water and underwater targets only, and the pilot can retarget them. Each has 25 M.D.C., top speed 120 mph (192 km/104 knots), +5 automatic dodge, Prowl 50%, and does not show on sonar or radar. Returns at half speed and recharges in one minute (4 melee rounds). A suicide order is obeyed 01-90% and destroys the torpedo. Double damage to the undead. If the vessel is gone it waits 1D4+2 days, then swims off.'),
  ('lemurian-sea-dart-interceptor', 3, 'Sea Dart Symbiote and Repairs', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. With the craft stopped (hovering or landed) the symbiote remoulds the hull, restoring 2D6 M.D.C. each melee round. Its own body regains 2D6 M.D.C. every 24 hours; magical healing also works on it.'),
  ('lemurian-sea-dart-interceptor', 4, 'Sensor System (psychic)', NULL, 0, '1,000 feet (305 m); double along ley lines', NULL, NULL, NULL, 'Not a weapon. No conventional sensors: the symbiote uses Empathy (4), Presence Sense (4), See the Invisible (4), Sense Dimensional Anomaly (4), Sense Time (2), Sixth Sense (2) and Telepathy (4). Base I.S.P. 1D6x10+33.'),
  ('lemurian-cloud-shell', 1, 'Stonecaster Gun (Nose Weapon)', 'Sedimentary: 4D6 M.D. to everything in an 8 foot (2.4 m) blast radius. Igneous: 5D6 M.D. on impact and 2D6 M.D. for the next 1D4 melee rounds. Metamorphic: 1D4x10+4 M.D.', 1, '4,000 feet (1,219 m), half underwater', 'Each shot counts as one melee attack.', '60 rounds; regenerates two rounds per hour. Payload and regeneration double inside a ley line triangle such as the Demon Sea; payload quadruples on a ley line, at a nexus or at a Lemurian stone pyramid.', NULL, 'Fixed forward. Stone Magic makes the rock chips it fires. Anti-submarine/anti-sea monster, secondarily anti-ship.'),
  ('lemurian-cloud-shell', 2, 'Ionic Charge Imbalancer', '1D4x10 M.D. per blast', 1, '1,500 feet (457 m) in all environments; double on or within one mile of a ley line or nexus point', 'Each blast counts as one melee attack/action.', 'Effectively unlimited as long as the vessel is charged.', NULL, 'The drive''s ionising effect boosted into a lightning-like stream; fires 360 degrees without turning the craft. Assault and anti-aircraft.'),
  ('lemurian-cloud-shell', 3, 'Symbiotic Living Torpedoes', '2D6 M.D. warning shot, 4D6 M.D. full strength, or 1D4x10+2 M.D. power attack (uses both of the torpedo''s attacks). Suicide detonation: 2D4x10 M.D.', 1, 'About 4,000 feet (1,219 m) per melee round; chases a target up to 4 miles (6.4 km)', 'One at a time or in volleys of two or four; a launch or volley counts as one of the pilot''s melee attacks. Each torpedo then has two attacks of its own.', 'Six re-useable Living Torpedoes.', '+3 to strike', 'Same as the Sea Dart Interceptor''s apart from rate of fire and payload: living fish, water targets only, 25 M.D.C., 120 mph, +5 automatic dodge, Prowl 50%, invisible to sonar and radar, one minute to recharge aboard, suicide order obeyed 01-90%, double damage to the undead.'),
  ('lemurian-cloud-shell', 4, 'Cloud Shell Symbiote and Repairs', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. With the craft stopped (hovering, floating, on land or on the sea floor) the symbiote remoulds the hull, restoring 2D6 M.D.C. each melee round. Its own body regains 3D6 M.D.C. every 24 hours; magical healing also works on it.'),
  ('lemurian-cloud-shell', 5, 'Sensor System (psychic)', NULL, 0, '1,000 feet (305 m); double along ley lines', NULL, NULL, NULL, 'Not a weapon. As the Sea Dart: Empathy (4), Presence Sense (4), See the Invisible (4), Sense Dimensional Anomaly (4), Sense Time (2), Sixth Sense (2) and Telepathy (4). Base I.S.P. 2D4x10+28.'),
  ('lemurian-cloud-wind', 1, 'Ionic Charge Imbalancer', '1D6x10 M.D. per blast', 1, '1,500 feet (457 m) in all environments; double on or within one mile (1.6 km) of a ley line or nexus point', 'Each blast counts as one melee attack.', 'Effectively unlimited as long as the vessel is charged.', NULL, 'Lightning bolts from the larger drive; fires 360 degrees without turning the craft. Assault and anti-aircraft.'),
  ('lemurian-cloud-wind', 2, 'Symbiotic Living Torpedoes', '2D6 M.D. warning shot, 4D6 M.D. full strength, or 1D4x10+2 M.D. power attack (uses both of the torpedo''s attacks). Suicide detonation: 2D4x10 M.D.', 1, 'About 4,000 feet (1,219 m) per melee round; chases a target up to 4 miles (6.4 km)', 'One at a time or in volleys of two or four; a launch or volley counts as one of the pilot''s melee attacks. Each torpedo then has two attacks of its own.', '12 re-useable Living Torpedoes.', '+3 to strike', 'Same as the Sea Dart Interceptor''s apart from rate of fire and payload: living fish, water targets only, 25 M.D.C., 120 mph, +5 automatic dodge, Prowl 50%, invisible to sonar and radar, one minute to recharge aboard, suicide order obeyed 01-90%, double damage to the undead.'),
  ('lemurian-cloud-wind', 3, 'Mini-Missile Launchers (2)', 'Varies with missile type; plasma is favored: 1D6x10 M.D. to a 15 foot (4.6 m) radius', 1, 'One mile (1.6 km)', 'One at a time or in volleys of 2, 4, 6 or 8.', '36 total mini-missiles, 16 in each wing (as printed).', NULL, 'One conventional human-tech launcher hidden in each wing, used from the water surface against aircraft, and from the air against land or air targets. Anti-aircraft/flyers, secondarily anti-missile and defense.'),
  ('lemurian-cloud-wind', 4, 'Seaweed Chaff', NULL, 0, 'Fills a 60 foot (18.3 m) diameter sphere', NULL, '8 seaweed bundles.', NULL, 'Defensive; works only underwater or on the surface. Swimmers touching the cloud take the Seaweed Bloom spell''s penalties and propellers are likely to foul and stall. A torpedo of any size (mini to long range) passing through has a 01-70% chance to detonate or lose lock; if one in a volley detonates, 01-90% all the rest do too, otherwise only 1D4x10% of them. An onboard Biomancer can enlarge the cloud with Seaweed Bloom.'),
  ('lemurian-cloud-wind', 5, 'Troops', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. Carried troops can leave the vehicle while it is moving, at a reasonable speed, to join a fight or attack.'),
  ('lemurian-cloud-wind', 6, 'Cloud Wind Symbiote and Repairs', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. With the craft stopped (hovering, floating, on land or on the sea floor) the symbiote remoulds the hull, restoring 3D6 M.D.C. each melee round. Its own body regains 3D6 M.D.C. every 24 hours; magical healing also works on it.'),
  ('lemurian-cloud-wind', 7, 'Sensor System (psychic)', NULL, 0, '1,000 feet (305 m); double along ley lines', NULL, NULL, NULL, 'Not a weapon. As the Sea Dart: Empathy (4), Presence Sense (4), See the Invisible (4), Sense Dimensional Anomaly (4), Sense Time (2), Sixth Sense (2) and Telepathy (4), plus Read Dimensional Portal (6). Base I.S.P. 2D4x10+40.'),
  ('lemurian-wave-shadow-submarine', 1, 'Main Gun Stonecaster Cannon (1)', 'Sedimentary: 6D6 M.D. to everything in a 20 foot (6.1 m) blast radius. Igneous: 1D6x10 M.D. on impact and 3D6 M.D. more for the next 1D4 melee rounds. Metamorphic: 2D6x10 M.D.', 1, '4,000 feet (1,219 m), half underwater', 'Each shot counts as one melee attack/action of its dedicated gunner (typically 4-5 attacks per melee round).', '100 shells; regenerates two rounds per hour. Payload and regeneration double inside a ley line triangle such as the Demon Sea; payload triples on a ley line, at a nexus or at a Lemurian stone pyramid.', NULL, 'Oversized stonecaster firing enchanted mini-boulders from a turret: 360 degree rotation, 90 degree arc up and down. Anti-ship, secondarily anti-submarine/anti-sea monster.'),
  ('lemurian-wave-shadow-submarine', 2, 'Standard Stonecaster Cannons (2)', 'Sedimentary: 5D6 M.D. to everything in an 8 foot (2.4 m) blast radius. Igneous: 1D4x10 M.D. on impact and 2D6 M.D. more for the next 1D4 melee rounds. Metamorphic: 2D4x10 M.D.', 1, '4,000 feet (1,219 m), half underwater', 'Each shot counts as one melee attack/action.', '100 rounds each; regenerates two rounds per hour. Payload and regeneration double inside a ley line triangle such as the Demon Sea; payload triples on a ley line, at a nexus or at a Lemurian stone pyramid.', NULL, 'Secondary guns, one gunner each: 360 degree rotation, 45 degree arc up and down. Anti-submarine/anti-sea monster, secondarily anti-ship.'),
  ('lemurian-wave-shadow-submarine', 3, 'Symbiotic Living Torpedoes', '2D6 M.D. warning shot, 4D6 M.D. full strength, or 1D4x10+2 M.D. power attack (uses both of the torpedo''s attacks). Suicide detonation: 2D4x10 M.D.', 1, 'About 4,000 feet (1,219 m) per melee round; chases a target up to 4 miles (6.4 km)', 'One at a time or in volleys of two or four; a launch or volley counts as one melee attack. Each torpedo then has two attacks of its own.', '16 total: eight re-useable Living Torpedoes in the launcher on each side.', '+3 to strike', 'Fired by the captain or second officer. Otherwise the same as the Sea Dart Interceptor''s: living fish, water targets only, 25 M.D.C., 120 mph, +5 automatic dodge, Prowl 50%, invisible to sonar and radar, one minute to recharge aboard, suicide order obeyed 01-90%, double damage to the undead.'),
  ('lemurian-wave-shadow-submarine', 4, 'Underwater Proximity Ionic Charge Imbalancer', '5D6 M.D. per discharge', 1, '100 feet (30.5 m); double on a ley line', 'Each blast/discharge counts as one melee attack of its dedicated gunner.', 'Effectively unlimited as long as the vessel is charged.', NULL, 'Close defense: the drive floods nearby water with ion energy, against boarders and small subs latching on. Defense, secondarily anti-submarine/anti-sea monster.'),
  ('lemurian-wave-shadow-submarine', 5, 'Seaweed Chaff', NULL, 0, NULL, NULL, '8 seaweed bundles.', NULL, 'The same system as the Cloud Wind''s: a 60 foot (18.3 m) seaweed cloud that hampers swimmers as the Seaweed Bloom spell, fouls propellers, and gives torpedoes a 01-70% chance to detonate or lose lock (01-90% the rest of a volley follows, else 1D4x10% of it).'),
  ('lemurian-wave-shadow-submarine', 6, 'Troops', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. Carried troops can leave the sub while it is moving, at a reasonable speed, to join a fight or attack.'),
  ('lemurian-wave-shadow-submarine', 7, 'Wave Shadow Symbiotes and Repairs', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon (headed ''Shadow Wave'' in the book). Each section is repaired by its own symbiote with the sub at 10 mph (16 km) or less, floating still or on the sea floor: 3D6 M.D.C. each melee round. Its own body regains 3D6 M.D.C. every 24 hours; magical healing also works on it.'),
  ('lemurian-wave-shadow-submarine', 8, 'Sensor System (psychic)', NULL, 0, '1,000 feet (305 m); double along ley lines', NULL, NULL, NULL, 'Not a weapon. As the Sea Dart: Empathy (4), Presence Sense (4), See the Invisible (4), Sense Dimensional Anomaly (4), Sense Time (2), Sixth Sense (2) and Telepathy (4), plus Read Dimensional Portal (6). Base I.S.P. 2D4x10+40.'),
  ('lemurian-scuttler-submersible-tank', 1, 'Stonecaster Cannon', 'Sedimentary: 5D6 M.D. to everything in an 8 foot (2.4 m) blast radius. Igneous: 1D4x10 M.D. on impact and 2D6 M.D. more for the next 1D4 melee rounds. Metamorphic: 2D4x10 M.D.', 1, '4,000 feet (1,219 m), half underwater', 'Each shot counts as one melee attack/action.', '100 rounds; regenerates two rounds per hour. Payload and regeneration double inside a ley line triangle such as the Demon Sea; payload triples on a ley line, at a nexus or at a Lemurian stone pyramid.', NULL, 'Main gun with its own gunner: 360 degree rotation, 45 degree arc up and down. Sedimentary rounds shatter into a blast, igneous rounds are lava pellets that keep burning, metamorphic rounds are dense armor-piercers. Anti-submarine/anti-sea monster, secondarily anti-ship.'),
  ('lemurian-scuttler-submersible-tank', 2, 'TK Defense', '1D6 M.D. per punch; Power TK-punch 2D6 M.D. (counts as two melee attacks); restrained TK-punch 3D6 S.D.C.', 1, '50 feet (15.2 m) in all environments', 'Each TK attack counts as one melee attack/action of the pilot.', 'Effectively unlimited.', '+1 to strike and parry giant-sized opponents; +1 to block/hit a volley of incoming missiles or torpedoes', 'Experimental telekinetic ''invisible hands'' that punch, block and parry; usable only against opponents 10 feet (3 m) tall or larger, never man-sized targets, and not as a standing wall or shield. Primary purpose is listed as an inertial dampening system. A blocked missile or torpedo volley has a 01-33% chance to explode on impact or veer off, and a deflected volley may strike an ally or cause collateral damage.'),
  ('lemurian-scuttler-submersible-tank', 3, 'Spined Fins', '1D6 M.D. to attackers climbing or holding on (they may attempt to dodge); 3D6 M.D. to sea serpents, squid and giants gripping the tank in jaws, hands or tentacles', 1, NULL, NULL, NULL, NULL, 'A pair of internal spined ridges that extend through the armor and sweep in wide circles like a buzz saw, to throw off melee attackers and anything trying to swallow the tank.'),
  ('lemurian-scuttler-submersible-tank', 4, 'Scuttler Symbiote and Repairs', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. With the tank stopped (hovering, floating, on land or on the sea floor) the symbiote remoulds the hull, restoring 2D6 M.D.C. each melee round. Its own body regains 3D6 M.D.C. every 24 hours; magical healing also works on it.'),
  ('lemurian-scuttler-submersible-tank', 5, 'Sensor System (psychic)', NULL, 0, '1,000 feet (305 m); double along ley lines', NULL, NULL, NULL, 'Not a weapon. As the Sea Dart: Empathy (4), Presence Sense (4), See the Invisible (4), Sense Dimensional Anomaly (4), Sense Time (2), Sixth Sense (2) and Telepathy (4), plus TK Defense at no extra I.S.P. cost. Base I.S.P. 1D6x10+33.'),
  ('lemurian-wind-seer', 1, 'Ionic Charge Imbalancer', '2D6 M.D. per blast', 1, '500 feet (152 m) in all environments; double on or within one mile of a ley line or nexus point', 'Each blast counts as one melee attack/action.', 'Effectively unlimited as long as the vessel is charged.', NULL, 'Electric bolts drawn from the drive; fires 360 degrees. Assault and anti-aircraft.'),
  ('lemurian-wind-seer', 2, 'Wind Seer Symbiote and Repairs', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. With the drone stopped (hovering or landed) the symbiote remoulds the shell, restoring 2D6 M.D.C. each melee round. Its own body regains 2D6 M.D.C. every 24 hours; magical healing also works on it.'),
  ('lemurian-wind-seer', 3, 'Sensor System (psychic)', NULL, 0, '1,000 feet (305 m); double along ley lines', NULL, NULL, NULL, 'Not a weapon. Empathy (4), Mind Block (4), Presence Sense (4), Read Dimensional Portal (6), See the Invisible (4), Sense Dimensional Anomaly (4), Sense Evil (2), Sense Magic (3), Sense Time (2), Sixth Sense (2) and Telepathy (4). Base I.S.P. 2D4x10+36.'),
  ('lemurian-moai-stone-guardian', 1, 'Breath Attack', '4D6 M.D. against supernatural evil, or 4D6 S.D.C. against mortal foes', 1, '100 feet (30.5 m)', NULL, NULL, NULL, 'A jet of steam from the mouth. Like every Moai attack it does double damage to Necromancers, animated dead, vampires and all undead.'),
  ('lemurian-moai-stone-guardian', 2, 'Eye Beams', 'Small Moai: 4D6 M.D. vs supernatural evil, 1D6x10 M.D. vs greater supernatural evil and deities, 3D6 M.D. vs other M.D.C. opponents. Large: 6D6 M.D., 2D6x10 M.D., 4D6 M.D. Giant: 1D6x10 M.D., 3D6x10 M.D., 6D6 M.D. Against mortal and S.D.C. targets: 1D6 to 5D6 S.D.C., set in 1D6 steps.', 1, '3,000 feet (914 m)', 'Four as an automaton, or the pilot''s number of attacks; each eye blast counts as one attack.', 'Effectively unlimited.', NULL, 'Energy blasts from the eyes. Double damage to Necromancers, animated dead, vampires and all undead.'),
  ('lemurian-moai-stone-guardian', 3, 'Hand to Hand Combat', 'Punches, kicks and head butts by Supernatural P.S. (Small 27, Large 37, Giant 47); double damage to greater supernatural beings', 1, NULL, 'Automaton: four attacks per melee round. Piloted: the pilot''s attacks +2.', NULL, 'Automaton vs supernatural evil: +5 Perception, +3 initiative, +6 strike, +4 parry, +2 dodge, +4 pull punch, +2 roll with impact; halve (round down) vs mortals. Piloted: pilot''s own bonuses plus +2 Perception (double vs supernatural evil), +2 initiative, +2 strike and parry, +3 pull punch, +2 roll with impact, +4 save vs Horror Factor, +3 save vs possession and mind control.', 'The Moai itself is immune to Horror Factor and to every kind of possession or outside control, though its pilot is not. Piloted, it answers at the speed of thought and uses the pilot''s attacks and moves. Double damage to the undead as with all its attacks.'),
  ('lemurian-moai-stone-guardian', 4, 'Ley Line Healing', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. Needs rest mode on a ley line, nexus, ley line triangle or Easter Island. If the main body is at zero but the head has any M.D.C. left, it regrows 1D6x10 main body M.D.C. per hour and reactivates after the first 10; head, then limbs, heal only once the main body is whole. A head destroyed on a ley line, nexus or Easter Island reforms after 48 hours, one piece per hour, then heals the same way; destroyed elsewhere it is lost unless the pieces go back to Easter Island for a Stone Master ritual.'),
  ('lemurian-moai-stone-guardian', 5, 'Resistance to Magic', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. Immune to possession and to magic fire, heat and lava. Magic cold does half damage. Electricity, lightning, other magic energy, physical attacks, missiles and high-tech weapons do full damage.'),
  ('lemurian-moai-stone-guardian', 6, 'Spell Casting Through the Moai (Voice of the Moai)', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. One rider at a time, usually the pilot, speaks through the statue in a deep baritone and may cast most spoken spells and Whale Songs through it: spell range doubled, spell damage +50%. Barred: rituals, Temporal Magic, Create Zombie, Animate and Control Dead, Metamorphosis, disguise, concealment and illusion magic, Necromancy, Demon Magic, Soulmancy and any dark magic; no Techno-Wizard devices, magic items, wards or circles, and nothing needing a delicate touch.'),
  ('lemurian-moai-stone-guardian', 7, 'Senses', NULL, 0, NULL, NULL, NULL, NULL, 'Not a weapon. Hearing and touch equal a human''s; smell about twice as keen. Full color supernatural vision: can pick out a bird 6 miles (9.6 km) off on the horizon, sees in total darkness to one mile (1.6 km), and sees the invisible, including Astral Travelers and fragmented essences of Alien Intelligences.'),
  ('lemurian-moai-stone-guardian', 8, 'Sense Ley Line Location', NULL, 0, '30 miles (48 km)', NULL, NULL, NULL, 'Not a weapon. Lets the Moai find ley lines to recharge.');

INSERT OR IGNORE INTO vehicle_weapons (vehicle_slug, ordinal, name, damage, is_mega_damage, range, rate_of_fire, payload, bonus, note) VALUES
  ('lemurian-moai-stone-guardian', 9, 'Sense the Supernatural', NULL, 0, '100 miles (160 km)', NULL, NULL, NULL, 'Not a weapon. Instantly senses supernatural evil and begins a deep ''singing'' moan, audible island-wide yet carrying roughly one mile (1.6 km) over the water; on its master''s order it then hunts the intruder. Asked, the statues standing guard on Easter Island can name the kind of menace, its rough position within 1,000 miles (1,600 km) and its heading; great gatherings of evil are felt out to 5,000 miles (8,000 km). No evil supernatural force has got closer to the island than 10 miles (16 km).');

-- Read the result back. This script asserts its OWN rows and nothing else.
SELECT 'all 7 machines are in' AS assertion, count(*) AS got, 7 AS want
  FROM vehicles WHERE slug IN ('lemurian-sea-dart-interceptor', 'lemurian-cloud-shell', 'lemurian-cloud-wind', 'lemurian-wave-shadow-submarine', 'lemurian-scuttler-submersible-tank', 'lemurian-wind-seer', 'lemurian-moai-stone-guardian');
SELECT 'their 43 locations are in' AS assertion, count(*) AS got, 43 AS want
  FROM vehicle_locations WHERE vehicle_slug IN ('lemurian-sea-dart-interceptor', 'lemurian-cloud-shell', 'lemurian-cloud-wind', 'lemurian-wave-shadow-submarine', 'lemurian-scuttler-submersible-tank', 'lemurian-wind-seer', 'lemurian-moai-stone-guardian');
SELECT 'their 41 weapon entries are in' AS assertion, count(*) AS got, 41 AS want
  FROM vehicle_weapons WHERE vehicle_slug IN ('lemurian-sea-dart-interceptor', 'lemurian-cloud-shell', 'lemurian-cloud-wind', 'lemurian-wave-shadow-submarine', 'lemurian-scuttler-submersible-tank', 'lemurian-wind-seer', 'lemurian-moai-stone-guardian');
SELECT 'each main body location equals mdc_main_body' AS assertion, count(*) AS got, 0 AS want
  FROM vehicles v JOIN vehicle_locations l ON l.vehicle_slug = v.slug AND l.location = 'Main Body'
  WHERE v.slug IN ('lemurian-sea-dart-interceptor', 'lemurian-cloud-shell', 'lemurian-cloud-wind', 'lemurian-wave-shadow-submarine', 'lemurian-scuttler-submersible-tank', 'lemurian-wind-seer', 'lemurian-moai-stone-guardian') AND l.mdc IS NOT NULL AND v.mdc_main_body IS NOT NULL AND l.mdc <> v.mdc_main_body;

-- Records this run. See db/migrations/024-data-script-runs.sql.
INSERT INTO data_script_runs (filename) VALUES ('~175-lemuria-vehicles.sql');
